/* Scene-grounded reference algebra, V1.12.0.
 * Read-only scene facts -> bounded declarative queries -> goals -> existing skills.
 * No geometry, joint, trajectory or model weights. A language model may propose
 * this same query algebra; it cannot decide the matching IDs or fake success.
 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.JarvisSceneGrounding=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.12.0',SCHEMA='jarvis/scene_goal_proposal@1.0';
const clone=x=>JSON.parse(JSON.stringify(x)),norm=x=>String(x||'').normalize('NFKC').trim(),uniq=a=>[...new Set(a)];
const COLORS={red:['红色','红'],blue:['蓝色','蓝'],yellow:['黄色','黄'],green:['绿色','绿'],purple:['紫色','紫'],orange:['橙色','橙'],cyan:['青色','青'],white:['白色','白'],black:['黑色','黑']};
const PALETTE={red:[.88,.16,.20],blue:[.18,.48,.88],yellow:[.92,.72,.14],green:[.15,.65,.40],purple:[.66,.24,.76],orange:[.95,.43,.12],cyan:[.08,.70,.76],white:[.88,.90,.92],black:[.08,.10,.13]};
const TYPES={sphere:['圆球','球体','球'],box:['长方体','立方体','方块','工具箱','训练箱','箱子','盒子','箱','盒'],cylinder:['圆柱体','训练圆柱','圆柱','柱体'],cone:['圆锥体','训练圆锥','圆锥','锥体'],prism:['三棱柱','棱柱'],table:['工作台','桌子','桌'],bench:['休息长凳','长凳','凳子'],shelf:['储物架','书架','架子'],platform:['低平台','平台']};
const GENERIC=/(?:的|那一个|这一个|那个|这个|一个|一些|几件|那些|这些|东西|物体|物品|物件|道具|目标|训练|色|个|件|只|块|颗)/g;
const ALL=/(?:所有|全部|全都|统统|一切|每一个|每个|各个|都|逐个|依次|一一)/g;
const SPECIAL=/地上|地面|地板|桌|台面|架子|长凳|平台|所有|全部|全都|统统|每个|每一个|剩下|剩余|其余|其他|它们|这些|那些|同色|相同颜色|除了|多少|几个|哪些|最近|最远|人物(?:的)?[左右]|你(?:的)?[左右]|区域.{0,3}(?:内|里)/;
class GroundingError extends Error{constructor(code,message,detail={}){super(message);this.name='GroundingError';this.code=code;this.detail=detail;}}
const fail=(code,message,detail={})=>{throw new GroundingError(code,message,detail)};
const worldData=w=>{w=w?.world||w||{};return{...w,objects:w.objects||[],zones:w.zones||[],revision:w.revision??0}};
function number(s){if(/^\d+$/.test(s))return Number(s);const d={零:0,一:1,二:2,两:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9};if(s==='十')return 10;if(s.includes('十')){const[a,b]=s.split('十');return(d[a]||1)*10+(d[b]||0)}return d[s]??NaN;}
function height(o){return Number(o.h)||(o.shape==='sphere'?Number(o.r)*2:0);}
function halfSize(o){if(o.halfExtentsM&&o.q&&Math.abs(1-2*(o.q[0]**2+o.q[2]**2))<.9999)return [o.halfExtentsM[0],o.halfExtentsM[2]];return o.shape==='box'?[Number(o.w)/2||Number(o.r)||.1,Number(o.d)/2||Number(o.r)||.1]:[Number(o.r)||.1,Number(o.r)||.1];}
function radius(o){if(o.shape==='sphere')return Number(o.r)||.1;const[a,b]=halfSize(o);return o.shape==='box'||o.q&&Math.abs(1-2*(o.q[0]**2+o.q[2]**2))<.9999?Math.hypot(a,b):a;}
function yaw(o){return Number.isFinite(o.yaw)?o.yaw:2*Math.atan2(o.q?.[1]||0,o.q?.[3]||1);}
function kind(o){return ({worktable:'table',bench:'bench',shelf:'shelf',platform:'platform'})[o.templateId]||o.semanticType||o.shape;}
function portable(o){return o.movable!==false&&!['furniture','landmark','obstacle'].includes(o.category);}
function color(o){let c=o.color;if(typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c))c=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255);if(!Array.isArray(c))return null;return Object.keys(PALETTE).sort((a,b)=>PALETTE[a].reduce((s,x,i)=>s+(x-c[i])**2,0)-PALETTE[b].reduce((s,x,i)=>s+(x-c[i])**2,0))[0];}
function surface(o){if(o.q&&1-2*(o.q[0]**2+o.q[2]**2)<.9999)return null;if(o.supportSurface?.enabled===true&&Number.isFinite(o.supportSurface.height))return{...o.supportSurface,id:o.id,p:o.p,yaw:yaw(o),w:o.w,d:o.d,topY:o.supportSurface.height};if(['table','bench','platform'].includes(kind(o))&&o.shape==='box')return{id:o.id,topY:(o.p?.[1]||0)+height(o)/2,p:o.p,yaw:yaw(o),w:o.w,d:o.d};return null;}
function fitsSupport(o,s,margin=0){if(!s||!o.p)return false;const a=-s.yaw,dx=o.p[0]-s.p[0],dz=o.p[2]-s.p[2],x=Math.cos(a)*dx-Math.sin(a)*dz,z=Math.sin(a)*dx+Math.cos(a)*dz,[rx,rz]=halfSize(o),da=yaw(o)-s.yaw,ex=o.shape==='box'?Math.abs(Math.cos(da))*rx+Math.abs(Math.sin(da))*rz:rx,ez=o.shape==='box'?Math.abs(Math.sin(da))*rx+Math.abs(Math.cos(da))*rz:rz;return Math.abs(x)+ex<=s.w/2+margin&&Math.abs(z)+ez<=s.d/2+margin;}
function inside(o,z){if(!o?.p||!z?.p)return false;const dx=Math.abs(o.p[0]-z.p[0]),dz=Math.abs(o.p[2]-z.p[2]),r=radius(o);const ex=o.halfExtentsM?.[0]??r,ez=o.halfExtentsM?.[2]??r;return z.shape==='square'?dx+ex<=z.r+.001&&dz+ez<=z.r+.001:Math.hypot(dx,dz)+r<=z.r*(z.shape==='hexagon'?Math.cos(Math.PI/6):1)+.001;}
function facts(world){
 const w=worldData(world),surfaces=w.objects.map(surface).filter(Boolean),groundY=Number(w.groundY)||0;
 return{schema:'jarvis/scene_facts@1.0',sceneId:w.sceneId,revision:w.revision,units:'meter',positionConvention:'object_center',
  supportToleranceM:.025,groundY,surfaces,physicsSettings:w.physicsSettings?clone(w.physicsSettings):null,
  objects:w.objects.map(o=>{
   const h=height(o),bottomY=Number(o.p?.[1])-Number(o.halfExtentsM?.[1]??h/2),physical=o.physicsState;
   // Observed contact state takes precedence over geometric proximity. A body
   // can pass through this height while falling, which is not a resting contact.
   let supportedBy;
   if(physical)supportedBy=[...(physical.supportIds||[])];
   else{supportedBy=o.held?[]:surfaces.filter(s=>s.id!==o.id&&Math.abs(bottomY-s.topY)<=.025&&fitsSupport(o,s,.001)).map(s=>s.id);if(!o.held&&Math.abs(bottomY-groundY)<=.025)supportedBy.push('ground');}
   return{id:o.id,name:o.name,type:kind(o),shape:o.shape,color:color(o),portable:portable(o),movable:o.movable!==false,
    held:!!o.held,bottomY,heightM:h,supportedBy,supportBasis:physical?'rigid-body-contact':'geometry-estimate',
    settled:physical?!!physical.settled:null,speedMps:physical?.speedMps??null,
    velocity:Array.isArray(o.v)?clone(o.v):null,inside:w.zones.filter(z=>inside(o,z)).map(z=>z.id),
    position:clone(o.p),massKg:Number.isFinite(o.mass)?o.mass:null};
  })};
}
function entityView(o){return{id:o.id,name:o.name,position:o.p,shape:o.shape};}
function aliases(w,raw,ctx={},bindings={}){let t=norm(bindings[raw]||raw).replace(/^(?:那个|这个|那张|这张|那一个|这一个|的)+/,'').replace(/的$/,'');t=t.replace(/一号区|第一区|一区/g,'Z1').replace(/二号区|第二区|二区/g,'Z2').replace(/三号区|第三区|三区/g,'Z3').replace(/第?(\d+)号?区/g,'Z$1');const pool=[...w.objects,...w.zones];if(/^(那里|这里|那儿|上次的地方|刚才那里)$/.test(t)){const e=pool.find(o=>o.id===ctx.lastTarget);if(e)return e;fail('MISSING_CONTEXT','还没有明确的目标位置。',{slot:'target',raw})}let es=pool.filter(o=>o.id.toLowerCase()===t.toLowerCase());if(!es.length)es=pool.filter(o=>[o.name,...(o.aliases||[])].some(a=>norm(a).toLowerCase()===t.toLowerCase()));if(!es.length){const k=Object.keys(TYPES).find(k=>TYPES[k].includes(t));if(k)es=w.objects.filter(o=>kind(o)===k);}if(es.length===1)return es[0];if(es.length>1)fail('AMBIGUOUS',`“${raw}”对应 ${es.length} 个目标，请选一个。`,{slot:'target',raw,candidates:es.map(entityView)});fail('NOT_FOUND',`场景中没有可确认的“${raw}”。`,{slot:'target',raw});}
function and(args){args=args.filter(Boolean);return args.length===1?args[0]:{op:'and',args};}
function or(args){return args.length===1?args[0]:{op:'or',args};}
function validateQuery(q,w,depth=0,budget={n:0}){if(++budget.n>64||depth>8)fail('QUERY_LIMIT','场景查询超过允许的复杂度。');if(!q||typeof q!=='object'||Array.isArray(q))fail('QUERY_SCHEMA','查询必须是声明式对象。');const keys={all:['op'],portable:['op'],ids:['op','ids'],type:['op','value'],color:['op','value'],support:['op','targetId'],inside:['op','targetId'],near:['op','targetId','distanceM'],side:['op','targetId','value','frame'],and:['op','args'],or:['op','args'],not:['op','arg'],rank:['op','arg','by','order','count','targetId'],context:['op','value'],movable:['op','value']};if(!keys[q.op])fail('QUERY_SCHEMA','未知查询操作：'+q.op);for(const k of Object.keys(q))if(!keys[q.op].includes(k))fail('QUERY_SCHEMA','查询含协议外字段：'+k);if(['and','or'].includes(q.op)){if(!Array.isArray(q.args)||!q.args.length)fail('QUERY_SCHEMA','组合查询不能为空。');q.args.forEach(x=>validateQuery(x,w,depth+1,budget));}if(['not','rank'].includes(q.op))validateQuery(q.arg,w,depth+1,budget);if(q.op==='ids'&&(!Array.isArray(q.ids)||!q.ids.length||q.ids.some(id=>!w.objects.some(o=>o.id===id))))fail('UNKNOWN_ENTITY','查询包含当前场景不存在的物体编号。');if(q.op==='type'&&!Object.keys(TYPES).includes(q.value))fail('QUERY_SCHEMA','缺少可验证的物体类型。');if(q.op==='color'&&!COLORS[q.value])fail('QUERY_SCHEMA','颜色查询无效。');if(q.op==='movable'&&typeof q.value!=='boolean')fail('QUERY_SCHEMA','可移动性必须为布尔值。');if(q.op==='context'&&!['set','remaining','object'].includes(q.value))fail('QUERY_SCHEMA','上下文查询无效。');if(q.op==='side'&&(!['left','right','front','behind'].includes(q.value)||!['world','self'].includes(q.frame)))fail('QUERY_SCHEMA','方向或参考系无效。');if(q.op==='near'&&(!Number.isFinite(q.distanceM)||q.distanceM<.05||q.distanceM>3))fail('QUERY_SCHEMA','附近范围必须为 0.05 至 3 米。');if(q.op==='rank'&&(!['distance','mass','volume','x'].includes(q.by)||!['asc','desc'].includes(q.order)||!Number.isInteger(q.count)||q.count<1||q.count>64))fail('QUERY_SCHEMA','排序查询无效。');if(['support','inside','near','side'].includes(q.op)&&typeof q.targetId!=='string')fail('QUERY_SCHEMA','空间关系缺少目标。');if(q.targetId&&!['ground','self'].includes(q.targetId)&&![...w.objects,...w.zones].some(o=>o.id===q.targetId))fail('UNKNOWN_ENTITY','关系目标不在当前场景：'+q.targetId);if(q.op==='inside'&&!w.zones.some(z=>z.id===q.targetId))fail('RELATION_TYPE','“里面”需要已定义的区域或容器，当前对象没有容器数据。');if(q.op==='support'&&q.targetId!=='ground'&&!surface(w.objects.find(o=>o.id===q.targetId)||{}))fail('RELATION_TYPE','目标缺少明确的支撑表面数据。');return q;}
function evaluate(q,world,ctx={}){const w=worldData(world),f=facts(w),byId=new Map(f.objects.map(o=>[o.id,o]));validateQuery(q,w);const all=w.objects.map(o=>o.id),get=id=>[...w.objects,...w.zones].find(o=>o.id===id);const run=n=>{switch(n.op){case'all':return all;case'portable':return f.objects.filter(o=>o.portable).map(o=>o.id);case'ids':return n.ids;case'type':return f.objects.filter(o=>o.type===n.value||o.shape===n.value&& !['table','bench','shelf','platform'].includes(o.type)).map(o=>o.id);case'color':return f.objects.filter(o=>o.color===n.value).map(o=>o.id);case'movable':return f.objects.filter(o=>o.movable===n.value).map(o=>o.id);case'support':return f.objects.filter(o=>o.supportedBy.includes(n.targetId)).map(o=>o.id);case'inside':return f.objects.filter(o=>o.inside.includes(n.targetId)).map(o=>o.id);case'context':{if(ctx.sceneId&&ctx.sceneId!==w.sceneId)fail('STALE_CONTEXT','场景已经切换，请重新说明所指的物体。');let ids=n.value==='object'?[ctx.lastObject].filter(Boolean):n.value==='remaining'?(ctx.lastUniverse||[]).filter(id=>!(ctx.completedObjectIds||[]).includes(id)):ctx.lastSet||[];if(!ids.length)fail('MISSING_CONTEXT',n.value==='remaining'?'还没有可确认的上一组对象及完成记录，请先说明范围。':'还没有明确的对象集合，请先说明“这些”指哪些东西。');const missing=ids.filter(id=>!get(id));if(missing.length)fail('STALE_CONTEXT','上次指代的部分对象已经不存在：'+missing.join('、'));return ids;}
case'and':return n.args.map(run).reduce((a,b)=>a.filter(id=>b.includes(id)));case'or':return uniq(n.args.flatMap(run));case'not':{const ex=run(n.arg);return all.filter(id=>!ex.includes(id));}
case'near':case'side':{const p=n.targetId==='self'?(ctx.position||[0,0,1.75]):get(n.targetId).p;return w.objects.filter(o=>{if(o.id===n.targetId)return false;let x=o.p[0]-p[0],z=o.p[2]-p[2];if(n.op==='near')return Math.hypot(x,z)<=n.distanceM;if(n.frame==='self'){const a=-(ctx.yaw||0),xx=Math.cos(a)*x-Math.sin(a)*z;z=Math.sin(a)*x+Math.cos(a)*z;x=xx;}return n.value==='left'?x<-.025:n.value==='right'?x>.025:n.value==='front'?z>.025:z<-.025;}).map(o=>o.id);}
case'rank':{const ids=run(n.arg),p=n.targetId&&n.targetId!=='self'?get(n.targetId).p:ctx.position||[0,0,1.75];const score=id=>{const o=get(id);if(n.by==='mass'){if(!Number.isFinite(o.mass))fail('MISSING_ATTRIBUTE','有物体缺少质量数据，无法可靠排序。');return o.mass;}if(n.by==='volume'){const h=height(o),r=Number(o.r)||.1;return o.shape==='sphere'?4/3*Math.PI*r**3:o.shape==='box'?o.w*h*o.d:Math.PI*r*r*h*(o.shape==='cone'?1/3:1);}if(n.by==='x')return o.p[0];return Math.hypot(o.p[0]-p[0],o.p[2]-p[2]);};ids.sort((a,b)=>(n.order==='asc'?1:-1)*(score(a)-score(b)));if(ids.length>n.count&&Math.abs(score(ids[n.count-1])-score(ids[n.count]))<.001)fail('AMBIGUOUS','排序边界上有多个同样符合的物体，请补充范围。',{slot:'object',candidates:ids.map(id=>entityView(get(id)))});return ids.slice(0,n.count);}
default:throw Error('Unreachable query');}};const ids=uniq(run(q));return{ids,entities:ids.map(get),facts:f,matched:ids.map(id=>byId.get(id)),excluded:f.objects.filter(o=>!ids.includes(o.id))};}
function stripRank(q){if(q.op==='rank')return stripRank(q.arg);if(q.args)return{...q,args:q.args.map(stripRank)};return q;}
function parseReference(raw,world,ctx={},options={}){const w=worldData(world),original=norm(raw);let t=original,quantifier='one',count=null,parts=[],rank=null,assumptions=[];const bindings=options.bindings||{};
 if(bindings[original])return{query:{op:'ids',ids:[aliases(w,bindings[original],ctx).id]},quantifier:'one',raw:original,assumptions};
 if(/^(它们|他们|她们|这些|那些|这几个|那几个|这些东西|那些东西|这些物体|这批物体|刚才那些|刚才的那些)$/.test(t.replace(/的$/,'')))return{query:{op:'context',value:'set'},quantifier:'all',raw:original,assumptions};
 if(/^(剩下|其余|剩余|其他)(?:的)?(?:东西|物体|物品|那些|这些)?$/.test(t))return{query:{op:'context',value:'remaining'},quantifier:'all',raw:original,assumptions};
 if(/^(它|该物体|刚才那个|刚才的物体)$/.test(t))return{query:{op:'context',value:'object'},quantifier:'one',raw:original,assumptions};
 let exclusion=null;const ex=t.match(/除了(.+?)(?:以外|之外|外)(.*)/);if(ex){exclusion=parseReference(ex[1],w,ctx,{...options,allowGeneric:true});t=ex[2]||'所有物体';quantifier='all';}
 const tail=t.match(/^(.+?)(?:，|,)?除了(.+?)(?:以外|之外|外)?$/);if(tail){exclusion=parseReference(tail[2],w,ctx,{...options,allowGeneric:true});t=tail[1];quantifier='all';}
 if(/所有|全部|全都|统统|每一个|每个|各个|一切|逐个|依次|都/.test(t)||options.all)quantifier='all';t=t.replace(ALL,'');
 const cnt=t.match(/([一二两三四五六七八九十\d]+)(?:个|件|只|颗|块)/);if(cnt){count=number(cnt[1]);t=t.replace(cnt[0],'');if(count<1||count>64)fail('QUERY_LIMIT','一次集合选择限定为 1 至 64 件。');quantifier='count';}
 t=t.replace(/^(?:把|将|的)+/,'').replace(/(?:散落|散放|散着|摆放|摆|放|落|躺|留)(?:着|在)?/g,'').replace(/^(?:场景|场内|屋子|房间)(?:里面|里|中|内)?(?:的)?/,'');
 const anchorRank=t.match(/(?:距离|离)(.+?)(最近|最远)/);if(anchorRank){const a=aliases(w,anchorRank[1].replace(/的$/,''),ctx,bindings);rank={by:'distance',order:anchorRank[2]==='最近'?'asc':'desc',count:count||1,targetId:a.id};t=t.replace(anchorRank[0],'');}
 const r=t.match(/最近|最远|最轻|最重|最大|最小|最左|最右/);if(r&&!rank){const v=r[0];rank={by:/轻|重/.test(v)?'mass':/大|小/.test(v)?'volume':/左|右/.test(v)?'x':'distance',order:/远|重|大|右/.test(v)?'desc':'asc',count:count||1,targetId:'self'};t=t.replace(v,'');}
 if(/地面上|地板上|地上|地面|地板/.test(t)){parts.push({op:'support',targetId:'ground'});t=t.replace(/(?:在)?(?:地面上|地板上|地上|地面|地板)/g,'');}
 const rel=t.match(/^(?:在)?(.+?)(?:的)?(旁边|附近|边上|左边|左侧|右边|右侧|前面|前方|后面|后方|上面|表面|台面|桌面|上|里面|里|内)(?:的)?/);
 if(rel){let anchor=rel[1].replace(/的$/,''),r=rel[2];if(/人物|智能人|你|自身|身体/.test(anchor)&&/^(人物|智能人|你|自身|身体)$/.test(anchor)){parts.push({op:'side',targetId:'self',value:/左/.test(r)?'left':/右/.test(r)?'right':/前/.test(r)?'front':'behind',frame:'self'});assumptions.push('人物方向由当前身体位置与朝向计算');}
 else{const a=aliases(w,anchor,ctx,bindings);if(/上|面$/.test(r)&&!/[前后]/.test(r))parts.push({op:'support',targetId:a.id});else if(/里|内/.test(r))parts.push({op:'inside',targetId:a.id});else if(/旁|附近|边上/.test(r)){parts.push({op:'near',targetId:a.id,distanceM:.85});assumptions.push('“附近”采用中心水平距离不超过 0.85 米的当前策略');}else parts.push({op:'side',targetId:a.id,value:/左/.test(r)?'left':/右/.test(r)?'right':/前/.test(r)?'front':'behind',frame:'world'});}
 t=t.replace(rel[0],'');}
 if(/我的|我左|我右|镜头|屏幕/.test(t))fail('UNAVAILABLE_FRAME','当前没有用户或摄像机的空间位置，请使用人物自身或场景实体作为参照。',{raw:original});
 if(/^(同色|相同颜色|一样颜色)/.test(t)){const o=w.objects.find(o=>o.id===ctx.lastObject);if(!o||!color(o))fail('MISSING_CONTEXT','还没有可比较颜色的上一物体。');parts.push({op:'color',value:color(o)});t=t.replace(/^(同色|相同颜色|一样颜色)/,'');}
 if(/可移动|可搬运|可搬|能搬|能搬动/.test(t)){parts.push({op:'portable'});t=t.replace(/可移动|可搬运|能搬动|可搬|能搬/g,'');}
 if(/固定|不可移动/.test(t)){parts.push({op:'movable',value:false});t=t.replace(/不可移动|固定/g,'');}
 // Union is composed recursively. The shared spatial predicate remains outside it.
 if(/和|以及|或者|或|、/.test(t)){const chunks=t.split(/以及|或者|和|或|、/).filter(Boolean);parts.push(or(chunks.map(s=>parseReference(s,w,ctx,{...options,allowGeneric:true}).query)));t='';quantifier='all';}
 if(t){const ids=w.objects.filter(o=>new RegExp('(^|[^a-z0-9_])'+o.id+'($|[^a-z0-9_])','i').test(t));if(ids.length){parts.push({op:'ids',ids:ids.map(o=>o.id)});for(const o of ids)t=t.replace(new RegExp(o.id,'i'),'');if(ids.length>1)quantifier='all';}
 const colorWords=Object.entries(COLORS).filter(([k,a])=>a.some(s=>t.includes(s)));if(colorWords.length){parts.push(or(colorWords.map(([k])=>({op:'color',value:k}))));for(const[k,a]of colorWords)for(const s of a)t=t.split(s).join('');}
 const candidates=Object.entries(TYPES).flatMap(([k,words])=>words.map(s=>({k,s}))).sort((a,b)=>b.s.length-a.s.length),kinds=[];for(const{k,s}of candidates){if(t.includes(s)){kinds.push(k);t=t.split(s).join('');}}if(kinds.length)parts.push(or(uniq(kinds).map(value=>({op:'type',value}))));
 // Dynamic user-assigned labels are exact references, never executable instructions.
 if(t.replace(GENERIC,'').trim()){const exact=w.objects.filter(o=>[o.name,...(o.aliases||[])].some(a=>a&&norm(a)===t.replace(/^的|的$/g,'')));if(exact.length){parts.push({op:'ids',ids:exact.map(o=>o.id)});t='';}}
 }
 t=t.replace(GENERIC,'').replace(/^(?:在|于)|(?:上|里|内)$|\s/g,'');if(t)fail('UNKNOWN_DESCRIPTION',`“${original}”中仍有无法用当前场景数据核对的描述“${t}”，请补充含义。`,{slot:'object',raw:original,unresolved:t});
 if(!parts.some(p=>p.op==='movable'&&p.value===false)&&!parts.some(p=>p.op==='ids')&&!parts.some(p=>p.op==='type'&&['table','bench','shelf','platform'].includes(p.value)))parts.unshift({op:'portable'});
 if(exclusion)parts.push({op:'not',arg:exclusion.query});let query=and(parts);if(rank)query={op:'rank',arg:query,...rank};return{query,quantifier,count,raw:original,assumptions};}
function resolveSelection(ref,w,ctx){const r=evaluate(ref.query,w,ctx);if(ref.quantifier==='one'&&r.ids.length>1)fail('AMBIGUOUS',`“${ref.raw}”符合 ${r.ids.length} 个物体，请指定一个或说明全部。`,{slot:'object',raw:ref.raw,candidates:r.entities.map(entityView)});if(ref.quantifier==='count'&&r.ids.length!==ref.count)fail(r.ids.length<ref.count?'COUNT_MISMATCH':'ORDER_UNSPECIFIED',r.ids.length<ref.count?`你提到 ${ref.count} 件，当前只找到 ${r.ids.length} 件符合条件的物体。`:`符合条件的有 ${r.ids.length} 件。选择 ${ref.count} 件还需要明确排序或范围。`,{slot:'object',raw:ref.raw,candidates:r.entities.map(entityView)});if(!r.ids.length&&ref.quantifier==='one')fail('NOT_FOUND',`当前没有符合“${ref.raw}”的物体。`,{slot:'object',raw:ref.raw});return r;}
function destination(raw,world,ctx={},bindings={}){const w=worldData(world);let t=norm(raw).replace(/(?:吧|一下|好吗|好不好|可以吗|行吗)$/,'').replace(/[，,]+$/,'').replace(/(?:去)$/,'');let relation=null;const match=t.match(/(上面|桌面|台面|表面|上|里面|里|内|旁边|附近|边上|左边|左侧|右边|右侧|前面|前方|后面|后方)$/);if(match){const v=match[1];relation=/^上|桌面|台面|表面/.test(v)?'on':/里|内/.test(v)?'inside':/左/.test(v)?'left':/右/.test(v)?'right':/前/.test(v)?'front':/后/.test(v)?'behind':'near';t=t.slice(0,-v.length).replace(/的$/,'');if(!t&&/桌面|台面/.test(v))t='桌子';}
 if(/^(地上|地面|地板)$/.test(raw)||t==='地')return{id:'ground',relation:'on',raw};const e=aliases(w,t||raw,ctx,bindings);relation=relation||(w.zones.some(z=>z.id===e.id)?'inside':surface(e)?'on':'near');if(relation==='on'&&!surface(e))fail('UNSUPPORTED_SURFACE',`“${e.name}”没有可确认的支撑表面数据。`,{slot:'target',raw});if(relation==='inside'&&!w.zones.some(z=>z.id===e.id))fail('UNSUPPORTED_CONTAINER',`“${e.name}”尚未提供容器内部空间数据。`,{slot:'target',raw});return{id:e.id,relation,raw,name:e.name};}
function effectSatisfied(effect,w,ctx={}){w=worldData(w);const o=w.objects.find(o=>o.id===effect.objectId),t=[...w.objects,...w.zones].find(e=>e.id===effect.targetId);if(!o||o.held)return false;if(effect.relation==='inside')return!!t&&inside(o,t);if(effect.relation==='on')return facts(w).objects.find(x=>x.id===o.id)?.supportedBy.includes(effect.targetId)||false;if(!t)return false;if(effect.relation==='near')return Math.hypot(o.p[0]-t.p[0],o.p[2]-t.p[2])<1.1;return evaluate({op:'side',targetId:t.id,value:effect.relation,frame:'world'},w,ctx).ids.includes(o.id);}
function supportedRelations(caps){return caps?.placementRelations||caps?.native?.placementRelations||caps?.source?.native?.placementRelations||['inside','near','left','right','front','behind'];}
function compileGoals(goals,world,ctx={},options={}){const w=worldData(world),nodes=[],grounding=[],requiredEffects=[],skipped=[],gaps=[],assumptions=[],selected=[],universe=[],protectedIds=options.protectedIds||[];let position=ctx.position||[0,0,1.75];
 for(const goal of goals){const sel=resolveSelection(goal.source,w,ctx),dest=goal.destination,ids=sel.ids.filter(id=>!protectedIds.includes(id));if(dest.id!=='ground'&&![...w.objects,...w.zones].some(o=>o.id===dest.id))fail('UNKNOWN_ENTITY','目标不在当前场景中。');const fixed=sel.entities.filter(o=>o.movable===false);if(fixed.length)fail('FIXED_OBJECT','明确选中的对象包含不能移动的固定环境：'+fixed.map(o=>o.name).join('、'));
 grounding.push({text:goal.source.raw||'模型声明式对象查询',ids,kind:'object_set',queryContext:clone(ctx),query:clone(goal.source.query),quantifier:goal.source.quantifier,evidence:'current_world_snapshot',matched:sel.matched.filter(o=>ids.includes(o.id)),excluded:sel.excluded.map(o=>({id:o.id,name:o.name,reasons:[!o.portable?'固定环境或非搬运对象':'不符合源集合谓词'],supportedBy:o.supportedBy})),target:{id:dest.id,relation:dest.relation,name:dest.name}});selected.push(...ids);universe.push(...ids);assumptions.push(...(goal.source.assumptions||[]));if(goal.source.quantifier==='all')assumptions.push('集合成员在理解时固定，执行中不会自动加入新出现的物体');
 const pending=[];for(const objectId of ids){if(objectId===dest.id)fail('SELF_TARGET','操作物体与目标不能相同。');const effect={objectId,targetId:dest.id,relation:dest.relation};requiredEffects.push(effect);if(effectSatisfied(effect,w,ctx))skipped.push(objectId);else pending.push(objectId);}
 if(pending.length&&(!supportedRelations(options.capabilities).includes(dest.relation)||dest.id==='ground'))gaps.push({code:'PLACEMENT_RELATION_UNSUPPORTED',relation:dest.relation,targetId:dest.id,objectIds:pending,requiredCapability:dest.relation==='on'?'carry_place_on_support':'place_at_ground_location'});
 if(pending.some(id=>facts(w).objects.find(o=>o.id===id).bottomY>(Number(w.groundY)||0)+.025))gaps.push({code:'ELEVATED_PICKUP_UNSUPPORTED',objectIds:pending.filter(id=>facts(w).objects.find(o=>o.id===id).bottomY>(Number(w.groundY)||0)+.025),requiredCapability:'pickup_from_support'});
 // Deterministic nearest-next order is an execution choice, never object selection.
 const remaining=[...pending];while(remaining.length){remaining.sort((a,b)=>{const aa=w.objects.find(o=>o.id===a),bb=w.objects.find(o=>o.id===b);return Math.hypot(aa.p[0]-position[0],aa.p[2]-position[2])-Math.hypot(bb.p[0]-position[0],bb.p[2]-position[2])||a.localeCompare(b)});const objectId=remaining.shift();nodes.push({kind:'action',id:'grounded_'+(nodes.length+1),step:{type:goal.method==='push'?'push':'carry',objectId,targetId:dest.id,relation:dest.relation,referenceFrame:'world'}});const target=[...w.objects,...w.zones].find(o=>o.id===dest.id);position=target?.p||position;}
 }
 if(nodes.length>64)fail('PLAN_LIMIT','展开后的计划超过 64 个动作，请缩小范围或分轮执行。');
 const last=goals.at(-1)?.destination,groundedIntent={schema:'jarvis/grounded_goal@1.0',worldRevision:w.revision,sceneId:w.sceneId,goals:clone(goals),selectedIds:uniq(selected),requiredEffects:clone(requiredEffects),skippedIds:uniq(skipped),capabilityGaps:gaps};
 let status=nodes.length?'ready':'noop',questions=[],response='';if(gaps.length){status='clarify';const names=uniq(selected).map(id=>w.objects.find(o=>o.id===id)?.name||id);response=`我已从当前场景确定 ${uniq(selected).length} 件对象：${names.join('、')}。目标是${last?.name||last?.id}${last?.relation==='on'?'的支撑表面':'指定位置'}。${gaps.some(g=>g.code==='PLACEMENT_RELATION_UNSUPPORTED')?'现有身体接口尚不支持在这个支撑表面上放置，当前只支持地面搬运与区域放置。':''}${gaps.some(g=>g.code==='ELEVATED_PICKUP_UNSUPPORTED')?'现有抓取还缺少从高处支撑表面取物的能力。':''}本轮保留完整目标，没有下发动作。`;questions=[{code:'CAPABILITY_GAP',message:response,capabilityGaps:gaps}];}
 else if(!nodes.length)response=selected.length?`符合条件的 ${uniq(selected).length} 件对象已经满足目标，无需重复搬运。`:'当前没有符合范围的可移动物体，无需执行动作。';
 return{status,engine:'scene-grounded-compositional',nodes:status==='ready'?nodes:[],desiredNodes:nodes,grounding,groundedIntent,requiredEffects,assumptions:uniq(assumptions),questions,response,constraints:{protectedIds,collisionAvoidance:true,forbiddenActions:[]},contextAfter:{lastObject:selected.at(-1)||ctx.lastObject,lastRelation:last?.relation,lastTarget:last?.id||ctx.lastTarget,lastSet:uniq(selected),lastUniverse:uniq(universe),completedObjectIds:uniq(skipped),sceneId:w.sceneId},summary:status==='clarify'?[`已理解 ${uniq(selected).length} 件对象及目标，等待身体能力接入`]:undefined};}
function queryCommand(text,w,ctx,options){let m=text.match(/^(?:现在|目前)?(.+?)(?:还有|有)(?:多少|几)(?:个|件|只|颗)?(?:东西|物体|物品|球|箱子)?[？?]?$/),ref=null;if(m){let noun=/球[？?]?$/.test(text)?'球':/箱子[？?]?$/.test(text)?'箱子':'物体';ref=m[1]+noun;}if(!ref){m=text.match(/^(.+?)(?:有(?:哪些|什么)|有哪些|有哪些东西|有哪些物体|都有哪些|都有什么|有哪些物品)[？?]?$/);if(m)ref=m[1]+'物体';}if(!ref){m=text.match(/^(.+?)(?:是哪些|有哪些|有几个|有多少|还剩多少)[？?]?$/);if(m)ref=m[1];}if(!ref)return null;const source=parseReference(ref,w,ctx,{...options,all:true}),result=evaluate(source.query,w,ctx),ids=result.ids;return{status:'query',engine:'scene-grounded-compositional',nodes:[],response:`按当前场景数据，符合“${ref}”的有 ${ids.length} 件${ids.length?'：'+result.entities.map(o=>`${o.name}（${o.id}）`).join('、'):''}。`,grounding:[{text:ref,ids,query:source.query,matched:result.matched,evidence:'current_world_snapshot'}],groundedIntent:{schema:'jarvis/grounded_goal@1.0',selectedIds:ids,goals:[],requiredEffects:[],capabilityGaps:[],worldRevision:w.revision,sceneId:w.sceneId},contextAfter:{...ctx,lastSet:ids,lastUniverse:ids,completedObjectIds:[],sceneId:w.sceneId},questions:[],assumptions:source.assumptions};}
function compile(text,world,ctx={},options={}){const w=worldData(world);let t=norm(text).replace(/^那(?:就|么)[，,]?/,'');if(!SPECIAL.test(t)&&!options.force)return null;if(/^(?:不要|别|不许|禁止)/.test(t))return null;if(/^(?:如果|为什么|怎么|如何|记住|请记住)/.test(t))return null;try{const q=queryCommand(t,w,ctx,options);if(q)return q;
 let mode=options.mode||'replace';if(/做完|追加/.test(t))mode='append';t=t.replace(/^(?:贾维斯|假维斯|jarvis)[，,：:\s]*/i,'').replace(/^(?:麻烦你|能不能帮我|请你|帮我|帮忙|请|先|你能不能|你能|你)+/,'').replace(/[。？?！!]$/,'');
 const chunks=t.split(/然后|接着|随后|最后|再(?=把|将|去|搬|推|放|收拾|整理)|[；;。]/).map(s=>s.trim().replace(/^[，,]+|[，,]+$/g,'').trim()).filter(Boolean);
 if(chunks.length>1){const plans=[];let c={...ctx};for(const chunk of chunks){const p=compile(chunk,w,c,{...options,mode})||options.fallback?.(chunk,c);if(!p||!['ready','noop'].includes(p.status))return p?{...p,nodes:[],status:'clarify',response:p.response||'复合指令中有未解决的步骤，本轮不会部分执行。'}:null;const earlier=plans.flatMap(x=>x.requiredEffects||[]);const dependent=(p.groundedIntent?.goals||[]).some(g=>{const json=JSON.stringify(g.source.query);return earlier.some(e=>json.includes('\"targetId\":\"'+e.targetId+'\"')&&['inside','on'].includes(e.relation));});if(dependent)fail('DEPENDENT_SCENE_QUERY','后续子句需要按前一步完成后的新场景重新筛选对象。请分轮执行，或用“它们”保留同一批对象。');plans.push(p);c={...c,...p.contextAfter};}return{status:'ready',engine:'scene-grounded-compositional',mode,nodes:plans.flatMap(p=>p.nodes||[]).map((n,i)=>({...n,id:'compound_'+(i+1)})),grounding:plans.flatMap(p=>p.grounding||[]),requiredEffects:plans.flatMap(p=>p.requiredEffects||[]),groundedIntent:{schema:'jarvis/grounded_goal@1.0',goals:plans.flatMap(p=>p.groundedIntent?.goals||[]),selectedIds:uniq(plans.flatMap(p=>p.groundedIntent?.selectedIds||[])),requiredEffects:plans.flatMap(p=>p.requiredEffects||[]),worldRevision:w.revision,sceneId:w.sceneId,capabilityGaps:[]},contextAfter:c,assumptions:uniq(plans.flatMap(p=>p.assumptions||[])),questions:[],constraints:{protectedIds:uniq(plans.flatMap(p=>p.constraints?.protectedIds||[])),forbiddenActions:uniq(plans.flatMap(p=>p.constraints?.forbiddenActions||[])),collisionAvoidance:true}};}
 const protectedIds=[];let prefixExclusion=null;const ex=t.match(/^除了(.+?)(?:以外|之外|外)?[，,](.+)$/);if(ex){prefixExclusion=parseReference(ex[1].replace(/(?:以外|之外|外)$/,''),w,ctx,options);t=ex[2];}
 t=t.replace(/[，,](?:不要|别|不许)(?:动|碰|搬|推)(.+)$/,(full,s)=>{protectedIds.push(...evaluate(parseReference(s,w,ctx,{...options,all:true}).query,w,ctx).ids);return''});
 // Separate source, transfer verb and destination. Quantifiers belong to the source.
 let m=t.match(/^(?:把|将)?(.+?)(?:搬运|收拾|归置|整理|移动|挪|搬|放|送|推|拿)(?:起来)?(?:到|至|进|入|在)(.+)$/),sourceRaw,destRaw,method;
 if(m){sourceRaw=m[1];destRaw=m[2];method=/(?:推)(?:到|至|进|入|在)/.test(t)?'push':'carry';}
 else{m=t.match(/^(?:把|将)?(?:搬运|收拾|归置|整理|移动|挪|搬|放|送|推|拿)(.+?)(?:到|至|进|入|在)(.+)$/);if(m){sourceRaw=m[1];destRaw=m[2];method=/^推/.test(t)?'push':'carry';}}
 if(!m)return null;
 const allInVerb=/都|全都|统统/.test(sourceRaw);sourceRaw=sourceRaw.replace(/(?:全都|统统|都)$/,'');const source=parseReference(sourceRaw,w,ctx,{...options,all:allInVerb||options.all});if(prefixExclusion){source.query=and([source.query,{op:'not',arg:prefixExclusion.query}]);source.quantifier='all';}
 const dest=destination(destRaw,w,ctx,options.bindings);const out=compileGoals([{action:'relocate',source,destination:dest,method}],w,ctx,{...options,protectedIds});out.mode=mode;return out;
 }catch(e){if(!(e instanceof GroundingError))throw e;return{status:'clarify',engine:'scene-grounded-compositional',nodes:[],questions:[{code:e.code,message:e.message,...e.detail}],response:e.message,grounding:[],assumptions:[],contextAfter:null,validation:{ok:false,errors:[e.message]}};}}
function fromProposal(proposal,world,ctx={},options={}){const w=worldData(world);if(!proposal||proposal.schema!==SCHEMA)fail('PROPOSAL_SCHEMA','场景目标建议协议不匹配。');for(const k of Object.keys(proposal))if(!['schema','status','mode','goals','response','questions'].includes(k))fail('PROPOSAL_SCHEMA','目标建议含协议外字段：'+k);if(!['ready','clarify','noop'].includes(proposal.status)||!['append','replace'].includes(proposal.mode)||!Array.isArray(proposal.goals)||proposal.goals.length>16)fail('PROPOSAL_SCHEMA','目标建议状态、模式或数量无效。');if(proposal.status!=='ready'){if(proposal.goals.length)fail('PROPOSAL_SCHEMA','未解决的建议不得包含待执行目标。');return{status:proposal.status,nodes:[],questions:proposal.questions||[],response:String(proposal.response||''),engine:'model-scene-goal-validated',requiresConfirmation:true};}if(!proposal.goals.length)fail('PROPOSAL_SCHEMA','可执行建议不能为空。');for(const g of proposal.goals){for(const k of Object.keys(g))if(!['action','source','destination','method'].includes(k))fail('PROPOSAL_SCHEMA','目标含协议外字段：'+k);if(g.action!=='relocate'||!['carry','push'].includes(g.method)||!g.source||!['one','all','count'].includes(g.source.quantifier))fail('PROPOSAL_SCHEMA','未知目标或对象量词。');for(const k of Object.keys(g.source))if(!['query','quantifier','count','raw'].includes(k))fail('PROPOSAL_SCHEMA','源对象含协议外字段：'+k);validateQuery(g.source.query,w);if(g.source.quantifier==='count'&&(!Number.isInteger(g.source.count)||g.source.count<1||g.source.count>64))fail('PROPOSAL_SCHEMA','数量约束无效。');if(!g.destination||!['on','inside','near','left','right','front','behind'].includes(g.destination.relation))fail('PROPOSAL_SCHEMA','目标位置关系无效。');for(const k of Object.keys(g.destination))if(!['id','relation','raw'].includes(k))fail('PROPOSAL_SCHEMA','目的地含协议外字段：'+k);const e=[...w.objects,...w.zones].find(o=>o.id===g.destination.id);if(!e&&g.destination.id!=='ground')fail('UNKNOWN_ENTITY','模型建议引用不存在的目标。');if(g.destination.relation==='on'&&g.destination.id!=='ground'&&!surface(e))fail('UNSUPPORTED_SURFACE','目标缺少支撑表面。');if(g.destination.relation==='inside'&&!w.zones.some(z=>z.id===g.destination.id))fail('RELATION_TYPE','目标没有容器或区域数据。');}
 const out=compileGoals(proposal.goals,w,ctx,options);return{...out,mode:proposal.mode,engine:'model-scene-goal-validated',requiresConfirmation:true};}
function revalidateStep(plan,step,world,ctx={}){if(!plan.groundedIntent||!step.objectId)return{ok:true};const w=worldData(world);if(w.sceneId!==plan.sceneId)return{ok:false,reason:'场景身份已经变化。'};for(const g of plan.grounding||[]){if(!g.ids?.includes(step.objectId)||!g.query)continue;try{const ids=evaluate(stripRank(g.query),w,g.queryContext||ctx).ids;if(!ids.includes(step.objectId))return{ok:false,reason:`物体 ${step.objectId} 已不符合原先的源集合条件，停止后续步骤并等待重新理解。`};}catch(e){return{ok:false,reason:e.message};}}return{ok:true};}
function verifyEffects(plan,world,ctx={}){const expected=[...new Map((plan.requiredEffects||[]).map(e=>[e.objectId,e])).values()],checks=expected.map(effect=>({...effect,satisfied:effectSatisfied(effect,world,ctx)}));return{schema:'jarvis/goal_verification@1.0',ok:checks.every(x=>x.satisfied),worldRevision:worldData(world).revision,checked:checks.length,checks};}
return{VERSION,SCHEMA,GroundingError,worldData,facts,surface,inside,color,portable,parseReference,evaluate,validateQuery,resolveSelection,destination,compile,compileGoals,fromProposal,revalidateStep,verifyEffects,effectSatisfied,stripRank};
});
