'use strict';
const fs=require('fs');fs.mkdirSync(__dirname+'/results',{recursive:true});
const {ProductShell,SurfaceLaw,LeatherDynamics}=require('./load-baseline.cjs');
const result={baseline:'f1ab73a7b289461a7d81e65eed935ec62369ed34',method:'Direct execution of hash-verified R08 production bundle. No renderer or source mutation.',releaseReady:false,cases:{}};
function energyInStoredFrame(s){const q=s.tri[0],F=new Float64Array(6),D=q.D;for(let j=0;j<3;j++){const e=s.x[q.ids[1]*3+j]-s.x[q.ids[0]*3+j],f=s.x[q.ids[2]*3+j]-s.x[q.ids[0]*3+j];F[j]=e*D[0]+f*D[2];F[j+3]=e*D[1]+f*D[3];}const C=[.5*(F[0]**2+F[1]**2+F[2]**2-1),.5*(F[3]**2+F[4]**2+F[5]**2-1),F[0]*F[3]+F[1]*F[4]+F[2]*F[5]],k=s.law.tangent0,K=[[k[0],k[1],k[2]],[k[1],k[3],k[4]],[k[2],k[4],k[5]]];let W=0;for(let i=0;i<3;i++)for(let j=0;j<3;j++)W+=.5*C[i]*K[i][j]*C[j];return{energyDensityPa:W,F:Array.from(F),areaM2:q.area};}
const cyclic=[];
for(const order of [[0,1,2],[1,2,0],[2,0,1]]){const s=new ProductShell({positions:[0,100,0,100,100,0,0,200,0],triangles:[[...order,1.39,0]]});for(let i=0;i<s.inv.length;i++)s.x[3*i]*=1.05;cyclic.push({order,...energyInStoredFrame(s)});}
result.cases.cyclicPermutation={description:'Only cyclically change triangle index order, not material or rest coordinates. A consistent material law must not change.',rows:cyclic,maxMinRatio:Math.max(...cyclic.map(x=>x.energyDensityPa))/Math.min(...cyclic.map(x=>x.energyDensityPa))};
const law=new SurfaceLaw('NL'),curves=[];
for(const e of [.01,.05,.10,.20,.30]){const s=new ProductShell({positions:[0,100,0,100,100,0,0,200,0],triangles:[[0,1,2,1.39,0]]});for(let i=0;i<s.inv.length;i++)s.x[3*i]*=(1+e);let t=energyInStoredFrame(s);curves.push({strain:e,R04NonlinearWPa:law.evaluate([1+e,0,0,0,1,0])[0],R08TangentWPa:t.energyDensityPa});}
result.cases.materialDifference={description:'Prescribed longitudinal extension with transverse stretch 1. Energy probe, not a tensile-stress test; no claim that tangent model is always softer.',rows:curves};
const S=new ProductShell({positions:[-60,100,-40,60,100,-40,0,100,60,-7,98,-7,7,102,-7,0,102,7],triangles:[[0,2,1,1.4,0],[3,4,5,1.4,0]]},{gravity:0,damping:0});const before=S.x.slice();S.selfContact();let maxDelta=0;for(let i=0;i<S.x.length;i++)maxDelta=Math.max(maxDelta,Math.abs(S.x[i]-before[i]));
result.cases.intersectionMiss={description:'A small triangle straddles the interior of a large triangle, far from its vertices. Static detection probe, not an initially feasible CCD case.',selfContactCount:S.contacts,maxCorrectionMM:maxDelta*1000,largeTriangleYMM:100,smallTriangleYMM:[98,102,102]};
const T=new ProductShell({positions:[-60,100,-40,60,100,-40,0,100,60,-7,104,-7,7,104,-7,0,104,7],triangles:[[0,2,1,1.4,0],[3,4,5,1.4,0]]},{gravity:0,damping:0});for(let i=0;i<3;i++)T.inv[i]=0;for(let i=3;i<6;i++)T.v[3*i+1]=-.5;T.active=true;T.step(8);
result.cases.slowCrossingMiss={description:'Initially separated triangles. At 0.5 m/s over eight nominal steps, the small triangle passes through the fixed triangle. Full original solver executed.',finalYMM:[3,4,5].map(i=>T.x[3*i+1]*1000),startedYMM:104,fixedSurfaceYMM:100,state:T.report()};
const r04=new LeatherDynamics({n:4,size:.24});
result.cases.damping={R04PerSecond:r04.cfg.damping,R08PerSecond:new ProductShell({positions:[0,100,0,50,100,0,0,100,50],triangles:[[0,1,2,1.39,0]]}).cfg.damping,halfLifeR04S:Math.log(2)/r04.cfg.damping,halfLifeR08S:Math.log(2)/.5,note:'Damping-only half-lives, not measured total response or material stress relaxation.'};
const patch={positions:[0,100,0,50,100,0,0,100,50,50,100,50],triangles:[[0,2,1,1.39,0],[1,2,3,1.39,0]]};const bend=new ProductShell(patch);result.cases.bending={r08HingeK:bend.bends[0].k,r04EquivalentSameGeometry:bend.bends[0].k*3,formulaRatio:1/3,note:'Verified source formula R04:3*D*l^2/(A0+A1), R08:D*l^2/(A0+A1) at reference thickness. Both D values unmeasured.'};
if(!(result.cases.slowCrossingMiss.finalYMM.every(y=>y<100)&&result.cases.cyclicPermutation.maxMinRatio>1.2))throw Error('Baseline defect did not reproduce; inspect, do not invent evidence');
fs.writeFileSync(__dirname+'/results/baseline-numeric.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
