'use strict';
const fs=require('fs');fs.mkdirSync(__dirname+'/results',{recursive:true});const L=require('./load-baseline.cjs');const{T,makeProduct,productMaterials,ProductShell,updateSkin}=L;
const root=makeProduct('wallet',productMaterials(new T.MeshStandardMaterial()),{}),r=root.userData.rig,s=new ProductShell(r.data),thread=r.meshes.find(m=>m.userData.thread),g=thread.geometry;
function pointAt(i){const ids=g.getAttribute('simIDs'),w=g.getAttribute('simWeights'),d=g.getAttribute('simDelta');let P=new T.Vector3(),X=new T.Vector3(),N=new T.Vector3();for(let j=0;j<4;j++){const id=ids.array[i*4+j],q=w.array[i*4+j];P.addScaledVector(new T.Vector3().fromArray(r.pixels,id*12),q);X.addScaledVector(new T.Vector3().fromArray(r.pixels,id*12+4),q);N.addScaledVector(new T.Vector3().fromArray(r.pixels,id*12+8),q);}N.normalize();X.addScaledVector(N,-X.dot(N)).normalize();return P.addScaledVector(X,d.getX(i)).addScaledVector(N.clone().cross(X),d.getY(i)).addScaledVector(N,d.getZ(i));}
const sets=r.parts.map(p=>new Set(p.lookup.flatMap(q=>q.ids)));const bindCount=r.parts.map(()=>0);for(let i=0;i<g.attributes.position.count;i++)for(let j=0;j<4;j++){if(Math.abs(g.getAttribute('simWeights').array[i*4+j])<1e-8)continue;let id=g.getAttribute('simIDs').array[i*4+j];for(let k=0;k<sets.length;k++)if(sets[k].has(id))bindCount[k]++;}
const initial=Array.from({length:g.attributes.position.count},(_,i)=>pointAt(i));
for(const id of sets[0])s.x[3*id+2]-=.001;updateSkin(root,s);
const moved=initial.map((p,i)=>pointAt(i).distanceTo(p)),back=Array.from({length:initial.length},(_,i)=>i).filter(i=>initial[i].z<0);
const report={scope:'Exact R08 procedural product and GPU position formula evaluated on CPU. Controlled 1mm motion of only the back layer isolates ownership. Not a dynamics solution or real-leather measurement.',releaseReady:false,parts:r.parts.map((p,i)=>({name:p.name,simNodes:sets[i].size,activeYarnBindingEntries:bindCount[i]})),backLayerDisplacementMM:1,backFacingThreadVertices:back.length,maximumYarnDisplacementMM:Math.max(...moved),maximumBackYarnDisplacementMM:Math.max(...back.map(i=>moved[i]))};
for(let i=0;i<s.x.length;i++)s.x[i]=s.rest[i]+(i%3===0?.005:0);updateSkin(root,s);report.uniformTranslationMaxErrorMM=Math.max(...initial.map((p,i)=>pointAt(i).distanceTo(p.clone().add(new T.Vector3(5,0,0)))));
if(!(report.maximumBackYarnDisplacementMM<1e-6&&report.uniformTranslationMaxErrorMM<1e-4))throw Error('Unexpected baseline attachment behavior');
fs.writeFileSync(__dirname+'/results/thread-probe.json',JSON.stringify(report,null,2));console.log(report);
