import test from 'node:test';
import assert from 'node:assert/strict';
import * as k from '../prototype/kernels.mjs';
const close=(a,b,e=1e-10)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const norm=a=>Math.hypot(...a),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
test('01 quintic endpoints and derivative',()=>{assert.deepEqual(k.smoothTransition(0),{value:0,derivative:0});assert.deepEqual(k.smoothTransition(1),{value:1,derivative:0});close(k.smoothTransition(.5).value,.5);});
test('02 quintic clamps without overshoot',()=>{close(k.smoothTransition(-1).value,0);close(k.smoothTransition(2).value,1);for(let i=0;i<=100;i++){let r=k.smoothTransition(i/100);assert.ok(r.value>=0&&r.value<=1&&r.derivative>=0);}});
test('03 Fourier periodic and derivative',()=>{const c={offset:.2,sin:[.4,.1],cos:[.3,-.2]},p=.73,h=1e-6;close(k.sampleFourier(p,c).value,k.sampleFourier(p+2*Math.PI,c).value);close(k.sampleFourier(p,c).dPhase,(k.sampleFourier(p+h,c).value-k.sampleFourier(p-h,c).value)/(2*h),1e-8);});
test('04 Fourier rejects mismatched coefficients',()=>assert.throws(()=>k.sampleFourier(0,{sin:[1],cos:[]})));
test('05 critical spring semigroup with constant target',()=>{const a=k.criticalSpring(1,.3,2,4,.2),b=k.criticalSpring(a.x,a.v,2,4,.3),c=k.criticalSpring(1,.3,2,4,.5);close(b.x,c.x);close(b.v,c.v);});
test('06 critical spring zero dt and convergence',()=>{let a=k.criticalSpring(1,.3,2,4,0);close(a.x,1);close(a.v,.3);close(k.criticalSpring(1,0,2,4,10).x,2);assert.throws(()=>k.criticalSpring(0,0,0,4,-1));});
test('07 Bezier exact endpoints',()=>{const p=[[0,0,0],[0,1,0],[1,1,0],[1,0,0]];assert.deepEqual(k.bezier3(p,0),p[0]);assert.deepEqual(k.bezier3(p,1),p[3]);close(k.bezier3(p,.5)[1],.75);});
test('08 Bezier invalid data rejected',()=>{assert.throws(()=>k.bezier3([[0,0,0]],0));assert.throws(()=>k.bezier3([[0,0,0],[1,0,0],[2,0,0],[3,0,0]],2));});
test('09 transported frames remain orthonormal at zero curvature and turns',()=>{const f=k.transportedFrames([[0,0,1],[0,0,1],[0,.1,1],[0,.5,1]],[1,0,0]);for(const p of f){close(norm(p.t),1);close(norm(p.n),1);close(norm(p.b),1);close(dot(p.t,p.n),0);close(dot(p.n,p.b),0);}});
test('10 transport rejects degenerate or antiparallel tangents',()=>{assert.throws(()=>k.transportedFrames([[0,0,1],[0,0,-1]],[1,0,0]));assert.throws(()=>k.transportedFrames([[0,0,0]],[1,0,0]));});
test('11 feather asymmetric width and camber',()=>{assert.deepEqual(k.featherPoint([0,0,0],[1,0,0],[0,1,0],.2,.1,-1,.03),[-.2,0,0]);close(k.featherPoint([0,0,0],[1,0,0],[0,1,0],.2,.1,.5,.03)[1],.03);assert.throws(()=>k.featherPoint([0,0,0],[1,0,0],[1,0,0],.2,.1,0,0));});
test('12 IK fixed lengths and reachable targets',()=>{for(const sign of [-1,1])for(const [x,y] of [[1,1],[.5,.7],[-.6,1]]){let r=k.twoBoneIK(x,y,1,.8,sign);assert.ok(r.reachable);close(norm(r.elbow),1);close(norm(r.end.map((v,i)=>v-r.elbow[i])),.8);close(r.error,0);}});
test('13 IK unreachable and ambiguous reported',()=>{let r=k.twoBoneIK(4,0,1,1);assert.equal(r.reachable,false);close(r.error,2);assert.equal(k.twoBoneIK(0,0,1,1).ambiguous,true);});
const opts={radius:10,responseTime:1,separationRadius:2,separationWeight:1,alignmentWeight:1,cohesionWeight:1,maxAcceleration:.5};
test('14 flock acceleration bounded and inputs unchanged',()=>{let s={position:[0,0,0],velocity:[0,0,1]},ns=[{position:[1,0,0],velocity:[2,0,1]},{position:[2,0,0],velocity:[1,0,1]}],before=JSON.stringify(ns);let a=k.flockSteering(s,ns,{...opts,k:1});assert.ok(norm(a.acceleration)<=.5+1e-12);assert.equal(a.neighborCount,1);assert.equal(JSON.stringify(ns),before);});
test('15 flock empty and coincident safe',()=>{let s={position:[0,0,0],velocity:[0,0,0]};assert.deepEqual(k.flockSteering(s,[],opts).acceleration,[0,0,0]);assert.equal(k.flockSteering(s,[s],opts).coincident,1);});
test('16 closest approach head-on and diverging',()=>{let a=k.closestApproach([10,0,0],[-2,0,0],10,1);close(a.time,5);assert.ok(a.risk);let b=k.closestApproach([10,0,0],[2,0,0],10,1);close(b.time,0);assert.equal(b.risk,false);});
test('17 closest approach zero relative velocity',()=>{let r=k.closestApproach([2,0,0],[0,0,0],3,1);close(r.time,0);close(r.clearance,1);});
test('18 bank sign and speed scaling',()=>{close(k.bankAngle(0,.1,9.81),0);close(k.bankAngle(10,.02,9.81),-k.bankAngle(10,-.02,9.81));close(Math.tan(k.bankAngle(20,.02,9.81)),4*Math.tan(k.bankAngle(10,.02,9.81)));});
test('19 strip zero speed and area scaling',()=>{const p={density:1.2,speed:10,chord:.2,spanWidth:.1,cl:1,cd:.1};close(k.bladeElement({...p,speed:0}).lift,0);close(k.bladeElement({...p,spanWidth:.2}).lift,2*k.bladeElement(p).lift);assert.ok(k.bladeElement(p).drag>=0);assert.throws(()=>k.bladeElement({...p,cd:-1}));});
test('20 XPBD rigid projection and pinned endpoint',()=>{let r=k.xpbdDistance([0,0,0],[2,0,0],0,1,1,0,.01);assert.deepEqual(r.a,[0,0,0]);close(norm(r.b),1);close(r.residual,0);});
test('21 XPBD softness and retained iteration multiplier',()=>{let a=k.xpbdDistance([0,0,0],[2,0,0],0,1,1,.01,.1),b=k.xpbdDistance(a.a,a.b,0,1,1,.01,.1,a.lambda);assert.ok(a.residual>0&&a.residual<1);close(b.residual,a.residual);});
test('22 XPBD unresolved cases explicit',()=>{assert.equal(k.xpbdDistance([0,0,0],[2,0,0],0,0,1,0,.1).status,'PINNED');assert.equal(k.xpbdDistance([0,0,0],[0,0,0],1,1,1,0,.1).status,'DEGENERATE');});
test('23 invalid numeric inputs rejected',()=>{assert.throws(()=>k.smoothTransition(NaN));assert.throws(()=>k.bankAngle(Infinity,1,10));assert.throws(()=>k.closestApproach([1,0,0],[1,0,0],-1,1));assert.throws(()=>k.xpbdDistance([0,0,0],[1,0,0],1,1,1,0,0));});
test('24 prototype export inventory',()=>assert.equal(Object.keys(k).length,12));
