import assert from 'node:assert/strict';import fs from 'node:fs';
import {PROFILES,LeatherMaterial,materialPoint,makeSpecimen,MembraneSolver,RelaxationProbe} from './site/physics.mjs';
fs.mkdirSync(new URL('./qa',import.meta.url),{recursive:true});const tests=[];const check=(name,fn)=>{let e=fn();tests.push({name,pass:true,...e});console.log('PASS',name,JSON.stringify(e||{}));};
for(const id of Object.keys(PROFILES)){
check(id+' rest stress and energy',()=>{let r=new LeatherMaterial(id).evaluate([1,0,0,1]);assert(Math.abs(r.W)<1e-12);assert(Math.max(...r.P.map(Math.abs))<1e-10);});
check(id+' energy derivative finite difference',()=>{let m=new LeatherMaterial(id,35),F=[1.08,.025,.017,.97],r=m.evaluate(F),err=0;for(let i=0;i<4;i++){let a=[...F],b=[...F];a[i]+=1e-6;b[i]-=1e-6;err=Math.max(err,Math.abs((m.evaluate(a).W-m.evaluate(b).W)/2e-6-r.P[i]));}assert(err<1e-5);return{maxMPaError:err};});
if(id!=='SHOE')check(id+' rotation objectivity',()=>{let m=new LeatherMaterial(id,27),F=[1.14,.02,-.01,.94],c=Math.cos(.7),s=Math.sin(.7),Q=[c*F[0]-s*F[2],c*F[1]-s*F[3],s*F[0]+c*F[2],s*F[1]+c*F[3]];assert(Math.abs(m.evaluate(F).W-m.evaluate(Q).W)<1e-10);});}
check('AL directional response',()=>{let a=materialPoint(new LeatherMaterial('AL',0),.2).nominalStress,b=materialPoint(new LeatherMaterial('AL',90),.2).nominalStress;assert(a>b*1.2);return{MPa0:a,MPa90:b};});
check('isotropic dispersion limit',()=>{let a=new LeatherMaterial('NL',0),b=new LeatherMaterial('NL',90);a.fibers.forEach(f=>f.k=1/3);b.fibers.forEach(f=>f.k=1/3);assert(Math.abs(a.evaluate([1.15,0,0,.98]).W-b.evaluate([1.15,0,0,.98]).W)<1e-12);});
check('invalid inputs rejected',()=>{assert.throws(()=>materialPoint(new LeatherMaterial(),.5));assert.throws(()=>new RelaxationProbe(new LeatherMaterial(),{g:[1],tau:[0]}));assert.throws(()=>new LeatherMaterial('FAKE'));});
let holeForce,solidForce;for(const hole of [false,true])check('same-size '+(hole?'perforated':'solid')+' FE equilibrium',()=>{let mesh=makeSpecimen({hole,width:10}),s=new MembraneSolver(new LeatherMaterial('NL'),mesh);s.setStrain(.08);for(let k=0;k<200;k++){s.iterate(12);if(s.state.residual<1e-5||s.blocked)break;}let r=s.report();assert(r.converged,JSON.stringify(r));assert(r.forceN>0);assert(r.minAreaRatio>.5);assert(Array.from(s.x).every(Number.isFinite));if(hole)holeForce=r.forceN;else solidForce=r.forceN;return r;});
check('hole reduces force at equal dimensions and extension',()=>{assert(holeForce<solidForce);return{holeForce,solidForce};});
check('FE nodal energy gradient',()=>{let s=new MembraneSolver(new LeatherMaterial('NL'),makeSpecimen({nx:4,ny:2}));s.setStrain(.05);let r=s.evaluate(s.q),err=0;for(let i=0;i<s.q.length;i++){let a=s.q.slice(),b=s.q.slice();a[i]+=1e-5;b[i]-=1e-5;err=Math.max(err,Math.abs((s.evaluate(a).E-s.evaluate(b).E)/2e-5-r.g[i]));}assert(err<1e-5);return{maxForceErrorN:err};});
check('hold matches exact Prony decay',()=>{let r=new RelaxationProbe(new LeatherMaterial()),s0=r.jump(.12).nominalStressMPa;for(let i=0;i<120;i++)r.step(.12,.5);let expected=s0*(r.gInf+r.g.reduce((s,g,i)=>s+g*Math.exp(-60/r.tau[i]),0));assert(Math.abs(r.stress-expected)<1e-8);return{initialMPa:s0,MPaAt60s:r.stress};});
check('constant load creep and unload recovery',()=>{let p=new RelaxationProbe(new LeatherMaterial());p.forceStep(1,.5);let first=p.strain;for(let i=0;i<40;i++)p.forceStep(1,.5);let end=p.strain;assert(end>first);assert(Math.abs(p.stress-1)<1e-6);for(let i=0;i<60;i++)p.forceStep(0,.5);assert(p.strain<end*.8);return{first,crept:end,recovered:p.strain};});
check('elastic model has no fabricated permanent set',()=>{let m=new LeatherMaterial();materialPoint(m,.20);assert(Math.abs(m.evaluate([1,0,0,1]).W)<1e-12);});
check('inverted element rejected',()=>assert(!Number.isFinite(new LeatherMaterial().evaluate([1,0,0,-1]).W)));
fs.writeFileSync(new URL('./qa/numerics.json',import.meta.url),JSON.stringify({version:'R03.1',tests,pass:true,scope:'mathematical consistency; not independent experiments or paper curve reproduction',sourcePagesChecked:'PDF8-10, 2026-10-08'},null,2));
