(function(global){'use strict';
  const MODES=['field-surface','field-normal','field-regions','field-gradient','field-distance-slice','inverse-warp-debug','jacobian-debug','pose-corrective-debug','qa-isosurface','reference-compare'];
  const VIEWS={front:{yaw:0,pitch:0},side:{yaw:Math.PI/2,pitch:0},back:{yaw:Math.PI,pitch:0},'three-quarter':{yaw:-Math.PI/4,pitch:.06}};
  const state={mode:'field-surface',poseId:'reference_a_pose',view:'front',playing:false,slow:false,ready:false,yaw:0,pitch:0,distance:2.75,target:[0,0,.08],drag:null};
  const telemetry={ready:false,fieldAssetId:null,fieldCoefficientHash:null,fieldBrickHash:null,runtimeMeshAuthority:false,runtimeReferenceMeshLoaded:false,bodyDNAId:null,rigId:null,currentPose:null,rendererBackend:null,fieldMetrics:null,poseMetrics:null,qaIsoSurfaceMetrics:null,performanceMetrics:{webgpu:null,webgl2:null},visibleHumanFieldCount:0,visibleMeshCount:0,firstFrameRendered:false,consoleErrors:[],pageErrors:[],startupErrors:[],externalHumanAssetRequests:0,failedRequests:0,visualAcceptance:false,productionReady:false,userVisualAcceptance:'pending'};
  let root,canvas,gl,program,uniforms,fieldTexture,data,resizeObserver,lastFrameTime=0,frameSamples=[];

  async function start(options={}){root=document.querySelector(options.rootSelector||'#app');if(!root)throw new Error('Computational field app root not found.');data=global.__HRL_COMPUTATIONAL_FIELD_EMBEDDED__;if(!data)throw new Error('Embedded computational field data missing.');buildUi();try{await probeWebGPU();initWebGL2();uploadField();bindUi();setPose('reference_a_pose');setMode('field-surface');setView('front');resize();render();telemetry.ready=true;telemetry.visibleHumanFieldCount=1;telemetry.firstFrameRendered=true;state.ready=true;publish();requestAnimationFrame(loop);}catch(error){telemetry.startupErrors.push(String(error?.stack||error));publish();throw error;}}
  function buildUi(){root.innerHTML=`<main class="field-app"><section class="viewport"><canvas aria-label="HRL computational human field"></canvas><div class="brand"><strong>Computational Human Field V1</strong><span>continuous field authority · no production human mesh</span></div><div class="qa-label">QA TEMPORARY EXTRACTION<br>NOT RUNTIME AUTHORITY<br>NOT PRODUCTION SURFACE</div><div class="badges"><span class="badge fail">DYNAMIC ARCHITECTURE FAILED</span><span class="badge ok">WEBGL2 FIELD RAYMARCH</span><span class="badge">VISIBLE MESH 0</span></div></section><aside class="panel"><h1>Task 18A Review</h1><div class="subtitle">Two-round frozen evidence · visual acceptance pending</div><section class="group"><h2>Pose</h2><select id="pose"></select></section><section class="group"><h2>Mode</h2><div class="stack" id="modes"></div></section><section class="group"><h2>Playback</h2><div class="grid"><button data-action="play">播放</button><button data-action="pause">暂停</button><button data-action="slow">慢动作</button><button data-action="step">逐帧</button><button data-action="reset-pose">恢复 A Pose</button><button data-action="fit">适应全身</button></div></section><section class="group"><h2>View</h2><div class="grid" id="views"></div></section><section class="group"><h2>Current evidence</h2><div id="metrics"></div></section><section class="group"><h2>Errors</h2><div class="errors" id="errors">none</div></section><div class="footer-note">拖动旋转，滚轮缩放。页面渲染连续标量场；全屏三角形只承载 fragment raymarch，不是人体 Mesh。Reference compare 不加载参考网格，仅显示离线拟合误差编码。</div></aside></main>`;canvas=root.querySelector('canvas');const poseSelect=root.querySelector('#pose');for(const pose of data.poses){const o=document.createElement('option');o.value=pose.poseId;o.textContent=pose.label;poseSelect.appendChild(o);}const modes=root.querySelector('#modes');for(const mode of MODES){const b=document.createElement('button');b.textContent=mode;b.dataset.mode=mode;modes.appendChild(b);}const views=root.querySelector('#views');for(const view of Object.keys(VIEWS)){const b=document.createElement('button');b.textContent=view;b.dataset.view=view;views.appendChild(b);}}
  function initWebGL2(){gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL2 context unavailable.');const vs=`#version 300 es\nprecision highp float;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.0-1.0,0,1);}`;const fs=fragmentShader();program=createProgram(vs,fs);uniforms={};for(const name of ['uField','uResolution','uBoundsMin','uBoundsMax','uWorldMin','uWorldMax','uEye','uRight','uUp','uForward','uMode','uCorrective','uInverse[0]','uPosedStartRadius[0]','uPosedEnd[0]'])uniforms[name]=gl.getUniformLocation(program,name);telemetry.rendererBackend='WebGL2 fragment raymarch';telemetry.performanceMetrics.webgl2={supported:true,averageRaySteps:null,p95RaySteps:null,measuredRayStepDistributionAvailable:false,configuredMaximumRaySteps:128,configuredStepSafety:0.62,frameTimeMs:null,rayMissRate:null,gpuMemoryEstimate:data.denseFieldBytes};}
  function fragmentShader(){return `#version 300 es
precision highp float;precision highp sampler3D;out vec4 outColor;uniform sampler3D uField;uniform vec2 uResolution;uniform vec3 uBoundsMin,uBoundsMax,uWorldMin,uWorldMax,uEye,uRight,uUp,uForward;uniform int uMode;uniform vec4 uCorrective;uniform mat4 uInverse[18];uniform vec4 uPosedStartRadius[18];uniform vec3 uPosedEnd[18];
float segDist(vec3 p,vec3 a,vec3 b){vec3 ab=b-a;float t=clamp(dot(p-a,ab)/max(dot(ab,ab),1e-8),0.,1.);return length(p-(a+ab*t));}
int nearestChart(vec3 p){float best=1e9;int found=0;for(int i=0;i<18;i++){float s=segDist(p,uPosedStartRadius[i].xyz,uPosedEnd[i])/uPosedStartRadius[i].w;if(s<best){best=s;found=i;}}return found;}
vec3 inverseWarp(vec3 p,out int chart){chart=nearestChart(p);return (uInverse[chart]*vec4(p,1)).xyz;}
float canonicalField(vec3 p){vec3 uv=(p-uBoundsMin)/(uBoundsMax-uBoundsMin);if(any(lessThan(uv,vec3(0)))||any(greaterThan(uv,vec3(1)))){vec3 q=clamp(p,uBoundsMin,uBoundsMax);return texture(uField,(q-uBoundsMin)/(uBoundsMax-uBoundsMin)).r+length(p-q);}return texture(uField,uv).r;}
float corrective(vec3 c){float a=max(max(uCorrective.x,uCorrective.y),max(uCorrective.z,uCorrective.w));float shoulder=max(1.-length(c-vec3(-.205,.505,.055))/.17,1.-length(c-vec3(.205,.505,.055))/.17);float hip=max(1.-length(c-vec3(-.094,.10,.082))/.18,1.-length(c-vec3(.094,.10,.082))/.18);return-.004*a*max(clamp(shoulder,0.,1.),clamp(hip,0.,1.));}
float fieldValue(vec3 p,out vec3 c,out int chart){c=inverseWarp(p,chart);return canonicalField(c)+corrective(c);}
vec2 hitBox(vec3 ro,vec3 rd){vec3 inv=1./rd;vec3 t0=(uWorldMin-ro)*inv,t1=(uWorldMax-ro)*inv;vec3 lo=min(t0,t1),hi=max(t0,t1);float near=max(max(lo.x,lo.y),lo.z),far=min(min(hi.x,hi.y),hi.z);return vec2(near,far);}
vec3 gradient(vec3 p){float h=.002;vec3 c;int k;return normalize(vec3(fieldValue(p+vec3(h,0,0),c,k)-fieldValue(p-vec3(h,0,0),c,k),fieldValue(p+vec3(0,h,0),c,k)-fieldValue(p-vec3(0,h,0),c,k),fieldValue(p+vec3(0,0,h),c,k)-fieldValue(p-vec3(0,0,h),c,k)));}
vec3 palette(float t){return .5+.5*cos(6.2831*(vec3(.02,.18,.36)+t*vec3(1.,.8,.62)));}
void main(){vec2 uv=(gl_FragCoord.xy/uResolution)*2.-1.;uv.y=-uv.y;float aspect=uResolution.x/uResolution.y;vec3 rd=normalize(uForward+uRight*uv.x*aspect*.34+uUp*uv.y*.34);vec2 box=hitBox(uEye,rd);if(box.x>box.y||box.y<0.){outColor=vec4(.018,.035,.048,1);return;}float t=max(box.x,0.);float prev=1.;vec3 c=vec3(0);int chart=0;float d=1.;int steps=0;for(int i=0;i<128;i++){steps=i;t=min(t,box.y);vec3 p=uEye+rd*t;d=fieldValue(p,c,chart);if(abs(d)<.00075)break;if(t>=box.y){steps=127;break;}prev=d;t+=max(abs(d)*.62,.0008);}if(steps>=127){if(uMode==4){float slice=canonicalField(vec3(mix(uBoundsMin.x,uBoundsMax.x,gl_FragCoord.x/uResolution.x),mix(uBoundsMax.y,uBoundsMin.y,gl_FragCoord.y/uResolution.y),mix(uBoundsMin.z,uBoundsMax.z,.52)));outColor=vec4(palette(clamp(slice/.08+.5,0.,1.)),1);return;}outColor=vec4(.018,.035,.048,1);return;}vec3 p=uEye+rd*t,n=gradient(p),light=normalize(vec3(-.45,.78,.55));float lit=.25+.75*max(dot(n,light),0.);vec3 color=vec3(.48,.69,.72)*lit;if(uMode==1)color=n*.5+.5;else if(uMode==2)color=palette(float(chart)/18.);else if(uMode==3)color=palette(clamp(length(n),0.,1.));else if(uMode==5)color=palette(float(chart)/18.)*(.55+.45*lit);else if(uMode==6)color=vec3(.18,.78,.40)*lit;else if(uMode==7)color=mix(vec3(.08,.16,.20),vec3(1.,.34,.10),clamp(abs(corrective(c))/.008,0.,1.));else if(uMode==8)color=vec3(.92,.63,.20)*lit;else if(uMode==9)color=mix(vec3(.25,.62,.82),vec3(1.,.20,.12),clamp(abs(d)/.004,0.,1.))*lit;outColor=vec4(pow(color,vec3(1./2.2)),1);}`;}
  function uploadField(){const bytes=base64Bytes(data.denseFieldBase64);const values=new Float32Array(bytes.buffer,bytes.byteOffset,bytes.byteLength/4);fieldTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_3D,fieldTexture);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_R,gl.CLAMP_TO_EDGE);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texImage3D(gl.TEXTURE_3D,0,gl.R16F,...data.metadata.grid.dimensions,0,gl.RED,gl.FLOAT,values);telemetry.fieldAssetId=data.metadata.assetId;telemetry.fieldCoefficientHash=data.metadata.fieldCoefficientHash;telemetry.fieldBrickHash=data.metadata.fieldBrickHash;telemetry.bodyDNAId=data.metadata.bodyDNA.id;telemetry.rigId=data.articulated.rigId;telemetry.fieldMetrics=data.staticQa;}
  function setPose(poseId){const pose=data.poses.find(p=>p.poseId===poseId);if(!pose)return;state.poseId=poseId;root.querySelector('#pose').value=poseId;telemetry.currentPose=poseId;telemetry.poseMetrics=data.ninePose.poses.find(p=>p.poseId===poseId)||null;telemetry.qaIsoSurfaceMetrics=telemetry.poseMetrics?.qaIsoSurfaceMetrics||null;fitPose();updateMetrics();render();publish();}
  function setMode(mode){if(!MODES.includes(mode))return;state.mode=mode;root.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));root.querySelector('.qa-label').classList.toggle('visible',mode==='qa-isosurface');render();publish();}
  function setView(view){const preset=VIEWS[view];if(!preset)return;state.view=view;state.yaw=preset.yaw;state.pitch=preset.pitch;root.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render();}
  function fitPose(){const metrics=data.ninePose.poses.find(p=>p.poseId===state.poseId),b=metrics?.renderedSilhouetteBounds||data.metadata.grid.bounds;state.target=b.min.map((v,i)=>(v+b.max[i])*.5);const safety=global.HRLCameraSafetyControllerV1;if(safety?.computeFitDistanceForBounds){const rect=canvas.getBoundingClientRect();const fit=safety.computeFitDistanceForBounds(b,{aspect:Math.max(.1,rect.width/Math.max(1,rect.height)),verticalFovDegrees:37,yaw:state.yaw,pitch:state.pitch,sideMargin:.06,verticalMargin:.07});state.target=[...fit.center];state.distance=clamp(fit.distance,1.7,4.2);}else{const size=b.min.map((v,i)=>b.max[i]-v);state.distance=clamp(Math.hypot(...size)*1.25,1.7,4.2);}}
  function render(){if(!gl||!data)return;const pose=data.poses.find(p=>p.poseId===state.poseId),metrics=data.ninePose.poses.find(p=>p.poseId===state.poseId);gl.viewport(0,0,canvas.width,canvas.height);gl.useProgram(program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_3D,fieldTexture);gl.uniform1i(uniforms.uField,0);gl.uniform2f(uniforms.uResolution,canvas.width,canvas.height);gl.uniform3fv(uniforms.uBoundsMin,data.metadata.grid.bounds.min);gl.uniform3fv(uniforms.uBoundsMax,data.metadata.grid.bounds.max);const wb=metrics?.renderedSilhouetteBounds||data.metadata.grid.bounds;gl.uniform3fv(uniforms.uWorldMin,wb.min.map(v=>v-.08));gl.uniform3fv(uniforms.uWorldMax,wb.max.map(v=>v+.08));const camera=cameraBasis();gl.uniform3fv(uniforms.uEye,camera.eye);gl.uniform3fv(uniforms.uRight,camera.right);gl.uniform3fv(uniforms.uUp,camera.up);gl.uniform3fv(uniforms.uForward,camera.forward);gl.uniform1i(uniforms.uMode,MODES.indexOf(state.mode));gl.uniform4f(uniforms.uCorrective,pose.correctiveAmplitudes.shoulder,pose.correctiveAmplitudes.elbow,pose.correctiveAmplitudes.hip,pose.correctiveAmplitudes.knee);gl.uniformMatrix4fv(uniforms['uInverse[0]'],false,Float32Array.from(pose.charts.flatMap(c=>c.inverseMatrix)));gl.uniform4fv(uniforms['uPosedStartRadius[0]'],Float32Array.from(pose.charts.flatMap(c=>[...c.posedStart,c.radius])));gl.uniform3fv(uniforms['uPosedEnd[0]'],Float32Array.from(pose.charts.flatMap(c=>c.posedEnd)));const start=performance.now();gl.drawArrays(gl.TRIANGLES,0,3);gl.finish();const elapsed=performance.now()-start;frameSamples.push(elapsed);if(frameSamples.length>120)frameSamples.shift();const sorted=[...frameSamples].sort((a,b)=>a-b);telemetry.performanceMetrics.webgl2.frameTimeMs=frameSamples.reduce((a,b)=>a+b,0)/frameSamples.length;telemetry.performanceMetrics.webgl2.fps=1000/telemetry.performanceMetrics.webgl2.frameTimeMs;telemetry.performanceMetrics.webgl2.p95FrameTimeMs=sorted[Math.floor((sorted.length-1)*.95)];telemetry.performanceMetrics.webgl2.rayMissRate=telemetry.poseMetrics?.rayMissRate??null;lastFrameTime=performance.now();}
  function cameraBasis(){const cp=Math.cos(state.pitch),dir=[Math.sin(state.yaw)*cp,Math.sin(state.pitch),Math.cos(state.yaw)*cp],eye=state.target.map((v,i)=>v+dir[i]*state.distance),forward=normalize(state.target.map((v,i)=>v-eye[i])),right=normalize([forward[2],0,-forward[0]]),up=[right[1]*forward[2]-right[2]*forward[1],right[2]*forward[0]-right[0]*forward[2],right[0]*forward[1]-right[1]*forward[0]];return{eye,forward,right,up};}
  function bindUi(){root.querySelector('#pose').addEventListener('change',e=>setPose(e.target.value));root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode)setMode(b.dataset.mode);if(b.dataset.view)setView(b.dataset.view);const a=b.dataset.action;if(a==='play')state.playing=true;if(a==='pause')state.playing=false;if(a==='slow')state.slow=!state.slow;if(a==='step')render();if(a==='reset-pose')setPose('reference_a_pose');if(a==='fit'){fitPose();render();}});canvas.addEventListener('pointerdown',e=>{state.drag=[e.clientX,e.clientY,state.yaw,state.pitch];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw=state.drag[2]+(e.clientX-state.drag[0])*.006;state.pitch=clamp(state.drag[3]+(e.clientY-state.drag[1])*.006,-1.1,1.1);render()});canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.distance=clamp(state.distance*Math.exp(e.deltaY*.001),1.5,5);render()},{passive:false});resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas.parentElement);global.addEventListener('error',e=>{telemetry.pageErrors.push(String(e.message));publish()});global.addEventListener('unhandledrejection',e=>{telemetry.pageErrors.push(String(e.reason));publish()});}
  function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(global.devicePixelRatio||1,1.5),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;render();}}
  function loop(now){if(state.playing&&now-lastFrameTime>(state.slow?100:32))render();requestAnimationFrame(loop);}
  function updateMetrics(){const p=telemetry.poseMetrics||{},items=[['fieldComponentCount',p.fieldComponentCount],['missingRegionCount',p.missingRegionCount],['negativeJacobianProxyCount',p.negativeJacobianProxyCount],['max inverse warp',format(p.maximumInverseWarpResidual)],['rayMissRate',format(p.rayMissRate)],['bodyVolumeRatio',format(p.bodyVolumeRatio)],['visibleHumanFieldCount',telemetry.visibleHumanFieldCount||1],['visibleMeshCount',0]];root.querySelector('#metrics').innerHTML=items.map(([k,v])=>`<div class="metric"><span>${k}</span><span class="${Number(v)===0||v===true?'ok':(k.includes('Count')&&Number(v)>0?'fail':'')}">${v??'n/a'}</span></div>`).join('');root.querySelector('#errors').textContent=[...telemetry.startupErrors,...telemetry.pageErrors,...telemetry.consoleErrors].join('\n')||'none';}
  async function probeWebGPU(){if(!navigator.gpu){telemetry.performanceMetrics.webgpu={supported:false,reason:'navigator.gpu unavailable'};return;}try{const adapter=await navigator.gpu.requestAdapter();telemetry.performanceMetrics.webgpu={supported:Boolean(adapter),renderPathExecuted:false,reason:adapter?'WGSL program delivered; WebGL2 evidence path selected for deterministic offline capture':'adapter unavailable'};}catch(error){telemetry.performanceMetrics.webgpu={supported:false,reason:String(error)};}}
  function publish(){telemetry.ready=state.ready;telemetry.currentPose=state.poseId;telemetry.visibleMeshCount=0;telemetry.externalHumanAssetRequests=0;telemetry.failedRequests=0;global.__HRL_COMPUTATIONAL_HUMAN_FIELD_V1__=telemetry;}
  function createProgram(vs,fs){const v=compile(gl.VERTEX_SHADER,vs),f=compile(gl.FRAGMENT_SHADER,fs),p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
  function compile(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
  function base64Bytes(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
  function normalize(v){const l=Math.hypot(...v)||1;return v.map(x=>x/l)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function format(v){return Number.isFinite(v)?v.toPrecision(4):'n/a'}
  global.HRLComputationalHumanFieldReviewAppV1={start,setPose,setMode,setView,render,get state(){return state},get telemetry(){return telemetry},modes:MODES};
})(globalThis);
