const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),root=path.resolve(__dirname,'..'),out=path.join(root,'qa/composition-r22');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1350,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:8877/?version=R008-composition-22');await page.waitForFunction(()=>window.HumanAnatomy||window.failure,null,{timeout:240000});
 const setup=await page.evaluate(()=>{if(window.failure)throw Error(window.failure);HumanR008.renderer.setAnimationLoop(null);HumanGame.reset();HumanGame.setPaused(true);HumanGame.actor.rotation.y=0;HumanGame.actor.updateMatrixWorld(true);HumanGame.subject.play('rest');HumanGame.subject.finishPose();HumanGame.subject.eyes.setMode('centre');HumanGame.subject.eyes.update(0);document.querySelector('aside').style.visibility='hidden';return {generation:HumanSurface.report.generationMilliseconds,attributes:Object.keys(HumanGame.subject.mesh.geometry.attributes),materials:HumanGame.subject.mesh.geometry.groups.map(g=>{const p=HumanGame.subject.mesh.geometry.attributes.skinRest.array,ix=HumanGame.subject.mesh.geometry.index.array,lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let j=g.start;j<g.start+g.count;j++)for(let k=0;k<3;k++){lo[k]=Math.min(lo[k],p[ix[j]*3+k]);hi[k]=Math.max(hi[k],p[ix[j]*3+k]);}return {name:HumanGame.subject.mesh.material[g.materialIndex].name,lo,hi};}),areas:HumanGame.subject.body.composition.profile.areas.map(a=>({id:a.id,radius:a.radius,start:a.start,end:a.end})),maximumAttributes:HumanR008.renderer.capabilities.maxAttributes};});const bounds={};for(const g of setup.materials){const m=bounds[g.name]||={lo:[Infinity,Infinity,Infinity],hi:[-Infinity,-Infinity,-Infinity]};for(let k=0;k<3;k++){m.lo[k]=Math.min(m.lo[k],g.lo[k]);m.hi[k]=Math.max(m.hi[k],g.hi[k]);}}setup.materials=Object.entries(bounds).map(([name,b])=>({name,...b}));console.log(JSON.stringify({setup:{generation:setup.generation,attributes:setup.attributes,maximumAttributes:setup.maximumAttributes}}));
 assert(setup.attributes.length<=setup.maximumAttributes);
 let baselineBones=null;const rows=[],recipes=[['reference',{}],['lean',{fatness:-1,muscle:-1}],['athletic',{fatness:-1,muscle:1}],['fat',{fatness:1,muscle:0}],['fat-muscle',{fatness:1,muscle:1}],['older',{age:75,muscle:.5}]];
 for(const [name,recipe]of (process.env.HUMAN_QUICK_REVIEW?recipes.filter(([name])=>['reference','fat'].includes(name)):recipes)){
  const row=await page.evaluate(async({name,recipe})=>{await HumanBody.set({height:1.8,fatness:0,muscle:0,age:32,...recipe});const s=HumanGame.subject;s.play('rest');s.finishPose();const b=s.body.composition,p=s.mesh.geometry.attributes.skinRest.array,report=s.body.report,regions={};for(let i=0;i<p.length/3;i+=13){const c=b.fields.context(i),id=b.profile.areas[Math.floor(c.anchor[3]/32)].id,r=regions[id]||={n:0,meanDelta:0,meanRadius:0};const q=b.point(i);r.n++;r.meanDelta+=Math.hypot(...q.map((v,k)=>v-p[i*3+k]));r.meanRadius+=Math.hypot(...q.map((v,k)=>v-c.anchor[k]));}for(const r of Object.values(regions)){r.meanDelta/=r.n;r.meanRadius/=r.n;}return {name,recipe,regions,report:{minimumJacobian:report.minimumJacobian,maximumOffsetMetres:report.maximumOffsetMetres,composition:report.composition,tissueRuntimeBytes:report.tissueRuntimeBytes},bones:s.skeleton.bones.map(b=>b.matrixWorld.elements.slice())};},{name,recipe});
  assert(row.report.composition.maximumVolumeRelativeError<1e-5);assert(row.report.minimumJacobian>0);if(baselineBones){let delta=0;for(let i=0;i<row.bones.length;i++)for(let k=0;k<16;k++)delta=Math.max(delta,Math.abs(row.bones[i][k]-baselineBones[i][k]));row.maximumBoneChange=delta;assert(delta<1e-6,'bone change '+delta);}else{baselineBones=row.bones;row.maximumBoneChange=0;}delete row.bones;rows.push(row);
  for(const angle of [0,Math.PI/2,Math.PI]){const view=angle===0?'front':angle===Math.PI?'back':'side';await page.evaluate(angle=>{const h=HumanGame;h.actor.rotation.y=angle;h.actor.updateMatrixWorld(true);h.subject.finishPose();h.camera.position.set(h.actor.position.x,h.actor.position.y+1.05,h.actor.position.z+2.65);h.camera.lookAt(h.actor.position.x,h.actor.position.y+.96,h.actor.position.z);HumanR008.renderer.render(h.scene,h.camera);},angle);await page.screenshot({path:path.join(out,name+'-'+view+'.png')});}
  await page.evaluate(()=>{HumanGame.actor.rotation.y=0;HumanGame.actor.updateMatrixWorld(true);HumanGame.subject.finishPose();});console.log(JSON.stringify({captured:name,maximumOffset:row.report.maximumOffsetMetres,minimumJacobian:row.report.minimumJacobian}));
 }
 const motion=await page.evaluate(()=>{const s=HumanGame.subject,p=s.mesh.geometry.attributes.position.array,rows=[];for(const recipe of [{fatness:-1,muscle:-1},{fatness:1,muscle:1}])for(const phase of ['rest','walk','run','jump']){s.body.set(recipe);s.play(phase);if(phase!=='rest')s.step(.25);s.finishPose();let max=0;for(const group of s.surface.seamGroups){const a=group[0],v=HumanGame.actor.position.clone().fromArray(p,a*3);s.mesh.applyBoneTransform(a,v);for(const i of group){const q=v.clone().fromArray(p,i*3);s.mesh.applyBoneTransform(i,q);max=Math.max(max,v.distanceTo(q));}}HumanR008.renderer.render(HumanGame.scene,HumanGame.camera);rows.push({recipe,phase,maxSeamMetres:max,glError:HumanR008.renderer.getContext().getError()});}s.play('rest');s.body.set({});return rows;});assert(motion.every(r=>r.maxSeamMetres<1e-6&&r.glError===0),JSON.stringify(motion));
 const ui=await page.evaluate(async()=>{const s=HumanGame.subject;await HumanBody.set({fatness:.55});const changed=s.body.export().fatness===.55;await HumanBody.set({fatness:0});HumanAnatomy.inspect('muscle','biceps_brachii_l');HumanR008.renderer.render(HumanGame.scene,HumanGame.camera);HumanAnatomy.setActive(false);return {changed,export:HumanAnatomy.composition.export(),glError:HumanR008.renderer.getContext().getError()};});assert(ui.changed&&ui.glError===0);assert.deepEqual(errors,[]);
 const files=['HumanBodySystem.mjs','HumanBodySpecies.mjs','BodyComposition.mjs','R008CompositionCalibration.mjs','BodyParameters.mjs','BodyBinding.mjs','BodyWorkbench.mjs','AdiposeLayer.mjs','AnatomyAnalysis.mjs','AnatomyContract.mjs','AnatomyWorkbench.mjs'];const sourceHashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f),'utf8').replaceAll('\r\n','\n')).digest('hex')]));
 fs.writeFileSync(path.join(root,'COMPOSITION_REVIEW_REPORT.json'),JSON.stringify({capturedAt:new Date().toISOString(),setup,rows,motion,ui,errors,sourceHashes,sourceHashConvention:'utf8-LF',parameterSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'parameters.phf.gz'))).digest('hex'),acceptance:'runtime-and-numerical-review; appearance requires human review'},null,2)+'\n');console.log(JSON.stringify({complete:true,rows:rows.length,motion,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
