// Offline ASF/AMC feature compiler. Source files are read only from qa/;
// production receives sparse anatomical curve parameters, never a source mesh.
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
const qa=new URL('../qa/',import.meta.url),rad=Math.PI/180,I=[1,0,0,0,1,0,0,0,1];
mkdirSync(qa,{recursive:true});
if(process.argv.includes('--download'))for(const file of ['16/16.asf','16/16_05.amc','16/16_07.amc','75/75.asf','75/75_01.amc']){const response=await fetch('https://mocap.cs.cmu.edu/subjects/'+file);if(!response.ok)throw Error('CMU download failed '+file);writeFileSync(new URL(file.split('/').at(-1),qa),Buffer.from(await response.arrayBuffer()));}
const mul=(a,b)=>Array.from({length:9},(_,i)=>[0,1,2].reduce((s,k)=>s+a[Math.floor(i/3)*3+k]*b[k*3+i%3],0));
const vec=(m,v)=>[0,1,2].map(i=>m[i*3]*v[0]+m[i*3+1]*v[1]+m[i*3+2]*v[2]);
const trans=m=>[m[0],m[3],m[6],m[1],m[4],m[7],m[2],m[5],m[8]];
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),length=a=>Math.hypot(...a),norm=a=>a.map(v=>v/(length(a)||1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rot(axis,a){const c=Math.cos(a),s=Math.sin(a);return axis==='x'?[1,0,0,0,c,-s,0,s,c]:axis==='y'?[c,0,s,0,1,0,-s,0,c]:[c,-s,0,s,c,0,0,0,1];}
function euler(v,order=['rx','ry','rz']){let m=I;order.forEach((key,i)=>m=mul(rot(key.slice(-1),v[i]*rad),m));return m;}
function asf(text){const body=text.split(':bonedata')[1].split(':hierarchy')[0],bones=new Map();for(const block of body.matchAll(/begin\s+([\s\S]*?)\bend/g)){const rows=Object.fromEntries(block[1].trim().split(/\r?\n/).map(l=>{const [k,...v]=l.trim().split(/\s+/);return [k,v];}));const axis=euler(rows.axis.slice(0,3).map(Number));bones.set(rows.name[0],{name:rows.name[0],dir:rows.direction.map(Number),length:Number(rows.length[0]),axis,axisInverse:trans(axis),dof:rows.dof||[],children:[]});}const hierarchy=text.split(':hierarchy')[1].replace(/\b(begin|end)\b/g,'').trim().split(/\r?\n/);const root={name:'root',children:[]};for(const row of hierarchy){const [parent,...children]=row.trim().split(/\s+/);(parent==='root'?root:bones.get(parent)).children=children;}return {root,bones};}
function amc(text){const frames=[];let frame;for(const line of text.split(/\r?\n/)){const row=line.trim();if(!row||/^[#:]/.test(row))continue;if(/^\d+$/.test(row)){frame={frame:Number(row)};frames.push(frame);}else{const [name,...values]=row.split(/\s+/);frame[name]=values.map(Number);}}return frames;}
function fk(rig,frame){const result=new Map(),rootRotation=euler(frame.root.slice(3)),rootPos=frame.root.slice(0,3);result.set('root',{start:rootPos,end:rootPos,rotation:rootRotation});function visit(parent){const p=result.get(parent.name);for(const name of parent.children){const b=rig.bones.get(name),rotation=mul(p.rotation,mul(mul(b.axis,euler(frame[name]||[],b.dof)),b.axisInverse)),end=add(p.end,vec(rotation,b.dir).map(v=>v*b.length));result.set(name,{start:p.end,end,rotation});visit(b);}}visit(rig.root);return result;}
const channelNames=['hip_l','hip_r','knee_l','knee_r','arm_l','arm_r','elbow_l','elbow_r','torso','spread_l','spread_r','foot_l','foot_r'];
function features(joints){const root=joints.get('root'),f=vec(root.rotation,[0,0,1]);f[1]=0;const forward=norm(f),side=[forward[2],0,-forward[0]],up=[0,1,0],values={};for(const s of ['l','r']){const leg=sub(joints.get(s+'femur').end,joints.get(s+'femur').start),calf=sub(joints.get(s+'tibia').end,joints.get(s+'tibia').start),arm=sub(joints.get(s+'humerus').end,joints.get(s+'humerus').start),forearm=sub(joints.get(s+'radius').end,joints.get(s+'radius').start),foot=sub(joints.get(s+'foot').end,joints.get(s+'foot').start);values['hip_'+s]=Math.atan2(dot(leg,forward),-leg[1]);values['knee_'+s]=Math.acos(clamp(dot(norm(leg),norm(calf)),-1,1));values['arm_'+s]=Math.atan2(dot(arm,forward),-arm[1]);values['elbow_'+s]=Math.acos(clamp(dot(norm(arm),norm(forearm)),-1,1));values['spread_'+s]=Math.atan2((s==='l'?1:-1)*dot(arm,side),Math.hypot(arm[1],dot(arm,forward)));values['foot_'+s]=Math.atan2(-foot[1],dot(foot,forward));}const torso=sub(joints.get('thorax').end,root.end);values.torso=Math.atan2(dot(torso,forward),torso[1]);const feet=['l','r'].map(s=>joints.get(s+'tibia').end[1]*.0254/.45);return {values,feet,root:root.end.map(v=>v*.0254/.45)};}
const clips=[{id:'cmu-forward',subject:16,trial:'05',fps:120,label:'前跳',events:[72,114,160,194,264]},{id:'cmu-athletic',subject:16,trial:'07',fps:120,label:'舒展前跳',events:[181,219,271,310,378]},{id:'cmu-running',subject:75,trial:'01',fps:60,label:'跑跳',events:[110,128,151,166,204]}];
function tangents(knots){return knots.map((p,i)=>{if(i===0||i===knots.length-1)return 0;const a=knots[i-1],b=knots[i+1],h0=p[0]-a[0],h1=b[0]-p[0],s0=(p[1]-a[1])/h0,s1=(b[1]-p[1])/h1;if(s0*s1<=0)return 0;const w0=2*h1+h0,w1=h1+2*h0;return (w0+w1)/(w0/s0+w1/s1);});}
function sample(knots,t,slopes=tangents(knots)){let j=0;while(j<knots.length-2&&t>knots[j+1][0])j++;const [a,y0]=knots[j],[b,y1]=knots[j+1],u=clamp((t-a)/(b-a),0,1);return (2*u**3-3*u*u+1)*y0+(u**3-2*u*u+u)*slopes[j]*(b-a)+(-2*u**3+3*u*u)*y1+(u**3-u*u)*slopes[j+1]*(b-a);}
function fit(points,tolerance){const knots=[0,1,2,3,4].map(t=>points.find(p=>p[0]===t));let error=Infinity;for(let attempt=0;attempt<80;attempt++){const m=tangents(knots);let worst;error=0;for(const p of points){const e=Math.abs(sample(knots,p[0],m)-p[1]);if(e>error){error=e;worst=p;}}if(error<=tolerance)break;if(knots.some(k=>k[0]===worst[0]))throw Error('Curve fit stuck');knots.push(worst);knots.sort((a,b)=>a[0]-b[0]);}if(error>tolerance)throw Error('Curve fit error '+error);const slopes=tangents(knots);return {knots:knots.flatMap((p,i)=>[+p[0].toFixed(6),+p[1].toFixed(5),+slopes[i].toFixed(5)]),error};}
const summaries=[],output={};
for(const clip of clips){
 const asfName=clip.subject+'.asf',amcName=clip.subject+'_'+clip.trial+'.amc',raw=readFileSync(new URL(amcName,qa),'utf8'),rig=asf(readFileSync(new URL(asfName,qa),'utf8')),frames=amc(raw),rows=frames.map(f=>({...features(fk(rig,f)),frame:f.frame})),rest=rows.slice(0,30),mean=key=>rest.reduce((v,r)=>v+r.values[key],0)/rest.length,rootBaseline=rest.reduce((v,r)=>v+r.root[1],0)/rest.length,channels={};
 const timeline=frame=>{let i=0;while(i<3&&frame>clip.events[i+1])i++;return i+(frame-clip.events[i])/(clip.events[i+1]-clip.events[i]);};
 const selected=rows.filter(r=>r.frame>=clip.events[0]&&r.frame<=clip.events[4]);
 for(const key of [...channelNames,'drop']){
  const base=key==='drop'?0:key.startsWith('elbow_')?mean(key)*.3:mean(key),points=selected.map(r=>{let value=key==='drop'?Math.max(0,rootBaseline-r.root[1])*.85:r.values[key]-base;
   if(key.startsWith('hip_'))value=clamp(value,-.6,1.3);else if(key.startsWith('knee_'))value=clamp(value,0,1.75);else if(key.startsWith('arm_'))value=clamp(value,-1.2,1.8);else if(key.startsWith('elbow_'))value=clamp(value,.08,1.65);else if(key.startsWith('spread_'))value=clamp(value,-.07,.14);else if(key.startsWith('foot_'))value=clamp(value,-.45,.65);else if(key==='torso')value=clamp(value,-.15,.45);return [timeline(r.frame),value];});
  channels[key]=fit(points,key==='drop'?.0015:.025);
 }
 const sha256=createHash('sha256').update(raw).digest('hex');output[clip.id]={subject:clip.subject,trial:clip.trial,fps:clip.fps,events:clip.events,sha256,channels:Object.fromEntries(Object.entries(channels).map(([k,v])=>[k,v.knots]))};
 summaries.push({id:clip.id,frames:rows.length,events:clip.events,sha256,knots:Object.values(channels).reduce((n,v)=>n+v.knots.length/3,0),maxAngleFitError:Math.max(...Object.entries(channels).filter(([k])=>k!=='drop').map(([,v])=>v.error)),dropFitError:channels.drop.error});
}
const source='// Sparse C1 anatomical motion curves compiled from the CMU public database.\n// Times identify preparation / release / apex / contact / recovery, not frames.\nexport const JUMP_MOTIONS='+JSON.stringify(output)+';\n';
writeFileSync(new URL('../JumpMotionData.mjs',import.meta.url),source);const report={createdAt:new Date().toISOString(),bytes:Buffer.byteLength(source),clips:summaries};writeFileSync(new URL('cmu-jump-analysis.json',qa),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
