const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');const out=path.resolve(__dirname,'../qa/loading-and-face-capability');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.addInitScript(()=>{window.qaHeartbeats=0;setInterval(()=>{window.qaHeartbeats++;},100);});
 await page.goto('http://127.0.0.1:8879/?view=partitions&version=loading-r26',{waitUntil:'commit'});
 await page.waitForFunction(()=>window.failure||(window.HumanLoading?.percent>30&&HumanLoading.percent<68),null,{timeout:120000});
 assert(!await page.evaluate(()=>window.failure));
 const during=await page.evaluate(()=>({percent:HumanLoading.percent,stage:document.getElementById('loadingStage').textContent,elapsed:document.getElementById('loadingElapsed').textContent,heartbeats:qaHeartbeats,visible:!document.getElementById('loadingOverlay').hidden}));assert(during.visible&&during.percent>0);await page.screenshot({path:path.join(out,'loading-progress.png')});
 await page.waitForFunction(()=>window.HumanLoading?.finished,null,{timeout:180000});assert(!await page.evaluate(()=>window.failure));assert(await page.locator('#loadingOverlay').isHidden());
 const loaded=await page.evaluate(()=>({percent:HumanLoading.percent,history:HumanLoading.history,heartbeats:qaHeartbeats,elapsedMS:HumanLoading.elapsedMS,regions:HumanFace.shape.report.regions,points:HumanFace.shape.report.samples,front:HumanFace.frontLocked,eyes:HumanGame.subject.eyes.identityCalibration,geometry:{vertices:HumanGame.subject.surface.report.vertices,triangles:HumanGame.subject.surface.report.triangles}}));
 assert.equal(loaded.percent,100);assert.equal(loaded.regions,57);assert(loaded.front);assert(loaded.heartbeats>during.heartbeats);assert(loaded.history.length>100);assert(loaded.history.every((x,i)=>!i||x.percent>=loaded.history[i-1].percent));assert(loaded.history.some(x=>/表皮材质/.test(x.stage)));assert(loaded.history.some(x=>/首帧/.test(x.stage)));assert.equal(loaded.eyes.identityEditable,true);assert(Math.abs(loaded.eyes.centreDistanceMetres-.068)<1e-12);
 await page.locator('#faceCapabilityAudit').evaluate(e=>e.open=true);await page.locator('#faceCapabilityAudit').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'capability-audit.png')});assert((await page.locator('#faceCapabilityAudit').innerText()).includes('缺少独立比例控制'));await page.locator('#faceCapabilityAudit').evaluate(e=>e.open=false);
 // The skin controls remain actual geometry controls after worker generation.
 await page.selectOption('#faceRegion','noseTip');await page.fill('#shapeZ','1');await page.locator('#shapeApply').click();const shape=await page.evaluate(()=>HumanFace.shape.report);assert(shape.maxDisplacementMM>.7);await page.locator('#shapeReset').click();
 const failurePage=await browser.newPage();await failurePage.route('**/parameters.phf.gz',route=>route.fulfill({status:503,body:'Unavailable'}));await failurePage.goto('http://127.0.0.1:8879/?view=partitions',{waitUntil:'commit'});await failurePage.waitForFunction(()=>document.getElementById('loadingStage')?.textContent==='加载失败');assert(await failurePage.locator('#loadingRetry').isVisible());const failure=await failurePage.locator('#loadingDetail').innerText();assert(failure.includes('503'));await failurePage.screenshot({path:path.join(out,'loading-failure.png')});await failurePage.close();
 const hashes=Object.fromEntries(['LoadingProgress.js','SubjectLoading.mjs','SubjectLoadingWorker.mjs','SubjectRuntime.mjs','surface-generator.mjs','FacePartitionWorkbench.mjs','ProceduralEyes.mjs','app.mjs','index.html'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'..',f))).digest('hex')]));
 fs.writeFileSync(path.join(out,'review.json'),JSON.stringify({date:new Date().toISOString(),during,loaded,shape,failure,errors,hashes},null,2));assert.equal(errors.length,0);console.log(JSON.stringify({durationSeconds:loaded.elapsedMS/1000,events:loaded.history.length,heartbeats:loaded.heartbeats,regions:loaded.regions,points:loaded.points,eyes:loaded.eyes,shapeDisplacementMM:shape.maxDisplacementMM,failure,errors,out},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
