const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
 const root=path.resolve(__dirname,'..'),out=path.join(root,'qa/scar-r14');fs.mkdirSync(out,{recursive:true});
const files=['ScarState.mjs','ScarSurface.mjs','ScarWorkbench.mjs','SkinAppearance.mjs','SkinWorkbench.mjs','SubjectRuntime.mjs','FacialBinding.mjs','app.mjs','SkinMaterial.mjs'];
const hashes=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],report={date:new Date().toISOString(),sourceHashes:hashes(),checks:{},captures:[]};
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:8877/?version=R008-scar-13');await page.waitForFunction(()=>window.HumanGame||window.failure,null,{timeout:120000});
 async function setup(){await page.evaluate(()=>{if(window.failure)throw Error(window.failure);HumanR008.renderer.setAnimationLoop(null);HumanGame.setPaused(true);HumanGame.reset();HumanGame.controller.yaw=0;HumanGame.actor.rotation.y=0;HumanGame.subject.play('rest');HumanGame.faceExpression.setMode('neutral');HumanGame.faceExpression.update(HumanGame.controller,1);HumanGame.subject.eyes.setMode('centre');HumanGame.subject.eyes.update(0);HumanGame.actor.updateMatrixWorld(true);});}await setup();await page.selectOption('#skinPreset','reference');
 await page.evaluate(()=>{const g=HumanGame.subject.mesh.geometry;window.scarBaseline={p:g.attributes.position.array.slice(),n:g.attributes.normal.array.slice(),maps:HumanGame.subject.mesh.material.map(m=>m.map.uuid)};});
 async function capture(name,wide=false){const pixels=await page.evaluate(({wide})=>{document.querySelector('aside').style.visibility='hidden';const h=HumanGame;h.camera.position.set(wide?0:-.38,wide?1.25:1.30,wide?6.0:4.29);h.camera.lookAt(wide?0:-.26,wide?1.1:1.29,3.59);h.actor.updateMatrixWorld(true);h.subject.skeleton.update();const r=HumanR008.renderer;r.render(h.scene,h.camera);const gl=r.getContext(),buf=new Uint8Array(r.domElement.width*r.domElement.height*4);gl.readPixels(0,0,r.domElement.width,r.domElement.height,gl.RGBA,gl.UNSIGNED_BYTE,buf);if(!window.scarBaselinePixels)window.scarBaselinePixels=buf.slice();let changed=0;for(let i=0;i<buf.length;i++)if(buf[i]!==scarBaselinePixels[i])changed++;return {changed};},{wide});await page.screenshot({path:path.join(out,name+'.png')});await page.evaluate(()=>document.querySelector('aside').style.visibility='');report.captures.push(name);console.log('capture '+name);return pixels;}
 const base=await capture('original'),cleanAction=()=>page.locator('#scarClean').click();await cleanAction();const clean=await capture('clean');report.checks.removalChangedPixels=clean.changed;assert(report.checks.removalChangedPixels>1000);
 report.checks.localShapeOnly=await page.evaluate(()=>{const g=HumanGame.subject.mesh.geometry,b=scarBaseline;let changed=0,max=0,outside=0;for(let i=0;i<b.p.length;i+=3){const d=Math.hypot(...[0,1,2].map(k=>g.attributes.position.array[i+k]-b.p[i+k]));if(d>0){changed++;max=Math.max(max,d);const part=HumanGame.subject.data.charts.find(c=>c.id===HumanGame.subject.surface.chartIds[i/3]).part;if(![6,21,24].includes(part))outside++;}}return {changed,max,outside};});console.log(JSON.stringify(report.checks.localShapeOnly));assert(report.checks.localShapeOnly.changed>0&&report.checks.localShapeOnly.max<=.00201&&report.checks.localShapeOnly.outside===0);
 await page.locator('#scarOriginal').click();const restored=await capture('restored');assert.equal(restored.changed,0);assert(await page.evaluate(()=>HumanGame.subject.mesh.geometry.attributes.position.array.every((v,i)=>v===scarBaseline.p[i])));report.checks.exactOriginalRestore=true;
 for(const preset of ['fresh','scab','old','healed']){await page.selectOption('#scarPreset',preset);await capture(preset);}
 assert.equal(await page.locator('#scarInjure,#scarActive').count(),0);assert.equal(await page.evaluate(()=>typeof HumanScars.injure),'undefined');report.checks.syntheticScarRemoved=true;
 await page.selectOption('#scarRegion','rightShoulder');await page.selectOption('#scarPreset','original');await page.locator('#scarAuto').check();const start=await page.evaluate(()=>HumanSkin.export());await page.evaluate(()=>{HumanSkin.setAutomatic(false);HumanSkin.tick(60,true);});const progressed=await page.evaluate(()=>HumanSkin.export());assert.equal(progressed.scars.regions.rightShoulder.progress,.1);assert.equal(progressed.appearance.sunExposure,start.appearance.sunExposure);assert.equal(progressed.progression.elapsedHours,start.progression.elapsedHours);await page.evaluate(()=>HumanSkin.tick(60,false));assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),progressed);report.checks.independentHealingClockAndPause=true;
 await page.locator('#scarAdvance').click();assert.equal((await page.evaluate(()=>HumanScars.export())).regions.rightShoulder.progress,.2);await page.locator('#scarAuto').uncheck();
 const saved=await page.evaluate(()=>HumanSkin.export());await page.reload();await page.waitForFunction(()=>window.HumanGame||window.failure,null,{timeout:120000});await setup();assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),saved);report.checks.reloadRestore=true;
 await page.locator('#density').evaluate(e=>e.closest('details').open=true);await page.selectOption('#density','.020',{timeout:120000});assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),saved);await page.selectOption('#density','.012',{timeout:120000});await setup();report.checks.rebuildRestore=true;
 const bad=structuredClone(saved);bad.scars.regions.leftForearm.relief=-1;await page.locator('#skinImport').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>document.getElementById('skinMessage').textContent.includes('超出范围'));assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),saved);report.checks.invalidImportAtomic=true;
 const downloadPromise=page.waitForEvent('download');await page.locator('#skinExport').click();const download=await downloadPromise;await download.saveAs(path.join(out,'export.json'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(out,'export.json'))),saved);report.checks.exportRestore=true;
 await page.locator('#scarViewRight').click();const rightCamera=await page.evaluate(()=>HumanGame.camera.position.toArray());await page.locator('#scarViewLeft').click();const leftCamera=await page.evaluate(()=>HumanGame.camera.position.toArray());assert(rightCamera[0]<leftCamera[0]);await page.locator('#scarViewGame').click();report.checks.nearViewButtons=true;
 await page.selectOption('#scarRegion','all');await page.selectOption('#scarPreset','clean');await page.evaluate(()=>{HumanGame.subject.play('run');HumanGame.subject.setPaused(false);HumanGame.subject.step(.15);HumanGame.faceExpression.update(HumanGame.controller,.1);});await capture('clean-running',true);report.checks.animatedBinding=true;
 await setup();await page.selectOption('#scarPreset','fresh');await capture('fresh-full',true);await page.selectOption('#scarPreset','clean');await capture('clean-full',true);
 await page.evaluate(()=>{document.querySelector('aside').style.visibility='';document.getElementById('scarPanel').scrollIntoView();});await page.screenshot({path:path.join(out,'workbench.png')});report.captures.push('workbench');
 report.runtime=await page.evaluate(()=>{const gl=HumanR008.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,glError:gl.getError(),scars:HumanGame.subject.scars.report,stateBytes:new TextEncoder().encode(JSON.stringify(HumanSkin.export())).length};});assert.equal(report.runtime.glError,0);assert.equal(errors.length,0,errors.join('\n'));assert(report.runtime.stateBytes<4096);assert.deepEqual(hashes(),report.sourceHashes);report.errors=errors;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
