// Off-screen real-browser checks; never controls the desktop mouse.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(__dirname,'../qa/skin-r12');fs.mkdirSync(out,{recursive:true});
const sourceFiles=['ScarState.mjs','ScarSurface.mjs','ScarWorkbench.mjs','FacialBinding.mjs','SkinAppearance.mjs','SkinMaterial.mjs','SkinWorkbench.mjs','SubjectRuntime.mjs','ProceduralEyes.mjs','app.mjs'],hashSources=()=>Object.fromEntries(sourceFiles.map(f=>[f,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'../',f))).digest('hex')]));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto((process.env.HUMAN_PREVIEW_URL||'http://127.0.0.1:8877/')+'?version=R008-skin-12');await page.waitForFunction(()=>window.HumanGame||window.failure,null,{timeout:120000});
 await page.evaluate(()=>{if(window.failure)throw Error(window.failure);HumanR008.renderer.setAnimationLoop(null);HumanGame.setPaused(true);HumanGame.reset();HumanGame.controller.yaw=0;HumanGame.actor.rotation.y=0;HumanGame.actor.updateMatrixWorld(true);HumanGame.subject.play('rest');HumanGame.faceExpression.setMode('neutral');HumanGame.faceExpression.update(HumanGame.controller,1);HumanGame.subject.eyes.setMode('centre');HumanGame.subject.eyes.update(0);window.skinBaseline={p:HumanGame.subject.mesh.geometry.attributes.position.array.slice(),n:HumanGame.subject.mesh.geometry.attributes.normal.array.slice(),maps:HumanGame.subject.mesh.material.map(m=>m.map.uuid)};});
 const report={date:new Date().toISOString(),sourceHashes:hashSources(),errors,captures:[],checks:{}};
 async function view(name,head=false){await page.evaluate(({head})=>{const h=HumanGame;h.camera.position.set(0,head?1.665:1.15,head?4.22:6.55);h.camera.lookAt(0,head?1.653:1.02,3.6);HumanR008.renderer.render(h.scene,h.camera);},{head});await page.screenshot({path:path.join(out,name+'.png')});report.captures.push(name);if(!head){const pixels=await page.evaluate(name=>{const r=HumanR008.renderer,gl=r.getContext(),width=r.domElement.width,height=r.domElement.height,buf=new Uint8Array(width*height*4);r.render(HumanGame.scene,HumanGame.camera);gl.readPixels(0,0,width,height,gl.RGBA,gl.UNSIGNED_BYTE,buf);const regions={chest:[660,370,780,440],leg:[655,790,680,890],shorts:[675,575,765,655]};window.skinPixels??={};const rows={};for(const [key,[x0,y0,x1,y1]]of Object.entries(regions)){let total=0,maxDiff=0;const crop=[];for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=((height-1-y)*width+x)*4;crop.push(buf[i],buf[i+1],buf[i+2]);total+=.2126*buf[i]+.7152*buf[i+1]+.0722*buf[i+2];}if(name==='arrival')skinPixels[key]=crop;else if(skinPixels[key])maxDiff=Math.max(...crop.map((v,i)=>Math.abs(v-skinPixels[key][i])));rows[key]={luminance:total/((x1-x0)*(y1-y0)),maxArrivalDifference:maxDiff};}return rows;},name);(report.pixelChecks??={})[name]=pixels;}}
 for(const [preset,name]of [['reference','reference'],['arrival','arrival'],['week','week'],['month','month']]){await page.selectOption('#skinPreset',preset);await view(name);await view(name+'-head',true);}
 report.checks.noSurfaceMutation=await page.evaluate(()=>{const g=HumanGame.subject.mesh.geometry,b=skinBaseline;return g.attributes.position.array.every((v,i)=>v===b.p[i])&&g.attributes.normal.array.every((v,i)=>v===b.n[i])&&HumanGame.subject.mesh.material.every((m,i)=>m.map.uuid===b.maps[i]);});assert(report.checks.noSurfaceMutation);
 for(const region of ['chest','leg'])assert(report.pixelChecks.arrival[region].luminance>report.pixelChecks.week[region].luminance&&report.pixelChecks.week[region].luminance>report.pixelChecks.month[region].luminance);assert(report.pixelChecks.month.shorts.maxArrivalDifference<=1,'Excluded-clothing pixel tolerance: one 8-bit quantisation step');report.checks.visiblePigmentAndExcludedClothing=true;
 await page.locator('#skinAuto').check();report.checks.gameClock=await page.evaluate(()=>{const h=HumanGame,before=HumanSkin.export();h.setPaused(false);for(let i=0;i<10;i++)h.step(.1,false);const running=HumanSkin.export();h.setPaused(true);for(let i=0;i<10;i++)h.step(.1,false);const paused=HumanSkin.export();return {hours:running.progression.elapsedHours-before.progression.elapsedHours,sunHours:running.progression.equivalentSunHours-before.progression.equivalentSunHours,pausedUnchanged:JSON.stringify(paused)===JSON.stringify(running)};});assert(Math.abs(report.checks.gameClock.hours-.4)<1e-8&&Math.abs(report.checks.gameClock.sunHours-.1)<1e-8&&report.checks.gameClock.pausedUnchanged);
 const beforeManual=await page.evaluate(()=>HumanSkin.export());await page.locator('#action').evaluate(e=>e.closest('details').open=true);await page.selectOption('#action','rest');await page.evaluate(()=>{HumanGame.setPaused(false);for(let i=0;i<10;i++)HumanGame.step(.1,false);HumanGame.setPaused(true);});assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),beforeManual);await page.selectOption('#action','game');await page.locator('#skinAuto').uncheck();report.checks.manualInspectionStopsProgress=true;
 await page.selectOption('#skinPreset','arrival');await page.locator('#skinAdvanceDay').click();const oneDay=await page.evaluate(()=>HumanSkin.export());assert.equal(oneDay.progression.elapsedHours,24);assert.equal(oneDay.progression.equivalentSunHours,6);assert(oneDay.appearance.sunExposure>0);
 await page.locator('#skinAuto').check();await page.evaluate(()=>{HumanGame.setPaused(true);HumanSkin.tick(60,true);});const auto=await page.evaluate(()=>HumanSkin.export());assert.equal(auto.progression.elapsedHours,48);assert.equal(auto.progression.equivalentSunHours,12);
 await page.evaluate(()=>HumanSkin.tick(60,false));assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),auto);report.checks.autoTimeAndPause=true;
 await page.evaluate(()=>HumanSkin.advance(24,{uv:0}));const shade=await page.evaluate(()=>HumanSkin.export());assert.equal(shade.appearance.sunExposure,auto.appearance.sunExposure);report.checks.shadeAndNight=true;
 await page.locator('#skinAuto').uncheck();const saved=await page.evaluate(()=>HumanSkin.export());await page.reload();await page.waitForFunction(()=>window.HumanGame||window.failure,null,{timeout:120000});assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),saved);report.checks.reloadRestore=true;
 await page.evaluate(()=>{HumanR008.renderer.setAnimationLoop(null);HumanGame.setPaused(true);});await page.locator('#skinAuto').uncheck();await page.selectOption('#skinPreset','month');const beforeRebuild=await page.evaluate(()=>HumanSkin.export());await page.locator('#density').evaluate(e=>e.closest('details').open=true);await page.selectOption('#density','.020',{timeout:120000});assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),beforeRebuild);report.checks.rebuildPreservesSkin=true;
 await page.evaluate(()=>{HumanGame.subject.eyes.setMode('closed');HumanGame.subject.eyes.update(.1);});await view('month-closed',true);
 await page.selectOption('#density','.012',{timeout:120000});await page.evaluate(()=>{HumanGame.subject.eyes.setMode('centre');HumanGame.subject.eyes.update(.1);});
 await page.locator('#skinImport').setInputFiles({name:'invalid-skin.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schema:'invalid'}))});await page.waitForFunction(()=>document.getElementById('skinMessage').textContent.includes('不匹配'));assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),beforeRebuild);report.checks.invalidImportAtomic=true;
 const imported={...beforeRebuild,appearance:{...beforeRebuild.appearance,baseColor:'#d8b599',sunExposure:.42}};await page.locator('#skinImport').setInputFiles({name:'island-skin.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>document.getElementById('skinMessage').textContent.includes('已恢复'));assert.deepEqual(await page.evaluate(()=>HumanSkin.export()),imported);report.checks.importRestore=true;
 const downloadPromise=page.waitForEvent('download');await page.locator('#skinExport').click();const download=await downloadPromise;await download.saveAs(path.join(out,'exported-skin.json'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(out,'exported-skin.json'),'utf8')),imported);report.checks.exportRestore=true;
 await page.locator('#skinArrival').click();const arrived=await page.evaluate(()=>HumanSkin.export());assert.equal(arrived.appearance.sunExposure,0);assert.equal(arrived.progression.elapsedHours,0);assert.equal(await page.locator('#skinAuto').isChecked(),false);report.checks.arrivalReset=true;
 report.gpu=await page.evaluate(()=>{const gl=HumanR008.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,glError:gl.getError(),skin:HumanGame.subject.skin.report};});assert.equal(report.gpu.glError,0);assert.equal(errors.length,0,errors.join('\n'));
 assert.deepEqual(hashSources(),report.sourceHashes,'Runtime sources changed during capture');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
