import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {CharacterController,angleDelta,MOVEMENT} from '../CharacterController.mjs';
import {WORLD} from '../game-world.mjs';
const advance=(c,t,dt=1/120)=>{for(let i=0;i<Math.round(t/dt);i++)c.update(dt);};
const cases=[];function test(name,fn){fn();cases.push(name);}
test('A walking character cannot penetrate the low wall',()=>{const c=new CharacterController();c.press('KeyW');advance(c,3);assert(c.z>=-.12501);assert(c.blocked);assert.equal(c.y,0);});
test('Jumping lands on the actual 0.65 m wall top',()=>{const c=new CharacterController();c.press('KeyW');advance(c,3);c.press('Space');advance(c,.72);c.release('KeyW');advance(c,.35);assert.equal(c.y,.65);assert(c.grounded);assert.equal(c.support,'low-wall');assert(c.landings.some(l=>l.id==='low-wall'));assert.equal(c.jumpCount,1);advance(c,2);assert.equal(c.jumpCount,1);});
test('A jump from the ground lands on the 0.8 m platform',()=>{const c=new CharacterController();c.z=-2.149999;c.press('KeyW');advance(c,.3);c.press('Space');advance(c,.8);c.release('KeyW');advance(c,.2);assert(c.grounded);assert.equal(c.y,.8);assert.equal(c.support,'platform');assert(c.landings.some(l=>l.id==='platform'));});
test('A running jump from the wall crosses the gap onto the platform',()=>{const c=new CharacterController();c.y=.65;c.z=-1;c.support='low-wall';c.press('KeyW');c.press('ShiftLeft');c.press('Space');advance(c,.8);c.release('KeyW');advance(c,.2);assert(c.grounded);assert.equal(c.y,.8);assert.equal(c.support,'platform');});
test('Walking off a ledge during accepted jump preparation still takes off',()=>{const c=new CharacterController();c.y=.65;c.z=-1.4;c.vz=-1.65;c.support='low-wall';c.press('KeyW');c.press('Space');advance(c,.1);assert.equal(c.jumpCount,1);assert(c.vy>0);});
test('Running jump cannot cross the 1.7 m high wall',()=>{const c=new CharacterController();c.x=3.4;c.z=2;c.press('KeyW');c.press('ShiftLeft');advance(c,1);c.press('Space');advance(c,1);assert(c.z>=-.40001);assert.equal(c.y,0);});
test('Four 18 cm steps are walkable without a jump',()=>{const c=new CharacterController();c.x=-3.4;c.z=2.2;c.press('KeyW');advance(c,2.35);assert.equal(c.jumpCount,0);assert.equal(c.support,'step-4');assert.equal(c.y,.72);});
test('Diagonal input has the same speed as axial input',()=>{const empty={...WORLD,boxes:[]},a=new CharacterController(empty),b=new CharacterController(empty);a.press('KeyW');b.press('KeyW');b.press('KeyD');advance(a,1);advance(b,1);assert(Math.abs(a.speed-b.speed)<1e-6);assert(Math.abs(b.speed-MOVEMENT.walkSpeed)<.001);});
test('Sudden run reversal ramps angular speed and settles within 1.2 seconds',()=>{const c=new CharacterController({...WORLD,boxes:[]});c.press('KeyW');c.press('ShiftLeft');advance(c,.5);c.release('KeyW');c.press('KeyS');const yaw=c.yaw;c.update(1/120);assert(Math.abs(angleDelta(yaw,c.yaw))<.02);assert(Math.abs(angleDelta(c.yaw,0))>2);advance(c,1.2);assert(Math.abs(angleDelta(c.yaw,0))<.001);assert(Math.abs(c.turnRate)<=6);assert(c.vz>4);});
test('Render frame rate does not change the movement trajectory',()=>{const empty={...WORLD,boxes:[]},a=new CharacterController(empty),b=new CharacterController(empty);a.press('KeyW');b.press('KeyW');a.press('Space');b.press('Space');advance(a,2,1/30);advance(b,2,1/120);assert(Math.abs(a.z-b.z)<1e-8);assert.equal(a.jumpCount,b.jumpCount);assert.equal(a.y,b.y);});
test('Lost focus clears motion input and pending jump',()=>{const c=new CharacterController();c.press('KeyW');c.press('Space');c.clearInput();advance(c,1);assert.equal(c.z,WORLD.spawn.z);assert.equal(c.jumpCount,0);assert.equal(c.keys.size,0);});
test('Late ledge jump is accepted within coyote time',()=>{const c=new CharacterController();c.y=.65;c.z=-1.415;c.press('KeyW');advance(c,.1);assert(!c.grounded);c.press('Space');advance(c,.03);assert(c.vy>0);assert.equal(c.jumpCount,1);});
const report={createdAt:new Date().toISOString(),passed:cases.length,cases};mkdirSync(new URL('../qa/',import.meta.url),{recursive:true});writeFileSync(new URL('../qa/controller-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
