const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),path=require('node:path');const qa=path.resolve(__dirname,'../qa');
const assert=(v,m)=>{if(!v)throw Error(m)};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],forbidden=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>{if(/\.(fbx|obj|glb|gltf|png|jpg|jpeg)(\?|$)/i.test(r.url()))forbidden.push(r.url())});await p.goto('http://127.0.0.1:8877/?version=R008-face-1');await p.waitForFunction(()=>window.HumanFace||window.failure,null,{timeout:120000});assert(!await p.evaluate(()=>window.failure),'Startup failed');
 const report={url:p.url(),default:await p.evaluate(async()=>{const {FACE_REGIONS,sampleFaceWeights,resolveFaceAction}=await import('../FacialBinding.mjs'),s=HumanGame.subject,g=s.mesh.geometry,baseP=new Float32Array(g.attributes.position.array),baseN=new Float32Array(g.attributes.normal.array),a=s.face,rows=a.rows;let minJacobian=1,maxDisplacement=0,changedNonface=0,nonfinite=0,weightRangeErrors=0,seamMaxDifference=0,seamPairs=0;const seam=new Map();
  for(let k=0;k<rows.vertices.length;k++){const i=rows.vertices[k],p=Array.from(baseP.subarray(i*3,i*3+3)),key=p.map(v=>Math.round(v*1e6)).join(',');const w=sampleFaceWeights(p);for(const v of w)if(!Number.isFinite(v)||v<0||v>1)weightRangeErrors++;if(seam.has(key)){const old=seam.get(key);seamPairs++;seamMaxDifference=Math.max(seamMaxDifference,...w.map((v,j)=>Math.abs(v-old[j])));}else seam.set(key,w);}
  for(const r of FACE_REGIONS.filter(r=>r.kind==='skin')){const d=a.deform(r.id,1);minJacobian=Math.min(minJacobian,d.minJacobian);maxDisplacement=Math.max(maxDisplacement,d.maxDisplacement);}
  a.deform('mouthCornerLeft',1);const faceIds=new Set(rows.vertices);for(let i=0;i<baseP.length/3;i++){if(!faceIds.has(i))for(let j=0;j<3;j++)if(baseP[i*3+j]!==g.attributes.position.array[i*3+j])changedNonface++;}for(const value of [...g.attributes.position.array,...g.attributes.normal.array])if(!Number.isFinite(value))nonfinite++;
  a.reset();let restoredPositions=0,restoredNormals=0;for(let i=0;i<baseP.length;i++){if(baseP[i]!==g.attributes.position.array[i])restoredPositions++;if(baseN[i]!==g.attributes.normal.array[i])restoredNormals++;}
  const probes={eyeSkin:s.face.sample([.034,1.656,.102]).filter((_,i)=>FACE_REGIONS[i].kind==='skin'),rear:s.face.sample([0,1.65,-.06]),hair:s.face.sample([0,1.75,.10]),neck:s.face.sample([0,1.49,.09])};
  const gl=HumanR008.renderer.getContext();return {...a.report,minJacobian,maxDisplacement,changedNonface,nonfinite,weightRangeErrors,seamPairs,seamMaxDifference,restoredPositions,restoredNormals,protectedProbes:probes,actionContract:{smileLeft:resolveFaceAction('mouthSmile','Left'),blinkRight:resolveFaceAction('eyeBlink','Right'),jaw:resolveFaceAction('jawOpen','Both')},renderer:gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info').UNMASKED_RENDERER_WEBGL)};
 })};
 fs.writeFileSync(path.join(qa,'face-numeric-report.json'),JSON.stringify(report.default,null,2)); assert(report.default.channels.every(c=>c.samples>0),'Empty facial field');assert(report.default.nonfinite===0&&report.default.weightRangeErrors===0,'Nonfinite/out-of-range field');assert(report.default.minJacobian>.6&&report.default.maxDisplacement<=.001501,'Pull folds/overextends surface');assert(report.default.changedNonface===0&&report.default.restoredPositions===0&&report.default.restoredNormals===0,'Neutral/body changed');assert(Object.values(report.default.protectedProbes).flat().every(v=>v===0),'Hair/eye/neck/rear leakage');assert(report.default.seamMaxDifference<.002,'Weight discontinuity at seams');
 await p.locator('#facePanel summary').click();await p.locator('#faceEnter').click();await p.waitForTimeout(200);assert(await p.evaluate(()=>HumanFace.active),'Face mode did not enter');await p.screenshot({path:path.join(qa,'face-regions-current.png')});
 await p.selectOption('#faceRegion','mouthCornerLeft');await p.screenshot({path:path.join(qa,'face-mouth-weight.png')});await p.selectOption('#faceView','skin');await p.locator('#facePull').evaluate(e=>{e.value='1';e.dispatchEvent(new Event('input',{bubbles:true}));});report.uiPull=await p.evaluate(()=>HumanFace.lastPull);await p.screenshot({path:path.join(qa,'face-pull-current.png')});assert(report.uiPull.maxDisplacement>.0002,'Pull control did not change surface');await p.locator('#faceNeutral').click();assert(await p.evaluate(()=>HumanGame.subject.face.amount===0),'Reset control failed');
 await p.locator('#faceLeft').click();await p.screenshot({path:path.join(qa,'face-side-current.png')});await p.locator('#faceFront').click();await p.screenshot({path:path.join(qa,'face-neutral-current.png')});await p.selectOption('#faceRegion','lidUpperRight');assert(await p.locator('#facePull').isDisabled(),'Unsafe eyelid pull enabled');await p.locator('#faceLandmarks').check();await p.selectOption('#faceView','weights');await p.screenshot({path:path.join(qa,'face-eyelid-weight.png')});
 await p.locator('#faceEnter').click();assert(!await p.evaluate(()=>HumanFace.active),'Exit failed');assert(await p.evaluate(()=>HumanGame.subject.mesh.geometry.attributes.faceInspection.array.every((v,i)=>i%4!==3||v===0)),'Overlay remains in game');await p.locator('#start').click();await p.keyboard.down('w');await p.waitForTimeout(550);await p.keyboard.up('w');report.afterWalk=await p.evaluate(()=>HumanGame.controller.snapshot());assert(report.afterWalk.speed>.5,'WASD not restored');await p.keyboard.press('Space');await p.waitForTimeout(500);report.afterJump=await p.evaluate(()=>HumanGame.controller.snapshot());assert(!report.afterJump.grounded,'Jump not restored');await p.waitForTimeout(1100);
 await p.getByText('骨架与表面检查',{exact:true}).click();await p.locator('#density').selectOption('.020');await p.waitForFunction(()=>HumanGame.subject.surface.report.vertices<200000);report.lite=await p.evaluate(()=>HumanGame.subject.face.report);assert(report.lite.channels.every(c=>c.samples>0),'Empty field after density regeneration');await p.locator('#faceEnter').click();assert(await p.evaluate(()=>HumanFace.active),'Inspector failed after rebuild');await p.locator('#faceEnter').click();
 await p.locator('#regions').check();await p.locator('#bones').check();await p.locator('#faceEnter').click();assert(await p.evaluate(()=>!document.getElementById('regions').checked&&!HumanGame.subject.helper.visible),'Inspection did not hide body diagnostics');await p.locator('#faceEnter').click();assert(await p.evaluate(()=>document.getElementById('regions').checked&&HumanGame.subject.helper.visible),'Body diagnostic state was not restored');await p.locator('#regions').uncheck();await p.locator('#bones').uncheck();
 report.errors=errors;report.forbiddenRequests=forbidden;fs.writeFileSync(path.join(qa,'face-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({regions:report.default.regions,samples:report.default.sampledVertices,liteSamples:report.lite.sampledVertices,rangeErrors:report.default.weightRangeErrors,seamPairs:report.default.seamPairs,seamError:report.default.seamMaxDifference,minJacobian:report.default.minJacobian,restoredPositions:report.default.restoredPositions,restoredNormals:report.default.restoredNormals,errors,forbidden},null,2));assert(errors.length===0&&forbidden.length===0,'Browser/runtime errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
