const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict'),vm=require('node:vm'),esbuild=require('esbuild');
const ROOT=path.resolve(__dirname,'..'),BASE='c4cad2026f10b656a4bc00568be11dcf7429c44f',P='skin-quality-lab/emily-transfer/',hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function base(name){try{return cp.execFileSync('git',['show',BASE+':'+P+name],{encoding:'utf8',maxBuffer:12e6});}catch(e){cp.execFileSync('git',['fetch','--depth=1','origin',BASE],{stdio:'inherit'});return cp.execFileSync('git',['show',BASE+':'+P+name],{encoding:'utf8',maxBuffer:12e6});}}
let source=base('app.js'),app=source,html=base('index.html');assert.equal(hash(source),'03ed76f520092880bb5e1c396931ed3af475d5da9ecb045831dc3d3ac727e04f');
function patch(a,b){assert.equal(app.split(a).length,2,'Missing unique S1.1 anchor: '+a);app=app.replace(a,()=>b);}
patch("import {EYE_VERSION,ContourEyes as EyeSystem} from './stage1/ContourEyes.js';","import {EYE_VERSION,SectionEyes as EyeSystem} from './stage2/SectionEyes.js';\nimport {createSectionReview} from './stage2/SectionReview.js';");
patch("VERSION='emily-transfer/8.0.1-s1'","VERSION='emily-transfer/9.0.0-s2'");
patch('installGrayBoundaryOverlap(eyesRig);render();','installGrayBoundaryOverlap(eyesRig);stage1View=createSectionReview({rig:eyesRig,mesh,skin,fuzz,renderer,scene,camera,controls,key,fill,rim,state,requestRender:()=>{dirty=true;renderer.shadowMap.needsUpdate=true;},setCamera},stage1View);render();');
html=html.replace(/<title>[^<]*<\/title>/,'<title>眼角与眼睑分层 · ET09 第二阶段</title>');
fs.writeFileSync(ROOT+'/app.js',app);fs.writeFileSync(ROOT+'/index.html',html);
const vendor=path.resolve(ROOT,'../r01/vendor');
const result=esbuild.buildSync({entryPoints:[ROOT+'/app.js'],bundle:true,minify:true,format:'iife',target:'es2022',write:false,metafile:true,legalComments:'inline',alias:{three:vendor+'/three.module.js','three/addons':vendor+'/addons'}});
const inputs=Object.keys(result.metafile.inputs);assert.equal(inputs.filter(p=>/three\.core\.js$/.test(p)).length,1);
const assetCommit='5be35195ad40d57507f7ab1785e4eecda6c648de',assetRoot='https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/'+assetCommit+'/skin-quality-lab/';
const code=result.outputFiles[0].text.replaceAll('../r01/',assetRoot+'r01/').replaceAll('../r02/',assetRoot+'r02/').replace(/<\/script/gi,'<\\/script');new vm.Script(code);
let preview=html.replace(/<script type="importmap">[\s\S]*?<\/script>/,'').replace('<script type="module" src="./app.js"></script>',()=>'<script>'+code+'</script>');preview=preview.replaceAll('../r01/',assetRoot+'r01/').replaceAll('../r02/',assetRoot+'r02/');
const notice=fs.readFileSync(ROOT+'/talkinghead/vendor/TalkingHeadBehavior.mjs','utf8').match(/^\/\*\*[\s\S]*?\*\//)?.[0];assert(notice?.includes('MIT License'));preview=preview.replace('</head>',()=>'<!--\n'+notice.replaceAll('-->','-- >')+'\n-->\n</head>');
const scripts=[...preview.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script\s*>/gi)];assert.equal(scripts.length,1);assert.equal(scripts[0][1],code);new vm.Script(scripts[0][1]);fs.writeFileSync(ROOT+'/preview.html',preview);
const manifest={schema:'kaopu/eyelid-section-build@1',version:'ET09-S2',codeVersion:'emily-transfer/9.0.0-s2',eyeVersion:'eyes/9.0.0-s2',baseline:BASE,assetCommit,baselineAppSHA256:hash(source),appSHA256:hash(app),previewSHA256:hash(preview),previewBytes:Buffer.byteLength(preview),finalHTMLSyntaxValidated:true,oneThreeCore:true,oneRenderer:true,hostAnimationLoopOnly:true,sourceHeadMeshChanged:false,sourceSkinTexturesChanged:false,stage1SourceFilesChanged:false,globeRadiusChanged:false,globeCentreDepthChanged:false,firstStageXYContourChanged:false,openCanthalDepthSmoothed:true,canthalAnchorPositionsChanged:false,closedSurfaceTargetChanged:false,upperLidSectionRebuilt:true,lowerLidSectionRebuilt:true,medialCanthusRebuilt:true,temporalCommissureAdded:true,stage3MaterialCoordinatesRebuilt:false,stage4PhysicsRebuilt:false,stage5OpticsRebuilt:false,personSpecificOpenScanAvailable:false,actualWebBrowserVerification:'stage2/qa-report.json and current Actions public artifact',realMobileDeviceTested:false,visualAcceptance:'pending user review; geometric fit, not a medical reconstruction'};
fs.writeFileSync(ROOT+'/BUILD_MANIFEST.json',JSON.stringify(manifest,null,2));fs.writeFileSync(__dirname+'/bundle-inputs.json',JSON.stringify(inputs,null,2));console.log('ET09_STAGE2_BUILD',JSON.stringify(manifest));
