import {materialize} from './materialize.mjs';
import {adaptTurntable} from './adapt-turntable.mjs';
materialize();
import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {esbuild,playwright} from './dependencies.mjs';const {build}=esbuild();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),safe=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const native=await build({entryPoints:[path.join(root,'src/native.js')],bundle:true,format:'iife',minify:true,write:false,target:'es2022',alias:{three:path.join(root,'vendor/three.module.js')},legalComments:'inline'});
const beachBundle=await build({entryPoints:[path.join(root,'src/beach-runtime.js')],bundle:true,format:'iife',minify:true,write:false,target:'es2022',legalComments:'inline'});
const turntableBundle=await build({entryPoints:[path.join(root,'src/turntable.js')],bundle:true,format:'iife',minify:true,write:false,target:'es2022',legalComments:'inline'});const turntableScript=turntableBundle.outputFiles[0].text;
const beachScript='/* '+read('vendor/tidewater/LICENSE')+' */\n'+beachBundle.outputFiles[0].text;
const nativeHtml='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><style>html,body{margin:0;overflow:hidden;width:100%;height:100%}canvas{width:100%;height:100%;display:block}</style></head><body><canvas></canvas><script>/* '+read('vendor/tidewater/LICENSE')+' */\n'+native.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></body></html>';
fs.writeFileSync(path.join(root,'assets/native.html'),nativeHtml);
const imported=await build({entryPoints:[path.join(root,'src/imported.js')],bundle:true,format:'iife',minify:true,write:false,target:'es2022',alias:{three:path.join(root,'vendor/three.module.js')},legalComments:'inline'});
const importedHtml='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><style>html,body{margin:0;overflow:hidden;width:100%;height:100%}canvas{display:block}</style></head><body><script>/* '+read('vendor/tidewater/LICENSE')+' */\n'+imported.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></body></html>';fs.writeFileSync(path.join(root,'assets/imported.html'),importedHtml);

const manifest={scenes:{turntable:JSON.parse(read('references/pandanus-display/PROVENANCE.json')),fish:JSON.parse(read('references/fish-scene/PROVENANCE.json')),beach:JSON.parse(read('references/tidewater/PROVENANCE.json'))},schema:'animal-atlas/source-manifest@1',builtAt:new Date().toISOString(),version:'1.2.0',sources:[]},sourceNames={fish:'Fish-Workbench/local-r13 · complete sampled surface, KFE1 eyes and interactive school',eagle:'Eagle-Workbench · R07 connected surface and life runtime',crab:'Crab-Life-R06/public/index.html · R11',palau:'Palau-Bird-Workbench · R04 full surface and anatomical rig',chicken:'haihao0307/Humanoid-Rig-Lab-Next@codex/chicken-r984-natural-head · CHICKEN_V46_R9_8_4_NATURAL_FACE.html','cat-v440':'Cat-V440-Repo · Cat Kaopu V4.40',native:'haihao0307/guilin-dem-pipeline@748f8793ea7ca84c30a2c441b6a63ce5c95ce13a · K5 mammals and K4 quadrupeds'};
let payloads='',assets={};const frameStyle=`html,body{width:100%!important;height:100%!important;margin:0!important;overflow:hidden!important}body{background:#17343c!important}header,aside,footer,.topbar,.controls,.footer,.panel-label,.toolbar,.observer,.composer,.life-visual-ui,.life-visual-settings,.life-visual-panel,#lifeUnifiedMark,.labels,.scene-badge,.scene-nav,.hint,.playbar,#badge,#status,#viewStrip,#identity,#dock,#restoreUI,#offscreen,#lifeEcologyRecorder,#lifeEcologyDock,#lifeEcologyPanel,.life-ecology-panel,.life-ecology-dock,#story,#teacherLabel,#activeLabel,#stats,#statusBox,.overlay,.world-title,.actor-label,.world-label{display:none!important}#stage,#viewport,.stage,.viewer{position:fixed!important;inset:0!important;display:block!important;width:100vw!important;height:100vh!important;min-height:0!important;margin:0!important;border:0!important;overflow:hidden!important}.app,.shell,.layout,.main,main{display:block!important;grid-template-columns:1fr!important;grid-template-rows:1fr!important;height:100vh!important;width:100vw!important;padding:0!important;margin:0!important}#stage>canvas,#viewport>canvas,.stage>canvas{display:block!important;width:100%!important;height:100%!important}#cards{position:fixed!important;inset:0!important;display:block!important;margin:0!important;padding:0!important}#cards article{margin:0!important;padding:0!important;border:0!important;border-radius:0!important;height:100vh!important;width:100vw!important;background:transparent!important}#cards article h2,#cards article p,body>p,body>details,.transport{display:none!important}#cards article canvas{display:block!important;width:100%!important;height:100%!important}#loading.hidden,#loader.done{display:none!important}`;
for(const filename of fs.readdirSync(path.join(root,'assets')).filter(p=>p.endsWith('.html')&&!p.includes('r91'))){const key=path.basename(filename,'.html'),source=fs.readFileSync(path.join(root,'assets',filename)),sourceSha=hash(source);let html=source.toString('utf8');html=html.replace(/<head[^>]*>/i,m=>m+'<script>'+turntableScript.replaceAll('</script','<\\/script')+'</script>');
 if(key==='fish'){
 html=html.replace('dt=Math.min(.08,elapsed)','dt=Math.max(0,Math.min(.08,elapsed))');
 html=html.replace('projection:mat4Ortho(-halfW,halfW,-halfH,halfH,.01,20)',"projection:globalThis.AtlasFishHabitat.projection(halfW,halfH,this.distance,.01,250)");
 html=html.replace("return{origin:eye.map((v,k)=>v+right[k]*nx*halfW+up[k]*ny*halfH),direction};","return{origin:eye,direction:normalize3(direction.map((v,k)=>v+right[k]*nx*halfW/this.camera.distance+up[k]*ny*halfH/this.camera.distance))};");
 html=html.replace('uniform int uMode,uWeightChannel;','uniform int uMode,uWeightChannel;uniform float uAtlasDensity;uniform bool uAtlasEnvironment;');
 html=html.replace('outColor=vec4(toSRGB(clamp(lit,0.,1.)),1);',`if(uAtlasEnvironment&&uMode==0){float distanceM=length(vViewPos);float haze=1.-exp(-distanceM*uAtlasDensity*.13);lit*=vec3(.78,.96,1.);lit=mix(lit,vec3(.028,.21,.25),haze*.55);}outColor=vec4(toSRGB(clamp(lit,0.,1.)),1);`);
 html=html.replace("gl.uniform1i(u('uSchool'),this.state.school?1:0);","gl.uniform1i(u('uSchool'),this.state.school?1:0);gl.uniform1i(u('uAtlasEnvironment'),this.state.environment===false?0:1);gl.uniform1f(u('uAtlasDensity'),this.state.waterDensity??1);");
 html=html.replace('const m=this.camera.mvp(w/h);this.applyMesh','const m=this.camera.mvp(w/h);globalThis.AtlasFishHabitat?.draw(gl,m,this.state);this.applyMesh').replace('gl.clearColor(.035,.055,.072,1)','gl.clearColor(.028,.14,.19,1)').replace('const renderer=new Renderer(canvas,h,gl,textures);','window.__ATLAS_FISH_TEXTURE_BYTES__=h.textures.base;await AtlasFishHabitat.prepare(canvas,gl);const renderer=new Renderer(canvas,h,gl,textures);');
 html=html.replace('<script>\'use strict\';',()=>'<script>'+read('src/reference-water-runtime.js').replaceAll('</script','<\\/script')+'</script><script>\'use strict\';');
 if(!html.includes('AtlasFishHabitat?.draw')||!html.includes('await AtlasFishHabitat.prepare'))throw Error('Fish habitat hook failed');
 }
 if(key.startsWith('life-')){html=html.replace('window.__LIFE_VISUAL = engine;','engine.animal=animal;window.__ATLAS_THREE=T;window.__LIFE_VISUAL = engine;').replace('const raw=Math.min(.05,(now-lastTime)/1000||0);','const raw=window.__ATLAS_PAUSED?0:Math.min(.05,(now-lastTime)/1000||0);').replace('function tick(dt){\n simTime+=dt;','function tick(dt){if(window.__ATLAS_PAUSED)return;\n simTime+=dt;').replace('function tick(dt){lifeVisualClock+=dt;','function tick(dt){if(window.__ATLAS_PAUSED)return;lifeVisualClock+=dt;');}
 if(['life-pig','life-bruce','life-cat'].includes(key)){
 html=html.replace(/<head[^>]*>/i,m=>m+'<script>'+beachScript.replaceAll('</script','<\\/script')+'</script>');
 const anchor='const world = LV.worlds(T, G, M, U).create(kind, scene, source);';
 if(!html.includes(anchor))throw Error('Beach life scene anchor missing '+key);
 html=html.replace(anchor,anchor+`\nconst atlasBeach=AtlasBeach.create(T,scene,{lighting:false,activityRadius:3.8});const atlasWorldUpdate=world.update.bind(world);world.update=(...args)=>{atlasWorldUpdate(...args);world.group.visible=false;const sky=scene.getObjectByName('analytic-atmosphere');if(sky)sky.visible=false;camera.far=1800;camera.updateProjectionMatrix();atlasBeach.update(args[2],camera);};`);
 }
 if(key==='life-shark'){
 html=html.replace(/<head[^>]*>/i,m=>m+'<script>'+read('src/reference-water-runtime.js').replaceAll('</script','<\\/script')+'</script>');
 html=html.replace('world.update(state, settings.quality, time, snapshot); lighting.update(state, position, settings.quality);','world.update(state, settings.quality, time, snapshot); lighting.update(state, position, settings.quality);if(engine.referenceWater){world.group.visible=false;api.ocean.surface.visible=false;api.ocean.underwater.visible=false;api.ocean.skyGroup.visible=false;if(!AtlasTurntable.isActive())engine.referenceWater.update();}');
 html=html.replace('engine.animal=animal;window.__ATLAS_THREE=T;window.__LIFE_VISUAL = engine;','engine.animal=animal;window.__ATLAS_THREE=T;window.__LIFE_VISUAL = engine;AtlasFishHabitat.installLife(T,engine).catch(error=>{engine.referenceError=String(error);console.error(error);});');
 }
 if(key==='cat-v440'){html=html.replace('window.__CAT_V440_STATS__=','window.__ATLAS_CAT_MESH__=()=>m;window.__CAT_V440_STATS__=');}
 if(key==='cat-v440'){
 html=html.replace(/<head[^>]*>/i,m=>m+'<script>'+beachScript.replaceAll('</script','<\\/script')+'</script>');
 html=html.replace('const vs=`#version 300 es','AtlasBeach.prepareRaw(canvas,gl);const vs=`#version 300 es');
 html=html.replace('far=Math.max(4,dist+radius*5);return mul(perspective(CAMERA_FOV,canvas.width/canvas.height,near,far),lookAt(eye,target,up))','far=1800;const projection=perspective(CAMERA_FOV,canvas.width/canvas.height,near,far),view=lookAt(eye,target,up);window.__ATLAS_CAT_CAMERA_MATRICES__={projection,view,near,far};return mul(projection,view)');
 html=html.replace('gl.useProgram(pr);gl.bindVertexArray(meshVao);gl.uniformMatrix4fv(U.pv','AtlasBeach.drawRaw(gl,window.__ATLAS_CAT_CAMERA_MATRICES__);gl.useProgram(pr);gl.bindVertexArray(meshVao);gl.uniformMatrix4fv(U.pv');
 html=html.replace('gl.drawArrays(gl.LINES,0,grid.length/3);','if(!window.__ATLAS_BEACH?.group.visible)gl.drawArrays(gl.LINES,0,grid.length/3);');
 if(!html.includes('__ATLAS_CAT_CAMERA_MATRICES__'))throw Error('Cat beach camera hook missing');
 }
 if(key==='chicken'){html=html.replace('window.__CHICKEN_V46_API__=','window.__ATLAS_CHICKEN_MESHES=()=>candidateMeshes;window.__CHICKEN_V46_API__=');}
 if(key==='chicken'){
 html=html.replace(/<head[^>]*>/i,m=>m+'<script>'+beachScript.replaceAll('</script','<\\/script')+'</script>');
 html=html.replace('const scene=new T.Scene();scene.background=new T.Color(0x182027);','const scene=new T.Scene();const atlasBeach=AtlasBeach.create(T,scene,{lighting:false});');
 html=html.replace('new T.PerspectiveCamera(32,1,.005,40)','new T.PerspectiveCamera(32,1,.005,1800)');
 html=html.replace('renderer.render(scene,camera);','atlasBeach.update(performance.now()/1000,camera);renderer.render(scene,camera);');
 html=html.replace('window.__ATLAS_CHICKEN_MESHES=',"let atlasBeachClock=0;renderer.setAnimationLoop(()=>{atlasBeachClock+=1/60;atlasBeach.update(atlasBeachClock,camera);renderer.render(scene,camera);});window.__ATLAS_CHICKEN_MESHES=");
 }
 html=adaptTurntable(html,key);
 const compressed=zlib.gzipSync(Buffer.from(html),{level:6}),sourceLabel=sourceNames[key]||(key.startsWith('life-')?'Life Ecosystem V3.x · original procedural source snapshot':'Original project');assets[key]={source:sourceLabel,sha256:sourceSha,bytes:source.length,compressedBytes:compressed.length};manifest.sources.push({id:key,...assets[key],adaptedSha256:hash(Buffer.from(html))});payloads+='<script type="application/octet-stream" id="payload-'+key+'">'+compressed.toString('base64')+'</script>\n';
}
const stageBundle=await build({entryPoints:[path.join(root,'src/rehearsal-viewer.js')],bundle:true,format:'iife',minify:true,write:false,target:'es2022',alias:{three:path.join(root,'vendor/three.module.js')},legalComments:'inline'});
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/kaopu-stage-runtime.js'),stageBundle.outputFiles[0].text);
const app=await build({entryPoints:[path.join(root,'src/app.js')],bundle:true,format:'iife',minify:false,write:false,target:'es2022',alias:{three:path.join(root,'vendor/three.module.js')},legalComments:'inline'}),thumbs=fs.existsSync(path.join(root,'qa/thumbnails.json'))?JSON.parse(read('qa/thumbnails.json')):{};
const exampleScore=(await import('../vendor/quad/src/scores.js')).SCORE_LIBRARY.tortoise.score;
const boot='window.ATLAS_EXAMPLE_NOTATION='+safe(exampleScore)+';window.ATLAS_ASSETS='+safe(assets)+';window.ATLAS_BRIDGE='+safe(read('src/studio-bridge.js')+'\n'+read('src/bridge.js'))+';window.ATLAS_FRAME_STYLE='+safe(frameStyle)+';window.ATLAS_THUMBS='+safe(thumbs)+';';
const html=read('src/index.html').replace('/*STYLE*/',()=>read('src/style.css')+'\n'+read('src/rehearsal.css')).replace('<!--REHEARSAL-->',()=>read('src/rehearsal.html')).replace('<!--PAYLOADS-->',()=>payloads).replace('/*APP*/',()=>boot+'window.ATLAS_REHEARSAL_RUNTIME='+safe(stageBundle.outputFiles[0].text)+';'+app.outputFiles[0].text.replaceAll('</script','<\\/script'));
const output=path.join(root,'打开动物集成工作台.html');fs.writeFileSync(output,html);manifest.output={file:path.basename(output),bytes:Buffer.byteLength(html),sha256:hash(Buffer.from(html)),coreNetworkDependencies:0,independentHtml:true};fs.writeFileSync(path.join(root,'SOURCE_MANIFEST.json'),JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest.output));
