import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {playwright} from './dependencies.mjs';
const {chromium}=playwright(),browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']}),page=await browser.newPage({viewport:{width:1680,height:1000},acceptDownloads:true}),report={entries:[],errors:[],startedAt:new Date().toISOString()};page.on('pageerror',e=>report.errors.push(e.message));
async function select(id){await page.evaluate(id=>__ATLAS_BOOT__.select(id),id);await page.waitForFunction(id=>window.__ATLAS__?.current===id&&document.querySelector('#loading').hidden,id,{timeout:120000});}
const clock=()=>{const s=window.__LIFE_VISUAL_SOURCE;return s?.clock?.()??s?.sample?.().time??s?.api?.state?.time??null;};
try{await page.goto(pathToFileURL(process.cwd()+'/打开动物集成工作台.html').href,{timeout:120000});await page.waitForFunction(()=>window.__ATLAS__?.ready,null,{timeout:120000});
for(const id of ['pig','dog','lihua','dove','shark','fish','cat','eagle','crab','starling','chicken','wolf']){console.log('FINAL CHECK',id);await select(id);const f=page.frames()[1],entry={id};
for(const b of await page.locator('.viewbar button:visible').all()){await b.click();assert.equal((await page.locator('#toast').textContent()).includes('失败'),false);}await page.evaluate(()=>__ATLAS__.set('view','three'));
if(['pig','dog','lihua','dove','shark'].includes(id)){const before=await f.evaluate(()=>{let m;__LIFE_VISUAL.animal.root.traverse(o=>{if(!m&&o.material?.color)m=o.material;});return m.color.toArray();});await page.evaluate(()=>__ATLAS__.set('coatTone',1.1));const after=await f.evaluate(()=>{let m;__LIFE_VISUAL.animal.root.traverse(o=>{if(!m&&o.material?.color)m=o.material;});return m.color.toArray();});assert.ok(after.some((v,k)=>Math.abs(v-before[k])>1e-5));entry.actualMaterialChanged=true;await page.evaluate(()=>__ATLAS__.set('playing',false));await page.waitForTimeout(100);const a=await f.evaluate(clock);await page.waitForTimeout(350);const b=await f.evaluate(clock);assert.equal(a,b,'native animation clock must pause');entry.pauseClock={a,b};await page.evaluate(()=>__ATLAS__.set('playing',true));await page.waitForTimeout(300);const c=await f.evaluate(clock);assert.ok(c===null||c>b,'native clock must resume');}
if(id==='chicken'){const before=await f.evaluate(()=>__CHICKEN_V46_API__.meshHashes());await page.evaluate(()=>__ATLAS__.set('chicken:head_scale',1.07));await page.waitForTimeout(300);const after=await f.evaluate(()=>__CHICKEN_V46_API__.meshHashes());assert.notDeepEqual(after,before,'chicken actual geometry must change');const labels=await page.locator('[data-control^="chicken:"] label').allTextContents();assert.ok(labels.every(Boolean));entry.actualGeometryChanged=true;}
if(id==='wolf'){const before=await f.evaluate(()=>__ATLAS_NATIVE.score());await page.evaluate(()=>__ATLAS__.set('bulk',1.06));const after=await f.evaluate(()=>__ATLAS_NATIVE.score());assert.notEqual(before,after);entry.sourceScoreChanged=true;}
report.entries.push(entry);}
await select('chicken');const event=page.waitForEvent('download');await page.evaluate(()=>__ATLAS__.exportObject('json'));const d=await event;await d.saveAs('qa/exports/chicken.animal.json');await page.evaluate(()=>__ATLAS__.set('chicken:head_scale',.93));await page.locator('#recipe-file').setInputFiles('qa/exports/chicken.animal.json');await page.waitForFunction(()=>window.__ATLAS__?.current==='chicken'&&!document.querySelector('#loading').hidden);await page.waitForFunction(()=>document.querySelector('#loading').hidden,null,{timeout:120000});assert.equal(await page.evaluate(()=>__ATLAS__.settings()['chicken:head_scale']),1.07);report.recipeImport=true;
await page.locator('#favorite').click();await page.locator('#favorite-tab').click();assert.equal(await page.locator('.animal-card').count(),1);await page.locator('#all-tab').click();await select('fish');await page.waitForTimeout(1000);await page.screenshot({path:'qa/FINAL_PLATFORM.png'});await page.evaluate(()=>__ATLAS__.set('group',true));await page.waitForTimeout(600);await page.screenshot({path:'qa/FINAL_SCHOOL.png'});report.favorite=true;report.passed=report.errors.length===0;report.completedAt=new Date().toISOString();
}catch(e){report.passed=false;report.failure=e.stack;console.log(e.stack);}finally{fs.writeFileSync('qa/FINAL_CHECK_REPORT.json',JSON.stringify(report,null,2));await browser.close();}if(!report.passed)process.exitCode=1;
