import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import {esbuild,playwright} from './dependencies.mjs';const {build}=esbuild();
const reportFile=process.env.ATLAS_QA_REPORT||'qa/FUNCTIONAL_REPORT.json',root=process.cwd(),require=createRequire(import.meta.url),{chromium}=playwright();fs.mkdirSync('qa/exports',{recursive:true});
const code=await build({entryPoints:['tools/glb-viewer.js'],bundle:true,format:'iife',write:false,alias:{three:path.join(root,'vendor/three.module.js')}});fs.writeFileSync('qa/GLB_IMPORT_VIEWER.html','<!doctype html><html><head><meta charset="utf-8"></head><body><script>'+code.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script>');
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']}),page=await browser.newPage({viewport:{width:1680,height:1000},acceptDownloads:true}),viewer=await browser.newPage({viewport:{width:1000,height:750}}),errors=[],network=[],report={startedAt:new Date().toISOString(),entries:[],checks:[]};
for(const p of [page,viewer]){p.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});p.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('ERROR',m.text().slice(0,200));}});p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});}
function validateGLB(buffer){assert.equal(buffer.readUInt32LE(0),0x46546c67);assert.equal(buffer.readUInt32LE(4),2);assert.equal(buffer.readUInt32LE(8),buffer.length);const jlen=buffer.readUInt32LE(12),json=JSON.parse(buffer.subarray(20,20+jlen).toString()),offset=28+jlen;assert.equal(buffer.readUInt32LE(24+jlen),0x004e4942);assert.equal(json.asset.version,'2.0');assert.equal(json.buffers[0].byteLength,buffer.length-offset);for(const v of json.bufferViews){assert.equal(v.byteOffset%4,0);assert.ok(v.byteOffset+v.byteLength<=json.buffers[0].byteLength);}for(const a of json.accessors){const v=json.bufferViews[a.bufferView],dims={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type];assert.equal(v.byteLength,a.count*dims*4);if(a.componentType===5126)for(let i=0;i<a.count*dims;i++)assert.ok(Number.isFinite(buffer.readFloatLE(offset+v.byteOffset+i*4)));}for(const m of json.meshes)for(const p of m.primitives){const pos=json.accessors[p.attributes.POSITION],idx=json.accessors[p.indices],view=json.bufferViews[idx.bufferView];assert.equal(idx.count%3,0);for(let i=0;i<idx.count;i++)assert.ok(buffer.readUInt32LE(offset+view.byteOffset+i*4)<pos.count);}assert.ok(json.extras.boundsMetres.every(x=>x>0&&Number.isFinite(x)));return json;}
async function select(id){await page.evaluate(id=>__ATLAS_BOOT__.select(id),id);await page.waitForFunction(id=>window.__ATLAS__?.current===id&&document.querySelector('#loading').hidden,id,{timeout:120000});}
async function download(format,id){const event=page.waitForEvent('download',{timeout:180000});await page.evaluate(format=>__ATLAS__.exportObject(format),format);const d=await event,file='qa/exports/'+d.suggestedFilename();await d.saveAs(file);return file;}
try{
await page.goto(pathToFileURL(root+'/打开动物集成工作台.html').href,{timeout:120000});await page.waitForFunction(()=>window.__ATLAS__?.ready,null,{timeout:120000});await viewer.goto(pathToFileURL(root+'/qa/GLB_IMPORT_VIEWER.html').href);
const animals=await page.evaluate(()=>__ATLAS__.catalog),ids=process.argv.slice(2).length?process.argv.slice(2):animals.map(a=>a.id),testedAdapters=new Set();
for(const id of ids){console.log('EXPORT CHECK',id);await select(id);const a=animals.find(x=>x.id===id),entry={id};const controls=await page.evaluate(()=>__ATLAS__.controls),control=controls.find(d=>d.type==='range'&&['coatTone','bodyScale','chicken:head_scale','roughness','tone','speed'].includes(d.key))||controls.find(d=>d.type==='range')||controls.find(d=>d.key==='zoom');if(control){const value=control.type==='select'?control.options.at(-1).value:Math.min(control.max,Number(control.value)+(control.max-control.min)*.08);await page.evaluate(async({key,value})=>__ATLAS__.set(key,value),{key:control.key,value});assert.equal(await page.evaluate(key=>__ATLAS__.settings()[key],control.key),value);entry.parameter={key:control.key,value};}
const actions=await page.evaluate(()=>__ATLAS__.actions);if(actions.length){const chosen=actions[Math.min(1,actions.length-1)].id;await page.evaluate(id=>__ATLAS__.set('action',id),chosen);await page.waitForTimeout(300);await page.evaluate(()=>__ATLAS__.set('playing',false));entry.action=chosen;entry.runtimeAction=await page.frames()[1].evaluate(()=>({fish:window.__KAOPU_R13__?.renderer.state.mode,cat:window.__CAT_V440_METRICS__?.action,eagle:window.eagle?.action,crab:window.__CRAB_QA__?.state.behavior,palau:window.birdWorkbench?.getState().source,life:window.LifeEcologyRuntime?.summary().currentActivity}));assert.ok(Object.values(entry.runtimeAction).includes(chosen),'action must reach actual runtime');}
const file=await download('glb',id),buffer=fs.readFileSync(file),json=validateGLB(buffer);assert.equal(json.extras.animalId,id);entry.glb={file,bytes:buffer.length,meshes:json.meshes.length};entry.imported=await viewer.evaluate(b64=>loadGLBBase64(b64),buffer.toString('base64'));assert.equal(entry.imported.meshes,json.meshes.length);await viewer.screenshot({path:'qa/exports/'+id+'-imported.png'});
if(!testedAdapters.has(a.adapter)||a.adapter==='life'){testedAdapters.add(a.adapter);const html=await download('html',id),standalone=await browser.newPage({viewport:{width:1000,height:750}});standalone.on('pageerror',e=>errors.push(e.message));await standalone.goto(pathToFileURL(root+'/'+html).href,{timeout:120000});await standalone.waitForFunction(()=>window.AnimalRuntime?.ready,null,{timeout:120000});const actual=await standalone.evaluate(()=>AnimalRuntime.configuration()),expected=await page.evaluate(()=>__ATLAS__.settings());assert.deepEqual(actual,expected);entry.standaloneRoundTrip=true;await standalone.close();}
report.entries.push(entry);fs.writeFileSync(reportFile,JSON.stringify({...report,errors,network},null,2));console.log('EXPORT OK',id,(buffer.length/1048576).toFixed(1)+' MB',entry.imported.triangles+' triangles');}
await select('fish');await page.evaluate(()=>__ATLAS__.set('group',true));assert.equal(await page.frames()[1].evaluate(()=>__KAOPU_R13__.renderer.state.school),true);await page.screenshot({path:'qa/fish-school.png'});report.checks.push('fish actual 30-member school');await page.evaluate(()=>__ATLAS__.set('group',false));
await page.locator('[data-category="birds"]').click();assert.equal(await page.locator('.animal-card').count(),6);await page.locator('#search').fill('海雕');assert.equal(await page.locator('.animal-card').count(),1);await page.locator('#search').fill('');await page.locator('[data-category="all"]').click();assert.equal(await page.locator('.animal-card').count(),19);report.checks.push('category counts and search');
await page.evaluate(async()=>{__ATLAS_BOOT__.select('wolf');__ATLAS_BOOT__.select('chicken');await __ATLAS_BOOT__.select('pig');});await page.waitForFunction(()=>window.__ATLAS__?.current==='pig'&&document.querySelector('#loading').hidden,null,{timeout:120000});report.checks.push('rapid animal changes mount only final object');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/mobile.png'});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);await page.locator('#panel-toggle').click();await page.screenshot({path:'qa/mobile-parameters.png'});report.checks.push('mobile layout and parameter drawer');
report.passed=errors.length===0&&network.length===0;report.completedAt=new Date().toISOString();
}catch(e){report.passed=false;report.failure=e.stack;console.log('FAILED',e.stack);}finally{fs.writeFileSync(reportFile,JSON.stringify({...report,errors,network},null,2));await browser.close();}if(!report.passed)process.exitCode=1;
