import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {playwright} from './dependencies.mjs';
const browser=await playwright().chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']}),page=await browser.newPage({viewport:{width:1680,height:1000}}),errors=[],report={checks:[],errors};page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
async function select(id){await page.evaluate(id=>__ATLAS_BOOT__.select(id),id);await page.waitForFunction(id=>__ATLAS__?.current===id&&document.querySelector('#loading').hidden,id,{timeout:120000});return page.frames()[1];}
try{
 await page.goto(pathToFileURL(process.cwd()+'/打开动物集成工作台.html').href,{timeout:120000});await page.waitForFunction(()=>window.__ATLAS__?.ready,null,{timeout:120000});let frame=page.frames()[1];
 let stats=await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.stats());assert.equal(stats.terrainVertices,160801);assert.equal(stats.rocks,26);assert.equal(stats.bladeVertices,455);assert.ok(stats.frames>0);
 await page.evaluate(async()=>{await __ATLAS__.set('waterDensity',1.35);await __ATLAS__.set('lightRays',.3);await __ATLAS__.set('kelpDensity',0);});await page.waitForTimeout(200);stats=await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.stats());assert.equal(stats.waterDensity,1.35);assert.equal(stats.rays,.3);assert.equal(stats.kelp,0);
 await page.evaluate(()=>__ATLAS__.set('playing',false));await page.waitForTimeout(150);const time=await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.stats().time);await page.waitForTimeout(350);assert.equal(await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.stats().time),time);assert.equal(await frame.evaluate(()=>__KAOPU_R13__.renderer.gl.getError()),0);report.checks.push({id:'fish',originalScene:stats,parameters:true,pausedTime:true,glError:0});
 await frame.evaluate(()=>{const r=__KAOPU_R13__.renderer,gl=r.gl,draw=gl.drawElementsInstanced.bind(gl);gl.drawElementsInstanced=(...args)=>{if(r.state.school&&gl.getParameter(gl.CURRENT_PROGRAM)===r.program&&!window.__ATLAS_SCHOOL_QUERY){const query=gl.createQuery();window.__ATLAS_SCHOOL_QUERY=query;gl.beginQuery(gl.ANY_SAMPLES_PASSED,query);draw(...args);gl.endQuery(gl.ANY_SAMPLES_PASSED);}else draw(...args);};});
 await page.evaluate(async()=>{await __ATLAS__.set('kelpDensity',1);await __ATLAS__.set('waterDensity',1);await __ATLAS__.set('lightRays',.85);await __ATLAS__.set('group',true);await __ATLAS__.set('playing',true);});await page.waitForTimeout(900);assert.equal(await frame.evaluate(()=>__KAOPU_R13__.renderer.school.fish.length),30);const schoolVisible=await frame.evaluate(()=>{const gl=__KAOPU_R13__.renderer.gl,q=window.__ATLAS_SCHOOL_QUERY;return !!q&&gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE)&&gl.getQueryParameter(q,gl.QUERY_RESULT);});assert.ok(schoolVisible,'School must produce visible fragments through the environment depth');report.checks[0].schoolVisibleFragments=true;await page.screenshot({path:'qa/FINAL_SCHOOL.png'});
 for(const id of ['pig','dog','lihua','cat','neutral-dog','tabby','wolf','bear','tortoise','chicken']){frame=await select(id);const info=await frame.evaluate(()=>({stats:__ATLAS_BEACH.stats,height:__ATLAS_BEACH.sample(0,0).h,shaderErrors:window.__LIFE_VISUAL?.errors||[],glError:(window.__LIFE_VISUAL?.renderer||window.__ATLAS_NATIVE?.renderer)?.getContext().getError()??0}));assert.equal(info.height,-.015);assert.equal(info.stats.terrainVertices,37249);assert.ok(info.stats.rocks>15);assert.deepEqual(info.shaderErrors,[]);assert.equal(info.glError,0);await page.evaluate(()=>__ATLAS__.set('environment',false));assert.equal(await frame.evaluate(()=>__ATLAS_BEACH.group.visible),false);await page.evaluate(()=>__ATLAS__.set('environment',true));assert.equal(await frame.evaluate(()=>__ATLAS_BEACH.group.visible),true);report.checks.push({id,...info,sceneSwitch:true});}
 frame=await select('shark');assert.ok(await frame.evaluate(()=>__LIFE_VISUAL.referenceWater&&__ATLAS_WATER_REFERENCE.stats().frames>0));await page.evaluate(()=>__ATLAS__.set('kelpDensity',.5));await page.waitForTimeout(200);assert.equal(await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.stats().kelp),110);assert.equal(await frame.evaluate(()=>__ATLAS_WATER_REFERENCE.renderer.backend.gl.getError()),0);report.checks.push({id:'shark',referenceScene:true,parameters:true});
 await page.evaluate(()=>__ATLAS__.set('kelpDensity',1));await page.screenshot({path:'qa/FINAL_SHARK.png'});report.passed=errors.length===0;
}catch(e){report.passed=false;report.failure=e.stack;console.log(e.stack);}finally{report.completedAt=new Date().toISOString();fs.writeFileSync('qa/SCENE_REPORT.json',JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,errors}));if(!report.passed)process.exitCode=1;
