import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {playwright,esbuild} from './dependencies.mjs';import {SCORE_LIBRARY as K5} from '../vendor/mammal/src/scores.js';
const {chromium}=playwright(),browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']}),context=await browser.newContext({viewport:{width:1680,height:1000},acceptDownloads:true}),page=await context.newPage(),checks=[],network=[],errors=[],expectedErrors=[],url=pathToFileURL(process.cwd()+'/打开动物集成工作台.html').href,report={startedAt:new Date().toISOString()};let rejecting=false;fs.mkdirSync('qa/imports',{recursive:true});
page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});page.on('pageerror',e=>{(rejecting?expectedErrors:errors).push(e.message);});
const log=s=>{checks.push(s);console.log('PASS',s);};
async function ready(p=page,id){await p.waitForFunction(id=>window.__ATLAS__?.ready&&(!id||__ATLAS__.current===id)&&document.querySelector('#loading').hidden,id,{timeout:120000});}
async function open(){if(!await page.locator('#import-dialog').evaluate(d=>d.open))await page.locator('#import-animal').click();}
async function upload(file){await open();await page.locator('#import-file').setInputFiles(file);await page.waitForFunction(()=>/验证通过|导入失败/.test(document.querySelector('#import-status').textContent),null,{timeout:100000});return page.locator('#import-status').textContent();}
async function success(file){const status=await upload(file);assert.match(status,/验证通过/);assert.equal(await page.locator('#import-commit').isDisabled(),false);return status;}
async function fail(file,match){rejecting=true;try{const before=await page.evaluate(()=>__ATLAS_BOOT__.catalog.length);const s=await upload(file);assert.match(s,match);assert.equal(await page.locator('#import-commit').isDisabled(),true);assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),before);}finally{rejecting=false;}}
async function commit(){await page.locator('#import-commit').click();await page.waitForFunction(()=>!document.querySelector('#import-dialog').open);await ready();return page.evaluate(()=>__ATLAS__.current);}
async function download(format){const event=page.waitForEvent('download');await page.evaluate(f=>__ATLAS__.exportObject(f),format);const d=await event,file='qa/imports/'+d.suggestedFilename();await d.saveAs(file);return file;}
function fixture(name,content){const f='qa/imports/'+name;fs.writeFileSync(f,content);return f;}
function rewriteGLB(buffer,change,extra=Buffer.alloc(0)){const n=buffer.readUInt32LE(12),j=JSON.parse(buffer.subarray(20,20+n).toString()),bin=buffer.subarray(28+n);change(j,bin.length);const raw=Buffer.from(JSON.stringify(j)),json=Buffer.alloc(Math.ceil(raw.length/4)*4,32);raw.copy(json);const binary=Buffer.concat([bin,extra]),out=Buffer.alloc(28+json.length+binary.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(json.length,12);out.writeUInt32LE(0x4e4f534a,16);json.copy(out,20);out.writeUInt32LE(binary.length,20+json.length);out.writeUInt32LE(0x004e4942,24+json.length);binary.copy(out,28+json.length);return out;}
try{
 const viewerCode=await esbuild().build({entryPoints:['tools/glb-viewer.js'],bundle:true,format:'iife',write:false,alias:{three:path.join(process.cwd(),'vendor/three.module.js')}});fs.writeFileSync('qa/GLB_IMPORT_VIEWER.html','<!doctype html><html><head><meta charset="utf-8"></head><body><script>'+viewerCode.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></body></html>');
 await page.goto(url,{timeout:120000});await ready();assert.equal(await page.locator('.animal-card').count(),19);
 await open();await page.screenshot({path:'qa/IMPORT_WINDOW.png'});assert.match(await page.locator('.import-rules').textContent(),/K4\|/);log('directory import window and explicit supported modes');
 await fail(fixture('unsupported.fbx','bad'),/暂不支持/);await fail(fixture('invalid.json','{bad'),/无法解析/);await fail(fixture('bad-k5.txt','K5|Mffffff,.8'),/缺少必需谱段/);log('invalid formats and incomplete procedural scores cannot enter catalogue');
 const event=page.waitForEvent('download');await page.locator('#download-package-example').click();const example=await event;const sample='qa/imports/example-tortoise.kaopu.json';await example.saveAs(sample);await success(sample);await page.screenshot({path:'qa/IMPORT_PREVIEW_K4.png'});const k4=await commit();assert.match(k4,/^import-k4-/);assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),20);assert.ok(await page.frames().find(f=>f.name()==='').evaluate(()=>true));log('K4 example creates an actual procedural animal and catalogue card');
 const k5file=fixture('new-dog.score.txt',K5.neutralDog.score);await success(k5file);const k5=await commit();assert.match(k5,/^import-k5-/);assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),21);await page.evaluate(()=>__ATLAS__.set('bulk',1.03));const k5pack=await download('kaopu');assert.equal(JSON.parse(fs.readFileSync(k5pack)).score.parameters.bulk,1.03);log('K5 raw notation uses original mammal instrument and exports notation plus parameters');
 if(await page.locator('#import-dialog').evaluate(d=>d.open))await page.locator('#close-import').click();await page.evaluate(()=>__ATLAS_BOOT__.select('cat'));await ready(page,'cat');const catFixture=await download('glb');await success(catFixture);await page.locator('#import-name').fill('导入家猫');await page.locator('#import-category').selectOption('land');const glbId=await commit();assert.match(glbId,/^import-glb-/);assert.equal(await page.evaluate(()=>__ATLAS__.actions.length),0);assert.equal(await page.locator('#pause').isDisabled(),true);assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),22);await page.waitForTimeout(400);await page.screenshot({path:'qa/IMPORTED_ANIMAL.png'});log('real existing cat GLB imports with material controls and honest static capability');
 await page.evaluate(async()=>{await __ATLAS__.set('scale',1.5);await __ATLAS__.set('tint','#d3b985');});const pack=await download('kaopu'),score=await download('score'),old=await download('json');const pkg=JSON.parse(fs.readFileSync(pack));assert.equal(pkg.asset.format,'glb');assert.equal(pkg.score.parameters.scale,1.5);
 await success(pack);await commit();assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),22);assert.equal(await page.evaluate(()=>__ATLAS__.settings().scale),1.5);log('GLB full package roundtrip and duplicate detection');
 await page.evaluate(()=>__ATLAS__.set('scale',.75));await success(score);await commit();assert.equal(await page.evaluate(()=>__ATLAS__.settings().scale),1.5);await success(old);await commit();log('matching parameter score and legacy recipe restore imported animal');
 const data=JSON.parse(fs.readFileSync(score));await fail(fixture('wrong-version.score.json',JSON.stringify({...data,instrument:{...data.instrument,version:'99'}})),/版本/);await fail(fixture('missing-model.score.json',JSON.stringify({...data,animalId:'missing',instrument:{...data.instrument,assetSha256:'0'.repeat(64)}})),/缺少/);await fail(fixture('bad-param.score.json',JSON.stringify({...data,parameters:{scale:100}})),/范围/);await fail(fixture('unknown-param.score.json',JSON.stringify({...data,parameters:{age:10}})),/不支持.*age/);log('instrument version, asset fingerprint and parameter contract validation');
 await page.locator('#close-import').click();await page.reload({timeout:120000});await ready(page,'fish');assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),22);await page.evaluate(id=>__ATLAS_BOOT__.select(id),glbId);await ready(page,glbId);assert.equal(await page.evaluate(()=>__ATLAS__.settings().scale),1.5);assert.ok(await page.locator('[data-animal="'+glbId+'"] img').getAttribute('src'));log('IndexedDB persists models and thumbnails; settings survive reload');
 const html=await download('html'),standalone=await context.newPage();await standalone.goto(pathToFileURL(process.cwd()+'/'+html).href);await standalone.waitForFunction(()=>window.AnimalRuntime?.ready,null,{timeout:120000});assert.equal(await standalone.evaluate(()=>AnimalRuntime.configuration().scale),1.5);await standalone.close();const output=await download('glb');assert.equal(fs.readFileSync(output).readUInt32LE(0),0x46546c67);const viewer=await context.newPage();await viewer.goto(pathToFileURL(process.cwd()+'/qa/GLB_IMPORT_VIEWER.html').href);const imported=await viewer.evaluate(data=>loadGLBBase64(data),fs.readFileSync(output).toString('base64'));assert.ok(imported.meshes>0&&imported.triangles>0);await viewer.screenshot({path:'qa/IMPORTED_ANIMAL_REEXPORTED.png'});await viewer.close();log('imported animal exports standalone runtime and GLB reloaded with official GLTFLoader');
 const fresh=await browser.newContext({viewport:{width:1400,height:900},acceptDownloads:true}),other=await fresh.newPage();await other.goto(url,{timeout:120000});await ready(other);assert.equal(await other.locator('.animal-card').count(),19);await other.locator('#import-animal').click();await other.locator('#import-file').setInputFiles(pack);await other.waitForFunction(()=>/验证通过|导入失败/.test(document.querySelector('#import-status').textContent),null,{timeout:100000});assert.match(await other.locator('#import-status').textContent(),/验证通过/);await other.locator('#import-commit').click();await ready(other,glbId);assert.equal(await other.evaluate(()=>__ATLAS__.settings().scale),1.5);await fresh.close();log('full GLB package works in a fresh browser with no installed animal');
 await page.setViewportSize({width:390,height:844});await page.locator('#import-animal').click();await page.screenshot({path:'qa/IMPORT_MOBILE.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#import-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);await page.locator('#close-import').click();await page.setViewportSize({width:1680,height:1000});await page.locator('.remove-import').click();await ready(page,'fish');assert.equal(await page.evaluate(()=>__ATLAS_BOOT__.catalog.length),21);log('mobile import layout and removable browser catalogue entry');
 const source=fs.readFileSync(catFixture);await fail(fixture('external.glb',rewriteGLB(source,j=>j.buffers[0].uri='https://invalid.example/animal.bin')),/外部/);await fail(fixture('compressed.glb',rewriteGLB(source,j=>j.extensionsUsed=['KHR_draco_mesh_compression'])),/Draco|draco/);const corrupt=JSON.parse(fs.readFileSync(pack));corrupt.instrument.assetSha256=corrupt.score.instrument.assetSha256='0'.repeat(64);await fail(fixture('wrong-fingerprint.kaopu.json',JSON.stringify(corrupt)),/指纹/);log('external resources, unsupported compression and tampered package fingerprints are rejected');
 const animation=Buffer.alloc(48);[0,1,2,0,0,0,.4,0,0,0,0,0].forEach((x,i)=>animation.writeFloatLE(x,i*4));const animated=fixture('animated-cat.glb',rewriteGLB(source,(j,size)=>{const v=j.bufferViews.length,a=j.accessors.length;j.bufferViews.push({buffer:0,byteOffset:size,byteLength:12},{buffer:0,byteOffset:size+12,byteLength:36});j.accessors.push({bufferView:v,componentType:5126,count:3,type:'SCALAR',min:[0],max:[2]},{bufferView:v+1,componentType:5126,count:3,type:'VEC3'});j.buffers[0].byteLength=size+48;j.animations=[{name:'移动片段验收',samplers:[{input:a,output:a+1,interpolation:'LINEAR'}],channels:[{sampler:0,target:{node:0,path:'translation'}}]}];},animation));
 await success(animated);const animatedId=await commit();assert.equal(await page.evaluate(()=>__ATLAS__.actions.length),1);assert.equal(await page.locator('#pause').isDisabled(),false);const runtime=page.frames().find(f=>f.url()==='about:srcdoc');const before=await runtime.evaluate(()=>__ATLAS_IMPORTED.info().mixerTime);await page.waitForTimeout(400);assert.ok(await runtime.evaluate(()=>__ATLAS_IMPORTED.info().mixerTime)>before);await page.evaluate(()=>__ATLAS__.set('playing',false));const stopped=await runtime.evaluate(()=>__ATLAS_IMPORTED.info().mixerTime);await page.waitForTimeout(300);assert.equal(await runtime.evaluate(()=>__ATLAS_IMPORTED.info().mixerTime),stopped);const animatedPack=await download('kaopu');await success(animatedPack);await commit();assert.equal(await page.evaluate(()=>__ATLAS__.settings().playing),false);await page.screenshot({path:'qa/IMPORTED_ANIMATED_CAT.png'});log('GLB animation mixer actually advances, pauses and survives full package roundtrip');
 await open();await page.locator('#import-file').setInputFiles('examples/k5.kaopu.json');await page.locator('#close-import').click();assert.equal(await page.locator('#import-dialog').evaluate(d=>d.open),false);await success('examples/k4.kaopu.json');await page.locator('#close-import').click();log('closing a pending preview releases it and another import remains usable');
 await page.locator('[data-category="all"]').click();await page.evaluate(()=>__ATLAS_BOOT__.select('pig'));await ready(page,'pig');assert.ok((await page.evaluate(()=>__ATLAS__.actions.length))>0);await page.evaluate(()=>__ATLAS_BOOT__.select('fish'));await ready(page,'fish');await page.evaluate(()=>__ATLAS__.set('group',true));assert.equal(await page.frames().find(f=>f.url()==='about:srcdoc').evaluate(()=>__KAOPU_R13__.renderer.state.school),true);log('original animal motions and 30-fish school remain available');
 const noStorage=await browser.newContext({viewport:{width:1400,height:900}}),memoryPage=await noStorage.newPage();await memoryPage.addInitScript(()=>Object.defineProperty(window,'indexedDB',{get(){throw Error('simulated storage unavailable');}}));await memoryPage.goto(url,{timeout:120000});await ready(memoryPage);await memoryPage.locator('#import-animal').click();await memoryPage.locator('#import-file').setInputFiles('examples/k4.kaopu.json');await memoryPage.waitForFunction(()=>/验证通过/.test(document.querySelector('#import-status').textContent),null,{timeout:100000});await memoryPage.locator('#import-commit').click();await ready(memoryPage);await memoryPage.waitForFunction(()=>document.querySelector('#toast').textContent.includes('本次会话'));assert.equal(await memoryPage.evaluate(()=>__ATLAS_BOOT__.catalog.length),20);await memoryPage.locator('.remove-import').click();await ready(memoryPage,'fish');assert.equal(await memoryPage.evaluate(()=>__ATLAS_BOOT__.catalog.length),19);await noStorage.close();log('unavailable browser storage gives a session-only notice and still permits removing imports');
 assert.equal(network.length,0);assert.deepEqual(errors,[]);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;console.log('FAILED',e.stack);await page.screenshot({path:'qa/IMPORT_FAILURE.png'}).catch(()=>{});}finally{report.completedAt=new Date().toISOString();fs.writeFileSync('qa/IMPORT_REPORT.json',JSON.stringify({...report,checks,errors,expectedErrors,network},null,2));await browser.close();}if(!report.passed)process.exitCode=1;
