import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {playwright} from './dependencies.mjs';
const {chromium}=playwright(),browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']}),context=await browser.newContext({viewport:{width:1680,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[],checks=[],entries=[],network=[],report={startedAt:new Date().toISOString()},url=pathToFileURL(process.cwd()+'/打开动物集成工作台.html').href;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});const log=s=>{checks.push(s);console.log('PASS',s);};
async function ready(id){await page.waitForFunction(id=>window.__ATLAS__?.current===id&&document.querySelector('#loading').hidden,id,{timeout:120000});}async function select(id){await page.evaluate(id=>__ATLAS_BOOT__.select(id),id);await ready(id);}
try{
 await page.goto(url,{timeout:120000});await ready('fish');const catalog=await page.evaluate(()=>__ATLAS__.catalog);
 for(const a of catalog){await select(a.id);await page.evaluate(async()=>{if(__ATLAS__.actions.length)await __ATLAS__.set('playing',false);await __ATLAS__.set('studioRotate',false);});const before=await page.evaluate(async()=> (await __ATLAS__.request('capture')).image);await page.evaluate(()=>__ATLAS__.set('studioExposure',.45));const after=await page.evaluate(async()=> (await __ATLAS__.request('capture')).image);assert.notEqual(before,after,'exposure must affect actual rendered pixels: '+a.id);await page.evaluate(async()=>{await __ATLAS__.set('studioExposure',1.05);await __ATLAS__.set('studioKey',2);await __ATLAS__.set('studioAmbient',1.2);await __ATLAS__.set('studioLightAngle',-65);});const f=page.frames().find(f=>f.url()==='about:srcdoc');await f.waitForFunction(()=>{const scenes=AtlasTurntable.info().scenes;return !scenes.length||scenes.some(x=>x.lights.key===2&&x.lights.ambient===1.2);},null,{timeout:5000});const state=await f.evaluate(()=>({studio:AtlasTurntable.info(),glError:(window.__KAOPU_R13__?.renderer.gl||window.eagle?.gl||window.__ATLAS_CAT_GL__||window.__ATLAS_NATIVE?.renderer.getContext()||window.__ATLAS_IMPORTED?.renderer.getContext()||window.__LIFE_VISUAL?.renderer.getContext()||window.__ATLAS_CHICKEN_STAGE?.renderer.getContext()||window.__CRAB_QA__?.renderer.getContext()||window.birdWorkbench?.getStages().find(s=>s.renderer.domElement.getBoundingClientRect().width>1)?.renderer.getContext())?.getError()}));assert.equal(state.studio.state.displayStage,'turntable');if(state.studio.scenes.length)assert.ok(state.studio.scenes.some(x=>x.lights.key===2&&x.lights.ambient===1.2),'scene lights must receive actual values: '+a.id);assert.equal(state.glError,0);entries.push({id:a.id,actualExposurePixelsChanged:true,...state});console.log('STUDIO',a.id);}
 log('all 19 animals have working turntable lighting and actual exposure changes');
 await select('neutral-dog');await page.evaluate(()=>__ATLAS__.set('studioRotate',true));const f=page.frames().find(f=>f.url()==='about:srcdoc'),p0=await f.evaluate(()=>__ATLAS_NATIVE.camera.position.toArray());await page.waitForTimeout(450);const p1=await f.evaluate(()=>__ATLAS_NATIVE.camera.position.toArray());assert.notDeepEqual(p0,p1);await page.locator('#rotate-toggle').click();await f.waitForFunction(()=>AtlasTurntable.state.studioRotate===false);const paused=await f.evaluate(()=>__ATLAS_NATIVE.camera.position.toArray());await page.waitForTimeout(300);assert.deepEqual(await f.evaluate(()=>__ATLAS_NATIVE.camera.position.toArray()),paused);log('automatic orbit changes the real camera and pause orbit freezes it');
 await select('pig');await page.locator('#favorite').click();assert.match(await page.locator('#favorite').textContent(),/已收藏/);await page.locator('#favorite-tab').click();assert.equal(await page.locator('.animal-card').count(),1);await page.locator('#all-tab').click();await page.locator('[data-animal="fish"] .card-favorite').click();await page.reload({timeout:120000});await ready('fish');await page.locator('#favorite-tab').click();assert.equal(await page.locator('.animal-card').count(),2);await page.locator('#all-tab').click();log('obvious header and card favorite actions persist and filter correctly');
 await select('pig');await page.evaluate(()=>__ATLAS__.set('coatTone',.9));await page.locator('#delete-score').click();await page.waitForFunction(()=>!document.querySelector('[data-animal="pig"]'));assert.equal(await page.locator('.animal-card').count(),18);const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('animal-atlas/v1')));assert.ok(persisted.removed.includes('pig'));assert.equal(persisted.settings.pig,undefined);assert.ok(!persisted.favorites.includes('pig'));await page.reload({timeout:120000});await ready('fish');assert.equal(await page.locator('.animal-card').count(),18);await page.locator('#deleted-tab').click();await page.locator('[data-restore="pig"]').click();await page.locator('#close-deleted').click();await ready('pig');assert.equal(await page.locator('.animal-card').count(),19);log('delete removes the score, settings and favorite; deleted built-in scores restore after reload');
 const panel=await page.locator('#inspector').boundingBox(),stage=await page.locator('#stage').boundingBox();assert.ok(stage.x+stage.width<=panel.x+1);await page.locator('#studio-panel-tab').click();await page.evaluate(async()=>{await __ATLAS__.set('studioRotate',true);await __ATLAS__.set('studioLightAngle',35);await __ATLAS__.set('studioKey',3.2);await __ATLAS__.set('studioAmbient',1.8);});await page.screenshot({path:'qa/FINAL_ROTATING_STUDIO.png'});await page.locator('#object-panel-tab').click();assert.ok(await page.locator('#action-select').isVisible());await page.screenshot({path:'qa/FINAL_OBJECT_CONTROLS.png'});log('object controls and studio light controls are in the right panel');
 await select('fish');await page.evaluate(async()=>{await __ATLAS__.set('displayStage','habitat');await __ATLAS__.set('group',true);});assert.equal(await page.frames().find(f=>f.url()==='about:srcdoc').evaluate(()=>__KAOPU_R13__.renderer.state.school),true);assert.equal(await page.evaluate(()=>__ATLAS__.settings().displayStage),'turntable');await page.waitForTimeout(300);await page.screenshot({path:'qa/STUDIO_SCHOOL_MODE.png'});log('actual school remains available on the fixed studio; legacy habitat request stays in turntable mode');
 await select('pig');const download=page.waitForEvent('download');await page.evaluate(()=>__ATLAS__.exportObject('html'));const file='qa/studio-standalone.html';await (await download).saveAs(file);const standalone=await context.newPage();await standalone.goto(pathToFileURL(process.cwd()+'/'+file).href);await standalone.waitForFunction(()=>window.AnimalRuntime?.ready,null,{timeout:120000});assert.equal(await standalone.evaluate(()=>AnimalRuntime.configuration().displayStage),'turntable');assert.equal(await standalone.evaluate(()=>AtlasTurntable.state.studioKey),3.2);await standalone.close();log('standalone export keeps turntable and light settings');
 await page.setViewportSize({width:390,height:844});await page.locator('#panel-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa/FINAL_STUDIO_MOBILE.png'});await page.locator('#panel-toggle').click();await page.setViewportSize({width:1680,height:1000});log('mobile layout and right parameter drawer do not overflow');
 await page.evaluate(async()=>{while(__ATLAS_BOOT__.visible().length)await __ATLAS_BOOT__.deleteScore();});assert.equal(await page.locator('.animal-card').count(),0);assert.equal(await page.locator('#delete-score').isDisabled(),true);await page.locator('#deleted-tab').click();await page.locator('[data-restore="pig"]').click();await page.locator('#close-deleted').click();await ready('pig');assert.equal(await page.locator('.animal-card').count(),1);log('empty catalogue is usable and can restore a score');
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;console.log('FAILED',e.stack);await page.screenshot({path:'qa/STUDIO_FAILURE.png'}).catch(()=>{});}finally{report.completedAt=new Date().toISOString();fs.writeFileSync('qa/STUDIO_REPORT.json',JSON.stringify({...report,entries,checks,errors,network},null,2));await browser.close();}if(!report.passed)process.exitCode=1;
