import {playwright} from './dependencies.mjs';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(import.meta.url),{chromium}=playwright();
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11'],timeout:60000}),page=await browser.newPage({viewport:{width:1680,height:1000},acceptDownloads:true}),errors=[],network=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('CONSOLE ERROR',m.text().slice(0,300));}});page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
const report={startedAt:new Date().toISOString(),entries:[],errors,network};
try{
 await page.goto(pathToFileURL(path.join(root,'打开动物集成工作台.html')).href,{timeout:120000,waitUntil:'load'});await page.waitForFunction(()=>window.__ATLAS__?.ready,null,{timeout:120000});
 const catalog=await page.evaluate(()=>__ATLAS__.catalog),ids=process.argv.slice(2).length?process.argv.slice(2):catalog.map(x=>x.id),thumbs=fs.existsSync(path.join(root,'qa/thumbnails.json'))?JSON.parse(fs.readFileSync(path.join(root,'qa/thumbnails.json'))):{};
 for(const id of ids){console.log('CHECK',id);const start=Date.now(),before=errors.length;await page.evaluate(id=>__ATLAS_BOOT__.select(id),id);await page.waitForFunction(id=>window.__ATLAS__?.ready&&window.__ATLAS__.current===id&&document.querySelector('#loading').hidden,id,{timeout:120000});await page.waitForTimeout(1000);
 const entry=await page.evaluate(async()=>({id:__ATLAS__.current,controls:__ATLAS__.controls,actions:__ATLAS__.actions,configuration:__ATLAS__.settings(),canvas:await __ATLAS__.request('capture')}));thumbs[id]=entry.canvas.image;delete entry.canvas;
 const f=page.frames().find(f=>f!==page.mainFrame());entry.runtime=await f.evaluate(()=>({canvases:[...document.querySelectorAll('canvas')].filter(c=>c.clientWidth>1&&c.clientHeight>1).map(c=>({id:c.id,width:c.width,height:c.height,display:getComputedStyle(c).display})),life:window.__LIFE_VISUAL&&{roots:__LIFE_VISUAL.animal?.root?.name,stats:__LIFE_VISUAL.stats},native:window.__ATLAS_NATIVE?.info(),chicken:window.__CHICKEN_V46_API__&&{methods:Object.keys(__CHICKEN_V46_API__),parameters:__CHICKEN_V46_API__.parameterDefinitions().slice(0,4)},crab:window.__CRAB_QA__&&{version:__CRAB_QA__.version,mode:__CRAB_QA__.state.mode},fish:window.__KAOPU_R13__&&{indices:__KAOPU_R13__.renderer.indexCount,frames:__KAOPU_R13__.renderer.frames,glError:__KAOPU_R13__.renderer.gl.getError()}}));
 await page.screenshot({path:path.join(root,'qa/'+id+'.png')});entry.newErrors=errors.slice(before);entry.loadedMs=Date.now()-start;report.entries.push(entry);fs.writeFileSync(path.join(root,'qa/thumbnails.json'),JSON.stringify(thumbs));fs.writeFileSync(path.join(root,'qa/BROWSER_REPORT.json'),JSON.stringify(report,null,2));console.log('OK',id,entry.controls.length,'controls',entry.actions.length,'actions',entry.loadedMs+'ms');
 }
 report.passed=errors.length===0&&network.length===0&&report.entries.length===ids.length;report.completedAt=new Date().toISOString();
}catch(e){report.passed=false;report.error=e.stack;console.log('VERIFY FAILURE',e.stack);}finally{fs.writeFileSync(path.join(root,'qa/BROWSER_REPORT.json'),JSON.stringify(report,null,2));await browser.close();}if(!report.passed)process.exitCode=1;
