export const ChickenNpcState=Object.freeze({IDLE:'idle_stand',LOOK:'look',PECK:'peck',WALK:'walk',STOP:'stop',TURN:'turn',RUN:'short_run',WING_BALANCE:'wing_balance'});
const TAU=Math.PI*2,EPS=1e-8;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const sat=v=>clamp(v,0,1);
const ss=(a,b,v)=>{const t=sat((v-a)/(b-a||1));return t*t*(3-2*t)};
const lerp=(a,b,t)=>a+(b-a)*t;
const wrap=a=>{a%=TAU;if(a>Math.PI)a-=TAU;if(a<-Math.PI)a+=TAU;return a};
const approach=(a,b,d)=>Math.abs(b-a)<=d?b:a+Math.sign(b-a)*d;
const approachAngle=(a,b,d)=>{const e=wrap(b-a);return Math.abs(e)<=d?wrap(b):wrap(a+Math.sign(e)*d)};
const norm2=(x,z)=>{const l=Math.hypot(x,z);return l<EPS?[0,0]:[x/l,z/l]};
function hash32(x){x>>>=0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);return(x^(x>>>16))>>>0}
function rng32(seed){let s=hash32(seed||1)||1;return()=>{s+=0x6d2b79f5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}

export function createChickenVariant(seed=1){
 const r=rng32(seed),range=(a,b)=>lerp(a,b,r()),scale=range(.88,1.12),leg=range(.92,1.09);
 return Object.freeze({seed:seed>>>0,morphology:Object.freeze({overallScale:scale,bodyFullness:range(.9,1.1),breastFullness:range(.9,1.12),abdomenFullness:range(.9,1.12),legScale:leg,headScale:range(.92,1.08),combScale:range(.75,1.25),tailAngleRad:range(.42,.88),plumageHueOffset:range(-.06,.06),plumageValueOffset:range(-.12,.12)}),boneLengths:Object.freeze({pelvisToChest:.2*scale,chestToNeck:.18*scale,neckToHead:.105*scale,upperLeg:.18*scale*leg,lowerLeg:.19*scale*leg,foot:.115*scale,wingUpper:.19*scale,wingLower:.17*scale}),locomotion:Object.freeze({walkSpeed:range(.36,.62)*scale,runSpeed:range(.86,1.24)*scale,acceleration:range(1.5,2.2)*scale,braking:range(1.8,2.6)*scale,walkCadence:range(2.4,3.25),runCadence:range(3.8,5.1),turnRate:range(2.2,3.2),phaseOffset:r()}),behavior:Object.freeze({alertness:range(.2,.9),personalSpace:range(1.05,1.28),peckTempo:range(.85,1.18)}),collision:Object.freeze({bodyRadius:.19*scale,bodyHalfLength:.192*scale,bodyHeight:.42*scale,headRadius:.065*scale,hipHeight:.34*scale*leg,footRadius:.035*scale})});
}

function intent(value){
 if(!value||typeof value.type!=='string')return{type:'idle'};
 if(value.type==='moveTo')return{type:'moveTo',x:Number(value.x)||0,z:Number(value.z)||0,radius:clamp(Number(value.radius??.12),.04,1),urgency:clamp(Number(value.urgency??0),0,1)};
 if(value.type==='lookAt'||value.type==='peckAt')return{type:value.type,x:Number(value.x)||0,z:Number(value.z)||0,duration:clamp(Number(value.duration??(value.type==='peckAt'?.72:.8)),.2,4)};
 return{type:'idle'};
}
function separate(self,neighbors){let x=0,z=0,count=0,nearest=Infinity;for(const o of neighbors||[]){if(!o||o.id===self.id)continue;const dx=self.position[0]-o.position[0],dz=self.position[2]-o.position[2],d=Math.hypot(dx,dz),p=(self.variant.collision.bodyRadius+(o.bodyRadius??self.variant.collision.bodyRadius))*self.variant.behavior.personalSpace;nearest=Math.min(nearest,d);if(d>=p*1.8)continue;const n=d<EPS?[Math.cos((self.id+1)*2.399),Math.sin((self.id+1)*2.399)]:[dx/d,dz/d],w=1-sat((d-p)/(p*.8));x+=n[0]*w;z+=n[1]*w;count++}if(count){[x,z]=norm2(x,z)}return{x,z,count,nearest}}
function avoid(pos,dir,obstacles,radius){let x=0,z=0,pressure=0;for(const o of obstacles||[]){const dx=pos[0]-(o.x??0),dz=pos[2]-(o.z??0),d=Math.hypot(dx,dz),safe=radius+Math.max(0,o.radius??0)+.06;if(d>=safe*1.8)continue;const n=norm2(dx,dz),w=1-sat((d-safe)/(safe*.8)),cross=dir[0]*n[1]-dir[1]*n[0],sign=Math.abs(cross)<.05?1:Math.sign(cross),tx=-n[1]*sign,tz=n[0]*sign;x+=n[0]*w*1.5+tx*w*.85;z+=n[1]*w*1.5+tz*w*.85;pressure=Math.max(pressure,w)}return{x,z,pressure}}
function legPose(phase,speed,scale,run){const s=Math.sin(phase*TAU),ll=Math.max(0,-s),lr=Math.max(0,s),stride=(run?.72:.45)*speed,k=run?.85:.55,t=run?.16:.08;return{left:{hipPitch:s*stride,kneePitch:ll*k,footPitch:-s*stride*.42,lift:ll*.042*scale,contact:ll<=t},right:{hipPitch:-s*stride,kneePitch:lr*k,footPitch:s*stride*.42,lift:lr*.042*scale,contact:lr<=t}}}
function peck(t){const d=ss(.08,.42,t)*(1-ss(.56,.92,t)),c=ss(.36,.52,t)*(1-ss(.56,.72,t));return{neckPitch:-1.05*d,extend:.08*d,headPitch:-.48*d-.12*c,bill:c>.5}}

export class ChickenNpcController{
 constructor({id=0,seed=1,variant=null,position=[0,0,0],yaw=0}={}){this.id=Number(id)||0;this.variant=variant||createChickenVariant(seed);this.position=[Number(position[0])||0,Number(position[1])||0,Number(position[2])||0];this.velocity=[0,0,0];this.yaw=wrap(Number(yaw)||0);this.yawRate=0;this.speed=0;this.state=ChickenNpcState.IDLE;this.stateTime=0;this.intent={type:'idle'};this.intentTime=0;this.gaitPhase=this.variant.locomotion.phaseOffset;this.blockedTime=0;this.detourSign=hash32(this.id+this.variant.seed)&1?1:-1;this.taskComplete=false;this.events=[];this.lastContacts={leftFoot:true,rightFoot:true,bill:false}}
 setIntent(value){this.intent=intent(value);this.intentTime=0;this.blockedTime=0;this.taskComplete=false;return this}
 snapshot(){return{id:this.id,position:[...this.position],velocity:[...this.velocity],yaw:this.yaw,speed:this.speed,state:this.state,bodyRadius:this.variant.collision.bodyRadius}}
 transition(next){if(next===this.state)return;this.events.push({type:'state_exit',state:this.state});this.state=next;this.stateTime=0;this.events.push({type:'state_enter',state:next})}
 contacts(next){for(const[k,label]of[['leftFoot','left_foot'],['rightFoot','right_foot'],['bill','bill']])if(!!this.lastContacts[k]!==!!next[k])this.events.push({type:next[k]?'contact_begin':'contact_end',contact:label});this.lastContacts={...next}}
 update(dt,ctx={}){
  dt=clamp(Number(dt)||1/60,1/240,1/15);this.events=[];this.stateTime+=dt;this.intentTime+=dt;this.position[1]=approach(this.position[1],Number(ctx.groundHeight??0)+this.variant.collision.hipHeight,dt*.7);
  let dir=[Math.cos(this.yaw),Math.sin(this.yaw)],wantSpeed=0,distance=0,targetYaw=this.yaw,headYaw=0,next=ChickenNpcState.IDLE;
  if(this.intent.type==='moveTo'){const dx=this.intent.x-this.position[0],dz=this.intent.z-this.position[2];distance=Math.hypot(dx,dz);dir=norm2(dx,dz);targetYaw=Math.atan2(dir[1],dir[0]);const err=Math.abs(wrap(targetYaw-this.yaw)),run=this.intent.urgency>.58&&distance>.65;wantSpeed=run?this.variant.locomotion.runSpeed:this.variant.locomotion.walkSpeed;if(distance<=this.intent.radius){wantSpeed=0;this.taskComplete=true;next=this.speed>.05?ChickenNpcState.STOP:ChickenNpcState.IDLE}else if(err>.58&&this.speed<this.variant.locomotion.walkSpeed*.45){next=ChickenNpcState.TURN;wantSpeed*=.18}else next=run?ChickenNpcState.RUN:ChickenNpcState.WALK}
  else if(this.intent.type==='lookAt'||this.intent.type==='peckAt'){const dx=this.intent.x-this.position[0],dz=this.intent.z-this.position[2];targetYaw=Math.atan2(dz,dx);headYaw=clamp(wrap(targetYaw-this.yaw),this.intent.type==='lookAt'?-1.35:-.55,this.intent.type==='lookAt'?1.35:.55);next=this.intentTime<this.intent.duration?(this.intent.type==='lookAt'?ChickenNpcState.LOOK:ChickenNpcState.PECK):ChickenNpcState.IDLE;if(this.intentTime>=this.intent.duration)this.taskComplete=true}
  const sep=separate(this,ctx.neighbors),obs=avoid(this.position,dir,ctx.obstacles,this.variant.collision.bodyRadius);let sx=dir[0]+sep.x*Math.min(1.4,sep.count*.45)+obs.x,sz=dir[1]+sep.z*Math.min(1.4,sep.count*.45)+obs.z;
  if(this.intent.type==='moveTo'&&distance>this.intent.radius&&this.speed<.035)this.blockedTime+=dt;else this.blockedTime=Math.max(0,this.blockedTime-dt*.75);
  if(this.blockedTime>.42){const fx=Math.cos(this.yaw),fz=Math.sin(this.yaw);sx+=-fz*this.detourSign*.85;sz+=fx*this.detourSign*.85;wantSpeed=Math.max(wantSpeed,this.variant.locomotion.walkSpeed*.5);this.events.push({type:'replan_requested',reason:'temporary_blockage'});if(this.blockedTime>1.6){this.detourSign*=-1;this.blockedTime=.65}}
  if(Math.hypot(sx,sz)>EPS){[sx,sz]=norm2(sx,sz);targetYaw=Math.atan2(sz,sx)}if(obs.pressure>.65||sep.count>2)wantSpeed*=.58;
  const oldYaw=this.yaw;this.yaw=approachAngle(this.yaw,targetYaw,this.variant.locomotion.turnRate*(next===ChickenNpcState.RUN?1.22:1)*dt);this.yawRate=wrap(this.yaw-oldYaw)/dt;this.speed=approach(this.speed,wantSpeed,(wantSpeed<this.speed?this.variant.locomotion.braking:this.variant.locomotion.acceleration)*dt);if(next===ChickenNpcState.IDLE&&this.speed>.05)next=ChickenNpcState.STOP;if(Math.abs(this.yawRate)>2.15&&this.speed>this.variant.locomotion.walkSpeed*.65)next=ChickenNpcState.WING_BALANCE;this.transition(next);
  this.velocity[0]=Math.cos(this.yaw)*this.speed;this.velocity[2]=Math.sin(this.yaw)*this.speed;this.position[0]+=this.velocity[0]*dt;this.position[2]+=this.velocity[2]*dt;
  const run=this.state===ChickenNpcState.RUN,moving=[ChickenNpcState.WALK,ChickenNpcState.RUN,ChickenNpcState.TURN,ChickenNpcState.WING_BALANCE].includes(this.state),cadence=run?this.variant.locomotion.runCadence:this.variant.locomotion.walkCadence;if(moving&&this.speed>.02)this.gaitPhase=(this.gaitPhase+cadence*clamp(this.speed/Math.max(this.variant.locomotion.walkSpeed,.01),.25,run?2:1.2)*dt)%1;const speedRatio=clamp(this.speed/(run?this.variant.locomotion.runSpeed:this.variant.locomotion.walkSpeed),0,1),legs=legPose(this.gaitPhase,speedRatio,this.variant.morphology.overallScale,run);
  let neckYaw=headYaw*.62,headLocalYaw=headYaw*.38,neckPitch=-.06-(moving?Math.sin(this.gaitPhase*TAU)*.12*speedRatio:0),headPitch=moving?Math.sin(this.gaitPhase*TAU)*.16*speedRatio:.02,extend=0,bill=false;if(this.state===ChickenNpcState.LOOK){const t=sat(this.intentTime/this.intent.duration),e=ss(0,.18,t)*(1-ss(.78,1,t));neckYaw=headYaw*.62*e;headLocalYaw=headYaw*.38*e;neckPitch=-.08*e;headPitch=.06*Math.sin(t*Math.PI)*e}else if(this.state===ChickenNpcState.PECK){const p=peck(sat(this.intentTime/this.intent.duration)*this.variant.behavior.peckTempo);neckYaw=headYaw*.55;headLocalYaw=headYaw*.45;neckPitch=p.neckPitch;headPitch=p.headPitch;extend=p.extend;bill=p.bill}
  const wing=this.state===ChickenNpcState.WING_BALANCE?ss(0,.12,this.stateTime)*(1-ss(.28,.62,this.stateTime)):0,contacts={leftFoot:legs.left.contact||this.speed<.025,rightFoot:legs.right.contact||this.speed<.025,bill};this.contacts(contacts);
  return{version:'chicken_phase1_pose@1.0',id:this.id,state:this.state,stateTime:this.stateTime,root:{position:[...this.position],yaw:this.yaw,speed:this.speed,velocity:[...this.velocity]},body:{yOffset:moving?Math.sin(this.gaitPhase*TAU*2)*.0075*speedRatio*this.variant.morphology.overallScale:Math.sin(this.stateTime*TAU*1.25)*.0018*this.variant.morphology.overallScale,pitch:run?-.1*speedRatio:-.035*speedRatio,roll:clamp(-this.yawRate*.035,-.11,.11)},neck:{yaw:neckYaw,pitch:neckPitch,extend},head:{yaw:headLocalYaw,pitch:headPitch},legs,wings:{leftOpen:wing*(this.yawRate<0?1:.72),rightOpen:wing*(this.yawRate>0?1:.72)},contacts,collision:{bodyRadius:this.variant.collision.bodyRadius,headRadius:this.variant.collision.headRadius,bodyHalfLength:this.variant.collision.bodyHalfLength},status:{taskComplete:this.taskComplete,blockedTime:this.blockedTime,neighborCount:sep.count,nearestNeighbor:Number.isFinite(sep.nearest)?sep.nearest:null,obstaclePressure:obs.pressure},events:[...this.events]};
 }
}
export function stepChickenFlock(controllers,dt,world={}){const snapshots=controllers.map(c=>c.snapshot());return controllers.map(c=>c.update(dt,{...world,neighbors:snapshots}))}
