import * as THREE from 'three';
import {generateSurface} from './surface-generator.mjs';
import {decodeParameters} from './parameter-codec.mjs';
export async function loadSubjectParameters(url=new URL('./parameters.phf.gz',import.meta.url)){
 const compressed=await (await fetch(url)).arrayBuffer();const bytes=await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();const data=decodeParameters(bytes);if(data.schema!=='parametric-human-fields/v1')throw Error('Wrong subject schema');data.packageBytes=compressed.byteLength;return data;
}
export function createSubject(data,options={}){
 const surface=generateSurface(data,options),geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(surface.positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(surface.colors,3));const count=surface.positions.length/3;for(let half=0;half<2;half++){const ids=new Uint16Array(count*4),weights=new Float32Array(count*4);for(let i=0;i<count;i++)for(let j=0;j<4;j++){ids[i*4+j]=surface.skinIndex[i*8+half*4+j];weights[i*4+j]=surface.skinWeight[i*8+half*4+j];}geometry.setAttribute(half?'skinIndex2':'skinIndex',new THREE.BufferAttribute(ids,4));geometry.setAttribute(half?'skinWeight2':'skinWeight',new THREE.BufferAttribute(weights,4));}geometry.setAttribute('surfaceMaterial',new THREE.BufferAttribute(surface.material,2));geometry.setIndex(new THREE.BufferAttribute(surface.indices,1));if(surface.normals.length===surface.positions.length)geometry.setAttribute('normal',new THREE.BufferAttribute(surface.normals,3));else geometry.computeVertexNormals();
 // Merge shading normals at regenerated seam positions, without storing a mesh.
 const normals=geometry.attributes.normal.array,map=new Map();for(let i=0;i<surface.positions.length;i+=3){const key=Array.from(surface.positions.subarray(i,i+3),v=>Math.round(v*1e6)).join(',');if(!map.has(key))map.set(key,[]);map.get(key).push(i);}for(const rows of map.values())if(rows.length>1){const v=new THREE.Vector3();for(const i of rows)v.add(new THREE.Vector3(...normals.subarray(i,i+3)));v.normalize();for(const i of rows)v.toArray(normals,i);}
 const root=new THREE.Group();root.name='ProceduralSubject';const canonical=new THREE.Group();canonical.name='CanonicalFrame';canonical.position.fromArray(data.offset);canonical.scale.setScalar(data.scale);root.add(canonical);
 const armature=new THREE.Group();armature.name='Armature';armature.position.fromArray(data.armature.p);armature.quaternion.fromArray(data.armature.q);armature.scale.fromArray(data.armature.s);canonical.add(armature);
 const byName=new Map();for(const def of data.rig){const bone=new THREE.Bone();bone.name=def.name;bone.position.fromArray(def.p);bone.quaternion.fromArray(def.q);bone.scale.fromArray(def.s);byName.set(def.name,bone);}for(const def of data.rig){(byName.get(def.parent)||armature).add(byName.get(def.name));}
 root.updateMatrixWorld(true);
 const C=new THREE.Matrix4().makeScale(data.scale,data.scale,data.scale).setPosition(...data.offset),inverseC=C.clone().invert();const skeleton=new THREE.Skeleton(data.boneOrder.map(n=>byName.get(n)),data.inverses.map(a=>new THREE.Matrix4().fromArray(a).multiply(inverseC)));
 const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,metalness:1,side:THREE.DoubleSide});material.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nattribute vec2 surfaceMaterial; varying vec2 vSurfaceMaterial; attribute vec4 skinIndex2; attribute vec4 skinWeight2;').replace('#include <begin_vertex>','#include <begin_vertex>\nvSurfaceMaterial=surfaceMaterial;');const base=THREE.ShaderChunk.skinbase_vertex.replace('#endif','mat4 boneMatX2=getBoneMatrix(skinIndex2.x);mat4 boneMatY2=getBoneMatrix(skinIndex2.y);mat4 boneMatZ2=getBoneMatrix(skinIndex2.z);mat4 boneMatW2=getBoneMatrix(skinIndex2.w);\n#endif');const deform=THREE.ShaderChunk.skinning_vertex.replace(/\btransformed\s*=/,'skinned += boneMatX2*skinVertex*skinWeight2.x + boneMatY2*skinVertex*skinWeight2.y + boneMatZ2*skinVertex*skinWeight2.z + boneMatW2*skinVertex*skinWeight2.w;\ntransformed =');const normal=THREE.ShaderChunk.skinnormal_vertex.replace(/skinMatrix\s*=\s*bindMatrixInverse/,'skinMatrix += skinWeight2.x*boneMatX2+skinWeight2.y*boneMatY2+skinWeight2.z*boneMatZ2+skinWeight2.w*boneMatW2;\nskinMatrix = bindMatrixInverse');shader.vertexShader=shader.vertexShader.replace('#include <skinbase_vertex>',base).replace('#include <skinning_vertex>',deform).replace('#include <skinnormal_vertex>',normal);shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec2 vSurfaceMaterial;').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor *= vSurfaceMaterial.x;').replace('#include <metalnessmap_fragment>','#include <metalnessmap_fragment>\nmetalnessFactor *= vSurfaceMaterial.y;');};const mesh=new THREE.SkinnedMesh(geometry,material);mesh.name='GeneratedSurface';mesh.frustumCulled=false;root.add(mesh);mesh.bind(skeleton,new THREE.Matrix4());mesh.castShadow=true;mesh.receiveShadow=true;
 mesh.applyBoneTransform=function(index,target){const p=target.clone().applyMatrix4(this.bindMatrix),v=new THREE.Vector3(),M=new THREE.Matrix4();target.set(0,0,0);for(let k=0;k<8;k++){const w=surface.skinWeight[index*8+k];if(w){const id=surface.skinIndex[index*8+k];M.multiplyMatrices(skeleton.bones[id].matrixWorld,skeleton.boneInverses[id]);target.addScaledVector(v.copy(p).applyMatrix4(M),w);}}return target.applyMatrix4(this.bindMatrixInverse);};
 const mixer=new THREE.AnimationMixer(root),clips=data.animations.map(c=>new THREE.AnimationClip(c.name,c.duration,c.tracks.map(t=>{const Ctor=t.type==='quaternion'?THREE.QuaternionKeyframeTrack:THREE.VectorKeyframeTrack;return new Ctor(t.name,t.times,t.values,t.interpolation)})));
 const helper=new THREE.SkeletonHelper(canonical);helper.matrixAutoUpdate=true;helper.position.copy(canonical.position);helper.quaternion.copy(canonical.quaternion);helper.scale.copy(canonical.scale);helper.visible=false;helper.material.depthTest=false;helper.material.transparent=true;helper.material.opacity=.75;root.add(helper);
 const rest=[];root.traverse(o=>{if(o.isBone||o===armature)rest.push({o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()})});let active='rest',paused=false;
 function play(name){mixer.stopAllAction();for(const r of rest){r.o.position.copy(r.p);r.o.quaternion.copy(r.q);r.o.scale.copy(r.s);}active=name;if(name!=='rest'){const clip=clips.find(c=>c.name===name);if(!clip)throw Error('Unknown clip '+name);mixer.clipAction(clip).reset().play();}root.updateMatrixWorld(true);skeleton.update();}
 return {root,mesh,skeleton,mixer,clips,helper,surface,data,play,command(text){const name=/跳/.test(text)?'jump':/跑/.test(text)?'run':/走|步/.test(text)?'walk':/看|环顾/.test(text)?'look_around':'rest';play(name);return {phase:name,authority:'authored-61-bone-curves'}},step(dt){if(!paused)mixer.update(Math.min(dt,.06));root.updateMatrixWorld(true);skeleton.update();},setPaused(v){paused=v},get phase(){return active}};
}
