import fs from 'node:fs';import * as T from '../r02/site/three.module.js';import {buildSeam,insideHole,auditSeam} from './site/seam.mjs';import {buildContactField,mapSurfacePoint} from './site/contact-surface.mjs';
let s=fs.readFileSync(new URL('./site/geometry.js',import.meta.url),'utf8').replace("from 'three'",`from '${new URL('../r02/site/three.module.js',import.meta.url).href}'`).replace("from './seam.mjs'",`from '${new URL('./site/seam.mjs',import.meta.url).href}'`).replace("from './contact-surface.mjs'",`from '${new URL('./site/contact-surface.mjs',import.meta.url).href}'`);
const {makeLeatherGeometry,makeThreadGeometry}=await import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));
const tests=[];function ck(name,pass,details={}){tests.push({name,pass:!!pass,...details});if(!pass)console.error('FAIL',name,details);}
const g=makeThreadGeometry([[0,0,0],[5,0,0]],.4,true),pa=g.attributes.position,na=g.attributes.normal;let dots=[];for(let i=33;i<g.userData.ringCount*g.userData.ringStride-33;i++)dots.push(pa.getY(i)*na.getY(i)+pa.getZ(i)*na.getZ(i));ck('thread normals point OUTWARD, not hollow backfaces',dots.every(x=>x>0),{minRadialDot:Math.min(...dots)});
const ray=new T.Raycaster(new T.Vector3(2,2,0),new T.Vector3(0,-1,0)),obj=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));obj.updateMatrixWorld();ck('FrontSide thread is solid from above',ray.intersectObject(obj).length>0);ray.set(new T.Vector3(2,-2,0),new T.Vector3(0,1,0));ck('FrontSide thread is solid from below',ray.intersectObject(obj).length>0);
for(const tension of [0,.8,2.4]){
 const m=buildSeam({tensionN:tension});m.contact=buildContactField(m);ck('local elastic field converges '+tension,m.contact.stats.relativeResidual<1e-5,m.contact.stats);ck('finite field '+tension,m.contact.arrays.w.every(Number.isFinite));if(tension===0)ck('zero tension = ZERO load-driven displacement',m.contact.stats.minDisplacementMM===0&&m.contact.stats.maxDisplacementMM===0);
 const data=makeLeatherGeometry(m);
 for(const f of data.surfaces){let good=0,bad=0;const p=f.geometry.attributes.position,ix=f.geometry.index.array;for(let j=0;j<ix.length;j+=3){const a=new T.Vector3().fromBufferAttribute(p,ix[j]),b=new T.Vector3().fromBufferAttribute(p,ix[j+1]),c=new T.Vector3().fromBufferAttribute(p,ix[j+2]);const n=new T.Vector3().crossVectors(b.sub(a),c.sub(a));if(n.y*f.side>0)good++;else bad++;}ck(`outer and inner layer face winding ${f.layer}/${f.side}, T=${tension}`,bad===0,{good,bad});}
 const meshes=[...data.surfaces,...data.walls].map(g=>{const o=new T.Mesh(g.geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));o.updateMatrixWorld();return o;});
 for(const h of m.holes){const pt=mapSurfacePoint(m,[h.x,0,h.z]);ray.set(new T.Vector3(pt[0],10,pt[2]),new T.Vector3(0,-1,0));ck(`actual hole remains through, T=${tension}/${h.id}`,ray.intersectObjects(meshes).length===0);}
 if(tension>0){const f=data.surfaces.find(x=>x.layer===0&&x.side===1);let minY=1e9;for(let i=0;i<f.geometry.attributes.position.count;i++)minY=Math.min(minY,f.geometry.attributes.position.getY(i));ck('actual leather vertices depress under thread '+tension,minY<m.params.layerThickness-.03,{minY});}
 for(const route of m.routes){const tr=makeThreadGeometry(route.points.map(x=>mapSurfacePoint(m,x)),m.params.diameter,true);ck('finite complete thread mesh '+route.id+' '+tension,tr.attributes.position.array.every(Number.isFinite)&&tr.index.isBufferAttribute);}
}
const low=buildContactField(buildSeam({tensionN:.4})).stats,high=buildContactField(buildSeam({tensionN:1.6})).stats;ck('four times load increases linear local response four times',Math.abs(high.minDisplacementMM/low.minDisplacementMM-4)<1e-8);
const off=buildContactField(buildSeam(),false);ck('A/B off truly removes contact deformation',off.stats.minDisplacementMM===0);
fs.mkdirSync(new URL('./qa/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('./qa/r051-geometry-contact.json',import.meta.url),JSON.stringify({tests,pass:tests.every(t=>t.pass),scope:'orientation, local-response numerics and rendered-coordinate consistency; no physical calibration'},null,2));console.log('RESULT',tests.filter(t=>t.pass).length,tests.length);if(tests.some(t=>!t.pass))process.exitCode=1;
