import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {assemble} from '../../tools/build-pure.mjs';
const dir=new URL('./',import.meta.url),root=new URL('../../',dir);
const read=p=>readFileSync(new URL(p,root),'utf8');
mkdirSync(new URL('generated/',dir),{recursive:true});
mkdirSync(new URL('runtime-assets/',dir),{recursive:true});
const original=readFileSync('C:/Users/Administrator/Downloads/NEW_HUMAN_MOTION_BEHAVIOR_R005_1_FIXED.html','utf8');
const chunks=original.match(/const EMBEDDED_MODEL_CHUNKS\s*=\s*(\[[\s\S]*?\]);/);
if(!chunks)throw Error('Missing embedded source model');
const source=Buffer.from(JSON.parse(chunks[1]).join(''),'base64');
const sha=createHash('sha256').update(source).digest('hex');
if(sha!=='b0435f3f30e0d63b6d4527000b7995b16fa91ca0ba8cb16b811be285e4fe7567')throw Error('Source model identity changed');
writeFileSync(new URL('runtime-assets/source.usdz',dir),source);
const ref=JSON.parse(read('reconstruction/rig-reference.json'));
let runtime=assemble().runtime.split('// MODULE app')[0];
runtime=runtime.replace('const R2_RIG='+JSON.stringify(ref)+';','const R2_RIG=subjectReference;');
if(!runtime.includes('const R2_RIG=subjectReference;'))throw Error('Pinned reference injection failed');
const compact=read('body/CompactBinding.js').replace('/*__COMPACT_BINDING_CORE__*/','');
const output=`// Generated from pinned R2 production modules. Rebuild with prepare.mjs.\nexport function createInheritedHumanCore(subjectReference){\n${runtime}\n${compact}\nreturn {Human,World,Agent,MotionLabPose,MotionLab,qi,qm,inv,rotate,r2SourceFrames,compactSourceRig,r2DeformPoint,\nbuild(input={},log=()=>{}){const h=new Human(input);h.tissue=new ReconstructionState(h);const w=new World(260901);w.objects=[];w.zones=[];const a=new Agent(h,w,log);return {h,w,a};}};\n}\n`;
writeFileSync(new URL('generated/inherited-core.mjs',dir),output);
writeFileSync(new URL('generated/reference.json',dir),JSON.stringify(ref));
console.log(JSON.stringify({sourceBytes:source.length,sourceSHA256:sha,coreBytes:Buffer.byteLength(output),joints:Object.keys(ref.nodes).length}));
