import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {LastKernel,DEFAULT,KEYS,validateState,bounds,VERSION,shoeConstructionGate} from './kernel.mjs';
import {buildSeam,continuousRoutes,auditSeam} from '../vendor/leather/seam.mjs';
import {compile,example} from '../vendor/tailor/structured/compiler.mjs';
const $=s=>document.querySelector(s),fmt=(n,k=1)=>Number(n).toFixed(k),clone=structuredClone;
const palette=['#bb6d45','#477f79','#708d55','#6783a3','#a885ae','#bd995d'];
const buildId=typeof __BUILD_ID__==='undefined'?'local-source':__BUILD_ID__;
const methodUrl='https://github.com/haihao0307/Humanoid-Rig-Lab-Next/blob/a0cd098b4a0fcb8b5d5de90200acd0fb1051f543/WORKBENCH_BUILD_SYSTEM.md';
const descriptions={
 source:['01 / SOURCE REPLAY','楦上设计线','原始几何 · 待核对','Parametric shoe last.3dm · #32','闭合设计线 #29 / #30 / #31 · 未另造鞋壳','原文件中的鞋楦与设计线按毫米尺度展示。原始三维设计线和二维裁片尚未完成对应校准；这里不是已经缝制好的鞋。'],
 last:['02 / PARAMETRIC RESEARCH','参数化鞋楦','独立实现 · 非 GH 等价认证','原工程对象 #1 + 六条 GH 引用截线','零偏移严格恢复原数据；修改会令旧纸样失效','研究内核把截线位移按归一化 1/r³ 权重传播到原楦网格。该公式在原 GH 文件中出现，但本浏览器实现未与 Rhino / Grasshopper 输出做逐点等价认证。目标截线与实际变形标线的残差会显示。'],
 panels:['03 / ORIGINAL PATTERN PARTS','真实裁片','原始数据 · 非生产定版','原工程中的 9 个平面部件','只重排陈列位置，不重画裁剪轮廓','每块裁片保留原 CAD 轮廓、贯穿孔及厚度。若鞋楦已修改，这些仍是只读原样，不能继续当作适配后的纸样；目前不提供假缝合动画或生产纸样认证。'],
 seam:['04 / INHERITED SEWING KERNEL','连续针路','真实针路 · 独立试片','继承皮革台 R05.1 的连续马鞍缝','真实孔壁 / 正反两面 / 一根线的两个工作端','本工位是从皮革台继承的针路试片，不是成鞋。改变针距、针数和皮层厚度会重新构造孔、层和连续线；尚未把它绑定到原鞋片的真实缝边。'],
 method:['05 / WORKBENCH BUILD SYSTEM','方法与验收','六系统独立记录','本轮限定 S1 子能力','不把参考、执行、适配、验收混在一起','执行顺序采用仓库《KAOPU 顶尖工作台搭建方法论 V1.0》。本轮参考传输和参数研究可测试；整套制鞋与用户视觉认可仍未完成。']};
function toast(text){const e=$('#toast');e.textContent=text;e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',4500);}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function loadData(){const tag=$('#teacher-data');if(!tag)throw Error('缺少构建时内嵌的原工程数据，请使用 public-lite.html');const raw=Uint8Array.from(atob(tag.textContent.trim()),c=>c.charCodeAt(0));const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}
function simplify(pts,tol=.012){if(pts.length<=2)return pts;const a=pts[0],b=pts.at(-1),v=b.map((x,k)=>x-a[k]),ll=v.reduce((s,x)=>s+x*x,0);let max=0,index=0;for(let i=1;i<pts.length-1;i++){const p=pts[i],t=Math.max(0,Math.min(1,p.reduce((s,x,k)=>s+(x-a[k])*v[k],0)/Math.max(1e-20,ll))),d=p.reduce((s,x,k)=>s+(x-a[k]-t*v[k])**2,0);if(d>max){max=d;index=i;}}if(max<tol*tol)return[a,b];return [...simplify(pts.slice(0,index+1),tol).slice(0,-1),...simplify(pts.slice(index),tol)];}
class Polyline extends T.Curve{constructor(points){super();this.points=points;this.ds=[0];for(let i=1;i<points.length;i++)this.ds.push(this.ds.at(-1)+points[i].distanceTo(points[i-1]));this.total=this.ds.at(-1);}getPoint(t,target=new T.Vector3()){const d=Math.max(0,Math.min(1,t))*this.total;let l=0,r=this.ds.length-1;while(r-l>1){const m=(l+r)>>1;if(this.ds[m]<d)l=m;else r=m;}return target.copy(this.points[l]).lerp(this.points[r],(d-this.ds[l])/Math.max(1e-20,this.ds[r]-this.ds[l]));}}
async function init(){
 const data=await loadData();let state=DEFAULT(),kernel=new LastKernel(data);kernel.evaluate(state.lastDeltaPercent);let pieceOnly=false,seamModel=null,buildCount=0,renderCount=0,sourceVisibleOriginal=false,detailView=false;
 const canvas=$('#canvas'),view=$('#viewport');const renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene();scene.background=new T.Color('#e9e5dc');const pm=new T.PMREMGenerator(renderer);const env=new RoomEnvironment();scene.environment=pm.fromScene(env,.035).texture;env.dispose();pm.dispose();scene.environmentIntensity=.65;
 const camera=new T.PerspectiveCamera(32,1,.08,15000);const control=new OrbitControls(camera,canvas);control.enableDamping=false;control.minDistance=8;control.maxDistance=4500;control.addEventListener('change',render);const root=new T.Group();scene.add(root);
 const key=new T.DirectionalLight(0xfff3df,2.7);key.position.set(-230,420,280);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-700,right:700,top:700,bottom:-700,near:1,far:1500});key.shadow.bias=-.00003;scene.add(key);scene.add(key.target);scene.add(new T.HemisphereLight('#ffffff','#747067',1.1));const fill=new T.DirectionalLight('#dae5f0',.8);fill.position.set(270,170,-100);scene.add(fill);
 const floor=new T.Mesh(new T.PlaneGeometry(2400,2400),new T.MeshStandardMaterial({color:'#e9e5dc',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-3;floor.receiveShadow=true;scene.add(floor);
 const raycaster=new T.Raycaster(),mouse=new T.Vector2();let down=null;canvas.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObject(root,true).find(h=>h.object.userData.piece!==undefined);if(hit&&state.mode==='panels'){state.piece=hit.object.userData.piece;rebuild(false);inspector();}});
 function render(){if(!renderer||state.mode==='method')return;renderer.render(scene,camera);renderCount++;const info=renderer.info.render;$('#render-stats').textContent=fmt(info.triangles/1000,1)+'k 三角形 · 按需重绘';}
 function resize(){const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();setCamera(state.camera);render();}
 function clear(){const gs=new Set(),ms=new Set();root.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m);});root.clear();gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
 const material=(color,roughness=.62)=>new T.MeshStandardMaterial({color,roughness,metalness:0,side:T.DoubleSide});
 function transformFor(o,kind){const c=o.bbox[0].map((v,k)=>(v+o.bbox[1][k])/2),z0=o.bbox[0][2];if(kind==='base')return {p:v=>new T.Vector3(-(v[1]-c[1]),v[2]-z0,-(v[0]-c[0])),n:v=>new T.Vector3(-v[1],v[2],-v[0]),inverse:p=>[c[0]-p.z,c[1]-p.x,p.y+z0]};return {p:v=>new T.Vector3(v[1]-c[1],v[2]-z0,v[0]-c[0]),n:v=>new T.Vector3(v[1],v[2],v[0]),inverse:p=>[p.z+c[0],p.x+c[1],p.y+z0]};}
 function sourceMesh(o,tr,positions=o.positions,color='#c0b392',wire=false){const p=[];for(let i=0;i<positions.length;i+=3)p.push(...tr.p(positions.slice(i,i+3)));const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(o.indices);if(positions===o.positions&&o.normals){const ns=[];for(let i=0;i<o.normals.length;i+=3)ns.push(...tr.n(o.normals.slice(i,i+3)));g.setAttribute('normal',new T.Float32BufferAttribute(ns,3));}else g.computeVertexNormals();const m=material(color);m.wireframe=wire;const mesh=new T.Mesh(g,m);mesh.name='NATIVE_SOURCE_OBJECT_'+o.objectIndex;mesh.castShadow=!wire;mesh.receiveShadow=!wire;root.add(mesh);return mesh;}
 function line(points,color,radius=.3){const pts=points.map(p=>p instanceof T.Vector3?p:new T.Vector3(...p));const cv=new Polyline(pts);const g=new T.TubeGeometry(cv,Math.max(40,Math.ceil(cv.total/1.5)),radius,5,false),m=new T.Mesh(g,new T.MeshBasicMaterial({color}));m.name='SOURCE_CURVE';root.add(m);return m;}
 function label(text,p,color='#786854'){const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='rgba(253,251,244,0.9)';ctx.fillRect(0,0,256,64);ctx.strokeStyle='#d6caba';ctx.strokeRect(1,1,254,62);ctx.fillStyle=color;ctx.font='32px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,33);const tx=new T.CanvasTexture(c),mat=new T.SpriteMaterial({map:tx,depthTest:false,depthWrite:false,toneMapped:false});const s=new T.Sprite(mat);s.position.copy(p);s.scale.set(144,36,1);s.userData.labelTexture=tx;root.add(s);return s;}
 function disposeLabels(){root.traverse(o=>{if(o.userData.labelTexture)o.userData.labelTexture.dispose();});}
 function buildSource(){const tr=transformFor(data.last,'source');sourceMesh(data.last,tr,undefined,'#c3b79a',state.wireframe);for(let j=0;j<data.styleCurves.length;j++){const c=data.styleCurves[j];line(c.points.map(tr.p),palette[j],c.objectIndex===state.selectedCurve?.55:.3);} }
 function buildLast(){const tr=transformFor(data.baseLast,'base');const p=sourceVisibleOriginal?data.baseLast.positions:kernel.positions;const m=sourceMesh(data.baseLast,tr,p,'#c3b79a',state.wireframe);m.name='EDITABLE_SOURCE_LAST';for(const [j,s]of (sourceVisibleOriginal?data.sections:kernel.currentSections).entries())line(s.points.map(tr.p),palette[j],.26);if(state.overlay&&kernel.changed){const m2=sourceMesh(data.baseLast,tr,undefined,'#617e70',true);m2.material.transparent=true;m2.material.opacity=.24;m2.material.depthWrite=false;m2.name='READ_ONLY_REFERENCE_OVERLAY';} }
 function buildPanels(){const cols=3,spacingX=245,spacingZ=220;const chosen=pieceOnly?data.panels.filter(p=>p.objectIndex===state.piece):data.panels;for(const [j,o]of chosen.entries()){const min=o.bbox[0],max=o.bbox[1],cx=(min[0]+max[0])/2,cy=(min[1]+max[1])/2,z0=min[2],th=(max[2]-min[2])*state.panelThicknessScale;const dx=pieceOnly?0:(j%cols-1)*spacingX,dz=pieceOnly?0:(Math.floor(j/cols)-1)*spacingZ;const p=[],n=[];for(let i=0;i<o.positions.length;i+=3)p.push(o.positions[i]-cx+dx,(o.positions[i+2]-z0)*state.panelThicknessScale,-(o.positions[i+1]-cy)+dz);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(o.indices);g.computeVertexNormals();const selected=o.objectIndex===state.piece,m=material(selected?'#96754d':'#94998c',.79);m.wireframe=state.wireframe;const mesh=new T.Mesh(g,m);mesh.userData.piece=o.objectIndex;mesh.name='ORIGINAL_PATTERN_P'+o.objectIndex;mesh.castShadow=true;mesh.receiveShadow=true;root.add(mesh);for(const f of o.footprints){for(const curve of [f.outer,...f.holes])line(curve.map(p=>[p[0]-cx+dx,th+.12,-(p[1]-cy)+dz]),selected?'#543b22':'#485346',.40);}label('P'+o.objectIndex+' · '+fmt(th,1)+' mm',new T.Vector3(dx,th+7,dz+(max[1]-min[1])/2+12));} }
 function yarn(points,diameter){const pts=simplify(points,.01).map(p=>new T.Vector3(...p)),positions=[],normals=[],ix=[];const sides=8;let prevN=new T.Vector3(0,1,0);for(let i=0;i<pts.length;i++){const p=pts[i],t=pts[Math.min(i+1,pts.length-1)].clone().sub(pts[Math.max(0,i-1)]).normalize();const n=prevN.clone().addScaledVector(t,-prevN.dot(t));if(n.lengthSq()<1e-8){n.set(1,0,0).addScaledVector(t,-t.x);if(n.lengthSq()<1e-8)n.set(0,0,1).addScaledVector(t,-t.z);}n.normalize();prevN=n.clone();const bin=new T.Vector3().crossVectors(t,n).normalize();for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2,cos=Math.cos(a),sin=Math.sin(a),pp=p.clone().addScaledVector(n,cos*diameter*.23).addScaledVector(bin,sin*diameter*.51),nn=n.clone().multiplyScalar(cos/.23).addScaledVector(bin,sin/.51).normalize();positions.push(...pp);normals.push(...nn);if(i<pts.length-1&&j<sides){const q=i*(sides+1)+j;ix.push(q,q+sides+1,q+1,q+1,q+sides+1,q+sides+2);}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setIndex(ix);const m=new T.Mesh(g,material('#e4d2aa',.75));m.name='INHERITED_ONE_CONTINUOUS_SADDLE_THREAD';root.add(m);}
 function buildSeamView(){seamModel=buildSeam({...state.seam,type:'saddle'});const p=seamModel.params;const groupOffset=9;for(let layer=0;layer<2;layer++){const sh=new T.Shape(),w=seamModel.width,d=seamModel.depth;sh.moveTo(-w/2,-d/2);sh.lineTo(w/2,-d/2);sh.lineTo(w/2,d/2);sh.lineTo(-w/2,d/2);sh.closePath();for(const h of seamModel.holes){const hole=new T.Path();hole.absellipse(h.x,-h.z,h.rx,h.rz,0,Math.PI*2,true,-h.angle);sh.holes.push(hole);}const geo=new T.ExtrudeGeometry(sh,{depth:p.layerThickness,bevelEnabled:false,steps:1,curveSegments:24});geo.rotateX(-Math.PI/2);geo.translate(0,-p.layerThickness+layer*p.layerThickness,0);const m=new T.Mesh(geo,material(layer?'#774d30':'#b19067',.76));m.name='PERFORATED_LEATHER_LAYER_'+layer;m.userData.seamLeather=true;m.castShadow=true;m.receiveShadow=true;root.add(m);}for(const r of continuousRoutes(seamModel))yarn(r.points,p.diameter);root.position.y=groupOffset;floor.position.y=0; }
 function rebuild(fit=true){disposeLabels();clear();root.position.set(0,0,0);floor.position.y=-3;floor.visible=state.camera!=='bottom';buildCount++;kernel.evaluate(state.lastDeltaPercent);if(state.mode==='source')buildSource();else if(state.mode==='last')buildLast();else if(state.mode==='panels')buildPanels();else if(state.mode==='seam')buildSeamView();$('#method-view').hidden=state.mode!=='method';canvas.hidden=state.mode==='method';for(const el of ['.canvas-label','.canvas-tools','.canvas-footer'])$(el).hidden=state.mode==='method';$('#seam-detail').hidden=state.mode!=='seam';if(fit){detailView=false;setCamera(state.camera);}else if(detailView)seamDetail();updateNumbers();render();}
 function setCamera(name){detailView=false;state.camera=name;floor.visible=name!=='bottom';const box=new T.Box3().setFromObject(root);if(box.isEmpty())return;const center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),r=box.getBoundingSphere(new T.Sphere()).radius;const v=Math.min(camera.fov*Math.PI/360,Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect));const distance=r/Math.sin(v)*1.22;const sr=Math.max(r,8);key.target.position.copy(center);key.position.copy(center).add(new T.Vector3(-.85,1.55,1.05).multiplyScalar(sr*3.4));Object.assign(key.shadow.camera,{left:-sr*1.3,right:sr*1.3,top:sr*1.3,bottom:-sr*1.3,near:sr*.05,far:sr*14});key.shadow.camera.updateProjectionMatrix();key.shadow.bias=-.0002;key.shadow.normalBias=sr*.0008;key.shadow.needsUpdate=true;const dirs={hero:[1.3,1.05,1.7],side:[1,.14,0],front:[0,.14,1],top:[0,1,.00001],bottom:[0,-1,.00001]};const direction=new T.Vector3(...dirs[name]).normalize();camera.up.set(0,1,0);if(name==='top')camera.up.set(0,0,-1);if(name==='bottom')camera.up.set(0,0,1);control.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);camera.near=Math.max(.02,distance/1000);camera.far=Math.max(5000,distance*8);camera.updateProjectionMatrix();control.update();document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===name));render();}
 function seamDetail(){if(state.mode!=='seam'||!seamModel)return;detailView=true;const h=seamModel.holes[Math.floor(seamModel.holes.length/2)],center=new T.Vector3(h.x,root.position.y,h.z);control.target.copy(center);camera.up.set(0,1,0);camera.position.copy(center).add(new T.Vector3(5.2,7.4,8.6));camera.near=.015;camera.far=5000;camera.updateProjectionMatrix();control.update();document.querySelectorAll('[data-camera]').forEach(b=>b.classList.remove('active'));render();}
 $('#seam-detail').onclick=seamDetail;
 function metric(id,name,value,unit='mm'){return `<div class="metric"><span>${name}</span><strong id="${id}">${value} <small>${unit}</small></strong></div>`;}
 function slider(key,name,min,max,step,value,helper=''){return `<div class="control"><label for="p-${key}">${name}<output id="v-${key}">${value}</output></label><input id="p-${key}" data-param="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}">${helper?`<small>${helper}</small>`:''}</div>`;}
 function inspector(){let h='';if(state.mode==='source'){const b=bounds(data.last.positions);h=metric('src-length','原楦纵向长度',fmt(b.size[0]))+metric('src-width','原楦横向宽度',fmt(b.size[1]))+metric('src-height','原楦高度',fmt(b.size[2]))+'<div class="section-heading">原始设计线</div><div class="pill-row">'+data.styleCurves.map((c,i)=>`<button data-curve="${c.objectIndex}" class="${state.selectedCurve===c.objectIndex?'active':''}">C${c.objectIndex}</button>`).join('')+'</div>'+data.styleCurves.map(c=>metric('curve-'+c.objectIndex,'C'+c.objectIndex+' · 闭合线长',fmt(c.lengthMm))).join('')+'<p class="small">数值来自实际缓存几何和采样曲线。不是足长，也不是鞋内腔合脚证明。保留原 CAD 形状，检验灯光为本站中性着色。</p>';}
 else if(state.mode==='last'){const r=kernel.report();h=metric('last-length','实际纵向长度',fmt(r.lengthMm))+metric('last-width','实际横向宽度',fmt(r.widthMm))+metric('last-height','实际高度',fmt(r.heightMm))+'<div class="section-heading">原始截线驱动 · 设计偏移</div><p class="small">每条曲线通过 GH RefID 对上原 CAD。默认 0% 为原例；±8% 是本研究的限制，不是人体或生产标准。</p>'+data.sections.map(s=>slider(s.key,s.label,-8,8,.5,state.lastDeltaPercent[s.key],`<span id="m-${s.key}">原线 ${fmt(s.lengthMm)} mm</span>`)).join('')+metric('displacement','最大真实位移',fmt(r.maxDisplacementMm,3))+'<div class="gh-source">GH 原文件保存目标值：'+data.sourceAudit.selectedSourceInputs.map(s=>`${s.nickname} ${s.value}`).join(' / ')+'。只读记录，不冒充当前实测值或已重现输出。</div>';}
 else if(state.mode==='panels'){const o=data.panels.find(p=>p.objectIndex===state.piece),b=bounds(o.positions);h='<div class="piece-grid">'+data.panels.map(p=>`<button data-piece="${p.objectIndex}" class="${state.piece===p.objectIndex?'active':''}">P${p.objectIndex}</button>`).join('')+'</div>'+`<button class="wide" id="isolate">${pieceOnly?'显示全部原片':'只观察所选原片'}</button>`+metric('panel-width','原片 X 尺寸',fmt(b.size[0]))+metric('panel-depth','原片 Y 尺寸',fmt(b.size[1]))+metric('panel-thickness','实际厚度',fmt(b.size[2]*state.panelThicknessScale,2))+metric('panel-holes','缓存投影封闭孔',o.footprints.reduce((a,f)=>a+f.holes.length,0),'个')+metric('panel-area','投影材料面积',fmt(o.footprints.reduce((a,f)=>a+f.areaMm2,0),0),'mm²')+slider('panelThickness','厚度研究倍率',.5,2,.1,state.panelThicknessScale,'只改厚度，不重绘轮廓，不增加猜测的缝份。')+`<p class="small">原对象 #${o.objectIndex}<br>原图层：${o.layer}<br>原对象没有完整语义命名。投影边界按缓存三角形计算，忽略面积 ≤10⁻⁶ mm² 的数值裂隙；不修改原网格，不代替制造级轮廓。</p>`;}
 else if(state.mode==='seam'){h=slider('count','孔位数量',5,25,1,state.seam.count)+slider('pitch','针距 / mm',2.5,5.5,.1,state.seam.pitch)+slider('layerThickness','单层皮厚 / mm',.8,2.5,.1,state.seam.layerThickness)+slider('diameter','线径 / mm',.24,.60,.02,state.seam.diameter)+`<div class="section-heading">继承内核检查</div><div id="seam-report"></div><p class="small">内核来源：leather-workshop/r05/site/seam.mjs。针路不等于张力／摩擦物理求解。真实鞋片的缝边还未绑定。</p>`;}
 else h=`<p class="small">已接入观察员的分系统、分阶段检查原则，并固定引用仓库方法论。</p><a href="${methodUrl}" target="_blank" rel="noopener">打开完整搭建方法 ↗</a><div class="gh-source">原工程 RefID：${data.sourceAudit.externalReferences.length-data.sourceAudit.missingReferenceCount}/${data.sourceAudit.externalReferences.length} 在配套 CAD 中找到。<br>Rhino / Grasshopper 计算引擎：本轮未执行。<br>当前：缓存几何复现 + 独立参数研究。</div>`;
 $('#inspect-body').innerHTML=h;$('#inspect-title').textContent={source:'原几何测量',last:'原始截线与参数',panels:'裁片身份与尺寸',seam:'孔、层和连续线',method:'来源与证据'}[state.mode];updateNumbers();}
 function updateNumbers(){const r=kernel.report();for(const [id,val]of Object.entries({'last-length':r.lengthMm,'last-width':r.widthMm,'last-height':r.heightMm,'displacement':r.maxDisplacementMm}))if($('#'+id))$('#'+id).textContent=fmt(val,id==='displacement'?3:1)+' mm';for(const s of r.sections||[]){const el=$('#m-'+s.key);if(el)el.textContent=`原线 ${fmt(s.sourceLengthMm)} → 当前标线 ${fmt(s.guideLengthMm)} mm · 目标差 ${fmt(s.guideResidualMm,2)} mm`;const out=$('#v-'+s.key);if(out)out.textContent=(state.lastDeltaPercent[s.key]>0?'+':'')+state.lastDeltaPercent[s.key]+'%';}
 $('#gate-state').textContent=kernel.changed?'鞋楦已改：原纸样失效':'尚未进入成鞋缝合';$('#gate-detail').textContent=kernel.changed?'当前仍可查看原裁片，但它们没有重新展平和配缝，不能输出为已适配纸样。':'裁片对应、缝边方向和装配工序未核准。不用插值动画冒充缝合求解。';
 if(state.mode==='panels'&&$('#panel-thickness')){const o=data.panels.find(p=>p.objectIndex===state.piece);$('#panel-thickness').textContent=fmt((o.bbox[1][2]-o.bbox[0][2])*state.panelThicknessScale,2)+' mm';}
 if(state.mode==='seam'&&seamModel&&$('#seam-report')){const a=auditSeam(seamModel);$('#seam-report').innerHTML=metric('thread-count','连续线',a.threadCount,'根')+metric('passage-count','穿层针路段',a.passages,'段')+metric('thread-join','线端连接误差',fmt(a.threadJoinErrorMM,5))+metric('thread-outside','孔外针路点',a.pointsOutsideHole,'个');}
 }
 function mode(name,preserveRevision=false){if(!Object.hasOwn(descriptions,name))throw Error('未知工位');state.mode=name;if(!preserveRevision)state.revision++;state.camera=name==='panels'?'top':'hero';pieceOnly=false;const x=descriptions[name];$('#station-kicker').textContent=x[0];$('#station-title').textContent=x[1];$('#station-status').textContent=x[2];$('#model-label').textContent=x[3];$('#model-subtitle').textContent=x[4];$('#boundary-note').textContent=x[5];document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===name));rebuild();inspector();}
 function setState(s){const v=validateState(s);state=v;const savedCam=v.camera,savedMode=v.mode;mode(savedMode,true);state.camera=savedCam;setCamera(savedCam);syncControls();}
 function syncControls(){$('#wire').classList.toggle('active',state.wireframe);$('#overlay').classList.toggle('active',state.overlay);}
 function guards(){const good=compile(example()),bad=example(),missing=example();bad.stitches[0].b.reverse=false;missing.stitches[0].b.panelId='NOT_A_REAL_PANEL';let direction=null,reference=null;try{compile(bad);}catch(e){direction=String(e);}try{compile(missing);}catch(e){reference=String(e);}const out={normalThreePanels:good.report.valid===true,reversedSeamRejected:!!direction,missingPanelRejected:!!reference,direction,reference,shoeGate:shoeConstructionGate(state),nativeSourcesUnmodified:true};$('#guard-result').textContent=`原三片样例：${out.normalThreePanels?'通过':'失败'}；反向缝边：${direction?'被拒绝':'未发现错误'}；不存在的裁片：${reference?'被拒绝':'未发现错误'}。真实成鞋工序仍被拦截。`;return out;}
 $('#modes').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b)mode(b.dataset.mode);});$('#cameras').addEventListener('click',e=>{const b=e.target.closest('[data-camera]');if(b)setCamera(b.dataset.camera);});$('#inspect-body').addEventListener('click',e=>{const p=e.target.closest('[data-piece]'),c=e.target.closest('[data-curve]');if(p){state.piece=Number(p.dataset.piece);state.revision++;rebuild(pieceOnly);inspector();}if(c){state.selectedCurve=Number(c.dataset.curve);rebuild(false);inspector();}if(e.target.id==='isolate'){pieceOnly=!pieceOnly;rebuild();inspector();}});
 $('#inspect-body').addEventListener('input',e=>{const k=e.target.dataset.param;if(!k)return;const v=Number(e.target.value);if(KEYS.includes(k))state.lastDeltaPercent[k]=v;else if(k==='panelThickness')state.panelThicknessScale=v;else state.seam[k]=v;state.revision++;validateState(state);const out=$('#v-'+k);if(out)out.textContent=v;rebuild(false);});
 $('#wire').onclick=()=>{state.wireframe=!state.wireframe;syncControls();rebuild(false);};$('#overlay').onclick=()=>{if(state.mode!=='last'){toast('原例叠加用于“参数化鞋楦”工位；原工程本身没有修改。');return;}state.overlay=!state.overlay;syncControls();rebuild(false);};$('#reset').onclick=()=>{state.lastDeltaPercent=DEFAULT().lastDeltaPercent;state.panelThicknessScale=1;state.seam=DEFAULT().seam;state.overlay=false;state.wireframe=false;state.revision++;rebuild();inspector();syncControls();toast('已恢复原始数据与默认针路，未覆盖来源文件。');};
 $('#save').onclick=()=>{try{localStorage.setItem('kaopu-shoe-r02-study',JSON.stringify(state));toast('研究配方已保存到此浏览器。');}catch(e){toast('本浏览器未允许保存，请使用导出配方。');}};$('#restore').onclick=()=>{try{const s=localStorage.getItem('kaopu-shoe-r02-study');if(!s)throw Error('没有本机保存记录');setState(JSON.parse(s));toast('保存的研究配方已恢复。');}catch(e){toast(String(e));}};$('#export').onclick=()=>download('KAOPU_SHOE_R02_STUDY.json',JSON.stringify(state,null,2));$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{if(!e.target.files[0])return;setState(JSON.parse(await e.target.files[0].text()));toast('配方验证并导入成功。');}catch(e){toast('拒绝导入：'+e.message);}finally{$('#file').value='';}};$('#shot').onclick=()=>{render();const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='KAOPU_SHOE_R02_'+state.mode+'.png';a.click();};$('#guard-test').onclick=()=>{guards();toast('反例检查已运行。它不能代替成鞋验收。');};
 $('#method-view').innerHTML=`<div class="eyebrow">LOCK → EXECUTE → VERIFY → PROMOTE</div><h3>六个子系统，各自证明。</h3><p class="intro">先忠实复现有来源的原例，再研究哪些量控制形态。没有完成的部分保留明确状态，不让材质好看、按钮可点或测试数量掩盖结构问题。</p><div class="method-grid">${[
 ['01 · 制鞋结构','9 个原始平面部件可查。裁片到楦面、缝边方向、吃势、工序和重新展平尚未校准，因此拦截成鞋。连续针路先在带孔皮革试片核对。'],
 ['02 · 足—鞋—地面力学','尚未接入。外形和截线长度不证明压力、舒适性或鞋底承载。TPE 热成型也不能替代皮革绷楦工艺。'],
 ['03 · 影视外观','本轮中性灯只用于检查形态、孔和厚度。最终皮革、织物、鞋底与五金的影视级表面尚未验收。'],
 ['04 · 动态动作适配','尚未接入人物当前脚踝、前掌和脚趾姿态。不得用整体旋转或预设摆动冒充鞋体形变。'],
 ['05 · 接触／碰撞形变','尚未接入。当前针孔射线检查不等于整鞋防穿模，静态检查不等于动态连续碰撞。'],
 ['06 · 参数化母体与数据接口','本轮优先：原楦、六条 GH 引用截线、零偏移原例、独立位移场、真实尺寸与残差。改楦使旧纸样失效。人物实时量脚和无源网格依赖的母体尚未完成。']].map(([h,p])=>`<div class="method-card"><h4>${h}</h4><p>${p}</p></div>`).join('')}</div><div class="flow">足型／鞋楦 → 鞋面分片 → 3D 贴楦 → 2D 展开 → 厚度／缝份 → 鞋底与部件 → 放码 → 材质渲染 → 技术数据</div><p class="small">上面保留观察员的六类能力与工序链，具体执行遵循已有 S0–S9。结构 → 动作适配 → 碰撞 → 离线力学蒸馏 → 影视材质是工程接入顺序，不表示本轮已经完成。收集、下载和解析不单独代表制作完成。</p><p><a href="${methodUrl}" target="_blank" rel="noopener">仓库方法论固定版本 ↗</a></p><p class="small">原数据：GPL-3.0。本站的中性检验着色不是作者的最终材质。商业 CAD 目前仅作公开流程老师；没有取得其内核源码，不声称已经整套复制。</p>`;
 $('#build-label').textContent='源码 '+buildId+'\n教师 '+data.sourceCommit;mode('source');new ResizeObserver(resize).observe(view);$('#loading').hidden=true;
 async function sourceCheck(){
  if(!['source','last'].includes(state.mode))return{available:false};
  const editable=state.mode==='last',o=editable?data.baseLast:data.last,tr=transformFor(o,editable?'base':'source'),p=editable&&!sourceVisibleOriginal?kernel.positions:Float64Array.from(o.positions),expected=o.positionsSha256;
  const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',p.buffer)),b=>b.toString(16).padStart(2,'0')).join('');
  const mesh=root.getObjectByName(editable?'EDITABLE_SOURCE_LAST':'NATIVE_SOURCE_OBJECT_32');
  const actual=mesh?.geometry.attributes.position.array;let maxBufferErrorMm=Infinity;
  if(actual?.length===p.length){maxBufferErrorMm=0;for(let i=0;i<p.length;i+=3){const restored=tr.inverse(new T.Vector3(actual[i],actual[i+1],actual[i+2]));maxBufferErrorMm=Math.max(maxBufferErrorMm,Math.hypot(...restored.map((v,k)=>v-p[i+k])));}}
  return {available:true,mode:state.mode,hash,expected,matches:hash===expected&&maxBufferErrorMm<.0001,displayMatchesData:maxBufferErrorMm<.0001,maxBufferErrorMm,zeroDelta:!kernel.changed,comparison:'Actual displayed Float32 vertex buffer transformed back to source coordinates, plus immutable Float64 source hash'};
 }
 function rayHoles(){if(!seamModel||state.mode!=='seam')return{available:false};const h=seamModel.holes[3],objects=[];root.traverse(o=>{if(o.userData.seamLeather)objects.push(o);});scene.updateMatrixWorld(true);const cast=(x,z)=>{const r=new T.Raycaster(new T.Vector3(x,100,z),new T.Vector3(0,-1,0));return r.intersectObjects(objects).length;};return {available:true,holeHits:cast(h.x,h.z),materialHits:cast(h.x,0),description:'Actual displayed layer triangle ray test, not complete seam collision proof'};}
 window.SHOE_R02={ready:true,version:VERSION,buildId,data,kernel,renderer,scene,root,camera,control,render,resize,mode,setCamera,exportState:()=>clone(state),importState:setState,report:()=>({...kernel.report(),mode:state.mode,version:VERSION,buildId,buildCount,renderCount,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometryCount:renderer.info.memory.geometries,textureCount:renderer.info.memory.textures,sourceMeshCount:root.children.length,shoeGate:shoeConstructionGate(state)}),sourceCheck,guards,rayHoles,seamDetail,seamAudit:()=>seamModel?auditSeam(seamModel):null,setDelta:(key,v)=>{const s=clone(state);s.lastDeltaPercent[key]=v;setState(s);},originalHold:(on)=>{sourceVisibleOriginal=on;rebuild(false);}};
 render();
}
init().catch(e=>{$('#loading').hidden=false;$('#loading').textContent='没有完成加载：'+e.message;console.error(e);});
