"""Build only the CC-BY Lee Perry-Smith scan derivatives, not Pixar shaders or painted maps.
Requires Pillow, numpy and scipy. Output is deterministic and hash-recorded.
"""
from pathlib import Path
import hashlib, io, json, urllib.request, zipfile
import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets' / 'hires'
URL = 'https://assets.renderman.pixar.com/Tutorials/photorealistic_head/10100_skin_shading_renderman_21.zip'
ARCHIVE_SHA256 = '15e802b52dc5bdf0fdb0921c5801c41dd3aff7db3f1f0bdfcb9d407f283172c3'
OUT.mkdir(parents=True, exist_ok=True)
if (OUT / 'manifest.json').exists():
    manifest = json.loads((OUT / 'manifest.json').read_text())
    for filename, item in manifest['outputs'].items():
        assert hashlib.sha256((OUT / filename).read_bytes()).hexdigest() == item['sha256']
    print('High-resolution scan derivatives already verified.')
    raise SystemExit(0)

request = urllib.request.Request(URL, headers={'User-Agent': 'SkinQualityLab/1.0'})
with urllib.request.urlopen(request, timeout=180) as response:
    archive_bytes = response.read(200_000_000)
assert hashlib.sha256(archive_bytes).hexdigest() == ARCHIVE_SHA256, 'Upstream archive changed'
archive = zipfile.ZipFile(io.BytesIO(archive_bytes))
color_path = 'Skin_Shading/sourceimages/head_Color.jpg'
height_path = 'Skin_Shading/sourceimages/disp.tif'
color_bytes = archive.read(color_path)
height_bytes = archive.read(height_path)
color = Image.open(io.BytesIO(color_bytes))
assert color.size == (4096, 4096)
(OUT / 'albedo-4k.jpg').write_bytes(color_bytes)
raw = Image.open(io.BytesIO(height_bytes))
assert raw.size == (8192, 8192) and np.asarray(raw).dtype == np.uint16
height = Image.fromarray(np.asarray(raw).astype(np.float32) / 65535).resize((4096, 4096), Image.Resampling.LANCZOS)
height = np.array(height, dtype=np.float32)
# Retain scanned high frequencies. 2.2 pixels is a signal separation scale,
# not a biological pore size. No image enlargement or AI detail synthesis.
micro = height - gaussian_filter(height, 2.2)
dy, dx = np.gradient(micro)
base = np.asarray(Image.open(ROOT / 'assets' / 'normal.jpg').resize((4096, 4096), Image.Resampling.LANCZOS), dtype=np.float32) / 127.5 - 1
z = np.maximum(base[:, :, 2], 0.15)
sx = base[:, :, 0] / z - dx * 48.0
sy = base[:, :, 1] / z + dy * 48.0
sx = np.clip(sx, -2.5, 2.5)
sy = np.clip(sy, -2.5, 2.5)
den = np.sqrt(sx * sx + sy * sy + 1)
normal = np.stack([sx / den, sy / den, 1 / den], axis=-1)
normal = np.rint((normal * 0.5 + 0.5) * 255).clip(0, 255).astype(np.uint8)
Image.fromarray(normal).save(OUT / 'normal-4k.png', compress_level=7)
# Store a 16-bit-derived, explicitly remapped high-pass height for shader
# diagnostics/cavity. The full 8K source is not bundled in the web runtime.
height_preview = np.clip(0.5 + micro * 5.0, 0, 1)
Image.fromarray(np.uint8(np.rint(height_preview * 255))).save(OUT / 'microheight-4k.png', compress_level=7)
manifest = {
    'schema': 'kaopu/skin-reference-build@1',
    'original_asset': 'Infinite, 3D Head Scan by Lee Perry-Smith',
    'license': 'CC BY 3.0 Unported',
    'distribution': 'Pixar RenderMan Photorealistic Head tutorial, Leif Pedersen',
    'archive_url': URL,
    'archive_sha256': ARCHIVE_SHA256,
    'inputs': {
        color_path: {'resolution': [4096,4096], 'sha256': hashlib.sha256(color_bytes).hexdigest()},
        height_path: {'resolution': [8192,8192], 'dtype': 'uint16', 'sha256': hashlib.sha256(height_bytes).hexdigest()},
    },
    'changes': 'Original 4K color unchanged. 4K tangent normal combines the existing scan normal with band-separated derivatives of true 8K 16-bit displacement. No Pixar shaders, manually painted DMFP/specular/fuzz maps or scene geometry redistributed.',
    'calibration': 'Normal slope strength is an artistic lookdev parameter, not metrologically calibrated displacement.',
    'outputs': {}
}
for name in ['albedo-4k.jpg', 'normal-4k.png', 'microheight-4k.png']:
    b = (OUT / name).read_bytes()
    manifest['outputs'][name] = {'bytes': len(b), 'sha256': hashlib.sha256(b).hexdigest()}
(OUT / 'manifest.json').write_text(json.dumps(manifest, indent=2))
(OUT / 'LICENSE-AND-SOURCE.txt').write_text('Infinite, 3D Head Scan by Lee Perry-Smith. CC BY 3.0 Unported.\nOriginal work: www.triplegangers.com / Infinite Realities.\nReference distribution: '+URL+'\nRetrieved from the publicly downloadable Pixar Photorealistic Head tutorial.\nChanges: normal/height derivatives generated by tools/prepare_hires.py; original 4K color retained.\nNo claim of endorsement by Pixar, Infinite Realities, or Artefact VFX.\nLicense: https://creativecommons.org/licenses/by/3.0/\n')
print(json.dumps(manifest, indent=2))
