const {chromium}=require('playwright'),fs=require('fs'),{PNG}=require('pngjs');
const out=process.env.GITHUB_WORKSPACE+'/skin-quality-lab/r01/qa';fs.mkdirSync(out,{recursive:true});
const report={commit:process.env.LAB_COMMIT,desktop:{viewport:[1440,1040]},mobile:{viewport:[390,844],physicalDevice:false},screenshots:[],checks:[],errors:[],publicAttempts:[]};let browser,page,network=[];
function diff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let sum=0,n=0;for(let i=0;i<a.data.length;i+=4){for(let c=0;c<3;c++){sum+=Math.abs(a.data[i+c]-b.data[i+c]);n++;}}return sum/n}
(async()=>{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
page.on('requestfailed',r=>network.push({url:r.url(),failure:r.failure()}));page.on('response',r=>{if(r.status()>=400)network.push({url:r.url(),status:r.status()})});
const snap=async name=>{await page.evaluate(()=>window.__SKIN_LAB__.render());await page.waitForTimeout(400);await page.screenshot({path:out+'/'+name+'.png'});report.screenshots.push(name+'.png');return page.locator('#viewport canvas').screenshot()};
await page.goto('http://127.0.0.1:8793/index.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,null,{timeout:90000});await page.waitForTimeout(1200);
report.local=await page.evaluate(()=>({state:window.__SKIN_LAB__.state,camera:window.__SKIN_LAB__.camera(),geometry:window.__SKIN_LAB__.geometryInfo()}));
await snap('01-portrait');await page.click('[data-camera="front"]');await snap('02-front');await page.click('[data-camera="cheek"]');const natural=await snap('03-cheek-natural');
await page.evaluate(()=>window.__SKIN_LAB__.set({detail:0,pores:0,oil:0,sss:0}));const flat=await snap('04-cheek-no-detail');report.checks.push({name:'detail-changes-canvas',meanAbsolutePixelDifference:diff(natural,flat),pass:diff(natural,flat)>.15});
await page.click('#reset');await page.click('[data-camera="cheek"]');await page.click('[data-preset="oily"]');const oily=await snap('05-cheek-oily');report.checks.push({name:'oil-changes-canvas',meanAbsolutePixelDifference:diff(natural,oily),pass:diff(natural,oily)>.15});
await page.click('#reset');await page.click('[data-camera="ear"]');await page.selectOption('#lightPreset','back');await snap('06-ear-backlight');await page.click('#reset');await page.selectOption('#lightPreset','raking');await snap('07-raking');await page.selectOption('#layer','specular');await snap('08-specular');await page.selectOption('#layer','normal');await snap('09-normal');
await page.click('#reset');await page.click('#save');await page.evaluate(()=>window.__SKIN_LAB__.set({roughness:.67}));await page.click('#restore');report.checks.push({name:'save-restore',pass:await page.evaluate(()=>Math.abs(window.__SKIN_LAB__.values.roughness-window.__SKIN_LAB__.defaults.roughness)<1e-6)});
// One public candidate at a time, with response, page-state and actual browser evidence.
for(const host of ['rawcdn.githack.com','raw.githack.com']){
 const url='https://'+host+'/haihao0307/Humanoid-Rig-Lab-Next/'+process.env.LAB_COMMIT+'/skin-quality-lab/r01/index.html';let attempt={url};report.publicAttempts.push(attempt);network=[];
 try{
  const res=await page.goto(url,{waitUntil:'networkidle',timeout:90000});attempt.status=res.status();attempt.headers=await res.allHeaders();
  await page.waitForTimeout(2500);attempt.initial=await page.evaluate(()=>({title:document.title,url:location.href,text:document.body.innerText.slice(0,5000),ready:window.__SKIN_LAB__?.state,scriptCount:document.scripts.length}));
  await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,null,{timeout:60000});await snap('10-public-desktop');report.public=await page.evaluate(()=>({url:location.href,title:document.title,state:window.__SKIN_LAB__.state}));report.publicUrl=url;
  await page.click('[data-preset="dry"]');report.checks.push({name:'public-preset',pass:await page.evaluate(()=>window.__SKIN_LAB__.values.roughness===.66)});
  await page.click('#reset');const before=await page.locator('#viewport canvas').screenshot();await page.locator('#roughness').fill('0.70');await page.locator('#roughness').dispatchEvent('input');await page.evaluate(()=>window.__SKIN_LAB__.render());const after=await page.locator('#viewport canvas').screenshot();report.checks.push({name:'public-slider-changes-pixels',difference:diff(before,after),pass:diff(before,after)>.15});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{window.__SKIN_LAB__.set(window.__SKIN_LAB__.defaults);window.__SKIN_LAB__.setCamera('portrait')});await page.waitForTimeout(900);await snap('11-public-mobile-viewport');await page.click('#mobileToggle');await snap('12-mobile-parameters');report.mobile.panelVisible=await page.locator('.side').isVisible();report.mobile.horizontalOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);attempt.success=true;break;
 }catch(e){attempt.error=String(e);attempt.network=network;try{attempt.end=await page.evaluate(()=>({text:document.body.innerText.slice(0,5000),state:window.__SKIN_LAB__?.state}));await page.screenshot({path:out+'/public-failure-'+host+'.png'});}catch{} }
}
report.finishedAt=new Date().toISOString();report.pass=report.errors.length===0&&report.checks.every(x=>x.pass)&&!!report.public?.state.ready&&report.mobile.panelVisible&&!report.mobile.horizontalOverflow;fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();if(!report.pass)process.exitCode=1;
})().catch(async e=>{report.fatal=String(e);try{await page.screenshot({path:out+'/fatal.png'});report.pageState=await page.evaluate(()=>({text:document.body.innerText,state:window.__SKIN_LAB__?.state}));}catch{}fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.error(e);await browser?.close();process.exitCode=1});
