const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const root=path.resolve(__dirname,'../../..'),out=process.env.EVIDENCE_DIR||'/tmp/et05-evidence';fs.mkdirSync(out,{recursive:true});
const report={version:'ET05',sourceCommit:process.env.GITHUB_SHA,publicCommit:process.env.PUBLIC_COMMIT||null,localServer:!process.env.PUBLIC_URL,networkInterception:false,realMobileDevice:false,errors:[],consoleErrors:[],failedRequests:[],checks:{}};let browser,page,server;
const save=()=>fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));
const difference=(a,b)=>{a=PNG.sync.read(a);b=PNG.sync.read(b);assert.equal(a.width,b.width);let s=0;for(let i=0;i<a.data.length;i+=4)for(let c=0;c<3;c++)s+=Math.abs(a.data[i+c]-b.data[i+c]);return s/(a.width*a.height*3);};
(async()=>{
 let url=process.env.PUBLIC_URL;
 if(!url){server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');const s=fs.createReadStream(f);s.on('error',()=>{if(!res.headersSent)res.writeHead(404);res.end();});s.pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';}
 report.url=url;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.setDefaultTimeout(60000);
 await page.addInitScript(()=>{window.__EYE_QA_FREEZE__=true;});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:90000});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,{},{timeout:180000});
 assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/5.0.0');assert.equal(await page.evaluate(()=>__EYES__.version),'eyes/5.0.0');assert.equal(await page.locator('canvas').count(),1);
 await page.evaluate(()=>{__TALKINGHEAD__.set({headMotion:false,paused:true,manualYaw:0,manualPitch:0});__EYES__.set({autoBlink:false,autoPupil:false,pupilMM:3.4,manualBlink:0,squint:0});__EYES__.setMode('camera');__EYES__.step(0,true);});
 const sourceGeometry=await page.evaluate(()=>__EYES__.sourceGeometry()),skinValues=await page.evaluate(()=>({...__SKIN_LAB__.values}));
 async function canvas(){await page.evaluate(()=>__SKIN_LAB__.render());return Buffer.from((await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL('image/png'))).split(',')[1],'base64');}
 async function shot(name){const bytes=await canvas();fs.writeFileSync(out+'/'+name+'-canvas.png',bytes);await page.screenshot({path:out+'/'+name+'.png'});return bytes;}
 await shot('01-portrait');await page.click('[data-camera="eyes"]');await page.evaluate(()=>__EYES__.step(0,true));const eyes=await shot('02-eyes');report.checks.neutralStructure=await page.evaluate(()=>__EYES__.info().structure);save();
 assert(report.checks.neutralStructure.every(s=>s.realJoinedMargin&&s.rimJoinErrorMM<.00001&&s.innerPenetratingVertices===0&&s.upperRimThicknessMM[0]>.20),'Upper lid margin or inner contact failed');
 await page.click('[data-camera="upperlid"]');await page.evaluate(()=>__EYES__.step(0,true));await shot('03-upper-lid-oblique');
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>{__EYES__.set({manualBlink:.5});__EYES__.step(0,true);});await shot('04-half-closed');await page.evaluate(()=>{__EYES__.set({manualBlink:1});__EYES__.step(0,true);});await shot('05-closed');
 report.checks.closedStructure=await page.evaluate(()=>__EYES__.info().structure);save();
 const sweep=await page.evaluate(()=>{let results=[];__EYES__.setTarget([.01,.069,.8]);for(let b of [0,.25,.5,.75,1])for(let a of [[-.22,0],[.22,0],[0,-.1],[0,.1],[0,0]]){__TALKINGHEAD__.set({manualYaw:a[0],manualPitch:a[1]});__EYES__.set({manualBlink:b});__EYES__.step(0,true);const e=__EYES__.info();results.push({blink:b,head:a,lock:e.lockErrorDegrees,contact:e.contact,structure:e.structure,target:e.target,clamped:e.clamped});}return results;});
 report.checks.poseSweep25=sweep;save();assert(sweep.every(s=>s.lock.every(x=>x<.005)&&!s.clamped),'Head motion gaze regression');assert(sweep.every(s=>s.structure.every(x=>x.innerPenetratingVertices===0&&x.rimJoinErrorMM<.00001)),'Inner lid/contact join broke in motion');assert(sweep.every(s=>s.contact.every(x=>x.penetratingTestVertices===0)),'Inherited sampled outer contact violation');
 await page.click('[data-camera="portrait"]');await page.evaluate(()=>{__TALKINGHEAD__.set({manualYaw:.25,manualPitch:0});__EYES__.set({manualBlink:0});__EYES__.step(0,true);});await shot('06-head-turn-locked');
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>{__TALKINGHEAD__.set({paused:false,manualYaw:0,manualPitch:0});__EYES__.setMode('camera');__EYES__.set({manualBlink:-1});__TALKINGHEAD__.blink('left');__EYES__.step(.05);__EYES__.step(.05);__EYES__.step(.025);});const wink=await page.evaluate(()=>__EYES__.info());assert(wink.blinkLeft>.90&&wink.blinkRight<.05);const winkPixels=await shot('07-left-wink');report.checks.nativeWink={left:wink.blinkLeft,right:wink.blinkRight,imageDifference:difference(eyes,winkPixels)};
 await page.evaluate(()=>{__EYES__.set({manualBlink:.37});__TALKINGHEAD__.blink('double');__EYES__.set({manualBlink:.37});for(let i=0;i<4;i++)__EYES__.step(.05);});assert.equal(await page.evaluate(()=>__EYES__.info().blinkLeft),.37);report.checks.manualPriority=true;
 await page.evaluate(()=>{__TALKINGHEAD__.set({paused:true,manualYaw:.1});__EYES__.setTarget([.01,.069,.8]);});await page.click('#save');await page.evaluate(()=>__TALKINGHEAD__.set({manualYaw:-.1}));await page.click('#restore');assert.equal(await page.evaluate(()=>__EYES__.snapshot().behavior.manualYaw),.1);report.checks.recipeRestore=true;
 for(let i=0;i<6;i++)await page.evaluate(()=>{__TALKINGHEAD__.set({enabled:false});__EYES__.step(0,true);__TALKINGHEAD__.set({enabled:true});__EYES__.step(0,true);});assert.deepEqual(await page.evaluate(()=>__EYES__.sourceGeometry()),sourceGeometry);assert.equal(await page.locator('canvas').count(),1);report.checks.driverSwitch6={sameHead:true,oneCanvas:true};
 await page.evaluate(()=>{__TALKINGHEAD__.set({manualYaw:0,manualPitch:0,paused:true});__EYES__.setMode('camera');__EYES__.set({manualBlink:0});__EYES__.step(0,true);});await page.click('[data-method="enhanced"]');const enhanced=await canvas();await page.selectOption('#transferMode','base');report.checks.skinImageDifference=difference(enhanced,await canvas());assert(report.checks.skinImageDifference>.01);await page.selectOption('#transferMode','full');await page.click('[data-method="emily"]');assert.deepEqual(await page.evaluate(()=>({...__SKIN_LAB__.values})),skinValues);
 await page.setViewportSize({width:390,height:844});await page.click('[data-camera="portrait"]');await page.evaluate(()=>__EYES__.step(0,true));await shot('08-mobile');await page.click('#mobileToggle');assert(await page.locator('#thDouble').isVisible());await page.click('#thDouble');await page.evaluate(()=>{__EYES__.step(.05);__EYES__.step(.05);});await shot('09-mobile-controls');await page.click('#mobileToggle');report.checks.mobileViewportOnly=true;
 const before=await page.evaluate(()=>__TALKINGHEAD__.info().upstreamSteps);await page.evaluate(()=>{__TALKINGHEAD__.set({paused:false});window.__EYE_QA_FREEZE__=false;});await page.waitForTimeout(900);report.checks.hostLoopAdvances=await page.evaluate(()=>__TALKINGHEAD__.info().upstreamSteps)>before;assert(report.checks.hostLoopAdvances);
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.failedRequests,[]);report.passed=true;save();console.log('ET05_QA_PASS',JSON.stringify({url,structure:report.checks.neutralStructure,checks:Object.keys(report.checks)}));
})().catch(async e=>{report.passed=false;report.failure=e.stack;save();console.error(e);if(page)await page.screenshot({path:out+'/failure.png',timeout:20000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
