(()=>{
'use strict';
const E=window.__BIRD_R010_EXECUTION,C=window.__BIRD_R007_CONTRACT,K=window.__BIRD_R009_CONTRACT;
if(!E||!C||!K)throw new Error('R0.10 缺少合同链');
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const active=E.interface.output.activeChannels,locked=E.interface.output.lockedReadOnlyChannels,controls=E.controlGroups.map(x=>x.id),anchors=E.execution.anchorFramesZeroBased,S=C.series,env=E.sourceEnvelopes;
const defaults={phase01:0,interpolation:E.execution.defaultInterpolation,rootDrive:1,elbowFold:1,bodyCoupling:1,asymmetryResidual:1,periodicClosure:0};
let lastValid={...defaults};
const mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
const centers={};for(const n of active)centers[n]=mean(S[n]);
function interpWeight(t,mode){return mode==='linear'?t:t*t*(3-2*t)}
function sampleAnchors(a,phase,mode){const x=clamp(phase,0,1-Number.EPSILON)*49;if(x<=anchors[0])return a[anchors[0]];if(x>=anchors.at(-1))return a[anchors.at(-1)];let k=0;while(x>anchors[k+1])k++;const i=anchors[k],j=anchors[k+1],t=interpWeight((x-i)/(j-i),mode);return a[i]+(a[j]-a[i])*t}
function tailCorrection(a,phase,gain){if(gain<=0)return 0;const x=phase*49,s=E.execution.periodicCorrectionStartFrameZeroBased,e=49;if(x<s)return 0;const L=e-s,u=(x-s)/L,D=a[0]-a[49],d0=a[1]-a[0],c48=a[0]-a[48]-d0,t=(e-1-s)/L,A=(c48-D*t*t*t)/(t*t-t*t*t),B=D-A;return gain*(A*u*u+B*u*u*u)}
function sanitize(input={}){const clipped=[],fallback=[],lockedWrites=[],out={};let p=Number(input.phase01);if(!Number.isFinite(p)){fallback.push('phase01');p=lastValid.phase01??0}else p=((p%1)+1)%1;out.phase01=p;const mode=E.execution.allowedInterpolation.includes(input.interpolation)?input.interpolation:(E.execution.allowedInterpolation.includes(lastValid.interpolation)?lastValid.interpolation:defaults.interpolation);if(mode!==input.interpolation&&input.interpolation!==undefined)fallback.push('interpolation');out.interpolation=mode;for(const n of controls){let v=Number(input[n]);if(!Number.isFinite(v)){fallback.push(n);v=Number(lastValid[n]);if(!Number.isFinite(v))v=defaults[n]}const q=clamp(v,0,1);if(q!==v)clipped.push(n);out[n]=q}for(const n of locked)if(Object.prototype.hasOwnProperty.call(input,n))lockedWrites.push(n);lastValid={...out};return{input:out,clipped,fallback,lockedWrites}}
function pairValues(left,right,phase,mode,meanGain,residualGain,closure){const l=sampleAnchors(S[left],phase,mode),r=sampleAnchors(S[right],phase,mode),m=(l+r)/2,res=(l-r)/2,center=(centers[left]+centers[right])/2;let om=center+(m-center)*meanGain,or=res*residualGain;om+=(tailCorrection(S[left],phase,closure)+tailCorrection(S[right],phase,closure))/2;or+=(tailCorrection(S[left],phase,closure)-tailCorrection(S[right],phase,closure))/2*residualGain;return[om+or,om-or]}
function evaluatePacket(raw={}){try{const s=sanitize(raw),q=s.input,v={};[v.leftRootElevationDeg,v.rightRootElevationDeg]=pairValues('leftRootElevationDeg','rightRootElevationDeg',q.phase01,q.interpolation,q.rootDrive,q.asymmetryResidual,q.periodicClosure);for(const [l,r] of [['leftMidElevationDeg','rightMidElevationDeg'],['leftOuterElevationDeg','rightOuterElevationDeg'],['leftElbowFoldDeg','rightElbowFoldDeg']])[v[l],v[r]]=pairValues(l,r,q.phase01,q.interpolation,q.elbowFold,q.asymmetryResidual,q.periodicClosure);for(const [n,g] of [['averageWingtipY',q.rootDrive],['tipSpan',q.elbowFold],['bodyY',q.bodyCoupling]])v[n]=centers[n]+(sampleAnchors(S[n],q.phase01,q.interpolation)-centers[n])*g+tailCorrection(S[n],q.phase01,q.periodicClosure);for(const n of locked)v[n]=sampleAnchors(S[n],q.phase01,q.interpolation);const pre={...v};let postClampViolations=0;for(const n of [...active,...locked]){const e=env[n];if(!Number.isFinite(v[n]))throw new Error('non-finite output '+n);v[n]=clamp(v[n],e.min,e.max);if(v[n]<e.min-1e-9||v[n]>e.max+1e-9)postClampViolations++}if(postClampViolations)throw new Error('post clamp violation');const frame=Math.round(q.phase01*49)%50;return{ok:true,version:'R0.10',phase01:q.phase01,frame,interpolation:q.interpolation,controls:Object.fromEntries(controls.map(n=>[n,q[n]])),values:v,diagnostics:{clippedFields:s.clipped,fallbackFields:s.fallback,lockedWriteRejects:s.lockedWrites,postClampViolations,preClamp:pre,fallbackReason:s.fallback.length?'last-valid/default':'none'}}}catch(error){return{ok:false,version:'R0.10',error:error.message,diagnostics:{fallbackReason:'fail-closed'}}}}
function evaluateAtPhase(phase01,options={}){return evaluatePacket({...options,phase01})}
function setControls(x={}){return evaluatePacket({...lastValid,...x})}
function getState(){return{lastValid:{...lastValid},controls:Object.fromEntries(controls.map(n=>[n,lastValid[n]])),interpolation:lastValid.interpolation}}
function style(){const s=document.createElement('style');s.textContent=`.r010-card{border:1px solid #28505f;background:#091820;border-radius:10px;padding:10px;margin:8px 0}.r010-controls label{display:grid;grid-template-columns:1fr auto;font-size:10px;color:#9db4bf;margin:7px 0}.r010-controls input{grid-column:1/-1;width:100%;accent-color:#56cbe8}.r010-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.r010-grid>div{border:1px solid #244554;background:#0a1821;border-radius:8px;padding:8px}.r010-grid span{display:block;font-size:9px;color:#8199a5}.r010-grid b{display:block;font-size:12px;margin-top:3px;color:#edf7fa}.r010-status{font-size:10px;margin-top:7px;color:#75d3aa}.r010-buttons{display:grid;grid-template-columns:1fr 1fr;gap:6px}.r010-table{display:grid;gap:4px}.r010-row{display:grid;grid-template-columns:1fr auto auto;gap:7px;padding:6px;border:1px solid #223f4c;border-radius:7px;font-size:9px}.r010-row span{color:#91aab5}.r010-row b{color:#eaf5f8}.r010-row i{font-style:normal;color:#72cce5}.r010-bad{color:#ff9b91!important}.r010-good{color:#75d3aa!important}`;document.head.appendChild(s)}
function inject(){document.title='Bird Mother｜Seagull A 通道执行合同台 R0.10';const t=document.querySelector('.title-block b'),sm=document.querySelector('.title-block small'),pill=document.querySelector('header .pill');if(t)t.textContent='Bird Mother｜Seagull A 通道执行合同台 R0.10';if(sm)sm.textContent='显式输入/输出｜来源包络｜异常回退｜锁定写入拒绝｜fail-closed';if(pill)pill.textContent='BOUNDED CHANNEL EXECUTOR';const left=$('controls'),right=$('analysis'),l=document.createElement('section');l.innerHTML=`<h3>R0.10 执行输入</h3><div class="r010-card r010-controls" id="r010Controls">${controls.map(n=>`<label>${E.controlGroups.find(x=>x.id===n).label}<strong id="r010-${n}-v">${Math.round(defaults[n]*100)}%</strong><input id="r010-${n}" type="range" min="0" max="100" value="${Math.round(defaults[n]*100)}"></label>`).join('')}<div class="r010-buttons"><button id="r010BadInput">注入异常输入</button><button id="r010LockedWrite">尝试写入锁定腕部</button></div><div id="r010Status" class="r010-status">等待执行</div></div>`;left.prepend(l);const r=document.createElement('section');r.innerHTML=`<h3>R0.10 输出包</h3><div class="r010-grid"><div><span>活动通道</span><b>${active.length}</b></div><div><span>只读通道</span><b>${locked.length}</b></div><div><span>裁剪字段</span><b id="r010Clipped">0</b></div><div><span>回退字段</span><b id="r010Fallback">0</b></div><div><span>锁定写入拒绝</span><b id="r010Locked">0</b></div><div><span>后置越界</span><b id="r010Violations">0</b></div></div><h3>当前通道输出</h3><div class="r010-table" id="r010Table"></div>`;right.prepend(r);for(const n of [...active,...locked]){const d=document.createElement('div');d.className='r010-row';d.dataset.channel=n;d.innerHTML=`<span>${n}</span><b>—</b><i>${locked.includes(n)?'只读':'活动'}</i>`;$('r010Table').appendChild(d)}const foot=document.querySelector('footer');if(foot&&!foot.textContent.includes('channelExecutor=true')){const x=document.createElement('span');x.textContent='channelExecutor=true';foot.appendChild(x)}}
style();inject();let bad=null,lockedAttempt=false;for(const n of controls)$('r010-'+n).addEventListener('input',e=>{const v=Number(e.target.value)/100;lastValid[n]=v;$('r010-'+n+'-v').textContent=Math.round(v*100)+'%'});$('r010BadInput').addEventListener('click',()=>{bad={phase01:NaN,rootDrive:Infinity,elbowFold:-3,bodyCoupling:4,interpolation:'bad-mode'}});$('r010LockedWrite').addEventListener('click',()=>{lockedAttempt=true});
function render(){const phase=(window.__BIRD_R007_API?.frame||0)/49,input={...lastValid,phase01:phase};if(bad){Object.assign(input,bad);bad=null}if(lockedAttempt){input.leftWristFoldDeg=99;lockedAttempt=false}const p=evaluatePacket(input);if(p.ok){for(const n of [...active,...locked]){const row=document.querySelector(`.r010-row[data-channel="${n}"]`);if(row)row.querySelector('b').textContent=p.values[n].toFixed(n.endsWith('Deg')?2:4)}$('r010Clipped').textContent=p.diagnostics.clippedFields.length;$('r010Fallback').textContent=p.diagnostics.fallbackFields.length;$('r010Locked').textContent=p.diagnostics.lockedWriteRejects.length;$('r010Violations').textContent=p.diagnostics.postClampViolations;$('r010Status').textContent=`R0.10 执行成功｜F${String(p.frame+1).padStart(2,'0')}｜${p.interpolation}`;$('r010Status').className='r010-status r010-good';window.__BIRD_R010_QA={ready:true,version:'R0.10',activeChannelCount:active.length,lockedChannelCount:locked.length,controlGroupCount:E.controlGroups.length,postClampViolations:p.diagnostics.postClampViolations,externalRuntimeDependencies:0,controllerAffectsSourceMesh:false,lastPacket:p};document.body.dataset.r010Ready='true'}else{$('r010Status').textContent='R0.10 fail-closed：'+p.error;$('r010Status').className='r010-status r010-bad';window.__BIRD_R010_QA={ready:false,error:p.error}}requestAnimationFrame(render)}
window.__BIRD_R010_API={evaluatePacket,evaluateAtPhase,setControls,getState,sourceEnvelopes:env,activeChannels:active,lockedChannels:locked};Object.assign(window.__BIRD_QA,{channelExecutorReady:true,channelExecutorVersion:'R0.10'});render();
})();
