import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {measureGNM,measurementComparison,GNM_FRONT_CAMERA} from './GnmMeasurements.mjs';
const $=id=>document.getElementById(id),started=performance.now();let meta,recipe,current,baseline,mesh,markers,busy=false,pending=false,compared=null,firstFrame=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#182936');
const camera=new THREE.PerspectiveCamera(GNM_FRONT_CAMERA.fov,innerWidth/innerHeight,.001,5);camera.position.fromArray(GNM_FRONT_CAMERA.position);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#182936');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.body.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.fromArray(GNM_FRONT_CAMERA.target);controls.enabled=false;controls.enableDamping=true;controls.minDistance=.25;controls.maxDistance=2;
scene.add(new THREE.HemisphereLight(0xd9eaf4,0x54535c,1.6));const key=new THREE.DirectionalLight(0xffeddb,3.0);key.position.set(-.55,.70,.8);scene.add(key);const fill=new THREE.DirectionalLight(0xbad8ff,1.1);fill.position.set(.5,.5,.4);scene.add(fill);const rim=new THREE.DirectionalLight(0xd6e6ff,2);rim.position.set(.4,.65,-.3);scene.add(rim);
function render(){requestAnimationFrame(render);controls.update();renderer.render(scene,camera);}render();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function loading(percent,stage,detail=''){$('progress').value=percent;$('percent').textContent=Math.round(percent)+'%';$('loadStage').textContent=stage;$('loadDetail').textContent=detail;$('elapsed').textContent='已用 '+Math.floor((performance.now()-started)/1000)+' 秒';}
function fail(error){$('loadError').hidden=false;$('loadError').textContent=error.message;$('retry').hidden=false;window.GNMFailure=error.message;}
async function api(url,data){const response=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||response.status);return result;}
async function readMetadata(){const response=await fetch('/api/meta'),size=Number(response.headers.get('Content-Length'))||0;const reader=response.body.getReader(),chunks=[];let received=0;for(;;){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;loading(85,'读取真实网格、统计定义和原生分组',(received/1e6).toFixed(1)+' MB 已解码'+(size?' · 压缩传输 '+(size/1e6).toFixed(2)+' MB':''));}const bytes=new Uint8Array(received);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return JSON.parse(new TextDecoder().decode(bytes));}
function empty(){return {schema:'human/gnm-head-session@1',modelSHA256:meta.modelSHA256,identity:Array(meta.identityDim).fill(0),expression:Array(meta.expressionDim).fill(0),rotations:meta.jointNames.map(()=>[0,0,0]),translation:[0,0,0],semantic:{}};}
function sceneMesh(data){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(meta.colours,3));geometry.setIndex(meta.triangles);for(const group of meta.drawGroups)geometry.addGroup(group.start,group.count,group.materialIndex);geometry.computeVertexNormals();geometry.computeBoundingSphere();
 const materials=meta.componentNames.map((name,index)=>index===6?new THREE.MeshPhysicalMaterial({color:'#d4e5de',transparent:true,opacity:.08,roughness:.05,depthWrite:false,side:THREE.DoubleSide}):new THREE.MeshStandardMaterial({vertexColors:true,roughness:name.includes('eye')?.28:.62,side:THREE.DoubleSide}));mesh=new THREE.Mesh(geometry,materials);scene.add(mesh);
 markers=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:'#83ffe0',size:.0022,depthTest:false}));markers.renderOrder=20;markers.visible=false;scene.add(markers);
}
function updateMesh(data){current=data;mesh.geometry.attributes.position.array.set(data.positions);mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingSphere();markers.geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.landmarks.filter(p=>p.point).flatMap(p=>p.point),3));markers.geometry.computeBoundingSphere();displayRows();displayRegion();$('evaluationStatus').textContent='已更新真实 GNM 网格 · '+data.evaluationMS.toFixed(1)+' ms · 拓扑保持不变';}
function displayRows(){const rows=measurementComparison(measureGNM(current.measurementLandmarks),baseline);$('measureRows').innerHTML=rows.map(r=>`<tr title="${r.id}"><td>${r.label}</td><td>${r.actual===null?'未知':r.actual.toFixed(1)}</td><td>${r.baseline===null?'—':r.baseline.toFixed(1)}</td><td>${r.change===null?'—':(r.change>0?'+':'')+r.change.toFixed(1)+'%'}</td></tr>`).join('');
 const requests=recipe.semantic;$('requests').textContent=Object.keys(requests).length?meta.semanticDefinitions.filter(d=>requests[d.id]).map(d=>d.label+' '+(requests[d.id]>0?'+':'')+requests[d.id]+'%').join(' · '):'当前无语义比例请求';const report=current.semanticReport;$('semanticResult').textContent=report.actualPercent?Object.keys(requests).filter(id=>requests[id]).map(id=>`${meta.semanticDefinitions.find(d=>d.id===id).label}：请求 ${requests[id]}%，实际 ${report.actualPercent[id].toFixed(1)}%`).join(' · ')+(report.bounded?' · 已碰到统计系数边界':''):'当前显示 GNM 实测；照片拟合保持暂停。';}
async function regenerate(){if(busy){pending=true;return;}busy=true;do{pending=false;const snapshot=structuredClone(recipe);$('evaluationStatus').textContent='正在生成 GNM 顶点…';try{const data=await api('/api/mesh',snapshot);updateMesh(data);}catch(e){$('evaluationStatus').textContent=e.message;}}while(pending);busy=false;}
function leaveCompare(){compared=null;$('compare').textContent='对比中性基准';}
function semanticSelection(){const value=recipe.semantic[$('semanticParameter').value]||0;$('semanticNumber').value=$('semanticSlider').value=value;}
function applySemantic(){leaveCompare();const id=$('semanticParameter').value,value=Number($('semanticNumber').value);if(!Number.isFinite(value)||Math.abs(value)>15){$('evaluationStatus').textContent='比例请求需在 ±15% 内';return;}recipe.semantic[id]=value;if(!value)delete recipe.semantic[id];semanticSelection();regenerate();}
function coefficientNames(){return meta[$('coefficientKind').value==='identity'?'identityNames':'expressionNames'];}
function coefficientGroup(){const prefixes=[...new Set(coefficientNames().map(name=>name.replace(/_\d+$/,'')))];$('coefficientGroup').innerHTML=prefixes.map(id=>`<option>${id}</option>`).join('');coefficientList();}
function coefficientList(){$('coefficient').innerHTML=coefficientNames().map((name,index)=>({name,index})).filter(row=>row.name.replace(/_\d+$/,'')===$('coefficientGroup').value).map(row=>`<option value="${row.index}">${row.name}</option>`).join('');coefficientSelection();}
function coefficientSelection(){const kind=$('coefficientKind').value,index=Number($('coefficient').value);$('coefficientNumber').value=$('coefficientSlider').value=recipe[kind][index];}
function displayRegion(){const selected=$('region').value,colours=mesh.geometry.attributes.color;if(selected==='none'){colours.array.set(meta.colours);$('regionStats').textContent='表皮、眼、牙龈牙齿和舌均来自同一个 GNM 模型。';}else{const weights=meta.groupWeights[Number(selected)];let sum=0,count=0,peak=0;const colour=new THREE.Color();for(let i=0;i<weights.length;i++){const w=weights[i];sum+=w;peak=Math.max(peak,w);if(w>.01)count++;colour.setHSL((1-w)*.64,.8,.18+.38*Math.sqrt(w));colours.setXYZ(i,colour.r,colour.g,colour.b);}$('regionStats').textContent=`覆盖 >1%：${count.toLocaleString()} 点 · 峰值 ${peak.toFixed(3)} · 均值 ${(sum/weights.length).toFixed(4)}`;}colours.needsUpdate=true;visibility();}
function visibility(){for(let i=0;i<mesh.material.length;i++){const name=meta.componentNames[i];mesh.material[i].visible=i===6?$('showEyes').checked:name==='skin'?$('showSkin').checked:name.includes('eye')?$('showEyes').checked:name==='tongue'?$('showTongue').checked:$('showTeeth').checked;mesh.material[i].wireframe=$('wireframe').checked;}markers.visible=$('landmarks').checked;}
function front(){$('frontLock').checked=true;controls.enabled=false;camera.position.fromArray(GNM_FRONT_CAMERA.position);controls.target.fromArray(GNM_FRONT_CAMERA.target);controls.update();$('footer').textContent='固定正面 · 画面右＝人物左 · GNM 原生生成';}
function side(sign){$('frontLock').checked=false;controls.enabled=true;camera.position.set(sign*.70,.30,.70);controls.target.fromArray(GNM_FRONT_CAMERA.target);controls.update();$('footer').textContent='自由观察 · 拖动旋转 / 滚轮缩放 · GNM 原生生成';}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bindUI(){
 $('vertexCount').textContent=meta.vertices.toLocaleString();$('dimensions').textContent=meta.identityDim+' / '+meta.expressionDim;$('groupCount').textContent=meta.groupNames.length;$('landmarkCount').textContent=meta.landmarkNames.length+' / 82';$('semanticParameter').innerHTML=meta.semanticDefinitions.map(d=>`<option value="${d.id}">${d.label}</option>`).join('');$('joint').innerHTML=meta.jointNames.map((name,index)=>`<option value="${index}">${name}</option>`).join('');$('region').innerHTML+='<optgroup label="GNM 原生权重">'+meta.groupNames.map((name,index)=>`<option value="${index}">${name}</option>`).join('')+'</optgroup>';
 $('allMasks').innerHTML='<table><thead><tr><th>原生分组</th><th>>1% 点数</th><th>峰值</th></tr></thead><tbody>'+meta.groupNames.map((name,i)=>`<tr><td>${name}</td><td>${meta.groupWeights[i].filter(x=>x>.01).length.toLocaleString()}</td><td>${Math.max(...meta.groupWeights[i]).toFixed(3)}</td></tr>`).join('')+'</tbody></table>';
 $('semanticParameter').onchange=semanticSelection;$('semanticApply').onclick=applySemantic;$('semanticSlider').oninput=()=>{$('semanticNumber').value=$('semanticSlider').value;};$('semanticSlider').onchange=applySemantic;
 $('semanticDemo').onclick=()=>{leaveCompare();recipe=empty();recipe.semantic={mouthWidth:8,jawWidth:-7,noseWidth:-5};semanticSelection();coefficientSelection();regenerate();};
 $('identityDemo').onclick=()=>{leaveCompare();recipe=empty();recipe.identity[0]=.8;recipe.identity[1]=-.6;recipe.identity[2]=.5;semanticSelection();coefficientSelection();regenerate();};
 $('expressionDemo').onclick=()=>{leaveCompare();recipe.expression.fill(0);recipe.expression[200]=1;coefficientSelection();regenerate();};
 $('coefficientKind').onchange=coefficientGroup;$('coefficientGroup').onchange=coefficientList;$('coefficient').onchange=coefficientSelection;$('coefficientSlider').oninput=()=>{$('coefficientNumber').value=$('coefficientSlider').value;};$('coefficientSlider').onchange=()=>{$('coefficientApply').click();};$('coefficientApply').onclick=()=>{leaveCompare();const value=Number($('coefficientNumber').value);if(!Number.isFinite(value)||Math.abs(value)>3){$('evaluationStatus').textContent='统计系数范围为 -3 至 3';return;}recipe[$('coefficientKind').value][Number($('coefficient').value)]=value;if($('coefficientKind').value==='identity')recipe.semantic={};coefficientSelection();regenerate();};
 $('joint').onchange=()=>{const r=recipe.rotations[Number($('joint').value)];$('yaw').value=r[1]*180/Math.PI;$('pitch').value=r[0]*180/Math.PI;};$('poseApply').onclick=()=>{leaveCompare();recipe.rotations[Number($('joint').value)]=[Number($('pitch').value)*Math.PI/180,Number($('yaw').value)*Math.PI/180,0];regenerate();};
 $('region').onchange=displayRegion;for(const id of ['wireframe','landmarks','showSkin','showEyes','showTeeth','showTongue'])$(id).onchange=visibility;
 $('front').onclick=front;$('left').onclick=()=>side(1);$('right').onclick=()=>side(-1);$('frontLock').onchange=()=>{$('frontLock').checked?front():side(1);};
 $('reset').onclick=()=>{leaveCompare();recipe=empty();semanticSelection();coefficientSelection();$('joint').onchange();regenerate();};$('compare').onclick=()=>{if(compared){recipe=compared;leaveCompare();}else{compared=structuredClone(recipe);recipe=empty();$('compare').textContent='恢复调整';}semanticSelection();coefficientSelection();regenerate();};
 $('save').onclick=async()=>{try{await api('/api/save',recipe);$('evaluationStatus').textContent='已保存 GNM 系数、比例请求和来源；未保存顶点数组。';}catch(e){$('evaluationStatus').textContent=e.message;}};
 $('exportRecipe').onclick=()=>download(recipe,'GNM-head-recipe.json');$('export').onclick=()=>download({schema:'human/gnm-face-report@1',recipe,source:{commit:meta.sourceCommit,modelSHA256:meta.modelSHA256,version:meta.version},effectiveIdentity:current.effectiveIdentity,semanticReport:current.semanticReport,landmarks:current.landmarks,measurements:measurementComparison(measureGNM(current.measurementLandmarks),baseline),regionNames:meta.groupNames,storedVertexArrays:0,oldPhotoWorkflow:'paused',oldR008GeometryLoaded:false,limitations:meta.limitations},'GNM-face-data.json');
 $('recipeFile').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;const data=JSON.parse(await file.text()),candidate=data.schema==='human/gnm-face-report@1'?data.recipe:data;const result=await api('/api/mesh',candidate);leaveCompare();recipe=candidate;updateMesh(result);semanticSelection();coefficientSelection();}catch(e){$('evaluationStatus').textContent=e.message;}};
 coefficientGroup();semanticSelection();
}
async function init(){try{for(;;){const status=await api('/api/status');if(status.error)throw Error(status.error);loading(status.percent*.8,status.stage,'官方模型首次准备，使用真实后台加载状态');if(status.ready)break;await new Promise(resolve=>setTimeout(resolve,400));}meta=await readMetadata();loading(92,'生成 GNM 中性基准','平均头与固定拓扑');const neutral=await api('/api/mesh',empty());baseline=measureGNM(neutral.measurementLandmarks);recipe=await api('/api/session');const data=await api('/api/mesh',recipe);sceneMesh(data);bindUI();updateMesh(data);front();loading(98,'渲染第一个真实三维帧');renderer.render(scene,camera);await new Promise(resolve=>requestAnimationFrame(resolve));firstFrame=true;loading(100,'GNM 工作台加载完成');$('loader').hidden=true;
 window.GNMWorkbench={meta,get recipe(){return structuredClone(recipe);},get result(){return current;},get ready(){return firstFrame;},get busy(){return busy;},set(value){recipe=structuredClone(value);leaveCompare();semanticSelection();coefficientSelection();return regenerate();},measure:()=>measurementComparison(measureGNM(current.measurementLandmarks),baseline),renderer,scene,camera};
 }catch(error){fail(error);}}
init();
