const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require('playwright');const {PNG}=require('pngjs');const d=path.resolve(__dirname,'..'),out=path.join(d,'qa-results');fs.mkdirSync(out,{recursive:true});
const fixed='https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/2368e26e76114f45e716cefba3320cfd76c61a9e/skin-quality-lab/';
const report={commit:process.env.GITHUB_SHA||null,date:new Date().toISOString(),checks:[],errors:[],parity:'unverified'};
const png=(data)=>PNG.sync.read(Buffer.from(data.split(',')[1],'base64'));function difference(a,b){assert.equal(a.width,b.width);assert.equal(a.height,b.height);let abs=0,sq=0,max=0,changed=0;for(let i=0;i<a.data.length;i+=4){let different=false;for(let c=0;c<3;c++){const k=Math.abs(a.data[i+c]-b.data[i+c]);abs+=k;sq+=k*k;max=Math.max(max,k);if(k>1)different=true;}if(different)changed++;}return{meanAbsolute:abs/(a.width*a.height*3),rmse:Math.sqrt(sq/(a.width*a.height*3)),max,changedRatio:changed/(a.width*a.height)};}
async function download(url,file){if(fs.existsSync(file))return;const r=await fetch(url);if(!r.ok)throw Error(url+': '+r.status);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.from(await r.arrayBuffer()));}
(async()=>{await download('https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/1d4a616672f2a45e869d4ef3e36e710b11f5cf41/skin-quality-lab/r02/preview.html',out+'/baseline.html');const assets=['r01/vendor/three.core.js','r01/vendor/three.module.js','r01/vendor/addons/controls/OrbitControls.js','r01/vendor/addons/loaders/GLTFLoader.js','r01/vendor/addons/utils/BufferGeometryUtils.js','r01/assets/head.glb','r01/assets/hires/albedo-4k.jpg','r01/assets/normal.jpg','r01/assets/hires/microheight-4k.png','r01/assets/specular.jpg','r02/assets/meso.webp','r02/assets/micro.webp','r02/assets/surface.webp','r02/assets/occlusion.bin'];await Promise.all(assets.map(a=>download(fixed+a,out+'/assets/'+a)));
const server=http.createServer((req,res)=>{let f=path.resolve(d,'.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(d+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'application/octet-stream');fs.createReadStream(f).pipe(res)}).listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--disable-dev-shm-usage']});try{const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});await context.route(fixed+'**',r=>r.fulfill({path:out+'/assets/'+r.request().url().slice(fixed.length),headers:{'access-control-allow-origin':'*'}}));const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
async function ready(url){await page.goto(url);await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,null,{timeout:180000});await page.evaluate(()=>{window.__SKIN_LAB__.setCamera('front');window.__SKIN_LAB__.render()});await page.waitForTimeout(600);}
async function capture(name){await page.evaluate(()=>window.__SKIN_LAB__.render());const url=await page.locator('#viewport > canvas').evaluate(c=>c.toDataURL('image/png'));fs.writeFileSync(out+'/'+name+'.png',Buffer.from(url.split(',')[1],'base64'));return png(url)}
await ready(base+'/qa-results/baseline.html');const baseline=await capture('baseline-front');report.baselineState=await page.evaluate(()=>window.__SKIN_LAB__.state);
await ready(base+'/preview.html');report.checks.push('Small preview loader resolves module imports and CORS through fixed source URLs');await page.evaluate(()=>window.__SKIN_LAB__.dynamic.set({enabled:false,playing:false}));const candidateOff=await capture('candidate-dynamic-off');report.baselineParity=difference(baseline,candidateOff);report.parity=report.baselineParity.rmse<=1?'image tolerance passed':'image tolerance failed';assert(report.baselineParity.rmse<=1,'Baseline pixel tolerance exceeded');report.checks.push('R02 baseline image parity RMSE <= 1/255');
await page.evaluate(()=>window.__SKIN_LAB__.dynamic.set({enabled:true,playing:false,smile:.7,brow:.12,blush:.9}));const warm=await capture('dynamic-warm');report.warmDifference=difference(candidateOff,warm);assert(report.warmDifference.meanAbsolute>.1);report.checks.push('Dynamic skin visibly changes output');
await page.evaluate(()=>window.__SKIN_LAB__.dynamic.set({diagnostic:1,smile:.25,brow:.85}));await capture('strain-diagnostic');await page.evaluate(()=>window.__SKIN_LAB__.dynamic.set({diagnostic:0,smile:0,brow:0,blush:0,pulse:0}));await capture('zero-dynamic');report.runtime=await page.evaluate(()=>({state:window.__SKIN_LAB__.state,dynamic:window.__SKIN_LAB__.dynamic.state}));assert.equal(report.runtime.state.fuzzStrands,14000);assert.deepStrictEqual(report.runtime.state.assets.albedo,[4096,4096]);report.checks.push('Original 4K albedo and 14000 fuzz strands retained');
await page.getByRole('button',{name:'独立眼球',exact:true}).click();await page.waitForFunction(()=>window.__SKIN_LAB__.eye?.ready);await page.locator('#eyeViewport').screenshot({path:out+'/eye-default.png'});const eyeA=PNG.sync.read(await page.locator('#eyeViewport canvas').screenshot());await page.evaluate(()=>window.__SKIN_LAB__.setEye({pupil:.65,iris:1.3,corneaIOR:1.6,yaw:20,irisDepth:.008}));await page.locator('#eyeViewport').screenshot({path:out+'/eye-extreme.png'});const eyeB=PNG.sync.read(await page.locator('#eyeViewport canvas').screenshot());report.eyeDifference=difference(eyeA,eyeB);assert(report.eyeDifference.meanAbsolute>.2);report.checks.push('Eye controls alter rendered pixels');
for(let i=0;i<3;i++){await page.getByRole('button',{name:'皮肤融合',exact:true}).click();await page.getByRole('button',{name:'独立眼球',exact:true}).click();}await page.getByRole('button',{name:'恢复眼球参数',exact:true}).click();report.checks.push('Repeated skin/eye switching and reset');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'参数',exact:true}).click();await page.screenshot({path:out+'/mobile-eye.png'});report.mobile=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert(report.mobile.scrollWidth<=report.mobile.width);report.checks.push('Mobile width has no horizontal overflow');assert.equal(report.errors.length,0,'Browser console/page errors');report.status='passed';
}finally{await browser.close();server.close();}})().catch(e=>{report.status='failed';report.failure=String(e);process.exitCode=1}).finally(()=>{fs.writeFileSync(out+'/QA-REPORT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
