import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {chromium} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),pub=process.env.PUBLIC_URL||null,out=process.env.EVIDENCE_DIR||root+'/evidence/browser';fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],hash=b=>createHash('sha256').update(b).digest('hex');const check=(name,ok,details)=>{checks.push({name,pass:!!ok,details});if(!ok)throw Error('FAILED: '+name);console.log('PASS',name);};
let server=null,browser=null;const report={schema:'kaopu-shoe-r02-browser/1',testSourceCommit:process.env.GITHUB_SHA||'local',public:!!pub,startedAt:new Date().toISOString(),checks,errors,scope:'Chromium + SwiftShader. Desktop and mobile viewport simulation, NOT physical devices. No native Grasshopper/comfort/whole-shoe/visual acceptance claim.'};
try{
 if(!pub){server=http.createServer((q,r)=>{if(q.url==='/favicon.ico'){r.writeHead(204);r.end();return;}r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});r.end(fs.readFileSync(root+'/public-lite.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
 const url=pub||'http://127.0.0.1:'+server.address().port;report.url=url;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});const p=await ctx.newPage();p.setDefaultTimeout(90000);p.on('pageerror',e=>errors.push(String(e)));const go=await p.goto(url,{waitUntil:'domcontentloaded',timeout:90000});check('navigation',go.ok(),{status:go.status(),url});await p.waitForFunction(()=>window.SHOE_R02?.ready,{},{timeout:90000});
 const A=()=>p.evaluate(()=>SHOE_R02.report());const render=()=>p.evaluate(()=>SHOE_R02.render());
 const shot=async n=>{await render();await p.screenshot({path:path.join(out,n+'.png'),timeout:90000});};
 const initial=await A();report.initial=initial;check('expected-version',initial.version==='R02-S1'&&(!process.env.EXPECT_BUILD||initial.buildId===process.env.EXPECT_BUILD),{version:initial.version,buildId:initial.buildId});
 const pixels=await p.evaluate(()=>{const gl=SHOE_R02.renderer.getContext(),w=gl.drawingBufferWidth,h=gl.drawingBufferHeight,a=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,a);const vals=new Set();for(let y=Math.floor(h*.22);y<h*.80;y+=4)for(let x=Math.floor(w*.2);x<w*.8;x+=4){const i=(y*w+x)*4;vals.add((a[i]<<16)|(a[i+1]<<8)|a[i+2]);}return {unique:vals.size,width:w,height:h};});check('actual-webgl-pixels',pixels.unique>150,pixels);await shot('01-original-last');
 const source=await p.evaluate(()=>SHOE_R02.sourceCheck());check('displayed-source-buffer-fidelity',source.matches,source);
 const badBuffer=await p.evaluate(async()=>{const g=SHOE_R02.root.getObjectByName('NATIVE_SOURCE_OBJECT_32').geometry,a=g.attributes.position.array,old=a[0];a[0]+=3;const negative=await SHOE_R02.sourceCheck();a[0]=old;return negative;});check('detect-corrupted-display-buffer-negative',!badBuffer.matches&&badBuffer.maxBufferErrorMm>2,badBuffer);
 const native=await p.evaluate(()=>SHOE_R02.sourceCheck());check('negative-control-restored',native.matches);
 await p.locator('[data-mode="last"]').click();await render();const zero=await p.evaluate(()=>SHOE_R02.sourceCheck());check('zero-kernel-source-recovery',zero.matches,zero);await shot('02-parameter-last-zero');
 const keys=['toe','ball','waist','instep','ankle','sole'];for(const k of keys){await p.locator('#p-'+k).evaluate((el)=>{el.value='5';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});const r=await A();check('slider-changes-real-'+k,r.maxDisplacementMm>.01&&r.flatPatternState==='STALE_REQUIRES_REFLATTENING',r.sections.find(s=>s.key===k));const b=await p.evaluate(()=>SHOE_R02.sourceCheck());check('display-follows-'+k,b.displayMatchesData&&!b.matches,b);await p.locator('#reset').click();}
 await p.locator('#p-ball').evaluate(el=>{el.value='8';el.dispatchEvent(new Event('input',{bubbles:true}));});await p.locator('#overlay').click();await shot('03-parameter-ball-8-overlay');check('modified-paper-is-stale',(await A()).flatPatternState==='STALE_REQUIRES_REFLATTENING');
 const saved=await p.evaluate(()=>SHOE_R02.exportState());await p.locator('#save').click();await p.locator('#reset').click();await p.locator('#restore').click();const restored=await p.evaluate(()=>SHOE_R02.exportState());check('save-restore-state',JSON.stringify(saved)===JSON.stringify(restored));
 const before=await p.evaluate(()=>JSON.stringify(SHOE_R02.exportState()));const refused=await p.evaluate(()=>{const v=SHOE_R02.exportState();v.acceptance.manufacturing=true;try{SHOE_R02.importState(v);return false;}catch{return true;}});check('invalid-import-rejected-without-changing-state',refused&&before===await p.evaluate(()=>JSON.stringify(SHOE_R02.exportState())));
 const downloadPromise=p.waitForEvent('download');await p.locator('#export').click();const download=await downloadPromise;const recipePath=path.join(out,'exported-recipe.json');await download.saveAs(recipePath);const exported=JSON.parse(fs.readFileSync(recipePath));check('real-config-download',exported.schema==='kaopu-footwear-study/2'&&exported.lastDeltaPercent.ball===8);
 await p.locator('#reset').click();await p.locator('#file').setInputFiles(recipePath);await p.waitForFunction(()=>SHOE_R02.exportState().lastDeltaPercent.ball===8);check('actual-file-import',JSON.stringify(exported)===await p.evaluate(()=>JSON.stringify(SHOE_R02.exportState())));
 await p.locator('[data-mode="panels"]').click();await shot('04-source-panels');check('all-nine-actual-panels',await p.evaluate(()=>SHOE_R02.root.children.filter(o=>o.userData.piece!==undefined).length===9));check('panel-stale-not-substituted',(await A()).flatPatternState==='STALE_REQUIRES_REFLATTENING');
 await p.locator('[data-piece="22"]').click();await p.locator('#isolate').click();await p.locator('[data-camera="hero"]').click();await shot('05-real-panel-P22');
 const thick0=await p.evaluate(()=>{const o=SHOE_R02.root.children.find(o=>o.userData.piece===22),a=o.geometry.attributes.position;let lo=Infinity,hi=-Infinity;for(let i=0;i<a.count;i++){lo=Math.min(lo,a.getY(i));hi=Math.max(hi,a.getY(i));}return hi-lo;});
 await p.locator('#p-panelThickness').evaluate(el=>{el.value='2';el.dispatchEvent(new Event('input',{bubbles:true}));});const thick1=await p.evaluate(()=>{const o=SHOE_R02.root.children.find(o=>o.userData.piece===22),a=o.geometry.attributes.position;let lo=Infinity,hi=-Infinity;for(let i=0;i<a.count;i++){lo=Math.min(lo,a.getY(i));hi=Math.max(hi,a.getY(i));}return hi-lo;});check('panel-actual-buffer-thickness',Math.abs(thick1/thick0-2)<1e-6,{thick0,thick1});
 await p.locator('[data-mode="seam"]').click();await shot('06-continuous-seam');const audit=await p.evaluate(()=>SHOE_R02.seamAudit()),rays=await p.evaluate(()=>SHOE_R02.rayHoles());check('inherited-real-thread-topology',audit.threadCount===1&&audit.threadJoinErrorMM===0&&audit.pointsOutsideHole===0,audit);check('real-mesh-hole-and-solid-control',rays.holeHits===0&&rays.materialHits>0,rays);
 await p.locator('#p-count').evaluate(el=>{el.value='19';el.dispatchEvent(new Event('input',{bubbles:true}));});await p.locator('#p-layerThickness').evaluate(el=>{el.value='2.2';el.dispatchEvent(new Event('input',{bubbles:true}));});const changed=await p.evaluate(()=>SHOE_R02.seamAudit());check('thread-rebuilt-for-real-thickness-and-hole-count',Math.abs(changed.totalThicknessMM-4.4)<1e-6&&changed.passages>audit.passages,changed);await shot('07-seam-thickness-2-2');
 const guard=await p.evaluate(()=>SHOE_R02.guards());check('native-tailor-positive-and-negative-specs',guard.normalThreePanels&&guard.reversedSeamRejected&&guard.missingPanelRejected&&!guard.shoeGate.passed,guard);
 for(const mode of ['source','last','panels','seam']){await p.evaluate(mode=>SHOE_R02.mode(mode),mode);for(const cam of ['hero','side','front','top','bottom']){await p.evaluate(c=>SHOE_R02.setCamera(c),cam);const projected=await p.evaluate(()=>{const camera=SHOE_R02.camera;let finite=true,out=0,total=0;SHOE_R02.root.traverse(o=>{if(!o.geometry||o.type==='Sprite')return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i+=Math.max(1,Math.floor(a.count/300))){const q=SHOE_R02.control.target.clone().set(a.getX(i),a.getY(i),a.getZ(i)).applyMatrix4(o.matrixWorld).project(camera);finite&&=Number.isFinite(q.x+q.y+q.z);out+=Math.abs(q.x)>1||Math.abs(q.y)>1;total++;}});return {finite,out,total};});check('camera-framing-'+mode+'-'+cam,projected.finite&&projected.out===0&&projected.total>0,projected);}}
 await p.evaluate(()=>{SHOE_R02.mode('source');SHOE_R02.setCamera('hero');});const rect=await p.locator('#canvas').boundingBox(),c0=await p.evaluate(()=>SHOE_R02.camera.position.toArray());await p.mouse.move(rect.x+rect.width*.50,rect.y+rect.height*.55);await p.mouse.down();await p.mouse.move(rect.x+rect.width*.66,rect.y+rect.height*.55,{steps:8});await p.mouse.up();const c1=await p.evaluate(()=>SHOE_R02.camera.position.toArray());check('actual-orbit-pointer',Math.hypot(...c1.map((v,k)=>v-c0[k]))>1);await shot('08-rotated-source');
 await p.locator('[data-mode="method"]').click();check('framework-and-six-domains-present',await p.locator('.method-card').count()===6&&await p.locator('#method-view').isVisible());await shot('09-method-gates');
 const mob=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const m=await mob.newPage();m.on('pageerror',e=>errors.push(String(e)));await m.goto(url,{waitUntil:'domcontentloaded',timeout:90000});await m.waitForFunction(()=>window.SHOE_R02?.ready,{},{timeout:90000});await m.evaluate(()=>SHOE_R02.resize());check('mobile-no-horizontal-overflow',await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:path.join(out,'10-mobile-390x844.png'),fullPage:true,timeout:90000});
 await m.locator('[data-mode="last"]').click();await m.locator('#p-toe').evaluate(el=>{el.value='4';el.dispatchEvent(new Event('input',{bubbles:true}));});check('mobile-real-parameter-response',await m.evaluate(()=>SHOE_R02.report().maxDisplacementMm>.01));await mob.close();
 const offline=await browser.newContext();await offline.setOffline(true);const op=await offline.newPage();await op.goto('file://'+root+'/public-lite.html');await op.waitForFunction(()=>window.SHOE_R02?.ready);check('standalone-offline-file-render',await op.evaluate(()=>SHOE_R02.report().triangles>1000));await offline.close();
 check('no-page-errors',errors.length===0,errors);report.status='passed';
}catch(e){report.status='failed';report.failure=String(e);console.error(e);process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();report.passed=checks.filter(x=>x.pass).length;report.total=checks.length;fs.writeFileSync(path.join(out,'QA.json'),JSON.stringify(report,null,2));if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));console.log('BROWSER_RESULT',report.status,report.passed,'/',report.total);}
