const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');const root=path.resolve(__dirname,'../../..'),d=path.resolve(__dirname,'..'),out='/tmp/eye-evidence';fs.mkdirSync(out,{recursive:true});
const PUBLIC=process.env.EYE_PUBLIC_SHA;let server,browser,page;
const report={version:'ET02',run:process.env.GITHUB_RUN_ID,sourceCommit:process.env.GITHUB_SHA,publicCommit:PUBLIC||null,public:!!PUBLIC,networkInterception:false,physicalMobileDevice:false,errors:[],consoleErrors:[],requests:[],failures:[],checks:{},differences:{}};
function diff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);assert.equal(a.width,b.width);let sum=0,changed=0;for(let i=0;i<a.data.length;i+=4){let d=Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2]);sum+=d;if(d>8)changed++;}return {meanAbsolute:sum/(a.width*a.height*3),changedFraction:changed/(a.width*a.height)};}
async function capture(name){await page.evaluate(()=>__SKIN_LAB__.render());let str=await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL('image/png'));let b=Buffer.from(str.split(',')[1],'base64');if(name){fs.writeFileSync(out+'/'+name+'-canvas.png',b);await page.screenshot({path:out+'/'+name+'.png',timeout:90000});}return b;}
(async()=>{
 let url;
 if(PUBLIC){url='https://htmlpreview.github.io/?https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/'+PUBLIC+'/skin-quality-lab/emily-transfer/preview.html';}
 else {const mime={'.html':'text/html','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.json':'application/json','.glb':'model/gltf-binary'};server=http.createServer((req,res)=>{try{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep))throw Error('Outside root');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).on('error',()=>res.writeHead(404).end()).pipe(res);}catch(e){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';}
 report.url=url;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('request',r=>report.requests.push(r.url()));page.on('requestfailed',r=>report.failures.push({url:r.url(),reason:r.failure()?.errorText}));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__EYES__&&window.__SKIN_LAB__?.state.ready,{},{timeout:240000});
 await page.evaluate(()=>{window.__EYE_QA_FREEZE__=true;__EYES__.set({autoBlink:false,autoPupil:false,pupilMM:3.6});__EYES__.step(0,true);});
 assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/2.0.0');assert.equal(await page.locator('#viewport canvas').count(),1);const original=await page.evaluate(()=>__EYES__.sourceGeometry());report.checks.sourceGeometry=original;
 const portrait=await capture(PUBLIC?'public-portrait':'01-portrait');report.checks.initialEyes=await page.evaluate(()=>__EYES__.info());assert.equal(report.checks.initialEyes.eyes.length,2);assert(report.checks.initialEyes.lockErrorDegrees.every(n=>n<.05));
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>__EYES__.step(0,true));const eye=await capture(PUBLIC?'public-eyes':'02-eyes');
 await page.evaluate(()=>{__EYES__.setTarget([.13,.09,.7]);__EYES__.step(0,true);});const right=await capture(PUBLIC?'public-look-right':'03-look-right');const infoRight=await page.evaluate(()=>__EYES__.info());assert(infoRight.lockErrorDegrees.every(n=>n<.05),'Binocular target is not converged');
 await page.evaluate(()=>{__EYES__.setTarget([-.13,.09,.7]);__EYES__.step(0,true);});const left=await capture(PUBLIC?'public-look-left':'04-look-left');report.differences.leftRight=diff(left,right);assert(report.differences.leftRight.meanAbsolute>.02,'Eyes do not visibly change with target');report.checks.binocularTarget=await page.evaluate(()=>__EYES__.info());
 const targetBefore=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(1000,250);await page.evaluate(()=>__EYES__.step(.05));assert.deepEqual(await page.evaluate(()=>__EYES__.info().target),targetBefore);report.checks.worldTargetLock=true;
 await page.evaluate(()=>{__EYES__.setMode('camera');__EYES__.step(0,true);__EYES__.set({autoPupil:false,pupilMM:2});});let small=await capture();await page.evaluate(()=>__EYES__.set({autoPupil:false,pupilMM:6}));let large=await capture(PUBLIC?'public-pupil':'05-pupil-large');report.differences.pupil=diff(small,large);assert(report.differences.pupil.meanAbsolute>.005,'Pupil aperture has no visible effect');
 await page.evaluate(()=>{__EYES__.set({pupilMM:3.6});__EYES__.blink();__EYES__.step(.05);__EYES__.step(.05);});const closed=await capture(PUBLIC?'public-blink':'06-blink-closed');assert((await page.evaluate(()=>__EYES__.info().blink))>.99);report.differences.blink=diff(eye,closed);assert(report.differences.blink.meanAbsolute>.01);
 await page.evaluate(()=>{for(let i=0;i<6;i++)__EYES__.step(.05);__EYES__.step(0,true);});
 await page.click('[data-camera="iris"]');await page.evaluate(()=>__EYES__.step(0,true));await capture(PUBLIC?'public-iris':'07-iris-detail');
 await page.selectOption('#eyeIris','hazel');let hazel=await capture();await page.selectOption('#eyeIris','blue');let blue=await capture();report.differences.irisColor=diff(hazel,blue);assert(report.differences.irisColor.meanAbsolute>.002);
 await page.click('[data-camera="portrait"]');await page.evaluate(()=>{__EYES__.step(0,true);__EYES__.set({enabled:false});});const old=await capture(PUBLIC?'public-original-scan':'08-original-scan');assert.deepEqual(await page.evaluate(()=>__EYES__.sourceGeometry()),original);await page.evaluate(()=>__EYES__.set({enabled:true}));report.checks.geometryUnmodified=true;
 await page.selectOption('#transferMode','split');await page.click('[data-method="enhanced"]');await capture(PUBLIC?'public-skin-comparison':'09-skin-comparison');report.checks.skinComparisonRetained=true;
 await page.selectOption('#transferMode','full');await page.click('[data-method="emily"]');
 await page.selectOption('#eyeMode','pointer');await page.mouse.move(920,440);await page.evaluate(()=>__EYES__.step(0,true));let first=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(210,440);await page.evaluate(()=>__EYES__.step(0,true));let second=await page.evaluate(()=>__EYES__.info().target);assert.notDeepEqual(first,second);await page.click('#lockEye');assert.equal(await page.evaluate(()=>__EYES__.info().mode),'fixed');report.checks.pointerFollowAndLock=true;
 await page.selectOption('#eyeIris','green');await page.click('#save');await page.selectOption('#eyeIris','brown');await page.click('#restore');assert.equal(await page.locator('#eyeIris').inputValue(),'green');report.checks.eyeRecipeRestored=true;
 await page.click('#reset');await page.evaluate(()=>{__EYES__.set({autoBlink:false,autoPupil:false});__EYES__.step(0,true);});
 await page.setViewportSize({width:390,height:844});await page.click('[data-camera="portrait"]');await page.evaluate(()=>__EYES__.step(0,true));await capture(PUBLIC?'public-mobile':'10-mobile');await page.click('#mobileToggle');assert(await page.locator('.side').isVisible());await page.selectOption('#eyeMode','pointer');await page.click('#mobileToggle');assert(!await page.locator('.side').isVisible());report.checks.mobileViewport={width:390,height:844,physicalDevice:false,controls:true};
 assert.deepEqual(report.errors,[],'Page errors');assert.deepEqual(report.consoleErrors,[],'Shader/rendering errors');assert.deepEqual(report.failures,[],'Failed requests');assert(!report.requests.some(s=>s.includes('alteredqualia.com')),'Unexpected remote eye assets');
 report.passed=true;const json=JSON.stringify(report,null,2);fs.writeFileSync(out+'/'+(PUBLIC?'public-report.json':'qa-report.json'),json);if(!PUBLIC){fs.writeFileSync(__dirname+'/qa-report.json',json);fs.mkdirSync(__dirname+'/evidence',{recursive:true});for(let n of ['01-portrait','02-eyes','03-look-right','04-look-left','06-blink-closed','07-iris-detail','10-mobile'])fs.copyFileSync(out+'/'+n+'.png',__dirname+'/evidence/'+n+'.png');}
 console.log('EYE_QA_PASS',JSON.stringify({public:!!PUBLIC,url:report.url,checks:report.checks,differences:report.differences}));
})().catch(async e=>{report.passed=false;report.failure=e.stack;fs.writeFileSync(out+'/'+(PUBLIC?'public-failure.json':'qa-failure.json'),JSON.stringify(report,null,2));console.error(e);if(page){await page.screenshot({path:out+'/failure.png',timeout:90000}).catch(()=>{});fs.writeFileSync(out+'/failure-body.txt',await page.locator('body').innerText().catch(()=>''));}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
