const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const D=path.resolve(__dirname,'..'),ROOT=path.resolve(D,'../..'),OUT=process.env.EYE_OUT||path.join(__dirname,'evidence');fs.mkdirSync(OUT,{recursive:true});
const report={version:'ET02.0',errors:[],consoleErrors:[],checks:{},rendering:'Chromium / SwiftShader',mobilePhysicalDevice:false};
function difference(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let sum=0,n=0;for(let i=0;i<a.data.length;i+=4){sum+=Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2]);n+=3;}return sum/n;}
let browser,page,server;
(async()=>{
 if(process.env.EYE_FIXTURE){const o=await require('/mnt/data/eyes-work/local-runner.cjs').open();browser=o.b;page=o.p;report.errors=o.errors;report.offlineFixture=true;}
 else {server=http.createServer((req,res)=>{const f=path.resolve(ROOT,'.'+new URL(req.url,'http://test').pathname);if(!f.startsWith(ROOT+'/'))return res.writeHead(403).end();try{const ext=path.extname(f),types={'.html':'text/html','.js':'application/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.jpg':'image/jpeg','.webp':'image/webp','.png':'image/png'};res.setHeader('Content-Type',types[ext]||'text/plain');res.end(fs.readFileSync(f));}catch(e){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});await page.goto('http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>__SKIN_LAB__?.state.ready,null,{timeout:180000});}
 page.setDefaultTimeout(60000);
 async function settle(){await page.evaluate(()=>{__EYES__.step(0);__SKIN_LAB__.render()});}
 async function canvas(){await settle();return Buffer.from((await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL())).split(',')[1],'base64');}
 async function shot(name){await settle();await page.screenshot({path:OUT+'/'+name+'.png',timeout:90000});console.log('EYE_SHOT',name);}
 await page.evaluate(()=>__EYES__.set({autoBlink:false,autoPupil:false}));await settle();
 assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/2.0.0');
 report.checks.initialPose=await page.evaluate(()=>__EYES__.pose());assert.equal(report.checks.initialPose.eyes.length,2);assert(report.checks.initialPose.eyes.every(e=>e.targetErrorDegrees<.02));
 await shot('01-et02-portrait');
 // Actual cursor input, then a world-space fixation while the head mesh is rotated.
 await page.click('[data-gaze="pointer"]');await page.mouse.move(690,450);await settle();const follow=await page.evaluate(()=>__EYES__.pose());await page.click('[data-gaze="locked"]');const target=await page.evaluate(()=>__EYES__.pose().target);await page.mouse.move(120,210);await page.locator('#eye-headYaw').evaluate(el=>{el.value='12';el.dispatchEvent(new Event('input',{bubbles:true}));});await settle();const locked=await page.evaluate(()=>__EYES__.pose());assert.deepEqual(locked.target,target);assert(locked.eyes.every(e=>e.targetErrorDegrees<.02));assert(Math.abs(locked.headRotation[1]-.2094395102)<.001);report.checks.lockedTargetAfterHeadTurn={follow,locked};await shot('02-locked-head-turn');
 await page.click('#eye-reset');await page.evaluate(()=>{__EYES__.set({autoBlink:false,autoPupil:false});__SKIN_LAB__.setCamera('eye');});await settle();await shot('03-refracted-eye-macro');
 const original=await canvas();await page.uncheck('#eye-autoPupil');await page.locator('#eye-pupil').evaluate(el=>{el.value='.58';el.dispatchEvent(new Event('input',{bubbles:true}));});let pupil=await canvas();report.checks.pupilPixelDifference=difference(original,pupil);assert(report.checks.pupilPixelDifference>.08,'Pupil has no visible effect');
 await page.locator('#eye-wet').evaluate(el=>{el.value='0';el.dispatchEvent(new Event('input',{bubbles:true}));});const dry=await canvas();report.checks.corneaReflectionPixelDifference=difference(pupil,dry);assert(report.checks.corneaReflectionPixelDifference>.03,'Corneal reflection has no visible effect');
 await page.evaluate(()=>{__EYES__.set({wet:.92,pupil:.32,openness:0});});const closed=await canvas();report.checks.eyelidClosureDifference=difference(original,closed);assert(report.checks.eyelidClosureDifference>.2,'Eyelids do not close');await shot('04-closed-lids');
 await page.evaluate(()=>{__EYES__.set({openness:1,autoPupil:true});__SKIN_LAB__.setLighting({key:.05,fill:.03});__EYES__.step(0);});const dark=await page.evaluate(()=>__EYES__.pose().pupil);await page.evaluate(()=>{__SKIN_LAB__.setLighting({key:4.3,fill:.5});__EYES__.step(0);});const bright=await page.evaluate(()=>__EYES__.pose().pupil);assert(dark>bright+.05);report.checks.lightPupil={dark,bright};
 // Parameters share the original save/restore/JSON mechanism, including fixation target.
 await page.evaluate(()=>{__EYES__.set({iris:'hazel',headYaw:7,autoPupil:false,pupil:.44});__EYES__.setTarget([.04,.07,.72]);});const savedRecipe=await page.evaluate(()=>__EMILY_TRANSFER__.exportRecipe());if(!process.env.EYE_FIXTURE)await page.click('#save');await page.evaluate(()=>__EYES__.set({iris:'brown',headYaw:0,pupil:.22}));if(process.env.EYE_FIXTURE)await page.evaluate(o=>__EMILY_TRANSFER__.loadRecipe(o),savedRecipe);else await page.click('#restore');let restored=await page.evaluate(()=>({...__EYES__.config}));assert.equal(restored.iris,'hazel');assert.equal(restored.headYaw,7);assert.equal(restored.pupil,.44);assert.equal(restored.mode,'locked');report.checks.saveRestore=process.env.EYE_FIXTURE?'JSON roundtrip; opaque fixture cannot use localStorage':'actual browser localStorage';
 await page.click('#reset');await page.click('#eye-reset');await page.evaluate(()=>{__EYES__.set({autoBlink:false,autoPupil:true});__SKIN_LAB__.setCamera('eyes');});await settle();await shot('05-binocular-closeup');
 await page.evaluate(()=>__EYES__.setTarget([0,.069,-.2]));await settle();assert.equal(await page.evaluate(()=>__EYES__.pose().limited),true);report.checks.rearTargetSafelyLimited=true;
 await page.click('#eye-reset');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__SKIN_LAB__.setCamera('portrait'));await settle();await shot('06-mobile-viewport');await page.click('#mobileToggle');assert(await page.locator('.side').isVisible());await page.click('[data-gaze="pointer"]');await page.click('[data-gaze="locked"]');await page.click('#mobileToggle');report.checks.mobile={width:390,height:844,panel:true,gazeModes:true,realDevice:false};
 report.final=await page.evaluate(()=>({skin:__SKIN_LAB__.state,eyes:__EYES__.pose()}));assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.final.skin.errors,[]);report.passed=true;fs.writeFileSync(OUT+'/eyes-qa.json',JSON.stringify(report,null,2));console.log('ET02_QA_PASS',JSON.stringify(report.checks));
})().catch(async e=>{report.passed=false;report.failure=e.stack;console.error(e);if(page)await page.screenshot({path:OUT+'/failure.png',timeout:60000}).catch(()=>{});fs.writeFileSync(OUT+'/eyes-qa.json',JSON.stringify(report,null,2));process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
