import {parameterField,commonDescription} from './parameter-ui.js';
import {initExportGuide} from './export-guide.js';
import {createAssetLoader} from './asset-loader.js';
import {stringifyData} from './function-data.js';
import {createImporter} from './import-manager.js';
import {createRehearsal} from './rehearsal.js';
import {bakeAnimal} from './baked.js';
import {makeLiveBake} from './live-package.js';
import {factoryBasic,validateBasic,declaredBasic,basicSummary,meshBounds} from './basic-data.js';
import {ANIMALS,CATEGORIES} from './catalog.js';import {createGLB} from './glb.js';
const $=id=>document.getElementById(id),frame=$('animal-frame'),assets=window.ATLAS_ASSETS,thumbs=window.ATLAS_THUMBS||{},bridge=window.ATLAS_BRIDGE,style=window.ATLAS_FRAME_STYLE;
const basicSaved={};
for(const a of ANIMALS)a.basicData=factoryBasic(a.id);
function basicData(a=current){const b=basicSaved[a.id]||importer?.records.get(a.id)?.animal.basicData||a.basicData||factoryBasic(a.id);return b?validateBasic(b):null;}
function setBasic(id,value){validateBasic(value);basicSaved[id]=structuredClone(value);const a=ANIMALS.find(a=>a.id===id);if(a)a.basicData=structuredClone(value);persist();if(current?.id===id)renderControls();return basicSaved[id];}
function renderMissingBasic(el){const inputs={};for(const [key,label]of [['span','当前姿态跨度 (m)'],['mass','个体体重 (kg)']]){const row=document.createElement('label');row.className='field';row.textContent=label;const input=document.createElement('input');input.id='missing-basic-'+key;input.type='number';input.min='.000001';input.step='any';row.append(input);el.append(row);inputs[key]=input;}const button=document.createElement('button');button.textContent='补齐并保存基本数据';button.onclick=async()=>{button.disabled=true;try{const id=current.id,span=+inputs.span.value,mass=+inputs.mass.value;if(!(span>0&&mass>0))throw Error('请填写正数的跨度与体重');const result=await request('mesh',{},180000);setBasic(id,declaredBasic(span,mass,Math.max(...meshBounds(result.items).size)));toast('基本数据已补齐');}catch(e){toast(e.message);}finally{button.disabled=false;}};el.append(button);}
function renderBasic(mount){const b=basicData(),el=document.createElement('details');el.className='section';el.dataset.group='basic';el.open=true;const summary=document.createElement('summary');summary.textContent='统一基准 · 米 / 千克';el.append(summary);const note=document.createElement('p');note.className='hint';note.textContent=basicSummary(b);el.append(note);if(b){for(const [key,label]of [['referenceSpanM','基准姿态跨度 (m)'],['massKg','个体体重 (kg)']]){const row=document.createElement('div');row.className='field';const l=document.createElement('label'),input=document.createElement('input');input.id='basic-'+key;input.type='number';input.min=key==='massKg'?.000001:.001;input.step='any';input.value=b[key];l.htmlFor=input.id;l.textContent=label;input.onchange=()=>{try{setBasic(current.id,declaredBasic(key==='referenceSpanM'?+input.value:b.referenceSpanM,key==='massKg'?+input.value:b.massKg,b.sourceSpan,b));toast('基本数据已保存；下次导出和放入排练台使用此数据');}catch(e){toast(e.message);input.value=b[key];}};row.append(l,input);el.append(row);}const hint=document.createElement('p');hint.className='hint';hint.textContent='跨度指基准姿态的包围尺寸，含尾、翼或足。单位换算固定，调形体会改变实际尺寸。体重独立填写，不随展示缩放推算。';el.append(hint);const inspect=document.createElement('button');inspect.textContent='测量当前形态';inspect.onclick=async()=>{try{const captured=await request('mesh',{},180000),dimensions=meshBounds(captured.items).size.map(v=>v*b.metersPerUnit);hint.textContent='当前包围尺寸 X / Y / Z：'+dimensions.map(v=>v.toFixed(3)+' m').join(' / ')+'；体重 '+b.massKg+' kg（独立声明）。';}catch(e){toast(e.message);}};el.append(inspect);}else renderMissingBasic(el);mount.append(el);}
let category='all',query='',favoritesOnly=false,current=null,channel='',loaded=false,playing=true,settings={},controls=[],actions=[],serial=0,loadEpoch=0,loadTimer,toastTimer;let importer;const pending=new Map(),saved={};let favorites=new Set(),removed=new Set(),storage=true;
try{const data=JSON.parse(localStorage.getItem('animal-atlas/v1')||'{}');Object.assign(saved,data.settings||{});Object.assign(basicSaved,data.basicData||{});favorites=new Set(data.favorites||[]);removed=new Set(data.removed||[]);}catch{storage=false;}
for(const a of ANIMALS)if(basicSaved[a.id])try{a.basicData=validateBasic(basicSaved[a.id]);}catch{delete basicSaved[a.id];}
function persist(){try{localStorage.setItem('animal-atlas/v1',JSON.stringify({settings:saved,basicData:basicSaved,favorites:[...favorites],removed:[...removed]}));}catch{storage=false;$('save-status').textContent='浏览器不允许保存；可导出 JSON 配方';}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4300);}
function renderNav(){$('categories').replaceChildren();const label=document.createElement('div');label.className='caption';label.textContent='HABITATS';$('categories').append(label);for(const c of CATEGORIES){const button=document.createElement('button');button.className='category'+(category===c.id?' active':'');button.setAttribute('aria-pressed',String(category===c.id));button.dataset.category=c.id;button.innerHTML='<span class="icon">'+c.icon+'</span><span>'+c.name+'</span><span class="en">'+c.en+'</span>';button.onclick=()=>{category=c.id;renderNav();renderGrid();};$('categories').append(button);}const bottom=document.createElement('div');bottom.className='nav-bottom';bottom.innerHTML=visibleAnimals().length+'<br>SPECIMENS<br>V1.2';$('footer-count').textContent=visibleAnimals().length+' 个对象 / 4 类栖息环境';$('categories').append(bottom);}
function visibleAnimals(){return ANIMALS.filter(a=>!removed.has(a.id));}
function toggleFavorite(id){if(!ANIMALS.some(a=>a.id===id)||removed.has(id))return;const added=!favorites.has(id);added?favorites.add(id):favorites.delete(id);persist();updateFavorite();renderGrid();toast(added?'已添加到我的收藏':'已取消收藏');}
function renderGrid(){const c=CATEGORIES.find(c=>c.id===category),list=visibleAnimals().filter(a=>(category==='all'||a.category===category)&&(!favoritesOnly||favorites.has(a.id))&&(!query||[a.name,a.en,...a.tags].join(' ').toLowerCase().includes(query)));$('category-title').textContent=c.name;$('count').textContent=list.length+' 个';$('animal-grid').replaceChildren();$('empty').hidden=!!list.length;$('favorite-tab').textContent='收藏 '+visibleAnimals().filter(a=>favorites.has(a.id)).length;$('deleted-tab').textContent='已删除 '+removed.size;
 for(const a of list){const card=document.createElement('article');card.className='animal-card'+(current?.id===a.id?' active':'');card.dataset.animal=a.id;const pick=document.createElement('button');pick.className='animal-select';pick.setAttribute('aria-label',a.name+'，'+a.version);pick.setAttribute('aria-pressed',String(current?.id===a.id));const thumb=document.createElement('div');thumb.className='thumb';const img=document.createElement('img');img.alt=a.name+'的三维模型缩略图';if(thumbs[a.id])img.src=thumbs[a.id];else{img.hidden=true;const p=document.createElement('span');p.className='thumb-placeholder';p.textContent='◇';thumb.append(p);}thumb.append(img);if(current?.id===a.id){const tick=document.createElement('span');tick.className='tick';tick.textContent='✓';thumb.append(tick);}const name=document.createElement('span');name.className='name';name.textContent=a.name;pick.append(thumb,name);pick.onclick=()=>selectAnimal(a.id);const fav=document.createElement('button');fav.className='card-favorite'+(favorites.has(a.id)?' selected':'');fav.textContent=favorites.has(a.id)?'★':'☆';fav.title=(favorites.has(a.id)?'取消收藏':'添加收藏')+' '+a.name;fav.setAttribute('aria-label',fav.title);fav.setAttribute('aria-pressed',String(favorites.has(a.id)));fav.onclick=()=>toggleFavorite(a.id);card.append(pick,fav);$('animal-grid').append(card);}
}
function renderDeleted(){const list=$('deleted-list');list.replaceChildren();for(const id of removed){const a=ANIMALS.find(a=>a.id===id&&!a.imported);if(!a)continue;const row=document.createElement('div');row.className='deleted-row';const label=document.createElement('span');label.textContent=a.name+' · '+a.version;const restore=document.createElement('button');restore.textContent='恢复乐谱';restore.dataset.restore=id;restore.onclick=()=>{removed.delete(id);persist();renderNav();renderGrid();renderDeleted();selectAnimal(id);toast('已恢复 '+a.name+' 的初始乐谱');};row.append(label,restore);list.append(row);}if(!list.children.length)list.textContent='没有已删除的内置乐谱。';}
function emptyStage(){++loadEpoch;clearTimeout(loadTimer);loaded=false;current=null;frame.srcdoc='';$('loading').hidden=true;$('animal-name').textContent='选择或导入一份动物乐谱';$('animal-en').textContent='ANIMAL SCORE';$('habitat').textContent='旋转展示台';$('parameters').textContent='从目录选择动物，或导入乐谱。';$('pause').disabled=$('export').disabled=$('rotate-toggle').disabled=$('favorite').disabled=$('delete-score').disabled=true;$('runtime-status').textContent='EMPTY';window.__ATLAS__={ready:false,current:null,catalog:ANIMALS};renderGrid();}
function selectAvailable(preferred){const a=visibleAnimals().find(a=>a.id===preferred)||visibleAnimals()[0];return a?selectAnimal(a.id):emptyStage();}
async function deleteCurrentScore(){if(!current)return;const a=current;if(a.imported){await importer.remove(a.id);return;}removed.add(a.id);favorites.delete(a.id);delete saved[a.id];delete basicSaved[a.id];a.basicData=factoryBasic(a.id);persist();renderNav();renderGrid();const next=visibleAnimals().find(x=>x.category===a.category)||visibleAnimals()[0];next?selectAnimal(next.id):emptyStage();toast('已删除 '+a.name+' 的乐谱，可在“已删除”中恢复');}
const assetLoader=createAssetLoader(key=>{const data=$('payload-'+key)?.textContent.trim(),baseAsset=assets[key]?.baseAsset;return data&&{data,...(baseAsset?{base:$('payload-'+baseAsset)?.textContent.trim()}: {})};});
window.__ATLAS_LOADING__={last:null,stats:assetLoader.stats};
async function decodeAsset(key){const imported=await importer?.runtimeAsset(key);return imported||assetLoader.decode(key);}
const safe=x=>JSON.stringify(x).replace(/</g,'\\u003c');
function runtimeHtml(original,a,initial={},runtimeChannel='standalone'){
 const context={...a,basicData:a.basicData||basicData(a),...(a.adapter==='imported'?{geometryUnits:'source-units'}:{}),initial,channel:runtimeChannel};const bootstrap='<script>window.__ATLAS_CONTEXT='+safe(context)+';addEventListener("error",e=>{if(!window.AnimalRuntime?.ready&&parent!==window)parent.postMessage({protocol:"animal-atlas/1",channel:window.__ATLAS_CONTEXT.channel,type:"failure",error:e.message},"*");});<\/script>';return original.replace(/<head[^>]*>/i,m=>m+bootstrap).replace(/<\/head>/i,'<style>'+style+'</style></head>').replace(/<\/body>/i,()=>'<script>'+bridge.replaceAll('</script','<\\/script')+'<\/script></body>');
}
async function selectAnimal(id,{reset=false,initial}={}){
 const a=ANIMALS.find(a=>a.id===id);if(!a||removed.has(id))return;if(loaded&&current?.id===id&&!reset&&!initial)return;if(window.__ATLAS__)window.__ATLAS__.ready=false;const epoch=++loadEpoch;current=a;channel='atlas-'+epoch+'-'+Math.random().toString(36).slice(2);loaded=false;playing=true;settings={...(reset?{}:saved[id]),...initial};controls=[];actions=[];
 for(const {reject,timer}of pending.values()){clearTimeout(timer);reject(Error('对象已切换'));}pending.clear();frame.srcdoc='<!doctype html><html><body style="margin:0;background:#132730"></body></html>';
 $('loading').hidden=false;$('loading').classList.remove('error-card');$('loading-title').textContent='正在载入 '+a.name;$('loading-note').textContent='读取内嵌模型、绑定和原有运行时';$('retry').hidden=true;$('pause').disabled=true;$('export').disabled=true;$('favorite').disabled=$('delete-score').disabled=false;$('rotate-toggle').disabled=true;$('animal-en').textContent=a.en;$('animal-name').textContent=a.name;$('habitat').textContent='旋转展示台';$('stage-label').textContent='实时三维 · '+a.version;$('runtime-status').textContent='LOADING';$('parameters').innerHTML='<div class="section"><p class="description"></p><p class="hint">模型载入后显示可用参数…</p></div>';$('parameters').querySelector('.description').textContent=a.description;renderGrid();updateFavorite();document.querySelectorAll('.viewbar button').forEach(b=>b.classList.toggle('active',b.dataset.view==='three'));clearTimeout(loadTimer);
 loadTimer=setTimeout(()=>{if(epoch===loadEpoch&&!loaded)showError('模型加载时间较长，点击重新载入。');},110000);
 try{const started=performance.now(),original=await decodeAsset(a.asset);if(epoch!==loadEpoch)return;window.__ATLAS_LOADING__.last={id,started,decodeMs:performance.now()-started};frame.srcdoc=runtimeHtml(original,a,settings,channel);}catch(e){if(epoch===loadEpoch)showError(e.message);}
}
function showError(message){loaded=false;$('loading').hidden=false;$('loading').classList.add('error-card');$('loading-title').textContent='当前动物未能加载';$('loading-note').textContent=message;$('retry').hidden=false;$('runtime-status').textContent='LOAD FAILED';$('export').disabled=true;}
function request(type,data={},timeout=120000){if(!loaded)return Promise.reject(Error('请等待模型载入'));const requestId=++serial;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(requestId);reject(Error('操作超时，请重新载入当前动物'));},timeout);pending.set(requestId,{resolve,reject,timer});frame.contentWindow.postMessage({protocol:'animal-atlas/1',channel,type,requestId,...data},'*');});}
async function set(key,value){try{const r=await request('set',{key,value});settings={...r.record};const input=$('param-'+key);if(input){if(input.type==='checkbox')input.checked=!!settings[key];else input.value=String(settings[key]);const output=input.closest('.field')?.querySelector('output'),def=controls.find(d=>d.key===key);if(output&&def)output.value=format(settings[key],def);}if(key==='action'&&$('action-select'))$('action-select').value=value;saved[current.id]={...settings};persist();if(key==='playing'||key==='action'){playing=settings.playing!==false;updatePause();}if(key==='displayStage')renderControls();if(key==='studioRotate'||key==='displayStage')updateStudio();return r;}catch(e){if(e.message!=='对象已切换')toast(e.message);throw e;}}
async function setCommon(id,value){
 if(id==='physical.referenceSpanM'||id==='physical.massKg'){const b=basicData();if(!b)throw Error('请先补齐基本数据');return setBasic(current.id,declaredBasic(id==='physical.referenceSpanM'?Number(value):b.referenceSpanM,id==='physical.massKg'?Number(value):b.massKg,b.sourceSpan,b));}
 if(id==='lifecycle.playing'||id==='lifecycle.action'){if(!actions.length)throw Error('当前动物没有原生动作');return set(id==='lifecycle.playing'?'playing':'action',value);}
 const binding=controls.find(d=>d.commonId===id);if(!binding)throw Error('当前动物不支持这个共用参数：'+id);return set(binding.key,value);
}
function updatePause(){$('pause').textContent=playing?'Ⅱ 暂停动作':'▶ 播放动作';}
function section(label,num){const el=document.createElement('section');el.className='section';const h=document.createElement('h3');h.textContent=label;el.append(h);return el;}
function renderControls(){const mount=$('parameters');mount.replaceChildren();renderBasic(mount);const info=document.createElement('details');info.className='section object-info';const infoTitle=document.createElement('summary');infoTitle.textContent='对象说明';info.append(infoTitle);const desc=document.createElement('p');desc.className='description';desc.textContent=current.description;info.append(desc);const age=document.createElement('div');age.className='age';age.innerHTML='年龄 / 生长<span>原模型尚未开放</span>';age.classList.add('compact-age');info.append(age);info.dataset.group='info';if(current.imported){const tag=document.createElement('p');tag.className='hint';tag.textContent='乐器：'+importer.instrumentFor(current).id+' · '+importer.instrumentFor(current).version;info.append(tag);}if(current.capability){const note=document.createElement('div');note.className='limit';note.textContent=current.capability;info.append(note);}mount.append(info);
 const groups={studio:section('展示与光线','02'),motion:section('动作与演示','02'),common:section('通用外观与检查','03'),scene:section('栖息环境参数','04'),extensions:document.createElement('details')};groups.extensions.className='section species-controls';const extTitle=document.createElement('summary');extTitle.textContent='物种专属参数';groups.extensions.append(extTitle);
 if(actions.length){const row=document.createElement('div');row.className='field action-select';const label=document.createElement('label');label.textContent='动作演示';const sel=document.createElement('select');sel.id='action-select';sel.setAttribute('aria-label','动作演示');label.className='action-label';for(const a of actions){const o=document.createElement('option');o.value=a.id;o.textContent=a.label;sel.append(o);}if(!settings.action){const o=document.createElement('option');o.value='';o.textContent='选择动作演示';o.disabled=true;sel.prepend(o);}sel.value=settings.action||'';sel.onchange=()=>set('action',sel.value).catch(()=>{});row.append(label,sel);groups.motion.append(row);const note=document.createElement('p');note.className='hint';note.textContent=current.adapter==='fish'?'群体模式保留原有 30 条鱼的独立游动与互动。':'动作来自原工作台，选择后在当前场景演示。';info.append(note);}else{const note=document.createElement('p');note.className='hint';note.textContent='当前版本提供静态形体与参数检查。';groups.motion.append(note);}
 for(const d of controls){if(settings.displayStage==='turntable'&&(d.section==='scene'||d.key==='environment'||d.key==='stage'))continue;const group=groups[d.uiGroup]||groups.extensions;group.append(parameterField(d,settings[d.key]??d.value,{set,delay:current.adapter==='native'?220:45,format}));}
 groups.extensions.open=!controls.some(d=>d.commonId&&d.section!=='studio');extTitle.textContent+=' · '+(groups.extensions.children.length-1);for(const [key,group]of Object.entries(groups)){group.dataset.group=key;if(group.children.length>1)mount.append(group);}
 const detail=document.createElement('details');detail.className='source-details';detail.dataset.group='source';const summary=document.createElement('summary');summary.textContent='来源与导出说明';detail.append(summary);const text=document.createElement('p');text.textContent=current.version+' · '+(assets[current.asset]?.source||'已有动物工作台')+'。模型保留原项目的来源边界与待验收状态。GLB 输出当前姿态与基础 PBR 材质；自定义着色器和原动作保留在 HTML 中。';detail.append(text);mount.append(detail);
 const reset=section('保存与恢复','06');reset.dataset.group='reset';const buttons=document.createElement('div');buttons.className='motion-buttons';const r=document.createElement('button');r.id='reset-parameters';r.textContent='恢复初始参数';r.onclick=()=>{delete saved[current.id];persist();selectAnimal(current.id,{reset:true});};const save=document.createElement('button');save.textContent='导出参数配方';save.onclick=()=>downloadRecipe();buttons.append(r,save);reset.append(buttons);if(current.imported){const remove=document.createElement('button');remove.className='remove-import';remove.textContent='删除这份导入乐谱';remove.onclick=()=>deleteCurrentScore();reset.append(remove);}mount.append(reset);
}
function format(value,d){return Number(value).toFixed(d.step>=1?0:d.step>=.1?1:2);}
function updateFavorite(){const active=!!current&&favorites.has(current.id);$('favorite').textContent=active?'★ 已收藏':'☆ 添加收藏';$('favorite').classList.toggle('active',active);$('favorite').setAttribute('aria-pressed',String(active));$('favorite').setAttribute('aria-label',active?'取消收藏当前动物':'收藏当前动物');}
function updateStudio(){$('rotate-toggle').disabled=!loaded||settings.displayStage!=='turntable';$('rotate-toggle').textContent=settings.studioRotate?'Ⅱ 暂停环绕':'↻ 自动环绕';$('habitat').textContent=settings.displayStage==='turntable'?'旋转展示台':current?.habitat||'';$('stage-label').textContent=(settings.displayStage==='turntable'?'旋转展示 · ':'实时三维 · ')+(current?.version||'');}
addEventListener('message',e=>{const m=e.data;if(e.source!==frame.contentWindow||m?.protocol!=='animal-atlas/1'||m.channel!==channel)return;if(m.type==='ready'){if(window.__ATLAS_LOADING__.last?.id===current.id)window.__ATLAS_LOADING__.last.readyMs=performance.now()-window.__ATLAS_LOADING__.last.started;loaded=true;clearTimeout(loadTimer);controls=m.controls;actions=m.actions;settings={...m.record};playing=settings.playing!==false;saved[current.id]={...settings};persist();$('loading').hidden=true;$('pause').disabled=!actions.length;$('export').disabled=false;$('runtime-status').textContent=actions.length?'LIVE / INTERACTIVE':'STATIC / PARAMETRIC';updatePause();renderControls();updateStudio();if(current.imported&&!thumbs[current.id]){const id=current.id;request('capture').then(r=>{thumbs[id]=r.image;importer.saveThumbnail(id,r.image);renderGrid();}).catch(()=>{});}const allowedViews=current.adapter==='life'?current.life==='bird'?[]:current.life==='shark'?['three','front','side']:['three','side','top']:['three','front','side','top'];document.querySelectorAll('.viewbar button').forEach(b=>b.hidden=!allowedViews.includes(b.dataset.view));if(current.adapter==='fish')$('interaction-hint').innerHTML='左键拖动观察 · 滚轮缩放<br>鱼群：点击产生扰动';else $('interaction-hint').innerHTML='左键拖动观察 · 滚轮缩放<br>拖动时暂停自动环绕';window.__ATLAS__={ready:true,current:current.id,select:selectAnimal,request,set,common:()=>commonDescription(current,controls,actions,settings,basicData()),setCommon,settings:()=>({...settings}),basicData:()=>basicData(),setBasic,catalog:ANIMALS,exportObject,makeRuntime:async()=>runtimeHtml(await decodeAsset(current.asset),current,settings),get controls(){return controls;},get actions(){return actions;}};}else if(m.type==='failure'&&!m.requestId)showError(m.error);if(m.requestId&&pending.has(m.requestId)){const p=pending.get(m.requestId);clearTimeout(p.timer);pending.delete(m.requestId);if(m.type==='failure')p.reject(Error(m.error));else p.resolve(m);}});
function download(name,data,mime){const blob=data instanceof Blob?data:new Blob([data],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function recipe(){return{schema:'animal-atlas/recipe@1',platformVersion:'1.2.0',basicData:basicData(),animalId:current.id,name:current.name,sourceVersion:current.version,sourceSha256:assets[current.asset]?.sha256,parameters:{...settings},exportedAt:new Date().toISOString()};}
function animalSource(a=current,params=settings){const r=importer.records.get(a.id);return{animalId:a.id,name:a.name,category:a.category,basicData:basicData(a),instrument:importer.instrumentFor(a),parameters:{...params},sourceVersion:a.version,sourceSha256:assets[a.asset]?.sha256,source:assets[a.asset]?.source||'用户导入的动物模块',...(r?.content?{content:r.content}:{}),...(r?.bake?{upstream:r.bake.source}:{}),exportedAt:new Date().toISOString()};}
async function liveBake(bake,a){const r=importer.records.get(a.id);if(r?.bake?.runtime){const old=r.bake.runtime,p=old.presentation||{scale:1,tint:[1,1,1],roughness:1},values=bake.source.parameters,c=values.tint||'#ffffff',t=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return {...bake,schema:'kaopu/bake@2',representation:{...bake.representation,kind:'current-form-with-original-life-runtime'},runtime:{...old,parameters:old.parameters||r.bake.source.parameters,presentation:{scale:p.scale*(values.scale??1),tint:p.tint.map((v,i)=>v*t[i]),roughness:p.roughness*(values.roughness??1)}}};}return makeLiveBake(bake,a,await decodeAsset(a.adapter==='imported'?'imported':a.asset),r?.glb?{glb:r.glb}:undefined);}
function downloadRecipe(){download(current.id+'.animal.json',JSON.stringify(recipe(),null,2),'application/json');toast('参数配方已导出，可重新导入继续编辑');}
async function exportObject(format=$('export-format').value){if(!loaded)return;const a=current,epoch=loadEpoch,params={...settings};$('export').disabled=true;$('export').innerHTML='<span>◌</span> 正在打包对象…';try{
 if(format==='json'){downloadRecipe();return;}if(format==='score'||format==='kaopu'){await importer.exportKaopu(format);return;}
 if(format==='html'){const html=runtimeHtml(await decodeAsset(a.asset),a,params);download(a.id+'.animal.html',html,'text/html');toast('已导出独立对象，保留当前参数、动作和原有材质');return;}
 const result=await request('mesh',{},180000);if(epoch!==loadEpoch)throw Error('对象已切换');if(format==='bake'||format==='static-bake'){download(a.id+'.kaopu-bake.json',stringifyData(format==='static-bake'?bakeAnimal(result.items,{...animalSource(a,params),...(result.instrumentState?{instrumentState:result.instrumentState}:{})}):await liveBake(bakeAnimal(result.items,{...animalSource(a,params),...(result.instrumentState?{instrumentState:result.instrumentState}:{})}),a)),'application/json');toast('已导出当前形态和参数，可导入排练台继续生命活动');return;}const metadata={...recipe(),source:assets[a.asset]?.source,objectScope:a.adapter==='fish'&&params.group?'selected-individual':'single-object',sourceRights:'Original project provenance and licenses retained; see standalone runtime and project source manifest'},glb=createGLB(result.items.map(m=>({...m,positions:Array.from(m.positions,v=>v*basicData(a).metersPerUnit)})),{...metadata,geometryUnits:"m"});download(a.id+'.glb',glb,'model/gltf-binary');window.__ATLAS_LAST_EXPORT__={animalId:a.id,bytes:glb.length,meshes:result.items.length,format:'glb'};toast('GLB 已导出 · 当前姿态 · '+(glb.length/1048576).toFixed(1)+' MB');
 }catch(e){if(e.message!=='对象已切换')toast('导出失败：'+e.message);throw e;}finally{if(epoch===loadEpoch){$('export').disabled=!loaded;$('export').innerHTML='<span>↓</span> 导出对象';}}}
$('search').oninput=()=>{query=$('search').value.trim().toLowerCase();renderGrid();};$('all-tab').onclick=()=>{favoritesOnly=false;$('all-tab').classList.add('active');$('favorite-tab').classList.remove('active');renderGrid();};$('favorite-tab').onclick=()=>{favoritesOnly=true;$('all-tab').classList.remove('active');$('favorite-tab').classList.add('active');renderGrid();};$('favorite').onclick=()=>current&&toggleFavorite(current.id);$('delete-score').onclick=()=>deleteCurrentScore();$('rotate-toggle').onclick=()=>set('studioRotate',!settings.studioRotate).catch(()=>{});$('deleted-tab').onclick=()=>{renderDeleted();$('deleted-dialog').showModal();};$('close-deleted').onclick=()=>$('deleted-dialog').close();$('pause').onclick=()=>set('playing',!playing).catch(()=>{});$('retry').onclick=()=>selectAnimal(current.id);$('export').onclick=()=>exportObject().catch(()=>{});$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('panel-toggle').onclick=()=>$('inspector').classList.toggle('open');for(const [id,tab]of [['object-panel-tab','object'],['studio-panel-tab','studio']])$(id).onclick=()=>{$('inspector').dataset.tab=tab;$('object-panel-tab').classList.toggle('active',tab==='object');$('studio-panel-tab').classList.toggle('active',tab==='studio');};
for(const b of document.querySelectorAll('.viewbar button'))b.onclick=()=>set('view',b.dataset.view).then(()=>document.querySelectorAll('.viewbar button').forEach(x=>x.classList.toggle('active',x===b))).catch(()=>{});
addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)&&loaded&&actions.length&&!$('help-dialog').open&&!$('import-dialog').open&&!$('deleted-dialog').open){e.preventDefault();set('playing',!playing).catch(()=>{});}});
importer=createImporter({assets,thumbs,basicData,setBasic,current:()=>current,settings:()=>settings,request,download,decode:decodeAsset,runtimeHtml,select:selectAvailable,render:()=>{renderNav();renderGrid();},apply:async(id,params)=>{removed.delete(id);saved[id]={...params};persist();await selectAnimal(id,{initial:params});},focusCategory:id=>{category=id;query='';$('search').value='';favoritesOnly=false;$('all-tab').classList.add('active');$('favorite-tab').classList.remove('active');},forget:id=>{delete saved[id];delete basicSaved[id];favorites.delete(id);persist();},toast});
window.__ATLAS_BOOT__={catalog:ANIMALS,select:selectAnimal,importer,visible:visibleAnimals,deleteScore:deleteCurrentScore};renderNav();renderGrid();importer.restore().finally(()=>selectAvailable('fish'));
const rehearsalButton=document.createElement('button');rehearsalButton.id='rehearsal-open';rehearsalButton.className='quiet';rehearsalButton.textContent='排练台';document.querySelector('.top-actions').prepend(rehearsalButton);
const bakeOption=document.createElement('option');bakeOption.value='bake';bakeOption.textContent='靠谱烘焙 · 形态与生命活动';$('export-format').prepend(bakeOption);$('export-format').value='bake';$('export-format').title='保存当前形态、参数与原动物运行器。导入排练台后继续原生动作；每份鱼包为当前选中的单体。';
initExportGuide({current:()=>current,record:id=>importer.records.get(id)});
const rehearsal=createRehearsal({visible:visibleAnimals,current:()=>current,ready:()=>loaded,request,saved:id=>({...saved[id]}),source:animalSource,basicData,decode:decodeAsset,runtimeHtml,download,liveBake});window.__ATLAS_REHEARSAL__=rehearsal;
const newRules=$('import-dialog').querySelector('tbody');for(const [name,rule]of [['内容封套 · .kaopu.json','kaopu/content@1：payload 是完整的已注册动物包；knowledge / extensions 保存动物模块提供的知识和扩展。仓库保留这些数据，不替动物模块解释生长规律。'],['靠谱烘焙 · .kaopu-bake.json','kaopu/bake@2：当前形态、参数与匹配版本的原动物运行器。排练台“导入对象 / 排练谱”继续原生动作；目录入口展示静态快照，保留活动包供再次导出。兼容 bake@1 静态形态，最多 200 万顶点，烘焙 JSON 上限 180 MiB。']]){const row=document.createElement('tr');for(const text of [name,rule]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}newRules.append(row);}
const rehearsalHelp=document.createElement('p');rehearsalHelp.textContent='右上角“排练台”把多个动物当前形态放入同一个三维场景，可调整位置、大小、光线，并编排跟随、接近、避让与围绕。生命活动由原动物运行器播放，位置关系由人工编排。排练台导出独立 HTML 或可再次导入的完整排练谱。仓库不推断生态关系。';$('help-dialog').append(rehearsalHelp);
