// At most two decompressed modules, 64 MiB of UTF-16 text, and one active decode.
// No persistent meshes, thumbnail substitutes, or hidden GPU runtime pool.
export function createAssetLoader(payload){
 const entries=new Map(),inflight=new Map();let bytes=0,worker,url,serial=0,fallbackQueue=Promise.resolve();const pending=new Map();
 const metrics={hits:0,decodes:0,joined:0};
 const decodeBytes=b64=>{if(Uint8Array.fromBase64)return Uint8Array.fromBase64(b64);const s=atob(b64),b=new Uint8Array(s.length);for(let i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return b;};
 async function local(packet){const unpack=async b64=>new Response(new Blob([decodeBytes(b64)]).stream().pipeThrough(new DecompressionStream('gzip'))).text();const text=await unpack(packet.data);if(!packet.base)return text;const base=await unpack(packet.base),parts=JSON.parse(text);return base.replace(',surfaces={},bindings={}',()=>',surfaces='+JSON.stringify(parts.surfaces)+',bindings='+JSON.stringify(parts.bindings));}
 function stop(){worker?.terminate();worker=null;if(url)URL.revokeObjectURL(url);url=null;}
 function getWorker(){if(worker)return worker;url=URL.createObjectURL(new Blob([`const decodeBytes=${decodeBytes.toString()},local=${local.toString()};let running=false;const queue=[];onmessage=async({data:m})=>{queue.push(m);if(running)return;running=true;while(queue.length){const job=queue.shift();try{postMessage({id:job.id,html:await local(job.data)});}catch(e){postMessage({id:job.id,error:e.message});}}running=false;};`],{type:'text/javascript'}));worker=new Worker(url);worker.onmessage=({data:m})=>{const p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(Error(m.error)):p.resolve(m.html);if(!pending.size)stop();};worker.onerror=()=>{for(const p of pending.values())p.reject(Error('解包线程无法启动'));pending.clear();stop();};return worker;}
 async function decode(key){if(entries.has(key)){metrics.hits++;const html=entries.get(key);entries.delete(key);entries.set(key,html);return html;}if(inflight.has(key)){metrics.joined++;return inflight.get(key);}const data=payload(key);if(!data)throw Error('缺少内嵌动物文件：'+key);metrics.decodes++;
  const promise=(async()=>{let html;try{const w=getWorker();html=await new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});try{w.postMessage({id,data});}catch(e){pending.delete(id);if(!pending.size)stop();reject(e);}});}catch{if(!worker)stop();const task=fallbackQueue.then(()=>local(data));fallbackQueue=task.catch(()=>{});html=await task;}const size=html.length*2;if(size<=64*1048576){while(entries.size>=2||bytes+size>64*1048576){const id=entries.keys().next().value;bytes-=entries.get(id).length*2;entries.delete(id);}entries.set(key,html);bytes+=size;}return html;})();inflight.set(key,promise);try{return await promise;}finally{inflight.delete(key);}
 }
 return{decode,stats:()=>({...metrics,entries:entries.size,textBytes:bytes,inflight:inflight.size,workerActive:!!worker}),clear(){entries.clear();bytes=0;}};
}
