import {createBeach} from './beach.js';
import * as T from '../vendor/three.module.js';
const cache=new WeakMap();
globalThis.AtlasBeach={create:createBeach,
 prepareRaw(canvas,gl,force=false){if(!force&&globalThis.__ATLAS_CONTEXT&&(globalThis.__ATLAS_CONTEXT.initial?.displayStage||'turntable')==='turntable'){const beach={group:new T.Group(),stats:{deferred:true}};beach.group.name='atlas-tidewater-beach';window.__ATLAS_BEACH=beach;cache.set(gl,{beach,pending:()=>this.prepareRaw(canvas,gl,true)});return;}const renderer=new T.WebGLRenderer({canvas,context:gl,antialias:true});renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;const scene=new T.Scene(),beach=createBeach(T,scene),camera=new T.PerspectiveCamera(42,1,.004,1800);camera.matrixAutoUpdate=false;camera.matrixWorldAutoUpdate=false;
 const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),gradient=ctx.createRadialGradient(64,64,4,64,64,64);gradient.addColorStop(0,'rgba(28,32,24,.38)');gradient.addColorStop(.5,'rgba(28,32,24,.2)');gradient.addColorStop(1,'rgba(28,32,24,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const shadow=new T.Mesh(new T.PlaneGeometry(1.6,.85),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.007;shadow.renderOrder=1;beach.group.add(shadow);
 cache.set(gl,{renderer,scene,beach,camera,shadow,rotation:new T.Matrix4().makeRotationX(Math.PI/2)});renderer.resetState();},
 drawRaw(gl,m){let q=cache.get(gl);if(q?.pending){if(globalThis.AtlasTurntable?.isActive()!==false||q.beach.group.visible===false)return;q.pending();q=cache.get(gl);}if(!q||q.beach.group.visible===false)return;const {renderer,camera,rotation,beach}=q;renderer.resetState();renderer.setSize(gl.canvas.width,gl.canvas.height,false);camera.projectionMatrix.fromArray(m.projection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();camera.matrixWorldInverse.fromArray(m.view).multiply(rotation);camera.matrixWorld.copy(camera.matrixWorldInverse).invert();camera.position.setFromMatrixPosition(camera.matrixWorld);camera.near=m.near;camera.far=m.far;const root=window.__CAT_V440_METRICS__?.rootPosition||[0,0,0];q.shadow.position.set(root[0],-.007,-root[1]);beach.update(performance.now()/1000,camera);renderer.render(q.scene,camera);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,gl.canvas.width,gl.canvas.height);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.depthMask(true);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST);gl.bindVertexArray(null);for(let i=0;i<8;i++)gl.bindSampler(i,null);}
};
