/* Tidewater terrain / rock geometry: Copyright (c) 2026 DRG Software Solutions LLC.
 * MIT license retained in vendor/tidewater/LICENSE. Atlas shading and vegetation are procedural. */
import {TerrainData} from '../vendor/tidewater/src/world/TerrainData.js';
import {Noise2D,smoothstep} from '../vendor/tidewater/src/util/Noise.js';
import {buildRockGeometry} from '../vendor/tidewater/src/world/terrain/RockGeometry.js';

const noiseGLSL=`float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=mat2(.8,-.6,.6,.8)*p*2.03;a*=.5;}return v;}`;
export function createBeach(T,scene,{activityRadius=3.4,lighting=true}={}){
 const group=new T.Group();group.name='atlas-tidewater-beach';group.userData.environment=true;scene.add(group);
 const terrain=Object.create(TerrainData.prototype);terrain.noise=new Noise2D(7);terrain.noise2=new Noise2D(222);terrain.noise3=new Noise2D(934);terrain._F={};terrain._out={};
 const scale=.35,anchor={x:18,z:-64},base=terrain.heightFn(anchor.x,anchor.z).h,seaY=-base*scale-.015;
 function sample(x,z){const wx=x/scale+anchor.x,wz=-z/scale+anchor.z,F=terrain._fields(wx,wz,true),a=terrain._base(wx,wz,F,terrain._out);let h=a.h,add=0;
  // Original bay detail equations, evaluated analytically instead of a 2048² island grid.
  if(a.bz>.05){if(a.d<0){const e=-a.d,cusp=Math.sin((wx+terrain.noise.noise(wx/60,3.3)*9)*(2*Math.PI/24));add+=cusp*.09*smoothstep(4,12,e)*(1-smoothstep(20,32,e));add+=.14*Math.exp(-Math.pow((e-38)/5,2));}else{add+=(Math.exp(-Math.pow((a.d-44)/10,2))*.28-Math.exp(-Math.pow((a.d-26)/9,2))*.31)*(.7+.3*terrain.noise.noise(wx/50,7.7))*smoothstep(5,15,a.d);}h+=add*a.bz;}
  h=(h-base)*scale-.015;const flat=1-smoothstep(activityRadius,activityRadius+1.9,Math.hypot(x,z));h=h*(1-flat)-.015*flat;return {h,d:a.d*scale,rock:a.rock};
 }
 const terrainG=new T.PlaneGeometry(230,230,192,192);terrainG.rotateX(-Math.PI/2);const p=terrainG.attributes.position,colors=new Float32Array(p.count*3),c=new T.Color(),dry=new T.Color('#d8c8a6'),wet=new T.Color('#94816a'),rockC=new T.Color('#65714b');
 for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),s=sample(x,z);p.setY(i,s.h);const wetness=1-smoothstep(seaY+.1,seaY+.68,s.h),variation=.9+.12*terrain.noise.noise(x*2,z*2);c.copy(dry).lerp(wet,wetness*.82).lerp(rockC,s.rock*.8);c.multiplyScalar(variation);c.toArray(colors,i*3);}terrainG.setAttribute('color',new T.BufferAttribute(colors,3));terrainG.computeVertexNormals();
 const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d'),im=ctx.createImageData(256,256);let seed=713;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296;};for(let i=0;i<im.data.length;i+=4){const v=Math.round(100+rnd()*125);im.data.set([v,v,v,255],i);}ctx.putImageData(im,0,0);const grain=new T.CanvasTexture(canvas);grain.wrapS=grain.wrapT=T.RepeatWrapping;grain.repeat.set(440,440);grain.anisotropy=4;
 const floorMat=new T.MeshStandardMaterial({vertexColors:true,roughness:.9,bumpMap:grain,bumpScale:.018,roughnessMap:grain});const ground=new T.Mesh(terrainG,floorMat);ground.name='tidewater-bay-sand';ground.receiveShadow=true;group.add(ground);
 const time={value:0};const groundData=new Float32Array(p.count*4);for(let i=0;i<p.count;i++){groundData[i*4]=p.getY(i);groundData[i*4+3]=1;}const groundTex=new T.DataTexture(groundData,193,193,T.RGBAFormat,T.FloatType);groundTex.minFilter=groundTex.magFilter=T.LinearFilter;groundTex.needsUpdate=true;
 floorMat.onBeforeCompile=shader=>{shader.uniforms.atlasTime=time;shader.uniforms.atlasSea={value:seaY};shader.vertexShader='varying vec3 atlasGround;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\natlasGround=(modelMatrix*vec4(transformed,1.)).xyz;');shader.fragmentShader='uniform float atlasTime,atlasSea;varying vec3 atlasGround;\n'+shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat wetEdge=atlasSea+.17+.06*sin(atlasTime*.84);float wetSand=1.-smoothstep(wetEdge-.03,wetEdge+.2,atlasGround.y);diffuseColor.rgb*=1.-.24*wetSand;').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor=mix(roughnessFactor,.34,wetSand*.8);');};
 const waterMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time,groundTex:{value:groundTex},farPatch:{value:1},seaY:{value:seaY}},vertexShader:`uniform float time,seaY;uniform sampler2D groundTex;varying vec3 wp;
float wave(vec2 p,float t){return sin(dot(p,vec2(.18,.92))*1.4-t*.9)*.045+sin(dot(p,vec2(-.55,.7))*2.5-t*1.36)*.018+sin(dot(p,vec2(.75,.4))*4.3+t*1.8)*.008;}
void main(){vec3 w=(modelMatrix*vec4(position,1.)).xyz;float ground=texture2D(groundTex,vec2((w.x+115.)/230.,(w.z+115.)/230.)).r;float depth=max(0.,seaY-ground);float phase=w.z*1.15+time*.85+sin(w.x*.14)*.35;float surf=pow(max(0.,sin(phase)),6.)*exp(-pow((depth-.45)/.45,2.))*.17;w.y+=wave(w.xz,time)*smoothstep(0.,.6,depth)+surf;wp=w;gl_Position=projectionMatrix*viewMatrix*vec4(w,1.);}`,fragmentShader:`uniform float time,seaY,farPatch;uniform sampler2D groundTex;varying vec3 wp;${noiseGLSL}
void main(){if(farPatch>.5&&abs(wp.x)<90.&&wp.z>-80.&&wp.z<20.)discard;float ground=texture2D(groundTex,clamp(vec2((wp.x+115.)/230.,(wp.z+115.)/230.),0.,1.)).r;float depth=max(.001,seaY-ground);float phase=fract(time/7.5+wp.x*.002);float uprush=phase<.4?sin(phase/.4*1.570796):pow(max(0.,1.-(phase-.4)/.55),1.6);float sheet=seaY+.05+uprush*.12;float covered=1.-smoothstep(sheet-.018,sheet+.012,ground);if(covered<.005)discard;
float surfPhase=wp.z*1.15+time*.85+sin(wp.x*.14)*.35;float breaker=pow(max(0.,sin(surfPhase)),12.)*exp(-pow((depth-.46)/.4,2.));float cells=fbm(wp.xz*11.+vec2(time*.4,-time*.6));float edge=exp(-abs(ground-sheet)*65.);float foam=clamp(breaker*(.35+.65*cells)+edge*(.32+.68*cells),0.,1.);
vec2 n=vec2(cos(dot(wp.xz,vec2(.18,.92))*1.4-time*.9)*.058+cos(dot(wp.xz,vec2(-.55,.7))*2.5-time*1.36)*.037,sin(dot(wp.xz,vec2(.75,.4))*4.3+time*1.8)*.042);n+=vec2(noise(wp.xz*8.+time*.2)-.5,noise(wp.xz*8.+11.+time*.2)-.5)*.05;
vec3 N=normalize(vec3(n.x,1.,n.y)),V=normalize(cameraPosition-wp);float fres=pow(1.-max(dot(V,N),0.),4.);vec3 col=mix(vec3(.045,.36,.29),vec3(.009,.085,.14),1.-exp(-depth*.42));col=mix(col,vec3(.20,.43,.62),fres*.5);vec3 sun=normalize(vec3(-.5,.65,-.4));float glitter=pow(max(dot(reflect(-sun,N),V),0.),200.);col+=vec3(1.,.84,.62)*glitter*.32;col=mix(col,vec3(.83,.91,.86),foam*.86);gl_FragColor=vec4(col,mix(.45,.99,clamp(depth*1.2+foam,0.,1.))*covered);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});
 const ocean=new T.Mesh(new T.PlaneGeometry(1400,1400,64,64).rotateX(-Math.PI/2),waterMat);ocean.position.set(0,seaY+.025,-480);ocean.name='atlas-ocean';ocean.renderOrder=3;group.add(ocean);
 const nearMat=waterMat.clone();nearMat.uniforms.time=time;nearMat.uniforms.farPatch.value=0;const surf=new T.Mesh(new T.PlaneGeometry(180,100,200,128).rotateX(-Math.PI/2),nearMat);surf.position.set(0,seaY+.025,-30);surf.name='atlas-shore-waves';surf.renderOrder=3;group.add(surf);
 const skyMat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{time},vertexShader:`varying vec3 dir;void main(){dir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 dir;uniform float time;${noiseGLSL}void main(){vec3 D=normalize(dir);float h=max(D.y,0.);vec3 col=mix(vec3(.38,.64,.78),vec3(.035,.18,.42),pow(h,.4));float sun=pow(max(dot(D,normalize(vec3(-.5,.65,-.4))),0.),850.);col+=sun*vec3(1.,.84,.59)*2.;vec2 cloudUV=D.xz/max(.14,D.y)*.7+vec2(time*.002,0.);float clouds=smoothstep(.55,.78,fbm(cloudUV))*smoothstep(.02,.14,D.y)*(1.-smoothstep(.6,.88,D.y));col=mix(col,vec3(.96,.94,.86),clouds*.8);gl_FragColor=vec4(col,1.);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});const sky=new T.Mesh(new T.SphereGeometry(1200,48,24),skyMat);sky.name='atlas-coastal-sky';sky.frustumCulled=false;group.add(sky);scene.background=new T.Color('#b8d5df');scene.fog=new T.Fog('#bfd2d2',75,330);
 const rockMaterials=[0,1,2].map((i)=>new T.MeshStandardMaterial({color:['#8a8571','#696c5b','#a09a85'][i],roughness:.96,vertexColors:true}));let rocks=0;
 for(let i=0;i<54;i++){const a=rnd()*Math.PI*2,d=5.7+rnd()*35,x=Math.sin(a)*d,z=Math.cos(a)*d;if(z<-6&&Math.abs(x)<9)continue;const y=sample(x,z).h;if(y<seaY-.5)continue;const r=new T.Mesh(buildRockGeometry(T,i%4,77+i,3),rockMaterials[i%3]),size=.18+rnd()*1.1;r.scale.setScalar(size);r.position.set(x,y+size*.34,z);r.rotation.y=rnd()*6.28;const rp=r.geometry.attributes.position,rn=r.geometry.attributes.normal,ao=r.geometry.attributes.ao,rc=new Float32Array(rp.count*3),stone=new T.Color();for(let v=0;v<rp.count;v++){const x=rp.getX(v),y=rp.getY(v),z=rp.getZ(v),grainTone=.86+.16*terrain.noise2.noise(x*12+i,z*12+y*3),moss=smoothstep(.45,.85,rn.getY(v))*smoothstep(-.1,.5,terrain.noise3.noise(x*7+i,z*7))*.38;stone.set('#b6af98').lerp(new T.Color('#758051'),moss).multiplyScalar(grainTone*(.7+.3*ao.getX(v)));stone.toArray(rc,v*3);}r.geometry.setAttribute('color',new T.BufferAttribute(rc,3));r.castShadow=r.receiveShadow=true;r.name='tidewater-weathered-rock';group.add(r);rocks++;}
 const leafMat=new T.MeshStandardMaterial({color:'#597a37',roughness:.8,side:T.DoubleSide});const trunkMat=new T.MeshStandardMaterial({color:'#8b8064',roughness:1});let blades=0;const leafPositions=[];
 // Curved palm leaflets and bent trunks, authored here without downloaded foliage.
 for(const [x,z,height]of [[-8,3,5.4],[10,1,6.2],[-15,-4,7],[16,-9,6.4],[7,10,5.6]]){const y=sample(x,z).h,curve=new T.CatmullRomCurve3([new T.Vector3(x,y,z),new T.Vector3(x+.12,y+height*.35,z+.05),new T.Vector3(x+.5,y+height*.75,z-.2),new T.Vector3(x+.7,y+height,z-.5)]),trunk=new T.Mesh(new T.TubeGeometry(curve,24,.11,9,false),trunkMat);trunk.castShadow=true;group.add(trunk);const top=curve.getPoint(1);
  for(let j=0;j<10;j++){const a=j/10*Math.PI*2,axis=new T.Vector3(Math.cos(a),0,Math.sin(a)),pts=[];for(let k=0;k<=12;k++){const t=k/12;pts.push(top.clone().addScaledVector(axis,t*2.4).add(new T.Vector3(0,Math.sin(t*Math.PI)*.45-t*t*.75,0)));}const stem=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),12,.018,4,false),leafMat);group.add(stem);for(let k=2;k<12;k++){const t=k/12,len=Math.sin(t*Math.PI)*.62;for(const side of [-1,1]){const p=pts[k],cross=new T.Vector3(-axis.z,0,axis.x),end=p.clone().addScaledVector(cross,len*side).addScaledVector(axis,.2).add(new T.Vector3(0,-.12,0)),vertices=[p.x-.04*axis.x,p.y,p.z-.04*axis.z,p.x+.04*axis.x,p.y,p.z+.04*axis.z,end.x,end.y,end.z];leafPositions.push(...vertices);}}}
 }
 const palmLeaves=new T.BufferGeometry();palmLeaves.setAttribute('position',new T.Float32BufferAttribute(leafPositions,3));palmLeaves.computeVertexNormals();const canopy=new T.Mesh(palmLeaves,leafMat);canopy.castShadow=true;group.add(canopy);
 const grassPos=[],grassCol=[];for(let i=0;i<1500;i++){const x=(rnd()-.5)*65,z=(rnd()-.45)*45;if(Math.hypot(x,z)<activityRadius+2)continue;const s=sample(x,z);if(s.h<seaY+.38)continue;const h=.18+rnd()*.5,a=rnd()*6.28,w=.012+rnd()*.026,bx=x+Math.sin(a)*h*.35,bz=z+Math.cos(a)*h*.35;grassPos.push(x-w,s.h,z,x+w,s.h,z,bx,s.h+h,bz);for(let j=0;j<3;j++)grassCol.push(.16+rnd()*.1,.24+rnd()*.12,.05+rnd()*.04);blades++;}const grassG=new T.BufferGeometry();grassG.setAttribute('position',new T.Float32BufferAttribute(grassPos,3));grassG.setAttribute('color',new T.Float32BufferAttribute(grassCol,3));grassG.computeVertexNormals();group.add(new T.Mesh(grassG,new T.MeshStandardMaterial({vertexColors:true,roughness:1,side:T.DoubleSide})));
 if(lighting){scene.add(new T.HemisphereLight('#d7edff','#bda67d',1.05));const sun=new T.DirectionalLight('#fff0ce',3.2);sun.position.set(-9,14,-8);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.5,far:60});sun.shadow.normalBias=.02;sun.shadow.bias=-.0001;scene.add(sun,sun.target);}
 const api={group,seaY,sample,terrain,update(t,camera){time.value=t;sky.position.copy(camera.position);},stats:{source:'https://github.com/dgreenheck/tidewater',terrainVertices:p.count,rocks,grassBlades:blades,proceduralTextures:1,externalAssets:0}};window.__ATLAS_BEACH=api;return api;
}
