(function(){'use strict';
const context=window.__ATLAS_CONTEXT||{},kind=context.adapter,$=id=>document.getElementById(id),record={},channel=context.channel,send=(type,data)=>{if(parent!==window)parent.postMessage({protocol:'animal-atlas/1',channel,type,...data},'*');};
const event=(id,value,type='input')=>{const el=$(id);if(!el)throw Error('参数不存在：'+id);if(el.type==='checkbox')el.checked=!!value;else el.value=String(value);el.dispatchEvent(new Event(type,{bubbles:true}));};
const click=selector=>{const el=document.querySelector(selector);if(!el)throw Error('当前工作台不支持该操作');el.click();};
const range=(key,label,min,max,step,value,section='appearance')=>({key,label,type:'range',min,max,step,value:Number(value),section});
const check=(key,label,value,section='display')=>({key,label,type:'checkbox',value:!!value,section});
const select=(key,label,options,value,section='motion')=>({key,label,type:'select',options:options.map(x=>Array.isArray(x)?{value:String(x[0]),label:x[1]}:x),value:String(value),section});
function domRange(id,label,section='appearance'){const el=$(id);return el&&range(id,label,+el.min,+el.max,+el.step||.01,+el.value,section);}
let defs=[],actions=[],ready=false,selectionStage,studio,demo;const sourceMaterials=new Map();
function life(){return window.__LIFE_VISUAL;}
function roots(){if(kind==='imported')return __ATLAS_IMPORTED.meshes();if(kind==='native')return __ATLAS_NATIVE.meshes();if(kind==='life')return[life().animal.root];if(kind==='palau')return[selectionStage.rig.group];if(kind==='crab')return[__CRAB_QA__.meshes[context.key==='coconut'?1:0]];if(kind==='chicken')return window.__ATLAS_CHICKEN_MESHES();return[];}
function readyCheck(){return kind==='imported'?window.__ATLAS_IMPORTED?.ready:kind==='fish'?window.__KAOPU_R13__?.ready:kind==='native'?window.__ATLAS_NATIVE?.ready:kind==='life'?life()?.ready:kind==='cat'?!!window.__CAT_V440_READY__&&window.__CAT_V440_READY__!=='static-fallback':kind==='eagle'?window.__READY__===true:kind==='crab'?window.__CRAB_QA__?.ready:kind==='palau'?window.ready===true:kind==='chicken'?window.__CHICKEN_V46_READY__===true:false;}
let presentationSuspended=false,presentationInstalled=false;
function suspendPresentation(value){
 if(!presentationInstalled){presentationInstalled=true;const wrap=(object,key)=>{if(typeof object?.[key]!=='function')return;const original=object[key];object[key]=function(...args){if(!presentationSuspended)return original.apply(this,args);};};
 const renderers=[window.__ATLAS_IMPORTED?.renderer,window.__ATLAS_NATIVE?.renderer,window.__LIFE_VISUAL?.renderer,window.__CRAB_QA__?.renderer,window.__ATLAS_CHICKEN_STAGE?.renderer,...(window.birdWorkbench?.getStages().map(s=>s.renderer)||[])].filter(Boolean);for(const renderer of renderers)wrap(renderer,'render');
 if(kind==='fish'){wrap(__KAOPU_R13__.renderer,'draw');wrap(__KAOPU_R13__.renderer,'uploadPoses');}if(kind==='eagle')wrap(eagle,'render');
 }
 presentationSuspended=!!value;return presentationSuspended;
}
function setup(){
send('progress',{phase:3});
if(kind==='imported'){const n=__ATLAS_IMPORTED;actions=n.actions;record.action=n.state.action;defs=AtlasParameterSchema.profileControls('imported',{}, {actions:!!actions.length});if(!actions.length)delete record.action;record.playing=true;
}else if(kind==='fish'){
 const r=__KAOPU_R13__.renderer;r.setSchool(false);r.camera.yaw=-.65;r.camera.pitch=.17;r.camera.halfWidth=.63;
 actions=Object.entries(r.h.metadata.motion.modes).map(([id,v])=>({id,label:v.labelZh||v.label||id}));
 record.action=r.state.mode;defs=[check('group','显示鱼群 · 30 条',false,'motion'),domRange('speed','动作速度','motion'),domRange('amplitude','推进强度','motion'),domRange('swing','摆动幅度','motion'),range('bodyScale','整体尺寸',.8,1.2,.02,1),range('brightness','色调明暗',.8,1.2,.02,1),domRange('eyeYaw','视线左右'),domRange('eyePitch','视线上下'),domRange('pupil','瞳孔偏置'),range('waterDensity','水体浓度',.45,1.5,.05,1,'scene'),range('lightRays','水下光柱',0,1.5,.05,.85,'scene'),range('waterBloom','光晕强度',0,.5,.02,.18,'scene'),range('kelpDensity','海草密度',0,1,.05,1,'scene'),check('environment','海底场景',true),check('wire','线框检查',false),select('renderMode','表面显示',[['0','自然表面'],['1','白模'],['2','法线'],['5','鱼鳍权重']],0,'display')];
 r.__atlasVariants=r.school.fish.map(f=>({scale:f.variant.scale.slice(),brightness:f.variant.brightness,tint:f.variant.tint.slice()}));
}else if(kind==='native'){
 const n=__ATLAS_NATIVE;defs=AtlasParameterSchema.profileControls('native',{color:'#'+n.state.color,roughness:n.state.roughness},{mammal:context.engine==='mammal'});
}else if(kind==='life'){
 const ec=window.LifeEcologyRuntime;if(ec){actions=(ec.activityCatalog()||[]).map(a=>({id:a.id,label:a.label||a.name||a.id}));}
 const api=window.__LIFE_VISUAL_SOURCE?.api;if(context.life==='shark')event('cameraMode','follow','change');else if(document.querySelector('[data-view="close"]'))click('[data-view="close"]');
 if(window.__ATLAS_BEACH&&!Object.keys(context.initial||{}).length){ec?.setHour(11.5);ec?.setWeather('clear');}const sourceCamera=window.__LIFE_VISUAL_SOURCE?.camera?.();if(window.__ATLAS_BEACH&&sourceCamera){sourceCamera.pitch=.13;sourceCamera.distance*=1.12;}const settings=life().settings;defs=[range('hour','光照时间',5,20,.25,ec?.summary().hour??10.5,'scene'),range('exposure','曝光',.55,1.55,.05,settings.exposure,'scene'),select('quality','渲染品质',[['preview','预览'],['high','高品质'],['cinematic','精细']],settings.quality,'display'),check('ao','接触遮蔽',settings.ao),check('bones','骨架检查',false)];
 life().animal.root.traverse(o=>{for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m&&!sourceMaterials.has(m))sourceMaterials.set(m,{color:m.color?.clone(),roughness:m.roughness});});
 if(life().referenceWater||context.life==='shark')defs.push(check('environment','海底场景',true,'scene'),range('waterDensity','水体浓度',.45,1.5,.05,1,'scene'),range('lightRays','水下光柱',0,1.5,.05,.85,'scene'),range('kelpDensity','海草密度',0,1,.05,1,'scene'));if(window.__ATLAS_BEACH||['pig','bruce','cat'].includes(context.life))defs.push(check('environment','沙滩场景',true,'scene'));defs.push(range('coatTone','体表色调',.85,1.15,.02,1),range('coatRoughness','体表粗糙度',.75,1.1,.02,1));ec?.setSkeleton(false);record.playing=!ec?.summary().paused;
 if($('weather')||$('ecWeather')){const e=$('weather')||$('ecWeather');defs.push(select('weather','环境天气',[...e.options].map(o=>[o.value,o.textContent]),e.value,'scene'));}
 for(const [id,label,section]of [['paceSlider','步态速度','motion'],['jawPreview','张口角度','appearance'],['wind','林地风速','scene']])if($(id))defs.push(domRange(id,label,section));
 if($('doveInspectionMode'))defs.push(select('doveInspectionMode','羽毛与结构',[...$('doveInspectionMode').options].map(o=>[o.value,o.textContent]),'all','display'));
}else if(kind==='cat'){
 actions=[...document.querySelectorAll('[data-action]')].map(b=>({id:b.dataset.action,label:b.textContent.trim()}));
 record.action=__CAT_V440_METRICS__.action;record.playing=$('pause').textContent!=='继续';if($('contacts').classList.contains('active'))$('contacts').click();
 defs=[check('environment','沙滩场景',true,'scene'),domRange('speed','动作速度','motion'),check('autoExpression','自动视线与耳朵',true,'appearance'),domRange('gazeYaw','视线左右'),domRange('gazePitch','视线上下'),domRange('earLeft','左耳角度'),domRange('earRight','右耳角度'),domRange('furStrength','短毛强度'),check('skeleton','骨架检查',false),check('contacts','脚掌接触检查',false)];
}else if(kind==='eagle'){
 const e=window.eagle;$('autoplay').checked=false;actions=[...document.querySelectorAll('[data-action]')].map(b=>({id:b.dataset.action,label:b.querySelector('b')?.textContent||b.childNodes[0]?.textContent?.trim()||b.textContent.trim()}));
 record.action=e.action;record.playing=e.playing;
 defs=[domRange('speed','动作速度','motion'),...Object.entries(e.motion.controls||{}).map(([key,c])=>range('control:'+key,c.label||c.labelZh||key,c.min,c.max,c.step||.01,c.value??c.default??0,'appearance')),check('bones','控制骨架',false)];
}else if(kind==='crab'){
 const q=__CRAB_QA__;click('[data-mode="'+context.key+'"]');event('skin-target',context.key,'change');actions=[...document.querySelectorAll('[data-behavior]')].map(b=>({id:b.dataset.behavior,label:b.textContent.trim()}));const current=q.skinControls.getSelection()[context.key];
 defs=[select('skin','甲壳花色',q.skinControls.library.skins.filter(s=>s.kind===context.key).map(s=>[s.id,s.label]),current.skinId,'appearance'),domRange('tone','颜色深浅'),domRange('variation','细斑对比'),domRange('detail','颗粒肌理'),domRange('gloss','甲壳光泽'),domRange('speed','动作速度','motion'),select('stage','展示环境',[['beach','海滩生活'],['lab','形体观察']],q.state.stage,'scene'),check('bones','骨架检查',false)];
 record.action=q.state.behavior;record.playing=!q.state.paused;
}else if(kind==='palau'){
 selectionStage=birdWorkbench.getStages().find(s=>s.id===context.key);birdWorkbench.getStages().forEach(s=>{s.renderer.domElement.parentElement.style.setProperty('display',s===selectionStage?'block':'none','important');});
 const c=selectionStage.renderer.domElement;c.style.width='100%';c.style.height='100%';selectionStage.scene.background=null;selectionStage.renderer.setClearColor(0x456467);
 const resize=()=>{selectionStage.renderer.setSize(innerWidth,innerHeight,false);const a=innerWidth/innerHeight;selectionStage.camera.left=-.78*a;selectionStage.camera.right=.78*a;selectionStage.camera.top=.78;selectionStage.camera.bottom=-.78;selectionStage.camera.updateProjectionMatrix();birdWorkbench.setTime(birdWorkbench.getState().time);};new ResizeObserver(resize).observe(document.body);resize();
 actions=[...$('motion').options].map(o=>({id:o.value,label:o.textContent}));defs=[select('speed','播放速度',[['.25','0.25×'],['.5','0.5×'],['1','1×']],1,'motion'),select('zoom','对象放大',[['1','1×'],['1.3','1.3×'],['1.7','1.7×']],1,'display'),check('bones','骨架检查',false),check('regions','身体分区',false),check('wire','线框检查',false)];
 record.action=birdWorkbench.getState().source;record.playing=birdWorkbench.getState().playing;
}else if(kind==='chicken'){
 const api=window.__CHICKEN_V46_API__,labels={body_width:'躯干宽度',body_depth:'躯干厚度',neck_fullness:'颈部丰满度',head_scale:'头部大小',beak_length:'喙部长度',tail_root_length:'尾根长度',comb_height:'鸡冠高度',comb_thickness:'鸡冠厚度',wing_length:'翅膀长度',wing_fullness:'翅膀丰满度',eye_scale:'眼球大小',soft_tissue_scale:'肉垂大小',leg_thickness:'小腿粗细',foot_scale:'足部大小',toe_spread:'脚趾展开'};defs=[check('environment','沙滩场景',true,'scene'),...api.parameterDefinitions().map(p=>range('chicken:'+p.id,p.label||labels[p.id]||p.id,p.min,p.max,.01,p.default)),range('micro','皮肤微细节',0,1.5,.05,1),range('contrast','羽毛对比',0,1.5,.05,1)];
}
demo=window.__ATLAS_DEMO?AtlasDemoAdapter(context,roots):null;if(demo)defs.push(...AtlasParameterSchema.demonstrationControls());
studio=AtlasStudioAdapter(context,range,check,select);defs=AtlasParameterSchema.decorateControls([...studio.controls,...defs].filter(Boolean),context);actions=actions.filter((a,i,all)=>a.id&&all.findIndex(b=>b.id===a.id)===i);for(const d of defs)record[d.key]=d.value;
if('environment'in record)record.environment=false;if(kind==='crab')record.stage='lab';ready=true;if(kind==='fish'){__KAOPU_R13__.renderer.__atlasRecord=record;const r=__KAOPU_R13__.renderer,advance=r.advance.bind(r);r.advance=dt=>advance(dt*(window.__ATLAS_DEMO?.activity??1));}
if(demo){updateDemo();const renderers=[window.__ATLAS_IMPORTED?.renderer,window.__ATLAS_NATIVE?.renderer,window.__LIFE_VISUAL?.renderer,window.__CRAB_QA__?.renderer,window.__ATLAS_CHICKEN_STAGE?.renderer,...(window.birdWorkbench?.getStages().map(s=>s.renderer)||[])].filter(Boolean);for(const r of renderers){const render=r.render.bind(r);r.render=(...args)=>{demo.apply();return render(...args);};}}
for(const [key,value]of Object.entries(context.initial||{}))if(key!=='playing'&&(defs.some(d=>d.key===key)||['action','view'].includes(key)))set(key,value);if('playing'in(context.initial||{}))set('playing',context.initial.playing);
window.AnimalRuntime={version:'animal-atlas/1',ready:true,suspendPresentation,stageBinding:()=>({kind,roots:roots(),sourceUnitsPerDisplayUnit:kind==='imported'&&context.geometryUnits==='source-units'?1/__ATLAS_IMPORTED.info().normalization:1,zUp:kind==='palau'}),describe:()=>({schema:'kaopu/runtime@1',parameterSchema:AtlasParameterSchema.PARAMETER_SCHEMA,animalId:context.id,name:context.name,basicData:context.basicData||null,instrument:context.instrument||{id:'atlas/'+kind,version:context.version},controls:defs.map(d=>({...d,value:record[d.key]})),actions:[...actions],capabilities:{parameters:true,actions:!!actions.length,bakeCurrentPose:true,originalLifeRuntime:true,customShaderPortable:false}}),configuration:()=>({...record}),demonstration:()=>demo?.snapshot()||null,set,playAction:id=>set('action',id),pause:()=>set('playing',false),resume:()=>set('playing',true),meshes:exportMeshes,bake:async()=>({schema:'kaopu/mesh-snapshot@1',animalId:context.id,parameters:{...record},items:await exportMeshes()})};
requestAnimationFrame(()=>send('ready',{controls:defs.map(d=>({...d,value:record[d.key]})),actions,record}));
}
function updateDemo(){demo?.set({age:record.demoAge,maturity:record.demoMaturity,size:record.demoSize,condition:record.demoCondition,health:record.demoHealth,color:record.demoTint});}
function set(key,value){
 const def=defs.find(d=>d.key===key);if(!def&&!['action','playing','view'].includes(key))throw Error('未知动物参数');if(def)value=AtlasParameterSchema.controlValue(def,value,{clamp:true});
 if(key.startsWith('demo')){record[key]=value;updateDemo();if(kind==='eagle')eagle.dirty=true;studio.render();return{...record};}
 if(key==='displayStage'||key.startsWith('studio')){if(key==='displayStage')value='turntable';if(key==='studioLightAngle')value=35;studio.set(key,value);record[key]=value;return{...record};}
 if(['waterDensity','lightRays','waterBloom','kelpDensity'].includes(key)){record[key]=value;return{...record};}if(key==='environment'){record[key]=false;return{...record};}if(key==='stage'&&kind==='crab'){__CRAB_QA__.stage('lab');record[key]='lab';return{...record};}
 demo?.resetBase();
if(key==='action'){
 if(!actions.some(a=>a.id===value))throw Error('该动物尚不支持这个动作');
 if(kind==='imported')__ATLAS_IMPORTED.set('action',value);else if(kind==='fish')__KAOPU_R13__.renderer.setMode(value);else if(kind==='life')LifeEcologyRuntime.runActivity(value,{replace:true});else if(kind==='cat'||kind==='eagle')click('[data-action="'+value+'"]');else if(kind==='crab')__CRAB_QA__.behavior(value);else if(kind==='palau')birdWorkbench.setSource(value);
 set('playing',true);
 }else if(key==='playing'){
 value=!!value;if(kind==='imported')__ATLAS_IMPORTED.set('playing',value);else if(kind==='fish')__KAOPU_R13__.renderer.state.playing=value;else if(kind==='native')__ATLAS_NATIVE.state.playing=value;else if(kind==='palau')birdWorkbench[value?'play':'pause']();else if(kind==='eagle'){eagle.playing=value;eagle.dirty=true;}else if(kind==='crab')__CRAB_QA__.state.paused=!value;else if(kind==='cat'){const paused=__CAT_V440_METRICS__?$('pause').textContent==='继续':false;if(paused===value)$('pause').click();}else if(kind==='life'){window.__ATLAS_PAUSED=!value;const ec=LifeEcologyRuntime;ec[value?'resume':'pause']();const api=window.__LIFE_VISUAL_SOURCE?.api;const lab=context.life==='shark'?window.SHARK_LAB:context.life==='pig'?window.PIG_LAB:context.life==='cat'?window.CAT_LAB:api;if(lab?.runtime)lab.runtime.paused=!value;if(lab?.state)lab.state.paused=!value;}
 }else if(key==='view'){studio.resetView();
 if(kind==='imported')__ATLAS_IMPORTED.view(value);else if(kind==='native')__ATLAS_NATIVE.view(value);else if(kind==='eagle')eagle.setView(value==='side'?'left':value);else if(kind==='fish'){const map={three:'perspective',front:'head',side:'left',top:'top'};__KAOPU_R13__.renderer.camera.setView(map[value]||value);}else if(kind==='cat'){const map={three:'quarter',side:'left'};click('[data-view="'+(map[value]||value)+'"]');}else if(kind==='palau'){const map={three:'threequarter'};event('view',map[value]||value,'change');}else if(kind==='crab'){const map={three:'perspective',side:'left'};click('[data-view="'+(map[value]||value)+'"]');}else if(kind==='chicken'){const map={three:'threeQuarter',side:'left'};click('[data-view="'+(map[value]||value)+'"]');}else if(kind==='life'){if(context.life==='shark')event('cameraMode',value==='side'?'side':value==='front'?'head':'follow','change');else if(document.querySelector('[data-view="'+(value==='three'?'close':value==='front'?'close':value)+'"]'))click('[data-view="'+(value==='three'?'close':value==='front'?'close':value)+'"]');else{const api=window.__LIFE_VISUAL_SOURCE?.api;api?.setView?.(value==='three'?'close':value);}}
 }else if(kind==='imported')__ATLAS_IMPORTED.set(key,value);
 else if(kind==='native')__ATLAS_NATIVE.set(key,value);
 else if(kind==='fish'){
 const r=__KAOPU_R13__.renderer;if(key==='group'){const c=r.camera,lens={target:[...c.target],yaw:c.yaw,pitch:c.pitch,halfWidth:c.halfWidth,distance:c.distance,zoom:c.zoom,upMode:c.upMode};r.setSchool(value);Object.assign(c,lens);}else if(key==='mode')r.setMode(value);else if(key==='brightness'||key==='bodyScale'){r.school.fish.forEach((f,i)=>{const v=r.__atlasVariants[i];if(key==='brightness')f.variant.brightness=v.brightness*value;else f.variant.scale=v.scale.map(x=>x*value);});}else if(['environment','waterDensity','lightRays','waterBloom','kelpDensity'].includes(key))r.state[key]=value;else if(key==='renderMode')event(key,value,'change');else event(key,value);
 }else if(kind==='life'){
 const ec=LifeEcologyRuntime;if(life().referenceWater&&['environment','waterDensity','lightRays','kelpDensity'].includes(key))life().referenceWater.state[key]=value;else if(key==='environment'&&window.__ATLAS_BEACH)__ATLAS_BEACH.group.visible=value;else if(key==='coatTone'||key==='coatRoughness'){for(const [m,original]of sourceMaterials){if(key==='coatTone'&&original.color)m.color.copy(original.color).multiplyScalar(value);if(key==='coatRoughness'&&original.roughness!==undefined)m.roughness=Math.min(1,original.roughness*value);}}else if(key==='hour')ec.setHour(value);else if(key==='weather')ec.setWeather(value);else if(key==='quality'){ec.setQuality(value);life().settings.quality=value;}else if(key==='exposure'||key==='ao')life().settings[key]=value;else if(key==='bones'){ec.setSkeleton(value);life().settings.inspection=value;}else event(key,value,key==='doveInspectionMode'?'change':'input');
 }else if(kind==='cat'){
 if(key==='autoExpression'){window.__CAT_V440_SET_EXPRESSION__({auto:value});}else if(['skeleton','contacts'].includes(key)){if(record[key]!==value)$(key).click();}else event(key,value);
 }else if(kind==='eagle'){
 if(key.startsWith('control:'))eagle.setControl(key.slice(8),Number(value));else if(key==='bones'){eagle.showBones=value;eagle.dirty=true;}else event(key,value);
 }else if(kind==='crab'){
 const q=__CRAB_QA__;if(key==='skin')q.skinControls.select(context.key,value);else if(key==='stage')q.stage(value);else if(key==='bones'){const b=document.querySelector('[data-overlay="bones"]')||$('bones');if(b){if(b.type==='checkbox')event(b.id,value,'change');else b.click();}else{(q.scenes||[]).forEach(s=>s.traverse(o=>{if(o.type==='SkeletonHelper')o.visible=value;}));q.state.skeleton=value;q.beach.scene.traverse(o=>{if(o.type==='SkeletonHelper')o.visible=value;});}}else event(key,value);
 }else if(kind==='palau')event(key,value,'change');
 else if(kind==='chicken'){
 if(key.startsWith('chicken:')){window.__CHICKEN_V46_API__.setParam(key.slice(8),Number(value));}else{const e=document.querySelector('[data-appearance="'+key+'"]');if(e){e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));}}
 }
 record[key]=value;demo?.apply();return{...record};
}
function bakeRoot(root){
 root.updateMatrixWorld(true);const items=[];root.traverse(o=>{if(!o.isMesh||!o.geometry?.attributes.position||!o.visible)return;let p=o.parent;while(p){if(!p.visible)return;p=p.parent;}const g=o.geometry,attr=g.attributes.position,colors=g.attributes.color,uv=g.attributes.uv,normal=g.attributes.normal;
 const matrices=o.isInstancedMesh?Array.from({length:o.count},(_,i)=>{const m=o.matrixWorld.clone();const temp=m.clone();o.getMatrixAt(i,temp);return m.multiply(temp);}):[o.matrixWorld];
 for(let instance=0;instance<matrices.length;instance++){const mat=matrices[instance],positions=new Float32Array(attr.count*3),c=colors?new Float32Array(attr.count*3):undefined,u=uv?new Float32Array(attr.count*2):undefined,v=root.position.clone();for(let i=0;i<attr.count;i++){if(o.getVertexPosition)o.getVertexPosition(i,v);else v.fromBufferAttribute(attr,i);v.applyMatrix4(mat);positions.set(v.toArray(),i*3);if(c)c.set([colors.getX(i),colors.getY(i),colors.getZ(i)],i*3);if(u)u.set([uv.getX(i),uv.getY(i)],i*2);}const fullIndex=g.index?new Uint32Array(g.index.array):Uint32Array.from({length:attr.count},(_,i)=>i),groups=g.groups.length?g.groups:[{start:0,count:fullIndex.length,materialIndex:0}];for(const group of groups){const start=Math.max(group.start,g.drawRange.start),end=Math.min(group.start+group.count,fullIndex.length,g.drawRange.start+g.drawRange.count);if(end<=start)continue;const m=Array.isArray(o.material)?o.material[group.materialIndex]:o.material;if(!m||m.visible===false)continue;items.push({name:o.name||context.name,positions,colors:c,uv:u,indices:fullIndex.slice(start,end),material:{color:m.color?.toArray()||m.uniforms?.uAtlasDemoTint?.value.toArray()||[1,1,1],roughness:m.roughness??.8,metalness:m.metalness??0,opacity:m.opacity??1,doubleSided:m.side===2}});}}
 });return items;
}
function dqBake(positions,joints,weights,real,dual){const out=new Float32Array(positions.length);for(let i=0;i<positions.length/3;i++){const rr=[0,0,0,0],dd=[0,0,0,0],base=joints[i*4]*4,ref=real.subarray(base,base+4);for(let k=0;k<4;k++){const w=weights[i*4+k],j=joints[i*4+k]*4,sign=ref.reduce((s,v,t)=>s+v*real[j+t],0)<0?-1:1;for(let t=0;t<4;t++){rr[t]+=w*real[j+t]*sign;dd[t]+=w*dual[j+t]*sign;}}const len=Math.hypot(...rr)||1;for(let t=0;t<4;t++){rr[t]/=len;dd[t]/=len;}const [x,y,z,w]=rr,[dx,dy,dz,dw]=dd,p=positions.subarray(i*3,i*3+3),cx=y*p[2]-z*p[1],cy=z*p[0]-x*p[2],cz=x*p[1]-y*p[0];out[i*3]=p[0]+2*(w*cx+y*cz-z*cy)+2*(-dw*x+dx*w-dy*z+dz*y);out[i*3+1]=p[1]+2*(w*cy+z*cx-x*cz)+2*(-dw*y+dy*w-dz*x+dx*z);out[i*3+2]=p[2]+2*(w*cz+x*cy-y*cx)+2*(-dw*z+dz*w-dx*y+dy*x);}return out;}
async function exportMeshes(){
 demo?.apply();
 if(kind==='cat'){const m=window.__ATLAS_CAT_MESH__(),metrics=__CAT_V440_METRICS__,p=new Float32Array(__CAT_V440_EXPORT_EXPRESSED_POSITIONS__(metrics.action,metrics.time));for(let i=0;i<p.length;i+=3){const y=p[i+1];p[i+1]=p[i+2];p[i+2]=-y;}const items=[{name:context.name,positions:p,indices:new Uint32Array(m.idx),material:{color:[.33,.29,.25],roughness:.88,metalness:0}}];return demo?demo.bakeRaw(items):items;}
 if(kind==='eagle'){const e=eagle;const items=[{name:context.name,positions:dqBake(e.positions,e.joints,e.weights,e.rig.real,e.rig.dual),colors:new Float32Array(e.colors).map(v=>v/255),indices:e.indices.slice(),material:{color:[1,1,1],roughness:.85,metalness:0,doubleSided:true}}];return demo?demo.bakeRaw(items):items;}
 if(kind==='fish'){
 if(window.__ATLAS_FISH_CPU_SNAPSHOT__)return window.__ATLAS_FISH_CPU_SNAPSHOT__();
 const r=__KAOPU_R13__.renderer,A=__KAOPU_R13__.instrument,gl=r.gl,h=r.h;const read=(buffer,ctor,length)=>{const a=new ctor(length);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.getBufferSubData(gl.ARRAY_BUFFER,0,a);return a;},count=h.metadata.package?.vertices||497701,pos=read(r.buffers[0],Float32Array,count*3),weights=read(r.buffers[3],Uint8Array,count*12),info=read(r.buffers[4],Uint16Array,count*2),partRoot=read(r.buffers[5],Float32Array,count*3),uvRaw=read(r.buffers[2],Uint16Array,count*2),uv=new Float32Array(uvRaw.length),out=new Float32Array(pos.length),indices=new Uint32Array(r.indexCount);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,r.index);gl.getBufferSubData(gl.ELEMENT_ARRAY_BUFFER,0,indices);const variant=r.school.fish[r.state.selected].variant;for(let i=0;i<count;i++){const point=A.deformMaterial(h,pos.subarray(i*3,i*3+3),[0,1,0],null,weights.subarray(i*12,i*12+12),info.subarray(i*2,i*2+2),partRoot.subarray(i*3,i*3+3),true).position;for(let k=0;k<3;k++)out[i*3+k]=point[k]*variant.scale[k];}for(let i=0;i<uv.length;i++)uv[i]=i%2?1-uvRaw[i]/65535:uvRaw[i]/65535;const tex=window.__ATLAS_FISH_TEXTURE_BYTES__;return[{name:context.name,positions:out,uv,indices,texture:tex,textureMime:'image/jpeg',material:{color:variant.tint.map(v=>v*variant.brightness),roughness:.6,metalness:0,doubleSided:true}}];
 }
 let items=roots().flatMap(bakeRoot);if(kind==='imported'&&context.geometryUnits==='source-units'){const f=__ATLAS_IMPORTED.info().normalization;for(const item of items)for(let i=0;i<item.positions.length;i++)item.positions[i]/=f;}if(kind==='palau')for(const item of items)for(let i=0;i<item.positions.length;i+=3){const y=item.positions[i+1];item.positions[i+1]=item.positions[i+2];item.positions[i+2]=-y;}
 if(!items.length)throw Error('没有可以导出的对象网格');return items;
}
async function capture(){const cs=[...document.querySelectorAll('canvas')].filter(c=>c.clientWidth>2&&c.clientHeight>2);const canvas=kind==='palau'?selectionStage.renderer.domElement:cs.sort((a,b)=>b.width*b.height-a.width*a.height)[0];if(!canvas)throw Error('画布未就绪');if(kind==='imported')__ATLAS_IMPORTED.renderer.render(__ATLAS_IMPORTED.scene,__ATLAS_IMPORTED.camera);else if(kind==='native')__ATLAS_NATIVE.renderer.render(__ATLAS_NATIVE.scene,__ATLAS_NATIVE.camera);else if(kind==='life')life().render();else if(kind==='palau')birdWorkbench.setTime(birdWorkbench.getState().time);else if(kind==='eagle')eagle.render();else if(kind==='cat')await new Promise(requestAnimationFrame);else if(kind==='fish'){const r=__KAOPU_R13__.renderer;r.uploadPoses();r.draw(0,0,r.canvas.width,r.canvas.height,true);}else if(kind==='chicken'){const n=__ATLAS_CHICKEN_STAGE;n.renderer.render(n.scene,n.camera);}else if(kind==='crab'){await new Promise(requestAnimationFrame);const q=__CRAB_QA__,i=context.key==='coconut'?1:0;q.renderer.render(q.state.stage==='beach'?q.beach.scene:q.scenes[i],q.state.stage==='beach'?q.beachCamera:q.cameras[i]);}const dst=document.createElement('canvas');dst.width=360;dst.height=270;const ctx=dst.getContext('2d');ctx.drawImage(canvas,0,0,360,270);return dst.toDataURL('image/jpeg',.85);}
addEventListener('message',async e=>{const m=e.data;if(e.source!==parent||m?.protocol!=='animal-atlas/1'||m.channel!==channel||!ready)return;try{if(m.type==='set'){set(m.key,m.value);send('applied',{requestId:m.requestId,key:m.key,value:record[m.key],record});}else if(m.type==='capture')send('capture',{requestId:m.requestId,image:await capture()});else if(m.type==='mesh')send('mesh',{requestId:m.requestId,items:await exportMeshes(),...(kind==='fish'?{instrumentState:{selected:__KAOPU_R13__.renderer.state.selected,variant:__KAOPU_R13__.renderer.school.fish[__KAOPU_R13__.renderer.state.selected].variant}}:{})});else if(m.type==='snapshot')send('snapshot',{requestId:m.requestId,record,...(kind==='native'?{notation:__ATLAS_NATIVE.source.score}:{})});}catch(e){send('failure',{requestId:m.requestId,error:e.message});}});
addEventListener('error',e=>{if(!ready)send('failure',{error:e.message||'乐器初始化失败'});});
let tries=0;let wait;const checkReady=()=>{if(ready)return;if(window.__ATLAS_IMPORT_ERROR){clearInterval(wait);send('failure',{error:window.__ATLAS_IMPORT_ERROR});return;}if(readyCheck()){clearInterval(wait);try{setup();}catch(e){console.error('Atlas adapter:',e);send('failure',{error:e.message});}}else if(++tries>5625){clearInterval(wait);send('failure',{error:'当前动物加载超时。请重新选择。'});}};globalThis.__ATLAS_READY_CHECK__=checkReady;wait=setInterval(checkReady,16);checkReady();
})();

