export function createGLB(items,metadata){
 if(!items?.length)throw Error('没有模型数据');
 const json={asset:{version:'2.0',generator:'Animal Atlas 1.0'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],buffers:[{byteLength:0}],bufferViews:[],accessors:[],extras:{...metadata,units:'metre',upAxis:'Y',exportMode:'current-pose',animationIncluded:false,materialScope:'PBR base colour and vertex colour; custom procedural shaders require the standalone runtime'}};
 const chunks=[],encoder=new TextEncoder(),pad=(n)=>Math.ceil(n/4)*4;let length=0;
 function view(bytes,target){const index=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset:length,byteLength:bytes.byteLength,...(target?{target}:{} )});const chunk=new Uint8Array(pad(bytes.byteLength));chunk.set(new Uint8Array(bytes.buffer,bytes.byteOffset,bytes.byteLength));chunks.push(chunk);length+=chunk.byteLength;return index;}
 function accessor(array,type,componentType,count,bounds){const index=json.accessors.length;json.accessors.push({bufferView:view(array,type==='SCALAR'?34963:34962),componentType,count,type,...bounds});return index;}
 let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const item of items)for(let i=0;i<item.positions.length;i+=3)for(let k=0;k<3;k++){const v=item.positions[i+k];if(!Number.isFinite(v))throw Error('模型含无效顶点，已停止导出');min[k]=Math.min(min[k],v);max[k]=Math.max(max[k],v);}
 const origin=[(min[0]+max[0])/2,min[1],(min[2]+max[2])/2];json.extras.originalWorldOrigin=origin;json.extras.boundsMetres=max.map((v,k)=>v-min[k]);
 for(const item of items){
 const positions=new Float32Array(item.positions),indices=new Uint32Array(item.indices),count=positions.length/3;for(let i=0;i<positions.length;i+=3)for(let k=0;k<3;k++)positions[i+k]-=origin[k];for(const i of indices)if(i>=count)throw Error('网格索引越界');
 const low=[Infinity,Infinity,Infinity],high=[-Infinity,-Infinity,-Infinity];for(let i=0;i<positions.length;i+=3)for(let k=0;k<3;k++){low[k]=Math.min(low[k],positions[i+k]);high[k]=Math.max(high[k],positions[i+k]);}
 const attributes={POSITION:accessor(positions,'VEC3',5126,count,{min:low,max:high})},normals=new Float32Array(positions.length);
 for(let i=0;i<indices.length;i+=3){const a=indices[i]*3,b=indices[i+1]*3,c=indices[i+2]*3,ux=positions[b]-positions[a],uy=positions[b+1]-positions[a+1],uz=positions[b+2]-positions[a+2],vx=positions[c]-positions[a],vy=positions[c+1]-positions[a+1],vz=positions[c+2]-positions[a+2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;for(const j of[a,b,c]){normals[j]+=nx;normals[j+1]+=ny;normals[j+2]+=nz;}}
 for(let i=0;i<normals.length;i+=3){const n=Math.hypot(normals[i],normals[i+1],normals[i+2])||1;normals[i]/=n;normals[i+1]/=n;normals[i+2]/=n;}attributes.NORMAL=accessor(normals,'VEC3',5126,count);
 if(item.colors){const color=new Float32Array(item.colors);for(let i=0;i<color.length;i++)color[i]=Math.max(0,Math.min(1,color[i]));attributes.COLOR_0=accessor(color,'VEC3',5126,count);}
 if(item.uv)attributes.TEXCOORD_0=accessor(new Float32Array(item.uv),'VEC2',5126,count);
 const m=item.material||{},material={name:item.name||metadata.name,pbrMetallicRoughness:{baseColorFactor:[...(m.color||[1,1,1]).map(x=>Math.max(0,Math.min(1,x))),m.opacity??1],roughnessFactor:m.roughness??.8,metallicFactor:m.metalness??0},doubleSided:!!m.doubleSided};if(m.opacity<1)material.alphaMode='BLEND';
 if(item.texture?.length&&item.uv){json.images??=[];json.textures??=[];const image=json.images.length;json.images.push({bufferView:view(new Uint8Array(item.texture)),mimeType:item.textureMime||'image/jpeg'});json.textures.push({source:image});material.pbrMetallicRoughness.baseColorTexture={index:json.textures.length-1};}
 const materialIndex=json.materials.length;json.materials.push(material);const meshIndex=json.meshes.length;json.meshes.push({name:item.name||metadata.name,primitives:[{attributes,indices:accessor(indices,'SCALAR',5125,indices.length),material:materialIndex,mode:4}]});json.scenes[0].nodes.push(json.nodes.length);json.nodes.push({mesh:meshIndex,name:item.name||metadata.name});
 }
 json.buffers[0].byteLength=length;const encoded=encoder.encode(JSON.stringify(json)),j=new Uint8Array(pad(encoded.length));j.fill(32);j.set(encoded);const output=new Uint8Array(12+8+j.length+8+length),d=new DataView(output.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,output.length,true);d.setUint32(12,j.length,true);d.setUint32(16,0x4e4f534a,true);output.set(j,20);const b=20+j.length;d.setUint32(b,length,true);d.setUint32(b+4,0x004e4942,true);let offset=b+8;for(const chunk of chunks){output.set(chunk,offset);offset+=chunk.length;}return output;
}
