import {ENGINES,MAX_FILE,plain,parameters,compatible,sha,base64,unbase64,validateGLB,validateSettings,storeImports} from './kaopu.js';
import {ANIMALS,CATEGORIES} from './catalog.js';
import {validateBake} from './baked.js';
import {createGLB} from './glb.js';
const $=id=>document.getElementById(id),db=storeImports(),records=new Map(),persistedIds=new Set(),json=x=>JSON.stringify(x).replace(/</g,'\\u003c');
export function createImporter(api){
 let candidate=null,previewToken=0,busy=false,persistent=true,cancelPreview;
 const status=(text,error=false)=>{$('import-status').textContent=text;$('import-status').classList.toggle('error',error);};
 const instrumentFor=a=>a.instrument||(a.adapter==='native'?ENGINES[a.engine==='quad'?'K4':'K5']:{id:'atlas/'+a.adapter,version:a.version,assetSha256:api.assets[a.asset]?.sha256});
 function install(r){if(!r.thumbnail&&api.thumbs[r.id])r.thumbnail=api.thumbs[r.id];const index=ANIMALS.findIndex(a=>a.id===r.id);if(index<0)ANIMALS.push(r.animal);else if(ANIMALS[index].imported)ANIMALS[index]=r.animal;records.set(r.id,r);if(r.glb)api.assets[r.animal.asset]={source:r.sourceFile||'用户导入的内嵌 GLB',sha256:r.animal.instrument.assetSha256};if(r.thumbnail)api.thumbs[r.id]=r.thumbnail;}
 async function restore(){try{for(const r of await db.all())if(r.animal?.imported&&r.id===r.animal.id&&(r.glb||r.animal.notation)){install(r);persistedIds.add(r.id);}}catch{persistent=false;}api.render();}
 async function runtimeAsset(key){const r=[...records.values()].find(r=>r.animal.asset===key);if(!r?.glb)return null;return (await api.decode('imported')).replace('</body>','<script type="application/json" id="instrument-data">'+json({glb:r.glb})+'</script></body>');}
 function categoryOptions(){for(const c of CATEGORIES.filter(c=>c.id!=='all')){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;$('import-category').append(o);}}
 function open(){if(!$('import-dialog').open)$('import-dialog').showModal();}
 function clear(){previewToken++;cancelPreview?.();cancelPreview=null;candidate=null;$('import-preview').srcdoc='';$('import-preview').hidden=true;$('import-commit').disabled=true;$('import-name').disabled=$('import-category').disabled=true;$('import-draft').hidden=true;}
 function close(){clear();busy=false;$('import-file').disabled=false;$('import-dialog').close();}
 async function makeGLB(bytes,meta={}){validateGLB(bytes);const digest=await sha(bytes),id='import-glb-'+digest.slice(0,24),instrument={...ENGINES.GLB,assetSha256:digest};return{animal:{id,name:meta.name||'导入动物',en:'IMPORTED GLB',category:meta.category||'land',asset:id,adapter:'imported',version:'靠谱 GLB 乐器 V1',description:'用户导入的内嵌 GLB；保留源模型材质、骨架和已有动作片段。',habitat:'沙滩展示台',tags:['导入动物','GLB'],imported:true,instrument,capability:'没有动作片段的 GLB 为静态模型；不自动生成年龄、生长或程序化骨架。'},glb:base64(bytes),sourceFile:meta.sourceFile,parameters:{}};}
 async function makeNotation(text,meta={}){text=String(text).trim();const format=text.slice(0,2);if(!ENGINES[format]||format==='GLB'||!text.startsWith(format+'|')||text.length>100000)throw Error('需要以 K4| 或 K5| 开头的完整程序化动物谱');const digest=await sha(new TextEncoder().encode(text)),id='import-'+format.toLowerCase()+'-'+digest.slice(0,24);return{animal:{id,name:meta.name||'导入程序化动物',en:'PROCEDURAL '+format,category:'land',asset:'native',adapter:'native',engine:format==='K4'?'quad':'mammal',notation:text,version:format+' 程序化乐器',description:'由注册的 '+format+' 乐器读取动物谱并生成几何；可继续调节材质与形体。',habitat:'沙滩展示台',tags:['导入动物','程序化谱'],imported:true,instrument:ENGINES[format],capability:'当前 K4/K5 乐器支持静态形体生成，不包含动作或生长模型。'},parameters:{}};}
 function existingScore(score){const a=ANIMALS.find(a=>a.id===score.animalId)||ANIMALS.find(a=>a.imported&&score.instrument?.assetSha256&&compatible(score.instrument,instrumentFor(a)));if(!a)throw Error('缺少这份乐谱对应的乐器模型；请先导入完整动物包或原 GLB');if(!compatible(score.instrument,instrumentFor(a)))throw Error('乐谱与当前乐器版本或模型指纹不一致');return{animal:{...a},parameters:parameters(score.parameters),existing:true};}
 async function parseFile(file){if(!file.size||file.size>MAX_FILE)throw Error('文件为空或超过 90 MiB；GLB 上限 64 MiB');const stem=file.name.replace(/\.(kaopu|score|animal)?\.?json$|\.glb$|\.score\.txt$|\.txt$/i,'').slice(0,60)||'导入动物';
  if(/\.glb$/i.test(file.name))return makeGLB(new Uint8Array(await file.arrayBuffer()),{name:stem,sourceFile:file.name});
  if(/\.txt$/i.test(file.name)){if(file.size>100000)throw Error('程序化谱文本超过 100 KB');return makeNotation(await file.text(),{name:stem});}
  if(!/\.json$/i.test(file.name))throw Error('首版支持 .glb、K4/K5 .txt 和本平台 .json；HTML、FBX、OBJ、外置 .gltf 暂不支持');let data;try{data=JSON.parse(await file.text());}catch{throw Error('JSON 无法解析，请检查文件是否完整');}if(!plain(data))throw Error('JSON 必须是动物包或乐谱对象');
  if(data.schema==='kaopu/content@1'){if(!plain(data.payload)||data.payload.schema!=='kaopu/animal@1'||(data.knowledge!==undefined&&!plain(data.knowledge))||(data.extensions!==undefined&&!plain(data.extensions)))throw Error('内容封套需包含有效动物包 payload；知识与扩展必须为对象');const r=await parseFile(new File([JSON.stringify(data.payload)],file.name,{type:'application/json'}));if(r.existing)throw Error('知识内容封套需要完整的独立动物谱或资源，不能只有内置工作台引用');r.content=Object.fromEntries(Object.entries(data).filter(([k])=>k!=='payload'));return r;}
  if(data.schema==='kaopu/bake@1'){validateBake(data);const r=await makeGLB(createGLB(data.meshes,data.source||{}),{name:data.animal.name,category:data.animal.category||'land',sourceFile:file.name});r.bake=data;r.animal.description='靠谱烘焙对象：当前形态的静态几何与基础材质；原动物参数和来源作为记录保留。';r.animal.tags=['靠谱烘焙','静态形态'];r.animal.capability='烘焙后不再包含原动物生成器或骨骼动作；继续生成形态请使用源乐器与乐谱。';return r;}
  if(data.schema==='animal-atlas/recipe@1'){const a=ANIMALS.find(a=>a.id===data.animalId);if(!a)throw Error('旧配方缺少对应动物，请先导入动物包');if(data.sourceSha256&&data.sourceSha256!==api.assets[a.asset]?.sha256)throw Error('旧配方的动物版本指纹不一致');return{animal:{...a},parameters:parameters(data.parameters),existing:true};}
  if(data.schema==='kaopu/score@1'){if(data.notation){const r=await makeNotation(data.notation,{name:data.name||stem});if(!compatible(data.instrument,r.animal.instrument))throw Error('程序化谱指定了不兼容的乐器版本');r.parameters=parameters(data.parameters);return r;}return existingScore(data);}
  if(data.schema!=='kaopu/animal@1'||!plain(data.animal)||data.score?.schema!=='kaopu/score@1')throw Error('未知格式；动物包 schema 应为 kaopu/animal@1，乐谱为 kaopu/score@1');if(!compatible(data.score.instrument,data.instrument))throw Error('动物包中的乐器与乐谱声明不一致');let r;
  if(data.asset?.format==='glb'){if(data.asset.encoding!=='base64')throw Error('GLB 动物包 encoding 需要为 base64');r=await makeGLB(unbase64(data.asset.data),data.animal);if(!compatible(data.instrument,r.animal.instrument))throw Error('GLB 模型指纹或乐器版本校验失败');}
  else if(data.score.notation){r=await makeNotation(data.score.notation,data.animal);if(!compatible(data.instrument,r.animal.instrument))throw Error('程序化乐器版本不匹配');}
  else if(data.asset?.format==='atlas-reference'){r=existingScore({...data.score,animalId:data.asset.animalId});}
  else throw Error('动物包缺少内嵌 GLB、程序化谱或已安装对象引用');r.parameters=parameters(data.score.parameters);return r;
 }
 async function preview(r,token){const frame=$('import-preview'),runtimeChannel='import-'+token+'-'+Math.random().toString(36).slice(2);const original=r.glb?(await api.decode('imported')).replace('</body>','<script type="application/json" id="instrument-data">'+json({glb:r.glb})+'</script></body>'):await api.decode(r.animal.asset);
  if(token!==previewToken)return null;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(Error('动物预览超时；请检查模型大小、谱格式或 WebGL 支持')),90000);function finish(error,m){clearTimeout(timer);removeEventListener('message',receive);cancelPreview=null;error?reject(error):resolve(m);}cancelPreview=()=>finish(Error('导入预览已取消'));function receive(e){const m=e.data;if(e.source!==frame.contentWindow||m?.protocol!=='animal-atlas/1'||m.channel!==runtimeChannel)return;if(m.type==='failure')finish(Error(m.error));else if(m.type==='ready'){try{validateSettings(r.parameters,m.controls,m.actions);finish(null,m);}catch(e){finish(e);}}}addEventListener('message',receive);frame.hidden=false;frame.srcdoc=api.runtimeHtml(original,r.animal,r.parameters,runtimeChannel);});
 }
 async function loadFile(file){if(busy)return;clear();const token=previewToken;busy=true;$('import-file').disabled=true;status('正在识别文件、校验乐器并生成三维预览…');try{const r=await parseFile(file);if(token!==previewToken)return;if(typeof r.animal.name!=='string'||r.animal.name.length>60||!CATEGORIES.some(c=>c.id===r.animal.category&&c.id!=='all'))throw Error('动物名称最多 60 字，分类需要选择已支持的大类');const ready=await preview(r,token);if(token!==previewToken)return;r.controls=ready.controls;r.actions=ready.actions;candidate=r;$('import-name').value=r.animal.name;$('import-category').value=r.animal.category;$('import-name').disabled=!!r.existing;$('import-category').disabled=!!r.existing||r.animal.adapter==='native';$('import-draft').hidden=false;$('import-commit').disabled=false;$('import-commit').textContent=r.existing?'应用乐谱到已有动物':'加入动物目录';$('import-engine').textContent=instrumentFor(r.animal).id+' · '+instrumentFor(r.animal).version;$('import-capabilities').textContent=r.actions.length?r.actions.length+' 个原有动作片段 · '+r.controls.length+' 个可调参数':'静态形体 · '+r.controls.length+' 个可调参数';status('验证通过。'+(r.existing?'这份乐谱将恢复对应对象的参数。':'可修改名称，再加入目录。'));}catch(e){if(token===previewToken){candidate=null;$('import-preview').hidden=true;status('导入失败：'+e.message,true);}}finally{if(token===previewToken){busy=false;$('import-file').disabled=false;}}}
 async function commit(){if(!candidate||busy)return;busy=true;$('import-commit').disabled=true;try{const r=candidate;if(!r.existing){const name=$('import-name').value.trim();if(!name||name.length>60)throw Error('动物名称需要 1 到 60 个字');r.animal.name=name;r.animal.category=$('import-category').value;r.id=r.animal.id;install(r);try{await db.put(r);persistedIds.add(r.id);}catch{persistent=false;}}await api.apply(r.animal.id,r.parameters);api.focusCategory(r.animal.category);api.render();$('import-dialog').close();clear();api.toast(r.existing?'乐谱已应用':persistent?'动物已加入目录，已保存在当前浏览器':'动物已加入本次会话；浏览器保存不可用，请导出靠谱动物包');}catch(e){status('加入失败：'+e.message,true);$('import-commit').disabled=false;}finally{busy=false;}}
 async function score(){const a=api.current(),snapshot=await api.request('snapshot');return{schema:'kaopu/score@1',instrument:instrumentFor(a),animalId:a.id,name:a.name,...(snapshot.notation?{notation:snapshot.notation}:{}),parameters:parameters(snapshot.record),exportedAt:new Date().toISOString()};}
 async function exportKaopu(format){const a=api.current(),s=await score();if(format==='score'){api.download(a.id+'.score.json',JSON.stringify(s,null,2),'application/json');api.toast(s.notation?'程序化乐谱已导出；内含动物谱与参数':'乐谱已导出；重新导入前需安装匹配的动物乐器');return;}const r=records.get(a.id),pack={schema:'kaopu/animal@1',animal:{name:a.name,category:a.category},instrument:s.instrument,...(r?.glb?{asset:{format:'glb',encoding:'base64',data:r.glb}}:!s.notation?{asset:{format:'atlas-reference',animalId:a.id}}:{}),score:s};api.download(a.id+'.kaopu.json',JSON.stringify(r?.content?{...r.content,payload:pack}:pack),'application/json');api.toast(r?.glb||s.notation?'靠谱动物包已导出，可导入同版乐器继续编辑':'已导出内置对象引用包；接收平台需要包含同版原工作台');}
 async function remove(id){const index=ANIMALS.findIndex(a=>a.id===id&&a.imported);if(index<0)return;if(persistedIds.has(id))try{await db.remove(id);persistedIds.delete(id);}catch{api.toast('浏览器无法删除保存记录，暂未移除动物');return;}const a=ANIMALS[index];ANIMALS.splice(index,1);records.delete(id);delete api.thumbs[id];if(a.adapter==='imported')delete api.assets[a.asset];api.forget(id);api.render();await api.select('fish');api.toast('导入动物已从当前浏览器目录移除');}
 categoryOptions();$('import-animal').onclick=()=>{status('选择文件后先验证和预览，通过后再加入动物目录。');open();};$('import-recipe').onclick=()=>{open();status('可以导入旧参数配方、新乐谱或完整动物包。');};$('close-import').onclick=close;$('import-dialog').addEventListener('cancel',e=>{e.preventDefault();close();});$('import-file').onchange=e=>{const f=e.target.files[0];e.target.value='';if(f)loadFile(f);};$('import-commit').onclick=commit;
 const drop=$('import-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover');};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');if(e.dataTransfer.files.length!==1){status('每次请导入一个文件。',true);return;}loadFile(e.dataTransfer.files[0]);};
 $('download-score-example').onclick=()=>api.download('example.score.json',JSON.stringify({schema:'kaopu/score@1',instrument:{id:'atlas/fish',version:ANIMALS[0].version,assetSha256:api.assets.fish.sha256},animalId:'fish',name:'大型鱼参数谱',parameters:{group:false,playing:true,waterDensity:1,lightRays:.85}},null,2),'application/json');
 $('download-package-example').onclick=()=>{const engine='K4',notation=window.ATLAS_EXAMPLE_NOTATION;api.download('example-tortoise.kaopu.json',JSON.stringify({schema:'kaopu/animal@1',animal:{name:'陆龟程序化谱示例',category:'land'},instrument:ENGINES[engine],score:{schema:'kaopu/score@1',instrument:ENGINES[engine],notation,parameters:{scale:1,environment:true}}},null,2),'application/json');};
 async function saveThumbnail(id,image){const r=records.get(id);if(!r)return;r.thumbnail=image;try{await db.put(r);}catch{persistent=false;}}
 return{restore,runtimeAsset,instrumentFor,exportKaopu,remove,saveThumbnail,records};
}
