import * as T from '../vendor/three.module.js';

import * as Mammal from '../vendor/mammal/src/instrument.js';
import * as Quad from '../vendor/quad/src/instrument.js';
import {SCORE_LIBRARY as MS} from '../vendor/mammal/src/scores.js';
import {SCORE_LIBRARY as QS} from '../vendor/quad/src/scores.js';
const config=window.__ATLAS_CONTEXT,engine=config.engine==='quad'?Quad:Mammal,source=config.notation?{score:config.notation,label:config.name,source:'用户导入程序化动物谱'}:(config.engine==='quad'?QS:MS)[config.key],canvas=document.querySelector('canvas');
const renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene(),beach={group:new T.Group(),update(){}};
const camera=new T.PerspectiveCamera(37,1,.015,1800),target=new T.Vector3(),state={scale:1,bulk:1,color:source.score.match(/\|M([0-9a-f]+)/i)[1],roughness:Number(source.score.match(/\|M[0-9a-f]+,([.\d]+)/i)[1]),wire:false,bones:false,environment:true,playing:true,speed:1};let current,radius=3,yaw=.65,pitch=.13,time=0,frames=0;
const initial=config.initial||{};
if(typeof initial.color==='string'&&/^#[0-9a-f]{6}$/i.test(initial.color))state.color=initial.color.slice(1);
for(const [key,min,max]of [['roughness',.45,1],...(config.engine==='mammal'?[['bulk',.92,1.08]]:[])])if(Number.isFinite(Number(initial[key])))state[key]=Math.max(min,Math.min(max,Number(initial[key])));
function score(){let text=source.score;const parts=text.split('|');parts[1]=parts[1].replace(/^M[0-9a-f]+,[.\d]+/i,'M'+state.color+','+state.roughness);if(config.engine==='mammal'&&state.bulk!==1){const i=parts.findIndex(x=>x[0]==='B'),v=parts[i].slice(1).split(',').map(Number);for(const k of [1,3,4,6,7,8])v[k]*=state.bulk;parts[i]='B'+v.join(',');}return parts.join('|');}
function cameraUpdate(){camera.position.set(target.x+radius*Math.cos(pitch)*Math.sin(yaw),target.y+radius*Math.sin(pitch),target.z+radius*Math.cos(pitch)*Math.cos(yaw));camera.lookAt(target);}
function fit(){const box=new T.Box3().setFromObject(current.root),sphere=box.getBoundingSphere(new T.Sphere());target.copy(sphere.center);const half=Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*Math.min(1,camera.aspect));radius=sphere.radius/Math.sin(half)*1.22;cameraUpdate();}
function rebuild(){const result=engine.buildScore(score());result.root.scale.setScalar(state.scale);result.root.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;o.material.wireframe=state.wire;}});if(current)engine.dispose(current.root);current=result;scene.add(result.root);fit();}
rebuild();
function resize(){const w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();fit();}addEventListener('resize',resize);resize();
let drag=null;canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.pan){target.x-=dx*.002*radius;target.y+=dy*.002*radius;}else{yaw-=dx*.006;pitch=Math.max(-.05,Math.min(1.5,pitch+dy*.006));}drag={...drag,x:e.clientX,y:e.clientY};cameraUpdate();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('wheel',e=>{e.preventDefault();radius=Math.max(.1,Math.min(30,radius*Math.exp(e.deltaY*.001)));cameraUpdate();},{passive:false});
window.__ATLAS_NATIVE={ready:true,T,renderer,scene,camera,state,source,current:()=>current,meshes:()=>[current.root],score,info:()=>({frames,triangles:engine.measure(current.root,current.score).triangles}),orbit(delta,elevation=0){yaw+=delta;pitch=Math.max(-1.48,Math.min(1.48,pitch+elevation));cameraUpdate();},set(key,value){if(key==='color'){const next=String(value).replace('#','');if(next!==state.color){state.color=next;rebuild();}}else if(key==='roughness'||key==='bulk'){if(state[key]!==Number(value)){state[key]=Number(value);rebuild();}}else if(key==='scale'){state.scale=Number(value);current.root.scale.setScalar(state.scale);fit();}else if(key==='wire'){state.wire=!!value;current.root.traverse(o=>{if(o.material)o.material.wireframe=state.wire;});}else if(key==='environment'){state.environment=!!value;scene.children.forEach(o=>{if(o===beach.group)o.visible=state.environment;});}else state[key]=value;},view(name){const views={front:[0,.12],side:[Math.PI/2,.14],top:[0,1.45],three:[.65,.26]};[yaw,pitch]=views[name]||views.three;fit();}};
renderer.setAnimationLoop(()=>{frames++;if(state.playing)time+=1/60*state.speed;cameraUpdate();beach.update(time,camera);renderer.render(scene,camera);});
