import * as T from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {validateBake,validateRehearsal} from './baked.js';
export const DEFAULT_LIGHT={ambient:1.3,key:3,exposure:1.05,angle:35,background:'#15252d'};
export class RehearsalViewer{
 constructor(mount,onUpdate=()=>{}){
  this.mount=mount;this.onUpdate=onUpdate;this.actors=[];this.assets=new Map();this.elapsed=0;this.playing=false;this.environment={...DEFAULT_LIGHT};this.urls=[];
  this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;mount.append(this.renderer.domElement);
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(42,1,.05,250);this.camera.position.set(9,7,12);this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.target.set(0,1,0);this.orbit.enableDamping=true;this.orbit.minDistance=2;this.orbit.maxDistance=70;
  this.hemi=new T.HemisphereLight('#dfefff','#728079',1);this.key=new T.DirectionalLight('#fff3df',3);this.key.castShadow=true;this.key.shadow.mapSize.set(2048,2048);this.key.shadow.camera.left=-16;this.key.shadow.camera.right=16;this.key.shadow.camera.top=16;this.key.shadow.camera.bottom=-16;this.key.shadow.camera.far=55;this.scene.add(this.hemi,this.key);
  const floor=new T.Mesh(new T.CylinderGeometry(15,15,.18,96),new T.MeshStandardMaterial({color:'#31454b',roughness:.94}));floor.position.y=-.095;floor.receiveShadow=true;this.scene.add(floor);this.grid=new T.GridHelper(30,30,'#637b7d','#3f565c');this.grid.position.y=.005;this.scene.add(this.grid);
  this.resize=()=>{const {width,height}=mount.getBoundingClientRect();this.renderer.setSize(Math.max(1,width),Math.max(1,height),false);this.camera.aspect=width/Math.max(1,height);this.camera.updateProjectionMatrix();};this.observer=new ResizeObserver(this.resize);this.observer.observe(mount);this.setLight(this.environment);
  let previous=performance.now(),lastReport=0;this.renderer.setAnimationLoop(now=>{const dt=Math.min(.06,(now-previous)/1000);previous=now;if(!mount.clientWidth)return;if(this.playing)this.step(dt);this.orbit.update();this.renderer.render(this.scene,this.camera);if(now-lastReport>180){lastReport=now;this.onUpdate(this.info());}});
 }
 setLight(value){Object.assign(this.environment,value);this.scene.background=new T.Color(this.environment.background);this.hemi.intensity=this.environment.ambient;this.key.intensity=this.environment.key;const a=T.MathUtils.degToRad(this.environment.angle);this.key.position.set(Math.sin(a)*12,16,Math.cos(a)*12);this.renderer.toneMappingExposure=this.environment.exposure;}
 async add(bake,config={}){
  validateBake(bake);if(this.actors.length>=24)throw Error('当前排练台最多同时放置 24 个对象');const assetId=bake.assetId||'bake-'+crypto.randomUUID();bake.assetId=assetId;this.assets.set(assetId,bake);
  const group=new T.Group(),textures=[];try{for(const m of bake.meshes){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(m.positions,3));g.setIndex(m.indices);if(m.colors)g.setAttribute('color',new T.Float32BufferAttribute(m.colors,3));if(m.uv)g.setAttribute('uv',new T.Float32BufferAttribute(m.uv,2));g.computeVertexNormals();const d=m.material||{},material=new T.MeshStandardMaterial({color:new T.Color(...(d.color||[1,1,1])),roughness:d.roughness??.85,metalness:d.metalness??0,opacity:d.opacity??1,transparent:(d.opacity??1)<1,vertexColors:!!m.colors,side:d.doubleSided?T.DoubleSide:T.FrontSide});const mesh=new T.Mesh(g,material);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);if(m.texture&&m.uv){const url=URL.createObjectURL(new Blob([Uint8Array.from(m.texture)],{type:m.textureMime}));try{const texture=await new T.TextureLoader().loadAsync(url);texture.colorSpace=T.SRGBColorSpace;texture.flipY=false;material.map=texture;textures.push(texture);}catch{throw Error('烘焙贴图无法解码，请检查内嵌图片');}finally{URL.revokeObjectURL(url);}}}
  const bounds=new T.Box3().setFromObject(group),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),extent=Math.max(size.x,size.y,size.z);if(!Number.isFinite(extent)||extent<1e-8)throw Error('对象尺寸无效');const normalizer=new T.Group();group.position.set(-center.x,-bounds.min.y,-center.z);normalizer.add(group);normalizer.scale.setScalar(2/extent);const root=new T.Group();root.add(normalizer);const actor={id:config.id||crypto.randomUUID(),assetId,name:config.name||bake.animal.name,x:0,y:0,z:0,scale:1,yaw:0,speed:.7,mode:'still',target:'',...config,root,textures,extent,radius:Math.hypot(size.x,size.z)/extent,position:new T.Vector3()};this.actors.push(actor);this.scene.add(root);this.reset();return actor;
  }catch(e){group.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});for(const t of textures)t.dispose();if(!this.actors.some(a=>a.assetId===assetId))this.assets.delete(assetId);throw e;}
 }
 disposeActor(a){this.scene.remove(a.root);a.root.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});a.textures.forEach(t=>t.dispose());}
 remove(id){const i=this.actors.findIndex(a=>a.id===id);if(i<0)return;const [a]=this.actors.splice(i,1);this.disposeActor(a);for(const b of this.actors)if(b.target===id){b.target='';b.mode='still';}if(!this.actors.some(b=>b.assetId===a.assetId))this.assets.delete(a.assetId);}
 play(){this.playing=true;}
 pause(){this.playing=false;}
 reset(){this.elapsed=0;for(const a of this.actors){a.position.set(a.x,a.y,a.z);this.place(a);}this.onUpdate(this.info());}
 fit(){if(!this.actors.length)return;const bounds=new T.Box3();for(const a of this.actors)bounds.expandByObject(a.root);const sphere=bounds.getBoundingSphere(new T.Sphere());this.orbit.target.copy(sphere.center);const direction=this.camera.position.clone().sub(this.orbit.target).normalize();const angle=Math.atan(Math.tan(T.MathUtils.degToRad(this.camera.fov/2))*Math.min(1,this.camera.aspect));this.camera.position.copy(sphere.center).addScaledVector(direction,Math.max(4,sphere.radius/Math.sin(angle)*1.2));this.orbit.update();}
 place(a){a.root.position.copy(a.position);a.root.rotation.y=T.MathUtils.degToRad(a.yaw);a.root.scale.setScalar(a.scale);}
 step(dt){this.elapsed+=dt;const prior=new Map(this.actors.map(a=>[a.id,a.position.clone()]));for(const a of this.actors){const target=this.actors.find(b=>b.id===a.target);if(!target||a.mode==='still')continue;const p=prior.get(target.id),d=p.clone().sub(prior.get(a.id));d.y=0;const distance=d.length();if(a.mode==='orbit'){a.position.x=p.x+Math.cos(this.elapsed*a.speed)*3;a.position.z=p.z+Math.sin(this.elapsed*a.speed)*3;}else if(a.mode!=='face'){const desired=a.mode==='follow'?2:a.mode==='avoid'?4:1.4;if(a.mode==='avoid'&&distance<desired)a.position.addScaledVector(distance<.001?new T.Vector3(1,0,0):d.normalize(),-a.speed*dt);else if(a.mode!=='avoid'&&distance>desired)a.position.addScaledVector(d.normalize(),Math.min(a.speed*dt,distance-desired));}a.position.x=T.MathUtils.clamp(a.position.x,-14,14);a.position.z=T.MathUtils.clamp(a.position.z,-14,14);a.root.position.copy(a.position);a.root.scale.setScalar(a.scale);if(distance>.001)a.root.rotation.y=Math.atan2(p.x-a.position.x,p.z-a.position.z)+T.MathUtils.degToRad(a.yaw);}}
 info(){const pairs=[];for(let i=0;i<this.actors.length;i++)for(let j=i+1;j<this.actors.length;j++){const a=this.actors[i],b=this.actors[j],distance=a.position.distanceTo(b.position);pairs.push({a:a.id,b:b.id,names:a.name+' ↔ '+b.name,distance,near:distance<(a.radius*a.scale+b.radius*b.scale)*.65});}return{elapsed:this.elapsed,playing:this.playing,count:this.actors.length,pairs};}
 document(){const fields=['id','assetId','name','x','y','z','scale','yaw','speed','mode','target'];return{schema:'kaopu/rehearsal@1',version:'1.0.0',units:'display-units',scalePolicy:'each source normalized to maximum extent 2; not biological size calibration',representation:'static poses with host-authored root choreography; no skeletal animation or ecological inference',environment:{...this.environment},assets:[...this.assets.values()],actors:this.actors.map(a=>Object.fromEntries(fields.map(k=>[k,a[k]])))};}
 async load(doc){validateRehearsal(doc);const lookup=new Map(doc.assets.map(b=>[b.assetId,b])),previous={actors:this.actors,assets:this.assets,environment:{...this.environment},elapsed:this.elapsed,playing:this.playing};this.playing=false;for(const a of previous.actors)a.root.visible=false;this.actors=[];this.assets=new Map();this.setLight(doc.environment);try{for(const a of doc.actors)await this.add(lookup.get(a.assetId),a);}catch(e){for(const a of this.actors)this.disposeActor(a);this.actors=previous.actors;this.assets=previous.assets;this.elapsed=previous.elapsed;this.playing=previous.playing;this.setLight(previous.environment);for(const a of this.actors)a.root.visible=true;this.onUpdate(this.info());throw e;}for(const a of previous.actors)this.disposeActor(a);this.reset();}
 dispose(){this.renderer.setAnimationLoop(null);this.observer.disconnect();this.orbit.dispose();for(const id of this.actors.map(a=>a.id))this.remove(id);this.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.renderer.dispose();this.renderer.domElement.remove();}
}
if(typeof window!=='undefined')window.KaopuStageRuntime={version:'1.0.0',create:(mount,onUpdate)=>new RehearsalViewer(mount,onUpdate),validateBake,validateRehearsal};
// The same runtime is embedded in exported pages and runs without a server.
if(typeof document!=='undefined'&&document.getElementById('rehearsal-data')){
 const boot=async()=>{try{const viewer=new RehearsalViewer(document.getElementById('rehearsal-canvas'),info=>{document.getElementById('rehearsal-time').textContent=info.elapsed.toFixed(1)+' s';});await viewer.load(JSON.parse(document.getElementById('rehearsal-data').textContent));window.KaopuStage=viewer;document.getElementById('rehearsal-play').onclick=()=>{viewer.playing=!viewer.playing;document.getElementById('rehearsal-play').textContent=viewer.playing?'暂停':'播放';};document.getElementById('rehearsal-reset').onclick=()=>viewer.reset();document.getElementById('rehearsal-info').textContent=viewer.actors.map(a=>a.name).join(' · ');}catch(e){document.getElementById('rehearsal-info').textContent='无法载入：'+e.message;}};boot();
}
