import * as T from 'three';
import {compactBake,portableBake} from './function-data.js';
import {disposeTree} from './host-geometry.js';
import {stepRoots} from './root-choreography.js';
import {meshBounds} from './basic-data.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {validateBake,validateRehearsal} from './baked.js';
import {createLiveBinding} from './live-bindings.js';
import {sourceBasic,validateBasic} from './basic-data.js';
export const DEFAULT_LIGHT={ambient:1.35,key:2.4,exposure:1.02,angle:35,background:'#b9c0c6'};
function studioBackdrop(background){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=512;const ctx=canvas.getContext('2d'),base=new T.Color(background),gradient=ctx.createLinearGradient(0,0,0,512);gradient.addColorStop(0,base.clone().lerp(new T.Color('#ffffff'),.38).getStyle());gradient.addColorStop(.55,base.getStyle());gradient.addColorStop(1,base.clone().multiplyScalar(.72).getStyle());ctx.fillStyle=gradient;ctx.fillRect(0,0,256,512);const glow=ctx.createRadialGradient(128,145,10,128,220,310);glow.addColorStop(0,'rgba(255,255,255,.12)');glow.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,256,512);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;return texture;}
export class RehearsalViewer{
 constructor(mount,onUpdate=()=>{}){
  this.mount=mount;this.onUpdate=onUpdate;this.actors=[];this.assets=new Map();this.elapsed=0;this._playing=true;this.environment={...DEFAULT_LIGHT};this.units="meters";this.urls=[];this.dirty=true;this._byId=new Map();this.stats={draws:0,liveUpdates:0};
  this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;mount.append(this.renderer.domElement);
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(42,1,.001,500);this.camera.position.set(9,7,12);this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.target.set(0,1,0);this.orbit.enableDamping=true;this.orbit.addEventListener('change',()=>this.invalidate());this.orbit.minDistance=.025;this.orbit.maxDistance=300;
  this.hemi=new T.HemisphereLight('#e7eef4','#93918c',1);this.key=new T.DirectionalLight('#fff9ed',3);this.key.castShadow=true;this.key.shadow.mapSize.set(2048,2048);this.key.shadow.camera.left=-16;this.key.shadow.camera.right=16;this.key.shadow.camera.top=16;this.key.shadow.camera.bottom=-16;this.key.shadow.camera.far=55;this.key.shadow.bias=-.0002;this.key.shadow.normalBias=.025;this.key.shadow.radius=4;this.scene.add(this.hemi,this.key);
  const floorMaterial=new T.MeshStandardMaterial({color:'#a5adb0',roughness:1});floorMaterial.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 studioPosition;').replace('#include <project_vertex>','#include <project_vertex>\nstudioPosition=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 studioPosition;').replace('#include <color_fragment>','#include <color_fragment>\nvec2 broad=studioPosition.xz/vec2(10.0,8.0),pool=studioPosition.xz/vec2(5.5,4.2);diffuseColor.rgb*=.84+.07*exp(-dot(broad,broad)*.45)+.12*exp(-dot(pool,pool)*.7);');};floorMaterial.customProgramCacheKey=()=> 'kaopu/studio-ground@1';const floor=new T.Mesh(new T.PlaneGeometry(2000,2000),floorMaterial);floor.rotation.x=-Math.PI/2;floor.position.y=-.17;floor.receiveShadow=true;this.scene.add(floor);const trainingPad=new T.Mesh(new T.CylinderGeometry(7.5,7.5,.16,160),new T.MeshStandardMaterial({color:'#c4c8c7',roughness:1}));trainingPad.position.y=-.085;trainingPad.receiveShadow=trainingPad.castShadow=true;this.scene.add(trainingPad);this.scene.fog=new T.Fog(DEFAULT_LIGHT.background,18,65);
  this.resize=()=>{const {width,height}=mount.getBoundingClientRect();this.renderer.setSize(Math.max(1,width),Math.max(1,height),false);this.camera.aspect=width/Math.max(1,height);this.camera.updateProjectionMatrix();this.invalidate();};this.observer=new ResizeObserver(this.resize);this.observer.observe(mount);this.setLight(this.environment);
  let previous=performance.now(),lastReport=0;this.renderer.setAnimationLoop(now=>{const dt=Math.min(.06,(now-previous)/1000);previous=now;if(!mount.clientWidth||!mount.getClientRects().length)return;if(this.playing){this.step(dt);for(const a of this.actors)if(a.live&&a.lifePlaying&&a.live.capable){a.live.update();this.stats.liveUpdates++;this.dirty=true;}}if(this._syncSettle){for(const a of this.actors)if(a.live&&!(this.playing&&a.lifePlaying&&a.live.capable)){a.live.update();this.stats.liveUpdates++;}this._syncSettle--;}this.orbit.update();if(this.dirty){this.renderer.render(this.scene,this.camera);this.stats.draws++;this._settle=Math.max(0,(this._settle||0)-1);this.dirty=this._settle>0;}if(now-lastReport>180){lastReport=now;this.onUpdate(this.info());}});

 }
 invalidate(sync=false){this.dirty=true;this._settle=3;if(sync)this._syncSettle=3;}
 get playing(){return this._playing;}
 setUnits(units){if(!['meters','display-units'].includes(units))throw Error('排练单位无效');if(units==='meters')for(const a of this.actors)if(!a.basicData)throw Error(a.name+' 缺少基本数据，请先在动物目录导入并填写尺寸和体重');this.units=units;for(const a of this.actors){const factor=units==='meters'?a.basicData.metersPerUnit:2/a.extent;a.normalizer.scale.setScalar(factor);a.radius=Math.hypot(a.sourceSize.x,a.sourceSize.z)*factor/2;a.localBounds=new T.Box3(new T.Vector3(-a.sourceSize.x/2,0,-a.sourceSize.z/2).multiplyScalar(factor),new T.Vector3(a.sourceSize.x/2,a.sourceSize.y,a.sourceSize.z/2).multiplyScalar(factor));}this.invalidate();this.onUpdate(this.info());}
 set playing(value){this._playing=!!value;for(const a of this.actors)a.live?.setPlaying(this._playing&&a.lifePlaying);this.invalidate(true);}
 setLife(id,value){const a=this.actors.find(a=>a.id===id);if(a){a.lifePlaying=!!value;a.live?.setPlaying(this.playing&&a.lifePlaying);this.invalidate(true);}}
 setAction(id,value){const a=this.actors.find(a=>a.id===id);if(!a?.live||!a.live.actions.some(x=>x.id===value))throw Error('此对象不支持该动作');a.live.setAction(value);a.action=value;a.live.setPlaying(this.playing&&a.lifePlaying);this.invalidate(true);}
 setLight(value){Object.assign(this.environment,value);if(!this.backdrop||value.background!==undefined){this.backdrop?.dispose();this.backdrop=studioBackdrop(this.environment.background);this.scene.background=this.backdrop;}this.scene.fog?.color.set(this.environment.background);this.hemi.intensity=this.environment.ambient;this.key.intensity=this.environment.key;const a=T.MathUtils.degToRad(this.environment.angle);this.key.position.set(Math.sin(a)*12,16,Math.cos(a)*12);this.renderer.toneMappingExposure=this.environment.exposure;this.invalidate();}
 async add(bake,config={}){
  validateBake(bake);bake=compactBake(bake);const basicData=sourceBasic(bake);if(this.units==='meters'&&!basicData)throw Error("对象缺少米制基本数据，请先从动物目录导入并填写尺寸和体重，再放入排练台");if(basicData)bake={...bake,source:{...bake.source,basicData}};const total=[...this.assets.values()].reduce((n,b)=>n+b.meshes.reduce((n,m)=>n+m.positions.length/3,0),0)+(this.assets.has(bake.assetId)?0:bake.meshes.reduce((n,m)=>n+m.positions.length/3,0));if(total>4e6)throw Error('排练台总顶点超过 400 万');if(this.actors.length>=24)throw Error('当前排练台最多同时放置 24 个对象');if(bake.runtime&&this.actors.filter(a=>a.live).length>=8)throw Error('当前排练台最多同时运行 8 个活动动物');const assetId=bake.assetId||'bake-'+crypto.randomUUID();bake.assetId=assetId;
  let group=new T.Group(),textures=[],live;try{
   if(bake.runtime){live=await createLiveBinding(bake);group=live.root;textures=live.textures;}
   else for(const m of bake.meshes){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(m.positions,3));g.setIndex(new T.BufferAttribute(new Uint32Array(m.indices),1));if(m.colors)g.setAttribute('color',new T.Float32BufferAttribute(m.colors,3));if(m.uv)g.setAttribute('uv',new T.Float32BufferAttribute(m.uv,2));g.computeVertexNormals();const d=m.material||{},material=new T.MeshStandardMaterial({color:new T.Color(...(d.color||[1,1,1])),roughness:d.roughness??.85,metalness:d.metalness??0,opacity:d.opacity??1,transparent:(d.opacity??1)<1,vertexColors:!!m.colors,side:d.doubleSided?T.DoubleSide:T.FrontSide});const mesh=new T.Mesh(g,material);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);if(m.texture&&m.uv){const url=URL.createObjectURL(new Blob([Uint8Array.from(m.texture)],{type:m.textureMime}));try{const texture=await new T.TextureLoader().loadAsync(url);texture.colorSpace=T.SRGBColorSpace;texture.flipY=false;material.map=texture;textures.push(texture);}catch{throw Error('烘焙贴图无法解码，请检查内嵌图片');}finally{URL.revokeObjectURL(url);}}}
   // Normalize from the exported pose, independently of the live shader's rest geometry.
   const measured=meshBounds(bake.meshes),bounds=new T.Box3(new T.Vector3(...measured.min),new T.Vector3(...measured.max));const size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),extent=Math.max(size.x,size.y,size.z);if(!Number.isFinite(extent)||extent<1e-8)throw Error('对象尺寸无效');const offset=new T.Group();offset.position.set(-center.x,-bounds.min.y,-center.z);offset.add(group);const normalizer=new T.Group();normalizer.add(offset);const factor=this.units==='meters'?basicData.metersPerUnit:2/extent;normalizer.scale.setScalar(factor);const root=new T.Group();root.add(normalizer);const actor={id:config.id||crypto.randomUUID(),assetId,name:config.name||bake.animal.name,x:0,y:0,z:0,scale:1,yaw:0,speed:.7,mode:'still',target:'',lifePlaying:true,action:bake.runtime?.parameters?.action||bake.source?.parameters?.action||'',...config,root,textures,live,extent,basicData,normalizer,sourceSize:size,localBounds:new T.Box3(new T.Vector3(-size.x/2,0,-size.z/2).multiplyScalar(factor),new T.Vector3(size.x/2,size.y,size.z/2).multiplyScalar(factor)),radius:Math.hypot(size.x,size.z)*factor/2,position:new T.Vector3()};if(actor.action&&live){if(!live.actions.some(x=>x.id===actor.action))throw Error('排练对象不支持动作：'+actor.action);live.setAction(actor.action);}live?.setPlaying(this.playing&&actor.lifePlaying);this.assets.set(assetId,bake);this.actors.push(actor);this.scene.add(root);this.reset();return actor;
  }catch(e){live?.dispose();disposeTree(group,textures);throw e;}
 }
 disposeActor(a){a.live?.dispose();this.scene.remove(a.root);disposeTree(a.root,a.textures);}
 remove(id){const i=this.actors.findIndex(a=>a.id===id);if(i<0)return;const [a]=this.actors.splice(i,1);this.disposeActor(a);this._byId.delete(id);for(const b of this.actors)if(b.target===id){b.target='';b.mode='still';}if(!this.actors.some(b=>b.assetId===a.assetId))this.assets.delete(a.assetId);this.invalidate();}
 play(){this.playing=true;}
 pause(){this.playing=false;}
 reset(){this.elapsed=0;for(const a of this.actors){a.position.set(a.x,a.y,a.z);this.place(a);}this.invalidate(true);this.onUpdate(this.info());}
 fit(){if(!this.actors.length)return;const bounds=new T.Box3();for(const a of this.actors){a.root.updateWorldMatrix(true,true);bounds.union(a.localBounds.clone().applyMatrix4(a.root.matrixWorld));}const sphere=bounds.getBoundingSphere(new T.Sphere());this.orbit.target.copy(sphere.center);const direction=this.camera.position.clone().sub(this.orbit.target).normalize();const angle=Math.atan(Math.tan(T.MathUtils.degToRad(this.camera.fov/2))*Math.min(1,this.camera.aspect));this.camera.position.copy(sphere.center).addScaledVector(direction,Math.max(.25,sphere.radius/Math.sin(angle)*1.2));this.orbit.update();}
 place(a){a.root.position.copy(a.position);a.root.rotation.y=T.MathUtils.degToRad(a.yaw);a.root.scale.setScalar(a.scale);}
 step(dt){this.elapsed+=dt;stepRoots(this.actors,this.elapsed,dt,this._byId);if(this.actors.some(a=>a.target&&a.mode!=='still'))this.invalidate();}

 info(){const pairs=[];for(let i=0;i<this.actors.length;i++)for(let j=i+1;j<this.actors.length;j++){const a=this.actors[i],b=this.actors[j],distance=a.position.distanceTo(b.position);pairs.push({a:a.id,b:b.id,names:a.name+' ↔ '+b.name,distance,near:distance<(a.radius*a.scale+b.radius*b.scale)*.65});}return{elapsed:this.elapsed,playing:this.playing,count:this.actors.length,units:this.units,pairs};}
 document(){const fields=['id','assetId','name','x','y','z','scale','yaw','speed','mode','target','lifePlaying','action'];return{schema:'kaopu/rehearsal@1',version:'1.0.0',units:this.units,scalePolicy:this.units==='meters'?'fixed declared meters-per-source-unit; actor.scale is a presentation multiplier; mass is independent':'legacy each source normalized to maximum extent 2; not biological size calibration',representation:'current forms with original instrument life activities when provided; host-authored root choreography; no ecological inference',playing:this.playing,environment:{...this.environment},assets:[...this.assets.values()].map(portableBake),actors:this.actors.map(a=>Object.fromEntries(fields.map(k=>[k,a[k]])))};}
 async load(doc){validateRehearsal(doc);const lookup=new Map(doc.assets.map(b=>[b.assetId,b])),previous={actors:this.actors,assets:this.assets,environment:{...this.environment},elapsed:this.elapsed,playing:this.playing,units:this.units};this.playing=false;for(const a of previous.actors)a.root.visible=false;this.actors=[];this.assets=new Map();this._byId.clear();this.units=doc.units||'display-units';this.setLight(doc.environment);try{for(const a of doc.actors)await this.add(lookup.get(a.assetId),a);}catch(e){for(const a of this.actors)this.disposeActor(a);this.actors=previous.actors;this.assets=previous.assets;this.elapsed=previous.elapsed;this.units=previous.units;this.playing=previous.playing;this.setLight(previous.environment);for(const a of this.actors)a.root.visible=true;this.invalidate();this.onUpdate(this.info());throw e;}for(const a of previous.actors)this.disposeActor(a);this.reset();this.playing=doc.playing!==false;}
 dispose(){this.renderer.setAnimationLoop(null);this.observer.disconnect();this.orbit.dispose();for(const id of this.actors.map(a=>a.id))this.remove(id);this.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.backdrop?.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
if(typeof window!=='undefined')window.KaopuStageRuntime={version:'1.0.0',create:(mount,onUpdate)=>new RehearsalViewer(mount,onUpdate),validateBake,validateRehearsal};
// The same runtime is embedded in exported pages and runs without a server.
if(typeof document!=='undefined'&&document.getElementById('rehearsal-data')){
 const boot=async()=>{try{const viewer=new RehearsalViewer(document.getElementById('rehearsal-canvas'),info=>{document.getElementById('rehearsal-time').textContent=info.elapsed.toFixed(1)+' s';});await viewer.load(JSON.parse(document.getElementById('rehearsal-data').textContent));window.KaopuStage=viewer;document.getElementById('rehearsal-play').textContent=viewer.playing?'暂停':'播放';document.getElementById('rehearsal-play').onclick=()=>{viewer.playing=!viewer.playing;document.getElementById('rehearsal-play').textContent=viewer.playing?'暂停':'播放';};document.getElementById('rehearsal-reset').onclick=()=>viewer.reset();document.getElementById('rehearsal-info').textContent=viewer.actors.map(a=>a.name).join(' · ');}catch(e){document.getElementById('rehearsal-info').textContent='无法载入：'+e.message;}};boot();
}
