import {RehearsalViewer} from './rehearsal-viewer.js';
import {bakeAnimal,validateBake,validateRehearsal} from './baked.js';
const $=id=>document.getElementById(id),safe=v=>JSON.stringify(v).replace(/</g,'\\u003c');
export function standaloneStage(doc){return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>靠谱 · 烘焙展示</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;font:14px system-ui;background:#eff0ef;color:#343b3a}#rehearsal-canvas{position:absolute;inset:0}header{position:absolute;top:18px;left:20px;right:20px;pointer-events:none}footer{position:absolute;left:20px;bottom:20px;display:flex;gap:10px;align-items:center}button{background:#ffffffe0;border:1px solid #c7cecb;border-radius:5px;color:inherit;padding:9px 18px;cursor:pointer}small{display:block;margin-top:8px;color:#717c76}</style></head><body><div id="rehearsal-canvas"></div><header><span id="rehearsal-info">正在读取对象…</span><small>拖动旋转 · 滚轮缩放 · 当前形态 / 原生生命活动 / 编排演示</small></header><footer><button id="rehearsal-play">暂停</button><button id="rehearsal-reset">复位</button><span id="rehearsal-time">0.0 s</span></footer><script type="application/json" id="rehearsal-data">'+safe(doc)+'</script><script>window.ATLAS_LIVE_SUPPORT='+safe(window.ATLAS_LIVE_SUPPORT)+';</script><script>'+window.ATLAS_REHEARSAL_RUNTIME.replaceAll('</script','<\\/script')+'</script></body></html>';}
export function createRehearsal(api){
 let viewer,selected='',busy=false,session=0,cancelCapture;const dialog=$('rehearsal-dialog'),status=$('rehearsal-status');
 const say=s=>status.textContent=s;
 const guard=async job=>{if(busy)return;busy=true;buttons();try{await job();}catch(e){say(e.message);}finally{busy=false;buttons();}};
 function buttons(){$('rehearsal-add').disabled=busy;$('rehearsal-load').disabled=busy;$('rehearsal-export').disabled=busy||!viewer?.actors.length;$('rehearsal-remove').disabled=busy||!selected;for(const id of ['rehearsal-play','rehearsal-reset','rehearsal-fit'])$(id).disabled=busy||!viewer?.actors.length;for(const el of dialog.querySelectorAll('#rehearsal-controls input,#rehearsal-controls select,[id^="rehearsal-light-"],#rehearsal-actors button'))el.disabled=busy;const a=viewer?.actors.find(a=>a.id===selected);for(const id of ['actor-life','actor-action'])$(id).disabled=busy||!a?.live?.capable;}
 function catalog(){const select=$('rehearsal-animal'),old=select.value;select.replaceChildren();for(const a of api.visible()){const o=document.createElement('option');o.value=a.id;o.textContent=a.name;select.append(o);}select.value=api.current()?.id||old;}
 function open(){if(!viewer)viewer=new RehearsalViewer($('rehearsal-viewport'),update);catalog();dialog.showModal();viewer.resize();viewer.playing=true;$('rehearsal-play').textContent='Ⅱ 暂停';renderActors();buttons();}
 function close(){session++;cancelCapture?.();viewer&&(viewer.playing=false);$('rehearsal-play').textContent='▶ 播放';dialog.close();}
 function update(info){$('rehearsal-clock').textContent=info.elapsed.toFixed(1)+' s';const mount=$('rehearsal-relations');mount.replaceChildren();for(const p of info.pairs.slice(0,12)){const row=document.createElement('div');row.className='relation-row';row.textContent=p.names+' · '+p.distance.toFixed(2)+(p.near?' · 接近 / 包围范围重叠':'');mount.append(row);}if(!info.pairs.length)mount.textContent='放入两个以上对象后显示距离。单位为展示单位。';}
 function renderActors(){const mount=$('rehearsal-actors');mount.replaceChildren();for(const a of viewer.actors){const b=document.createElement('button');b.dataset.actor=a.id;b.textContent=a.name;b.classList.toggle('active',a.id===selected);b.onclick=()=>{selected=a.id;renderActors();};mount.append(b);}const a=viewer.actors.find(a=>a.id===selected);$('rehearsal-controls').hidden=!a;if(a){$('actor-life').checked=a.lifePlaying;$('actor-life').disabled=!a.live?.capable;const action=$('actor-action');action.replaceChildren();for(const item of a.live?.actions||[]){const o=document.createElement('option');o.value=item.id;o.textContent=item.label;action.append(o);}action.value=a.action||a.live?.sourceParameters.action||a.live?.actions[0]?.id||'';action.disabled=!a.live?.capable;$('actor-life-note').textContent=a.live?.capable?'生命活动由原动物运行器执行。位置静置时也可播放。':'此对象仅含静态形态，原模块没有可播放动作。';for(const k of ['x','y','z','scale','yaw','speed']){$('actor-'+k).value=a[k];$('actor-'+k+'-value').textContent=String(a[k]);}$('actor-mode').value=a.mode;const target=$('actor-target');target.replaceChildren();const none=document.createElement('option');none.value='';none.textContent='选择关系对象';target.append(none);for(const b of viewer.actors.filter(b=>b.id!==selected)){const o=document.createElement('option');o.value=b.id;o.textContent=b.name;target.append(o);}target.value=a.target||'';}buttons();update(viewer.info());}
 async function capture(id){
  const a=api.visible().find(a=>a.id===id);if(!a)throw Error('动物已从目录移除');if(id===api.current()?.id&&api.ready()){const result=await api.request('mesh',{},180000);return api.liveBake(bakeAnimal(result.items,{...api.source(),...(result.instrumentState?{instrumentState:result.instrumentState}:{})}),a);}
  const epoch=session,initial={...api.saved(id),displayStage:'turntable',studioRotate:false,playing:false,group:false},original=await api.decode(a.asset);if(epoch!==session)throw Error('已取消载入');const runtimeChannel='rehearsal-'+crypto.randomUUID(),iframe=document.createElement('iframe');iframe.className='rehearsal-worker';iframe.title='排练台后台读取动物';document.body.append(iframe);
  try{const snapshot=await new Promise((resolve,reject)=>{let timer;const finish=(e,value)=>{clearTimeout(timer);removeEventListener('message',receive);cancelCapture=null;e?reject(e):resolve(value);};cancelCapture=()=>finish(Error('已取消载入'));let record;function receive(e){const m=e.data;if(e.source!==iframe.contentWindow||m?.protocol!=='animal-atlas/1'||m.channel!==runtimeChannel)return;try{if(m.type==='failure')finish(Error(m.error));else if(m.type==='ready'){record=m.record;iframe.contentWindow.postMessage({protocol:'animal-atlas/1',channel:runtimeChannel,type:'mesh',requestId:1},'*');}else if(m.type==='mesh'){finish(null,bakeAnimal(m.items,{...api.source(a,record),...(m.instrumentState?{instrumentState:m.instrumentState}:{})}));}}catch(e){finish(e);}}addEventListener('message',receive);timer=setTimeout(()=>finish(Error('读取动物超时，请重试')),180000);iframe.srcdoc=api.runtimeHtml(original,a,initial,runtimeChannel);});return await api.liveBake(snapshot,a);}finally{iframe.srcdoc='';iframe.remove();}
 }
 async function add(id){return guard(async()=>{if(!viewer)open();say('正在读取动物的当前形态…');const b=await capture(id);if(!dialog.open)throw Error('已取消载入');const total=[...viewer.assets.values()].reduce((n,b)=>n+b.meshes.reduce((n,m)=>n+m.positions.length/3,0),0)+b.meshes.reduce((n,m)=>n+m.positions.length/3,0);if(total>4e6)throw Error('排练台总顶点超过 400 万，请移除部分对象');const index=viewer.actors.length,a=await viewer.add(b,{x:(index%4-1.5)*3,z:(Math.floor(index/4)-.5)*3});if(!dialog.open){viewer.remove(a.id);viewer.playing=false;return;}selected=a.id;viewer.playing=true;$('rehearsal-play').textContent='Ⅱ 暂停';renderActors();say('已加入 '+a.name+(a.live?.capable?' · 原生生命活动已播放。':' · 原模块未提供生命动作。'));});}
 function exportDoc(format){const doc=viewer.document();validateRehearsal(doc);api.download(format==='html'?'rehearsal.stage.html':'rehearsal.kaopu.json',format==='html'?standaloneStage(doc):JSON.stringify(doc),'text/'+(format==='html'?'html':'plain'));say(format==='html'?'已导出独立排练页，可以嵌入其他网站。':'已导出完整排练谱，包含形态、布局、关系和光线。');}
 $('rehearsal-open').onclick=open;$('rehearsal-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});$('rehearsal-add').onclick=()=>add($('rehearsal-animal').value);$('rehearsal-play').onclick=()=>{viewer.playing=!viewer.playing;$('rehearsal-play').textContent=viewer.playing?'Ⅱ 暂停':'▶ 播放';};$('rehearsal-reset').onclick=()=>viewer.reset();$('rehearsal-fit').onclick=()=>viewer.fit();$('rehearsal-remove').onclick=()=>{viewer.remove(selected);selected=viewer.actors[0]?.id||'';renderActors();};
 for(const k of ['x','y','z','scale','yaw','speed'])$('actor-'+k).oninput=()=>{const a=viewer.actors.find(a=>a.id===selected);if(!a)return;a[k]=+$('actor-'+k).value;$('actor-'+k+'-value').textContent=String(a[k]);viewer.reset();};
 for(const k of ['mode','target'])$('actor-'+k).onchange=()=>{const a=viewer.actors.find(a=>a.id===selected);if(!a)return;a[k]=$('actor-'+k).value;viewer.reset();if(a.mode!=='still'&&!a.target)say('请再选择一个关系对象。');else say('关系为人工编排，仅控制整体位移与朝向。');};
 for(const k of ['ambient','key','exposure','angle','background'])$('rehearsal-light-'+k).oninput=()=>viewer.setLight({[k]:k==='background'?$('rehearsal-light-'+k).value:+$('rehearsal-light-'+k).value});
 $('actor-life').onchange=()=>viewer.setLife(selected,$('actor-life').checked);$('actor-action').onchange=()=>{try{viewer.setAction(selected,$('actor-action').value);}catch(e){say(e.message);}};
 async function importFile(file){if(file.size>180*1048576)throw Error('文件超过 180 MiB');const doc=JSON.parse(await file.text());if(doc.schema==='kaopu/rehearsal@1'){say('正在恢复排练谱与生命活动…');await viewer.load(doc);selected=viewer.actors[0]?.id||'';say('已恢复 '+viewer.actors.length+' 个对象与关系。');}else{validateBake(doc);let bake=doc;if(!doc.runtime){const source=api.visible().find(a=>a.id===doc.source?.animalId);if(source&&doc.source?.sourceSha256===window.ATLAS_ASSETS[source.asset]?.sha256)bake=await api.liveBake(doc,source);}say('正在导入当前形态与动物运行器…');const a=await viewer.add(bake,{x:viewer.actors.length*2.5});selected=a.id;viewer.playing=true;say('已导入 '+a.name+(a.live?.capable?' · 已保留导出参数，生命活动已播放。':' · 静态形态，文件或原模块未提供生命动作。'));}if(!dialog.open){viewer.playing=false;return;}$('rehearsal-play').textContent=viewer.playing?'Ⅱ 暂停':'▶ 播放';for(const [k,v]of Object.entries(viewer.environment))$('rehearsal-light-'+k).value=v;renderActors();}
 $('rehearsal-export').onclick=()=>guard(()=>exportDoc($('rehearsal-format').value));$('rehearsal-load').onclick=()=>$('rehearsal-file').click();$('rehearsal-file').onchange=e=>{const file=e.target.files[0];e.target.value='';if(file)guard(()=>importFile(file));};
 return{open,add,capture,exportDoc,importFile,get viewer(){return viewer;},get busy(){return busy;}};
}
