import * as T0 from '../vendor/three.module.js';
const defaults={displayStage:'turntable',studioRotate:true,studioSpeed:.55,studioLightAngle:35,studioKey:3.8,studioAmbient:.65,studioRim:1.35,studioExposure:1.15,studioBackground:'#171b22'};
const state={...defaults};const instances=new Set(),rawCache=new WeakMap();let last=performance.now(),frames=0;
const KEY_DIRECTION=[.58,.78,.34],FILL_DIRECTION=[-.72,.38,-.55],KEY_COLOR=[1,.78,.52],FILL_COLOR=[.42,.64,1];
function lightDirection(){return KEY_DIRECTION;}
function fillDirection(){return FILL_DIRECTION;}
function sceneStage(T,scene,{zUp=false}={}){const group=new T.Group();group.name='atlas-rotating-display';if(zUp)group.rotation.x=Math.PI/2;const platform=new T.Group();group.add(platform);const sand=new T.Mesh(new T.CylinderGeometry(1,1,.035,96),new T.MeshStandardMaterial({color:'#737781',roughness:.95}));sand.position.y=-.018;sand.receiveShadow=true;platform.add(sand);const ring=new T.Mesh(new T.RingGeometry(1.015,1.035,96),new T.MeshBasicMaterial({color:'#9da3af',transparent:true,opacity:.65,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.014;platform.add(ring);
 const ground=new T.Mesh(new T.PlaneGeometry(1000,1000),new T.MeshStandardMaterial({color:'#232830',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.042;ground.receiveShadow=true;platform.add(ground);
 const hemisphere=new T.HemisphereLight('#d1d9e8','#343841',.65),sun=new T.DirectionalLight('#ffe0b8',3.8),rim=new T.DirectionalLight('#99c6ff',1.35);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.bias=-.0002;sun.shadow.normalBias=.005;group.add(hemisphere,sun,sun.target,rim,rim.target);scene.add(group);
 const sky=new T.Color(state.studioBackground),fog=new T.FogExp2(sky,.022),hidden=new Map(),origin=new T.Vector3(),worldScale=new T.Vector3(),lastScale=new T.Vector3();let fitRoot=null,radius=1,floorY=0,center=new T.Vector3(),visibleRoots=[];
 function fit(roots){visibleRoots=roots.filter(Boolean);if(!visibleRoots.length)return;const box=new T.Box3();for(const root of visibleRoots)box.union(new T.Box3().setFromObject(root));if(zUp)box.applyMatrix4(new T.Matrix4().makeRotationX(-Math.PI/2));if(box.isEmpty())return;const s=box.getSize(new T.Vector3());if(!Number.isFinite(s.length()))return;radius=Math.max(.05,Math.max(s.x,s.z,s.y*.65)*.75);floorY=box.min.y-.012*radius;box.getCenter(center);platform.scale.setScalar(radius);platform.position.set(center.x,floorY,center.z);fitRoot=visibleRoots[0];fitRoot.getWorldPosition(origin);fitRoot.getWorldScale(lastScale);const extent=radius*2;Object.assign(sun.shadow.camera,{left:-extent,right:extent,top:extent,bottom:-extent,near:radius*.05,far:radius*20});sun.shadow.camera.updateProjectionMatrix();sun.shadow.normalBias=radius*.007;}
 function apply(renderer,roots){if(roots?.[0]!==fitRoot||roots?.[0]&&!roots[0].getWorldScale(worldScale).equals(lastScale))fit(roots||[]);if(fitRoot){const delta=fitRoot.getWorldPosition(new T.Vector3()).sub(origin);if(zUp)delta.applyAxisAngle(new T.Vector3(1,0,0),-Math.PI/2);platform.position.set(center.x+delta.x,floorY,center.z+delta.z);}const active=true;group.visible=active;if(!active){for(const [o,v]of hidden)o.visible=v;hidden.clear();return;}const preserve=new Set([group]);for(const r of roots||[])for(let o=r;o;o=o.parent)preserve.add(o);for(const child of scene.children){if(preserve.has(child)||child.isSkeletonHelper)continue;if(!hidden.has(child))hidden.set(child,child.visible);child.visible=false;}
  for(const root of roots||[])root.traverse(o=>{for(const m of(Array.isArray(o.material)?o.material:[o.material]))if(m?.uniforms?.uAtlasKey){m.uniforms.uAtlasKey.value=state.studioKey/3.8;m.uniforms.uAtlasAmbient.value=state.studioAmbient/.65;m.uniforms.uAtlasRim.value=state.studioRim/1.35;}});scene.environment=null;scene.background=sky.set(state.studioBackground);scene.fog=fog;fog.color.copy(sky);fog.density=.022/Math.max(.05,radius);renderer.toneMappingExposure=state.studioExposure;hemisphere.intensity=state.studioAmbient;sun.intensity=state.studioKey;rim.intensity=state.studioRim;sun.target.position.set(0,0,0);sun.position.set(...KEY_DIRECTION).multiplyScalar(8);rim.target.position.set(0,0,0);rim.position.set(...FILL_DIRECTION).multiplyScalar(8);sun.shadow.camera.far=Math.max(100,radius*20);sun.shadow.camera.updateProjectionMatrix();
 }
 const api={group,fit,apply,get radius(){return radius;},stats:()=>({radius,floorY,frames,lights:{key:sun.intensity,ambient:hemisphere.intensity,rim:rim.intensity,keyColor:sun.color.getHexString(),fillColor:rim.color.getHexString(),keyPosition:sun.position.toArray(),fillPosition:rim.position.toArray(),keyTarget:sun.target.position.toArray(),fillTarget:rim.target.position.toArray()},visibleScenery:[...hidden].filter(([o])=>o.visible).map(([o])=>o.name||o.type),background:scene.background?.getHexString(),mode:state.displayStage})};instances.add(api);return api;
}
function installScene(T,scene,renderer,camera,roots,options){const old={background:scene.background,fog:scene.fog,exposure:renderer.toneMappingExposure,toneMapping:renderer.toneMapping},stage=sceneStage(T,scene,options),before=scene.onBeforeRender,base=new T.Vector3(),adjusted=new T.Vector3();let portraitAdjusted=false;stage.restoreCamera=c=>{if(portraitAdjusted&&c.position.equals(adjusted))c.position.copy(base);portraitAdjusted=false;};scene.onBeforeRender=function(r,s,c,...args){before?.call(this,r,s,c,...args);stage.restoreCamera(c);r.toneMapping=state.displayStage==='turntable'&&old.toneMapping===T.NoToneMapping?T.ACESFilmicToneMapping:old.toneMapping;if(state.displayStage!=='turntable'){scene.background=old.background;scene.fog=old.fog;r.toneMappingExposure=old.exposure;}stage.apply(r,roots());stage.group.updateMatrixWorld(true);if(state.displayStage==='turntable'&&c.isPerspectiveCamera&&c.aspect<1&&roots()[0]){const center=new T.Box3().setFromObject(roots()[0]).getCenter(new T.Vector3());base.copy(c.position);c.position.sub(center).multiplyScalar(1/c.aspect).add(center);adjusted.copy(c.position);portraitAdjusted=true;}c.updateMatrixWorld(true);};stage.fit(roots());return stage;}
function prepareRaw(gl,{radius=.8,floorY=-.02,center=[0,0]}={}){if(rawCache.has(gl))return rawCache.get(gl);const gl2=!!gl.createVertexArray,ext=!gl2&&gl.getExtension('EXT_frag_depth'),header=gl2?'#version 300 es\n':'',vs=header+'precision highp float;'+(gl2?'in':'attribute')+' vec2 position;'+(gl2?'out':'varying')+' vec2 uv;void main(){uv=position;gl_Position=vec4(position,0.,1.);}',fs=header+(!gl2&&ext?'#extension GL_EXT_frag_depth : enable\n':'')+'precision highp float;'+(gl2?'in':'varying')+' vec2 uv;'+(gl2?'out vec4 fragColor;':'')+`uniform mat4 invVP,VP;uniform vec3 eye,bg,keyDir;uniform float radius,floorY,key,ambient,exposure;uniform vec2 center;void main(){vec4 q=invVP*vec4(uv,1.,1.);vec3 ray=normalize(q.xyz/q.w-eye);vec3 color=bg*(.72+.42*(1.-length(uv)*.4));float depth=1.;float t=(floorY-eye.y)/ray.y;if(t>0.&&ray.y<-.0001){vec3 p=eye+ray*t;float r=length(p.xz-center)/radius;float grain=fract(sin(dot(p.xz/radius,vec2(127.1,311.7))*80.)*43758.5453);vec3 base=vec3(.31,.33,.37);float ring=1.-smoothstep(.004,.012,abs(r-1.025));base=mix(base,vec3(.45,.48,.53),ring*.7);base=mix(base,bg*.8,smoothstep(1.,1.015,r)*(1.-ring));float contact=exp(-dot(p.xz-center,p.xz-center)/(radius*radius*.1));color=base*(ambient*.18+key*.22*keyDir.y)*(1.-contact*.18);color=mix(color,bg,1.-exp(-t*.026/radius));vec4 clip=VP*vec4(p,1.);depth=clip.z/clip.w*.5+.5;}color=pow(max(color*exposure,vec3(0.)),vec3(1./2.2));`+(gl2?'fragColor':'gl_FragColor')+'=vec4(color,1.);'+(gl2?'gl_FragDepth=depth;':ext?'gl_FragDepthEXT=depth;':'')+'}';
 const compile=(type,text)=>{const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('展示台着色器：'+gl.getShaderInfoLog(s));return s;};const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const vao=gl2?gl.createVertexArray():null;const item={program,buffer,vao,radius,floorY,center,gl2,uniforms:new Map(),frames:0};rawCache.set(gl,item);return item;}
function rawDraw(gl,{view,projection,eye,zUp=false},options){if(state.displayStage!=='turntable')return false;const q=prepareRaw(gl,options);if(options)Object.assign(q,options);const v=new T0.Matrix4().fromArray(view),p=new T0.Matrix4().fromArray(projection);if(zUp)v.multiply(new T0.Matrix4().makeRotationX(Math.PI/2));const vp=p.clone().multiply(v),inv=vp.clone().invert(),pos=new T0.Vector3().setFromMatrixPosition(v.clone().invert()),bg=new T0.Color(state.studioBackground),u=name=>{if(!q.uniforms.has(name))q.uniforms.set(name,gl.getUniformLocation(q.program,name));return q.uniforms.get(name);};if(q.gl2){gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindVertexArray(q.vao);gl.drawBuffers([gl.BACK]);for(let i=0;i<8;i++)gl.bindSampler(i,null);}gl.viewport(0,0,gl.canvas.width,gl.canvas.height);gl.disable(gl.SCISSOR_TEST);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.ALWAYS);gl.depthMask(true);gl.colorMask(true,true,true,true);gl.useProgram(q.program);gl.bindBuffer(gl.ARRAY_BUFFER,q.buffer);const loc=gl.getAttribLocation(q.program,'position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(u('VP'),false,vp.elements);gl.uniformMatrix4fv(u('invVP'),false,inv.elements);gl.uniform3fv(u('eye'),pos.toArray());gl.uniform3fv(u('bg'),bg.toArray());gl.uniform3fv(u('keyDir'),lightDirection());gl.uniform2fv(u('center'),q.center);for(const [name,value]of Object.entries({radius:q.radius,floorY:q.floorY,key:state.studioKey,ambient:state.studioAmbient,exposure:state.studioExposure}))gl.uniform1f(u(name),value);gl.drawArrays(gl.TRIANGLES,0,6);if(q.gl2)gl.bindVertexArray(null);gl.depthFunc(gl.LEQUAL);q.frames++;return true;}
const lightCache=new WeakMap();function rawLight(gl,program,{view,zUp=false}={}){let cache=lightCache.get(program);if(!cache){cache={};for(const key of ['uAtlasLightDirection','uAtlasFillDirection','uAtlasKeyColor','uAtlasFillColor','uAtlasKey','uAtlasAmbient','uAtlasExposure','uAtlasRim'])cache[key]=gl.getUniformLocation(program,key);lightCache.set(program,cache);}let d=new T0.Vector3(...lightDirection());if(zUp)d.set(d.x,-d.z,d.y);if(view)d.transformDirection(new T0.Matrix4().fromArray(view));const studio=state.displayStage==='turntable';let fill=new T0.Vector3(...FILL_DIRECTION);if(zUp)fill.set(fill.x,-fill.z,fill.y);if(view)fill.transformDirection(new T0.Matrix4().fromArray(view));gl.uniform3fv(cache.uAtlasLightDirection,d.toArray());gl.uniform3fv(cache.uAtlasFillDirection,fill.toArray());gl.uniform3fv(cache.uAtlasKeyColor,KEY_COLOR);gl.uniform3fv(cache.uAtlasFillColor,FILL_COLOR);gl.uniform1f(cache.uAtlasKey,studio?state.studioKey/3.8:1);gl.uniform1f(cache.uAtlasAmbient,studio?state.studioAmbient/.65:1);gl.uniform1f(cache.uAtlasExposure,studio?state.studioExposure:1);gl.uniform1f(cache.uAtlasRim,studio?state.studioRim/1.35:1);}
function rotationDelta(){const now=performance.now(),dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;frames++;return state.displayStage==='turntable'&&state.studioRotate?dt*state.studioSpeed*Math.PI/30:0;}
function projection(halfW,halfH,distance,near,far){const p=new Float32Array(16);p[0]=distance/halfW;p[5]=distance/halfH;p[10]=-(far+near)/(far-near);p[11]=-1;p[14]=-2*far*near/(far-near);return p;}
globalThis.AtlasTurntable={T:T0,projection,defaults,state,installScene,rawDraw,rawLight,rotationDelta,set(key,value){if(key==='displayStage')value='turntable';if(key==='studioLightAngle')value=35;state[key]=value;},isActive:()=>state.displayStage==='turntable',info:()=>({rig:'warm-cool-fixed@1',keyDirection:[...KEY_DIRECTION],fillDirection:[...FILL_DIRECTION],keyColor:[...KEY_COLOR],fillColor:[...FILL_COLOR],state:{...state},frames,scenes:[...instances].map(x=>x.stats())})};
