/* Runtime-only triangle queries. The repository stores functions, not a baked NPC. */
export const add=(a,b)=>a.map((x,i)=>x+b[i]),sub=(a,b)=>a.map((x,i)=>x-b[i]),mul=(a,s)=>a.map(x=>x*s),dot=(a,b)=>a.reduce((n,x,i)=>n+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=a=>Math.hypot(...a),unit=a=>mul(a,1/(len(a)||1)),mix=(a,b,t)=>a.map((x,i)=>x+(b[i]-x)*t),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const smooth=t=>(t=clamp(t,0,1),t*t*(3-2*t));
export class BodyBVH{
 constructor(meshes){let np=0,ni=0;for(const m of meshes){np+=m.p.length;ni+=m.indices.length;}this.p=new Float32Array(np);this.i=new Uint32Array(ni);let po=0,io=0;for(const m of meshes){this.p.set(m.p,po);for(let k=0;k<m.indices.length;k++)this.i[io+k]=m.indices[k]+po/3;po+=m.p.length;io+=m.indices.length;}this.centres=new Float32Array(ni);for(let t=0;t<ni/3;t++)for(let k=0;k<3;k++)this.centres[t*3+k]=(this.p[this.i[t*3]*3+k]+this.p[this.i[t*3+1]*3+k]+this.p[this.i[t*3+2]*3+k])/3;this.root=this.build(Array.from({length:ni/3},(_,i)=>i));}
 point(i){return Array.from(this.p.subarray(i*3,i*3+3));}
 tri(t){return [this.point(this.i[t*3]),this.point(this.i[t*3+1]),this.point(this.i[t*3+2])];}
 build(ids){const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const t of ids)for(let j=0;j<3;j++)for(let k=0;k<3;k++){const p=this.p[this.i[t*3+j]*3+k];lo[k]=Math.min(lo[k],p);hi[k]=Math.max(hi[k],p);}const node={lo,hi};if(ids.length<=16){node.ids=ids;return node;}const d=sub(hi,lo),axis=d.indexOf(Math.max(...d));ids.sort((a,b)=>this.centres[a*3+axis]-this.centres[b*3+axis]);const n=ids.length>>1;node.a=this.build(ids.slice(0,n));node.b=this.build(ids.slice(n));return node;}
 ray(o,d,limit=Infinity){let best=limit,hit=null;const visit=n=>{let near=0,far=best;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-12){if(o[k]<n.lo[k]||o[k]>n.hi[k])return;}else{let a=(n.lo[k]-o[k])/d[k],b=(n.hi[k]-o[k])/d[k];if(a>b)[a,b]=[b,a];near=Math.max(near,a);far=Math.min(far,b);if(near>far)return;}}if(n.ids){for(const t of n.ids){const [a,b,c]=this.tri(t),e=sub(b,a),f=sub(c,a),h=cross(d,f),det=dot(e,h);if(Math.abs(det)<1e-12)continue;const s=sub(o,a),u=dot(s,h)/det;if(u<0||u>1)continue;const q=cross(s,e),v=dot(d,q)/det;if(v<0||u+v>1)continue;const r=dot(f,q)/det;if(r>1e-7&&r<best){best=r;hit={p:add(o,mul(d,r)),distance:r,n:mul(unit(cross(e,f)),-1),triangle:t};}}}else{visit(n.a);visit(n.b);}};visit(this.root);return hit;}
 nearest(p,limit=Infinity){let best=limit*limit,out=null;const distBox=n=>{let d=0;for(let k=0;k<3;k++){const v=Math.max(n.lo[k]-p[k],0,p[k]-n.hi[k]);d+=v*v;}return d;};const visit=n=>{if(distBox(n)>best)return;if(n.ids){for(const t of n.ids){const [a,b,c]=this.tri(t),q=closestTriangle(p,a,b,c),v=sub(p,q),d=dot(v,v);if(d<best){best=d;out={p:q,n:mul(unit(cross(sub(b,a),sub(c,a))),-1),distance:Math.sqrt(d),triangle:t};}}}else{const da=distBox(n.a),db=distBox(n.b);if(da<db){visit(n.a);visit(n.b);}else{visit(n.b);visit(n.a);}}};visit(this.root);if(out)out.signed=dot(sub(p,out.p),out.n);return out;}
}
export function closestTriangle(p,a,b,c){const ab=sub(b,a),ac=sub(c,a),ap=sub(p,a),d1=dot(ab,ap),d2=dot(ac,ap);if(d1<=0&&d2<=0)return a;const bp=sub(p,b),d3=dot(ab,bp),d4=dot(ac,bp);if(d3>=0&&d4<=d3)return b;const vc=d1*d4-d3*d2;if(vc<=0&&d1>=0&&d3<=0)return add(a,mul(ab,d1/(d1-d3)));const cp=sub(p,c),d5=dot(ab,cp),d6=dot(ac,cp);if(d6>=0&&d5<=d6)return c;const vb=d5*d2-d1*d6;if(vb<=0&&d2>=0&&d6<=0)return add(a,mul(ac,d2/(d2-d6)));const va=d3*d6-d5*d4;if(va<=0&&d4-d3>=0&&d5-d6>=0)return add(b,mul(sub(c,b),(d4-d3)/((d4-d3)+(d5-d6))));const den=1/(va+vb+vc);return add(a,add(mul(ab,vb*den),mul(ac,vc*den)));}
export function bodySection(bvh,centre,count=96){const points=[];let missing=0;for(let k=0;k<count;k++){const a=k/count*Math.PI*2,d=[Math.sin(a),0,Math.cos(a)],h=bvh.ray(centre,d,.4);if(h)points.push(h.p);else{missing++;points.push(add(centre,mul(d,.14)));}}let circumference=0;for(let k=0;k<count;k++)circumference+=len(sub(points[k],points[(k+1)%count]));const rx=Math.max(...points.map(p=>Math.abs(p[0]-centre[0]))),front=Math.max(...points.map(p=>p[2]-centre[2])),back=Math.max(...points.map(p=>centre[2]-p[2]));return{y:centre[1],points,circumference,rx,front,back,missing};}
export function normals(p,indices){const n=new Float32Array(p.length);for(let k=0;k<indices.length;k+=3){const ids=Array.from(indices.slice(k,k+3)),a=Array.from(p.slice(ids[0]*3,ids[0]*3+3)),b=Array.from(p.slice(ids[1]*3,ids[1]*3+3)),c=Array.from(p.slice(ids[2]*3,ids[2]*3+3)),v=cross(sub(b,a),sub(c,a));for(const id of ids)for(let j=0;j<3;j++)n[id*3+j]+=v[j];}for(let k=0;k<n.length;k+=3)n.set(unit(Array.from(n.slice(k,k+3))),k);return n;}
export function orientMesh(p,i,centre){for(let k=0;k<i.length;k+=3){const a=p.slice(i[k]*3,i[k]*3+3),b=p.slice(i[k+1]*3,i[k+1]*3+3),c=p.slice(i[k+2]*3,i[k+2]*3+3),n=cross(sub(b,a),sub(c,a)),mid=mul(add(a,add(b,c)),1/3);if(dot(n,sub(mid,centre))<0)[i[k+1],i[k+2]]=[i[k+2],i[k+1]];}}
