import {vertex,fragment} from './material-kernel.mjs';
import {add,mul,sub,cross,unit} from './geometry.mjs';
const I=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function program(gl,vs,fs){const make=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};const v=make(gl.VERTEX_SHADER,vs),f=make(gl.FRAGMENT_SHADER,fs),p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const neutral=`#version 300 es
precision highp float;in vec3 W;in vec3 N;in vec2 C;uniform vec3 uCam;out vec4 O;void main(){vec3 n=normalize(N)*(gl_FrontFacing?1.:-1.);float d=max(0.,dot(n,normalize(vec3(-.65,.8,.8))));float rim=pow(1.-abs(dot(n,normalize(uCam-W))),2.);O=vec4(vec3(.48,.51,.52)*(.43+.54*d)+.09*rim,1.);}`;
function shell(m){const p=Array.from(m.p),n=Array.from(m.n),uv=Array.from(m.uv),ids=Array.from(m.indices),count=p.length/3,edges=new Map(),keys=[];
 for(let k=0;k<count;k++)keys.push(p.slice(k*3,k*3+3).map(v=>Math.round(v*1e6)).join(','));
 for(let k=0;k<m.indices.length;k+=3)for(let j=0;j<3;j++){const a=m.indices[k+j],b=m.indices[k+(j+1)%3],key=[keys[a],keys[b]].sort().join('|');if(!edges.has(key))edges.set(key,{a,b,n:0});edges.get(key).n++;}
 for(let k=0;k<count;k++){const q=Array.from(m.p.slice(k*3,k*3+3)),v=Array.from(m.n.slice(k*3,k*3+3));p.splice(k*3,3,...add(q,mul(v,m.thickness/2)));p.push(...add(q,mul(v,-m.thickness/2)));n.push(...mul(v,-1));uv.push(...m.uv.slice(k*2,k*2+2));}
 for(let k=0;k<m.indices.length;k+=3)ids.push(m.indices[k]+count,m.indices[k+2]+count,m.indices[k+1]+count);
 let boundaryEdges=0;for(const e of edges.values())if(e.n===1){boundaryEdges++;const a=e.a,b=e.b,start=p.length/3,qa=p.slice(a*3,a*3+3),qb=p.slice(b*3,b*3+3),qc=p.slice((b+count)*3,(b+count)*3+3),qd=p.slice((a+count)*3,(a+count)*3+3),normal=unit(cross(sub(qb,qa),sub(qc,qa)));p.push(...qa,...qb,...qc,...qd);for(let k=0;k<4;k++){n.push(...normal);uv.push(...m.uv.slice((k===0||k===3?a:b)*2,(k===0||k===3?a:b)*2+2));}ids.push(start,start+1,start+2,start,start+2,start+3);}
 return{p:Float32Array.from(p),n:Float32Array.from(n),uv:Float32Array.from(uv),indices:Uint32Array.from(ids),boundaryEdges};}
export async function createClothRenderer(renderer){const gl=renderer.gl,vs=vertex,fs=await fragment();
 const main=program(gl,vs,fs),plain=program(gl,vs,neutral),state={light:1,neutral:false,garment:true,seams:false,swatch:false};let cloth=null,patch=null,lines=null;
 const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
 const hashes={vertex:await hash(vs),fragment:await hash(fs)};
 if(hashes.vertex!=='166c644d4093c030bf1600744be46ba464a22fcdc6f184f7a298eb031f420d16'||hashes.fragment!=='2e2aeb7031af426b11b81f06544b960c1f95e3fc927d348333560aef84f8c3c5')throw Error('原包麻布着色器校验不一致，停止替换');
 const upload=m=>{const vao=gl.createVertexArray(),buffers=[];gl.bindVertexArray(vao);for(const [loc,data,size]of [[0,m.p,3],[1,m.n,3],[2,m.uv,2]]){const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0);}const ib=gl.createBuffer();buffers.push(ib);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,m.indices,gl.STATIC_DRAW);return{vao,buffers,count:m.indices.length};};
 const dispose=g=>{if(!g)return;gl.deleteVertexArray(g.vao);for(const b of g.buffers)gl.deleteBuffer(b);};
 const uniforms=p=>{const u=n=>gl.getUniformLocation(p,n);gl.useProgram(p);gl.uniformMatrix4fv(u('uM'),false,I);gl.uniformMatrix4fv(u('uVP'),false,renderer.vp);gl.uniform3fv(u('uCam'),renderer.eye);gl.uniform2f(u('uViewport'),renderer.canvas.width,renderer.canvas.height);for(const [n,v]of Object.entries({uMode:2,uLight:state.light,uNeutral:0,uCompare:0,uDiag:0}))gl.uniform1i(u(n),v);for(const n of ['uCoarse','uWeave','uSlub','uAge','uFarId','uSheen','uFuzz'])gl.uniform1f(u(n),1);gl.uniform1f(u('uTime'),0);};
 const lineP=program(gl,`#version 300 es\nlayout(location=0)in vec3 p;uniform mat4 vp;void main(){gl_Position=vp*vec4(p,1.);}`,`#version 300 es\nprecision highp float;out vec4 o;void main(){o=vec4(.16,.085,.030,1.);}`);
 function setMesh(m){dispose(cloth);dispose(patch);if(lines){gl.deleteBuffer(lines.b);gl.deleteVertexArray(lines.vao);}const s=shell(m);cloth=upload(s);
  const z=m.chestTarget[2]+.18,x=m.chestTarget[0]+.39,y=m.chestTarget[1];patch=upload({p:new Float32Array([x,y-.08,z,x+.16,y-.08,z,x+.16,y+.08,z,x,y+.08,z]),n:new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1]),uv:new Float32Array([-8,-8,8,-8,8,8,-8,8]),indices:new Uint32Array([0,1,2,0,2,3])});
  const p=[];for(const seam of m.seams)for(let k=1;k<seam.length;k++)for(const id of [seam[k-1],seam[k]])p.push(...add(Array.from(m.p.slice(id*3,id*3+3)),mul(Array.from(m.n.slice(id*3,id*3+3)),.001)));const vao=gl.createVertexArray(),b=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,Float32Array.from(p),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);lines={vao,b,count:p.length/3};return {renderTriangles:s.indices.length/3,boundaryEdges:s.boundaryEdges};
 }
 function draw(){if(!cloth)return;gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.depthFunc(gl.LEQUAL);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.frontFace(gl.CCW);uniforms(state.neutral?plain:main);if(state.garment){gl.bindVertexArray(cloth.vao);gl.drawElements(gl.TRIANGLES,cloth.count,gl.UNSIGNED_INT,0);}if(state.swatch){uniforms(main);gl.bindVertexArray(patch.vao);gl.drawElements(gl.TRIANGLES,patch.count,gl.UNSIGNED_INT,0);}if(state.garment&&state.seams){gl.useProgram(lineP);gl.uniformMatrix4fv(gl.getUniformLocation(lineP,'vp'),false,renderer.vp);gl.bindVertexArray(lines.vao);gl.drawArrays(gl.LINES,0,lines.count);}gl.bindVertexArray(null);}
 return{state,setMesh,draw,hashes,dispose(){dispose(cloth);dispose(patch);for(const p of[main,plain,lineP])gl.deleteProgram(p);}};
}
