import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id), next=()=>new Promise(r=>requestAnimationFrame(r));
const DEFAULT={id:'cable',dye:'original',width:1,depth:1,height:1,lift:0,tilt:0,roughness:.86,detail:1,sheen:.65,view:'product',head:0,light:'studio',layer:'material'};
const COLORS={original:null,sand:'#d6b894',navy:'#293e55',moss:'#61705c',wine:'#794149',pearl:'#b9b7ab'};
const SCHEMA='kaopu.hat.recipe/1';let D,state={...DEFAULT},token=0,asset=null,hat=null,person=null,rotating=false,framePending=false,busy=false,ready=false,compare=false,thumbsReady=0;
const storage='kaopu.hat-r01.recipe';let saveWarning='';
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
async function unpack64(s,type){const bytes=Uint8Array.from(atob(s),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new type(await new Response(stream).arrayBuffer());}
async function decodeGeometry(data){const [p,n,u,i]=await Promise.all([unpack64(data.p,Float32Array),data.n?unpack64(data.n,Float32Array):null,data.u?unpack64(data.u,Float32Array):null,unpack64(data.i,Uint32Array)]);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));if(n)g.setAttribute('normal',new T.BufferAttribute(n,3));if(u)g.setAttribute('uv',new T.BufferAttribute(u,2));g.setIndex(new T.BufferAttribute(i,1));if(!n)g.computeVertexNormals();g.computeBoundingBox();return g;}
const canvas=$('canvas'),renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.96;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.001,20),controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.minDistance=.1;controls.maxDistance=2.4;controls.maxPolarAngle=Math.PI*.96;controls.addEventListener('change',requestRender);controls.addEventListener('start',()=>{rotating=false;$('rotate').setAttribute('aria-pressed','false');});
const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
const hemi=new T.HemisphereLight(0xffffff,0xb8aa94,2),key=new T.DirectionalLight(0xfff0da,3.2),fill=new T.DirectionalLight(0xdbe8ff,1.15),rim=new T.DirectionalLight(0xffffff,2.3);key.position.set(-.6,.85,.8);fill.position.set(.6,.28,.4);rim.position.set(.35,.6,-.8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-.6;key.shadow.camera.right=.6;key.shadow.camera.top=.65;key.shadow.camera.bottom=-.6;key.shadow.camera.near=.05;key.shadow.camera.far=3;key.shadow.bias=-.00012;key.shadow.normalBias=.00055;key.shadow.radius=3;scene.add(hemi,key,fill,rim,key.target);
const stage=new T.Group();scene.add(stage);const floor=new T.Mesh(new T.PlaneGeometry(8,8),new T.MeshStandardMaterial({color:0xe6e1d7,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.049;floor.receiveShadow=true;scene.add(floor);
const plinth=new T.Mesh(new T.CylinderGeometry(.205,.209,.04,128),new T.MeshStandardMaterial({color:0xd2c9ba,roughness:.9}));plinth.position.y=-.025;plinth.receiveShadow=true;plinth.castShadow=true;scene.add(plinth);
function requestRender(){if(framePending)return;framePending=true;requestAnimationFrame(()=>{framePending=false;render();});}
function render(){if(!asset)return;renderer.render(scene,camera);if(rotating){stage.rotation.y+=.006;requestRender();}}
function resize(){const r=$('viewport').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();requestRender();}new ResizeObserver(resize).observe($('viewport'));
function disposeAsset(a){if(!a)return;a.geometry.dispose();a.material.dispose();Object.values(a.maps).forEach(t=>t.dispose());}
async function loadAsset(meta){const geometry=await decodeGeometry(meta.geometry),maps={};await Promise.all(Object.entries(meta.textures).map(async([key,url])=>{const t=await new T.TextureLoader().loadAsync(url);t.colorSpace=key==='color'?T.SRGBColorSpace:T.NoColorSpace;t.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);maps[key]=t;}));const material=new T.MeshPhysicalMaterial({map:maps.color,normalMap:maps.normal||null,normalScale:new T.Vector2(.8,.8),color:0xffffff,roughness:.86,metalness:0,sheen:.65,sheenColor:new T.Color(.45,.42,.38),sheenRoughness:.85,specularIntensity:.35,side:T.DoubleSide,alphaTest:.25,envMapIntensity:.7});
 const uniforms={uDye:{value:new T.Color('#d6b894')},uDyeAmount:{value:0}};material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,uniforms);shader.fragmentShader='uniform vec3 uDye;\nuniform float uDyeAmount;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat hatLum=dot(diffuseColor.rgb,vec3(0.2126,0.7152,0.0722));\ndiffuseColor.rgb=mix(diffuseColor.rgb,uDye*clamp(pow(max(hatLum,0.0),0.72)*1.45,0.03,1.2),uDyeAmount);');};material.customProgramCacheKey=()=> 'hat-dye-v1';return{geometry,material,maps,uniforms,meta};}
function changed(){state.layer='material';apply();persist();}
function persist(){try{localStorage.setItem(storage,JSON.stringify(recipe()));}catch(e){saveWarning='此浏览器未允许本地保存；可导出配方。';}}
function recipe(){return{schema:SCHEMA,version:D.version,sourceCommit:D.sourceCommit,sourceId:state.id,settings:{...state},nativeHeadId:D.native.heads[state.head].id,fitModel:'bounded-affine/1',physicalFitValidated:false};}
function validate(input){if(!input||input.schema!==SCHEMA||input.version!==D.version||input.sourceCommit!==D.sourceCommit)throw Error('配方版本不匹配；未改变当前帽子');const s=input.settings;if(!s||!D.hats.some(x=>x.id===s.id)||!Object.hasOwn(COLORS,s.dye))throw Error('未知帽型或配色');for(const [k,lo,hi]of[['width',.9,1.12],['depth',.9,1.12],['height',.85,1.2],['lift',-.035,.045],['tilt',-15,15],['roughness',.45,1],['detail',0,1.7],['sheen',0,1],['head',0,D.native.heads.length-1]])if(!Number.isFinite(s[k])||s[k]<lo||s[k]>hi)throw Error('非法参数：'+k);if(!Number.isInteger(s.head)||!['product','wear'].includes(s.view)||!['studio','neutral','raking'].includes(s.light)||!['material','clay','wire','normal'].includes(s.layer))throw Error('无效显示配置');return structuredClone(s);}
async function restore(input){const valid=validate(input);await select(valid.id,valid);persist();return recipe();}
function metrics(){if(!hat)return null;hat.updateMatrixWorld(true);const box=new T.Box3().setFromObject(hat),size=box.getSize(new T.Vector3());return{hat:state.id,triangles:asset.geometry.index.count/3,vertices:asset.geometry.attributes.position.count,widthMM:size.x*1000,heightMM:size.y*1000,depthMM:size.z*1000,view:state.view,headId:D.native.heads[state.head].id,sourceCommit:D.sourceCommit,rendererCalls:renderer.info.render.calls,geometryCount:renderer.info.memory.geometries,textureCount:renderer.info.memory.textures,hatVisible:hat.visible,headVisible:person?.visible||false};}
const clay=new T.MeshStandardMaterial({color:0xc6c1b8,roughness:.9,side:T.DoubleSide}),normal=new T.MeshNormalMaterial({side:T.DoubleSide});
function apply(){if(!hat)return;const s=compare?{...DEFAULT,id:state.id,view:state.view,head:state.head,light:state.light}:state;const meta=asset.meta,head=D.native.heads[state.head];stage.rotation.y=0;hat.material=s.layer==='clay'?clay:s.layer==='normal'?normal:asset.material;asset.material.wireframe=s.layer==='wire';asset.material.roughness=s.roughness;asset.material.sheen=s.sheen;asset.material.normalScale.set(s.detail*.8,s.detail*.8);asset.uniforms.uDyeAmount.value=s.dye==='original'?0:1;if(COLORS[s.dye])asset.uniforms.uDye.value.set(COLORS[s.dye]);
 const origin=new T.Vector3(...meta.origin),b=asset.geometry.boundingBox.clone(),center=b.getCenter(new T.Vector3());
 hat.position.set(0,0,0);hat.rotation.set(0,0,0);hat.scale.set(s.width,s.height,s.depth);
 if(s.view==='product'){hat.position.set(-center.x*s.width,-b.min.y*s.height+.017,-center.z*s.depth);person.visible=false;plinth.visible=true;floor.position.y=-.049;}
 else{const sx=head.headWidthM/.148,sz=head.headDepthM/.19221,sy=(sx+sz)/2;hat.scale.multiply(new T.Vector3(sx,sy,sz));hat.rotation.z=T.MathUtils.degToRad(s.tilt);hat.position.copy(origin.clone().multiply(hat.scale).applyEuler(hat.rotation).multiplyScalar(-1));hat.position.y+=s.lift;person.visible=true;plinth.visible=false;floor.position.y=-.46;}
 if(s.view==='product')hat.rotation.z=0;
 if(s.light==='studio'){key.position.set(-.6,.85,.8);key.intensity=3.2;fill.intensity=1.15;rim.intensity=2.3;hemi.intensity=2;renderer.toneMappingExposure=.96;}
 if(s.light==='neutral'){key.position.set(.1,.9,.7);key.intensity=2.5;fill.intensity=1.8;rim.intensity=.8;hemi.intensity=2.2;renderer.toneMappingExposure=.93;}
 if(s.light==='raking'){key.position.set(-.9,.15,.25);key.intensity=4;fill.intensity=.5;rim.intensity=1.4;hemi.intensity=.85;renderer.toneMappingExposure=1.02;}
 syncUI();requestRender();const m=metrics();$('dimensions').textContent=`${m.widthMM.toFixed(0)} × ${m.heightMM.toFixed(0)} × ${m.depthMM.toFixed(0)} mm`;
}
function frame(view='three'){if(!hat)return;stage.rotation.y=0;const b=new T.Box3().setFromObject(hat);if(state.view==='wear')b.union(new T.Box3().setFromObject(person));const size=b.getSize(new T.Vector3()),c=b.getCenter(new T.Vector3());let d=Math.max(size.y,size.x/camera.aspect,size.z)*1.85;d=Math.max(d,.36);const dirs={three:[1,.65,1.5],front:[0,.25,1],side:[1,.25,.03],back:[0,.3,-1],top:[.03,1,.03],inside:[.25,-.8,1],detail:[.4,.3,1]};const dir=new T.Vector3(...(dirs[view]||dirs.three)).normalize();if(view==='detail')d*=.56;camera.position.copy(c).addScaledVector(dir,d);controls.target.copy(c);controls.update();requestRender();}
async function headGeometry(){if(person)person.geometry.dispose();const h=D.native.heads[state.head],g=await decodeGeometry(h);if(person){person.geometry=g;}else{person=new T.Mesh(g,new T.MeshStandardMaterial({color:0xc8bdae,roughness:.72}));person.castShadow=true;person.receiveShadow=true;person.name='Original common-person evaluated static head';stage.add(person);}}
async function select(id,settings=null){const t=++token;busy=true;message('正在载入真实三维帽型…');const meta=D.hats.find(x=>x.id===id);if(!meta)throw Error('Unknown hat');const a=await loadAsset(meta);if(t!==token){disposeAsset(a);return;}if(hat)stage.remove(hat);disposeAsset(asset);asset=a;state=settings||{...DEFAULT,id,view:state.view,head:state.head,light:state.light};hat=new T.Mesh(a.geometry,a.material);hat.name=id;hat.castShadow=true;hat.receiveShadow=true;stage.add(hat);await headGeometry();apply();frame();busy=false;ready=true;$('loading').hidden=true;$('title').textContent=meta.title;$('eyebrow').textContent=`${meta.category} / ${id.toUpperCase()}`;$('source-note').textContent=`原帽型 / 贴图：${meta.author} · ${meta.licence}。当前为 Three.js 材质适配，不是原渲染器逐像素复刻。`;$('teacher-image').src=meta.teacherThumbnail;$('teacher-link').href=meta.referenceURL;message(saveWarning||'拖动旋转 · 滚轮拉近 · 长按「初始版本」对照');document.querySelectorAll('.hat-card').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));persist();return metrics();}
function syncUI(){$('detail').disabled=!asset.maps.normal;for(const k of['width','depth','height','lift','tilt','roughness','detail','sheen']){if($(k))$(k).value=state[k];if($(k+'-v'))$(k+'-v').textContent=['width','depth','height'].includes(k)?Math.round(state[k]*100)+'%':k==='lift'?(state[k]*1000).toFixed(0)+' mm':k==='tilt'?state[k]+'°':state[k].toFixed(2);}$('wear').setAttribute('aria-pressed',String(state.view==='wear'));$('product').setAttribute('aria-pressed',String(state.view==='product'));$('head-select').value=state.head;$('fit-controls').hidden=state.view!=='wear';$('head-info').textContent=state.view==='wear'?`原总台静态头形 · 水平截面椭圆估算 ${(D.native.heads[state.head].ellipseCircumferenceM*1000).toFixed(0)} mm；非实测头围`:'单帽观察 · 保留原形体与材质层次';document.querySelectorAll('[data-dye]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dye===state.dye)));document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layer===state.layer)));document.querySelectorAll('[data-light]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.light===state.light)));}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function thumbnails(){const rt=new T.WebGLRenderTarget(288,210,{colorSpace:T.SRGBColorSpace});const ts=new T.Scene();ts.environment=env.texture;ts.background=new T.Color(0xe9e4da);const h=new T.HemisphereLight(0xffffff,0x94836b,2.5),l=new T.DirectionalLight(0xfff3e4,3),r=new T.DirectionalLight(0xe1eaff,2);l.position.set(-1,1,2);r.position.set(1,1,-1);ts.add(h,l,r);const tc=new T.PerspectiveCamera(34,288/210,.001,10),raw=new Uint8Array(288*210*4),flipped=new Uint8ClampedArray(raw.length),c=document.createElement('canvas');c.width=288;c.height=210;const ctx=c.getContext('2d');for(const meta of D.hats){try{const a=await loadAsset(meta),m=new T.Mesh(a.geometry,a.material);const box=a.geometry.boundingBox,center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());m.position.copy(center).multiplyScalar(-1);ts.add(m);tc.position.copy(new T.Vector3(1,.65,1.5).normalize().multiplyScalar(Math.max(size.y,size.x/(288/210),size.z)*2.05));tc.lookAt(0,0,0);renderer.setRenderTarget(rt);renderer.render(ts,tc);renderer.readRenderTargetPixels(rt,0,0,288,210,raw);renderer.setRenderTarget(null);for(let y=0;y<210;y++)flipped.set(raw.subarray(y*288*4,(y+1)*288*4),(209-y)*288*4);ctx.putImageData(new ImageData(flipped,288,210),0,0);const img=document.querySelector(`.hat-card[data-id="${meta.id}"] img`);img.src=c.toDataURL('image/webp',.87);img.dataset.rendered='true';ts.remove(m);disposeAsset(a);thumbsReady++;requestRender();await next();}catch(e){message('缩略图生成失败：'+meta.title,true);throw e;}}rt.dispose();$('count').textContent=D.hats.length+' 款真实三维';}
async function boot(){const bytes=Uint8Array.from(atob($('payload').textContent.trim()),c=>c.charCodeAt(0));D=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());$('build-id').textContent=D.version+' · '+D.sourceCommit.slice(0,8);$('catalogue').innerHTML=D.hats.map((x,i)=>`<button class="hat-card" data-id="${x.id}" aria-pressed="false"><div class="thumb"><img alt="${x.title}的真实三维缩略图"><span>${String(i+1).padStart(2,'0')}</span></div><strong>${x.title}</strong><small>${x.category} · ${x.author}</small></button>`).join('');$('catalogue').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)select(b.dataset.id).catch(fatal);});$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.hat-card').forEach(x=>x.hidden=b.dataset.category!=='all'&&D.hats.find(h=>h.id===x.dataset.id).category!==b.dataset.category);});
 $('head-select').innerHTML=D.native.heads.map((h,i)=>`<option value="${i}">${h.title}</option>`).join('');$('head-select').onchange=async()=>{state.head=Number($('head-select').value);await headGeometry();apply();frame();persist();};
 for(const k of['width','depth','height','lift','tilt','roughness','detail','sheen'])$(k).oninput=()=>{state[k]=Number($(k).value);changed();};for(const el of document.querySelectorAll('[data-dye]'))el.onclick=()=>{state.dye=el.dataset.dye;changed();};for(const el of document.querySelectorAll('[data-light]'))el.onclick=()=>{state.light=el.dataset.light;apply();persist();};for(const el of document.querySelectorAll('[data-layer]'))el.onclick=()=>{state.layer=el.dataset.layer;apply();};for(const el of document.querySelectorAll('[data-camera]'))el.onclick=()=>frame(el.dataset.camera);
 for(const view of['wear','product'])$(view).onclick=()=>{state.view=view;apply();frame();persist();};$('rotate').onclick=()=>{rotating=!rotating;$('rotate').setAttribute('aria-pressed',String(rotating));requestRender();};$('reset').onclick=()=>select(state.id).catch(fatal);const stopCompare=()=>{if(compare){compare=false;apply();$('compare').classList.remove('holding');}};$('compare').onpointerdown=e=>{e.preventDefault();compare=true;$('compare').setPointerCapture(e.pointerId);$('compare').classList.add('holding');apply();};$('compare').onpointerup=stopCompare;$('compare').onpointercancel=stopCompare;window.addEventListener('blur',stopCompare);
 $('export').onclick=()=>download('hat-'+state.id+'.json',JSON.stringify(recipe(),null,2));$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const file=$('file').files[0];if(!file)return;if(file.size>100000)throw Error('配方文件过大');await restore(JSON.parse(await file.text()));message('配方已恢复');}catch(e){message(e.message,true);}finally{$('file').value='';}};
 $('about').onclick=()=>$('about-dialog').showModal();$('close-dialog').onclick=()=>$('about-dialog').close();$('credits').innerHTML=D.hats.map(x=>`<p>${x.title}：${x.author} · ${x.licence}</p>`).join('');
 let start={...DEFAULT};try{const saved=localStorage.getItem(storage);if(saved)start=validate(JSON.parse(saved));}catch(e){}
 const requested=new URL(location.href).searchParams.get('hat');if(requested&&D.hats.some(x=>x.id===requested))start={...DEFAULT,id:requested};await select(start.id,start);await thumbnails();
 window.hatLab={version:D.version,sourceCommit:D.sourceCommit,ready:()=>ready&&!busy,thumbnails:()=>thumbsReady,catalogue:()=>D.hats.map(({id,title,author,licence})=>({id,title,author,licence})),select,metrics,recipe,restore,validate,frame,set:values=>{state=validate({...recipe(),settings:{...state,...values}});apply();return metrics();},headHashes:()=>D.native.heads.map(h=>({id:h.id,hash:h.fullPositionsSHA256})),headPositions:()=>Array.from(person.geometry.attributes.position.array),currentPositions:()=>Array.from(hat.geometry.attributes.position.array),render:()=>{render();return renderer.domElement.toDataURL('image/png');}};
 $('loading').hidden=true;requestRender();
}
function fatal(e){console.error(e);message('运行失败：'+e.message,true);$('loading').hidden=false;$('loading').textContent='未完成载入：'+e.message;}
boot().catch(fatal);
