const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),{execFileSync}=require('child_process'),assert=require('assert/strict'),{PNG}=require('pngjs');
const out='/tmp/skin-evidence',sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const relative='skin-quality-lab/emily-transfer/preview.html',raw='https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/'+sha+'/'+relative;
const urls=['https://htmlpreview.github.io/?'+raw,'https://raw.githack.com/haihao0307/Humanoid-Rig-Lab-Next/'+sha+'/'+relative];
const report={version:'ET01',publishedCommit:sha,networkInterception:false,localServer:false,physicalMobileDevice:false,attempts:[]};let browser;
(async()=>{browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let page;
for(const url of urls){page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});const attempt={url,errors:[],failedRequests:[]};report.attempts.push(attempt);page.on('pageerror',e=>attempt.errors.push(e.message));page.on('requestfailed',r=>attempt.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,{},{timeout:240000});await page.evaluate(()=>__SKIN_LAB__.render());let data=await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL());let p=PNG.sync.read(Buffer.from(data.split(',')[1],'base64')),skin=0;for(let i=0;i<p.data.length;i+=4)if(p.data[i]>65&&p.data[i]>p.data[i+1]*1.08&&p.data[i]>p.data[i+2]*1.15)skin++;assert(skin/(p.width*p.height)>.05,'Public canvas is empty');assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/1.0.0');assert.deepEqual(attempt.errors,[]);await page.screenshot({path:out+'/public-desktop.png',timeout:90000});await page.selectOption('#transferMode','split');await page.click('[data-method="enhanced"]');await page.evaluate(()=>__SKIN_LAB__.render());await page.screenshot({path:out+'/public-live-comparison.png',timeout:90000});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);await page.click('[data-camera="portrait"]');await page.selectOption('#transferMode','full').catch(async()=>{await page.click('#mobileToggle');await page.selectOption('#transferMode','full');await page.click('#mobileToggle');});await page.evaluate(()=>__SKIN_LAB__.render());await page.screenshot({path:out+'/public-mobile-viewport.png',timeout:90000});attempt.passed=true;report.passed=true;report.url=url;report.runtime=await page.evaluate(()=>__SKIN_LAB__.state);break;
}catch(e){attempt.passed=false;attempt.failure=String(e);await page.screenshot({path:out+'/public-failure-'+report.attempts.length+'.png',timeout:60000}).catch(()=>{});await page.close();}}
fs.writeFileSync(out+'/public-report.json',JSON.stringify(report,null,2));fs.writeFileSync(out+'/OPEN_WEBSITE.txt',report.url||'PUBLIC VALIDATION FAILED');assert(report.passed,'No public preview passed real browser validation');console.log('PUBLIC_DELIVERY_PASS',JSON.stringify(report));
})().catch(e=>{console.error(e);process.exitCode=1;fs.writeFileSync(out+'/public-report.json',JSON.stringify({...report,failure:String(e)},null,2));}).finally(async()=>{if(browser)await browser.close();});
