const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const dir=__dirname,root=path.resolve(dir,'../..'),out='/tmp/skin-evidence';
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(dir+'/evidence',{recursive:true});
function stats(buf){const p=PNG.sync.read(buf),bins=new Set();let sum=0,sum2=0,skin=0;for(let i=0;i<p.data.length;i+=4){let r=p.data[i],g=p.data[i+1],b=p.data[i+2],v=(r+g+b)/3;sum+=v;sum2+=v*v;bins.add((r>>3)*1024+(g>>3)*32+(b>>3));if(r>g*1.08&&r>b*1.15&&r>65)skin++;}let n=p.width*p.height;return {width:p.width,height:p.height,colorBins:bins.size,mean:sum/n,deviation:Math.sqrt(Math.max(0,sum2/n-(sum/n)**2)),skinFraction:skin/n};}
function diff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);assert.equal(a.width,b.width);assert.equal(a.height,b.height);let sum=0,changed=0;for(let i=0;i<a.data.length;i+=4){let d=Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2]);sum+=d;if(d>3)changed++;}return {meanAbsolute:sum/(a.width*a.height*3),changedFraction:changed/(a.width*a.height)};}
const mime={'.html':'text/html','.js':'application/javascript','.json':'application/json','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.glb':'model/gltf-binary','.bin':'application/octet-stream'};
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}const st=fs.statSync(f);if(!st.isFile())throw Error('Not a file');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);}catch(e){res.writeHead(404).end('Not found');}});
let browser,page;const report={version:'ET01',sourceCommit:process.env.GITHUB_SHA,device:'headless Chromium / SwiftShader software rendering',realMobileDeviceTested:false,errors:[],consoleErrors:[],requests:[],checks:{},differences:{}};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.setDefaultTimeout(45000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('request',r=>report.requests.push(r.url()));
const url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,{},{timeout:240000});await page.waitForTimeout(2500);
async function canvas(name){await page.evaluate(()=>window.__SKIN_LAB__.render());const data=await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL('image/png'));let b=Buffer.from(data.split(',')[1],'base64');if(name)fs.writeFileSync(out+'/'+name+'.png',b);return b;}
async function shot(name){await canvas();await page.screenshot({path:out+'/'+name+'.png',timeout:90000});}
report.runtime=await page.evaluate(()=>({state:window.__SKIN_LAB__.state,values:window.__SKIN_LAB__.values}));assert.equal(report.runtime.state.version,'emily-transfer/1.0.0');assert.equal(await page.locator('#viewport canvas').count(),1);const beauty=await canvas('01-emily-method-canvas');report.checks.render=stats(beauty);assert(report.checks.render.colorBins>250,'Canvas is empty or flat');assert(report.checks.render.skinFraction>.05,'No visible skin-like subject');await shot('01-emily-method-desktop');
const invariant=await page.evaluate(()=>__EMILY_TRANSFER__.invariants());await page.selectOption('#transferMode','base');const base=await canvas('02-same-model-baseline');report.differences.referenceVsBase=diff(beauty,base);assert(report.differences.referenceVsBase.meanAbsolute>.05,'Reference method has no visual effect');assert.deepEqual(await page.evaluate(()=>__EMILY_TRANSFER__.invariants()),invariant);
await page.selectOption('#transferMode','full');await page.click('[data-method="enhanced"]');const enhanced=await canvas('03-enhanced-canvas');report.differences.enhancedVsReference=diff(enhanced,beauty);assert(report.differences.enhancedVsReference.meanAbsolute>.01);await shot('03-enhanced-desktop');
await page.selectOption('#transferMode','split');const split=await canvas('04-live-wipe');await page.locator('#wipe').evaluate(el=>{el.value='72';el.dispatchEvent(new Event('input',{bubbles:true}));});const moved=await canvas();report.differences.movingWipe=diff(split,moved);assert(report.differences.movingWipe.changedFraction>.0001,'Live wipe does not move');await shot('04-live-wipe-desktop');assert.deepEqual(await page.evaluate(()=>__EMILY_TRANSFER__.invariants()),invariant);
await page.selectOption('#transferMode','full');await page.click('[data-camera="cheek"]');await page.waitForTimeout(1000);const cheek=await canvas('05-cheek-macro');await shot('05-cheek-macro-desktop');await page.uncheck('#feature-detail');let without=await canvas('06-without-microdetail');report.differences.microDetail=diff(cheek,without);assert(report.differences.microDetail.meanAbsolute>.01,'Microdetail toggle does not render');await page.check('#feature-detail');
await page.uncheck('#feature-diffusion');without=await canvas('07-without-diffusion');report.differences.diffusion=diff(cheek,without);assert(report.differences.diffusion.meanAbsolute>.001,'Diffusion toggle does not render');await page.check('#feature-diffusion');
await page.uncheck('#feature-reflection');without=await canvas('08-without-oil-layer');report.differences.reflection=diff(cheek,without);assert(report.differences.reflection.meanAbsolute>.001,'Oil toggle does not render');await page.check('#feature-reflection');
await page.click('[data-camera="ear"]');await page.selectOption('#lightPreset','back');await page.waitForTimeout(700);await shot('09-ear-backlight');report.checks.earView=true;
await page.evaluate(()=>{__SKIN_LAB__.set({roughness:.61,pigment:.4,wrap:.73});__EMILY_TRANSFER__.setMode('split');});await page.click('#save');await page.evaluate(()=>{__SKIN_LAB__.set({roughness:.3,pigment:.1});__EMILY_TRANSFER__.setMethod('emily');});await page.click('#restore');const restored=await page.evaluate(()=>({roughness:__SKIN_LAB__.values.roughness,pigment:__SKIN_LAB__.values.pigment,method:__EMILY_TRANSFER__.transfer.method,mode:__EMILY_TRANSFER__.transfer.mode}));assert.equal(restored.roughness,.61);assert.equal(restored.pigment,.4);assert.equal(restored.method,'enhanced');assert.equal(restored.mode,'split');report.checks.saveRestore=restored;
await page.click('#reset');await page.selectOption('#quality','medium');await canvas();assert.equal(await page.locator('#transferMode').inputValue(),'full');assert.equal(await page.evaluate(()=>__EMILY_TRANSFER__.transfer.method),'emily');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);await page.click('[data-camera="portrait"]');await canvas();await shot('10-mobile-viewport');await page.click('#mobileToggle');assert(await page.locator('.side').isVisible());await page.click('[data-method="enhanced"]');await page.selectOption('#transferMode','split');await canvas();await shot('11-mobile-controls');report.checks.mobile={width:390,height:844,panelToggle:true,methodSwitch:true,liveWipe:true,physicalDevice:false};
assert.equal(report.errors.length,0,'Page script errors');assert.equal(report.consoleErrors.length,0,'Rendering errors');assert(!report.requests.some(u=>u.includes('alteredqualia.com')),'Target demo unexpectedly loads original Emily assets');report.checks.noEmilyAssetRequests=true;report.checks.sameGeometryColorLighting=true;report.passed=true;
const data=JSON.stringify(report,null,2);fs.writeFileSync(out+'/qa-report.json',data);fs.writeFileSync(dir+'/qa-report.json',data);for(const f of ['01-emily-method-desktop.png','03-enhanced-desktop.png','04-live-wipe-desktop.png','05-cheek-macro-desktop.png','09-ear-backlight.png','10-mobile-viewport.png'])fs.copyFileSync(out+'/'+f,dir+'/evidence/'+f);for(const f of ['index.html','app.js','preview.html','BUILD_MANIFEST.json','EmilyTransferKernel.js','build.cjs','transfer-runtime.js'])fs.copyFileSync(dir+'/'+f,out+'/'+f);console.log('TRANSFER_QA_PASS',JSON.stringify({render:report.checks.render,differences:report.differences,errors:report.errors,mobile:report.checks.mobile}));
})().catch(async e=>{report.passed=false;report.failure=e.stack;console.error(e);fs.writeFileSync(out+'/qa-failure.json',JSON.stringify(report,null,2));if(page)await page.screenshot({path:out+'/failure.png',timeout:60000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
