const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),{PNG}=require('pngjs');
const out=path.resolve(process.env.SKIN_QA_DIR||'r02-evidence');fs.mkdirSync(out,{recursive:true});
const url=process.env.SKIN_QA_URL||'http://127.0.0.1:8793/skin-quality-lab/r02/index.html';
const report={url,version:'skin-quality-lab/r02.0',desktop:[1440,1040],mobileViewport:[390,844],physicalMobile:false,hardwarePerformance:false,errors:[],checks:[],shots:[]};let browser,page;
function delta(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let sum=0,n=0;for(let i=0;i<a.data.length;i+=4)for(let c=0;c<3;c++){sum+=Math.abs(a.data[i+c]-b.data[i+c]);n++}return sum/n;}
async function state(){return page.evaluate(()=>({state:window.__SKIN_LAB__?.state,values:window.__SKIN_LAB__?.values,body:document.body.innerText.slice(-1000)}));}
(async()=>{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)report.errors.push('HTTP '+r.status()+': '+r.url())});
 await page.goto(url,{waitUntil:'networkidle',timeout:120000});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready,null,{timeout:90000});await page.waitForTimeout(900);
 async function snap(name){await page.evaluate(()=>window.__SKIN_LAB__.render());await page.waitForTimeout(400);await page.screenshot({path:out+'/'+name+'.png'});report.shots.push(name);return page.locator('canvas').screenshot()}
 report.initial=await state();await snap('01-portrait');await page.click('[data-camera="cheek"]');const original=await snap('02-cheek');
 for(const [key,v] of [['micro',0],['meso',0],['sss',0],['oil',.8]]){await page.evaluate(([key,v])=>window.__SKIN_LAB__.set({...window.__SKIN_LAB__.defaults,[key]:v}),[key,v]);const changed=await snap('03-'+key);const d=delta(original,changed);report.checks.push({name:key+'-pixel-response',difference:d,pass:d>.03});}
 await page.click('#reset');await page.click('[data-camera="ear"]');await page.selectOption('#lightPreset','back');const trans=await snap('04-transmission');await page.evaluate(()=>window.__SKIN_LAB__.set({translucency:0}));const opaque=await snap('05-no-transmission');report.checks.push({name:'lightspace-transmission-response',difference:delta(trans,opaque),pass:delta(trans,opaque)>.005});
 await page.click('#reset');await page.click('[data-camera="cheek"]');await page.selectOption('#lightPreset','raking');await snap('06-raking');await page.selectOption('#layer','normal');await snap('07-normal');await page.selectOption('#layer','specular');await snap('08-specular');
 await page.click('#reset');await page.click('#save');await page.locator('#micro').fill('1.6');await page.locator('#micro').dispatchEvent('input');await page.click('#restore');report.checks.push({name:'save-restore-new-fields',pass:await page.evaluate(()=>window.__SKIN_LAB__.values.micro===window.__SKIN_LAB__.defaults.micro)});
 await page.click('[data-camera="cheek"]');await page.evaluate(()=>window.__SKIN_LAB__.render());const before=await page.locator('canvas').screenshot();await page.locator('#compare').hover();await page.mouse.down();await page.waitForTimeout(600);const cmp=await page.locator('canvas').screenshot();await page.mouse.up();report.checks.push({name:'held-comparison',difference:delta(before,cmp),pass:delta(before,cmp)>.1});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__SKIN_LAB__.setCamera('portrait'));await snap('09-mobile');await page.click('#mobileToggle');await snap('10-mobile-panel');report.checks.push({name:'mobile-panel-layout',pass:await page.locator('.side').isVisible()&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)});
 report.final=await state();report.pass=report.errors.length===0&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();if(!report.pass)process.exitCode=1;
})().catch(async e=>{report.fatal=String(e);try{await page.screenshot({path:out+'/fatal.png'});report.final=await state()}catch{}fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser?.close();console.error(e);process.exitCode=1});
