import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const deps=process.env.SHOE_DEPS||'/mnt/data/shoe-deps';
execFileSync(process.execPath,[path.join(root,'tools/bake.mjs')],{stdio:'inherit',env:process.env});
const result=await build({entryPoints:[path.join(root,'src/app.mjs')],bundle:true,minify:true,format:'iife',write:false,legalComments:'inline',target:['chrome110','safari17'],logLevel:'info'});
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
html=html.replace(/<link rel="stylesheet" href="\.\/style\.css">/,()=>'<style>'+fs.readFileSync(path.join(root,'style.css'),'utf8')+'</style>');
html=html.replace(/<script type="importmap">[\s\S]*?<\/script>/,'');
const buildId=process.env.GITHUB_SHA||'local-build';
const encoded=fs.readFileSync(path.join(root,'assets/body-pack.json.gz')).toString('base64');
const script=result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
html=html.replace(/<script type="module" src="\.\/src\/app\.mjs"><\/script>/,()=>`<script id="body-data" type="application/octet-stream">${encoded}</script><script>globalThis.__SHOE_BUILD__=${JSON.stringify(buildId)};${script}</script>`);
if(html.includes('src="./src/app.mjs"')||html.includes('href="./style.css"')||!html.includes('id="body-data"'))throw Error('Single-file embedding failed');
fs.writeFileSync(path.join(root,'preview.html'),html);fs.mkdirSync(path.join(root,'licenses'),{recursive:true});
fs.copyFileSync(path.join(deps,'node_modules/three/LICENSE'),path.join(root,'licenses/THREE-MIT.txt'));fs.copyFileSync(path.join(deps,'human/NOTICE.md'),path.join(root,'licenses/HUMAN-SOURCE-NOTICE.md'));fs.copyFileSync(path.join(deps,'human/INTAKE.json'),path.join(root,'assets/SOURCE-INTAKE.json'));
const sha=b=>createHash('sha256').update(b).digest('hex');const files=['index.html','style.css','src/app.mjs','src/geometry.mjs','src/materials.mjs','tools/bake.mjs','tools/build.mjs','tools/test.mjs','preview.html','assets/body-pack.json.gz','assets/BODY-PROVENANCE.json'].map(p=>({path:p,bytes:fs.statSync(path.join(root,p)).size,sha256:sha(fs.readFileSync(path.join(root,p)))}));
const manifest={schema:'kaopu-shoe-build/1',version:'R01.0',sourceBuildCommit:buildId,createdAt:new Date().toISOString(),humanSourceCommit:'900d68a6206b9f8d220dff5a6c34fb0aa683deb5',renderer:'three 0.179.1',scope:'Static visual candidate. Not production, medical, comfort or collision certified.',shoeMeshSource:'Original procedural construction, no imported shoe mesh.',personScope:'Three static unmodified Anny body snapshots. Not the full GNM/MHR/live common-person workbench.',files};fs.writeFileSync(path.join(root,'BUILD_MANIFEST.json'),JSON.stringify(manifest,null,2));
console.log('Built frozen offline-capable preview',html.length,'characters');
