import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const evidence=path.join(root,'evidence');fs.mkdirSync(evidence,{recursive:true});
const report={schema:'kaopu-shoe-browser-qa/1',buildCommit:process.env.GITHUB_SHA||'local',startedAt:new Date().toISOString(),checks:[],errors:[],scope:'Desktop Chromium software rendering; phone viewport emulation, not a physical device. Geometry checks are not intersection or comfort certification.'};
const hash=b=>createHash('sha256').update(b).digest('hex');
function check(name,pass,details){report.checks.push({name,pass:!!pass,details});if(!pass)throw Error('CHECK FAILED: '+name);console.log('PASS',name);}
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,'preview.html')));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const target=process.env.SHOE_PUBLIC_URL||`http://127.0.0.1:${server.address().port}/preview.html`;let browser,page;
try{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const response=await page.goto(target,{waitUntil:'domcontentloaded',timeout:90000});check('page-response',response.ok(),{url:target,status:response.status()});
 await page.waitForFunction(()=>window.SHOE_QA?.ready,{},{timeout:90000});await page.waitForFunction(()=>window.SHOE_QA.stats().thumbReady,{},{timeout:90000});
 const settle=async()=>{await page.evaluate(()=>SHOE_QA.render());await page.waitForTimeout(180);};await settle();await page.locator('#advanced').evaluate(e=>e.open=true);
 check('six-real-3d-thumbnails',await page.locator('.shoe-card img').evaluateAll(imgs=>imgs.length===6&&imgs.every(i=>i.complete&&i.naturalWidth>10&&i.src.startsWith('data:image/'))));
 await page.screenshot({path:path.join(evidence,'01-derby-desktop.png')});report.initialStats=await page.evaluate(()=>SHOE_QA.stats());check('initial-finite-geometry',report.initialStats.invalid===0,report.initialStats);
 const styles=['derby','loafer','sneaker','chelsea','sandal','wholecut'];report.styleStats=[];
 for(const style of styles){await page.locator(`[data-style="${style}"]`).click();await settle();const stats=await page.evaluate(()=>SHOE_QA.stats());check('style-'+style,stats.style===style&&stats.invalid===0&&stats.triangles>1000,{triangles:stats.triangles});report.styleStats.push(stats);await page.screenshot({path:path.join(evidence,`style-${style}.png`)});}
 for(const person of ['standard','slender','broad']){await page.locator(`[data-person="${person}"]`).click();await page.locator('[data-mode="wear"]').click();for(const style of styles){await page.locator(`[data-style="${style}"]`).click();await settle();const s=await page.evaluate(()=>SHOE_QA.stats());check(`wear-${person}-${style}`,s.invalid===0&&s.person===person&&s.mode==='wear',{dimensions:s.shoeDimensions,bodyPositionSha:s.bodyPositionSha});}}
 await page.locator('[data-person="standard"]').click();await page.locator('[data-style="derby"]').click();
 for(const mode of ['wear','person','exploded','measure','last','studio']){await page.locator(`[data-mode="${mode}"]`).click();await settle();check('mode-'+mode,await page.evaluate(m=>SHOE_QA.stats().mode===m&&SHOE_QA.stats().invalid===0,mode));await page.screenshot({path:path.join(evidence,`mode-${mode}.png`)});}
 for(const view of ['side','front','top','sole','macro','hero']){await page.locator(`[data-view="${view}"]`).click();await settle();const buffer=await page.locator('#viewport canvas').screenshot();check('camera-'+view,buffer.length>1000,{pngHash:hash(buffer),bytes:buffer.length});if(view==='macro'||view==='sole')await page.screenshot({path:path.join(evidence,`camera-${view}.png`)});}
 const materialHashes=[];for(const material of ['smooth','grain','suede','weave','patent']){await page.locator(`[data-material="${material}"]`).click();await settle();materialHashes.push(hash(await page.locator('#viewport canvas').screenshot()));}check('five-material-images-change',new Set(materialHashes).size===5,materialHashes);
 await page.locator('[data-colour="#191b1e"]').click();check('colour-control',await page.evaluate(()=>SHOE_QA.config().colour==='#191b1e'));
 await page.locator('[data-light="dark"]').click();await settle();check('dark-studio',await page.evaluate(()=>SHOE_QA.config().light==='dark'));await page.screenshot({path:path.join(evidence,'studio-dark.png')});
 await page.locator('#reset').click();await page.evaluate(()=>SHOE_QA.setFit({toe:20,ease:6,instep:5}));await settle();const fitted=await page.evaluate(()=>SHOE_QA.stats());check('fit-dimensions-change',fitted.config.fit.toe===20&&fitted.shoeDimensions[0].length>report.initialStats.shoeDimensions[0].length,{before:report.initialStats.shoeDimensions[0],after:fitted.shoeDimensions[0]});
 const rejected=await page.evaluate(()=>{const before=JSON.stringify(SHOE_QA.config());let rejects=0;for(const edit of [{schema:'wrong'},{fit:{toe:-20,ease:4,instep:3}},{source:{commit:'wrong'}}]){try{SHOE_QA.validateConfig({...SHOE_QA.config(),...edit});}catch{rejects++;}}return {rejects,unchanged:before===JSON.stringify(SHOE_QA.config())};});check('invalid-import-transaction',rejected.rejects===3&&rejected.unchanged,rejected);
 await page.locator('#save').click();await page.locator('#reset').click();await page.locator('#restore').click();check('save-reset-restore',await page.evaluate(()=>SHOE_QA.config().fit.toe===20));
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);const saved=path.join(evidence,'exported-config.json');await download.saveAs(saved);const config=JSON.parse(fs.readFileSync(saved));check('versioned-config-export',config.schema==='kaopu-shoe-config/1'&&config.fit.toe===20&&config.source.commit===report.initialStats.sourceCommit);
 await page.locator('#reset').click();await page.locator('#import-file').setInputFiles(saved);await page.waitForTimeout(250);check('config-file-import',await page.evaluate(()=>SHOE_QA.config().fit.toe===20));
 await page.locator('#reset').click();await settle();const beforeOrbit=await page.locator('#viewport canvas').screenshot();const rect=await page.locator('#viewport canvas').boundingBox();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.6);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.66,rect.y+rect.height*.64,{steps:8});await page.mouse.up();await page.waitForTimeout(400);await settle();check('pointer-orbit-changes-image',hash(beforeOrbit)!==hash(await page.locator('#viewport canvas').screenshot()));
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mobile=await context.newPage();mobile.on('pageerror',e=>report.errors.push('mobile '+e));await mobile.goto(target,{waitUntil:'domcontentloaded',timeout:90000});await mobile.waitForFunction(()=>window.SHOE_QA?.ready,{},{timeout:90000});await mobile.waitForFunction(()=>SHOE_QA.stats().thumbReady,{},{timeout:90000});await mobile.evaluate(()=>SHOE_QA.render());await mobile.screenshot({path:path.join(evidence,'mobile-390x844.png'),fullPage:true});const mobileMetrics=await mobile.evaluate(()=>({inner:innerWidth,scroll:document.documentElement.scrollWidth,stats:SHOE_QA.stats()}));check('phone-viewport-no-horizontal-overflow',mobileMetrics.scroll<=mobileMetrics.inner+1,mobileMetrics);check('phone-viewport-rendered',mobileMetrics.stats.rendered>0&&mobileMetrics.stats.invalid===0);await context.close();
 check('no-javascript-or-shader-errors',report.errors.length===0,report.errors);report.status='passed';report.finishedAt=new Date().toISOString();
}catch(e){report.status='failed';report.failure=String(e);console.error(e);try{await page?.screenshot({path:path.join(evidence,'FAILURE.png')});}catch{}process.exitCode=1;}
finally{fs.writeFileSync(path.join(evidence,'QA.json'),JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));console.log('QA_RESULT',report.status,report.checks.length,'checks');}
