const {chromium}=require('playwright');const fs=require('node:fs'),crypto=require('node:crypto');
fs.mkdirSync('evidence',{recursive:true});
const report={schema:'kaopu/observed-surface-qa@2',commit:process.env.PREVIEW_SHA,publicVerified:false,requestedFullCharacterComplete:false,visualAcceptance:false,desktop:{width:1200,height:900},mobileViewport:{width:390,height:844,physicalDevice:false},errors:[],consoleErrors:[],requests:[],checks:[]};
const save=()=>fs.writeFileSync('evidence/qa.json',JSON.stringify(report,null,2));const stage=s=>{report.stage=s;save();console.log(s)};const timer=setTimeout(()=>{report.fatal='300 second timeout at '+report.stage;save();process.exit(1)},300000);
(async()=>{
 const raw=`https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/${report.commit}/studies/skin-atelier-r2/observed-surface.html`,url='https://htmlpreview.github.io/?'+raw;report.url=url;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:report.desktop,deviceScaleFactor:1});const page=await context.newPage();
 page.on('pageerror',e=>{report.errors.push(String(e));save()});page.on('console',m=>{if(m.type()==='error'){report.consoleErrors.push(m.text());save()}});page.on('requestfinished',r=>report.requests.push(r.url()));
 stage('public byte comparison');const r=await context.request.get(raw,{timeout:45000});const bytes=await r.body(),local=fs.readFileSync('studies/skin-atelier-r2/observed-surface.html');report.byteMatch=bytes.equals(local);report.sha256=crypto.createHash('sha256').update(bytes).digest('hex');report.bytes=bytes.length;save();if(!report.byteMatch)throw Error('Public bytes do not match the committed file');
 stage('public renderer');await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>window.__surface?.ready||window.__surfaceErrors?.length,{timeout:90000,polling:500});report.publicVerified=await page.evaluate(()=>window.__surface?.ready===true);report.runtime=await page.evaluate(()=>({ready:window.__surface?.ready,version:window.__surface?.version,stats:window.__surface?.stats,errors:window.__surfaceErrors||[],videoElements:document.querySelectorAll('video').length,visibleLimits:document.querySelector('.limits')?.textContent}));save();if(!report.publicVerified)throw Error(JSON.stringify(report.runtime));
 async function shot(name){stage('capture '+name);await page.evaluate(()=>window.__surface.draw());await page.screenshot({path:`evidence/${name}.png`,timeout:45000});const raw=await page.evaluate(()=>window.__surface.canvas.toDataURL('image/png'));fs.writeFileSync(`evidence/${name}-canvas.png`,Buffer.from(raw.split(',')[1],'base64'));report.checks.push({name,state:await page.evaluate(()=>({...window.__surface.state}))});save()}
 await shot('01-desktop');
 for(const [i,v] of ['skin','eyes','hair'].entries()){await page.locator(`[data-view="${v}"]`).click();await shot(`0${i+2}-${v}`)}
 await page.locator('#home').click();await page.locator('#angle').evaluate(e=>{e.value='23';e.dispatchEvent(new Event('input',{bubbles:true}))});await shot('05-oblique');
 await page.locator('#home').click();const before=await page.evaluate(()=>({...window.__surface.state}));await page.mouse.move(500,430);await page.mouse.down();await page.mouse.move(420,445,{steps:3});await page.mouse.up();await page.mouse.wheel(0,-150);await page.waitForTimeout(150);const after=await page.evaluate(()=>({...window.__surface.state}));report.nativeRotation=before.angle!==after.angle;report.nativeZoom=before.zoom!==after.zoom;
 await page.locator('[data-mode="1"]').click();await shot('06-recovered-surface');await page.locator('#light').evaluate(e=>{e.value='1.6';e.dispatchEvent(new Event('input',{bubbles:true}))});report.diagnosticLight=await page.evaluate(()=>window.__surface.state.light===1.6);
 await page.locator('#wire').check();await shot('07-triangles');await page.locator('#home').click();await page.waitForTimeout(150);const n1=await page.evaluate(()=>window.__surface.frames);await page.waitForTimeout(250);const n2=await page.evaluate(()=>window.__surface.frames);report.idleStops=n1===n2;
 await page.locator('#auto').click();const a1=await page.evaluate(()=>window.__surface.state.angle);await page.waitForTimeout(400);const a2=await page.evaluate(()=>window.__surface.state.angle);report.turntableChanged=a1!==a2;await page.locator('#auto').click();
 await page.setViewportSize(report.mobileViewport);await page.evaluate(()=>{window.dispatchEvent(new Event('resize'));window.__surface.view('portrait');window.__surface.update({angle:4.8});window.__surface.draw()});await shot('08-mobile');await page.locator('#controls').click();report.mobilePanel=await page.locator('#panel').evaluate(e=>e.classList.contains('open'));await shot('09-mobile-controls');
 report.glError=await page.evaluate(()=>window.__surface.gl.getError());report.passed=report.publicVerified&&report.byteMatch&&report.nativeRotation&&report.nativeZoom&&report.idleStops&&report.turntableChanged&&report.mobilePanel&&!report.errors.length&&!report.runtime.errors.length&&report.glError===0;stage('complete');console.log(JSON.stringify(report,null,2));clearTimeout(timer);await browser.close();if(!report.passed)process.exitCode=1;
})().catch(e=>{report.fatal=String(e.stack||e);save();console.error(e);process.exit(1)});
