(()=>{
'use strict';
const H=window.__BIRD_R012_HANDOFF,CLOCK=window.__BIRD_R011_API,EXEC=window.__BIRD_R010_API;
if(!H||!CLOCK||!EXEC)throw new Error('R0.12 缺少 R0.10/R0.11 合同链');
const $=id=>document.getElementById(id),D=CLOCK.contract.clock.phaseTicksPerCycle;
const controls=H.controlOrder,active=H.activeChannelOrder,locked=H.lockedChannelOrder,env=EXEC.sourceEnvelopes;
const MAGIC=H.packet.magicAscii,BYTES=H.packet.byteLength;
const te=new TextEncoder(),td=new TextDecoder();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const q01=v=>{const n=Number(v);return Math.round(clamp(Number.isFinite(n)?n:0,0,1)*65535)};
const u32=(v,name)=>{const n=Number(v);if(!Number.isInteger(n)||n<0||n>0xffffffff)throw new Error(name+' uint32');return n>>>0};
const dq01=q=>q/65535;
const qChannel=(n,v)=>{const e=env[n];return Math.round((clamp(v,e.min,e.max)-e.min)/(e.max-e.min)*65535)};
const dqChannel=(n,q)=>{const e=env[n];return e.min+(q/65535)*(e.max-e.min)};
function fnv1a(bytes,end=62){let h=0x811c9dc5;for(let i=0;i<end;i++){h^=bytes[i];h=Math.imul(h,0x01000193)>>>0}return h>>>0}
function toHex(bytes){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
function fromHex(hex){const s=String(hex).replace(/[^0-9a-f]/gi,'');if(s.length!==BYTES*2)throw new Error('hex length');const out=new Uint8Array(BYTES);for(let i=0;i<BYTES;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
function eventMask(clock,override){if(Number.isInteger(override))return override&0xffff;let mask=0;for(const e of clock.lastEvents||[]){const bit=H.eventBits[e.id];if(bit)mask|=bit}if(!mask&&clock.lastEvent&&H.eventBits[clock.lastEvent])mask|=H.eventBits[clock.lastEvent];return mask&0xffff}
function canonicalClock(input){const src=input||CLOCK.getClock();const c=CLOCK.createClock(src);c.lastEvent=src.lastEvent||null;c.lastEvents=[...(src.lastEvents||[])];c.paused=!!src.paused;return c}
function canonicalControls(input={}){const base=EXEC.getState();const out={};for(const n of controls){const raw=Object.prototype.hasOwnProperty.call(input,n)?input[n]:base.controls[n];out[n]=dq01(q01(raw))}out.interpolation=['smoothstep','linear'].includes(input.interpolation)?input.interpolation:(base.interpolation||'smoothstep');return out}
function encodeSnapshot(input={}){
 const clock=canonicalClock(input.clock),ctrl=canonicalControls(input.controls||{}),phase01=clock.phaseTicks/D;
 const evaluated=EXEC.evaluateAtPhase(phase01,ctrl);if(!evaluated.ok)throw new Error('R0.10 evaluation failed: '+evaluated.error);
 const bytes=new Uint8Array(BYTES),dv=new DataView(bytes.buffer);bytes.set(te.encode(MAGIC),0);dv.setUint16(8,H.packet.schemaVersion,true);
 let flags=4;if(ctrl.interpolation==='linear')flags|=1;if(clock.paused)flags|=2;dv.setUint16(10,flags,true);dv.setUint32(12,u32(clock.cycleIndex,'cycleIndex'),true);dv.setUint16(16,clock.phaseTicks,true);dv.setUint16(18,clock.rateHz,true);dv.setUint32(20,u32(clock.eventSerial,'eventSerial'),true);
 let off=24;for(const n of controls){dv.setUint16(off,q01(ctrl[n]),true);off+=2}
 off=34;for(const n of active){dv.setUint16(off,qChannel(n,evaluated.values[n]),true);off+=2}
 off=56;for(const n of locked){dv.setUint16(off,qChannel(n,evaluated.values[n]),true);off+=2}
 const mask=eventMask(clock,input.eventMask);dv.setUint16(60,mask,true);const checksum=fnv1a(bytes);dv.setUint32(62,checksum,true);
 return{bytes,hex:toHex(bytes),checksum,flags,eventMask:mask,clock,controls:ctrl,values:evaluated.values};
}
function decodePacket(input){const bytes=input instanceof Uint8Array?new Uint8Array(input):fromHex(input);if(bytes.length!==BYTES)throw new Error('packet length');const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(td.decode(bytes.slice(0,8))!==MAGIC)throw new Error('magic');if(dv.getUint16(8,true)!==H.packet.schemaVersion)throw new Error('schema');const checksum=dv.getUint32(62,true),actual=fnv1a(bytes);if(checksum!==actual)throw new Error('checksum');const flags=dv.getUint16(10,true);if(flags&~7)throw new Error('flags');if(!(flags&4))throw new Error('source bounded flag');const cycleIndex=dv.getUint32(12,true),phaseTicks=dv.getUint16(16,true),rateHz=dv.getUint16(18,true),eventSerial=dv.getUint32(20,true);if(phaseTicks>=D)throw new Error('phaseTicks');if(!CLOCK.contract.clock.supportedSampleRatesHz.includes(rateHz))throw new Error('rateHz');
 let off=24;const ctrl={};for(const n of controls){ctrl[n]=dq01(dv.getUint16(off,true));off+=2}ctrl.interpolation=(flags&1)?'linear':'smoothstep';
 const expected=EXEC.evaluateAtPhase(phaseTicks/D,ctrl);if(!expected.ok)throw new Error('re-evaluation');const values={},quantized={};off=34;for(const n of active){const q=dv.getUint16(off,true),qe=qChannel(n,expected.values[n]);if(q!==qe)throw new Error('channel contract '+n);quantized[n]=q;values[n]=dqChannel(n,q);off+=2}off=56;for(const n of locked){const q=dv.getUint16(off,true),qe=qChannel(n,expected.values[n]);if(q!==qe)throw new Error('locked channel contract '+n);quantized[n]=q;values[n]=dqChannel(n,q);off+=2}
 const mask=dv.getUint16(60,true);if(mask&~0xff)throw new Error('event mask');const clock=CLOCK.createClock({rateHz,phaseTicks,cycleIndex,eventSerial,paused:!!(flags&2)});clock.lastEvents=Object.entries(H.eventBits).filter(([,bit])=>mask&bit).map(([id])=>({id}));clock.lastEvent=clock.lastEvents.at(-1)?.id||null;
 const errors={};for(const n of [...active,...locked]){const e=env[n];errors[n]=Math.abs(values[n]-expected.values[n])/(e.max-e.min)}
 return{ok:true,bytes,hex:toHex(bytes),checksum,flags,eventMask:mask,clock,controls:ctrl,values,expected:expected.values,quantized,normalizedErrors:errors,maxNormalizedError:Math.max(...Object.values(errors))};
}
function reencodeDecoded(decoded){return encodeSnapshot({clock:decoded.clock,controls:decoded.controls,eventMask:decoded.eventMask})}
function corrupt(input,index=40,mask=1){const bytes=input instanceof Uint8Array?new Uint8Array(input):fromHex(input);bytes[clamp(Math.floor(index),0,bytes.length-1)]^=mask&255;return bytes}
function restoreSnapshot(decoded){if(!decoded?.ok)throw new Error('decoded packet required');CLOCK.setClock(decoded.clock);EXEC.setControls(decoded.controls);return{clock:CLOCK.getClock(),controls:EXEC.getState()}}
function style(){const s=document.createElement('style');s.textContent=`.r012-card{border:1px solid #28505f;background:#091820;border-radius:10px;padding:10px;margin:8px 0}.r012-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.r012-hex{width:100%;min-height:112px;background:#061219;color:#8fdcf0;border:1px solid #284957;border-radius:8px;padding:8px;font:9px ui-monospace,monospace;resize:vertical;word-break:break-all}.r012-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.r012-grid>div{border:1px solid #244554;background:#0a1821;border-radius:8px;padding:8px}.r012-grid span{display:block;color:#819aa6;font-size:9px}.r012-grid b{display:block;color:#edf7fa;font-size:12px;margin-top:3px}.r012-layout{display:grid;gap:4px}.r012-row{display:grid;grid-template-columns:1.2fr 45px 45px 1fr;gap:5px;padding:6px;border:1px solid #244554;border-radius:7px;font-size:9px}.r012-row span{color:#a9bec7}.r012-row b{color:#79d6ec}.r012-errors{font:9px ui-monospace,monospace;line-height:1.45;color:#94acb7}.r012-good{color:#75d3aa!important}.r012-bad{color:#ff9b91!important}`;document.head.appendChild(s)}
function inject(){document.title='Bird Mother｜Seagull A 精确运行时交接包 R0.12';const t=document.querySelector('.title-block b'),sub=document.querySelector('.title-block small'),pill=document.querySelector('header .pill');if(t)t.textContent='Bird Mother｜Seagull A 精确运行时交接包 R0.12';if(sub)sub.textContent='66 字节｜精确 phaseTicks｜Q16 通道｜FNV-1a｜合同复算｜损坏拒绝';if(pill)pill.textContent='EXACT RUNTIME HANDOFF · 66 BYTES';const left=$('controls'),right=$('analysis');const l=document.createElement('section');l.innerHTML=`<h3>R0.12 交接包</h3><div class="r012-card"><div class="r012-actions"><button id="r012Encode" class="primary">编码当前状态</button><button id="r012Decode">解码并校验</button><button id="r012Corrupt">注入单字节损坏</button><button id="r012Restore">恢复到解码状态</button></div><textarea id="r012Hex" class="r012-hex" spellcheck="false"></textarea><div id="r012Status" class="r010-status">等待编码</div></div>`;left.prepend(l);const r=document.createElement('section');r.innerHTML=`<h3>R0.12 包状态</h3><div class="r012-grid"><div><span>长度</span><b id="r012Bytes">66 bytes</b></div><div><span>校验和</span><b id="r012Checksum">—</b></div><div><span>周期 / 相位刻度</span><b id="r012Clock">—</b></div><div><span>采样率</span><b id="r012Rate">—</b></div><div><span>事件掩码</span><b id="r012Mask">—</b></div><div><span>最大归一误差</span><b id="r012Error">—</b></div></div><h3>字段布局</h3><div class="r012-layout" id="r012Layout"></div><h3>通道量化误差</h3><div class="r012-errors" id="r012Errors">尚未解码</div>`;right.prepend(r);for(const f of H.packet.fields){const d=document.createElement('div');d.className='r012-row';d.innerHTML=`<span>${f.name}</span><b>${f.offset}</b><b>${f.bytes}</b><span>${f.type}</span>`;$('r012Layout').appendChild(d)}const footer=document.querySelector('footer');if(footer&&!footer.textContent.includes('runtimeHandoff=true')){const s=document.createElement('span');s.textContent='runtimeHandoff=true';footer.appendChild(s)}}
style();inject();let encoded=null,decoded=null;
function showDecode(d){$('r012Checksum').textContent='0x'+d.checksum.toString(16).padStart(8,'0');$('r012Clock').textContent=`C${d.clock.cycleIndex} / ${d.clock.phaseTicks}`;$('r012Rate').textContent=d.clock.rateHz+' Hz';$('r012Mask').textContent='0x'+d.eventMask.toString(16).padStart(4,'0');$('r012Error').textContent=d.maxNormalizedError.toExponential(3);$('r012Errors').innerHTML=Object.entries(d.normalizedErrors).map(([n,e])=>`${n.padEnd(28)} ${e.toExponential(3)}`).join('<br>');$('r012Status').textContent='解码通过：校验和、字段范围与 R0.10 通道复算全部一致';$('r012Status').className='r010-status r012-good'}
function encodeCurrent(){encoded=encodeSnapshot();$('r012Hex').value=encoded.hex;decoded=decodePacket(encoded.bytes);showDecode(decoded);return encoded}
$('r012Encode').addEventListener('click',encodeCurrent);$('r012Decode').addEventListener('click',()=>{try{decoded=decodePacket($('r012Hex').value);showDecode(decoded)}catch(error){$('r012Status').textContent='拒绝：'+error.message;$('r012Status').className='r010-status r012-bad'}});$('r012Corrupt').addEventListener('click',()=>{try{const src=encoded||encodeCurrent();const bad=corrupt(src.bytes,40,1);$('r012Hex').value=toHex(bad);decodePacket(bad);$('r012Status').textContent='错误：损坏包未被拒绝';$('r012Status').className='r010-status r012-bad'}catch(error){$('r012Status').textContent='损坏包已拒绝：'+error.message;$('r012Status').className='r010-status r012-good'}});$('r012Restore').addEventListener('click',()=>{try{if(!decoded)decoded=decodePacket($('r012Hex').value);restoreSnapshot(decoded);$('r012Status').textContent='已恢复精确周期、相位刻度、采样率和控制量';$('r012Status').className='r010-status r012-good'}catch(error){$('r012Status').textContent='恢复失败：'+error.message;$('r012Status').className='r010-status r012-bad'}});
encoded=encodeCurrent();const repeat=encodeSnapshot();const deterministic=repeat.hex===encoded.hex,round=decodePacket(encoded.bytes),reencoded=reencodeDecoded(round),roundtrip=reencoded.hex===encoded.hex;window.__BIRD_R012_API={encodeSnapshot,decodePacket,reencodeDecoded,corrupt,restoreSnapshot,toHex,fromHex,fnv1a,contract:H};window.__BIRD_R012_QA={ready:true,version:'R0.12',packetBytes:BYTES,deterministic,roundtrip,maxNormalizedError:round.maxNormalizedError,checksum:round.checksum,externalRuntimeDependencies:0,controllerAffectsSourceMesh:false};Object.assign(window.__BIRD_QA,{runtimeHandoffReady:true,runtimeHandoffVersion:'R0.12'});document.body.dataset.r012Ready='true';
})();
