const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const root=path.resolve(__dirname,'../../..'),out=process.env.EVIDENCE_DIR||'/tmp/et04-evidence';fs.mkdirSync(out,{recursive:true});
const report={version:'ET04',sourceCommit:process.env.GITHUB_SHA||null,publicCommit:process.env.PUBLIC_COMMIT||null,networkInterception:false,physicalMobileDevice:false,renderBackend:'Chromium / SwiftShader',errors:[],consoleErrors:[],failedRequests:[],checks:{}};
let browser,server,page;const requests=[];
function imageDiff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);assert.equal(a.width,b.width);assert.equal(a.height,b.height);let s=0,changed=0;for(let i=0;i<a.data.length;i+=4){let d=0;for(let c=0;c<3;c++)d+=Math.abs(a.data[i+c]-b.data[i+c]);s+=d;if(d>3)changed++;}return {meanRGB:s/(a.width*a.height*3),changedFraction:changed/(a.width*a.height)};}
(async()=>{
 let url=process.env.PUBLIC_URL||null;
 if(!url){server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');const stream=fs.createReadStream(f);stream.on('error',()=>{if(!res.headersSent)res.writeHead(404);res.end();});stream.pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';}
 report.url=url;report.localServer=!!server;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.setDefaultTimeout(60000);
 await page.addInitScript(()=>{window.__EYE_QA_FREEZE__=true;window.__et04BootErrors=[];window.addEventListener('error',e=>window.__et04BootErrors.push(e.message));});
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));page.on('request',r=>requests.push(r.url()));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:90000});
 await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready||window.__et04BootErrors?.length,{},{timeout:180000});
 assert.deepEqual(report.errors,[]);assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/4.0.0');assert.equal(await page.evaluate(()=>__EYES__.version),'eyes/4.0.0');
 async function pixels(){await page.evaluate(()=>__SKIN_LAB__.render());return Buffer.from((await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL('image/png'))).split(',')[1],'base64');}
 async function shot(name){const p=await pixels();fs.writeFileSync(out+'/'+name+'-canvas.png',p);await page.screenshot({path:out+'/'+name+'.png'});return p;}
 assert.equal(await page.locator('canvas').count(),1);
 const portrait=await shot('01-portrait');const p=PNG.sync.read(portrait);const bins=new Set();for(let i=0;i<p.data.length;i+=4)bins.add((p.data[i]>>3)*1024+(p.data[i+1]>>3)*32+(p.data[i+2]>>3));assert(bins.size>250,'Canvas contains no rendered subject');report.checks.canvas={count:1,colorBins:bins.size};
 report.checks.source=await page.evaluate(()=>__TALKINGHEAD__.info());assert.equal(report.checks.source.source.commit,'b3e277b3b46f88e557bf28a2c5612a5b04e075c3');
 const geometry=await page.evaluate(()=>__EYES__.sourceGeometry());const skinValues=await page.evaluate(()=>({...__SKIN_LAB__.values}));
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>{__TALKINGHEAD__.set({headMotion:false});__EYES__.set({autoBlink:false,autoPupil:false,pupilMM:3.4,manualBlink:-1});__EYES__.setMode('camera');__EYES__.step(0,true);});await shot('02-eyes');
 await page.evaluate(()=>{__TALKINGHEAD__.blink('single');__EYES__.step(.05);__EYES__.step(.05);__EYES__.step(.025);});
 const blink=await page.evaluate(()=>__EYES__.info());assert(blink.blinkLeft>.90&&blink.blinkRight>.90,'Native blink not mapped to both lids');report.checks.nativeBlink={left:blink.blinkLeft,right:blink.blinkRight};await shot('03-native-blink');
 await page.evaluate(()=>{for(let i=0;i<20;i++)__EYES__.step(.05);__TALKINGHEAD__.blink('left');__EYES__.step(.05);__EYES__.step(.05);__EYES__.step(.025);});
 const wink=await page.evaluate(()=>__EYES__.info());assert(wink.blinkLeft>.90&&wink.blinkRight<.05,'Anatomical left wink is misrouted');report.checks.leftWink={left:wink.blinkLeft,right:wink.blinkRight};await shot('04-left-wink');
 await page.evaluate(()=>{__TALKINGHEAD__.blink('double');__EYES__.set({manualBlink:.37});for(let i=0;i<4;i++)__EYES__.step(.05);});
 const manual=await page.evaluate(()=>({eye:__EYES__.info(),bridge:__TALKINGHEAD__.info()}));assert.equal(manual.eye.blinkLeft,.37);assert.equal(manual.eye.blinkRight,.37);assert.equal(manual.bridge.controls.blinkOwner,'manual');report.checks.manualPriority=true;
 // World-space target stays unchanged while the whole existing head moves.
 const sweep=await page.evaluate(()=>{
  __TALKINGHEAD__.set({headMotion:false,paused:true,manualYaw:0,manualPitch:0});__EYES__.setTarget([.01,.069,.80]);let results=[];
  for(const b of [0,.25,.5,.75,1])for(const angles of [[-.22,0],[.22,0],[0,-.10],[0,.10],[0,0]]){
   __TALKINGHEAD__.set({manualYaw:angles[0],manualPitch:angles[1]});__EYES__.set({manualBlink:b});__EYES__.step(0,true);const e=__EYES__.info();results.push({closure:b,head:angles,lock:e.lockErrorDegrees,clamped:e.clamped,target:e.target,contact:e.contact});
  }return results;
 });
 assert(sweep.every(s=>s.lock.every(x=>x<.005)&&!s.clamped),'Head rotation broke gaze lock');assert(sweep.every(s=>s.contact.every(c=>c.penetratingTestVertices===0)),'Sampled contact violation');assert(sweep.every(s=>JSON.stringify(s.target)===JSON.stringify([.01,.069,.80])),'Fixed target overwritten');report.checks.headLockAndContact25=sweep;
 await page.click('[data-camera="portrait"]');await page.evaluate(()=>{__EYES__.set({manualBlink:0});__TALKINGHEAD__.set({manualYaw:.25,manualPitch:0});__EYES__.step(0,true);});await shot('05-head-turn-locked');
 await page.evaluate(()=>{__EYES__.setTarget([3,2,-1]);__EYES__.step(0,true);});assert(await page.evaluate(()=>__EYES__.info().clamped),'Unreachable gaze not bounded');report.checks.unreachableTargetBounded=true;
 // Native nod must move the original head, without loading another avatar.
 const nod=await page.evaluate(()=>{__TALKINGHEAD__.reset();__TALKINGHEAD__.set({headAmount:1});__EYES__.setMode('camera');__EYES__.set({manualBlink:0,autoBlink:false});__TALKINGHEAD__.gesture('yes');let peak=0;for(let i=0;i<20;i++){__EYES__.step(.04);peak=Math.max(peak,Math.abs(__TALKINGHEAD__.info().headQuaternion[0]));}return peak;});assert(nod>.01,'Native head gesture has no output');report.checks.nativeNodQuaternionPeak=nod;await shot('06-native-nod');
 // Exercise the real pointer event handler and lock button.
 await page.evaluate(()=>{__TALKINGHEAD__.set({headMotion:false,paused:true,manualYaw:0,manualPitch:0});__EYES__.set({manualBlink:0});});
 await page.selectOption('#eyeMode','pointer');await page.mouse.move(400,480);await page.evaluate(()=>__EYES__.step(0,true));const t1=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(710,460);await page.evaluate(()=>__EYES__.step(0,true));assert.notDeepEqual(await page.evaluate(()=>__EYES__.info().target),t1);
 await page.click('#lockEye');await page.evaluate(()=>__EYES__.step(0,true));const locked=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(270,410);await page.evaluate(()=>__EYES__.step(0,true));assert.deepEqual(await page.evaluate(()=>__EYES__.info().target),locked);report.checks.pointerAndLock=true;
 await page.evaluate(()=>{__TALKINGHEAD__.set({mood:'happy',headAmount:.3,manualYaw:.15,paused:true});__EYES__.setTarget([.01,.069,.8]);__EYES__.step(0,true);});await page.click('#save');await page.evaluate(()=>__TALKINGHEAD__.set({mood:'sad',manualYaw:-.1}));await page.click('#restore');
 const restored=await page.evaluate(()=>__EYES__.snapshot());assert.equal(restored.behavior.mood,'happy');assert.equal(restored.behavior.manualYaw,.15);assert.deepEqual(restored.fixedTarget,[.01,.069,.8]);assert.equal(restored.mode,'fixed');report.checks.recipeRestore=true;
 report.checks.oldRecipeAndRejection=await page.evaluate(()=>{const old=__EMILY_TRANSFER__.exportRecipe();delete old.eyes.behavior;__EMILY_TRANSFER__.loadRecipe(old);const before=JSON.stringify(__EYES__.snapshot());let rejected=false;try{__EYES__.restore({...__EYES__.snapshot(),mode:'invalid'});}catch{rejected=true;}return {oldAccepted:true,rejected,unchanged:JSON.stringify(__EYES__.snapshot())===before};});assert(report.checks.oldRecipeAndRejection.unchanged&&report.checks.oldRecipeAndRejection.rejected);
 for(let i=0;i<10;i++){await page.evaluate(()=>{__TALKINGHEAD__.set({enabled:false});__EYES__.step(.02,true);});assert.equal(await page.evaluate(()=>__TALKINGHEAD__.info().legacySchedulerActive),true);await page.evaluate(()=>{__TALKINGHEAD__.set({enabled:true});__EYES__.step(.02,true);});}
 assert.deepEqual(await page.evaluate(()=>__EYES__.sourceGeometry()),geometry);assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.evaluate(()=>__TALKINGHEAD__.info().legacySchedulerActive),false);report.checks.repeatedDriverToggle={cycles:10,sameGeometry:true,oneCanvas:true};
 await page.evaluate(()=>{__TALKINGHEAD__.reset();__TALKINGHEAD__.set({headMotion:false,paused:true});__EYES__.set({manualBlink:0,autoBlink:false,autoPupil:false,pupilMM:2,squint:0});__EYES__.setMode('camera');});await page.click('[data-camera="iris"]');await page.evaluate(()=>__EYES__.step(0,true));const small=await pixels();await page.evaluate(()=>{__EYES__.set({pupilMM:6});__EYES__.step(0,true);});const large=await pixels();report.checks.pupilImageDifference=imageDiff(small,large);assert(report.checks.pupilImageDifference.meanRGB>.01);await shot('07-iris');
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>{__EYES__.set({pupilMM:3.4});__EYES__.step(0,true);});await page.click('[data-method="enhanced"]');const enhanced=await pixels();await page.selectOption('#transferMode','base');const base=await pixels();report.checks.skinComparison=imageDiff(enhanced,base);assert(report.checks.skinComparison.meanRGB>.01);await page.selectOption('#transferMode','split');await shot('08-skin-comparison');
 assert.deepEqual(await page.evaluate(()=>({...__SKIN_LAB__.values})),skinValues);report.checks.originalSkinValuesPreserved=true;
 await page.click('#reset');await page.evaluate(()=>{__TALKINGHEAD__.set({headMotion:false,paused:true});__EYES__.set({manualBlink:0});__EYES__.step(0,true);});await page.setViewportSize({width:390,height:844});await page.click('[data-camera="portrait"]');await page.evaluate(()=>__EYES__.step(0,true));await shot('09-mobile-viewport');await page.click('#mobileToggle');await page.click('#thSocial');assert.equal(await page.evaluate(()=>__EYES__.info().mode),'relaxed');await page.click('#thDouble');await page.evaluate(()=>{__EYES__.step(.05);__EYES__.step(.05);});await shot('10-mobile-controls');await page.click('#mobileToggle');report.checks.mobile={viewport:[390,844],panelToggle:true,behaviorControls:true,realDevice:false};
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.failedRequests,[]);
 assert(!requests.some(u=>/texttospeech|speech\.google|elevenlabs|api\.openai|readyplayer|\.fbx(?:\?|$)/i.test(u)),'Unexpected voice/avatar dependency');report.checks.noNewVoiceOrAvatarRequests=true;report.requests=requests;
 report.passed=true;fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log('ET04_BROWSER_PASS',JSON.stringify({url,checks:Object.keys(report.checks),errors:report.errors,publicCommit:report.publicCommit}));
})().catch(async e=>{report.passed=false;report.failure=e.stack||String(e);report.requests=requests;console.error(e);fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(page)await page.screenshot({path:out+'/failure.png',timeout:30000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
