// Original shoe presentation materials, using the public Three.js API.
import * as T from 'three';
export const MATERIALS={smooth:{name:'细纹皮革',roughness:.43,clearcoat:.15,clearcoatRoughness:.32,note:'细微表面起伏与涂饰反射'},grain:{name:'粒面皮革',roughness:.52,clearcoat:.1,note:'粗粒起伏与较宽高光'},suede:{name:'绒面革',roughness:.94,sheen:.75,sheenRoughness:.8,note:'粗糙反射与掠射绒光'},weave:{name:'织物鞋面',roughness:.85,sheen:.5,sheenRoughness:.8,note:'程序化经纬纹理'},patent:{name:'亮面漆皮',roughness:.22,clearcoat:.95,clearcoatRoughness:.13,note:'独立清漆层'}};
export const COLOURS=[['深栗棕','#683920'],['酒红','#4d2025'],['炭黑','#191b1e'],['烟草棕','#996344'],['奶油白','#c4bca9'],['深海蓝','#253d4b'],['苔绿','#465245']];
const cache=new Map();
function texture(kind){if(cache.has(kind))return cache.get(kind);const n=256,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const f=Math.sin(x*127.1+y*311.7)*43758.5453,noise=f-Math.floor(f);let h=noise;if(kind==='weave')h=.5+.22*Math.cos(x*Math.PI/4)+.22*Math.cos(y*Math.PI/4);if(kind==='grain')h=.5+.23*Math.sin(x*.7+Math.sin(y*.65))+.16*noise;for(let c=0;c<3;c++)data[(y*n+x)*4+c]=Math.round(h*255);data[(y*n+x)*4+3]=255;}const t=new T.DataTexture(data,n,n);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(25,25);t.generateMipmaps=true;t.minFilter=T.LinearMipmapLinearFilter;t.magFilter=T.LinearFilter;t.anisotropy=8;t.needsUpdate=true;cache.set(kind,t);return t;}
export function palette(kind='smooth',colour='#683920'){const {name,note,...p}=MATERIALS[kind],bump=texture(kind),standard=(color,roughness=.8)=>new T.MeshStandardMaterial({color,roughness});return{skin:new T.MeshPhysicalMaterial({...p,color:colour,bumpMap:bump,bumpScale:kind==='grain'?.0003:kind==='suede'?.00015:.00006,sheenColor:new T.Color(colour).lerp(new T.Color('#c9b49b'),.4),ior:1.48}),edge:standard(new T.Color(colour).multiplyScalar(.58),.65),lining:standard('#a67d51',.76),sole:standard('#252322',.85),cupsole:standard('#b8b2a4',.76),leatherSole:standard('#654730',.65),thread:standard(new T.Color(colour).lerp(new T.Color('#d9c8a4'),.6),.96),lace:new T.MeshStandardMaterial({color:colour==='#c4bca9'?'#d6cebc':'#33261e',roughness:.95,bumpMap:texture('weave'),bumpScale:.00012}),metal:new T.MeshStandardMaterial({color:'#a38c68',metalness:.86,roughness:.26}),dark:standard('#0d0d0e',.95),elastic:new T.MeshStandardMaterial({color:'#171718',roughness:.88,bumpMap:texture('weave'),bumpScale:.00016}),wood:standard('#b18e5a',.5)};}
export function disposePalette(p){Object.values(p).forEach(m=>m.dispose());}
export function makeEnvironment(renderer){const scene=new T.Scene();scene.background=new T.Color('#424449');for(const [x,y,z,w,h,p]of [[-3,3,2,3,4,6],[3,2,-1,2,4,3.5],[0,5,0,4,3,2.7],[1,1,4,1.2,3,1.8]]){const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:new T.Color(1,1,1).multiplyScalar(p),side:T.DoubleSide}));m.position.set(x,y,z);m.lookAt(0,0,0);scene.add(m);}const generator=new T.PMREMGenerator(renderer),target=generator.fromScene(scene,.035);generator.dispose();scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});return target.texture;}
