const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const repo=path.resolve(__dirname,'../../..'),out=process.env.EVIDENCE_DIR||'/tmp/et06-evidence/local',sha=process.env.PUBLIC_COMMIT;fs.mkdirSync(out,{recursive:true});
const report={version:'ET07.3',publicCommit:sha||null,backend:'Chromium / SwiftShader',physicalMobileDevice:false,networkInterception:false,errors:[],consoleErrors:[],failedRequests:[],checks:{}};let browser,page,server;
function diff(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);assert.equal(a.width,b.width);assert.equal(a.height,b.height);let sum=0,n=0;for(let i=0;i<a.data.length;i+=4){let d=0;for(let k=0;k<3;k++)d+=Math.abs(a.data[i+k]-b.data[i+k]);sum+=d;if(d>5)n++;}return {meanRGB:sum/(a.width*a.height*3),changedFraction:n/(a.width*a.height)};}
function audit(v,label){assert.equal(v.version,'ET07.3');assert(v.scanRepair?.ready&&v.scanRepair.enabled&&v.scanRepair.extraTextures===3);assert.equal(v.scanRepair.originalAssetsModified,false);for(const t of v.tissue){assert(t.boundaryUVMaxError<1e-6);assert.equal(t.sharedMarginNormalMaxError,0);assert(t.sameAlbedoTexture&&t.canthalPatch);assert.equal(t.canthalContact.invalid,0);assert.equal(t.canthalContact.penetrations,0);assert(t.canthalContact.samples>1000);}for(const e of v.eyes){assert.equal(e.nonfiniteVertices,0,label+' nonfinite');assert(e.surfaceTests.triangleSamples>10000);assert.equal(e.surfaceTests.trianglePenetrations,0,label+' triangle interior contact');assert(e.surfaceTests.triangleMinAxialGapMM>=-.0001,label+' triangle clearance');assert.equal(e.posteriorAndMarginPenetrations,0,label+' penetrates posterior/margin');assert(e.maxSharedEdgeErrorMM<.00001,label+' disconnected margin');assert(e.posteriorAndMarginMinAxialGapMM>.035,label+' missing contact clearance');assert(e.outerBoundaryDeviationMM<.00002,label+' changed outer anchor');assert.equal(e.eyeHidden,false,label+' hidden eye');}}
(async()=>{
 let url;
 if(sha){assert(/^[0-9a-f]{40}$/.test(sha));url='https://htmlpreview.github.io/?https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/'+sha+'/skin-quality-lab/emily-transfer/preview.html';}
 else{server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),f=path.resolve(repo,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(repo+path.sep))return res.writeHead(403).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');const s=fs.createReadStream(f);s.on('error',()=>{if(!res.headersSent)res.writeHead(404);res.end();});s.pipe(res);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';}
 report.url=url;console.log('LOAD',url);
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1280,height:960},deviceScaleFactor:1});page.setDefaultTimeout(90000);
 await page.addInitScript(()=>{window.__EYE_QA_FREEZE__=true;});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready&&window.__EYES__?.audit&&window.__TALKINGHEAD__,{},{timeout:240000});
 assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/7.3.0');assert.equal(await page.locator('canvas').count(),1);console.log('READY');
 await page.evaluate(()=>{__TALKINGHEAD__.set({headMotion:false,paused:true,manualYaw:0,manualPitch:0});__EYES__.set({autoBlink:false,autoPupil:false,pupilMM:3.4,manualBlink:0,squint:0,opening:.88});__EYES__.setTarget([-.004,.069,.8]);__EYES__.step(0,true);});
 async function shot(name,full=false){await page.evaluate(()=>__SKIN_LAB__.render());const b=Buffer.from((await page.evaluate(()=>document.querySelector('#viewport canvas').toDataURL('image/png'))).split(',')[1],'base64');fs.writeFileSync(out+'/'+name+'.png',b);if(full)await page.screenshot({path:out+'/'+name+'-page.png'});console.log('SHOT',name);return b;}
 await page.click('[data-camera="eyes"]');const open=await shot('01-eyes-open',true),rest=await page.evaluate(()=>__EYES__.audit(true));report.checks.resting=rest;audit(rest,'rest');
 for(const e of rest.eyes){assert(e.horizontalApertureMM>23&&e.horizontalApertureMM<24.2);assert(e.verticalApertureMM>5.7&&e.verticalApertureMM<7.4);assert(e.upperFreeMarginArcMM>e.lowerFreeMarginArcMM+.20);assert(e.upperFreeMarginArcMM>.5&&e.upperFreeMarginArcMM<1.2);}
 await page.locator('#scanRepairCompare').hover();await page.mouse.down();const rawCapture=await shot('09-original-capture-texture');await page.mouse.up();const repaired=await shot('10-repair-restored');
 report.checks.textureRepairToggle={rawDifference:diff(open,rawCapture),restoredDifference:diff(open,repaired),info:await page.evaluate(()=>__NATURAL_REVIEW__.repairInfo())};
 assert(report.checks.textureRepairToggle.rawDifference.meanRGB>.05,'Repair comparison must change actual skin pixels');assert(report.checks.textureRepairToggle.restoredDifference.meanRGB<.01,'Held repair comparison did not restore the same frame');
 const source=await page.evaluate(()=>__EYES__.sourceGeometry());report.checks.sourceGeometry=source;
 await page.click('[data-camera="lidSide"]');await shot('02-margin-side');await page.click('[data-camera="lidBelow"]');await shot('03-upper-lid-underside');
 await page.click('[data-camera="eyes"]');await page.evaluate(()=>__EYES__.set({manualBlink:.5}));const half=await shot('04-half-closed');await page.evaluate(()=>__EYES__.set({manualBlink:1}));const closed=await shot('05-closed');report.checks.closed=await page.evaluate(()=>__EYES__.audit(true));audit(report.checks.closed,'closed');assert(report.checks.closed.eyes.every(e=>Math.abs(e.verticalApertureMM)<.0001&&e.upperFreeMarginArcMM<.7&&e.lowerFreeMarginArcMM<.7));
 report.checks.openToHalf=diff(open,half);report.checks.halfToClosed=diff(half,closed);assert(report.checks.openToHalf.meanRGB>.03&&report.checks.halfToClosed.meanRGB>.03,'No visible closure');
 report.checks.sweep=await page.evaluate(()=>{const rows=[];for(const b of [0,.25,.5,.75,1])for(const v of [[-.004,.069,.8],[-.16,.069,.65],[.16,.069,.65],[-.004,.17,.65],[-.004,-.04,.65],[-.16,.17,.65],[.16,.17,.65],[-.16,-.04,.65],[.16,-.04,.65]]){__EYES__.setTarget(v);__EYES__.set({manualBlink:b});__EYES__.step(0,true);rows.push({blink:b,target:v,audit:__EYES__.audit(true)});}return rows;});for(const r of report.checks.sweep)audit(r.audit,'sweep '+r.blink+' '+r.target);console.log('45_CONTACT_STATES_PASS');
 await page.evaluate(()=>{__EYES__.set({manualBlink:0,opening:.88});__EYES__.setTarget([.01,.069,.8]);__TALKINGHEAD__.set({manualYaw:.18,manualPitch:-.04});__EYES__.step(0,true);});let i=await page.evaluate(()=>__EYES__.info());assert(i.lockErrorDegrees.every(v=>v<.01),'Head/gaze tracking');report.checks.headTarget={target:i.target,errors:i.lockErrorDegrees};await shot('06-turned-gaze');
 report.checks.recipe=await page.evaluate(()=>{const r=__EYES__.snapshot();__EYES__.set({opening:.65});const small=__EYES__.audit(true);__EYES__.restore(r);__EYES__.step(0,true);return {restored:__EYES__.snapshot().opening===r.opening,small,sourceSame:__EYES__.sourceGeometry()};});assert(report.checks.recipe.restored);assert.deepEqual(report.checks.recipe.sourceSame,source);
 await page.evaluate(()=>{__TALKINGHEAD__.set({manualYaw:0,manualPitch:0});__EYES__.setTarget([-.004,.069,.8]);__EYES__.step(0,true);});await page.click('[data-camera="portrait"]');await shot('07-portrait');
 await page.setViewportSize({width:390,height:844});await page.click('[data-camera="eyes"]');await shot('08-mobile',true);await page.click('#mobileToggle');assert(await page.locator('.side').isVisible());report.checks.mobile={viewport:[390,844],panel:true,realHardware:false};
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.failedRequests,[]);report.passed=true;console.log('ET07_PASS',JSON.stringify({url,states:report.checks.sweep.length,rest:report.checks.resting,headTarget:report.checks.headTarget}));
})().catch(async e=>{report.passed=false;report.failure=e.stack||String(e);console.error(e);if(page)await page.screenshot({path:out+'/failure.png',timeout:30000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(browser)await browser.close();if(server)server.close();});
