import {HUMAN_INVERSE_METHOD} from '../New-Human-Production/R008/HumanInverseMethod.mjs';
import {readFileSync} from 'node:fs';import {join} from 'node:path';import {gunzipSync} from 'node:zlib';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {decodeParameters} from '../New-Human-Production/R008/parameter-codec.mjs';import {JUMP_MOTIONS} from '../New-Human-Production/R008/JumpMotionData.mjs';
import {FACE_REGIONS} from '../New-Human-Production/R008/FacialBinding.mjs';
import {NATURAL_RUN} from '../New-Human-Production/R008/NaturalRunData.mjs';
import {EXPRESSIONS} from '../New-Human-Production/R008/FacialExpression.mjs';
import {ANATOMY_RULES} from '../New-Human-Production/R008/AnatomyContract.mjs';
export function checkR008(root){
 const read=p=>readFileSync(join(root,p),'utf8'),assert=(v,m)=>{if(!v)throw Error(m)},base='New-Human-Production/R008/',manifest=JSON.parse(read('source/assembly.json')),selected=manifest.subjects[manifest.activeSubject];
 assert(selected.bodyTissue===base+'BodyTissue.mjs','Missing active eight-weight tissue generator');assert(selected.sourceModelAtRuntime===false,'Reference models forbidden at runtime');assert(read('index.html')===read(selected.entry).replaceAll('\"./vendor/',`\"./${base}vendor/`).replace('src="./app.mjs"',`src="./${base}app.mjs"`),'Active entrypoint mismatch');
 assert(selected.humanInverseMethodId===HUMAN_INVERSE_METHOD.id&&Object.isFrozen(HUMAN_INVERSE_METHOD),'Missing fixed inverse methodology');assert(read(base+'SurfaceSkeletonDisplay.mjs').includes('createHumanInverseSystem')&&read(base+'MotionAnatomyWorkbench.mjs').includes('model:nextInverse.system.muscles'),'Separate inverse skeleton/muscle methods are forbidden');
 assert(selected.anatomyAnalysis===base+'AnatomyAnalysis.mjs'&&selected.anatomyContract===base+'AnatomyContract.mjs','Missing anatomy knowledge contract');assert(read('AGENTS.md').includes('docs/anatomy-knowledge/README.md'),'Missing persistent anatomy instructions');
 for(const [key,file]of Object.entries({humanInverseMethod:'HumanInverseMethod.mjs',humanInverseSystem:'HumanInverseSystem.mjs',surfaceSkeletonFit:'SurfaceSkeletonFit.mjs',surfaceSkeletonDisplay:'SurfaceSkeletonDisplay.mjs',inverseCalibration:'R008InverseCalibration.mjs',bodySpecies:'HumanBodySpecies.mjs',bodySystem:'HumanBodySystem.mjs',bodyComposition:'BodyComposition.mjs',bodyCalibration:'R008CompositionCalibration.mjs',motorAnatomy:'MotorAnatomy.mjs',anatomyDisplay:'AnatomyDisplay.mjs',motionAnatomyWorkbench:'MotionAnatomyWorkbench.mjs'}))assert(selected[key]===base+file,'Missing reusable human composition module: '+key);
 assert(ANATOMY_RULES.length===8&&new Set(ANATOMY_RULES.map(r=>r.id)).size===8,'Invalid anatomy rules');assert(read(selected.anatomyKnowledge).includes('R20'),'Missing anatomy failure history');for(const file of ['test-human-inverse.mjs','test-surface-skeleton.mjs','test-anatomy.mjs','test-body-tissue.mjs','test-body-parameters.mjs','test-body-composition.mjs','test-motor-anatomy.mjs']){const test=spawnSync(process.execPath,[join(root,base+'tools/'+file)],{encoding:'utf8'});assert(test.status===0,'Anatomy gate failed: '+file+' '+test.stderr);}
 const modules=['CandidateKinematics.mjs','AnatomicalField.mjs','AnatomicalRegistration.mjs','AnatomicalLandmarks.mjs','AnatomicalSkeleton.mjs','vendor/marching-cubes-tables.mjs','HumanInverseMethod.mjs','HumanInverseSystem.mjs','SurfaceSkeletonFit.mjs','SurfaceSkeletonDisplay.mjs','R008InverseCalibration.mjs','MotorAnatomy.mjs','AnatomyDisplay.mjs','MotionAnatomyWorkbench.mjs','HumanBodySystem.mjs','HumanBodySpecies.mjs','BodyComposition.mjs','R008CompositionCalibration.mjs','AnatomyAnalysis.mjs','AnatomyMath.mjs','AnatomyContract.mjs','MuscleAtlas.mjs','AnatomyWorkbench.mjs','AdiposeLayer.mjs','BodyParameters.mjs','BodyTissue.mjs','BodyBinding.mjs','BodyWorkbench.mjs','SurfaceQuality.mjs','app.mjs','ViewControls.mjs','SkinAppearance.mjs','SkinMaterial.mjs','SkinWorkbench.mjs','ScarState.mjs','ScarSurface.mjs','ScarWorkbench.mjs','SubjectRuntime.mjs','CharacterController.mjs','GameAnimator.mjs','NaturalRunData.mjs','JumpProfiles.mjs','JumpMotionData.mjs','FacialBinding.mjs','FacialExpression.mjs','ProceduralEyes.mjs','FacialWorkbench.mjs','game-world.mjs','game-scene.mjs','surface-generator.mjs','material-fields.mjs','parameter-codec.mjs','vendor/earcut.js'];for(const module of modules){const text=read(base+module),syntax=spawnSync(process.execPath,['--check','--input-type=module'],{input:text,encoding:'utf8'});assert(syntax.status===0,syntax.stderr);assert(!/FBXLoader|USDZLoader|source-intake|capture\.json|data:image\//.test(text),'Source dependency in runtime '+module);}
 assert(selected.runningMotionData===base+'NaturalRunData.mjs','Missing active running field');assert(NATURAL_RUN.order===3&&NATURAL_RUN.source==='CMU 02_03 run/jog'&&Object.keys(NATURAL_RUN.channels).length===46,'Invalid full-body running field contract');for(const coefficients of Object.values(NATURAL_RUN.channels))assert(coefficients.length===7&&coefficients.every(Number.isFinite),'Invalid periodic running coefficients');assert(NATURAL_RUN.strideSeconds>0&&NATURAL_RUN.strideLegLengths>0,'Invalid stride calibration');assert(Object.keys(EXPRESSIONS).length===15,'Missing facial presets');
 assert(selected.skinAppearance===base+'SkinAppearance.mjs'&&selected.skinMaterial===base+'SkinMaterial.mjs'&&selected.skinWorkbench===base+'SkinWorkbench.mjs','ScarState.mjs','ScarSurface.mjs','ScarWorkbench.mjs','Missing active skin channels');
 assert(selected.scarState===base+'ScarState.mjs'&&selected.scarSurface===base+'ScarSurface.mjs'&&selected.scarWorkbench===base+'ScarWorkbench.mjs','Missing active scar controls');
 assert(selected.cameraControls===base+'ViewControls.mjs'&&read(base+'app.mjs').includes('createViewControls'),'Missing freely adjustable camera');
 assert(selected.proceduralEyes===base+'ProceduralEyes.mjs','Missing independent generated eyes');assert(read(base+'SubjectRuntime.mjs').includes('createProceduralEyes'),'Eye builder not wired');assert(read(base+'app.mjs').includes("$('eyeMode').onchange"),'Missing gaze controls');
 assert(FACE_REGIONS.length===46&&new Set(FACE_REGIONS.map(r=>r.id)).size===46,'Invalid facial channel catalog');for(const r of FACE_REGIONS){assert(r.centre.length===3&&r.radii.length===3&&r.radii.every(v=>v>0),'Invalid compact face region');if(r.kind!=='skin')assert(r.pull.every(v=>v===0),'Eye/lid/jaw requires independent structure');}
 const packed=readFileSync(join(root,selected.parameters)),b=gunzipSync(packed),d=decodeParameters(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));assert(d.schema==='parametric-human-uv-fields/v2','Wrong parameter schema');assert(d.rig.length===61&&d.animations.length===4&&d.materials.length===31,'Missing inherited rig, clips or surface parts');assert(d.source.faces===977244&&d.source.samples===977244,'Incomplete intake');assert(d.charts.reduce((s,c)=>s+c.sourceFaces,0)===d.source.faces,'Unaccounted source faces');
 for(const c of d.charts){assert(!c.positions&&!c.triangles&&!c.index,'Stored source mesh');assert(c.linear.length===9&&c.textureLinear.length===6,'Missing surface/appearance coordinate functions');for(const f of [c.shape,c.weights,c.normals])for(const l of f.layers)assert(l.c.length===l.ids.length*f.channels,'Invalid basis coefficients');for(const loop of c.trim)assert(loop.uv.length===loop.seams.length*2,'Invalid trim parameters');}
 for(const m of d.materials)for(const key of ['basecolor','normal','roughness','metallic']){const f=m[key];assert(f.size>0&&(f.size&(f.size-1))===0&&f.channels===3&&f.c.length===f.size*f.size*3,'Invalid material wavelet extent');}
 assert(Object.keys(JUMP_MOTIONS).length===3,'Missing replacement jump curves');for(const motion of Object.values(JUMP_MOTIONS))for(const knots of Object.values(motion.channels)){assert(knots.length%3===0&&knots.every(Number.isFinite),'Invalid motion coefficients');for(let i=3;i<knots.length;i+=3)assert(knots[i]>knots[i-3],'Non-increasing motion knots');}
 return {mode:'file-audit',subject:manifest.activeSubject,charts:d.charts.length,parts:d.materials.length,bones:d.rig.length,clips:d.animations.length,gameJumpStyles:Object.keys(JUMP_MOTIONS).length,runningFieldChannels:Object.keys(NATURAL_RUN.channels).length,runningFieldBytes:readFileSync(join(root,base+'NaturalRunData.mjs')).length,facialRegions:FACE_REGIONS.length,facialModuleBytes:readFileSync(join(root,base+'FacialBinding.mjs')).length,storedFacialVertexWeights:0,jumpCurveBytes:readFileSync(join(root,base+'JumpMotionData.mjs')).length,referenceFaces:d.source.faces,parametersBytes:packed.length,sha256:createHash('sha256').update(packed).digest('hex'),sourceModelAtRuntime:false,bindingStatus:'candidate-for-user-motion-test',applicationExecuted:false};
}
