// Source-structure contracts only. Never import/evaluate the application or
// call forecast/navigation/pose functions. Runtime behaviour needs separate QA.
export function checkActionSources({parse,read,runtime,assert}){
 let checks=0;const check=(ok,message)=>{assert(ok,'Action source contract: '+message);checks++};
 const syntax=text=>parse(text,{ecmaVersion:'latest',sourceType:'module'});
 function nodes(node,predicate,out=[]){if(!node||typeof node!=='object')return out;if(Array.isArray(node)){node.forEach(n=>nodes(n,predicate,out));return out}if(predicate(node))out.push(node);for(const [key,value]of Object.entries(node))if(!['start','end','loc','type'].includes(key))nodes(value,predicate,out);return out}
 const named=(tree,name)=>nodes(tree,n=>n.type==='FunctionDeclaration'&&n.id?.name===name)[0];
 const calls=(tree,name)=>nodes(tree,n=>n.type==='CallExpression'&&(n.callee.name===name||n.callee.property?.name===name));
 const part=(source,node)=>{check(!!node,'required function declaration is present');return source.slice(node.start,node.end)};
 const parent=read('language/JarvisLanguageController.js'),p=syntax(parent),enqueue=named(p,'enqueueSemantic'),forecast=named(p,'forecastSemantic');
 const preflightDeclaration=enqueue.body.body.find(n=>n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name==='preflight'&&d.init?.type==='AwaitExpression'&&d.init.argument.callee.name==='forecastSemantic'));
 check(!!preflightDeclaration,'whole-plan forecast is awaited unconditionally by the submission entry');
 check(preflightDeclaration.end<calls(enqueue,'controlSemantic')[0].start&&preflightDeclaration.end<calls(enqueue,'push')[0].start,'forecast precedes stop and queue mutations');
 const forecastText=part(parent,forecast);
 check(/!forecast\.feasible\|\|!forecast\.complete/.test(forecastText)&&calls(forecast,'Error').length>0,'incomplete or infeasible forecasts block submission');
 check(calls(forecast,'verifyEffects').length===1,'final object goals are checked on forecast output');
 check(/nodes:safe\(plan\.nodes\)/.test(forecastText)&&!/Lang\.flatten/.test(forecastText),'conditions reach the forecast as a tree');
 check(!/reasoningEnabled|physicalPreflight/.test(forecastText),'optional reasoning toggles cannot disable the mandatory forecast');
 check(calls(named(p,'drainSemanticQueue'),'forecastSemantic').length===1,'queued plans are checked again from the actual start state');
 check(/initialForecast/.test(forecastText)&&/sceneSignature/.test(forecastText),'append forecasts validate the predecessor basis');
 const executeText=part(parent,named(p,'executeNodes'));
 check(/\['observe','wait','joint_pose'\]/.test(executeText)&&/n\?\.kind==='action'/.test(executeText),'batching preserves wait, observation, condition and joint-goal barriers');
 const dispatchText=part(parent,named(p,'runNativeSemantic'));
 check(/steps:nodes\.map/.test(dispatchText)&&/stepIds:nodes\.map/.test(dispatchText),'one native ticket carries the ordered steps and identifiers');
 check(/if\(!languageState\.paused&&state\.heartbeat\?\.status!=='paused'\)waiter\.elapsed/.test(dispatchText)&&/waiter\.deadline/.test(dispatchText),'per-step timeout excludes parent and body pauses and uses the forecast duration');
 check(/waiter\.elapsed=0/.test(part(parent,named(p,'semanticFeedback'))),'verified progress resets the per-step clock');
 const waitText=part(parent,named(p,'waitSemanticDuration'));
 check(/elapsed=next\.timeS-clock\.timeS/.test(waitText)&&/remaining-=elapsed/.test(waitText)&&!/performance\.now|Date\.now/.test(waitText),'explicit waits measure body time rather than page wall time');
 check(calls(named(p,'waitSemanticDuration'),'waitUnpaused').length===2&&/generation:task\.generation/.test(waitText),'body-time waits preserve pause and cancellation guards');
 const core=read('control/PlanForecast.js'),c=syntax(core),simulation=part(core,named(c,'simulateSemanticPlanSteps'));
 check(calls(named(c,'simulateSemanticPlan'),'motionDrainPreflight').length===1&&/yield\* visit\(value\?node\.then:node\.else/.test(simulation),'synchronous and cooperative whole-plan forecasts preserve one selected branch against evolving state');
 check(/actor\.yaw=e\.bodyYaw/.test(simulation)&&/actor\.posture=e\.posture/.test(simulation)&&/o\.p=\[\.\.\.u\.p\]/.test(simulation),'later steps inherit actor and object effects');
 check(/capacity\.advance/.test(simulation)&&/capacity\.project/.test(simulation)&&/capacity\.recover/.test(simulation),'activity, loads and rest have separate projected strength updates');
 check(!/new World\(|\.pose\(|\.tick\(|\.render\(|\.importScene\(|\.geometryFor\(/.test(core),'forecast does not instantiate a world or invoke live pose/render/navigation execution');
 check(/failedStep=/.test(simulation)&&/stepNumber:/.test(simulation),'blocked steps carry stable identifiers and sequence numbers');
 const run=syntax(runtime),agent=nodes(run,n=>n.type==='ClassDeclaration'&&n.id.name==='Agent')[0],basic=nodes(run,n=>n.type==='ClassDeclaration'&&n.id.name==='BasicController')[0];
 const method=(cls,name)=>cls.body.body.find(n=>n.key.name===(cls.id.name==='Agent'&&name==='tick'?'tickFixed':name)).value;
 check(calls(method(agent,'submitPlan'),'simulateSemanticPlan').length===1,'native submission also requires a full forecast');
 check(calls(method(basic,'chooseSeat'),'chooseFloorSeat').length===1&&calls(method(basic,'hasFloorRoom'),'floorRoom').length===1,'floor clearance rules are shared with the executor');
 const analysis=named(c,'physicalAnalyzeStepSteps');
 check(analysis?.generator&&calls(named(c,'physicalAnalyzeStep'),'motionDrainPreflight').length===1,'cooperative analysis and the synchronous contract share one implementation');
 check(calls(method(agent,'begin'),'walkDestination').length===1&&calls(analysis,'walkDestination').length===1,'walk endpoints are shared with the executor');
 const transferEntry=named(c,'planObjectTransfer');
 check(calls(transferEntry,'navigationQueryBatch').length===1&&calls(transferEntry,'planObjectTransferInSnapshot').length===1,'transfer search shares navigation only inside its synchronous snapshot scope');
 const transfer=named(c,'planObjectTransferInSnapshotSteps'),transferText=part(core,transfer),transferLoop=nodes(transfer,n=>n.type==='ForOfStatement')[0];
 check(transfer?.generator&&calls(named(c,'planObjectTransferSteps'),'navigationQueryBatchSteps').length===1&&calls(named(c,'planObjectTransferInSnapshot'),'motionDrainPreflight').length===1,'synchronous and cooperative searches share the same generator and scoped navigation');
 check(calls(method(agent,'tick'),'carryRouteRadius').length===1&&calls(transfer,'carryRouteRadius').length===1,'carry envelope is shared with the executor');
 check(calls(analysis,'planObjectTransfer').length===1&&calls(analysis,'planObjectTransferSteps').length===1&&calls(transfer,'reasoningDestinations').length===1,'physical analysis uses the complete candidate selector');
 const candidateTry=transferLoop.body.body.find(n=>n.type==='TryStatement');
 check(calls(candidateTry.block,'path').length===2&&calls(candidateTry.block,'straightPushRoute').length===1&&calls(candidateTry.block,'assess').length===2&&calls(candidateTry.block,'motionChooseContactSteps').length===2,'each candidate checks approach, pickup/placement reach, transport, sustained strength and the one-hand supported change');
 check(calls(candidateTry.block,'path')[1].end<calls(candidateTry.block,'motionChooseContactSteps')[0].start&&calls(candidateTry.block,'assess')[0].end<calls(candidateTry.block,'motionChooseContactSteps')[0].start,'transport and strength can reject candidates before dense contact certification');
 check(candidateTry.block.body.at(-1).type==='ReturnStatement'&&calls(candidateTry.handler,'push').length===1&&nodes(candidateTry.handler,n=>['ReturnStatement','ThrowStatement'].includes(n.type)).length===0&&transfer.body.body.at(-1).type==='ThrowStatement','candidate failures continue the search; rejection occurs after the candidates are exhausted');
 check(!/capacity\.(?:advance|recover|project)\(/.test(transferText)&&nodes(named(c,'reasoningDestinations'),n=>n.type==='ReturnStatement').length===1,'candidate exploration neither spends live strength nor returns the first object-only landing');
 const beginText=part(runtime,method(agent,'begin'));
 check(/transport=capability\.transport/.test(beginText)&&/s\.dest=\[\.\.\.transport\.destination\]/.test(beginText)&&/s\.transferEnd=\[\.\.\.transport\.bodyEnd\]/.test(beginText)&&/this\.route=transport\.approach\.map/.test(beginText),'execution consumes the selected landing, body endpoint and approach');
 check(/this\.w\.path\(this\.pos,s\.transferEnd,carryRouteRadius/.test(part(runtime,method(agent,'tick'))),'loaded-route revalidation preserves the selected body endpoint');
 check(calls(method(agent,'advanceStrength'),'advance').length===1&&calls(method(agent,'tick'),'advance').length===0&&calls(method(agent,'tick'),'advanceStrength').length===3,'native strength updates use the shared agent entry');
 check(calls(named(c,'straightPushRoute'),'collision').length===2,'straight pushing checks both the object and body sweep');
 check(/this\.plan\.steps=this\.plan\.steps\.slice\(0,this\.index\+1\)/.test(part(runtime,method(agent,'cancel'))),'held stop truncates the remaining native batch');
 const bridge=read('language/HumanoidSemanticBridge.js'),b=syntax(bridge),completion=part(bridge,named(b,'checkCompletion'));
 check(completion.indexOf('agent.stats.failed')<completion.indexOf("emit('step_completed'"),'failure is examined before emitting verified progress');
 const binding=named(b,'bindCurrentBody'),tickAssignment=nodes(binding,n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.object.name==='agent'&&n.left.property.name==='tick'&&n.right.type==='ArrowFunctionExpression')[0],tickStatements=tickAssignment?.right.body.body;
 check(tickStatements?.[0]?.type==='ExpressionStatement'&&tickStatements[0].expression.callee?.name==='tick'&&tickStatements[0].expression.arguments[0]?.name==='dt','the captured body update runs before checking completion');
 const tickGuard=tickStatements?.[1],tickGuardText=tickGuard?bridge.slice(tickGuard.start,tickGuard.end):'';
 check(tickGuard?.type==='IfStatement'&&!tickGuard.alternate&&/if\(api\(\)\?\.agent===agent\)/.test(tickGuardText)&&calls(tickGuard.consequent,'checkCompletion').length===1&&calls(tickAssignment.right,'checkCompletion').length===1,'completion is checked immediately after updating the active body; background bodies cannot complete its ticket');
 const bindingText=part(bridge,binding);
 check(/if\(boundAgent!==agent\)pausedByUser=!!agent\.paused/.test(bindingText)&&bindingText.indexOf('pausedByUser=!!agent.paused')<bindingText.indexOf('boundAgent=agent'),'switching agents adopts the new body pause state before rebinding');
 const bodyRequestListener=nodes(b,n=>n.type==='CallExpression'&&n.callee.name==='addEventListener'&&n.arguments[0]?.value==='message')[0]?.arguments[1],requestListenerText=part(bridge,bodyRequestListener);
 const instanceGuard=nodes(bodyRequestListener,n=>n.type==='IfStatement'&&bridge.slice(n.test.start,n.test.end)==='d.instanceId&&d.instanceId!==activeInstanceId()')[0],bodyDispatch=calls(bodyRequestListener,'dispatch')[0];
 check(/e\.source!==parent/.test(requestListenerText)&&instanceGuard?.consequent.type==='ThrowStatement'&&bodyDispatch&&instanceGuard.end<bodyDispatch.start,'requests reject a mismatched target instance before dispatch and only accept the parent window');
 check(/const instanceId=d\.instanceId\|\|activeInstanceId\(\)/.test(requestListenerText)&&requestListenerText.indexOf('const instanceId=')<requestListenerText.indexOf('await dispatch(')&&(requestListenerText.match(/id:ID,instanceId,requestId:d\.requestId/g)||[]).length===2,'both success and error replies retain the request instance across an asynchronous dispatch');
 check(/parent\.postMessage\(\{instanceId:activeInstanceId\(\),\.\.\.x\}/.test(bridge),'outbound heartbeat and execution events include the originating instance');
 check(/a\.agent\.paused=pausedByUser/.test(bridge)&&/open\.stepCount=a\.agent\.plan/.test(bridge),'pause and held-stop state survive native batching');
 const waitClock=nodes(named(b,'dispatch'),n=>n.type==='IfStatement'&&n.test.type==='BinaryExpression'&&n.test.right.value==='semantic.waitClock')[0],clockText=part(bridge,waitClock);
 check(/window\.__jarvisSemanticReservation!==p\.owner/.test(clockText)&&/p\.generation<generation/.test(clockText)&&/a\.agent\.error/.test(clockText)&&/a\.agent\.held/.test(clockText),'wait-clock access validates ownership, generation, body errors and free hands');
 check(/timeS:a\.agent\.time/.test(clockText)&&/a\.agent\.paused=pausedByUser/.test(clockText)&&!/\.tick\(|\.advance\(/.test(clockText),'wait-clock reads the body time and preserves a raced user pause without advancing the body itself');
 const joints=read('control/HumanJointControlAdapter.js');
 check(/supportsDirectGoals:false/.test(joints)&&/containsJoint\(plan\)/.test(joints),'direct joint goals remain explicitly unavailable');
 check(/raw\.tick\(dt\)/.test(joints)&&!/dt=Math|a\.time\s*\+=|h\.fk\(|j\.q\s*=|a\.paused\s*=/.test(joints),'joint observation does not clamp the fixed clock or write body state');
 const gait=read('body/NaturalLocomotion.js'),g=syntax(gait),locomotion=nodes(g,n=>n.type==='ClassDeclaration'&&n.id.name==='NaturalLocomotion')[0];
 check(/new MotionLab\.MotionController/.test(gait)&&/new MotionLabPose/.test(gait),'the tuned lab controller owns locomotion and the skin adapter');
 check(calls(method(basic,'update'),'turnInPlace').length===1&&calls(method(basic,'update'),'isSettled').length===1,'floor alignment waits for settled locomotion');
 check(/foot\.contact/.test(read('motion/vendor/controller.mjs'))&&/Math\.abs\(twist\) > \.28/.test(read('motion/vendor/controller.mjs')),'the lab retains planted-foot turn bounds');
 check(/!s\.swing&&s\.speed<\.001&&s\.status==='idle'/.test(gait),'handoffs wait for completed foot placement rather than a cosmetic blend delay');
 check(!/this\.phaseT>\.35/.test(part(runtime,method(agent,'tick'))),'fixed settling delays were removed from native manipulation');
 check(/checked="" disabled="" id="physicalPreflight"/.test(read('source/index.template.html')),'the required forecast is shown as always enabled');
 return{checks,applicationExecuted:false,kinematicExecutionVerified:false};
}
