import {readFileSync,statSync} from 'node:fs';import {join} from 'node:path';import {gunzipSync} from 'node:zlib';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {decodeParameters} from '../New-Human-Production/R007/parameter-codec.mjs';
export function checkR007(root){
 const read=p=>readFileSync(join(root,p),'utf8'),check=(x,m)=>{if(!x)throw Error(m)},base='New-Human-Production/R007/';const manifest=JSON.parse(read('source/assembly.json')),selected=manifest.subjects[manifest.activeSubject];check(selected.sourceModelAtRuntime===false,'Source asset runtime forbidden');
 check(read('index.html')===read(selected.entry).replace('src="./app.mjs"','src="./New-Human-Production/R007/app.mjs"'),'Wrong active generated entrypoint');
 const modules=['app.mjs','SubjectRuntime.mjs','surface-generator.mjs','parameter-codec.mjs','vendor/earcut.js'];for(const name of modules){const text=read(base+name),syntax=spawnSync(process.execPath,['--check','--input-type=module'],{input:text,encoding:'utf8'});check(syntax.status===0,syntax.stderr);check(!/FBXLoader|USDZLoader|EMBEDDED_MODEL|source-intake|capture\.json|projection-charts\.json/.test(text),'Raw source dependency in '+name);}
 const packed=readFileSync(join(root,selected.parameters)),bytes=gunzipSync(packed),data=decodeParameters(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));check(data.schema==='parametric-human-fields/v1','Wrong coefficient schema');check(data.rig.length===61&&data.animations.length===4,'Rig or animation coverage mismatch');check(data.source.faces===17885&&data.source.samples===data.source.faces*7,'Incomplete source intake');
 check(data.charts.reduce((n,c)=>n+c.sourceFaces,0)===data.source.faces,'Unaccounted source faces');for(const c of data.charts){check(!Object.hasOwn(c,'positions')&&!Object.hasOwn(c,'triangles')&&!Object.hasOwn(c,'index'),'Stored mesh in parameter domain');check(c.maxFitError<=.00051,'Fit tolerance not met');check(c.height.channels===1&&c.normals.channels===3&&c.appearance.channels===5,'Missing fields');for(const f of [c.height,c.weights,c.normals,c.appearance])for(const l of f.layers)check(l.c.length===l.ids.length*f.channels,'Wrong coefficient extent');for(const t of c.trim)check(t.uv.length===t.seams.length*2,'Wrong trim parameter extent');}
 check(new Set(data.boneOrder).size===61,'Duplicated bone identity');check(data.rig.every(b=>b.parent==='Armature'||data.boneOrder.includes(b.parent)),'Broken authored hierarchy');
 return {mode:'file-audit',subject:manifest.activeSubject,modules:modules.length,charts:data.charts.length,bones:data.rig.length,clips:data.animations.length,referenceFaces:data.source.faces,referenceSamples:data.source.samples,parametersBytes:packed.length,sha256:createHash('sha256').update(packed).digest('hex'),sourceModelAtRuntime:false,applicationExecuted:false};
}
