import {sub,add,mul,dot,length,unit,cross,projection,segmentPoint,quantile}from './AnatomyMath.mjs';
import {buildMuscleAtlas}from './MuscleAtlas.mjs';
export const ANATOMY_SCHEMA='human/anatomy-analysis@1';
const critical=['pelvis','chest','head',...['l','r'].flatMap(s=>['upperarm','lowerarm','hand','thigh','calf','foot'].map(b=>b+'_'+s))];
const plain=n=>n.split(':').at(-1).toLowerCase().replace(/mixamorig/g,'').replace(/[ ._-]/g,'');
export function boneRole(name){const n=plain(name);if(/twist|end|nub|ik|target/.test(n))return null;
 if(['pelvis','hips','hip','rootpelvis'].includes(n))return 'pelvis';if(n==='head')return 'head';if(/^neck/.test(n))return 'neck';if(/^(spine03|spine2|chest|upperchest|thorax)$/.test(n))return 'chest';if(/^(spine02|spine1|spine2mid)$/.test(n))return 'spineMiddle';if(/^(spine01|spine|spine0)$/.test(n))return 'spineLower';
 const side=n.startsWith('left')?'l':n.startsWith('right')?'r':/[lr]$/.test(n)?n.at(-1):null;if(!side)return null;
 const base=/^(left|right)/.test(n)?n.replace(/^(left|right)/,''):n.slice(0,-1);
 for(const [role,aliases]of Object.entries({clavicle:['clavicle','shoulder','collar'],upperarm:['upperarm','arm','humerus'],lowerarm:['lowerarm','forearm','radiusulna'],hand:['hand','wrist'],thigh:['thigh','upleg','upperleg','femur'],calf:['calf','leg','lowerleg','shin','tibia'],foot:['foot','ankle'],ball:['ball','toebase','toe']}))if(aliases.includes(base))return role+'_'+side;
 const digit=base.match(/^(thumb|index|middle|ring|pinky|little)(?:0)?([123])$/);return digit?digit[1].replace('little','pinky')+'_'+digit[2]+'_'+side:null;
}
export function regionForRole(role,name=''){if(/^(hand|foot|ball|thumb|index|middle|ring|pinky)_/.test(role||''))return [0,0,0,1];if(/^(upperarm|lowerarm)_/.test(role||''))return [0,1,0,0];if(/^(thigh|calf)_/.test(role||''))return [0,0,1,0];if(/^clavicle_/.test(role||''))return [.4,.6,0,0];if(/^(pelvis|spineLower|spineMiddle|chest)$/.test(role||''))return [1,0,0,0];return [0,0,0,0];}
export function analyzeHumanoid(input,{mapping={},frontHint=null,maxSamples=120000}={}){
 const {joints=[],positions,skinIndex,skinWeight}=input;if(!Array.isArray(joints))throw Error('Invalid skeleton');const warnings=[],names=new Set(),roles={},roleByIndex=new Array(joints.length).fill(null);
 const candidates={};for(let i=0;i<joints.length;i++){const j=joints[i];if(!j?.name||names.has(j.name)||j.position?.length!==3||!j.position.every(Number.isFinite))throw Error('Malformed or duplicate joint');names.add(j.name);const role=Object.entries(mapping).find(([,name])=>name===j.name)?.[0]||boneRole(j.name);if(role){(candidates[role]||= []).push(i);roleByIndex[i]=role;}}
 for(const [role,ids]of Object.entries(candidates)){roles[role]=ids.length===1?ids[0]:null;if(ids.length>1)warnings.push({code:'ambiguous-role',role,names:ids.map(i=>joints[i].name)});}
 const byName=new Map(joints.map((j,i)=>[j.name,i]));for(const j of joints){const visited=new Set([j.name]);let p=j.parent;while(p&&byName.has(p)){if(visited.has(p))throw Error('Cyclic skeleton');visited.add(p);p=joints[byName.get(p)].parent;}}
 const missing=critical.filter(r=>!Number.isInteger(roles[r]));if(missing.length)warnings.push({code:'missing-critical-roles',roles:missing});
 const status=missing.length||warnings.some(w=>w.code==='ambiguous-role')?'needs-review':'analyzed-rigged-humanoid';
 if(status==='needs-review')return {schema:ANATOMY_SCHEMA,status,sourceId:input.sourceId||'unidentified',warnings,roles,joints:joints.map(j=>({...j,position:[...j.position]})),muscles:[],segments:[],unknown:['internal-bone-surfaces','muscle-attachments','fat-thickness'],canDeform:false};
 const pos=r=>joints[roles[r]].position,pelvis=pos('pelvis'),up=unit(sub(pos('head'),pelvis)),lateral=unit(sub(pos('upperarm_l'),pos('upperarm_r'))),right=unit(sub(lateral,mul(up,dot(up,lateral)))),front=unit(frontHint||cross(right,up));
 if(length(cross(right,up))<.9||Math.abs(dot(front,up))>.2)throw Error('Ambiguous anatomical axes');
 const local=p=>{const q=sub(p,pelvis);return [dot(q,right),dot(q,up),dot(q,front)];};
 let floor=Infinity,top=-Infinity,count=positions?.length/3||0;for(let i=0;i<count;i++){const h=dot(sub(Array.from(positions.subarray(i*3,i*3+3)),pelvis),up);floor=Math.min(floor,h);top=Math.max(top,h);}
 const height=count?top-floor:length(sub(pos('head'),pos('foot_l')))*1.12;if(!(height>1e-6&&Number.isFinite(height)))throw Error('Invalid subject scale');
 const parentByIndex=joints.map(j=>byName.get(j.parent)),children=joints.map(()=>[]);parentByIndex.forEach((p,i)=>{if(p!==undefined)children[p].push(i);});
 // Helper/twist joints inherit segment semantics from their ancestry. No
 // assignment is made across an unknown root or onto a contralateral limb.
 for(let i=0;i<joints.length;i++)if(!roleByIndex[i]){let p=parentByIndex[i],guard=0;while(p!==undefined&&guard++<joints.length){if(roleByIndex[p]){roleByIndex[i]=roleByIndex[p];break;}p=parentByIndex[p];}}
 const nextRole=r=>{const s=r?.endsWith('_l')?'l':'r',base=r?.split('_')[0];return ({upperarm:'lowerarm',lowerarm:'hand',hand:'middle_1',thigh:'calf',calf:'foot',foot:'ball'})[base]?({upperarm:'lowerarm',lowerarm:'hand',hand:'middle_1',thigh:'calf',calf:'foot',foot:'ball'})[base]+'_'+s:({pelvis:'spineLower',spineLower:'spineMiddle',spineMiddle:'chest',chest:'neck',neck:'head'})[r];};
 const segments=joints.map((j,i)=>{const role=roleByIndex[i],primary=Number.isInteger(roles[role])?roles[role]:i,start=joints[primary].position,nr=nextRole(role),next=Number.isInteger(roles[nr])?roles[nr]:children[i].find(k=>length(sub(joints[k].position,start))>height*.003),end=next!==undefined?joints[next].position:start;return {id:i,name:j.name,role,start:[...start],end:[...end],length:length(sub(end,start)),region:regionForRole(role),surfaceRadius:null,supportRadius:null,crossSections:[],evidence:'imported-bind-rig',supportEvidence:'not-measured'};});
 if(count&&(skinIndex?.length!==count*8||skinWeight?.length!==count*8))throw Error('Expected all eight surface influences');
 const samples=segments.map(()=>Array.from({length:8},()=>[])),stride=Math.max(1,Math.ceil(count/maxSamples));let sampled=0,badWeights=0;
 for(let i=0;i<count;i+=stride){const p=Array.from(positions.subarray(i*3,i*3+3));let sum=0;for(let k=0;k<8;k++){const id=skinIndex[i*8+k],w=skinWeight[i*8+k];if(id>=segments.length||!Number.isFinite(w)||w<0)throw Error('Invalid bone weight');sum+=w;if(w<.12||segments[id].length<height*.004)continue;const s=segments[id],t=projection(p,s.start,s.end),r=length(sub(p,segmentPoint(p,s.start,s.end)));if(r<height*.20)samples[id][Math.min(7,Math.floor(t*8))].push(r);}if(Math.abs(sum-1)>.02)badWeights++;sampled++;}
 for(let i=0;i<segments.length;i++){const rows=samples[i],all=rows.flat(),s=segments[i];if(all.length>=16){s.surfaceRadius=quantile(all,.55);s.supportRadius=Math.max(height*.0015,quantile(all,.25)*.30);s.supportEvidence='authored-protection-fitted-to-observed-skin';s.crossSections=rows.map((a,k)=>({t:(k+.5)/8,samples:a.length,r25:quantile(a,.25),r55:quantile(a,.55),r85:quantile(a,.85)}));}}
 if(badWeights)warnings.push({code:'non-normalized-skin-weights',samples:badWeights});
 const profile={schema:ANATOMY_SCHEMA,status,sourceId:input.sourceId||'unidentified',unit:input.unit||'source-units',frame:{origin:[...pelvis],right,up,front,height,floor,top},roles,roleByIndex,joints:joints.map(j=>({...j,position:[...j.position]})),segments,warnings,observations:{joints:joints.length,surfaceSamples:sampled,skinInfluences:8,shoulderDistance:length(sub(pos('upperarm_l'),pos('upperarm_r'))),hipDistance:length(sub(pos('thigh_l'),pos('thigh_r')))},unknown:['internal-bone-surfaces','individual-muscle-boundaries','true-muscle-attachment-sites','true-fat-thickness','hidden-body-under-clothes'],canDeform:badWeights===0};
 profile.muscles=buildMuscleAtlas(profile);profile.local=local;return profile;
}
export function compactAnatomy(profile){return {schema:profile.schema,status:profile.status,sourceId:profile.sourceId,unit:profile.unit,frame:profile.frame,roles:profile.roles,observations:profile.observations,warnings:profile.warnings,unknown:profile.unknown,canDeform:profile.canDeform,bones:profile.segments.map(s=>({id:s.id,name:s.name,role:s.role,length:s.length,surfaceRadius:s.surfaceRadius,supportRadius:s.supportRadius,evidence:s.evidence,supportEvidence:s.supportEvidence})),muscles:profile.muscles.map(m=>({id:m.id,label:m.label,group:m.group,side:m.side,path:m.attachments,actions:m.actions,antagonists:m.antagonists,evidence:m.evidence,available:m.available})),rules:['composition-does-not-change-bind-bones','muscle-attachments-are-estimated','adipose-attenuates-muscle-relief','microskin-is-independent','new-subject-must-be-reanalyzed']};}
