import * as THREE from 'three';
import {analyzeHumanoid,compactAnatomy}from './AnatomyAnalysis.mjs';
import {ANATOMY_RULES}from './AnatomyContract.mjs';
import {muscleWeight}from './MuscleAtlas.mjs';
export function createAnatomyWorkbench({getSubject,actor,enter,exit}){
 const panel=document.createElement('details');panel.id='anatomyPanel';panel.innerHTML='<summary>解剖分析 · 规则与证据</summary><p id="anatomySummary"></p><button id="anatomyEnter">检查骨架与组织</button><select id="anatomyView"><option value="bones">实际绑定骨架</option><option value="muscle">肌肉关系与估计影响区</option><option value="fat">脂肪遮蔽与保护区</option></select><select id="anatomyMuscle"></select><p id="anatomyEvidence"></p><button id="anatomyExport">导出分析报告</button><small>骨段来自当前绑定数据。肌肉路线为自创解剖模板估计，不能作为真实附着点或内部肌肉边界。未来模型先分析、校准，再接入体型。</small>';document.querySelector('#bodyPanel').before(panel);
 const $=id=>panel.querySelector('#'+id);let active=false,lines=null,savedBones=false;
 function clear(){if(lines){actor.remove(lines);lines.geometry.dispose();lines.material.dispose();lines=null;}}
 function display(){const s=getSubject();if(!s)return;clear();const a=s.mesh.geometry.attributes.faceInspection;a.array.fill(0);if(active)s.helper.visible=$('anatomyView').value==='bones';if(active&&$('anatomyView').value!=='bones'){const m=s.body.anatomy.muscles.find(m=>m.id===$('anatomyMuscle').value),p=s.mesh.geometry.attributes.skinRest.array;for(let i=0;i<a.count;i++){const w=$('anatomyView').value==='fat'?s.body.adipose.delta[i*4+3]:m?muscleWeight(Array.from(p.subarray(i*3,i*3+3)),m):0;if(w>.001)a.setXYZW(i,1-w,.12+.75*w,.1,.65*w);}if($('anatomyView').value==='muscle'&&m?.available){const points=m.path.slice(1).flatMap((p,i)=>[...m.path[i],...p]),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));lines=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0xffad31,depthTest:false}));lines.renderOrder=35;actor.add(lines);}}
 a.needsUpdate=true;const m=s.body.anatomy.muscles.find(m=>m.id===$('anatomyMuscle').value);$('anatomyEvidence').textContent=$('anatomyView').value==='muscle'&&m?`${m.label}：${m.actions.join(' / ')}。拮抗关系：${m.antagonists.join(', ')||'未定义'}。参考骨段：${m.attachments.map(a=>a.role).join(' → ')}。附着精度：未观测。`:$('anatomyView').value==='fat'?'暖色是脂肪遮蔽影响区，未着色是保护区。厚度为造型估计，肌肉尺度起伏随脂肪衰减；微观肤质独立。':'骨架来自输入绑定姿态；骨内部形状、软组织厚度与肌肉精确边界未观测。';}
 function refresh(){const p=getSubject()?.body.anatomy;if(!p)return;$('anatomySummary').textContent=`${p.joints.length} 个绑定骨骼 · ${p.observations.surfaceSamples.toLocaleString()} 个表面采样 · ${p.muscles.length} 个左右肌肉/肌群关系 · ${p.warnings.length} 项骨架警告`;const selected=$('anatomyMuscle').value;$('anatomyMuscle').replaceChildren(...p.muscles.map(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.label+(m.available?'':' · 待校准');return o;}));if(selected)$('anatomyMuscle').value=selected;display();}
 function setActive(v){if(active===v)return;if(v){savedBones=getSubject().helper.visible;enter();active=true;panel.open=true;}else{active=false;clear();getSubject().helper.visible=savedBones;exit();}display();$('anatomyEnter').textContent=active?'退出解剖检查':'检查骨架与组织';}
 $('anatomyEnter').onclick=()=>setActive(!active);$('anatomyView').onchange=display;$('anatomyMuscle').onchange=display;
 $('anatomyExport').onclick=()=>{const blob=new Blob([JSON.stringify(compactAnatomy(getSubject().body.anatomy),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='human-anatomy-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};refresh();
 return {analyze:analyzeHumanoid,export:()=>compactAnatomy(getSubject().body.anatomy),rules:ANATOMY_RULES,setActive,refresh,inspect(mode,id){setActive(true);$('anatomyView').value=mode;if(id)$('anatomyMuscle').value=id;display();},get active(){return active;}};
}
