import {BODY_DEFAULT,BODY_CONTROLS,BODY_PRESETS,normalizeBody} from './BodyParameters.mjs';
export function createBodyWorkbench({apply,getReport}){
 const storage='human.r008.body.v1',panel=document.createElement('details');panel.id='bodyPanel';panel.open=true;let recipe=normalizeBody(),busy=false;
 try{const raw=localStorage.getItem(storage);if(raw)recipe=normalizeBody(JSON.parse(raw));}catch{}
 panel.innerHTML=`<summary>体型与年龄</summary><label>体型示例<select id="bodyPreset"><option value="custom">自定义</option>${Object.entries(BODY_PRESETS).map(([id,p])=>`<option value="${id}">${p.label}</option>`).join('')}</select></label>${BODY_CONTROLS.map(c=>`<label>${c.label} <output id="body-${c.key}-value"></output><input id="body-${c.key}" aria-label="${c.label}" type="range" min="${c.min}" max="${c.max}" step="${c.step}" style="width:100%"></label>`).join('')}<div class="row"><button id="bodyApply">应用体型与年龄</button><button id="bodyReset">恢复原人物</button></div><small>成人范围的外观变化：胖瘦、肌肉量独立调整；年龄影响脸颊、细纹、肤质和发色。应用时短暂停留，保留肤色、伤疤与镜头。数值是造型控制，不是体脂率或医学测量。</small><p id="bodyMessage" role="status"></p>`;
 document.querySelector('#surfacePanel').before(panel);const $=id=>panel.querySelector('#'+id);
 function refresh(){for(const c of BODY_CONTROLS){$('body-'+c.key).value=recipe[c.key];$('body-'+c.key+'-value').value=c.key==='height'?(recipe[c.key]*100).toFixed(0)+' cm':c.key==='age'?recipe[c.key].toFixed(0)+' 岁':recipe[c.key].toFixed(2);}}
 async function set(patch){if(busy)throw Error('体型正在应用，请稍候');const next=normalizeBody({...recipe,...patch});busy=true;for(const e of panel.querySelectorAll('input,select,button'))e.disabled=true;$('bodyMessage').textContent='正在计算体型与表面法线…';await new Promise(r=>setTimeout(r,40));try{await apply(next);recipe=next;refresh();try{localStorage.setItem(storage,JSON.stringify(recipe));}catch{}$('bodyMessage').textContent=`已应用 · 身高 ${(recipe.height*100).toFixed(0)} cm · 年龄外观 ${recipe.age.toFixed(0)} 岁`;return {...recipe};}catch(e){refresh();$('bodyMessage').textContent=e.message;throw e;}finally{busy=false;for(const e of panel.querySelectorAll('input,select,button'))e.disabled=false;}}
 for(const c of BODY_CONTROLS)$('body-'+c.key).oninput=()=>{$('body-'+c.key+'-value').value=c.key==='height'?(Number($('body-'+c.key).value)*100).toFixed(0)+' cm':c.key==='age'?$('body-'+c.key).value+' 岁':Number($('body-'+c.key).value).toFixed(2);$('bodyPreset').value='custom';};
 $('bodyApply').onclick=()=>set(Object.fromEntries(BODY_CONTROLS.map(c=>[c.key,Number($('body-'+c.key).value)]))).catch(()=>{});
 $('bodyReset').onclick=()=>set(BODY_DEFAULT).catch(()=>{});$('bodyPreset').onchange=()=>{if($('bodyPreset').value==='custom')return;set({...BODY_DEFAULT,...BODY_PRESETS[$('bodyPreset').value].recipe}).catch(()=>{});};refresh();
 return {set,restore:r=>set(normalizeBody(r)),export:()=>({...recipe}),preset:id=>{if(!Object.hasOwn(BODY_PRESETS,id))throw Error('未知体型示例');return set({...BODY_DEFAULT,...BODY_PRESETS[id].recipe});},bind:()=>apply(recipe,{bind:true}),get busy(){return busy;},get report(){return getReport();}};
}
