import {IDENTITY_PARAMETERS,normalizeIdentity} from './FaceIdentityModel.mjs';
import {normalizeReference,referenceCoordinates,referencePointPixels} from './FaceLandmarks.mjs';
import {projectCanonical} from './FaceMeasurements.mjs';
export function faceReferenceError(landmarks,reference){const ref=normalizeReference(reference),target=referenceCoordinates(referencePointPixels(ref)),model=referenceCoordinates(Object.fromEntries(landmarks.filter(p=>p.point).map(p=>[p.id,projectCanonical(p.point)]))),rows=landmarks.filter(p=>p.point&&target[p.id]&&ref.landmarks[p.id]?.visible),groups={};for(const p of rows)groups[p.group]=(groups[p.group]||0)+1;
 const residuals=[],groupError={},pointErrors=[];let square=0,weight=0;for(const p of rows){const confidence=p.confidence*ref.landmarks[p.id].confidence,w=confidence/groups[p.group],delta=model[p.id].map((x,k)=>x-target[p.id][k]),distance=Math.hypot(...delta);for(const x of delta)residuals.push(x*Math.sqrt(w));square+=w*distance*distance;weight+=w;const g=groupError[p.group]||(groupError[p.group]={square:0,weight:0,points:0});g.square+=confidence*distance*distance;g.weight+=confidence;g.points++;pointErrors.push({id:p.id,label:p.label,group:p.group,distance,confidence});}return {rms:Math.sqrt(square/(weight||1)),points:rows.length,residuals,groups:Object.fromEntries(Object.entries(groupError).map(([id,g])=>[id,{rms:Math.sqrt(g.square/(g.weight||1)),points:g.points}])),largestErrors:pointErrors.sort((a,b)=>b.distance-a.distance).slice(0,8),evidence:'2D landmark error / eye-centre distance; not identity similarity score'};
}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let pivot=c;for(let i=c+1;i<n;i++)if(Math.abs(M[i][c])>Math.abs(M[pivot][c]))pivot=i;if(Math.abs(M[pivot][c])<1e-12)return null;[M[pivot],M[c]]=[M[c],M[pivot]];const q=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=q;for(let i=0;i<n;i++)if(i!==c){const s=M[i][c];for(let j=c;j<=n;j++)M[i][j]-=s*M[c][j];}}return M.map(r=>r[n]);}
export async function fitFaceReference({reference,initial,evaluate,onProgress,maxIterations=40}){
 const ref=normalizeReference(reference),recipe=normalizeIdentity(initial),descriptors=IDENTITY_PARAMETERS.filter(d=>d.fit),ranges=descriptors.map(d=>Math.max(Math.abs(d.min),Math.abs(d.max))),initialError=faceReferenceError(evaluate(recipe.parameters),ref);if(initialError.points<10)throw Error('至少需要 10 个可见标志点；左右眼中心必须记录');
 let u=descriptors.map((d,i)=>(recipe.parameters[d.id]||0)/ranges[i]),lambda=.001;const regularization=.00004,history=[];
 const params=v=>{const p={...recipe.parameters};descriptors.forEach((d,i)=>p[d.id]=v[i]*ranges[i]);return p;},residual=v=>{const p=params(v),error=faceReferenceError(evaluate(p),ref);return {...error,residuals:error.residuals.concat(evaluate.constraintResiduals?.(p)||[])};},cost=(r,v)=>r.residuals.reduce((s,x)=>s+x*x,0)+regularization*v.reduce((s,x)=>s+x*x,0);
 let seedAdjusted=false;if(evaluate.feasible)for(let tries=0;!evaluate.feasible(params(u));tries++){if(tries>=24)throw Error('当前深度组合没有足够的形变空间，请先减少深度调整');u=u.map(v=>v*.8);seedAdjusted=true;}
 let current=residual(u),objective=cost(current,u);
 for(let iteration=0;iteration<maxIterations;iteration++){
  const columns=descriptors.map((d,i)=>{const v=[...u],step=.004;v[i]+=step;const r=residual(v);return r.residuals.map((x,k)=>(x-current.residuals[k])/step);}),n=u.length,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);
  for(let i=0;i<n;i++){b[i]=-columns[i].reduce((s,x,k)=>s+x*current.residuals[k],0)-regularization*u[i];for(let j=0;j<n;j++)A[i][j]=columns[i].reduce((s,x,k)=>s+x*columns[j][k],0);A[i][i]+=regularization+lambda;}
  const step=solve(A,b);if(!step)break;let candidate,next,nextCost,accepted=false;
  for(let fraction=1;fraction>=1/1024;fraction*=.5){candidate=u.map((x,i)=>Math.max(descriptors[i].min/ranges[i],Math.min(descriptors[i].max/ranges[i],x+fraction*Math.max(-.22,Math.min(.22,step[i])))));if(evaluate.feasible&&!evaluate.feasible(params(candidate)))continue;next=residual(candidate);nextCost=cost(next,candidate);if(nextCost<objective){accepted=true;break;}}
  if(accepted){u=candidate;current=next;objective=nextCost;lambda=Math.max(.000001,lambda*.55);}else lambda=Math.min(10,lambda*5);
  history.push({iteration:iteration+1,rms:current.rms,accepted});onProgress?.(history.at(-1));await new Promise(resolve=>setTimeout(resolve,0));if(accepted&&Math.max(...step.map(Math.abs))<.0003)break;
 }
 const parameters=params(u);for(const key of Object.keys(parameters))if(Math.abs(parameters[key])<.000001)delete parameters[key];return {recipe:normalizeIdentity({...recipe,parameters}),before:initialError.rms,after:current.rms,points:current.points,iterations:history.length,history,depthFitted:false,method:'bounded-regularized-landmark-fit@2',safetyConstrained:!!evaluate.constraintResiduals,seedAdjusted,limitations:'只拟合可见正面标志点；未观察深度不求解；有限形变基，不保证任意脸型或身份相似度。'};
}
