import * as THREE from 'three';
import {IDENTITY_PARAMETERS,DEMO_IDENTITY,normalizeIdentity,FACE_IDENTITY_SCHEMA,FACE_IDENTITY_SOURCE} from './FaceIdentityModel.mjs';
import {FACE_LANDMARKS,LANDMARK_SCHEMA,normalizeReference} from './FaceLandmarks.mjs';
import {projectCanonical} from './FaceMeasurements.mjs';
import {fitFaceReference,faceReferenceError} from './FaceReferenceFit.mjs';
const STORAGE='human.r008.face-identity.v1',REFERENCE_STORAGE='human.r008.face-reference.v1';
const recipeFor=parameters=>normalizeIdentity({schema:FACE_IDENTITY_SCHEMA,source:FACE_IDENTITY_SOURCE,parameters});
export function createFaceIdentityWorkbench({getSubject,actor,ensureFront}){
 const $=id=>document.getElementById(id),panel=document.createElement('section');panel.id='faceIdentityEditor';panel.hidden=true;
 panel.innerHTML=`<h3>面部数据 · 身份与比例</h3><button id="referenceResult">载入本次参考与拟合结果</button><p>全脸外表面参数与五官测量。左右以人物自身为准；正值含义见参数名称。零值是当前人物基准。</p>
 <label>参数组<select id="identityGroup"></select></label><label>调整项目<select id="identityParameter"></select></label>
 <p id="identityLogic"></p><div class="row"><input id="identityValue" type="number" step=".1" aria-label="面部参数数值"><strong id="identityUnit"></strong><button id="identityApply">应用</button></div><input id="identitySlider" type="range" aria-label="面部参数滑块" style="width:100%">
 <label><input id="identityMirror" type="checkbox" checked> 左右同步调整</label><label><input id="identityMarkers" type="checkbox" checked> 显示实际五官标志点</label><label><input id="identityReferenceEyes" type="checkbox" checked> 使用参考虹膜 / 瞳孔比例</label>
 <div class="row"><button id="identityDemo">特征差异演示</button><button id="identityCompare">对比基准</button></div><div class="row"><button id="identityReset">恢复身份基准</button><button id="identityExport">导出面部数据</button></div><button id="identityRecipeExport">导出调整配方</button><label>载入身份配方<input id="identityRecipeFile" type="file" accept="application/json,.json"></label>
 <p id="identityStatus" role="status"></p><details><summary>变化逻辑与数据边界</summary><p>先在中性表面叠加局部微调和表情，再施加身份变化。头脸比例使用连续场，眼、眉、鼻、唇、颊、下颌使用局部仿射场；眼球与眼睑同步映射，法线随形变变化。组合超出采样安全范围时会显示实际限幅。</p><p>标志点绑定当前表面或眼部构造；眉、唇、发际线等语义位置是本人物校准，需结合参考图复核。眼区是有限范围的整体形态近似，不能视为真实眼球解剖恢复。发型、毛发密度、牙列及内部骨骼不由这组参数重建。</p><p>图片坐标以两眼中心建立方向和尺度，只比较可见比例。没有标尺的单图不换算真实毫米；侧面深度保留未知。数值误差不是身份相似度评分。</p></details>
 <details id="identityReferenceDetails"><summary>下一步 · 参考图片与数据</summary><p>载入照片，在右侧按五官名称标点；也可导入助手记录的坐标数据。未标记的点保持未知，不参与拟合。</p><label>参考图片<input id="referenceImageFile" type="file" accept="image/*"></label><label>参考坐标文件<input id="referenceDataFile" type="file" accept="application/json,.json"></label><button id="referenceRead">读取已记录的参考数据</button><textarea id="referenceJSON" rows="4" placeholder="粘贴 human/face-reference@1 数据" aria-label="参考坐标 JSON"></textarea><div class="row"><button id="referenceImport">导入坐标</button><button id="referenceExport">导出坐标</button></div><button id="referenceFit">按参考数据调整</button><button id="referenceDemoFit">验证数据拟合路线（演示目标）</button><button id="referenceClear">清除参考目标</button><p id="referenceStatus" role="status">等待参考图片</p></details>`;
 $('faceControls').append(panel);
 const numeric=document.createElement('section');numeric.id='identityNumericPanel';numeric.hidden=true;numeric.innerHTML=`<h2>五官实测与参考比较</h2><p id="identitySummary"></p><div id="identityTargetPreview" hidden><img id="identityTargetPhoto" alt="用户提供的目标脸参考"><p id="identityTargetCaption"></p><small>第一版比例拟合：眼眉、唇缝与外观仍有差异。发型、肤质、伤痕和侧面深度尚未匹配。</small><button id="identityTargetAnnotate">检查照片标志点</button></div><div class="row"><button id="identityMeasureTab">比例数据</button><button id="identityImageTab">参考标点</button></div><div id="identityMeasureView"><small>毫米为当前模型构造尺寸。照片只比较投影比例；比例以两眼中心距离 = 1 归一化。</small><div class="identity-measure-scroll"><table><thead><tr><th>项目</th><th>模型<br>mm / °</th><th>比例</th><th>参考</th><th>误差</th></tr></thead><tbody id="identityMeasureRows"></tbody></table></div><p id="identityFitError"></p><p id="identityResiduals"></p><small>表面标志点经绑定；语义位置需校准。发际线可靠度较低。三庭五眼是比较量，不强制统一标准。</small></div><div id="identityImageView" hidden><label>当前标记<select id="referenceLandmark"></select></label><label>可信度<input id="referenceConfidence" type="number" min="0" max="1" step=".05" value=".75"></label><div class="row"><button id="referenceNext">下一点</button><button id="referenceRemove">该点未知</button></div><div id="referenceViewport"><svg id="referenceSVG" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" aria-label="参考图标志点编辑"><image id="referenceImage" x="0" y="0" width="600" height="600"/><g id="referenceDots"></g></svg><p id="referenceImageNote">尚未载入图片。图片仅用作参考，标志点坐标单独保存。</p></div><p id="referencePointInfo"></p><small>画面左为人物右。先标左右眼中心，再记录轮廓、眼缘、眉、鼻、唇。遮挡点不要猜测。</small></div>`;document.body.append(numeric);
 let visible=false,recipe=normalizeIdentity(),reference=null,busy=false,markers=null,comparison=null,baselineRows=[],imageURL=null,referenceEyeAppearance=null;
 const groups=[...new Set(IDENTITY_PARAMETERS.map(p=>p.group))];$('identityGroup').innerHTML=groups.map(g=>`<option>${g}</option>`).join('');$('referenceLandmark').innerHTML=FACE_LANDMARKS.map(p=>`<option value="${p.id}">${p.label} · ${p.id}</option>`).join('');$('referenceLandmark').value='pupilRight';
 function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function selection(){const d=IDENTITY_PARAMETERS.find(p=>p.id===$('identityParameter').value);if(!d)return;const v=recipe.parameters[d.id]||0;for(const id of ['identityValue','identitySlider']){const e=$(id);e.min=d.min;e.max=d.max;e.step=d.step;e.value=id==='identityValue'?Number(v.toFixed(2)):v;}$('identityUnit').textContent=d.unit;$('identityLogic').textContent=`${d.label} · ${d.min} 至 ${d.max} ${d.unit}。${d.unit==='%'?'百分比为该形变场的相对尺度，不等于实测特征保证同幅变化。':'数值是形变请求，实际变化见右侧测量。'}${!d.fit?'正面图不直接求解此深度参数。':''}`;}
 function group(){const previous=$('identityParameter').value;$('identityParameter').innerHTML=IDENTITY_PARAMETERS.filter(p=>p.group===$('identityGroup').value).map(p=>`<option value="${p.id}">${p.label}</option>`).join('');if([...$('identityParameter').options].some(o=>o.value===previous))$('identityParameter').value=previous;selection();}
 function setParameter(id,value,{mirror=true}={}){const p={...recipe.parameters,[id]:value};if(mirror&&/(Left|Right)$/.test(id))p[id.replace(/(Left|Right)$/,id.endsWith('Left')?'Right':'Left')]=value;return set(recipeFor(p));}
 function updateMarkers(){if(!visible||!$('identityMarkers').checked){if(markers)markers.visible=false;return;}const points=getSubject().identity.landmarks().filter(p=>p.point);if(!markers){markers=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:'#8cffda',size:.0045,sizeAttenuation:true,depthTest:false}));markers.renderOrder=40;actor.add(markers);}markers.visible=true;markers.geometry.setAttribute('position',new THREE.Float32BufferAttribute(points.flatMap(p=>p.point),3));markers.geometry.computeBoundingSphere();}
 function refreshRows(){if(!getSubject()?.identity)return;const model=getSubject().identity,rows=model.measure(reference);$('identityMeasureRows').innerHTML=rows.map(r=>`<tr title="模型语义可信度 ${r.confidence.toFixed(2)}${r.referenceConfidence!==null?' / 参考 '+r.referenceConfidence.toFixed(2):''}"><td>${r.label}</td><td>${r.actual!==null?r.actual.toFixed(1):'未知'}</td><td>${r.ratio!==null?r.ratio.toFixed(r.type==='tilt'?1:3):'—'}</td><td>${r.target!==null?r.target.toFixed(r.type==='tilt'?1:3):'—'}</td><td>${r.error!==null?(r.error>0?'+':'')+r.error.toFixed(r.type==='tilt'?1:3):'—'}</td></tr>`).join('');const report=model.report;$('identitySummary').textContent=`${IDENTITY_PARAMETERS.length} 项身份参数 · ${report.coverage.landmarksAvailable} / ${FACE_LANDMARKS.length} 个标志点 · ${report.samples.toLocaleString()} 头脸表面样本`;
  try{const e=reference?faceReferenceError(model.landmarks(),reference):null;const pixels=reference?.landmarks.pupilLeft&&reference?.landmarks.pupilRight?Math.hypot(...reference.landmarks.pupilLeft.xy.map((v,k)=>(v-reference.landmarks.pupilRight.xy[k])*(k?reference.image.height:reference.image.width))):0;$('identityResiduals').textContent=e?.groups?'各区位置误差（原图像素）：'+Object.entries(e.groups).map(([id,g])=>id+' '+(g.rms*pixels).toFixed(1)+' px').join(' · '):'';$('identityFitError').textContent=e?`${reference.kind==='synthetic-demo'?'演示目标':'参考目标'} · ${e.points} 个可见比较点 · 归一化位置误差 ${e.rms.toFixed(4)}`:'等待参考目标 · 当前只显示模型实测与基准；尚未匹配参考脸。';}catch(e){$('identityFitError').textContent=e.message;}
  updateMarkers();selection();
 }
 function applyEyeAppearance(){const eyes=getSubject()?.eyes;if(!eyes?.setAppearance)return;if(referenceEyeAppearance&&$('identityReferenceEyes').checked&&!comparison){const spacing=getSubject().identity.measure().find(r=>r.id==='eyeSpacing').actual;eyes.setAppearance(Object.fromEntries(['Left','Right'].map(side=>[side,{irisRadiusMM:spacing*referenceEyeAppearance[side].irisDiameterRatio/2,pupilRadiusMM:spacing*referenceEyeAppearance[side].pupilDiameterRatio/2}])));}else eyes.setAppearance();}
 function set(input,{save=true}={}){const next=normalizeIdentity(input);comparison=null;$('identityCompare').textContent='对比基准';ensureFront();const report=getSubject().identity.set(next);recipe=next;applyEyeAppearance();if(save)try{localStorage.setItem(STORAGE,JSON.stringify(recipe));}catch{}refreshRows();$('identityStatus').textContent=`已应用 · 最大实际位移 ${report.maxDisplacementMM.toFixed(2)} mm · 最小采样雅可比 ${report.minJacobian.toFixed(3)} · 安全缩放 ${report.safeScale.toFixed(3)}${report.safeScale<.999?'，实际调整已限幅':''}`;return report;}
 function selectTab(image){$('identityMeasureView').hidden=image;$('identityImageView').hidden=!image;$('identityTargetPreview').hidden=image||!imageURL;}
 function renderReference(){const svg=$('referenceSVG'),ref=reference;if(ref){svg.setAttribute('viewBox',`0 0 ${ref.image.width} ${ref.image.height}`);$('referenceImage').setAttribute('width',ref.image.width);$('referenceImage').setAttribute('height',ref.image.height);$('referenceDots').innerHTML=Object.entries(ref.landmarks).filter(([,p])=>p.visible).map(([id,p])=>`<g><circle cx="${p.xy[0]*ref.image.width}" cy="${p.xy[1]*ref.image.height}" r="${Math.max(ref.image.width,ref.image.height)*.004}" fill="${id===$('referenceLandmark').value?'#ffc36b':'#80ffc9'}" stroke="#182631" stroke-width="${Math.max(ref.image.width,ref.image.height)*.001}"/><title>${id}</title></g>`).join('');const selected=ref.landmarks[$('referenceLandmark').value];$('referencePointInfo').textContent=selected?`当前点 ${(selected.xy[0]*ref.image.width).toFixed(1)}, ${(selected.xy[1]*ref.image.height).toFixed(1)} px · 可信度 ${selected.confidence.toFixed(2)}`:'当前点未知';}else{$('referenceDots').replaceChildren();$('referencePointInfo').textContent='当前点未知';}}
 function setReference(input){reference=normalizeReference(input);try{localStorage.setItem(REFERENCE_STORAGE,JSON.stringify(reference));}catch{}$('referenceJSON').value=JSON.stringify(reference,null,2);$('referenceStatus').textContent=`${reference.kind==='synthetic-demo'?'演示数据，不是用户参考脸':'参考图片数据'} · ${Object.keys(reference.landmarks).length} 个记录点 · 深度和绝对尺寸未知`;renderReference();refreshRows();return reference;}
 function mark(id,xy,confidence=.75){if(!reference)throw Error('先载入参考图片');return setReference({...reference,landmarks:{...reference.landmarks,[id]:{xy,confidence,visible:true}}});}
 function nextPoint(){const e=$('referenceLandmark');e.selectedIndex=(e.selectedIndex+1)%e.options.length;renderReference();}
 async function fit(){if(busy)throw Error('正在拟合，请稍候');if(!reference)throw Error('先记录参考图片的标志点');ensureFront();busy=true;$('referenceFit').disabled=$('referenceDemoFit').disabled=true;
  try{const result=await fitFaceReference({reference,initial:recipeFor(getSubject().identity.report.effectiveParameters),evaluate:getSubject().identity.fitEvaluator(),onProgress:r=>{$('referenceStatus').textContent=`拟合第 ${r.iteration} 次 · 位置误差 ${r.rms.toFixed(4)}`;}});set(result.recipe);const measured=faceReferenceError(getSubject().identity.landmarks(),reference);const report={...result,actualAfter:measured.rms,actualSafeScale:getSubject().identity.report.safeScale};$('referenceStatus').textContent=`${reference.kind==='synthetic-demo'?'演示验证':'参考拟合'}完成 · ${result.points} 点 · 误差 ${result.before.toFixed(4)} → ${measured.rms.toFixed(4)} · 深度未求解`;api.lastFit=report;selectTab(false);return report;}finally{busy=false;$('referenceFit').disabled=$('referenceDemoFit').disabled=false;}}
 function syntheticReference(parameters=DEMO_IDENTITY){const points=getSubject().identity.fitEvaluator()(parameters),width=1000,height=1000,factor=height/(2*Math.tan(11*Math.PI/180));return {schema:LANDMARK_SCHEMA,kind:'synthetic-demo',image:{width,height,name:'authored-parameter-route-demo'},landmarks:Object.fromEntries(points.filter(p=>p.point).map(p=>{const q=projectCanonical(p.point);return [p.id,{xy:[.5+factor*q[0]/width,.5+factor*q[1]/height],confidence:p.confidence,visible:true}];})),notes:'由现有模型的已知参数生成目标，仅验证数据拟合闭环；不是用户参考图，不证明任意照片匹配质量。'};}
 async function demoFit(){setReference(syntheticReference());set(normalizeIdentity());return fit();}
 $('identityGroup').onchange=group;$('identityParameter').onchange=selection;$('identityApply').onclick=()=>{try{setParameter($('identityParameter').value,Number($('identityValue').value),{mirror:$('identityMirror').checked});}catch(e){$('identityStatus').textContent=e.message;}};
 $('identitySlider').oninput=()=>{$('identityValue').value=$('identitySlider').value;};$('identitySlider').onchange=()=>{$('identityApply').click();};$('identityMarkers').onchange=updateMarkers;$('identityReferenceEyes').onchange=applyEyeAppearance;
 $('identityDemo').onclick=()=>{set(recipeFor(DEMO_IDENTITY));$('identityStatus').textContent+=' · 当前为演示参数，非参考脸匹配。';};$('identityReset').onclick=()=>set(normalizeIdentity());
 $('identityCompare').onclick=()=>{if(comparison){const previous=comparison;comparison=null;recipe=previous;getSubject().identity.set(previous);$('identityCompare').textContent='对比基准';}else{comparison=normalizeIdentity(recipe);getSubject().identity.set(normalizeIdentity());$('identityCompare').textContent='恢复调整';}applyEyeAppearance();refreshRows();};
 $('identityExport').onclick=()=>download({...getSubject().identity.report,reference,eyeAppearance:getSubject().eyes.appearance,referenceEyeAppearance,fit:api.lastFit,baselineMeasurements:baselineRows,localShape:getSubject().face.partition.export(),referenceComparison:getSubject().identity.measure(reference)},'R008-face-data.json');$('identityRecipeExport').onclick=()=>download(recipe,'R008-face-identity.json');
 $('identityRecipeFile').onchange=async event=>{try{const file=event.target.files[0];if(file){const data=JSON.parse(await file.text());set(data.schema==='human-r008/face-data-report@1'?data.parameters:data);}}catch(e){$('identityStatus').textContent=e.message;}};
 $('identityMeasureTab').onclick=()=>selectTab(false);$('identityImageTab').onclick=()=>selectTab(true);$('referenceLandmark').onchange=renderReference;$('referenceNext').onclick=nextPoint;
 $('referenceRemove').onclick=()=>{if(reference){const landmarks={...reference.landmarks};delete landmarks[$('referenceLandmark').value];setReference({...reference,landmarks});}};
 $('referenceSVG').onclick=event=>{try{if(!imageURL)throw Error('坐标可导入；在图片上标点需先载入对应图片');const point=$('referenceSVG').createSVGPoint();point.x=event.clientX;point.y=event.clientY;const q=point.matrixTransform($('referenceSVG').getScreenCTM().inverse());mark($('referenceLandmark').value,[q.x/reference.image.width,q.y/reference.image.height],Number($('referenceConfidence').value));nextPoint();}catch(e){$('referenceStatus').textContent=e.message;}};
 $('referenceImageFile').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(imageURL)URL.revokeObjectURL(imageURL);imageURL=URL.createObjectURL(file);$('referenceStatus').textContent='正在读取参考图片…';const im=new Image();im.src=imageURL;await im.decode();$('referenceImage').setAttribute('href',imageURL);$('referenceImageNote').hidden=true;setReference({schema:LANDMARK_SCHEMA,image:{width:im.width,height:im.height,name:file.name},landmarks:{}});selectTab(true);$('referenceLandmark').value='pupilRight';renderReference();}catch(e){$('referenceStatus').textContent=e.message;}};
 $('referenceDataFile').onchange=async event=>{try{const file=event.target.files[0];if(file)setReference(JSON.parse(await file.text()));}catch(e){$('referenceStatus').textContent=e.message;}};
 $('referenceImport').onclick=()=>{try{setReference(JSON.parse($('referenceJSON').value));}catch(e){$('referenceStatus').textContent=e.message;}};$('referenceExport').onclick=()=>{if(reference)download(reference,'face-reference.json');};
 async function readRecorded({apply=false}={}){
 const response=await fetch('./face-reference.json',{cache:'no-store'});if(!response.ok)throw Error('参考数据读取失败：'+response.status);const data=await response.json();
 if(!data.reference){$('referenceStatus').textContent='尚未记录目标图片；下一步提供照片后写入参考坐标。';return null;}
 const requested=new URL(location.href).searchParams.get('reference');if(apply&&requested&&requested!==data.id)throw Error('此链接的参考版本与当前记录不同，请用载入按钮读取当前记录');
 referenceEyeAppearance=data.eyeAppearance||null;setReference(data.reference);if(data.imageURL){const url=new URL(data.imageURL,location.href);if(url.origin!==location.origin)throw Error('参考输入必须来自当前工作台');const im=new Image();im.src=url.href;try{await im.decode();if(im.naturalWidth!==reference.image.width||im.naturalHeight!==reference.image.height)throw Error('参考图片尺寸与坐标不一致');if(imageURL?.startsWith('blob:'))URL.revokeObjectURL(imageURL);imageURL=url.href;$('referenceImage').setAttribute('href',imageURL);$('referenceImageNote').hidden=true;$('identityTargetPhoto').src=imageURL;$('identityTargetPreview').hidden=false;}catch(e){$('referenceImageNote').textContent='参考原图不可用，已保留坐标数据：'+e.message;}}
 if(apply&&data.recipe){set(data.recipe);api.lastFit=data.fit||null;$('identityStatus').textContent+=' · 已载入用户参考的第一版拟合';$('identityMarkers').checked=false;updateMarkers();}
 const count=Object.keys(reference.landmarks).length;$('identityTargetCaption').textContent='用户参考 · '+count+' 个可见点；人工读数约 ±2–4 px。深度未知。';$('referenceStatus').textContent='已载入用户参考 · '+count+' 点'+(apply&&data.fit?' · 位置误差 '+data.fit.before.toFixed(4)+' → '+data.fit.actualAfter.toFixed(4):'');renderReference();refreshRows();selectTab(false);return data;
 }
 $('referenceRead').onclick=()=>readRecorded().catch(e=>$('referenceStatus').textContent=e.message);
 $('referenceResult').onclick=()=>readRecorded({apply:true}).catch(e=>$('referenceStatus').textContent=e.message);
 $('identityTargetAnnotate').onclick=()=>selectTab(true);
 $('referenceClear').onclick=()=>{reference=null;referenceEyeAppearance=null;applyEyeAppearance();$('identityTargetPreview').hidden=true;localStorage.removeItem(REFERENCE_STORAGE);$('referenceJSON').value='';$('referenceStatus').textContent='等待参考图片';if(imageURL?.startsWith('blob:'))URL.revokeObjectURL(imageURL);imageURL=null;$('referenceImage').removeAttribute('href');$('referenceImageNote').hidden=false;renderReference();refreshRows();};
 $('referenceFit').onclick=()=>fit().catch(e=>$('referenceStatus').textContent=e.message);$('referenceDemoFit').onclick=()=>demoFit().catch(e=>$('referenceStatus').textContent=e.message);
 function refresh(){const s=getSubject();if(!s?.identity)return;baselineRows=s.identity.measure();try{const stored=localStorage.getItem(STORAGE);recipe=stored?normalizeIdentity(JSON.parse(stored)):normalizeIdentity();s.identity.set(recipe);}catch{recipe=normalizeIdentity();s.identity.set(recipe);}try{const stored=localStorage.getItem(REFERENCE_STORAGE);if(stored)reference=normalizeReference(JSON.parse(stored));}catch{reference=null;}group();renderReference();refreshRows();$('identityStatus').textContent='身份参数已准备 · 当前保存 '+Object.keys(recipe.parameters).length+' 项调整';}
 const api={set,setParameter,export:()=>normalizeIdentity(recipe),setReference,mark,fit,demoFit,syntheticReference,refresh,get reference(){return reference;},get report(){return getSubject().identity.report;},lastFit:null,setVisible(value){visible=value;panel.hidden=numeric.hidden=!value;updateMarkers();if(value)refreshRows();},dispose(){if(markers){actor.remove(markers);markers.geometry.dispose();markers.material.dispose();}numeric.remove();panel.remove();if(imageURL)URL.revokeObjectURL(imageURL);}};
 refresh();if(new URL(location.href).searchParams.has('reference'))api.ready=readRecorded({apply:true}).catch(e=>{$('referenceStatus').textContent=e.message;});return api;
}
