import * as THREE from 'three';
import {createAnatomyDisplay} from './AnatomyDisplay.mjs';
import {createSurfaceSkeletonDisplay} from './SurfaceSkeletonDisplay.mjs';

export function createMotionAnatomyWorkbench({getSubject,actor,getView,enter,exit}){
 const panel=document.createElement('details');panel.id='motionAnatomyPanel';panel.innerHTML=`<summary>骨性框架 / 运动肌肉 · 三维展示</summary>
 <p>统一反推方法：当前表面 → 骨架候选 → 组织预算 → 运动肌群。方法一致，人物差异由各自数据决定；内部结构仍为估计。</p>
 <div style="display:flex;gap:6px"><button id="frameworkShow">① 反推骨性框架</button><button id="motorShow">② 同数据运动肌群</button></div>
 <button id="inverseShow">③ 根据当前表面反推骨架</button><div id="inverseControls" hidden><p>金色：表面约束的骨段中心线 / 关节候选；青色：原绑定参考；绿色：实际表面拟合截面；红色：数据不足或关节拟合需复核。皮肤轴不等同于真实骨轴，骨形与关节仍为估计。</p><label><input id="inverseSections" type="checkbox" checked>显示表面截面</label><label><input id="inversePrior" type="checkbox" checked>对照原绑定</label><label><input id="inverseSkin" type="checkbox" checked>半透明显示当前人物</label><select id="inverseSegment" aria-label="反推骨段"></select><p id="inverseMetrics" style="white-space:pre-line"></p><button id="inverseExport">导出反推参数与误差</button><small>拟合原人物参考体型与参考姿势，临时暂停体型调整；退出恢复原配方。不改动来源表面或动画绑定。衣物区域不充当人体表面；未知骨直径和内部结构保持未观测。</small></div>
 <label>演示动作<select id="motorAction"><option value="rest">静止 / 手动关节</option><option value="elbow">屈肘 · 二头肌 / 三头肌</option><option value="knee">屈膝 · 股四头肌 / 腘绳肌</option><option value="shoulder">抬臂 · 三角肌 / 肩带</option><option value="walk">当前人物行走</option><option value="run">当前人物跑步</option></select></label>
 <button id="motorPlay">暂停演示</button><label>相对绑定姿势角度 <output id="motorAngleValue">0°</output><input id="motorAngle" type="range" min="0" max="110" step="1" value="0" style="width:100%"></label>
 <label>手动关节<select id="motorJoint"><option value="elbow">肘关节</option><option value="knee">膝关节</option><option value="shoulder">肩外展</option></select></label>
 <label>肌群 / 拮抗对<select id="motorSelection"><option value="all">全部主要运动肌群</option></select></label>
 <label><input id="motorSkin" type="checkbox">显示原人物表面作比例对照（内部结构被遮挡）</label>
 <p id="motorLegend">米色：估计骨轮廓 / 肌腱；青色：绑定关节；红橙：缩短；蓝色：拉长。</p>
 <p id="motorMetrics"></p><small>演示由关节运动驱动肌肉路径，尚非肌肉力量驱动的动力学。肌肉真实附着点、激活、力量未观测。骨架不随胖瘦滑块缩骨。</small>
 <button id="motorExit">返回人物工作台</button>`;
 document.querySelector('#anatomyPanel').before(panel);
 const $=id=>panel.querySelector('#'+id);let active=false,display=null,inverse=null,bound=null,saved=null,referenceState=null,mode='framework',time=0,playing=true,manualAngle=0,lastMetrics=0;
 function bind(){const s=getSubject();if(bound===s)return;display?.dispose();inverse?.dispose();inverse=null;bound=s;inverse=createSurfaceSkeletonDisplay(s,actor);display=createAnatomyDisplay(s,actor,{profile:inverse.system.profile,model:inverse.system.muscles});$('inverseSegment').replaceChildren(new Option('全部骨段 / 表面轴','all'),...inverse.fit.segments.map(s=>new Option(s.label+' · '+s.id,s.id)));$('motorSelection').replaceChildren(new Option('全部主要运动肌群','all'),...display.model.muscles.map(m=>new Option((m.side==='l'?'左':'右')+' · '+m.label,m.id)));}
 function rotate(role,axis,angle){const s=getSubject(),id=s.body.anatomy.roles[role];if(!Number.isInteger(id))return;const b=s.skeleton.bones[id],parentQ=b.parent.getWorldQuaternion(new THREE.Quaternion()),localAxis=new THREE.Vector3(...axis).applyQuaternion(parentQ.invert()).normalize();b.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(localAxis,angle));s.root.updateMatrixWorld(true);}
 function jointPose(joint,degrees){const s=getSubject(),f=s.body.anatomy.frame,a=degrees*Math.PI/180;s.play('rest');for(const side of ['l','r']){if(joint==='elbow')rotate('lowerarm_'+side,f.right,-a);else if(joint==='knee')rotate('calf_'+side,f.right,a);else rotate('upperarm_'+side,f.front,a*(side==='l'?1:-1));}s.finishPose();}
 function pose(dt){if(mode==='inverse'){jointPose('elbow',0);return;}const s=getSubject(),action=$('motorAction').value;if(action==='walk'||action==='run'){if(s.phase!==action)s.play(action);if(playing)s.step(dt);else s.finishPose();}else{if(playing&&action!=='rest')time+=dt;const angle=action==='rest'?manualAngle:(1-Math.cos(time*1.6))*.5*(action==='shoulder'?85:105);$('motorAngle').value=Math.round(angle);$('motorAngleValue').value=Math.round(angle)+'°';jointPose(action==='rest'?$('motorJoint').value:action,angle);}}
 function update(dt=0){if(!active)return;pose(dt);if(mode==='inverse'){inverse?.update();return;}display.update(dt);lastMetrics+=dt;if(lastMetrics>.15||dt===0){lastMetrics=0;const selected=$('motorSelection').value,rows=display.report.muscles.filter(m=>selected==='all'?['biceps_l','triceps_l','rectus_femoris_l','hamstrings_l'].includes(m.id):m.id===selected||m.id===display.model.muscles.find(m=>m.id===selected)?.antagonist);$('motorMetrics').textContent=rows.map(m=>`${m.label}：${(m.length*100).toFixed(1)}cm · ${(m.lengthRatio*100).toFixed(0)}% 初始路径长度`).join('\n');$('motorMetrics').style.whiteSpace='pre-line';}}
 function restoreMaterials(){if(saved)for(let i=0;i<saved.materials.length;i++)Object.assign(getSubject().mesh.material[i],saved.materials[i],{needsUpdate:true});}
 function referenceBody(v){const s=getSubject();if(v&&!referenceState){const controls=[...document.querySelectorAll('#bodyPanel input,#bodyPanel select,#bodyPanel button')];referenceState={recipe:s.body.export(),controls:controls.map(e=>[e,e.disabled])};s.body.set({...referenceState.recipe,fatness:0,muscle:0,age:32});for(const e of controls)e.disabled=true;}else if(!v&&referenceState){s.body.set(referenceState.recipe);for(const [e,disabled]of referenceState.controls)e.disabled=disabled;referenceState=null;}}
 function setSkin(){const s=getSubject();restoreMaterials();if(mode==='inverse'){s.mesh.visible=$('inverseSkin').checked;s.eyes.root.visible=false;for(const m of s.mesh.material){m.transparent=true;m.opacity=.18;m.depthWrite=false;m.needsUpdate=true;}}else{s.mesh.visible=$('motorSkin').checked;s.eyes.root.visible=$('motorSkin').checked;}}
 function setActive(v){if(v===active)return;if(v){enter();bind();const s=getSubject();saved={mesh:s.mesh.visible,eyes:s.eyes.root.visible,helper:s.helper.visible,view:getView().snapshot(),materials:s.mesh.material.map(m=>({transparent:m.transparent,opacity:m.opacity,depthWrite:m.depthWrite}))};active=true;panel.open=true;referenceBody(true);s.helper.visible=false;setSkin();const p=actor.position.clone().add(new THREE.Vector3(0,.96*actor.scale.y,0));getView().frame(p,p.clone().add(new THREE.Vector3(0,.05,2.8*actor.scale.y)));display.setMode(mode);update();}else{active=false;referenceBody(false);display.root.visible=false;if(inverse)inverse.root.visible=false;restoreMaterials();const s=getSubject();s.mesh.visible=saved.mesh;s.eyes.root.visible=saved.eyes;s.helper.visible=saved.helper;const prior=saved;exit();getView().frame(new THREE.Vector3().fromArray(prior.view.target),new THREE.Vector3().fromArray(prior.view.position));saved=null;} }
 function inverseMetrics(){if(!inverse)return;const f=inverse.fit,s=f.segments.find(s=>s.id===$('inverseSegment').value)||f.segments[0],side=s?.id.endsWith('_l')?'左':s?.id.endsWith('_r')?'右':'';$('inverseMetrics').textContent=`统一方法：${f.unified?.methodId||inverse.system.method.id}\n表面采样 ${f.surfaceSamples.toLocaleString()} · 排除衣物/未知 ${f.excludedSamples.toLocaleString()}\n截面约束骨段 ${f.summary.surfaceFittedSegments}/${f.summary.totalSegments} · 调整关节 ${f.summary.adjustedJoints} · 需复核 ${f.summary.jointsNeedingReview}\n最大中心偏移 ${(f.summary.maximumJointShift*1000).toFixed(1)}mm\n${side}${s.label}：原参考长 ${(s.priorLength*100).toFixed(1)}cm → 候选长 ${(s.length*100).toFixed(1)}cm\n有效截面 ${s.observedSections}/${s.totalSections} · 皮肤截面残差 ${s.rms===null?'无有效观测':(s.rms*1000).toFixed(1)+'mm'}\n近端：${s.startStatus}；远端：${s.endStatus}\n同源肌群 ${inverse.system.report().muscles} · 表面尺寸约束 ${inverse.system.report().surfaceSizedMuscles}\n残差衡量外表面与椭圆的差异；肌肉/脂肪分配是共用先验。`;}
 function show(v){if(!['framework','muscles','inverse'].includes(v))throw Error('Unknown anatomy view');mode=v;setActive(true);display.setMode(v==='inverse'?'framework':v);display.root.visible=v!=='inverse';referenceBody(true);if(v==='inverse'){if(!inverse){inverse=createSurfaceSkeletonDisplay(getSubject(),actor);$('inverseSegment').replaceChildren(new Option('全部骨段 / 表面轴','all'),...inverse.fit.segments.map(s=>new Option(s.label+' · '+s.id,s.id)));}inverse.root.visible=true;inverseMetrics();}else if(inverse)inverse.root.visible=false;$('inverseControls').hidden=v!=='inverse';for(const id of ['motorAction','motorPlay','motorAngle','motorJoint','motorSelection','motorSkin'])$(id).disabled=v==='inverse';setSkin();$('frameworkShow').style.outline=v==='framework'?'2px solid #5fd6e5':'';$('motorShow').style.outline=v==='muscles'?'2px solid #e35732':'';$('inverseShow').style.outline=v==='inverse'?'2px solid #ffc767':'';document.querySelector('aside').scrollTop=panel.offsetTop-20;update();}
 $('frameworkShow').onclick=()=>show('framework');$('motorShow').onclick=()=>show('muscles');$('motorExit').onclick=()=>setActive(false);$('motorSkin').onchange=setSkin;
 $('inverseShow').onclick=()=>show('inverse');$('inverseSections').onchange=()=>inverse?.setSections($('inverseSections').checked);$('inversePrior').onchange=()=>inverse?.setPrior($('inversePrior').checked);$('inverseSkin').onchange=setSkin;$('inverseSegment').onchange=()=>{inverse.select($('inverseSegment').value);inverseMetrics();};$('inverseExport').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(inverse.export(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='surface-inverse-skeleton.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('motorAction').onchange=()=>{time=0;playing=true;$('motorPlay').textContent='暂停演示';update();};$('motorPlay').onclick=()=>{playing=!playing;$('motorPlay').textContent=playing?'暂停演示':'继续演示';};
 $('motorAngle').oninput=()=>{$('motorAction').value='rest';manualAngle=Number($('motorAngle').value);playing=false;$('motorPlay').textContent='继续演示';update();};$('motorJoint').onchange=()=>{$('motorAction').value='rest';update();};$('motorSelection').onchange=()=>{display.select($('motorSelection').value);update();};
 return {show,setActive,update,setAction(action){if(!['rest','elbow','knee','shoulder','walk','run'].includes(action))throw Error('Unknown motor action');$('motorAction').value=action;time=0;playing=true;update();},setJoint(joint,angle){if(!['elbow','knee','shoulder'].includes(joint)||!Number.isFinite(angle)||angle<0||angle>110)throw Error('Invalid joint control');$('motorJoint').value=joint;$('motorAction').value='rest';manualAngle=angle;playing=false;update();},select(id){if(id!=='all'&&!display.model.muscles.some(m=>m.id===id))throw Error('Unknown motor muscle');$('motorSelection').value=id;display.select(id);update();},get active(){return active;},get report(){return display?.report;},get inverseReport(){return inverse?.report();},get inverseParameters(){return inverse?.export();},dispose(){setActive(false);display?.dispose();inverse?.dispose();display=null;inverse=null;bound=null;}};
}
