import * as THREE from 'three';
import {createAnatomyDisplay} from './AnatomyDisplay.mjs';

export function createMotionAnatomyWorkbench({getSubject,actor,getView,enter,exit}){
 const panel=document.createElement('details');panel.id='motionAnatomyPanel';panel.innerHTML=`<summary>骨性框架 / 运动肌肉 · 三维展示</summary>
 <p>两套独立视图，取自当前人物的绑定比例。骨轮廓、肌肉附着与肌腹为程序化估计。</p>
 <div style="display:flex;gap:6px"><button id="frameworkShow">① 骨性框架</button><button id="motorShow">② 运动肌群</button></div>
 <label>演示动作<select id="motorAction"><option value="rest">静止 / 手动关节</option><option value="elbow">屈肘 · 二头肌 / 三头肌</option><option value="knee">屈膝 · 股四头肌 / 腘绳肌</option><option value="shoulder">抬臂 · 三角肌 / 肩带</option><option value="walk">当前人物行走</option><option value="run">当前人物跑步</option></select></label>
 <button id="motorPlay">暂停演示</button><label>相对绑定姿势角度 <output id="motorAngleValue">0°</output><input id="motorAngle" type="range" min="0" max="110" step="1" value="0" style="width:100%"></label>
 <label>手动关节<select id="motorJoint"><option value="elbow">肘关节</option><option value="knee">膝关节</option><option value="shoulder">肩外展</option></select></label>
 <label>肌群 / 拮抗对<select id="motorSelection"><option value="all">全部主要运动肌群</option></select></label>
 <label><input id="motorSkin" type="checkbox">显示原人物表面作比例对照（内部结构被遮挡）</label>
 <p id="motorLegend">米色：估计骨轮廓 / 肌腱；青色：绑定关节；红橙：缩短；蓝色：拉长。</p>
 <p id="motorMetrics"></p><small>演示由关节运动驱动肌肉路径，尚非肌肉力量驱动的动力学。肌肉真实附着点、激活、力量未观测。骨架不随胖瘦滑块缩骨。</small>
 <button id="motorExit">返回人物工作台</button>`;
 document.querySelector('#anatomyPanel').before(panel);
 const $=id=>panel.querySelector('#'+id);let active=false,display=null,bound=null,saved=null,mode='framework',time=0,playing=true,manualAngle=0,lastMetrics=0;
 function bind(){const s=getSubject();if(bound===s)return;display?.dispose();bound=s;display=createAnatomyDisplay(s,actor);$('motorSelection').replaceChildren(new Option('全部主要运动肌群','all'),...display.model.muscles.map(m=>new Option((m.side==='l'?'左':'右')+' · '+m.label,m.id)));}
 function rotate(role,axis,angle){const s=getSubject(),id=s.body.anatomy.roles[role];if(!Number.isInteger(id))return;const b=s.skeleton.bones[id],parentQ=b.parent.getWorldQuaternion(new THREE.Quaternion()),localAxis=new THREE.Vector3(...axis).applyQuaternion(parentQ.invert()).normalize();b.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(localAxis,angle));s.root.updateMatrixWorld(true);}
 function jointPose(joint,degrees){const s=getSubject(),f=s.body.anatomy.frame,a=degrees*Math.PI/180;s.play('rest');for(const side of ['l','r']){if(joint==='elbow')rotate('lowerarm_'+side,f.right,-a);else if(joint==='knee')rotate('calf_'+side,f.right,a);else rotate('upperarm_'+side,f.front,a*(side==='l'?1:-1));}s.finishPose();}
 function pose(dt){const s=getSubject(),action=$('motorAction').value;if(action==='walk'||action==='run'){if(s.phase!==action)s.play(action);if(playing)s.step(dt);else s.finishPose();}else{if(playing&&action!=='rest')time+=dt;const angle=action==='rest'?manualAngle:(1-Math.cos(time*1.6))*.5*(action==='shoulder'?85:105);$('motorAngle').value=Math.round(angle);$('motorAngleValue').value=Math.round(angle)+'°';jointPose(action==='rest'?$('motorJoint').value:action,angle);}}
 function update(dt=0){if(!active)return;pose(dt);display.update(dt);lastMetrics+=dt;if(lastMetrics>.15||dt===0){lastMetrics=0;const selected=$('motorSelection').value,rows=display.report.muscles.filter(m=>selected==='all'?['biceps_l','triceps_l','rectus_femoris_l','hamstrings_l'].includes(m.id):m.id===selected||m.id===display.model.muscles.find(m=>m.id===selected)?.antagonist);$('motorMetrics').textContent=rows.map(m=>`${m.label}：${(m.length*100).toFixed(1)}cm · ${(m.lengthRatio*100).toFixed(0)}% 初始路径长度`).join('\n');$('motorMetrics').style.whiteSpace='pre-line';}}
 function setSkin(){const s=getSubject();s.mesh.visible=$('motorSkin').checked;s.eyes.root.visible=$('motorSkin').checked;}
 function setActive(v){if(v===active)return;if(v){enter();bind();const s=getSubject();saved={mesh:s.mesh.visible,eyes:s.eyes.root.visible,helper:s.helper.visible,view:getView().snapshot()};active=true;panel.open=true;s.helper.visible=false;setSkin();const p=actor.position.clone().add(new THREE.Vector3(0,.96*actor.scale.y,0));getView().frame(p,p.clone().add(new THREE.Vector3(0,.05,2.8*actor.scale.y)));display.setMode(mode);update();}else{active=false;display.root.visible=false;const s=getSubject();s.mesh.visible=saved.mesh;s.eyes.root.visible=saved.eyes;s.helper.visible=saved.helper;const prior=saved;exit();getView().frame(new THREE.Vector3().fromArray(prior.view.target),new THREE.Vector3().fromArray(prior.view.position));saved=null;} }
 function show(v){if(!['framework','muscles'].includes(v))throw Error('Unknown anatomy view');mode=v;setActive(true);display.setMode(v);$('frameworkShow').style.outline=v==='framework'?'2px solid #5fd6e5':'';$('motorShow').style.outline=v==='muscles'?'2px solid #e35732':'';document.querySelector('aside').scrollTop=panel.offsetTop-20;update();}
 $('frameworkShow').onclick=()=>show('framework');$('motorShow').onclick=()=>show('muscles');$('motorExit').onclick=()=>setActive(false);$('motorSkin').onchange=setSkin;
 $('motorAction').onchange=()=>{time=0;playing=true;$('motorPlay').textContent='暂停演示';update();};$('motorPlay').onclick=()=>{playing=!playing;$('motorPlay').textContent=playing?'暂停演示':'继续演示';};
 $('motorAngle').oninput=()=>{$('motorAction').value='rest';manualAngle=Number($('motorAngle').value);playing=false;$('motorPlay').textContent='继续演示';update();};$('motorJoint').onchange=()=>{$('motorAction').value='rest';update();};$('motorSelection').onchange=()=>{display.select($('motorSelection').value);update();};
 return {show,setActive,update,setAction(action){if(!['rest','elbow','knee','shoulder','walk','run'].includes(action))throw Error('Unknown motor action');$('motorAction').value=action;time=0;playing=true;update();},setJoint(joint,angle){if(!['elbow','knee','shoulder'].includes(joint)||!Number.isFinite(angle)||angle<0||angle>110)throw Error('Invalid joint control');$('motorJoint').value=joint;$('motorAction').value='rest';manualAngle=angle;playing=false;update();},select(id){if(id!=='all'&&!display.model.muscles.some(m=>m.id===id))throw Error('Unknown motor muscle');$('motorSelection').value=id;display.select(id);update();},get active(){return active;},get report(){return display?.report;},dispose(){setActive(false);display?.dispose();display=null;bound=null;}};
}
