import {SCAR_REGIONS,SCAR_CONTROLS} from './ScarState.mjs';
export function createScarWorkbench({getState,apply,onPreview}){
 const $=id=>document.getElementById(id),panel=document.createElement('details');panel.id='scarPanel';panel.open=true;
 panel.innerHTML=`<summary>肩臂伤疤与愈合</summary><div class="row"><button id="scarViewRight">近看右肩臂</button><button id="scarViewLeft">近看左肩臂</button></div><button id="scarViewGame">返回游戏镜头</button><label>控制区域<select id="scarRegion"><option value="all">全部原有伤痕</option>${SCAR_REGIONS.filter(r=>r.sourceScar).map(r=>`<option value="${r.id}">${r.label}</option>`).join('')}</select></label><label>阶段示例<select id="scarPreset"><option value="custom">自定义</option><option value="original">恢复原始伤痕</option><option value="clean">无伤健康皮肤</option><option value="fresh">原有伤痕 · 明显</option><option value="scab">结痂</option><option value="old">淡疤</option><option value="healed">已愈合</option></select></label><label>伤痕颜色<input id="scarColor" type="color" aria-label="伤痕颜色"></label>${SCAR_CONTROLS.map(c=>`<label>${c.label}<output id="scar-${c.key}-value"></output><input id="scar-${c.key}" aria-label="${c.label}" type="range" min="${c.min}" max="${c.max}" step="${c.step}" style="width:100%"></label>`).join('')}<label><input id="scarAuto" type="checkbox"> 随游戏时间自动愈合</label><label>完全愈合用时（游戏天）<input id="scarDays" type="number" min=".01" max="4000" step=".1" style="width:100%"></label><label>愈合后淡疤保留量<output id="scarResidualValue"></output><input id="scarResidual" type="range" min="0" max="1" step=".01" style="width:100%"></label><div class="row"><button id="scarAdvance">推进愈合一天</button></div><div class="row"><button id="scarClean">清除所选伤痕</button><button id="scarOriginal">恢复所选原貌</button></div><p id="scarProgress"></p><small>全部区域数值不同的时候，滑条显示右肩数值；调整将统一所选区域。自动愈合沿用上方预览一天用时，无需开启日晒。阶段和时间为游戏美术参数。肤色导出包含伤疤。</small><p id="scarMessage" role="status"></p>`;
 $('skinPanel').after(panel);const target=()=>$('scarRegion').value;
 function refresh(){const s=getState(),p=s.regions[target()==='all'?'rightShoulder':target()];for(const c of SCAR_CONTROLS){$('scar-'+c.key).value=p[c.key];$('scar-'+c.key+'-value').value=p[c.key].toFixed(2);}$('scarColor').value=p.color;$('scarAuto').checked=s.automaticHealing;$('scarDays').value=s.healingHours/24;$('scarResidual').value=s.residual;$('scarResidualValue').value=s.residual.toFixed(2);$('scarProgress').textContent=SCAR_REGIONS.filter(r=>r.sourceScar&&(target()==='all'||r.id===target())).map(r=>`${r.label} ${Math.round(s.regions[r.id].progress*100)}%`).join(' · ');}
 function change(fn){try{fn();apply();refresh();$('scarMessage').textContent='';}catch(e){$('scarMessage').textContent=e.message;refresh();}}
 for(const c of SCAR_CONTROLS)$('scar-'+c.key).oninput=()=>change(()=>{getState().set(target(),{[c.key]:Number($('scar-'+c.key).value)});$('scarPreset').value='custom';});
 $('scarRegion').onchange=()=>{$('scarPreset').value='custom';refresh();};
 $('scarColor').oninput=()=>change(()=>getState().set(target(),{color:$('scarColor').value,tint:1}));
 $('scarAuto').onchange=()=>change(()=>getState().configure({automaticHealing:$('scarAuto').checked}));
 $('scarDays').onchange=()=>change(()=>getState().configure({healingHours:Number($('scarDays').value)*24}));
 $('scarResidual').oninput=()=>change(()=>getState().configure({residual:Number($('scarResidual').value)}));
 $('scarPreset').onchange=()=>change(()=>{if($('scarPreset').value!=='custom')getState().preset($('scarPreset').value,target());});
 $('scarAdvance').onclick=()=>change(()=>getState().advance(24,true));
 for(const [button,preset]of [['scarClean','clean'],['scarOriginal','original']])$(button).onclick=()=>change(()=>{getState().preset(preset,target());$('scarPreset').value=preset;});
 for(const [id,view]of [['scarViewRight','right'],['scarViewLeft','left'],['scarViewGame','game']])$(id).onclick=()=>onPreview?.(view);
 const api={refresh,export:()=>getState().export(),set(id,patch){getState().set(id,patch);apply();return this.export();},configure(patch){getState().configure(patch);apply();return this.export();},preset(id,target='all'){getState().preset(id,target);apply();return this.export();},advance(hours){getState().advance(hours,true);apply();return this.export();},restore(recipe){getState().restore(recipe);apply();return this.export();}};
 window.HumanScars=api;refresh();return api;
}
