import * as THREE from 'three';
// Continuous geometric authoring, not a paper-metric/contact solve. Actual
// triangle/plane intersections own the body curves; no fitted old cloth mesh
// or outward-face-projection history is used as a new material reference.
// https://threejs.org/docs/pages/Plane.html
// https://salvi.chaosnet.org/texts/transfinite-surfaces.pdf
const PAD_M=.0025,ANGULAR_SAMPLES=360;
const clamp=x=>Math.max(0,Math.min(1,x)),mix=(a,b,t)=>a.map((x,k)=>x+(b[k]-x)*t),dist=(a,b)=>Math.hypot(...a.map((x,k)=>x-b[k])),cross2=(a,b)=>a[0]*b[1]-a[1]*b[0];
const state=c=>JSON.stringify({previous:c.previous,velocity:c.velocity,initial:c.initial,history:c.history,time:c.time,steps:c.steps,accumulator:c.accumulator,enabled:c.enabled,cpu:c.cpu,options:c.options,lambda:[...c.edges,...c.bends,...c.elastic].map(e=>e.lambda)});
function localMesh(world,inverse){const out=new Float64Array(world.length),p=new THREE.Vector3();for(let i=0;i<world.length;i+=3)p.fromArray(world,i).applyMatrix4(inverse).toArray(out,i);return out;}
function planeSegments(positions,triangles,axis,level,accept=()=>true){
 const rows=[];for(let ti=0;ti<triangles.length;ti++){const t=triangles[ti],ids=t.indices??t;if(!accept(t))continue;const p=ids.map(i=>Array.from(positions.subarray(i*3,i*3+3)));if(level<Math.min(...p.map(v=>v[axis]))||level>Math.max(...p.map(v=>v[axis])))continue;const hits=[];
  for(let e=0;e<3;e++){const a=p[e],b=p[(e+1)%3];if((a[axis]<=level&&b[axis]>level)||(b[axis]<=level&&a[axis]>level)){const q=mix(a,b,(level-a[axis])/(b[axis]-a[axis]));if(!hits.some(v=>dist(q,v)<1e-10))hits.push(q);}}
  if(hits.length===2&&dist(hits[0],hits[1])>1e-10)rows.push({a:hits[0],b:hits[1],triangleId:t.id??ti,indices:Array.from(ids)});
 }return rows;
}
function contour(rows,y,scope){
 if(rows.length<3)throw Error('HOLD_SURFACE_SECTION: missing actual '+scope+' plane '+y);
 const points=rows.flatMap(r=>[r.a,r.b]),cx=(Math.min(...points.map(p=>p[0]))+Math.max(...points.map(p=>p[0])))/2,cz=(Math.min(...points.map(p=>p[2]))+Math.max(...points.map(p=>p[2])))/2,loop=[],witness=[];
 for(let i=0;i<ANGULAR_SAMPLES;i++){const theta=2*Math.PI*i/ANGULAR_SAMPLES,d=[Math.sin(theta),Math.cos(theta)];let best=null;
  for(const r of rows){const a=[r.a[0]-cx,r.a[2]-cz],e=[r.b[0]-r.a[0],r.b[2]-r.a[2]],den=cross2(d,e);if(Math.abs(den)<1e-14)continue;const radius=cross2(a,e)/den,u=cross2(a,d)/den;if(radius>=0&&u>=-1e-10&&u<=1+1e-10&&(!best||radius>best.radius))best={radius,row:r,edgeT:u};}
  if(!best)throw Error('HOLD_SURFACE_SECTION: actual '+scope+' ray '+i+' missing at '+y+'; no invented closed contour');
  loop.push([cx+(best.radius+PAD_M)*d[0],y,cz+(best.radius+PAD_M)*d[1]]);witness.push({triangleId:best.row.triangleId,sourceIndices:best.row.indices,edgeParameter:best.edgeT});
 }
 // Each sector uses its actual measured curve length, including orientation.
 const arc=(start,end,t,extra=0,side=null,midX=0)=>{const step=end>=start?1:-1,pts=[];for(let i=start;i!==end+step;i+=step){const p=loop[(i+ANGULAR_SAMPLES)%ANGULAR_SAMPLES].slice(),radius=Math.hypot(p[0]-cx,p[2]-cz),dx=extra*(p[0]-cx)/radius,dz=extra*(p[2]-cz)/radius;
   // Smooth inner-leg saturation retains a positive gap instead of clipping
   // a radial offset into a flat plane or letting two trouser legs overlap.
   if(side==='left'&&dx>0){const available=midX-PAD_M-p[0];if(!(available>0))throw Error('Actual left leg already crosses its midpoint domain');p[0]+=available*dx/(available+dx);}else if(side==='right'&&dx<0){const available=p[0]-midX-PAD_M;if(!(available>0))throw Error('Actual right leg already crosses its midpoint domain');p[0]-=available*(-dx)/(available-dx);}else p[0]+=dx;p[2]+=dz;pts.push(p);}
  const cumulative=[0];for(let i=1;i<pts.length;i++)cumulative.push(cumulative.at(-1)+dist(pts[i-1],pts[i]));const s=clamp(t)*cumulative.at(-1);let i=1;while(i<cumulative.length-1&&cumulative[i]<s)i++;return mix(pts[i-1],pts[i],(s-cumulative[i-1])/(cumulative[i]-cumulative[i-1]));};
 return {y,cx,cz,loop,witness,arc,scope,segmentCount:rows.length,allRaysHit:true,circumferenceM:loop.reduce((s,p,i)=>s+dist(p,loop[(i+1)%loop.length]),0)};
}
function quadraticThroughMiddle(a,m,b,t){const control=m.map((x,k)=>2*x-(a[k]+b[k])/2);return a.map((x,k)=>(1-t)**2*x+2*t*(1-t)*control[k]+t*t*b[k]);}
function metricAudit(cloth){let maximum=0,worst=null;const byPiece={};for(const t of cloth.triangles){const p=t.q.map(i=>cloth.positions[i]),uv=t.original.map(i=>Array.from(cloth.draft.sourceUV.subarray(i*2,i*2+2))),a=uv[1].map((x,k)=>x-uv[0][k]),b=uv[2].map((x,k)=>x-uv[0][k]),d=a[0]*b[1]-a[1]*b[0];if(Math.abs(d)<1e-14)throw Error('Nondegenerate source paper required');const u=p[1].map((x,k)=>((x-p[0][k])*b[1]-(p[2][k]-p[0][k])*a[1])/d),v=p[1].map((x,k)=>((p[2][k]-p[0][k])*a[0]-(x-p[0][k])*b[0])/d),dot=(a,b)=>a.reduce((s,x,k)=>s+x*b[k],0),A=dot(u,u),B=dot(u,v),D=dot(v,v),z=Math.hypot(A-D,2*B),s0=Math.sqrt(Math.max(0,(A+D-z)/2)),s1=Math.sqrt(Math.max(0,(A+D+z)/2)),e=Math.max(Math.abs(s0-1),Math.abs(s1-1)),id=cloth.draft.ranges.find(r=>t.original[0]>=r.offset&&t.original[0]<r.offset+r.count).pieceId;byPiece[id]=Math.max(byPiece[id]??0,e);if(e>maximum){maximum=e;worst={pieceId:id,sourceIndices:t.original,minimumStretch:s0,maximumStretch:s1};}}return {maximumPrincipalStrain:maximum,byPiece,worst,originalFivePercentGatePassed:maximum<=.05};}
export function fitShortsSurface(cloth,barePelvis){
 if(barePelvis?.report?.closedSolidTopologyCertified!==true||!barePelvis.queryAPI?.positions||!barePelvis.queryAPI?.indices||!cloth.actor||!cloth.body?.triangles||!cloth.body?.positions)throw Error('Actual closed bare and current native WORLD triangle sources required');
 if(cloth.positions.length!==451||cloth.quotient.length!==553||cloth.triangles.length!==848||cloth.activeSeams.length!==19||!cloth.invMass.every(x=>x>0&&Number.isFinite(x)))throw Error('Original nine-piece complete all-free source garment required');
 const paperIdentity=cloth.materialIdentity(),historyIdentity=state(cloth),original=cloth.positions.map(p=>p.slice()),recipe=cloth.draft.receipt,d=recipe.design,byId=new Map(cloth.draft.pieces.map(p=>[p.id,p])),ranges=new Map(cloth.draft.ranges.map(r=>[r.pieceId,r]));
 cloth.actor.updateWorldMatrix(true,false);const frame=new THREE.Matrix4().compose(cloth.actor.getWorldPosition(new THREE.Vector3()),cloth.actor.getWorldQuaternion(new THREE.Quaternion()),new THREE.Vector3(1,1,1)),inverse=frame.clone().invert(),toWorld=p=>new THREE.Vector3(...p).applyMatrix4(frame).toArray(),bareLocal=localMesh(barePelvis.queryAPI.positions,inverse),bareTriangles=Array.from({length:barePelvis.queryAPI.indices.length/3},(_,i)=>Array.from(barePelvis.queryAPI.indices.subarray(i*3,i*3+3))),nativeLocal=localMesh(cloth.body.positions,inverse),nativeTriangles=cloth.body.triangles;
 const sections=new Map(),sectionEvidence=[],legNativeParts={left:[18,12],right:[1,26]},midX=recipe.measurements.waistCenter[0],midZ=recipe.measurements.waistCenter[2],bareMinimumY=Math.min(...Array.from({length:bareLocal.length/3},(_,i)=>bareLocal[i*3+1]));
 const section=(y,side=null)=>{const key=(side??'whole')+':'+y.toPrecision(12);if(sections.has(key))return sections.get(key);let rows=planeSegments(bareLocal,bareTriangles,1,y),scope='actual closed authored bare';if(side)rows=rows.filter(r=>(r.a[0]+r.b[0])/2*(side==='left'?-1:1)>midX*(side==='left'?-1:1));if(y<=bareMinimumY+.010&&side){rows=planeSegments(nativeLocal,nativeTriangles,1,y,t=>legNativeParts[side].includes(t.part));scope='actual native visible '+side+' leg';}
  const s=contour(rows,y,scope);sections.set(key,s);sectionEvidence.push({key,y,side,authority:scope,segmentCount:s.segmentCount,all360RaysHit:true,center:[s.cx,s.cz]});return s;};
 const sector=(y,side,front,t,extra=0)=>{const s=section(y);return front?s.arc(0,side==='left'?-90:90,t,extra):s.arc(180,side==='left'?270:90,t,extra);};
 const legArc=(y,side,front,t,extra=0)=>{const s=section(y,side);return side==='left'?s.arc(90,front?-90:270,t,extra,side,midX):s.arc(270,front?450:90,t,extra,side,midX);},interfaceTopY=bareMinimumY+.015,interfaceBottomY=bareMinimumY-.015;
 // A continuous interface joins actual authored and native skin curves. It
 // avoids switching bodies at one row or claiming an open native cap is a
 // closed body. Both end curves retain their own actual triangle witnesses.
 const leg=(y,side,front,t,extra=0)=>y>=interfaceTopY||y<=interfaceBottomY?legArc(y,side,front,t,extra):mix(legArc(interfaceTopY,side,front,t,extra),legArc(interfaceBottomY,side,front,t,extra),(interfaceTopY-y)/(interfaceTopY-interfaceBottomY));
 // Locate the actual closed body's crotch from its sagittal cut, not from
 // the old clothing envelope. The minimum belongs to the connected bridge.
 const sagittal=planeSegments(bareLocal,bareTriangles,0,midX),lowest=sagittal.flatMap(r=>[{point:r.a,witness:r},{point:r.b,witness:r}]).sort((a,b)=>a.point[1]-b.point[1])[0];if(!lowest)throw Error('Actual closed-bare sagittal crotch witness required');
 const crotch=lowest.point.slice(),hipY=recipe.measurements.metadata.hipY,hemY=recipe.hem.y,upperY=recipe.upperY,lowerY=recipe.lowerY,middleY=recipe.middleY,frontBackY=crotch[1]+(hipY-crotch[1])/3,tipY=crotch[1]-(crotch[1]-hemY)/5;
 if(!(lowerY>hipY&&hipY>frontBackY&&frontBackY>tipY&&tipY>hemY))throw Error('Measured surface waist/hip/U/cuff domains not ordered');
 const hipExtra=d.hipEase/(2*Math.PI),thighExtra=d.thighEase/(2*Math.PI),sourceHemLength=side=>cloth.draft.pieces.filter(p=>p.kind==='leg-panel'&&p.side===side).reduce((s,p)=>s+p.boundaries.hem.slice(1).reduce((a,i,j)=>a+dist(p.materialCoordinates[i],p.materialCoordinates[p.boundaries.hem[j]]),0),0),hemExtras=Object.fromEntries(['left','right'].map(side=>[side,Math.max(0,(sourceHemLength(side)-section(hemY,side).circumferenceM)/(2*Math.PI))]));
 const gCorners=[sector(frontBackY,'right',true,0,hipExtra),leg(tipY,'right',true,0,thighExtra),sector(frontBackY,'right',false,0,hipExtra),leg(tipY,'left',true,0,thighExtra)],gMids=gCorners.map((a,i)=>{const p=mix(a,gCorners[(i+1)%4],.5),h=barePelvis.queryAPI.closestPoint(new THREE.Vector3(...toWorld(p)));if(!h||h.signAmbiguous)throw Error('HOLD: actual U-boundary skin witness ambiguous');return h.point.clone().addScaledVector(h.normal,PAD_M+(hipExtra+thighExtra)/2).applyMatrix4(inverse).toArray();}),gCenter=[crotch[0],crotch[1]-PAD_M-d.crotchDrop,crotch[2]],edge=(i,t)=>quadraticThroughMiddle(gCorners[i],gMids[i],gCorners[(i+1)%4],clamp(t));
 const coons=(s,t)=>{const a=edge(0,s),b=edge(2,1-s),c=edge(3,1-t),e=edge(1,t),bilinear=gCorners[0].map((x,k)=>(1-s)*(1-t)*x+s*(1-t)*gCorners[1][k]+s*t*gCorners[2][k]+(1-s)*t*gCorners[3][k]);return a.map((x,k)=>(1-t)*x+t*b[k]+(1-s)*c[k]+s*e[k]-bilinear[k]);},coonsCenter=coons(.5,.5),gUV=byId.get('G').materialCoordinates;
 const gusset=uv=>{const x=uv[0]/gUV[2][0],v=uv[1]/(uv[1]<0?-gUV[0][1]:gUV[4][1]),s=clamp((x+v+1)/2),t=clamp((-x+v+1)/2),p=coons(s,t),bubble=16*s*(1-s)*t*(1-t);return p.map((x,k)=>x+bubble*(gCenter[k]-coonsCenter[k]));};
 const rowY=(piece,r,a,b,ya,yb)=>{const n=piece.grid.columns+1,at=x=>{const i=Math.floor(x),f=x-i;return piece.materialCoordinates[Math.min(i,piece.grid.rows)*n+piece.grid.columns][1]*(1-f)+piece.materialCoordinates[Math.min(i+1,piece.grid.rows)*n+piece.grid.columns][1]*f;};return ya+(yb-ya)*(at(r)-at(a))/(at(b)-at(a));};
 const main=(piece,row,column)=>{const r=Math.max(0,Math.min(13,row)),t=clamp(column/7),front=piece.bodySide==='front',side=piece.side;if(r<=7){const y=r<=d.hipRow?rowY(piece,r,0,d.hipRow,lowerY,hipY):rowY(piece,r,d.hipRow,7,hipY,frontBackY),u=clamp(r/d.hipRow),extra=hipExtra*u*u*(3-2*u);return sector(y,side,front,t,extra);}if(r>=9){const u=(r-9)/4,extra=thighExtra+(hemExtras[side]-thighExtra)*u*u*(3-2*u);return leg(rowY(piece,r,9,13,tipY,hemY),side,front,t,extra);}
  const v=(r-7)/2,a=sector(frontBackY,side,front,t,hipExtra),b=leg(tipY,side,front,t,thighExtra),p=mix(a,b,v),inner=front?(side==='right'?edge(0,v):edge(3,1-v)):(side==='right'?edge(1,1-v):edge(2,v)),oldInner=mix(front?gCorners[0]:gCorners[2],side==='right'?gCorners[1]:gCorners[3],v);return p.map((x,k)=>x+(1-t)*(inner[k]-oldInner[k]));};
 const casingBulgeM=cloth.draft.casing?.channelBulgeM??.0015;
 const evaluateSurface=(pieceId,{row,column}={})=>{const piece=byId.get(pieceId);if(!piece||![row,column].every(Number.isFinite))throw Error('Valid original structured piece coordinates required');if(piece.kind==='leg-panel')return toWorld(main(piece,row,column));if(piece.kind==='waistband'){const parent=byId.get(piece.parentPanel),t=['FL','BR'].includes(parent.id)?1-column/7:column/7,y=row<=1?lowerY+(middleY-lowerY)*row:middleY+(upperY-middleY)*(row-1),bulge=row<=0||row>=2?0:casingBulgeM*Math.sin(Math.PI*row/2);return toWorld(sector(y,parent.side,parent.bodySide==='front',clamp(t),bulge));}throw Error('G evaluates by its actual source UV, not a fictitious structured grid');};
 const evaluator=(pieceId,{sourceIndices,weights}={})=>{const piece=byId.get(pieceId);if(!piece||!(sourceIndices?.length>=1&&sourceIndices.length<=3)||weights?.length!==sourceIndices.length||!weights.every(x=>Number.isFinite(x)&&x>=-1e-10)||Math.abs(weights.reduce((a,b)=>a+b,0)-1)>1e-9)throw Error('Actual original local triangle barycentric coordinates required');if(sourceIndices.some(i=>!Number.isInteger(i)||i<0||i>=piece.materialCoordinates.length))throw Error('Source-local index outside original paper');if(piece.kind==='gusset'){const uv=[0,1].map(k=>sourceIndices.reduce((s,id,j)=>s+piece.materialCoordinates[id][k]*weights[j],0));return toWorld(gusset(uv));}const n=piece.grid.columns+1,row=sourceIndices.reduce((s,id,j)=>s+Math.floor(id/n)*weights[j],0),column=sourceIndices.reduce((s,id,j)=>s+(id%n)*weights[j],0);return evaluateSurface(pieceId,{row,column});};
 const authored=Array(553),candidate=Array.from({length:451},()=>[]);for(const piece of cloth.draft.pieces){const range=ranges.get(piece.id);for(let i=0;i<range.count;i++){const p=piece.kind==='gusset'?toWorld(gusset(piece.materialCoordinates[i])):evaluateSurface(piece.id,{row:Math.floor(i/(piece.grid.columns+1)),column:i%(piece.grid.columns+1)});if(!p.every(Number.isFinite))throw Error('Nonfinite continuous surface placement');authored[range.offset+i]=p;candidate[cloth.quotient[range.offset+i]].push(p);}}
 let maximumSourceSharedEndpointDifferenceM=0;for(const points of candidate)for(const p of points)maximumSourceSharedEndpointDifferenceM=Math.max(maximumSourceSharedEndpointDifferenceM,dist(p,points[0]));if(maximumSourceSharedEndpointDifferenceM>1e-8)throw Error('HOLD: continuous source boundaries disagree by '+maximumSourceSharedEndpointDifferenceM+'m');
 const refinedSeamChecks=[];let maximumQuarterSegmentSeamGapM=0,quarterSegmentEvaluations=0;
 for(const seam of cloth.draft.seams){const aRange=ranges.get(seam.a.pieceId),bRange=ranges.get(seam.b.pieceId);let maximum=0;for(let i=1;i<seam.pairs.length;i++)for(const t of [.25,.5,.75]){const pair0=seam.pairs[i-1],pair1=seam.pairs[i],weights=[1-t,t],a=evaluator(seam.a.pieceId,{sourceIndices:[pair0.a-aRange.offset,pair1.a-aRange.offset],weights}),b=evaluator(seam.b.pieceId,{sourceIndices:[pair0.b-bRange.offset,pair1.b-bRange.offset],weights}),gap=dist(a,b);maximum=Math.max(maximum,gap);maximumQuarterSegmentSeamGapM=Math.max(maximumQuarterSegmentSeamGapM,gap);quarterSegmentEvaluations++;}refinedSeamChecks.push({sourceSeamId:seam.id,sourceSegments:seam.pairs.length-1,maximumQuarterSegmentSeamGapM:maximum});}
 if(maximumQuarterSegmentSeamGapM>1e-7)throw Error('HOLD: continuous source seam disagrees under genuine 2D refinement by '+maximumQuarterSegmentSeamGapM+'m');
 for(let i=0;i<candidate.length;i++)for(let k=0;k<3;k++)cloth.positions[i][k]=candidate[i][0][k];cloth.surfaceEvaluator=evaluator;cloth.evaluateSurface=evaluateSurface;cloth.syncRender();
 const waistDistances={upper:[],middle:[],lower:[]};for(const piece of cloth.draft.pieces.filter(p=>p.kind==='waistband'))for(let r=0;r<=2;r++)for(let c=0;c<=7;c++){const id=ranges.get(piece.id).offset+r*8+c,h=barePelvis.queryAPI.closestPoint(new THREE.Vector3(...cloth.positions[cloth.quotient[id]]));waistDistances[['lower','middle','upper'][r]].push(h.signedDistance);}
 if(cloth.materialIdentity()!==paperIdentity||state(cloth)!==historyIdentity)throw Error('Surface authoring changed source paper/rest/mass or native history');
 const material=metricAudit(cloth),receipt={sourceSeamRefinement:{maximumQuarterSegmentSeamGapM,quarterSegmentEvaluations,sourceSeams:refinedSeamChecks,originalSegmentParameters:[.25,.5,.75],gapGuardM:1e-7},version:'r008-continuous-actual-surface-authoring@1',scope:'continuous parametric geometry authoring from actual closed bare and native visible-leg triangle sections; no cloth solver or collision-based shape acceptance',status:'GEOMETRIC_SHAPE_PREVIEW_REQUIRES_VISUAL_REVIEW',padM:PAD_M,paperCounts:{sourceVertices:553,sourceTriangles:848,actualSourceSeams:19,freeDofs:451},actorFrame:{worldTranslation:cloth.actor.getWorldPosition(new THREE.Vector3()).toArray(),worldQuaternion:cloth.actor.getWorldQuaternion(new THREE.Quaternion()).toArray(),unitScaleActualSubjectScaleAlreadyMeasured:true},waist:{authority:'actual closed bare WORLD triangles, horizontal actor-local sections; original source-row arclength parameters shared by casing and main',upperY,middleY,lowerY,casingBulgeM,casingProfile:'sine over the 38mm finished casing width; upper/lower zero, middle 1.5mm; elastic force not simulated',distances:Object.fromEntries(Object.entries(waistDistances).map(([key,v])=>[key,{minimumM:Math.min(...v),maximumM:Math.max(...v),sourceSamples:v.length}]))},designEase:{hipRadialM:hipExtra,thighRadialM:thighExtra,hemExtraRadialM:hemExtras,sourceHemTapeM:Object.fromEntries(['left','right'].map(side=>[side,sourceHemLength(side)])),waistToHip:'smoothstep zero casing slack to original design hipEase/(2π)',innerLegRule:'smooth rational saturation before the midpoint ±2.5mm; no intersecting radial sleeves',gussetDropM:d.crotchDrop,physicalMetricAcceptanceClaimed:false},gusset:{construction:'Coons diamond with four actual shared U-boundary curves, centre correction vanishes on all edges',actualBareSagittalCrotch:crotch,witness:{triangleId:lowest.witness.triangleId,indices:lowest.witness.indices},frontBackY,tipY,center:gCenter,corners:gCorners,midpoints:gMids},nativeLegInterface:{topY:interfaceTopY,bottomY:interfaceBottomY,method:'continuous interpolation of actual closed-bare and visible-native boundary curves through the native open-cap overlap; no native closed-membership claim'},maximumSourceSharedEndpointDifferenceM,maximumPositionChangeM:Math.max(...cloth.positions.map((p,i)=>dist(p,original[i]))),sourceUVRestMassUnchanged:true,nativeTimePreviousVelocityHistoryUnchanged:true,sourceEvaluator:'cloth.surfaceEvaluator(pieceId,{sourceIndices:[one to three ORIGINAL local indices],weights:[matching barycentric weights]}) returns WORLD xyz; source2D subdivision/rest/mass belongs to caller',sectionEvidence,materialAudit:material,shapeAccepted:false,bodyIntersectionChecked:false,selfContactChecked:false,physicalWearingPassed:false,motionValidated:false,productionReady:false};return receipt;
}
