import * as THREE from 'three';
import {manufacturingPaperGramRow} from './ShortsManufacturingCoupled.mjs';

// Bounded static AUTHORING, not a replacement for XPBD/native cloth dynamics.
// Source2D and actual physical masses supply a fixed residual scale. Recomputing
// that scale from a strained current chart would change the merit each round.
const dot=(a,b)=>{let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s;};
const distance=(a,b)=>Math.hypot(...a.map((v,k)=>v-b[k]));
function entries(cloth,ids,gradients,scale=1){const combined=new Map();ids.forEach((id,j)=>gradients[j].forEach((g,k)=>{const key=id*3+k;combined.set(key,(combined.get(key)||0)+g*Math.sqrt(cloth.invMass[id])/scale);}));return [...combined].filter(([,g])=>g!==0);}
function norm(entries){return Math.hypot(...entries.map(([,g])=>g));}
function sourceScale(cloth,t,mode){const m=t.inv,cu=[-m[0]-m[2],m[0],m[2]],cv=[-m[1]-m[3],m[1],m[3]],g=cu.map((a,i)=>mode===0?[2*a,0,0]:mode===1?[0,2*cv[i],0]:[cv[i],a,0]);return norm(entries(cloth,t.q,g));}
function samplePosition(cloth,sample){const p=[0,0,0];sample.ids.forEach((id,j)=>p.forEach((_,k)=>p[k]+=cloth.positions[id][k]*sample.weights[j]));return p;}
function contact(cloth,sample){const p=samplePosition(cloth,sample),hit=cloth.body.closestPoint(p);if(!hit||hit.signAmbiguous)throw Object.assign(Error('HOLD: ambiguous actual closest-feature contact'),{witness:{kind:sample.kind,ids:sample.ids,weights:sample.weights,point:p,hit:hit?{triangleId:hit.triangleId,feature:hit.feature?.type,distanceM:hit.distance,projectionM:hit.pseudonormalProjectionM}:null}});const n=hit.normal.toArray();if(!n.every(Number.isFinite)||!Number.isFinite(hit.signedDistance))throw Error('HOLD: nonfinite current-body contact');return{value:Math.max(0,cloth.options.bodyClearanceM-hit.signedDistance),normal:n,signedDistanceM:hit.signedDistance,witness:{kind:sample.kind,ids:sample.ids,weights:sample.weights,point:p,surfacePoint:hit.point.toArray(),normal:n,triangleId:hit.triangleId,part:hit.part,feature:hit.feature.type,featureIndices:hit.feature.indices,incidentTriangleIds:hit.feature.incidentTriangleIds,pseudonormal:hit.feature.normal.toArray(),pseudonormalProjectionM:hit.pseudonormalProjectionM,nearestFaceProjectionM:hit.nearestFaceProjectionM,unsignedDistanceM:hit.distance,signedDistanceM:hit.signedDistance,sourceIndices:hit.indices,barycentric:hit.weights,closedSolidCertified:false}};}
function makeDefinitions(cloth){
 const rows=[],d=cloth.draft;
 for(const t of cloth.triangles)for(const mode of [0,1,2]){const scale=sourceScale(cloth,t,mode);if(!(scale>0))throw Error('HOLD: invalid original source Gram scale');rows.push({kind:'source-gram',scale,evaluate:()=>manufacturingPaperGramRow(cloth,t,mode).value,linearize:()=>{const r=manufacturingPaperGramRow(cloth,t,mode);return{value:r.value,entries:entries(cloth,t.q,r.gradients,scale)};}});}
 for(const e of cloth.edges){const scale=Math.sqrt(cloth.invMass[e.a]+cloth.invMass[e.b])/e.rest;rows.push({kind:'source-edge',scale,evaluate:()=>distance(cloth.positions[e.a],cloth.positions[e.b])/e.rest-1,linearize:()=>{const a=cloth.positions[e.a],b=cloth.positions[e.b],l=distance(a,b);if(l<1e-12)throw Error('HOLD: collapsed source cloth edge');const g=a.map((v,k)=>(v-b[k])/l/e.rest);return{value:l/e.rest-1,entries:entries(cloth,[e.a,e.b],[g,g.map(v=>-v)],scale)};}});}
 const samples=[...cloth.positions.map((_,i)=>({kind:'body-vertex',ids:[i],weights:[1]})),...cloth.triangles.map(t=>({kind:'body-centroid',ids:t.q,weights:[1/3,1/3,1/3]}))];
 for(const s of samples){const scale=norm(entries(cloth,s.ids,s.weights.map(w=>[w,0,0])));rows.push({kind:s.kind,sample:s,scale,evaluate:()=>contact(cloth,s).value,linearize:()=>{const h=contact(cloth,s),anchor=h.witness.point.slice(),normal=h.normal.slice(),signed=h.signedDistanceM;
  // This plane agrees with the ACTUAL closest-feature signed distance and its
  // radial gradient at this iteration's anchor. Only its local model is frozen.
  // Refinding a different/open overlapping feature during FD would differentiate
  // another function than the Jacobian assembled above. True queries remain the
  // independent acceptance authority below; this is no global solid oracle.
  return{value:h.value,entries:h.value>0?entries(cloth,s.ids,s.weights.map(w=>normal.map(v=>-w*v)),scale):[],contactAnchor:h.witness,surrogateEvaluate:()=>Math.max(0,cloth.options.bodyClearanceM-signed-dot(samplePosition(cloth,s).map((v,k)=>v-anchor[k]),normal))};}});}
 const origin=new THREE.Vector3(),rotation=new THREE.Quaternion();cloth.actor.getWorldPosition(origin);cloth.actor.getWorldQuaternion(rotation);const axis=new THREE.Vector3(0,1,0).applyQuaternion(rotation).toArray(),base=dot(origin.toArray(),axis),byId=new Map(d.ranges.map(r=>[r.pieceId,r]));
 const lower=[...new Set(['FL','FR','BL','BR'].flatMap(id=>Array.from({length:8},(_,i)=>cloth.quotient[byId.get(id).offset+i])))],hem=[...new Set(['FL','FR','BL','BR'].flatMap(id=>Array.from({length:8},(_,i)=>cloth.quotient[byId.get(id).offset+104+i])))],upper=[...new Set(Array.from(d.waistIndices,i=>cloth.quotient[i]))],guideGroups=[{kind:'waist-upper',ids:upper,y:d.receipt.upperY},{kind:'waist-lower',ids:lower,y:d.receipt.lowerY},{kind:'hem',ids:hem,y:d.receipt.hem.y}];
 for(const g of guideGroups){if(!Number.isFinite(g.y))throw Error('HOLD: current measured waist/hem authoring height missing');for(const id of g.ids){const scale=Math.sqrt(cloth.invMass[id]);rows.push({kind:'guide-'+g.kind,scale,evaluate:()=>dot(cloth.positions[id],axis)-base-g.y,linearize:()=>({value:dot(cloth.positions[id],axis)-base-g.y,entries:entries(cloth,[id],[axis],scale)})});}}
 return{rows,samples,guideGroups,axis,base};
}
function components(rows){const result={};for(const r of rows){const value=r.evaluate()/r.scale;result[r.kind]=(result[r.kind]??0)+value*value;}return result;}
const energy=c=>Object.values(c).reduce((s,v)=>s+v,0);
function proposal(cloth,defs){
 const dimension=cloth.positions.length*3,rows=defs.rows.map(r=>{const linear=r.linearize();return{...r,...linear,evaluate:linear.surrogateEvaluate??r.evaluate};}),rhs=new Float64Array(dimension),diagonal=new Float64Array(dimension);diagonal.fill(.01);
 for(const r of rows)for(const[k,g]of r.entries){rhs[k]-=g*r.value/r.scale;diagonal[k]+=g*g;}
 const multiply=v=>{const result=Float64Array.from(v,x=>x*.01);for(const r of rows){let projection=0;for(const[k,g]of r.entries)projection+=g*v[k];for(const[k,g]of r.entries)result[k]+=g*projection;}return result;};
 const delta=new Float64Array(dimension),residual=Float64Array.from(rhs),z=Float64Array.from(residual,(v,k)=>v/diagonal[k]);let direction=Float64Array.from(z),rz=dot(residual,z),cgIterations=0;
 for(;cgIterations<Math.min(120,dimension)&&dot(residual,residual)>1e-24;cgIterations++){const q=multiply(direction),den=dot(direction,q);if(!(den>0))throw Error('HOLD: nonpositive damped mass-weighted wear system');const alpha=rz/den;for(let k=0;k<dimension;k++){delta[k]+=alpha*direction[k];residual[k]-=alpha*q[k];z[k]=residual[k]/diagonal[k];}const next=dot(residual,z),beta=next/rz;for(let k=0;k<dimension;k++)direction[k]=z[k]+beta*direction[k];rz=next;}
 const old=cloth.positions.map(p=>p.slice()),proposedMoveM=Math.max(...cloth.positions.map((_,i)=>Math.hypot(...delta.subarray(i*3,i*3+3))*Math.sqrt(cloth.invMass[i]))),trustFraction=Math.min(1,.003/Math.max(1e-30,proposedMoveM));if(!Number.isFinite(proposedMoveM))throw Error('HOLD: nonfinite whole wear proposal');
 const apply=fraction=>{for(let i=0;i<cloth.positions.length;i++)for(let k=0;k<3;k++)cloth.positions[i][k]=old[i][k]+delta[i*3+k]*Math.sqrt(cloth.invMass[i])*trustFraction*fraction;};
 return{rows,rhs,delta,residual,cgIterations,old,proposedMoveM,trustFraction,apply,analytic:-2*dot(rhs,delta)*trustFraction};
}
// A single derivative OBSERVER. No iteration is accepted, no native state is
// modified, and all temporarily perturbed static coordinates are restored.
export function auditShortsWearingContactDerivative(cloth,{epsilon=1e-4}={}){
 if(epsilon!==1e-4)throw Error('Contact derivative observer freezes the original epsilon, no scan');
 const identity=cloth.materialIdentity(),native=JSON.stringify({time:cloth.time,steps:cloth.steps,previous:cloth.previous,velocity:cloth.velocity,history:cloth.history}),before=cloth.positions.map(p=>p.slice());cloth.body.refitExact();const defs=makeDefinitions(cloth),p=proposal(cloth,defs),captures=[];let trueMinus,truePlus,frozenMinus,frozenPlus;
 try{
  for(const fraction of [-epsilon,epsilon]){p.apply(fraction);const contacts=defs.samples.map(s=>contact(cloth,s).witness);captures.push({fraction,contacts});const t=energy(components(defs.rows)),f=energy(components(p.rows));if(fraction<0){trueMinus=t;frozenMinus=f;}else{truePlus=t;frozenPlus=f;}}
 }finally{p.apply(0);}
 const switched=[];for(let i=0;i<defs.samples.length;i++){const minus=captures[0].contacts[i],plus=captures[1].contacts[i],base=p.rows.find(r=>r.sample===defs.samples[i]).contactAnchor,signChanged=Math.sign(minus.signedDistanceM)!==Math.sign(plus.signedDistanceM),featureChanged=minus.triangleId!==plus.triangleId||minus.feature!==plus.feature||JSON.stringify(minus.featureIndices)!==JSON.stringify(plus.featureIndices),jump=Math.abs(plus.signedDistanceM-minus.signedDistanceM);if(signChanged||featureChanged)switched.push({sampleIndex:i,signChanged,featureChanged,maximumSamplePerturbationM:Math.hypot(...plus.point.map((v,k)=>v-minus.point[k]))/2,signedDistanceJumpM:jump,anchor:base,minus,plus});}
 switched.sort((a,b)=>b.signedDistanceJumpM-a.signedDistanceJumpM);const trueFD=(truePlus-trueMinus)/(2*epsilon),frozenFD=(frozenPlus-frozenMinus)/(2*epsilon);
 if(identity!==cloth.materialIdentity()||native!==JSON.stringify({time:cloth.time,steps:cloth.steps,previous:cloth.previous,velocity:cloth.velocity,history:cloth.history})||JSON.stringify(before)!==JSON.stringify(cloth.positions))throw Error('Read-only contact derivative observer modified physical/source state');
 return{schema:'shorts-contact-derivative-observer@1',epsilon,analytic:p.analytic,trueClosestFD:trueFD,frozenPlaneFD:frozenFD,trueClosestRelativeError:Math.abs(trueFD-p.analytic)/Math.max(Math.abs(trueFD),Math.abs(p.analytic),1e-30),frozenPlaneRelativeError:Math.abs(frozenFD-p.analytic)/Math.max(Math.abs(frozenFD),Math.abs(p.analytic),1e-30),trueMinusEnergy:trueMinus,truePlusEnergy:truePlus,frozenMinusEnergy:frozenMinus,frozenPlusEnergy:frozenPlus,proposedMoveM:p.proposedMoveM,trustFraction:p.trustFraction,cgIterations:p.cgIterations,switchedContactCount:switched.length,signSwitchCount:switched.filter(s=>s.signChanged).length,switchedContacts:switched,sourceAndCoordinatesAndNativeStateUnchanged:true,noStepAccepted:true,closedSolidCertified:false};
}
function inspect(cloth,defs,heightToleranceM){const material=cloth.audit(false);let minSigned=Infinity,worst=null;for(const s of defs.samples){const h=contact(cloth,s);if(h.signedDistanceM<minSigned){minSigned=h.signedDistanceM;worst=h.witness;}}const heights=defs.guideGroups.map(g=>({kind:g.kind,targetActorLocalY:g.y,count:g.ids.length,maximumGapM:Math.max(...g.ids.map(id=>Math.abs(dot(cloth.positions[id],defs.axis)-defs.base-g.y)))})),heightGapM=Math.max(...heights.map(g=>g.maximumGapM)),deficit=Math.max(0,cloth.options.bodyClearanceM-minSigned),passed=material.finite&&material.mainStrain<=.05&&deficit===0&&heightGapM<=heightToleranceM;return{sampledStaticPassed:passed,mainStrain:material.mainStrain,worstMaterialTriangle:material.worstMaterialTriangle,finite:material.finite,minimumFeatureSignedDistanceM:minSigned,requiredClearanceM:cloth.options.bodyClearanceM,maximumSampledClearanceDeficitM:deficit,worstContact:worst,heights,maximumHeightGapM:heightGapM,heightToleranceM,materialFivePercentPassed:material.mainStrain<=.05,sampledClearancePassed:deficit===0,heightPassed:heightGapM<=heightToleranceM,contactScope:'actual current source-feature vertices and centroids only; complete triangles, strict self-contact and motion pending'};}
export async function solveShortsWearingMetric(cloth,{maximumIterations=40,heightToleranceM=.008,onProgress=()=>{}}={}){
 if(!Number.isInteger(maximumIterations)||maximumIterations<1||maximumIterations>40||!(heightToleranceM>0&&Number.isFinite(heightToleranceM)))throw Error('Wear authoring requires at most forty iterations and finite positive height tolerance');
 if(cloth.activeSeams.length!==19||cloth.positions.length!==451||cloth.quotient.length!==553||cloth.triangles.length!==848||!cloth.invMass.every(w=>w>0&&Number.isFinite(w)))throw Error('Whole wear metric requires the actual full nineteen source seams and 451 free physical DOFs');
 const sourceIdentity=cloth.materialIdentity(),sourcePairs=JSON.stringify(cloth.draft.seams),nativeIdentity=JSON.stringify({time:cloth.time,steps:cloth.steps,previous:cloth.previous,velocity:cloth.velocity,history:cloth.history}),initialPositions=cloth.positions.map(p=>p.slice()),trace=[],start=performance.now();let initial=null,final=null,stopReason='bounded iteration limit',holdWitness=null,lastAcceptedAudit=null;
 cloth.body.refitExact();const defs=makeDefinitions(cloth);
 try{
  initial=inspect(cloth,defs,heightToleranceM);lastAcceptedAudit=initial;
  for(let iteration=0;iteration<maximumIterations&&!initial.sampledStaticPassed;iteration++){
   const {rows,rhs,residual,cgIterations,proposedMoveM,trustFraction,apply,analytic}=proposal(cloth,defs),initialComponents=components(rows),initialEnergy=energy(initialComponents),actualInitialComponents=components(defs.rows),actualInitialEnergy=energy(actualInitialComponents),initialActualContactEnergy=(actualInitialComponents['body-vertex']??0)+(actualInitialComponents['body-centroid']??0);
   const evaluateAt=fraction=>{apply(fraction);return energy(components(rows));},epsilon=1e-4;let fd;
   try{fd=(evaluateAt(epsilon)-evaluateAt(-epsilon))/(2*epsilon);}catch(e){apply(0);throw e;}apply(0);
   const relativeError=Math.abs(analytic-fd)/Math.max(1e-30,Math.abs(analytic),Math.abs(fd)),descentAudit={scope:'same frozen current closest-feature planes for Jacobian and FD; fresh closest queries independently gate acceptance',analyticDirectionalDerivative:analytic,finiteDifferenceDirectionalDerivative:fd,relativeError,relativeCGResidual:Math.hypot(...residual)/Math.max(1e-30,Math.hypot(...rhs))};let fraction=0,finalEnergy=initialEnergy,acceptedAudit=null,finalComponents=initialComponents,actualFinalComponents=actualInitialComponents,actualFinalEnergy=actualInitialEnergy,rejectedPrincipalCandidates=0,rejectedActualContactCandidates=0,rejectedActualMeritCandidates=0;
   if(!(analytic<0)||relativeError>1e-3){stopReason='HOLD: independent finite-difference descent check failed';trace.push({iteration:iteration+1,descentAudit,proposedMoveM,acceptedFraction:0,initialEnergy});break;}
   try{for(let power=0;power<=20;power++){const f=2**(-power);apply(f);const c=components(rows),value=energy(c);if(Number.isFinite(value)&&value<initialEnergy&&value<=initialEnergy+1e-4*f*analytic){
    const audit=inspect(cloth,defs,heightToleranceM);if(!audit.finite||audit.mainStrain>initial.mainStrain+1e-9){rejectedPrincipalCandidates++;continue;}
    const actual=components(defs.rows),trueEnergy=energy(actual),trueContactEnergy=(actual['body-vertex']??0)+(actual['body-centroid']??0);
    // A local contact plane is a model only. A sign/feature switch must never
    // turn a better surrogate into an accepted worse actual-body contact.
    if(audit.maximumSampledClearanceDeficitM>lastAcceptedAudit.maximumSampledClearanceDeficitM||trueContactEnergy>initialActualContactEnergy){rejectedActualContactCandidates++;continue;}
    if(!Number.isFinite(trueEnergy)||!(trueEnergy<actualInitialEnergy)){rejectedActualMeritCandidates++;continue;}
    fraction=f;finalEnergy=value;finalComponents=c;actualFinalComponents=actual;actualFinalEnergy=trueEnergy;acceptedAudit=audit;break;
   }}}catch(e){apply(0);throw e;}
   if(!fraction){apply(0);stopReason='HOLD: no bounded surrogate Armijo step passed fresh actual-body no-regression and initial-principal guards';}
   trace.push({iteration:iteration+1,cgIterations,rows:rows.length,proposedMoveM,trustFraction,acceptedFraction:fraction,maximumAppliedMoveM:proposedMoveM*trustFraction*fraction,meritScope:'initialEnergy/finalEnergy frozen local contact planes; actualInitialEnergy/actualFinalEnergy fresh actual closest features',initialEnergy,finalEnergy,initialComponents,finalComponents,actualInitialEnergy,actualFinalEnergy,actualInitialComponents,actualFinalComponents,descentAudit,rejectedPrincipalCandidates,rejectedActualContactCandidates,rejectedActualMeritCandidates,actualAcceptedAudit:acceptedAudit});onProgress(trace.at(-1));
   if(!fraction)break;lastAcceptedAudit=acceptedAudit;if(acceptedAudit.sampledStaticPassed){stopReason='sampled static gates passed; complete wearing remains pending';break;}await new Promise(r=>setTimeout(r,0));
  }
  final=inspect(cloth,defs,heightToleranceM);
 }catch(e){stopReason=e.message;holdWitness=e.witness??null;try{final=inspect(cloth,defs,heightToleranceM);}catch{final=null;}}
 let restoredInitialForRegression=false;if(final&&initial&&(!final.finite||final.mainStrain>initial.mainStrain+1e-9)){initialPositions.forEach((p,i)=>p.forEach((v,k)=>cloth.positions[i][k]=v));restoredInitialForRegression=true;final=inspect(cloth,defs,heightToleranceM);stopReason='HOLD: whole candidate regressed initial material envelope; initial state retained';}
 if(sourceIdentity!==cloth.materialIdentity()||sourcePairs!==JSON.stringify(cloth.draft.seams)||nativeIdentity!==JSON.stringify({time:cloth.time,steps:cloth.steps,previous:cloth.previous,velocity:cloth.velocity,history:cloth.history}))throw Error('Static wear authoring changed source references or native state/history');
 cloth.syncRender();return{schema:'r008-whole-wear-metric-authoring@2',status:final?.sampledStaticPassed&&!holdWitness?'sampled-static-passed':'HOLD',scope:'bounded simultaneous whole free-DOF static authoring only; not XPBD/native dynamics or complete collision acceptance',maximumIterations,iterations:trace.length,staticProposalMaximumMoveM:.003,numericalDamping:.01,sourceRowScaling:'fixed original source2D isometric Gram derivatives and unchanged actual inverse masses; never current-strain row normalization',contactLinearization:'one actual closest-feature signed-distance plane frozen only within each GN FD/Armijo iteration; new closest queried for every candidate acceptance and next iteration',actualContactNoRegressionGuard:'fresh sampled maximum clearance deficit and fixed-scaled contact squared merit cannot increase from previous accepted state; fresh total merit must decrease',fullCoverageValidated:false,initial,final,trace,stopReason,holdWitness,restoredInitialForRegression,elapsedMs:performance.now()-start,sourceUVRestMassAllNineteenPairsUnchanged:true,all451PhysicalDofsFree:cloth.invMass.every(w=>w>0),temporaryHeightGuides:defs.guideGroups.map(g=>({kind:g.kind,count:g.ids.length,targetActorLocalY:g.y})),permanentPins:0,elastic:{sourceEdges:cloth.draft.elasticEdges.length,activeNativeEdges:cloth.elastic.length,activatedByThisAuthoring:false,scope:'original finite elastic channel preserved; no elastic/native force integration in this static solve'},previousVelocityTimeHistoryUnchanged:true,nativeInitialStateRebasePending:true,nativeClothSteps:0,strictSelfContactValidated:false,fullTriangleBodyContactValidated:false,motionValidated:false,productionReady:false};
}
