// Independent read-only authoring audit. Geometry, source UV, masses and native
// state are never repaired here. Spacing and distortion are separate evidence:
// https://graphics.pixar.com/library/garmentRefit/paper.pdf
const EPS=1e-9;
const sub=(a,b)=>a.map((x,k)=>x-b[k]),dot=(a,b)=>a.reduce((s,x,k)=>s+x*b[k],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],length=a=>Math.hypot(...a),distance=(a,b)=>length(sub(a,b));
const key=(a,b)=>a<b?a+':'+b:b+':'+a;
function stats(values){const sorted=values.slice().sort((a,b)=>a-b);return {count:sorted.length,min:sorted[0]??null,max:sorted.at(-1)??null,mean:sorted.length?sorted.reduce((a,b)=>a+b,0)/sorted.length:null,p50:sorted.length?sorted[Math.floor((sorted.length-1)*.5)]:null,p95:sorted.length?sorted[Math.floor((sorted.length-1)*.95)]:null};}
const bounds=p=>({min:[0,1,2].map(k=>Math.min(...p.map(v=>v[k]))-EPS),max:[0,1,2].map(k=>Math.max(...p.map(v=>v[k]))+EPS)}),overlap=(a,b)=>[0,1,2].every(k=>a.min[k]<=b.max[k]&&b.min[k]<=a.max[k]);
const axis=n=>Math.abs(n[0])>=Math.abs(n[1])&&Math.abs(n[0])>=Math.abs(n[2])?0:Math.abs(n[1])>=Math.abs(n[2])?1:2,project=(p,k)=>p.filter((_,i)=>i!==k),orient=(a,b,p)=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]),mix=(a,b,t)=>a.map((x,k)=>x+(b[k]-x)*t);
function clip(points,tri,drop){let result=points.map(p=>p.slice());const t=tri.map(p=>project(p,drop)),sign=Math.sign(orient(...t));for(let e=0;e<3&&result.length;e++){const a=t[e],b=t[(e+1)%3],tolerance=EPS*Math.hypot(b[0]-a[0],b[1]-a[1]),input=result;result=[];let previous=input.at(-1),dp=sign*orient(a,b,project(previous,drop));for(const current of input){const dc=sign*orient(a,b,project(current,drop)),pin=dp>=-tolerance,cin=dc>=-tolerance;if(pin!==cin&&dp!==dc)result.push(mix(previous,current,Math.max(0,Math.min(1,dp/(dp-dc)))));if(cin)result.push(current.slice());previous=current;dp=dc;}}return result;}
function segmentTriangle(a,b,t,n){const da=dot(sub(a,t[0]),n),db=dot(sub(b,t[0]),n);if((da>EPS&&db>EPS)||(da< -EPS&&db< -EPS))return [];if(Math.abs(da)<=EPS&&Math.abs(db)<=EPS)return clip([a,b],t,axis(n));if(da===db)return [];const u=da/(da-db);if(u<0||u>1)return [];const p=mix(a,b,u);return clip([p],t,axis(n));}
function triangleIntersection(a,b){const d=a.points.map(p=>dot(sub(p,b.points[0]),b.normal)),e=b.points.map(p=>dot(sub(p,a.points[0]),a.normal));if(d.every(x=>x>EPS)||d.every(x=>x< -EPS)||e.every(x=>x>EPS)||e.every(x=>x< -EPS))return null;const coplanar=d.every(x=>Math.abs(x)<=EPS)&&e.every(x=>Math.abs(x)<=EPS),points=[];if(coplanar)points.push(...clip(a.points,b.points,axis(b.normal)));else for(let i=0;i<3;i++){points.push(...segmentTriangle(a.points[i],a.points[(i+1)%3],b.points,b.normal));points.push(...segmentTriangle(b.points[i],b.points[(i+1)%3],a.points,a.normal));}const unique=[];for(const p of points)if(!unique.some(q=>distance(p,q)<=EPS))unique.push(p);return unique.length?{coplanar,points:unique}:null;}

/** Current cloth WORLD coordinates are authority. Thresholds describe authoring
 * review only: 12 mm maximum waist spacing, 4 mm minimum contact distance, and
 * 60 degree fold flags are explicit engineering criteria, not fabric data.
 * body should be the same actual visible-skin contact API used by the preview.
 * This does not advance poses, turn on gravity, or certify physical wearing. */
export function inspectShortsSurfaceQuality(cloth,{body=cloth?.body,minimumWaistClearanceM=.004,maximumWaistDistanceM=.012,principalStrainLimit=.05,flagFoldAngleDegrees=60,checkSelfIntersections=true}={}){
 if(!cloth?.draft||!Array.isArray(cloth.positions)||!Array.isArray(cloth.triangles)||!cloth.quotient||!body?.closestPoint)throw Error('Actual cloth, source paper and current visible-body query required');
 if(![minimumWaistClearanceM,maximumWaistDistanceM,principalStrainLimit,flagFoldAngleDegrees].every(Number.isFinite)||minimumWaistClearanceM<0||maximumWaistDistanceM<minimumWaistClearanceM||principalStrainLimit<0||flagFoldAngleDegrees<0||flagFoldAngleDegrees>180)throw Error('Finite ordered surface-review thresholds required');
 const start=performance.now(),materialBefore=cloth.materialIdentity?.(),nativeBefore=body.snapshot?.(),positions=cloth.positions.map(p=>{if(p.length!==3||!p.every(Number.isFinite))throw Error('Finite current WORLD cloth positions required');return p.slice();}),draft=cloth.draft,uv=draft.sourceUV||draft.uvs,ranges=draft.ranges,rows=[],edges=new Map(),byPiece={};
 if(!uv||!ranges||!draft.pieces||!draft.seams)throw Error('Independent source paper identity and seams required');
 const sourcePoint=i=>{const q=cloth.quotient[i];if(!Number.isInteger(q)||!positions[q])throw Error('Actual source quotient mapping required');return positions[q];};
 let worstMetric=null,maximumPrincipal=0;const zeroAreaTriangles=[];
 for(let id=0;id<cloth.triangles.length;id++){
  const t=cloth.triangles[id];if(t.q.length!==3||t.original.length!==3)throw Error('Original paper and actual quotient triangle required');
  const points=t.q.map(i=>positions[i]),u=t.original.map(i=>[uv[i*2],uv[i*2+1]]);if(!points.every(Boolean)||!u.flat().every(Number.isFinite))throw Error('Finite actual/source triangle required');
  const du=sub(u[1],u[0]),dv=sub(u[2],u[0]),det=du[0]*dv[1]-du[1]*dv[0];if(!Number.isFinite(det)||Math.abs(det)<=1e-14)throw Error('HOLD: degenerate original two-dimensional paper');
  const a=sub(points[1],points[0]),b=sub(points[2],points[0]),n=cross(a,b),area2=length(n),side2=[0,1,2].map(i=>distance(points[i],points[(i+1)%3])**2),area=area2/2,quality=side2.reduce((x,y)=>x+y,0)>0?2*Math.sqrt(3)*area2/side2.reduce((x,y)=>x+y,0):0,minimumAltitude=area2/Math.sqrt(Math.max(...side2));
  const Fu=a.map((x,k)=>(x*dv[1]-b[k]*du[1])/det),Fv=b.map((x,k)=>(x*du[0]-a[k]*dv[0])/det),A=dot(Fu,Fu),B=dot(Fu,Fv),D=dot(Fv,Fv),disc=Math.hypot(A-D,2*B),sigmaMin=Math.sqrt(Math.max(0,(A+D-disc)/2)),sigmaMax=Math.sqrt(Math.max(0,(A+D+disc)/2)),strain=Math.max(Math.abs(sigmaMin-1),Math.abs(sigmaMax-1)),pieceId=ranges.find(r=>t.original[0]>=r.offset&&t.original[0]<r.offset+r.count)?.pieceId;
  const row={id,q:t.q.slice(),original:t.original.slice(),points:points.map(p=>p.slice()),normal:area2?n.map(x=>x/area2):[0,0,0],areaM2:area,quality,minimumAltitudeM:Number.isFinite(minimumAltitude)?minimumAltitude:0,areaRatio:area/Math.abs(det/2),sigmaMin,sigmaMax,strain,pieceId,box:bounds(points)};rows.push(row);
  if(area2<=1e-20)zeroAreaTriangles.push({triangle:id,pieceId,sourceIndices:row.original,actualDOFs:row.q,worldXYZ:row.points});
  if(!byPiece[pieceId])byPiece[pieceId]={rows:[]};byPiece[pieceId].rows.push(row);
  if(!worstMetric||strain>maximumPrincipal){maximumPrincipal=strain;worstMetric={triangle:id,pieceId,sourceIndices:row.original,actualDOFs:row.q,sigmaMin,sigmaMax,principalStrain:strain,sourceUV:u,worldXYZ:row.points};}
  for(let j=0;j<3;j++){const x=t.q[j],y=t.q[(j+1)%3],k=key(x,y);if(!edges.has(k))edges.set(k,[]);edges.get(k).push({triangle:id,a:x,b:y});}
 }
 const orientation=Array(rows.length).fill(0),adj=rows.map(()=>[]),nonManifoldEdges=[];for(const [edge,list]of edges){if(list.length===2){const [a,b]=list,factor=a.a===b.a?-1:1;adj[a.triangle].push([b.triangle,factor]);adj[b.triangle].push([a.triangle,factor]);}else if(list.length>2)nonManifoldEdges.push({edge,triangles:list.map(x=>x.triangle)});}
 let components=0,orientationConflict=false;for(let i=0;i<rows.length;i++)if(!orientation[i]){components++;orientation[i]=1;const queue=[i];for(let h=0;h<queue.length;h++)for(const [j,factor]of adj[queue[h]]){const expected=orientation[queue[h]]*factor;if(!orientation[j]){orientation[j]=expected;queue.push(j);}else if(orientation[j]!==expected)orientationConflict=true;}}
 const folds=[];for(const [edge,list]of edges)if(list.length===2){const [a,b]=list,x=rows[a.triangle],y=rows[b.triangle];if(x.areaM2<=5e-21||y.areaM2<=5e-21)continue;const degrees=Math.acos(Math.max(-1,Math.min(1,dot(x.normal,y.normal)*orientation[a.triangle]*orientation[b.triangle])))*180/Math.PI;folds.push({edge,triangles:[a.triangle,b.triangle],pieces:[x.pieceId,y.pieceId],angleDegrees:degrees,sharedWorldEdge:edge.split(':').map(i=>positions[Number(i)].slice())});}
 const activeSeams=new Set((cloth.activeSeams||draft.seams).map(s=>s.id)),seamWitnesses=[];let maximumSeamGapM=0;for(const seam of draft.seams)for(const [pairId,pair]of seam.pairs.entries()){const a=pair.a??pair[0],b=pair.b??pair[1],gap=distance(sourcePoint(a),sourcePoint(b));maximumSeamGapM=Math.max(maximumSeamGapM,gap);seamWitnesses.push({seamId:seam.id,pairId,active:activeSeams.has(seam.id),sourceIndices:[a,b],actualDOFs:[cloth.quotient[a],cloth.quotient[b]],gapM:gap});}
 // Fine source paper preserves the original structured grid metadata. Its
 // actual elastic-channel ring, rather than that old grid, owns fine middle
 // sampling. No refinement or replacement of source metadata happens here.
 const ringInput=draft.casing?.middleIndices,hasMiddleRing=ringInput!==undefined&&ringInput!==null,middleRing=hasMiddleRing?Array.from(ringInput):null,paths=[];
 if(hasMiddleRing){if(middleRing.length>1&&cloth.quotient[middleRing[0]]===cloth.quotient[middleRing.at(-1)])middleRing.pop();if(middleRing.length<3||!middleRing.every(i=>Number.isInteger(i)&&i>=0&&i<cloth.quotient.length)||new Set(middleRing.map(i=>cloth.quotient[i])).size!==middleRing.length)throw Error('HOLD: complete nonduplicated actual casing middle ring required');paths.push({role:'middle',pieceId:null,ids:middleRing,closed:true,authority:'actual draft.casing.middleIndices complete closed elastic-channel ring'});}
 for(const piece of draft.pieces)if(piece.kind==='waistband'){const range=ranges.find(r=>r.pieceId===piece.id);if(!range)throw Error('Casing source range required');for(const edge of ['upper','lower']){const ids=piece.boundaries[edge]?.map(i=>range.offset+i);if(!ids?.length)throw Error('Casing source upper/lower boundaries required');paths.push({role:edge,pieceId:piece.id,ids});}if(!hasMiddleRing){const boundary=piece.middleBoundary??piece.boundaries.middle;if(boundary?.length)paths.push({role:'middle',pieceId:piece.id,ids:Array.from(boundary,i=>range.offset+i),authority:'actual piece middle source boundary'});else if(piece.grid?.rows===2&&!piece.surfaceRefinement)paths.push({role:'middle',pieceId:piece.id,ids:Array.from({length:piece.grid.columns+1},(_,c)=>range.offset+piece.grid.columns+1+c),authority:'unrefined original structured two-row source grid'});else throw Error('HOLD: refined casing requires its actual middle source boundary');}}
 if(!paths.length)throw Error('Actual source casing paths required');
 const samples=[],sampleKeys=new Set();function sample(role,kind,ids,weights,pieceId){const q=ids.map(i=>cloth.quotient[i]),id=role+':'+kind+':'+q.join(':');if(sampleKeys.has(id))return;sampleKeys.add(id);const p=[0,1,2].map(k=>q.reduce((sum,i,j)=>sum+positions[i][k]*weights[j],0)),h=body.closestPoint(p);if(!h||![h.distance,h.signedDistance].every(Number.isFinite))throw Error('Finite current visible-body distance required');samples.push({role,kind,pieceId,sourceIndices:ids,actualDOFs:q,worldXYZ:p,distanceM:h.distance,signedDistanceM:h.signedDistance,part:h.part,bodyTriangle:h.triangleId,bodyIndices:h.indices?.slice(),feature:typeof h.feature==='string'?h.feature:h.feature?.type,signAmbiguous:!!h.signAmbiguous,signedDistanceAuthority:h.signedDistanceAuthority??h.normalAuthority??null,closestWorldXYZ:h.point?.toArray?.()??null,guard:h.guard??null});}
 for(const p of paths){for(const id of p.ids)sample(p.role,'vertex',[id],[1],p.pieceId);for(let i=0;i<p.ids.length-(p.closed?0:1);i++)sample(p.role,'edge-midpoint',[p.ids[i],p.ids[(i+1)%p.ids.length]],[.5,.5],p.pieceId);}
 for(const row of rows)if(draft.pieces.find(p=>p.id===row.pieceId)?.kind==='waistband')sample('casing-surface','triangle-centroid',row.original,[1/3,1/3,1/3],row.pieceId);
 const spacing={};for(const role of [...new Set(samples.map(s=>s.role))]){const s=samples.filter(p=>p.role===role);spacing[role]={unsignedDistanceM:stats(s.map(p=>p.distanceM)),signedDistanceM:stats(s.map(p=>p.signedDistanceM)),minimumWitness:s.reduce((a,b)=>!a||b.signedDistanceM<a.signedDistanceM?b:a,null),maximumWitness:s.reduce((a,b)=>!a||b.distanceM>a.distanceM?b:a,null)};}
 const insideOrTooClose=samples.filter(s=>s.signedDistanceM<minimumWaistClearanceM),tooFar=samples.filter(s=>s.distanceM>maximumWaistDistanceM),ambiguous=samples.filter(s=>s.signAmbiguous),selfCrossings=[];let testedPairs=0,broadphasePairs=0,excludedSharedDOFPairs=0;
 if(checkSelfIntersections){const sorted=rows.slice().sort((a,b)=>a.box.min[0]-b.box.min[0]);for(let i=0;i<sorted.length;i++){const a=sorted[i];if(a.areaM2<=5e-21)continue;for(let j=i+1;j<sorted.length&&sorted[j].box.min[0]<=a.box.max[0];j++){const b=sorted[j];if(!overlap(a.box,b.box)||b.areaM2<=5e-21)continue;broadphasePairs++;if(a.q.some(q=>b.q.includes(q))){excludedSharedDOFPairs++;continue;}testedPairs++;const hit=triangleIntersection(a,b);if(hit)selfCrossings.push({triangles:[a.id,b.id],pieces:[a.pieceId,b.pieceId],actualDOFs:[a.q,b.q],sourceIndices:[a.original,b.original],worldXYZ:[a.points,b.points],...hit});}}}
 const boundaryEdges=[...edges.values()].filter(list=>list.length===1),boundaryAdj=new Map();for(const [edge]of boundaryEdges){for(const [a,b]of [[edge.a,edge.b],[edge.b,edge.a]]){if(!boundaryAdj.has(a))boundaryAdj.set(a,[]);boundaryAdj.get(a).push(b);}}
 let boundaryComponents=0;const seen=new Set();for(const id of boundaryAdj.keys())if(!seen.has(id)){boundaryComponents++;const queue=[id];seen.add(id);for(let h=0;h<queue.length;h++)for(const j of boundaryAdj.get(queue[h]))if(!seen.has(j)){seen.add(j);queue.push(j);}}
 const referencedDOFs=new Set(rows.flatMap(r=>r.q)),closedBoundaryLoops=[...boundaryAdj.values()].every(a=>a.length===2),euler=referencedDOFs.size-edges.size+rows.length,topology={referencedDOFs:referencedDOFs.size,edges:edges.size,triangles:rows.length,components,boundaryEdges:boundaryEdges.length,boundaryComponents,closedBoundaryLoops,euler,nonManifoldEdges,orientationConflict,pairOfPantsTopologyObserved:components===1&&boundaryComponents===3&&closedBoundaryLoops&&euler===-1&&!nonManifoldEdges.length&&!orientationConflict};
 for(const [piece,record]of Object.entries(byPiece)){const r=record.rows;byPiece[piece]={triangles:r.length,areaM2:r.reduce((s,t)=>s+t.areaM2,0),quality:stats(r.map(t=>t.quality)),minimumAltitudeM:stats(r.map(t=>t.minimumAltitudeM)),areaRatioToSource:stats(r.map(t=>t.areaRatio)),principalStrain:stats(r.map(t=>t.strain))};}
 if(materialBefore!==cloth.materialIdentity?.()||cloth.positions.some((p,i)=>p.some((x,k)=>x!==positions[i][k])))throw Error('Surface audit changed or raced actual source/positions');const nativeAfter=body.snapshot?.();if(nativeBefore&&nativeAfter&&(nativeBefore.revision!==nativeAfter.revision||nativeBefore.time!==nativeAfter.time))throw Error('HOLD: body pose changed during surface quality audit');
 const materialPassed=maximumPrincipal<=principalStrainLimit,waistSpacingPassed=!insideOrTooClose.length&&!tooFar.length&&!ambiguous.length,seamsPassed=maximumSeamGapM<=EPS&&activeSeams.size===draft.seams.length,staticTopologyPassed=topology.pairOfPantsTopologyObserved&&!zeroAreaTriangles.length,selfTestPassed=checkSelfIntersections&&!selfCrossings.length;
 return {schema:'r008-shorts-surface-quality/v1',coordinateFrame:'current WORLD metres',elapsedMs:performance.now()-start,criteria:{minimumWaistClearanceM,maximumWaistDistanceM,principalStrainLimit,flagFoldAngleDegrees,authority:'explicit authoring review criteria; spacing/angle are uncalibrated engineering inputs, not fabric measurements'},material:{maximumPrincipalStrain:maximumPrincipal,worst:worstMetric,passed:materialPassed,sourceAuthority:'independent source two-dimensional UV to actual three-dimensional quotient metric; original rest unchanged'},waistCasing:{spacing,sampleCount:samples.length,samples,insideOrTooClose,tooFar,ambiguous,passed:waistSpacingPassed,scope:'actual vertices/edge midpoints and casing triangle centroids; finite samples do not bound the entire curved body distance'},seams:{maximumGapM:maximumSeamGapM,active:activeSeams.size,source:draft.seams.length,passed:seamsPassed,witnesses:seamWitnesses,authority:'source pair mapped to actual current quotient WORLD positions; no assumed seamGap=0'},triangles:{areaM2:stats(rows.map(r=>r.areaM2)),quality:stats(rows.map(r=>r.quality)),minimumAltitudeM:stats(rows.map(r=>r.minimumAltitudeM)),byPiece,zeroAreaTriangles,qualityDefinition:'4 sqrt(3) area / sum squared edge lengths, equilateral=1, degenerate=0'},folds:{angleDegrees:stats(folds.map(f=>f.angleDegrees)),flagged:folds.filter(f=>f.angleDegrees>flagFoldAngleDegrees),orientationAuthority:'source quotient adjacency parity; no rendered smooth-normal substitution',visualSmoothnessCertified:false},topology,selfIntersections:{performed:checkSelfIntersections,broadphasePairs,testedPairs,excludedSharedDOFPairs,crossingCount:selfCrossings.length,witnesses:selfCrossings,passed:selfTestPassed,method:'conservative AABB sweep, six edges and coplanar polygon clipping, double precision',toleranceM:EPS,limitations:'pairs sharing any actual DOF excluded; folds/overlap in adjacent triangles and swept intersections are not certified'},authoringReviewPassed:materialPassed&&waistSpacingPassed&&seamsPassed&&staticTopologyPassed&&selfTestPassed,bodyTriangleCoverageChecked:false,wholeSurfaceCleanCertified:false,physicalWearingPassed:false,nativeMotionValidated:false,sourceUVRestMassChanged:false,geometryMutations:0};
}
