import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {constructShortsPaper} from './ShortsPaperConstruction.mjs';
import {constructFeasibleShortsPaper} from './ShortsFeasiblePaperConstruction.mjs';
import {ShortsClothRuntime} from './ShortsClothRuntime.mjs';
import {compilePaperSurfaceModel,evaluatePaperSurface} from './ShortsPaperSurfaceModel.mjs';
import {inspectShortsTriangleCrossings} from './ShortsCoverageIntersection.mjs';
export function installShortsPaperResearch(game,{renderer,camera,scene,body,measuredBody,barePelvis,skinTapes,draft,sourcePants}){
 const panel=document.createElement('aside');panel.id='paper-research';panel.style.cssText='position:absolute;right:12px;top:18px;background:#152424ee;color:white;padding:14px;width:280px;font:14px/1.6 system-ui';panel.innerHTML='<strong>短裤 · 缝合与人物定位检查</strong><p id="paper-state">正在构造布片</p><p>穿着尚未通过，动作暂停</p>';document.body.append(panel);
 const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=false;let cloth=null,render=true,disposed=false;
 const api={inspection:true,simulationCertified:false,body,measuredBody,barePelvis,skinTapes,measurementDraft:draft,game,fitStatus:'adjusting',get fitPreview(){return cloth;},get draft(){return cloth?.draft??draft;},requestRender(){render=true;},consumeRenderRequest(){const r=render;render=false;return r;},updateCamera(){orbit.update();},setView(name){const target=game.actor.localToWorld(new THREE.Vector3(0,(draft.receipt.upperY+draft.receipt.hem.y)/2,0)),offset=new THREE.Vector3(name==='side'?1.1:0,name==='below'?-.65:.07,name==='back'?-1.1:name==='side'?0:1.1).applyQuaternion(game.actor.getWorldQuaternion(new THREE.Quaternion()));camera.position.copy(target).add(offset);orbit.target.copy(target);camera.lookAt(target);orbit.update();renderer.render(scene,camera);},dispose(){disposed=true;cloth?.dispose();barePelvis.dispose();for(const p of sourcePants)p.material.visible=p.visible;panel.remove();orbit.dispose();}};
 window.HumanShorts=api;game.setPaused(true);for(const id of ['start','tryJump','pause','action','reset']){const node=document.getElementById(id);if(node)node.disabled=true;}
 const queryContact=p=>{const hit=body.closestSurfacePoint(new THREE.Vector3(...p).applyMatrix4(skinTapes.frame));return{signedDistanceM:hit.signedDistance,normal:hit.normal.clone().transformDirection(skinTapes.inverseFrame).toArray(),signAmbiguous:hit.signAmbiguous,geometryRevision:hit.geometryRevision,bareGeometryRevision:hit.bareGeometryRevision,contactMode:hit.contactMode,bareClosedInsideObserved:hit.bareClosedInsideObserved};};
 const options={queryContact,onProgress:r=>{if(disposed)throw Error('Superseded paper research');document.getElementById('paper-state').textContent=`${r.phase}${r.strain!==undefined?' · 应变 '+(100*r.strain).toFixed(2)+'%':''}`;}};
 api.fitPromise=(window.__SHORTS_PAPER_CONTACT_PROBE_ONLY__===true?Promise.resolve({status:'CONTACT_PROBE_ONLY',draft,activeSeamIDs:[]}):window.__SHORTS_PAPER_FEASIBLE__===true?constructFeasibleShortsPaper(draft,skinTapes,measuredBody,barePelvis,options):constructShortsPaper(draft,skinTapes,options)).then(result=>{
  if(disposed)return;api.fitResult=result;cloth=new ShortsClothRuntime(result.draft,body,game.actor,scene,{...(result.activeSeamIDs?{activeSeamIDs:result.activeSeamIDs}:{}),membraneModel:'orthotropic-paper',paperMaterial:{warpNPerM:2000,weftNPerM:1200,shearNPerM:300},bendTopology:'within-piece-flat'});cloth.enabled=false;barePelvis.mesh.visible=true;for(const p of sourcePants)p.material.visible=false;api.fitStatus=result.status;api.paperAudit=evaluatePaperSurface(compilePaperSurfaceModel(result.draft),cloth.positions,cloth.quotient);api.inspectTriangleCrossings=()=>inspectShortsTriangleCrossings(cloth,measuredBody,barePelvis);document.getElementById('paper-state').textContent=`${cloth.activeSeams.length}/19条缝闭合 · 布片应变 ${(100*api.paperAudit.maximumPrincipalStrain).toFixed(2)}% · 穿着未通过`;api.setView('front');return result;
 }).catch(error=>{api.fitStatus='HOLD_RESEARCH_ERROR';api.fitFailure=error.message;document.getElementById('paper-state').textContent=error.message;console.error(error);});
 api.setView('front');return api;
}
