// Static source-paper forming, not cloth dynamics or contact/garment acceptance.
// Local/global rigidity principle: Sorkine & Alexa, SGP2007,
// https://igl.ethz.ch/projects/ARAP/arap_web.pdf . Here each source2D triangle
// has its own 3x2 deformation gradient; posed XYZ never defines a rest metric.
import {compilePaperSurfaceModel,evaluatePaperSurface,paperTriangle} from './ShortsPaperSurfaceModel.mjs';
import {evaluatePaperContactBarrier} from './ShortsPaperContactBarrier.mjs';
import {paperFormingStrainBarrierTerms,paperFormingStrainBarrierProduct} from './ShortsPaperBarrierTerms.mjs';
import {compilePaperBendingTopology,paperFormingBendingTerms,paperFormingBendingProduct} from './ShortsPaperBendingTerms.mjs';
import {paperFormingSourceStepDomain} from './ShortsPaperStepDomain.mjs';
import {paperFormingContactStepDomain} from './ShortsPaperContactStepDomain.mjs';
import {evaluateFiniteSeamConstraint} from './ShortsPaperSeamMultipliers.mjs';
import {createShortsPaperBlockPreconditioner} from './ShortsPaperBlockPreconditioner.mjs';
const dot=(a,b)=>a.reduce((s,v,k)=>s+v*b[k],0),finite=v=>Array.from(v).every(Number.isFinite);
const MAX_OUTER=80,MAX_CG=300,MAX_WALL_MS=30000,CG_RELATIVE=1e-8,PROXIMAL_RELATIVE=1e-8;
export function paperFormingPolar3x2(F){
 if(!Array.isArray(F)||F.length!==2||F.some(c=>c.length!==3||!finite(c)))throw Error('Invalid3x2 source deformation gradient');
 const [u,v]=F,a=dot(u,u),b=dot(u,v),c=dot(v,v),cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],s=Math.hypot(...cross),largest=.5*(a+c+Math.hypot(a-c,2*b)),sigmaMax=Math.sqrt(largest),sigmaMin=s/Math.max(sigmaMax,1e-300),rankTolerance=1e-10*Math.max(1,sigmaMax);
 if(![a,b,c,s,sigmaMin,sigmaMax].every(Number.isFinite)||sigmaMin<=rankTolerance)return{status:'HOLD',reason:'Rank-deficient current surface gradient',sigmaMin,sigmaMax,rankTolerance};
 // For SPD G, sqrt(G)=(G+sqrt(detG)I)/sqrt(traceG+2sqrt(detG)).
 // det(G+sI)=s*(traceG+2s), avoiding cancellation a*c-b*b.
 const q=Math.sqrt(a+c+2*s),den=s*(a+c+2*s),i00=q*(c+s)/den,i01=-q*b/den,i11=q*(a+s)/den;
 const R=[u.map((t,k)=>i00*t+i01*v[k]),u.map((t,k)=>i01*t+i11*v[k])],orthogonalityError=Math.max(Math.abs(dot(R[0],R[0])-1),Math.abs(dot(R[1],R[1])-1),Math.abs(dot(R[0],R[1])));
 if(!R.every(finite)||orthogonalityError>1e-7)return{status:'HOLD',reason:'Polar linear algebra unresolved',sigmaMin,sigmaMax,rankTolerance,orthogonalityError};
 return{status:'POLAR_VALID',R,sigmaMin,sigmaMax,orthogonalityError,squaredDistance:Math.max(0,(sigmaMin-1)**2+(sigmaMax-1)**2),orientationAuthority:'oriented3x2 columns; cross(Ru,Rv) follows current cross(Fu,Fv); no invented third-axis rest or normal'};
}
export function paperFormingSeamSpringTerms(positions,seamSprings,options={}){return evaluateFiniteSeamConstraint(positions,seamSprings,options);}
export function paperFormingPositionalGuideTerms(positions,positionalGuides,{withGradients=true}={}){
 const gradients=withGradients?positions.map(()=>[0,0,0]):null;let energyM2=0,maximumGuideGapM=0;
 for(const g of positionalGuides){if(!Number.isInteger(g.id)||g.id<0||g.id>=positions.length||!g.target||g.target.length!==3||!finite(g.target)||!(Number.isFinite(g.weight)&&g.weight>0))throw Error('Invalid finite static positional guide');const d=positions[g.id].map((v,k)=>v-g.target[k]);if(!finite(d))throw Error('Nonfinite positional guide positions');maximumGuideGapM=Math.max(maximumGuideGapM,Math.hypot(...d));energyM2+=.5*g.weight*dot(d,d);if(withGradients)for(let k=0;k<3;k++)gradients[g.id][k]+=g.weight*d[k];}
 if(!Number.isFinite(energyM2)||gradients?.some(g=>!finite(g)))throw Error('Nonfinite derived positional guide terms');
 return{energyM2,maximumGuideGapM,gradients};
}
export function paperFormingContactTerms(positions,contact,{withGradients=true,withRows=true,deadlineMs=Infinity}={}){
 const gradients=withGradients?positions.map(()=>[0,0,0]):null,diagonalXYZ=new Float64Array(positions.length*3),rows=[];
 if(contact===null||contact===undefined)return{status:'CONTACT_VALID',energyM2:0,maximumViolationM:0,squaredViolationSumM2:0,minimumSignedDistanceM:null,violatingSamples:0,samples:0,gradients,diagonalXYZ,rows,worst:null};
 if(typeof contact.query!=='function'||!Array.isArray(contact.samples)||!(Number.isFinite(contact.clearanceM)&&contact.clearanceM>0)||!(Number.isFinite(contact.weight)&&contact.weight>0)||![undefined,'finite-restoration','feasible-barrier'].includes(contact.mode))throw Error('Explicit finite contact query, samples, clearance and weight required');
 let energyM2=0,maximumViolationM=0,squaredViolationSumM2=0,minimumSignedDistanceM=Infinity,violatingSamples=0,worst=null;const sampleDistances=new Float64Array(contact.samples.length);
 for(let index=0;index<contact.samples.length;index++){
  if(performance.now()>=deadlineMs)return{status:'HOLD',reason:'bounded contact query wall budget exhausted',sample:index};
  const sample=contact.samples[index];if(!sample||!Array.isArray(sample.indices)||!Array.isArray(sample.weights)||!sample.indices.length||sample.indices.length!==sample.weights.length||sample.indices.some(i=>!Number.isInteger(i)||i<0||i>=positions.length)||sample.weights.some(w=>!Number.isFinite(w)||w<=0)||Math.abs(sample.weights.reduce((s,w)=>s+w,0)-1)>1e-10)throw Error('Invalid actual quotient contact sample');
  const combined=new Map();sample.indices.forEach((id,i)=>combined.set(id,(combined.get(id)??0)+sample.weights[i]));const entries=[...combined],point=[0,1,2].map(k=>entries.reduce((s,[id,w])=>s+w*positions[id][k],0));if(!finite(point))return{status:'HOLD',reason:'nonfinite actual contact sample',sample:index};
  const hit=contact.query(point.slice());if(!hit||typeof hit.signAmbiguous!=='boolean'||hit.signAmbiguous||!Number.isFinite(hit.signedDistanceM)||!hit.normal||hit.normal.length!==3||!finite(hit.normal)||Math.abs(Math.hypot(...hit.normal)-1)>1e-7)return{status:'HOLD',reason:'ambiguous or invalid actual signed contact query',sample:index,point,query:hit??null};
  if(contact.distanceAuthority==='fixed-unsigned-surface-set'&&(!Number.isInteger(contact.geometryRevision)||hit.geometryRevision!==contact.geometryRevision||hit.bareGeometryRevision!==contact.bareGeometryRevision||hit.contactMode!=='fixed-unsigned-surface-obstacle-with-independent-closed-bare-membership'))return{status:'HOLD',reason:'fixed actual surface authority or revision changed',sample:index};
  sampleDistances[index]=hit.signedDistanceM;const normal=Array.from(hit.normal),residual=Math.max(0,contact.clearanceM-hit.signedDistanceM);minimumSignedDistanceM=Math.min(minimumSignedDistanceM,hit.signedDistanceM);squaredViolationSumM2+=residual*residual;
  if(residual>maximumViolationM){maximumViolationM=residual;worst={sample:index,indices:sample.indices.slice(),weights:sample.weights.slice(),point,signedDistanceM:hit.signedDistanceM,normal:normal.slice(),violationM:residual};}
  if(contact.mode==='feasible-barrier'){
   const b=evaluatePaperContactBarrier(hit.signedDistanceM,{clearanceM:contact.clearanceM,activationDistanceM:contact.activationDistanceM,weight:contact.weight});if(b.status==='HOLD')return{status:'HOLD',reason:'strict sampled contact barrier domain unresolved',sample:index,query:hit};energyM2+=b.energyM2;
   if(b.secondDerivative>0){if(withRows)rows.push({entries,normal,residual:-b.derivativeM/contact.weight,curvature:b.secondDerivative/contact.weight,sample:index});for(const[id,w]of entries)for(let k=0;k<3;k++){if(withGradients)gradients[id][k]+=b.derivativeM*w*normal[k];diagonalXYZ[id*3+k]+=b.secondDerivative*w*w*normal[k]*normal[k];}}
  }else if(residual>0){violatingSamples++;if(withRows)rows.push({entries,normal,residual,sample:index});for(const[id,w]of entries)for(let k=0;k<3;k++){if(withGradients)gradients[id][k]-=contact.weight*residual*w*normal[k];diagonalXYZ[id*3+k]+=contact.weight*w*w*normal[k]*normal[k];}}
 }
 if(contact.mode!=='feasible-barrier')energyM2=.5*contact.weight*squaredViolationSumM2;if(!Number.isFinite(energyM2)||!finite(diagonalXYZ)||gradients?.some(g=>!finite(g)))return{status:'HOLD',reason:'nonfinite derived actual contact terms'};
 return{status:'CONTACT_VALID',energyM2,maximumViolationM,squaredViolationSumM2,minimumSignedDistanceM:Number.isFinite(minimumSignedDistanceM)?minimumSignedDistanceM:null,violatingSamples,samples:contact.samples.length,gradients,diagonalXYZ,rows,worst,sampleDistances};
}
export function paperFormingContactProduct(rows,vector,weight){
 const out=new Float64Array(vector.length);for(const r of rows){let projected=0;for(const[id,w]of r.entries)for(let axis=0;axis<3;axis++)projected+=w*r.normal[axis]*vector[id*3+axis];for(const[id,w]of r.entries)for(let axis=0;axis<3;axis++)out[id*3+axis]+=weight*(r.curvature??1)*w*r.normal[axis]*projected;}return out;
}
export function createShortsPaperForming({draft,positions,sourceToDof=null,activeSeamIds=null,seamSprings=[],targetGapM=1e-4,positionalGuides=[],contact=null,strainBarrier=null,bending=null}){
 const started=performance.now(),sourceUV=draft.sourceUV??draft.uv??draft.uvs,model=compilePaperSurfaceModel({...draft,sourceUV});if(model.status!=='SOURCE_METRIC_VALID')throw Error('Invalid source paper metric or seam authority');
 const map=sourceToDof?Array.from(sourceToDof):Array.from({length:model.sourceVertices},(_,i)=>i);if(map.length!==model.sourceVertices||map.some(i=>!Number.isInteger(i)||i<0))throw Error('Invalid original seam quotient');
 const count=Math.max(...map)+1;if(count>2000)throw Error('Source forming supports at most2000 actual DOFs');const sourceMass=Array.from(draft.mass??[]);if(sourceMass.length!==model.sourceVertices||sourceMass.some(m=>!Number.isFinite(m)||m<=0))throw Error('Positive unchanged actual source masses required');
 const mass=Array(count).fill(0);map.forEach((id,i)=>mass[id]+=sourceMass[i]);if(mass.some(m=>m<=0))throw Error('Sparse or massless seam quotient');
 const seamSet=new Set(activeSeamIds??(draft.seams??[]).map(s=>s.id));for(const id of seamSet)if(!(draft.seams??[]).some(s=>s.id===id))throw Error('Unknown active source seam');for(const s of draft.seams??[])if(seamSet.has(s.id))for(const p of s.pairs)if(map[p.a]!==map[p.b])throw Error('Active original seam quotient is not joined');
 const nested=Array.isArray(positions?.[0])?positions:Array.from({length:count},(_,i)=>Array.from(positions??[]).slice(i*3,i*3+3));if(nested.length!==count||nested.some(p=>p.length!==3||!finite(p)))throw Error('Expected actual quotient XYZ in one metre frame');
 if(targetGapM!==1e-4)throw Error('Static source sewing freezes its declared0.1mm gap gate');
 let x=nested.map(p=>Array.from(p));const seed=x.map(p=>p.slice()),springs=seamSprings.map(s=>({...s}));paperFormingSeamSpringTerms(x,springs,{withGradients:false});paperFormingPositionalGuideTerms(x,positionalGuides,{withGradients:false});const guides=positionalGuides.map(g=>({...g,target:Array.from(g.target)})),guideIdentity=JSON.stringify(positionalGuides),springIdentity=JSON.stringify(seamSprings),contactQuery=contact?.query,contactIdentity=JSON.stringify(contact),reference=JSON.stringify({uv:sourceUV,triangles:draft.triangles,mass:draft.mass,seams:draft.seams,map,activeSeamIds:[...seamSet]}),inputPositions=JSON.stringify(positions),strainBarrierIdentity=JSON.stringify(strainBarrier),bendingIdentity=JSON.stringify(bending);
 const triangles=model.triangles.map(t=>{const r=paperTriangle(t.reference.uv),combined=new Map();t.ids.forEach((source,i)=>{const id=map[source],g=[r.warpCoefficients[i],r.weftCoefficients[i]],old=combined.get(id)??[0,0];combined.set(id,[old[0]+g[0],old[1]+g[1]]);});return{ids:t.ids,area:r.areaM2,entries:[...combined]};});
 const bendingTopology=compilePaperBendingTopology(model,map,bending);
 const diag=Array(count).fill(0);for(const t of triangles)for(const[id,g]of t.entries)diag[id]+=t.area*dot(g,g);
 const totalMass=mass.reduce((s,m)=>s+m,0),traceK=diag.reduce((s,v)=>s+v,0),mu=PROXIMAL_RELATIVE*traceK/totalMass;if(!(mu>0&&Number.isFinite(mu)))throw Error('Invalid source global gauge coefficient');diag.forEach((v,i)=>diag[i]=v+mu*mass[i]);for(const s of springs){diag[s.a]+=s.weight;diag[s.b]+=s.weight;}for(const g of guides)diag[g.id]+=g.weight;
 let lastCurrentEnergy=null;const evaluateBase=(p,needRotations=false)=>{let paperEnergyM2=0,proximalEnergyM2=0,maximumPolarError=0;const rotations=[];for(let k=0;k<triangles.length;k++){const t=triangles[k],F=[[0,0,0],[0,0,0]];for(const[id,g]of t.entries)for(let axis=0;axis<3;axis++){F[0][axis]+=g[0]*p[id][axis];F[1][axis]+=g[1]*p[id][axis];}const polar=paperFormingPolar3x2(F);if(polar.status==='HOLD')return{status:'HOLD',reason:polar.reason,triangle:k,sourceIndices:t.ids,...polar};paperEnergyM2+=.5*t.area*polar.squaredDistance;maximumPolarError=Math.max(maximumPolarError,polar.orthogonalityError);if(needRotations)rotations.push({F,R:polar.R});}for(let i=0;i<count;i++)for(let axis=0;axis<3;axis++)proximalEnergyM2+=.5*mu*mass[i]*(p[i][axis]-seed[i][axis])**2;const strain=paperFormingStrainBarrierTerms(p,triangles,strainBarrier,{withRows:needRotations});if(strain.status==='HOLD')return strain;const soft=paperFormingSeamSpringTerms(p,springs,{withGradients:false}),placement=paperFormingPositionalGuideTerms(p,guides,{withGradients:false}),actualContact=paperFormingContactTerms(p,contact,{withGradients:false,withRows:needRotations,deadlineMs:started+MAX_WALL_MS});if(actualContact.status==='HOLD')return actualContact;const result={status:'ENERGY_VALID',paperEnergyM2,proximalEnergyM2,seamSpringEnergyM2:soft.energyM2,maximumSoftGapM:soft.maximumSoftGapM,positionalGuideEnergyM2:placement.energyM2,maximumGuideGapM:placement.maximumGuideGapM,totalEnergyM2:paperEnergyM2+proximalEnergyM2+soft.energyM2+placement.energyM2+actualContact.energyM2+strain.energyM2,strainBarrierEnergyM2:strain.energyM2,strainBarrierRows:strain.rows,strainBarrierDiagonalXYZ:strain.diagonalXYZ,strainBarrierGradients:strain.gradients,contactEnergyM2:actualContact.energyM2,contactMetrics:{samples:actualContact.samples,maximumViolationM:actualContact.maximumViolationM,squaredViolationSumM2:actualContact.squaredViolationSumM2,minimumSignedDistanceM:actualContact.minimumSignedDistanceM,violatingSamples:actualContact.violatingSamples,worst:actualContact.worst},contactRows:actualContact.rows,contactSampleDistances:actualContact.sampleDistances,contactDiagonalXYZ:needRotations?actualContact.diagonalXYZ:undefined,maximumPolarError,rotations};return result;};
 const evaluate=(p,needRotations=false)=>{
  const e=evaluateBase(p,needRotations);if(e.status==='HOLD')return e;
  const b=paperFormingBendingTerms(p,bendingTopology,{withRows:needRotations});if(b.status==='HOLD')return b;
  const result={...e,totalEnergyM2:e.totalEnergyM2+b.energyM2,bendingEnergyM2:b.energyM2,bending:{provided:bending!==null,hinges:b.hinges,maximumAbsoluteAngleRadians:b.maximumAbsoluteAngleRadians,worst:b.worst,energyM2:b.energyM2,stiffnessNm:bending?.stiffnessNm??null,membraneScaleNPerM:bending?.membraneScaleNPerM??null,seamLaw:bending?.seamLaw??null,matrixAuthority:b.matrixAuthority,physicalCalibrated:false}};
  Object.defineProperties(result,{bendingRows:{value:b.rows},bendingDiagonalXYZ:{value:b.diagonalXYZ},bendingGradients:{value:b.gradients}});
  if(p===x)lastCurrentEnergy=result;return result;
 };
 const multiply=(v,contactRows=[],strainRows=[],bendingRows=[])=>{const out=Float64Array.from(v,(value,k)=>value*mu*mass[Math.floor(k/3)]);for(const t of triangles)for(let axis=0;axis<3;axis++){let fu=0,fv=0;for(const[id,g]of t.entries){fu+=g[0]*v[3*id+axis];fv+=g[1]*v[3*id+axis];}for(const[id,g]of t.entries)out[3*id+axis]+=t.area*(g[0]*fu+g[1]*fv);}for(const s of springs)for(let axis=0;axis<3;axis++){const value=s.weight*(v[s.a*3+axis]-v[s.b*3+axis]);out[s.a*3+axis]+=value;out[s.b*3+axis]-=value;}for(const g of guides)for(let axis=0;axis<3;axis++)out[g.id*3+axis]+=g.weight*v[g.id*3+axis];if(bendingRows.length){const extra=paperFormingBendingProduct(bendingRows,v);for(let k=0;k<out.length;k++)out[k]+=extra[k];}if(strainRows.length){const extra=paperFormingStrainBarrierProduct(strainRows,v);for(let k=0;k<out.length;k++)out[k]+=extra[k];}if(contactRows.length){const extra=paperFormingContactProduct(contactRows,v,contact.weight);for(let k=0;k<out.length;k++)out[k]+=extra[k];}return out;};
 const contactEnabled=contact!==null&&contact.samples.length>0;const audit=p=>evaluatePaperSurface(model,p,map,{strainLimit:.05}),initial=audit(x),initialEnergy=evaluate(x);let stop=initialEnergy.status==='HOLD'?initialEnergy.reason:null,iterations=0;const trace=[];
 const unchanged=()=>{if(reference!==JSON.stringify({uv:draft.sourceUV??draft.uv??draft.uvs,triangles:draft.triangles,mass:draft.mass,seams:draft.seams,map,activeSeamIds:[...seamSet]})||inputPositions!==JSON.stringify(positions)||springIdentity!==JSON.stringify(seamSprings)||guideIdentity!==JSON.stringify(positionalGuides)||contactIdentity!==JSON.stringify(contact)||contactQuery!==contact?.query||strainBarrierIdentity!==JSON.stringify(strainBarrier)||bendingIdentity!==JSON.stringify(bending))throw Error('Caller changed original source or input positions during forming');};
 const rhsFor=(p,current)=>{
  const rhs=new Float64Array(count*3);for(let k=0;k<triangles.length;k++){const t=triangles[k],{F,R}=current.rotations[k];for(const[id,g]of t.entries)for(let axis=0;axis<3;axis++)rhs[id*3+axis]+=t.area*(g[0]*(R[0][axis]-F[0][axis])+g[1]*(R[1][axis]-F[1][axis]));}for(let i=0;i<count;i++)for(let axis=0;axis<3;axis++)rhs[i*3+axis]-=mu*mass[i]*(p[i][axis]-seed[i][axis]);
  for(const s of springs)for(let axis=0;axis<3;axis++){const value=s.weight*(p[s.a][axis]-p[s.b][axis])+(s.multiplier?.[axis]??0);rhs[s.a*3+axis]-=value;rhs[s.b*3+axis]+=value;}
  for(const g of guides)for(let axis=0;axis<3;axis++)rhs[g.id*3+axis]-=g.weight*(p[g.id][axis]-g.target[axis]);
  for(let id=0;id<count;id++)for(let axis=0;axis<3;axis++)rhs[id*3+axis]-=current.strainBarrierGradients[id][axis]+current.bendingGradients[id][axis];
  for(const r of current.contactRows)for(const[id,w]of r.entries)for(let axis=0;axis<3;axis++)rhs[id*3+axis]+=contact.weight*r.residual*w*r.normal[axis];
  return rhs;
 };
 const snapshotBase=()=>{unchanged();const final=audit(x),contactQueryBudgetExhausted=performance.now()-started>=MAX_WALL_MS,e=lastCurrentEnergy??evaluate(x);return{schema:'shorts-source-paper-forming@1',status:final.status==='METRIC_VALID_ONLY'&&e.status==='ENERGY_VALID'&&e.maximumSoftGapM<=targetGapM?'SOURCE_METRIC_FORMED_ONLY':'HOLD',positions:x.map(p=>p.slice()),initial,final,initialEnergy:{...initialEnergy,rotations:undefined,contactRows:undefined,contactSampleDistances:undefined,contactDiagonalXYZ:undefined,strainBarrierRows:undefined,strainBarrierDiagonalXYZ:undefined,strainBarrierGradients:undefined},finalEnergy:{...e,rotations:undefined,contactRows:undefined,contactDiagonalXYZ:undefined,strainBarrierRows:undefined,strainBarrierDiagonalXYZ:undefined,strainBarrierGradients:undefined},iterations,trace:trace.map(t=>({...t})),stopReason:stop??'not run',limits:{outer:MAX_OUTER,cg:MAX_CG,wallMs:MAX_WALL_MS},elapsedMs:performance.now()-started,gauge:{massProximalCoefficientPerKg:mu,relativeDiagonalScale:PROXIMAL_RELATIVE,authority:'fixed weak numerical SPD/gauge only; not cloth stiffness or source rest; seed XYZ is a proximal centre only'},source:{vertices:model.sourceVertices,dofs:count,triangles:triangles.length,activeSeams:seamSet.size,sourceAreaM2:model.areaM2,totalActualMassKg:totalMass,sourceUVRestMassQuotientUnchanged:true,sourceRestFromXYZ:false},strainBarrier:{provided:strainBarrier!==null,mu:strainBarrier?.mu??null,principalLimit:.05,energyM2:e.strainBarrierEnergyM2??null,matrixAuthority:'PSD metric pullback, not exact XYZ Hessian',physicalCalibrated:false},softSeams:{springs:springs.length,maximumGapM:e.maximumSoftGapM??null,targetGapM,law:'finite static authoring quadratic, not calibrated needle/thread/native law',weightUnits:'dimensionless energy coefficient for squared metre gap',restFromXYZ:false,sourceToDofUnchanged:true},positionalGuides:{count:guides.length,maximumGapM:e.maximumGuideGapM??null,energyM2:e.positionalGuideEnergyM2??null,law:'finite static placement quadratic; not body contact, permanent pin, calibration or source rest',targetRestFromXYZ:false,placementValidated:false,metricEarlyStopDisabled:guides.length>0},contact:{provided:contact!==null,sampleMetrics:e.contactMetrics??null,weight:contact?.weight??null,clearanceM:contact?.clearanceM??null,energyM2:e.contactEnergyM2??null,metricEarlyStopDisabled:contactEnabled,queryBudgetExhausted:contactQueryBudgetExhausted,metricsAuthority:'last same-position true evaluation, fixed supplied contact revision; no extra snapshot queries',scope:'provided actual point/centroid signed queries only; no full-triangle/CCD/volume certificate',sampledContactPassed:contactEnabled&&e.contactMetrics?.maximumViolationM===0,fullTriangleContactValidated:false},bodyConstructed:false,noBody:contact===null,noBendingLaw:true,noElasticCalibration:true,nativeSteps:0,nativeClockAdvanced:false,bodyClearanceValidated:false,selfContactValidated:false,motionValidated:false,wearingAccepted:false};};
 let failureDiagnostics=null;
 let firstOrder=null;const snapshot=()=>({...snapshotBase(),noBendingLaw:bending===null,failureDiagnostics,firstOrder});
 const step=()=>{unchanged();if(stop||iterations>=MAX_OUTER)return snapshot();if(performance.now()-started>=MAX_WALL_MS){stop='bounded wall budget exhausted';return snapshot();}const current=evaluate(x,true);if(current.status==='HOLD'){stop=current.reason;return snapshot();}
  const rhs=rhsFor(x,current);
  let preconditioner;try{preconditioner=createShortsPaperBlockPreconditioner(diag,{contactRows:current.contactRows,contactWeight:contact?.weight??0,strainRows:current.strainBarrierRows,bendingRows:current.bendingRows});}catch(error){stop='numerical block preconditioner unresolved';failureDiagnostics={phase:'preconditioner',reason:error.message};return snapshot();}
  const delta=new Float64Array(count*3),residual=rhs.slice(),z=preconditioner.apply(residual);let direction=z.slice(),rz=dot(residual,z),cgIterations=0,wallStopped=false;const rhsNorm=Math.hypot(...rhs),tolerance=CG_RELATIVE*Math.max(rhsNorm,1e-30);
  for(;cgIterations<MAX_CG&&Math.hypot(...residual)>tolerance;cgIterations++){if(performance.now()-started>=MAX_WALL_MS){wallStopped=true;break;}const product=multiply(direction,current.contactRows,current.strainBarrierRows,current.bendingRows),den=dot(direction,product);if(!(den>0&&Number.isFinite(den))){stop='global SPD linear algebra unresolved';break;}const alpha=rz/den;for(let k=0;k<delta.length;k++){delta[k]+=alpha*direction[k];residual[k]-=alpha*product[k];}z.set(preconditioner.apply(residual));const next=dot(residual,z),beta=next/rz;for(let k=0;k<direction.length;k++)direction[k]=z[k]+beta*direction[k];rz=next;}
  if(stop||wallStopped){stop??='bounded wall budget exhausted';failureDiagnostics={phase:'linear-solve',reason:stop,cgIterations,rhsNorm,recursiveRelativeResidual:Math.hypot(...residual)/Math.max(rhsNorm,1e-30),trueResidualNotEvaluated:true};return snapshot();}
  const analytic=-dot(rhs,delta),actualProduct=multiply(delta,current.contactRows,current.strainBarrierRows,current.bendingRows),actualRelativeResidual=Math.hypot(...actualProduct.map((v,k)=>v-rhs[k]))/Math.max(rhsNorm,1e-30),directionReceipt={cgIterations,rhsNorm,recursiveRelativeResidual:Math.hypot(...residual)/Math.max(rhsNorm,1e-30),actualRelativeResidual,cgConverged:actualRelativeResidual<=CG_RELATIVE,analyticDirectionalDerivative:analytic,maximumAbsoluteDeltaM:Math.max(...delta.map(Math.abs))};
  if(!finite(delta)||!(analytic<0)){stop=rhsNorm<=1e-12?'source energy stationary; five-percent audit decides':'global direction is not finite descent';failureDiagnostics={phase:'direction',reason:stop,...directionReceipt};return snapshot();}
  const domain=strainBarrier===null?{status:'SOURCE_STEP_DOMAIN_BOUND',maximumFraction:1}:paperFormingSourceStepDomain(x,triangles,delta);
  if(domain.status!=='SOURCE_STEP_DOMAIN_BOUND'){stop='strict source direction domain unresolved';failureDiagnostics={phase:'source-step-domain',reason:stop,...directionReceipt,domain};return snapshot();}
  const contactDomain=contact?.distanceAuthority==='fixed-unsigned-surface-set'?paperFormingContactStepDomain(delta,contact.samples,{minimumDistanceM:current.contactMetrics.minimumSignedDistanceM,sampleDistancesM:current.contactSampleDistances,clearanceM:contact.clearanceM}):{status:'SAMPLED_SURFACE_STEP_BOUND',maximumFraction:1};
  if(contactDomain.status!=='SAMPLED_SURFACE_STEP_BOUND'){stop='strict sampled surface path domain unresolved';failureDiagnostics={phase:'contact-step-domain',contactDomain};return snapshot();}
  const safeFraction=Math.min(domain.maximumFraction,contactDomain.maximumFraction);let fraction=0,candidateEnergy=null,nextPositions=null;const rejections=[];
  for(let power=0;power<=20;power++){
   if(performance.now()-started>=MAX_WALL_MS)break;
   const f=safeFraction*2**(-power),candidate=x.map((p,i)=>p.map((v,k)=>v+f*delta[i*3+k])),e=evaluate(candidate),armijoRHS=current.totalEnergyM2+1e-4*f*analytic;
   if(e.status==='ENERGY_VALID'&&e.totalEnergyM2<current.totalEnergyM2&&e.totalEnergyM2<=armijoRHS){fraction=f;candidateEnergy=e;nextPositions=candidate;break;}
   rejections.push({fraction:f,status:e.status,reason:e.status==='HOLD'?e.reason:e.totalEnergyM2>=current.totalEnergyM2?'no representable true energy decrease':'Armijo condition',triangle:e.triangle??null,sourceIndices:e.sourceIndices??null,barrier:e.barrier?{gaps:e.barrier.gaps,sigmaMin:e.barrier.sigmaMin,sigmaMax:e.barrier.sigmaMax}:null,contactSample:e.sample??null,signedDistanceM:e.query?.signedDistanceM??null,totalEnergyM2:e.totalEnergyM2??null,armijoRHS});
  }
  if(!fraction)failureDiagnostics={phase:'backtrack',...directionReceipt,domain,contactDomain,rejections,notAnInfeasibilityCertificate:true};
  if(!fraction){stop='bounded monotone source-energy backtrack unresolved';return snapshot();}x=nextPositions;lastCurrentEnergy=candidateEnergy;iterations++;const acceptedAudit=audit(x);trace.push({iteration:iterations,rhsNorm,cgIterations,cgRelativeResidual:actualRelativeResidual,cgRecursiveRelativeResidual:Math.hypot(...residual)/Math.max(rhsNorm,1e-30),cgConverged:actualRelativeResidual<=CG_RELATIVE,acceptedFraction:fraction,sourceDomainFraction:domain.maximumFraction,contactDomainFraction:contactDomain.maximumFraction,sampledPointPathClearanceOnly:contact?.distanceAuthority==='fixed-unsigned-surface-set',sourceDomainLimitingTriangle:domain.firstLimitingTriangle??null,initialEnergyM2:current.totalEnergyM2,finalEnergyM2:candidateEnergy.totalEnergyM2,paperEnergyM2:candidateEnergy.paperEnergyM2,seamSpringEnergyM2:candidateEnergy.seamSpringEnergyM2,maximumSoftGapM:candidateEnergy.maximumSoftGapM,positionalGuideEnergyM2:candidateEnergy.positionalGuideEnergyM2,maximumGuideGapM:candidateEnergy.maximumGuideGapM,contactEnergyM2:candidateEnergy.contactEnergyM2,bendingEnergyM2:candidateEnergy.bendingEnergyM2,maximumAbsoluteBendingAngleRadians:candidateEnergy.bending.maximumAbsoluteAngleRadians,contactMetrics:candidateEnergy.contactMetrics,maximumPrincipalStrain:acceptedAudit.maximumPrincipalStrain,analyticDirectionalDerivative:analytic});if(acceptedAudit.status==='METRIC_VALID_ONLY'&&candidateEnergy.maximumSoftGapM<=targetGapM&&!guides.length&&!contactEnabled&&bending===null)stop='source five-percent metric and declared soft seam gap passed only; embedding/contact pending';else if(iterations>=MAX_OUTER)stop='bounded outer iteration limit';return snapshot();
 };
 return{step,snapshot,solve({maximumIterations=MAX_OUTER}={}){if(!Number.isInteger(maximumIterations)||maximumIterations<1||maximumIterations>MAX_OUTER)throw Error('At most80 source forming iterations');while(!stop&&iterations<maximumIterations)step();if(!stop)stop='requested bounded outer iteration limit';if(performance.now()-started<MAX_WALL_MS){const e=evaluate(x,true);if(e.status==='ENERGY_VALID'){const g=rhsFor(x,e);firstOrder={gradientNormM:Math.hypot(...g),maximumAbsoluteGradientM:Math.max(...g.map(Math.abs)),authority:'actual complete fixed-inner authoring merit gradient; not physical force or KKT certificate'};}}return snapshot();}};
}
export function formShortsPaperSurface(input,options={}){return createShortsPaperForming(input).solve(options);}
