import {add,sub,mul,dot,length,unit,cross,quantile} from './AnatomyMath.mjs';

// Project-owned inverse fitting, with observed skin constraints and explicit priors.
// This does not infer measured bone diameter or hidden anatomy from skin weights.
export const INVERSE_SEGMENTS=[
 ['abdomen','腹腰','pelvis','spineMiddle','torso'],['thorax','胸廓','spineMiddle','neck','torso'],
 ['neck','颈','neck','head','neck'],['head','头','head','$top','head'],
 ...['l','r'].flatMap(s=>[['upperarm_'+s,'上臂','upperarm_'+s,'lowerarm_'+s,'upperarm_'+s],['lowerarm_'+s,'前臂','lowerarm_'+s,'hand_'+s,'lowerarm_'+s],['hand_'+s,'手掌','hand_'+s,'middle_1_'+s,'hand_'+s],['thigh_'+s,'大腿','thigh_'+s,'calf_'+s,'thigh_'+s],['calf_'+s,'小腿','calf_'+s,'foot_'+s,'calf_'+s],['foot_'+s,'足','foot_'+s,'ball_'+s,'foot_'+s]])
];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function solve(A,b){const n=b.length,m=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let pivot=k;for(let i=k+1;i<n;i++)if(Math.abs(m[i][k])>Math.abs(m[pivot][k]))pivot=i;if(Math.abs(m[pivot][k])<1e-12)return null;[m[pivot],m[k]]=[m[k],m[pivot]];const d=m[k][k];for(let j=k;j<=n;j++)m[k][j]/=d;for(let i=0;i<n;i++)if(i!==k){const f=m[i][k];for(let j=k;j<=n;j++)m[i][j]-=f*m[k][j];}}return m.map(r=>r[n]);}

export function fitSurfaceEllipse(points){
 if(points.length<24)return {status:'insufficient-samples',samples:points.length};
 const scale=quantile(points.map(p=>Math.hypot(...p)),.5);if(!(scale>1e-9))return {status:'degenerate-section',samples:points.length};
 const rows=points.filter(p=>Math.hypot(...p)<scale*2.5).map(p=>p.map(v=>v/scale)),bins=new Array(24).fill(0),bin=p=>Math.min(23,Math.floor((Math.atan2(p[1],p[0])+Math.PI)/(2*Math.PI)*24));for(const p of rows)bins[bin(p)]++;
 const coverage=bins.filter(n=>n>0).length/24;if(coverage<.625)return {status:'partial-angular-coverage',samples:rows.length,coverage};
 let robust=rows.map(()=>1),q=null;
 for(let iter=0;iter<4;iter++){const A=Array.from({length:5},()=>new Array(5).fill(0)),b=new Array(5).fill(0);for(let i=0;i<rows.length;i++){const [x,y]=rows[i],f=[x*x,x*y,y*y,x,y],w=robust[i]/bins[bin(rows[i])];for(let k=0;k<5;k++){b[k]+=w*f[k];for(let j=0;j<5;j++)A[k][j]+=w*f[k]*f[j];}}q=solve(A,b);if(!q)return {status:'singular-section',samples:rows.length,coverage};const errors=rows.map(([x,y])=>Math.abs(q[0]*x*x+q[1]*x*y+q[2]*y*y+q[3]*x+q[4]*y-1)),mad=Math.max(.03,quantile(errors,.5)*1.4826);robust=errors.map(e=>Math.min(1,1.5*mad/Math.max(e,1e-9)));}
 const [a,b,c,d,e]=q,det=a*c-b*b/4;if(a<=0||c<=0||det<=1e-8)return {status:'non-elliptic-section',samples:rows.length,coverage};
 const cx=-(c*d-b*e/2)/(2*det),cy=-(a*e-b*d/2)/(2*det),k=1+a*cx*cx+b*cx*cy+c*cy*cy,delta=Math.hypot(a-c,b),large=(a+c+delta)/2,small=(a+c-delta)/2;
 if(!(small>0&&k>0))return {status:'invalid-ellipse',samples:rows.length,coverage};
 const rx=scale*Math.sqrt(k/large),ry=scale*Math.sqrt(k/small),centre=[cx*scale,cy*scale],angle=.5*Math.atan2(b,a-c),ca=Math.cos(angle),sa=Math.sin(angle),residuals=points.map(p=>{const x=p[0]-centre[0],y=p[1]-centre[1],u=x*ca+y*sa,v=-x*sa+y*ca;return Math.abs(Math.hypot(u/rx,v/ry)-1)*Math.min(rx,ry);});
 if(Math.hypot(...centre)>scale*1.5||ry/rx>5)return {status:'unstable-ellipse',samples:rows.length,coverage};
 const relative=points.map(p=>[p[0]-centre[0],p[1]-centre[1]]),actualBins=new Set(relative.map(bin)),actualCoverage=actualBins.size/24,projected=relative.map(([x,y])=>[x*ca+y*sa,-x*sa+y*ca]),spans=[0,1].map(i=>{const a=projected.map(p=>p[i]);return quantile(a,.99)-quantile(a,.01);});
 if(actualCoverage<.625||rx*2>spans[0]*1.35||ry*2>spans[1]*1.35)return {status:'partial-fitted-ellipse',samples:rows.length,coverage:actualCoverage};
 return {status:'fitted',centre,axes:[rx,ry],angle,samples:rows.length,coverage:actualCoverage,rms:Math.sqrt(residuals.reduce((s,e)=>s+e*e,0)/residuals.length),p95:quantile(residuals,.95),evidence:'observed-skin-section-fit'};
}

function fitLine(rows,axis){const sw=rows.reduce((s,r)=>s+r.weight,0),st=rows.reduce((s,r)=>s+r.weight*r.t,0),stt=rows.reduce((s,r)=>s+r.weight*r.t*r.t,0),sy=rows.reduce((s,r)=>s+r.weight*r.offset[axis],0),sty=rows.reduce((s,r)=>s+r.weight*r.t*r.offset[axis],0),det=sw*stt-st*st;if(det<1e-10)return [sy/Math.max(sw,1e-9),0];return [(sy*stt-sty*st)/det,(sty*sw-sy*st)/det];}

export function reverseFitSkeleton(profile,{positions,materialIds,materialRegions,maxSamples=180000,sections=12}={}){
 if(!profile?.canDeform||!profile.frame)throw Error('Inverse fit requires unambiguous subject axes and semantic landmarks');
 if(!positions?.length||positions.length%3||!materialIds||materialIds.length!==positions.length/3||!materialRegions)throw Error('Inverse fit needs current skin data and source-specific material semantics');
 if(!Number.isInteger(maxSamples)||maxSamples<100||!Number.isInteger(sections)||sections<6||sections>48)throw Error('Invalid inverse sampling resolution');
 const h=profile.frame.height,origin=profile.frame.origin,top=add(origin,mul(profile.frame.up,profile.frame.top)),pos=r=>r==='$top'?top:profile.joints[profile.roles[r]]?.position;
 const drafts=INVERSE_SEGMENTS.filter(([, ,a,b])=>pos(a)&&pos(b)).map(([id,label,a,b,region])=>{const start=pos(a),end=pos(b),d=sub(end,start),L=length(d),axis=unit(d),ref=Math.abs(dot(axis,profile.frame.front))<.9?profile.frame.front:profile.frame.right,u=unit(cross(axis,ref)),v=unit(cross(axis,u));return {id,label,startRole:a,endRole:b,region,start:[...start],end:[...end],axis,u,v,length:L,bins:Array.from({length:sections},()=>[])};});
 const stride=Math.max(1,Math.ceil(positions.length/3/maxSamples));let sampled=0,excluded=0;
 for(let i=0;i<positions.length/3;i+=stride){const p=Array.from(positions.subarray(i*3,i*3+3));if(!p.every(Number.isFinite))throw Error('Non-finite skin sample');const region=materialRegions[materialIds[i]];if(!region||region==='clothing'){excluded++;continue;}sampled++;
  for(const d of drafts){if(d.region!==region&&!(region==='knee_'+d.id.at(-1)&&/^(thigh|calf)_/.test(d.id)))continue;const q=sub(p,d.start),t=dot(q,d.axis)/d.length;if(t<.025||t>.975)continue;const planar=[dot(q,d.u),dot(q,d.v)];if(Math.hypot(...planar)>Math.min(h*.18,d.length*.8))continue;d.bins[Math.min(sections-1,Math.floor(t*sections))].push(planar);}
 }
 const contributions=Array.from({length:profile.joints.length},()=>[]),segments=[];
 for(const d of drafts){const rows=d.bins.map((points,i)=>{const t=(i+.5)/sections,f=fitSurfaceEllipse(points),priorCentre=add(d.start,mul(sub(d.end,d.start),t));if(f.status==='fitted'&&(f.rms/Math.min(...f.axes)>.15||f.p95/Math.min(...f.axes)>.40))f.status='needs-review-non-elliptic-skin';return {...f,t,priorCentre,centre:f.centre?add(add(priorCentre,mul(d.u,f.centre[0])),mul(d.v,f.centre[1])):null};}),valid=rows.filter(r=>r.status==='fitted'),reg=valid.map(r=>({t:r.t,offset:r.centre.map((v,k)=>v-r.priorCentre[k]),weight:r.coverage/Math.max(.05,(r.rms/Math.min(...r.axes))**2)}));
  const span=valid.length?valid.at(-1).t-valid[0].t:0,first=valid[0]?.t??1,last=valid.at(-1)?.t??0;
  // Joint candidates use only nearby skin: a muscle belly must not drag a joint.
  const endpoint=(t,role)=>{const near=reg.filter(r=>Math.abs(r.t-t)<.30),observed=valid.length>=4&&span>.25&&near.length>=2&&(t===0?first<.22:last>.78)&&!(/^hand_/.test(d.id)&&t===1);if(!observed)return {position:t===0?d.start:d.end,status:'prior-only-no-local-surface',weight:0};const line=[0,1,2].map(k=>fitLine(near,k)),raw=line.map(c=>c[0]+t*c[1]),limit=Math.min(h*.04,d.length*.20),dist=length(raw),delta=mul(raw,Math.min(1,limit/Math.max(dist,1e-12))),position=add(t===0?d.start:d.end,delta),weight=near.length;const id=profile.roles[role];if(Number.isInteger(id))contributions[id].push({position,weight,segment:d.id,bounded:dist>limit});return {position,status:dist>limit?'surface-fit-bounded-by-prior':'surface-constrained-estimate',weight};};
  const a=endpoint(0,d.startRole),b=endpoint(1,d.endRole),status=valid.length>=4&&span>.25?'surface-fitted':'insufficient-local-surface';segments.push({id:d.id,label:d.label,startRole:d.startRole,endRole:d.endRole,priorStart:d.start,priorEnd:d.end,priorLength:d.length,start:a.position,end:b.position,length:length(sub(b.position,a.position)),startStatus:a.status,endStatus:b.status,status,axis:d.axis,u:d.u,v:d.v,sections:rows,observedSections:valid.length,totalSections:sections,coverage:valid.length/sections,sectionSpan:span,medianSkinRadius:valid.length?quantile(valid.map(r=>Math.sqrt(r.axes[0]*r.axes[1])),.5):null,rms:valid.length?Math.sqrt(valid.reduce((s,r)=>s+r.rms*r.rms,0)/valid.length):null,p95:valid.length?quantile(valid.map(r=>r.p95),.95):null,evidence:'surface-constrained-inverse-estimate',boneDiameter:'NotObserved'});
 }
 const joints=profile.joints.map((j,i)=>{const rows=contributions[i],total=rows.reduce((s,r)=>s+r.weight,0),position=total?j.position.map((_,k)=>rows.reduce((s,r)=>s+r.weight*r.position[k],0)/total):[...j.position],disagreement=rows.length>1?Math.max(...rows.map(r=>length(sub(r.position,position)))):0,needsReview=disagreement>h*.006||rows.some(r=>r.bounded);return {name:j.name,parent:j.parent,priorPosition:[...j.position],position,shift:length(sub(position,j.position)),status:total?(needsReview?'surface-constrained-estimate-needs-review':'surface-constrained-estimate'):'prior-only',sources:rows.map(r=>r.segment),uncertainty:{sectionModelDisagreement:disagreement,priorBoundReached:rows.some(r=>r.bounded),internalJointCentre:'NotObserved'}};});
 for(const s of segments){const a=profile.roles[s.startRole],b=profile.roles[s.endRole];if(Number.isInteger(a))s.start=[...joints[a].position];if(Number.isInteger(b))s.end=[...joints[b].position];s.length=length(sub(s.end,s.start));if(s.length<s.priorLength*.7||s.length>s.priorLength*1.3){s.status='needs-review-length-change';}}
 return {schema:'human/surface-inverse-skeleton@1',sourceId:profile.sourceId,unit:profile.unit,frame:profile.frame,method:'angular-balanced-robust-conic-sections-local-endpoints-and-coupled-joint-centres',status:segments.some(s=>s.status==='surface-fitted')?'candidate-surface-fit':'needs-review',surfaceSamples:sampled,excludedSamples:excluded,samplingStride:stride,joints,segments,summary:{surfaceFittedSegments:segments.filter(s=>s.status==='surface-fitted').length,totalSegments:segments.length,adjustedJoints:joints.filter(j=>j.status!=='prior-only').length,jointsNeedingReview:joints.filter(j=>j.status.endsWith('needs-review')).length,maximumJointShift:Math.max(...joints.map(j=>j.shift)),rmsSkinSection:Math.sqrt(segments.filter(s=>s.rms!==null).reduce((n,s)=>n+s.rms*s.rms,0)/Math.max(1,segments.filter(s=>s.rms!==null).length))},unknown:['true-bone-surfaces','true-bone-diameters','hidden-hip-and-proximal-thigh','true-muscle-attachments','individual-finger-bone-centres'],internalAccuracy:'estimated-not-uniquely-identifiable',skinUnmodified:true,storedVertexBytes:0};
}
