import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {createShark,createFishGeometry} from './anatomy.js';
import {createOcean,hash} from './ocean.js';
import {createBehavior,parseInstruction,validatePlan,MOTION_LIMITS} from './behavior.js';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),M=THREE.MathUtils;
window.addEventListener('error',e=>{$('loadError').textContent=e.message;});
window.addEventListener('unhandledrejection',e=>{$('loadError').textContent=e.reason?.message||String(e.reason);});
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;$('viewport').append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.05,240);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=2.6;controls.maxDistance=35;controls.maxPolarAngle=Math.PI*.94;controls.target.set(0,-4,0);camera.position.set(3.6,-3.0,6.3);
const ocean=createOcean(scene,renderer),shark=createShark();scene.add(shark.root);ocean.caustics(shark.mat,true);
const fish=[],fishGeo=createFishGeometry(),fishPalette={silver:'#9dbbb9',blue:'#6c9ea6',gold:'#b6a571'},fishMaterials={};for(let k of Object.keys(fishPalette))fishMaterials[k]=new THREE.MeshStandardMaterial({color:fishPalette[k],roughness:.37,metalness:.40,side:THREE.DoubleSide});
let fishSerial=0;function spawn(count){for(let j=0;j<count&&fish.length<120;j++){let i=++fishSerial,a=hash(i*733+4217)*Math.PI*2,r=3+hash(i*277+4217)*5,color=['silver','blue','gold'][(i-1)%3],group=new THREE.Group(),body=new THREE.Mesh(fishGeo.body,fishMaterials[color]),tail=new THREE.Mesh(fishGeo.tail,fishMaterials[color]);group.add(body,tail);let eyeM=new THREE.MeshStandardMaterial({color:'#071923',roughness:.3});for(let s of[-1,1]){let eye=new THREE.Mesh(new THREE.SphereGeometry(.007,7,5),eyeM);eye.position.set(.104,.018,s*.029);group.add(eye);}group.position.set(3+Math.cos(a)*r,-3-hash(i*571)*3,Math.sin(a)*r);scene.add(group);const scale=.65+hash(i*821)*.6;group.scale.setScalar(scale);const f={id:'F'+String(i).padStart(2,'0'),color,mesh:group,body,tail,position:group.position,velocity:V(Math.cos(a)*.4,0,Math.sin(a)*.4),next:V(),state:'alive',phase:hash(i*191)*6.28,scale};body.userData.fishId=f.id;fish.push(f);}}
spawn(36);let selected=null,point=null,follow=true,displayMode='ocean',manual=false;
const marker=new THREE.Mesh(new THREE.TorusGeometry(.2,.012,6,36),new THREE.MeshBasicMaterial({color:'#cee1c9',depthTest:false,transparent:true,opacity:.65}));marker.rotation.x=Math.PI/2;marker.visible=false;marker.renderOrder=20;scene.add(marker);
const halo=new THREE.Mesh(new THREE.RingGeometry(.27,.28,36),new THREE.MeshBasicMaterial({color:'#d4e6ba',side:THREE.DoubleSide,depthTest:false,transparent:true,opacity:.8}));halo.visible=false;halo.renderOrder=30;scene.add(halo);
const events=[];const behavior=createBehavior({shark,ocean,fish,camera,getSelected:()=>selected,getPoint:()=>point,spawn,onEvent:e=>{events.push(e);if(events.length>100)events.shift();}}),state=behavior.state;
const temp=V(),sep=V(),align=V(),cohere=V(),acc=V();
function updateFish(dt){const t=state.time;
 for(const f of fish){if(f.state!=='alive')continue;sep.set(0,0,0);align.set(0,0,0);cohere.set(0,0,0);let n=0;
 for(const other of fish){if(other===f||other.state!=='alive')continue;temp.copy(f.position).sub(other.position);let d2=temp.lengthSq();if(d2<6.25){align.add(other.velocity);cohere.add(other.position);n++;if(d2<.25)sep.addScaledVector(temp,1/Math.max(.012,d2));}}
 acc.set(0,0,0);if(n){align.multiplyScalar(1/n).sub(f.velocity);cohere.multiplyScalar(1/n).sub(f.position);acc.addScaledVector(align,.5).addScaledVector(cohere,.18).addScaledVector(sep,.26);}
 const home=V(3+2*Math.sin(t*.022),-4.4,2*Math.sin(t*.033)),dh=home.sub(f.position);acc.addScaledVector(dh,.025);acc.y+=(-4.5-f.position.y)*.04;
 let threat=f.position.distanceTo(state.position),escaping=threat<3.3;
 if(escaping){temp.copy(f.position).sub(state.position).normalize();acc.addScaledVector(temp,(3.3-threat)*.65);acc.y+=Math.sin(f.phase)*.16;}
 for(const rock of ocean.rocks){temp.copy(f.position).sub(rock.position);let d=temp.length();if(d<rock.radius+.6)acc.addScaledVector(temp.normalize(),(rock.radius+.6-d)*1.2);}
 if(f.position.y>ocean.surfaceAt(f.position.x,f.position.z,t)-.7)acc.y-=1;
 if(f.position.y<ocean.floorAt(f.position.x,f.position.z)+.5)acc.y+=1;
 acc.clampLength(0,1.6);f.next.copy(f.velocity).addScaledVector(acc,dt);const max=escaping?1.25:.62,sp=f.next.length();if(sp>max)f.next.multiplyScalar(max/sp);if(sp<.23)f.next.setLength(.23);
 }
 for(const f of fish){if(f.state==='alive'){f.velocity.copy(f.next);f.position.addScaledVector(f.velocity,dt).addScaledVector(ocean.flowAt(f.position,t),dt);const yaw=Math.atan2(-f.velocity.z,f.velocity.x),pitch=Math.atan2(f.velocity.y,Math.hypot(f.velocity.x,f.velocity.z));f.mesh.quaternion.slerp(new THREE.Quaternion().setFromEuler(new THREE.Euler(0,yaw,pitch,'YZX')),1-Math.exp(-dt*7));}if(f.state!=='consumed'){f.phase+=dt*(6+f.velocity.length()*7);f.tail.rotation.y=Math.sin(f.phase)*.35;}}
}
function step(dt){behavior.begin();if(state.paused)return;updateFish(dt);behavior.step(dt);ocean.update(dt,state.time,state.position);}
let last=performance.now(),debt=0,uiTime=0,frameTimes=[],renderedFrames=0,displayTime=0,hidden=false;
function render(){requestAnimationFrame(render);const now=performance.now(),delta=(now-last)/1000;last=now;displayTime+=delta;const before=state.position.clone();
 if(!manual&&!hidden){if(!state.paused){debt+=delta;let steps=0;while(debt>=MOTION_LIMITS.solverStep&&steps<60){step(MOTION_LIMITS.solverStep);debt-=MOTION_LIMITS.solverStep;steps++;}}else behavior.begin();}
 if(follow){const shift=state.position.clone().sub(before);camera.position.add(shift);controls.target.add(shift);}
 if(selected){const f=fish.find(f=>f.id===selected&&f.state!=='consumed');halo.visible=!!f;if(f){halo.position.copy(f.position);halo.lookAt(camera.position);}}else halo.visible=false;
 marker.visible=!!point;controls.update();renderer.render(scene,camera);renderedFrames++;frameTimes.push(delta);if(frameTimes.length>120)frameTimes.shift();uiTime+=delta;if(uiTime>.2){refresh();uiTime=0;}
 if(renderedFrames===2){$('loading').hidden=true;$('engine').textContent='实时水下场域';window.SHARK_LAB.ready=true;}
}
function refresh(){const living=fish.filter(f=>f.state==='alive'||f.state==='gripped').length;$('depth').innerHTML=(-state.position.y).toFixed(1)+' <small>m</small>';$('speed').innerHTML=state.speed.toFixed(2)+' <small>m/s</small>';$('fishCount').innerHTML=living+' <small>条</small>';$('status').textContent=state.status;$('message').textContent=state.status;$('pause').textContent=state.paused?'恢复模拟':'暂停模拟';$('queue').replaceChildren();for(let t of state.queue){let d=document.createElement('div');d.textContent=t.label||t.type;$('queue').append(d);}$('rigInfo').textContent=JSON.stringify({...shark.audit(),physicalTime:+state.time.toFixed(2),solverStep:MOTION_LIMITS.solverStep,epoch:state.epoch,huntAuthorized:state.permission,queued:state.queue.length},null,2);const fps=frameTimes.length/Math.max(.001,frameTimes.reduce((a,b)=>a+b,0));$('frameInfo').textContent=Math.round(fps)+' FPS · '+renderer.domElement.width+' × '+renderer.domElement.height+' · 候选预览';if(!$('panel').hidden){$('history').replaceChildren();for(let e of events.slice(-10).reverse()){let p=document.createElement('p');p.textContent=e.time.toFixed(2)+'s '+e.type+(e.id?' '+e.id:'');$('history').append(p);}}}
function setMode(mode){displayMode=mode;ocean.setMode(mode);shark.cartilage.visible=mode==='diagnostic';shark.mat.transparent=mode==='diagnostic';shark.mat.opacity=mode==='diagnostic'?.10:1;shark.mat.depthWrite=mode!=='diagnostic';shark.mat.needsUpdate=true;for(const f of fish)f.mesh.visible=mode==='ocean'&&f.state!=='consumed';halo.visible=mode==='ocean';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));shark.update(0,state.speed,0,state.pitch,state.jaw);}
function homeView(){controls.target.copy(state.position);camera.position.copy(state.position).add(V(3.6,1.0,6.3));follow=true;$('followView').classList.add('active');controls.update();}
let semantic=null,abortController=null;
const AI_SYSTEM=`You are a grounded shark task planner. Convert the user's Chinese instruction into JSON only, no code. Never invent entities, obey negation. Return {"schema":"shark/behavior_plan@1","tasks":[...]}. Motor capabilities: hunt {selector:{id:"F01"} OR {color:"silver|blue|gold"} OR {nearest:true} OR {selected:true},count:1..40,speed:0.42..3.4}; follow same selector,duration seconds,speed; orbit selector:{school:true} OR {point:true} OR {selected:true},laps:0.1..20,radius:2.5..15,direction:1 or -1,speed; depth depth:1.2..8,speed; move target:home|observer|point|school|fish,selector,speed; travel distance:1..60,direction:forward|left|right,speed; cruise duration:1..300,speed,direction; turn angle:3.14159,speed; jaw open:boolean,duration; stop; pause paused:boolean; spawn count:1..40. Each task may include a Chinese label. No hunting without explicit authorization. For impossible/ambiguous/unsupported requests return {"error":"Chinese explanation"}. Species needs continuous ram ventilation; stop cancels tasks, pause freezes simulation. Do not create preset routes or animation clips. Use quantities and order from the instruction.`;
function snapshot(){return{schema:'shark/world_snapshot@1',time:state.time,epoch:state.epoch,shark:{position:state.position.toArray(),speed:state.speed,species:shark.profile.species},selected,point:point?.toArray()||null,fish:fish.filter(f=>f.state==='alive').map(f=>({id:f.id,color:f.color,position:f.position.toArray()})),bounds:{depthM:[1.2,8],radiusM:32},capabilities:['hunt','follow','orbit','depth','move','travel','cruise','turn','jaw','stop','pause','spawn']};}
async function command(text){if(!semantic){const r=behavior.submit(text);if(r.ok){state.paused=false;behavior.begin();}refresh();return r;}
 const epoch=behavior.cancel();abortController?.abort();abortController=new AbortController();const signal=abortController.signal;state.status='正在结合当前鱼群理解目标';const world=snapshot();try{let output;if(semantic.type==='native'){output=await semantic.session.prompt(AI_SYSTEM+'\nWORLD:'+JSON.stringify(world)+'\nUSER:'+text,{signal});output=JSON.parse(output.replace(/^```(?:json)?\s*|\s*```$/g,''));}else{const response=await fetch(semantic.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instruction:text,world,schema:'shark/behavior_plan@1',plannerContract:AI_SYSTEM}),signal});if(!response.ok)throw Error('语义服务 HTTP '+response.status);output=await response.json();}if(epoch!==state.epoch)return{ok:false,stale:true};if(output.error)throw Error(output.error);behavior.install(output.plan||output,epoch);state.paused=false;behavior.begin();return{ok:true,plan:output};}catch(e){if(e.name==='AbortError')return{ok:false,cancelled:true};if(epoch===state.epoch)state.status='语义理解未完成：'+e.message;return{ok:false,error:e.message};}finally{refresh();}}
$('commandForm').addEventListener('submit',async e=>{e.preventDefault();const text=$('instruction').value.trim();if(!text)return;await command(text);});
$('instruction').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('commandForm').requestSubmit();}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('homeView').onclick=homeView;$('followView').onclick=()=>{follow=!follow;$('followView').classList.toggle('active',follow);};$('panelBtn').onclick=()=>$('panel').hidden=!$('panel').hidden;$('closePanel').onclick=()=>$('panel').hidden=true;$('help').onclick=()=>$('examples').hidden=!$('examples').hidden;document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('instruction').value=b.dataset.example;$('instruction').focus();});
$('pause').onclick=()=>{state.paused=!state.paused;debt=0;refresh();};$('aboutBtn').onclick=()=>$('about').showModal();$('closeAbout').onclick=()=>$('about').close();$('wire').onchange=e=>shark.mat.wireframe=e.target.checked;
for(let k of['key','fill','rim'])$(k+'Light').oninput=e=>ocean.lights[k].intensity=Number(e.target.value);
$('nativeAI').onclick=async()=>{const status=$('aiStatus');try{if(!globalThis.LanguageModel){throw Error('这个浏览器没有设备语言模型接口。');}const opts={expectedInputs:[{type:'text',languages:['zh']}],expectedOutputs:[{type:'text',languages:['zh']}]};const availability=await LanguageModel.availability(opts);if(availability==='unavailable')throw Error('当前设备或模型尚不支持中文语义。');status.textContent='正在准备设备模型；首次使用可能需要浏览器下载。';const session=await LanguageModel.create({...opts,monitor(m){m.addEventListener('downloadprogress',e=>status.textContent='设备模型 '+Math.round(e.loaded*100)+'%');}});semantic={type:'native',session};status.textContent='设备语义引擎已连接，推理在本机运行。';$('modeLabel').textContent='设备语义';}catch(e){status.textContent=e.message+' 继续使用组合解析。';}};
$('connectAI').onclick=()=>{try{const u=new URL($('endpoint').value);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error('需要 HTTPS 或本机服务。');semantic={type:'service',url:u.href};$('aiStatus').textContent='已选择语义服务，首次指令时验证连接。指令与场景摘要将发送到该地址。';$('modeLabel').textContent='自有语义服务';}catch(e){$('aiStatus').textContent=e.message;}};
function exportState(){return{build:'shark-ocean-agent-0.1.0',motherPolicy:'1.0.0',profile:shark.profile,world:snapshot(),anatomy:shark.audit(),pose:shark.bones.map(b=>({id:b.name,rotation:b.quaternion.toArray()})),history:state.events,weather:ocean.weather.getEnvironment(),physicalTime:state.time,displayTime,solverStep:MOTION_LIMITS.solverStep,masterSeed:4217,semanticEngine:semantic?.type||'bounded_compositional_parser',visualApproved:false,productionApproved:false,limitations:['procedural seabed is not measured bathymetry','cartilage proportions are illustrative','not a CFD or validated biomechanics solver','shared original strict schema and validator unavailable','open language needs connected semantic engine']};}
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(exportState(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='shark-world-state.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>4)return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(fish.filter(f=>f.state==='alive').map(f=>f.body));if(hits.length){selected=hits[0].object.userData.fishId;$('selection').textContent='已选择 '+selected+'。可以要求靠近、跟随或捕食。';}else{const plane=new THREE.Plane(V(0,1,0),-state.position.y),hit=ray.ray.intersectPlane(plane,V());if(hit&&Math.hypot(hit.x,hit.z)<32){point=hit;marker.position.copy(hit);$('selection').textContent='目的地 '+point.toArray().map(x=>x.toFixed(1)).join(', ')+' 米；说“游到那里”。';selected=null;}}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});document.addEventListener('visibilitychange',()=>{hidden=document.hidden;last=performance.now();});
window.SHARK_LAB={ready:false,state,shark,fish,ocean,scene,camera,controls,renderer,command,parse:parseInstruction,validatePlan,snapshot,exportState,homeView,setMode,setManual:v=>{manual=v;debt=0;},advance:seconds=>{for(let i=0;i<Math.round(seconds/MOTION_LIMITS.solverStep);i++)step(MOTION_LIMITS.solverStep);refresh();},audit:()=>({...shark.audit(),time:state.time,consumed:state.caught,alive:fish.filter(f=>f.state==='alive').length,permission:state.permission,events:state.events,mode:displayMode,frameCount:renderedFrames}),cancel:()=>{abortController?.abort();behavior.cancel('manual');}};
fetch('BUILD.json').then(r=>r.ok?r.json():null).then(b=>{if(b)$('buildInfo').textContent=(location.href.match(/[a-f0-9]{40}/)?.[0]||b.sourceHead||'local')+' / Three.js '+b.threeVersion;}).catch(()=>{});
shark.update(0,.5,0,0,0);render();
