import * as THREE from 'three';
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),M=THREE.MathUtils;
export const hash=n=>{n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return((n^(n>>>16))>>>0)/4294967296;};
// Adapted from Ocean Mother 0.1.0 makeWaves(), source commit 970aa25814e5d5f98cf10091da69666f62dbcd28.
export function makeWaves(seed=4217,swell=.48,period=8.8,wind=5,direction=270){const waveK=[],waveA=[];const bearing=direction*Math.PI/180,base=Math.atan2(Math.cos(bearing),-Math.sin(bearing));let sumSteep=0;
 for(let group=0;group<2;group++){let raw=[],sum2=0;for(let j=0;j<12;j++){const idx=j+12*group,h=hash(seed+idx*341),d=base+(hash(seed+idx*991)-.5)*(group?1.8:.58)+(group?0:.24),len=group?Math.max(1.7,Math.min(40,2+wind*1.6))*Math.pow(.79,j):9.81*period*period/(2*Math.PI)*(.62+hash(seed+idx*723)*.78),weight=group?Math.pow(.83,j):.46+hash(seed+idx*419);raw.push({idx,d,len,weight,h});sum2+=weight*weight;}
 const scale=(group?Math.min(3.7,wind*wind*.010):swell)/(4*Math.sqrt(.5*sum2));for(const w of raw){let k=2*Math.PI/w.len,amp=w.weight*scale;waveK.push(new THREE.Vector4(Math.cos(w.d),Math.sin(w.d),k,Math.sqrt(9.81*k)));waveA.push(new THREE.Vector4(amp,amp*.65,w.h*Math.PI*2,w.len));sumSteep+=amp*.65*k;}}
 const gain=Math.min(1,.70/Math.max(sumSteep,1e-8));waveA.forEach(a=>a.y*=gain);return{waveK,waveA};}
export function createOcean(scene,renderer){
 const time={value:0},environmentGroup=new THREE.Group();scene.add(environmentGroup);const waves=makeWaves();
 const W=window.OceanWeather;W.set('wind',5);W.set('hour',11);W.set('timeScale',1);W.setSeed(4217);
 const lightGroup=new THREE.Group();scene.add(lightGroup);const hemi=new THREE.HemisphereLight('#a5d8db','#203c46',1.65);lightGroup.add(hemi);
 const key=new THREE.DirectionalLight('#ecf4e1',3.5),fill=new THREE.DirectionalLight('#69b5cb',1.05),rim=new THREE.DirectionalLight('#b1ebdf',2);key.position.set(-6,14,6);fill.position.set(6,2,-8);rim.position.set(-5,2,-9);lightGroup.add(key,fill,rim);
 scene.background=new THREE.Color('#176577');scene.fog=new THREE.FogExp2('#176577',.037);
 const surfaceGeo=new THREE.PlaneGeometry(210,210,160,160);surfaceGeo.rotateX(-Math.PI/2);
 const surfaceMat=new THREE.MeshPhysicalMaterial({color:'#76bfba',roughness:.22,metalness:.30,side:THREE.DoubleSide,transparent:true,opacity:.84,depthWrite:false});
 surfaceMat.onBeforeCompile=s=>{s.uniforms.oTime=time;s.uniforms.waveK={value:waves.waveK};s.uniforms.waveA={value:waves.waveA};s.vertexShader='uniform float oTime; uniform vec4 waveK[24]; uniform vec4 waveA[24];\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`vec3 transformed=position; for(int i=0;i<24;i++){vec4 k=waveK[i],a=waveA[i];float ph=dot(k.xy,position.xz)*k.z-k.w*oTime+a.z;transformed+=vec3(k.x*a.y*cos(ph),a.x*sin(ph),k.y*a.y*cos(ph));}`);};
 const surface=new THREE.Mesh(surfaceGeo,surfaceMat);environmentGroup.add(surface);
 function surfaceAt(x,z,t=time.value){let ux=x,uz=z;
 for(let it=0;it<5;it++){let px=ux,pz=uz,j00=1,j01=0,j11=1;for(let i=0;i<24;i++){let k=waves.waveK[i],a=waves.waveA[i],ph=(k.x*ux+k.y*uz)*k.z-k.w*t+a.z,c=Math.cos(ph),s=Math.sin(ph);px+=k.x*a.y*c;pz+=k.y*a.y*c;j00-=k.x*k.x*a.y*k.z*s;j01-=k.x*k.y*a.y*k.z*s;j11-=k.y*k.y*a.y*k.z*s;}let ex=px-x,ez=pz-z,det=j00*j11-j01*j01;ux-=(j11*ex-j01*ez)/det;uz-=(-j01*ex+j00*ez)/det;}
 let h=0;for(let i=0;i<24;i++){let k=waves.waveK[i],a=waves.waveA[i];h+=a.x*Math.sin((k.x*ux+k.y*uz)*k.z-k.w*t+a.z);}return h;}
 function floorAt(x,z){return -9.4+.19*Math.sin(x*.16)*Math.cos(z*.13)+.07*Math.sin(x*1.1+Math.sin(z*.65));}
 const causticMaterials=[];
 const causticGLSL=`uniform float oTime;uniform float oCaustic;varying vec3 oceanWorld; varying vec3 objectRest;
 float nh(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
 float cell(vec2 p){vec2 i=floor(p),f=fract(p);float a=8.,b=8.; for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){vec2 g=vec2(float(x),float(y));float n=nh(i+g);vec2 r=g+.5+.30*sin(vec2(n*6.28,n*10.6)+oTime*.55)-f;float d=dot(r,r);if(d<a){b=a;a=d;}else{b=min(b,d);}}return exp(-max(0.,sqrt(b)-sqrt(a))*27.);}
 `;
 const causticEnabled={value:1};
 function caustics(mat,micro=false){causticMaterials.push(mat);mat.onBeforeCompile=s=>{s.uniforms.oTime=time;s.uniforms.oCaustic=causticEnabled;s.vertexShader='varying vec3 oceanWorld;varying vec3 objectRest;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nobjectRest=position;');s.vertexShader=s.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\noceanWorld=(modelMatrix*vec4(transformed,1.0)).xyz;');s.fragmentShader=causticGLSL+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 vec2 cp=oceanWorld.xz*1.05+vec2(sin(oceanWorld.z*.37+oTime*.17),cos(oceanWorld.x*.27+oTime*.2))*.28;
 float cc=cell(cp);diffuseColor.rgb*=1.+cc*.36*oCaustic;
 `);if(micro)s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_maps>',`#include <normal_fragment_maps>\nfloat denticle=sin(objectRest.x*370.+sin(objectRest.z*190.))*sin(objectRest.y*330.+objectRest.z*230.);normal=normalize(normal+vec3(denticle*.025,denticle*.010,0.));`);};}
 const groundG=new THREE.PlaneGeometry(200,200,210,210);groundG.rotateX(-Math.PI/2);let ga=groundG.attributes.position;const gc=[];for(let i=0;i<ga.count;i++){let x=ga.getX(i),z=ga.getZ(i);ga.setY(i,floorAt(x,z));let h=.08*Math.sin(x*9+Math.sin(z*.55)*3)+.035*Math.sin(x*29+z*1.5),col=new THREE.Color('#b3bca1').multiplyScalar(.90+h);gc.push(col.r,col.g,col.b);}groundG.setAttribute('color',new THREE.Float32BufferAttribute(gc,3));groundG.computeVertexNormals();const groundM=new THREE.MeshStandardMaterial({vertexColors:true,roughness:1});caustics(groundM);const ground=new THREE.Mesh(groundG,groundM);environmentGroup.add(ground);
 const rocks=[],rMat=new THREE.MeshStandardMaterial({color:'#48635d',roughness:.95});caustics(rMat);
 for(let i=0;i<24;i++){let a=hash(4217+i*127)*Math.PI*2,r=9+hash(4217+i*151)*23,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.4+hash(4217+i*71)*2.0,g=new THREE.IcosahedronGeometry(1,2),v=g.attributes.position;for(let j=0;j<v.count;j++){let x0=v.getX(j),y=v.getY(j),z0=v.getZ(j),f=1+.12*Math.sin(x0*9+y*7)*Math.cos(z0*6);v.setXYZ(j,x0*f,y*f,z0*f);}g.computeVertexNormals();let m=new THREE.Mesh(g,rMat);m.position.set(x,floorAt(x,z)+s*.30,z);m.scale.set(s*1.3,s*.75,s);m.rotation.set(.1,hash(i+7)*6,0);environmentGroup.add(m);rocks.push({position:m.position.clone(),radius:s*1.3});}
 const kelpGroup=new THREE.Group();environmentGroup.add(kelpGroup);const bladeG=new THREE.PlaneGeometry(.26,1,3,12);bladeG.translate(0,.5,0);const bladeM=new THREE.MeshStandardMaterial({color:'#49745b',roughness:.9,side:THREE.DoubleSide});const sharkUniform={value:V(0,-4,0)};
 bladeM.onBeforeCompile=s=>{s.uniforms.oTime=time;s.uniforms.sharkPosition=sharkUniform;s.vertexShader='uniform float oTime;uniform vec3 sharkPosition;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`vec3 transformed=position;vec3 base=(modelMatrix*instanceMatrix*vec4(0.,0.,0.,1.)).xyz;float stem=position.y;transformed.x+=sin(oTime*.65+base.x*.7+base.z*.4+stem*2.)*.19*stem*stem;transformed.z+=cos(oTime*.5+base.z)*.12*stem;transformed.x+=exp(-distance(base,sharkPosition)*.6)*sin(oTime*3.)*.18*stem;`);};
 const blades=new THREE.InstancedMesh(bladeG,bladeM,420),dummy=new THREE.Object3D();for(let i=0;i<420;i++){let cluster=Math.floor(i/21),a=cluster/20*Math.PI*2,r=12+hash(cluster*31+4)*11,x=Math.cos(a)*r+(hash(i*63)-.5)*3,z=Math.sin(a)*r+(hash(i*47)-.5)*3;dummy.position.set(x,floorAt(x,z),z);dummy.rotation.set(0,hash(i*137)*6.28,0);dummy.scale.set(.7+hash(i+15),.8+hash(i*13)*2.6,1);dummy.updateMatrix();blades.setMatrixAt(i,dummy.matrix);}kelpGroup.add(blades);
 const dustG=new THREE.BufferGeometry(),dustP=[];for(let i=0;i<650;i++)dustP.push((hash(i*31+1)-.5)*75,-hash(i*37+2)*9,(hash(i*43+3)-.5)*75);dustG.setAttribute('position',new THREE.Float32BufferAttribute(dustP,3));const dustM=new THREE.PointsMaterial({color:'#c1e2d7',size:.012,transparent:true,opacity:.32,depthWrite:false});const dust=new THREE.Points(dustG,dustM);environmentGroup.add(dust);
 let mode='ocean';function setMode(v){mode=v;environmentGroup.visible=v==='ocean';causticEnabled.value=v==='ocean'?1:0;scene.fog=v==='ocean'?new THREE.FogExp2('#176577',.037):null;scene.background.set(v==='ocean'?'#176577':v==='neutral'?'#708489':'#14262c');hemi.intensity=v==='neutral'?2.3:1.65;key.intensity=v==='neutral'?2.6:3.5;}
 function update(dt,t,sharkPos){time.value=t;W.tick(dt);sharkUniform.value.copy(sharkPos);dust.position.x=Math.sin(t*.06)*.4;dust.position.z=Math.cos(t*.05)*.2;}
 return{time,group:environmentGroup,surfaceAt,floorAt,rocks,caustics,setMode,update,lights:{key,fill,rim},weather:W,flowAt:(p,t)=>V(.035+.012*Math.sin(t*.15+p.z*.1),0,.015*Math.sin(p.x*.1+t*.08)),waves,get mode(){return mode;}};
}
