/* Skin Atelier R1. Authored procedural geometry and surface fields.
 * No captured vertices, photographs, baked character textures, or teacher assets.
 * Method inheritance: FaceAnatomy r14 / EyeAnatomy r14, Humanoid-Rig-Lab-Next
 * 8b34db7993b27f8cdb40c801a40bf20931d8a416. Does not replace the production rig.
 * Local units: centimetres. Optical distances are authored approximations.
 */
const errors=[];window.__atelierErrors=errors;
function fail(e){errors.push(String(e?.stack||e));document.querySelector('#loading').classList.remove('hidden');document.querySelector('#status').classList.add('error');document.querySelector('#status').textContent=String(e?.message||e);console.error(e)}
window.addEventListener('error',e=>fail(e.error||e.message));window.addEventListener('unhandledrejection',e=>fail(e.reason));
try {
const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js');
const $=s=>document.querySelector(s),status=s=>$('#status').textContent=s;
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),PI=Math.PI;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t,smooth=(a,b,x)=>{let t=clamp((x-a)/(b-a));return t*t*(3-2*t)},G=(x,s)=>Math.exp(-((x/s)**2));
let seed=746331;const rng=()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296};
const viewport=$('#viewport'),renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.setClearColor(0x101112);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(31,1,.1,250),portrait=new THREE.Group();scene.add(portrait);
const globals={pore:{value:.65},oil:{value:.45},sss:{value:.45},tone:{value:.10},blush:{value:.55},freckles:{value:.32},micro:{value:.60},mode:{value:0},key:{value:V(-18,24,30)},pupil:{value:.215}};
const allGeometry=[],skinMats=[],eyeParts=[],hairGroup=new THREE.Group(),lashGroup=new THREE.Group(),fuzzGroup=new THREE.Group();portrait.add(hairGroup,lashGroup,fuzzGroup);
const key=new THREE.DirectionalLight(0xffead6,2.6);key.position.set(-18,24,30);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-25;key.shadow.camera.right=25;key.shadow.camera.top=26;key.shadow.camera.bottom=-30;key.shadow.camera.near=1;key.shadow.camera.far=120;key.shadow.bias=-.00012;key.shadow.normalBias=.018;scene.add(key,key.target);
const fill=new THREE.DirectionalLight(0xc8dfff,.75);fill.position.set(18,8,24);scene.add(fill);const rim=new THREE.DirectionalLight(0xdbebff,2.7);rim.position.set(17,12,-18);scene.add(rim);scene.add(new THREE.HemisphereLight(0xd3dbea,0x53403a,.48));
// Self-generated studio environment; no HDR photograph.
function makeEnvironment(){const w=384,h=192,data=new Float32Array(w*h*4);for(let j=0;j<h;j++)for(let i=0;i<w;i++){let u=i/w*PI*2-PI,v=j/h*PI;const d=V(-Math.cos(u)*Math.sin(v),Math.cos(v),Math.sin(u)*Math.sin(v));let c=.022+.035*Math.max(0,d.y);const a=Math.pow(Math.max(0,d.dot(V(-.46,.45,.77).normalize())),72)*8,b=Math.pow(Math.max(0,d.dot(V(.57,.20,.8).normalize())),110)*3,e=Math.pow(Math.max(0,d.dot(V(.55,.2,-.8).normalize())),45)*5,k=(j*w+i)*4;data[k]=c+a+e*.8+b*.65;data[k+1]=c+a*.91+e*.9+b*.84;data[k+2]=c+a*.78+e+b;data[k+3]=1}const t=new THREE.DataTexture(data,w,h,THREE.RGBAFormat,THREE.FloatType);t.mapping=THREE.EquirectangularReflectionMapping;t.needsUpdate=true;const p=new THREE.PMREMGenerator(renderer);scene.environment=p.fromEquirectangular(t).texture;t.dispose();p.dispose()}
makeEnvironment();status('建立多尺度皮肤场');
// Deterministic periodic pore tile. Channels: height, roughness, pore region.
function makeMicro(){const n=1024,d=new Uint8Array(n*n*4);for(let j=0;j<n;j++)for(let i=0;i<n;i++){const k=(j*n+i)*4,q=rng();d[k]=128+(q-.5)*7;d[k+1]=126+(rng()-.5)*22;d[k+2]=0;d[k+3]=255}for(let gy=0;gy<62;gy++)for(let gx=0;gx<62;gx++){const x=(gx+.15+rng()*.7)*n/62,y=(gy+.15+rng()*.7)*n/62,r=1.7+rng()*2.7,elong=1.1+rng()*.8,ang=rng()*PI,cs=Math.cos(ang),sn=Math.sin(ang),rr=Math.ceil(r*elong*2.0);for(let j=-rr;j<=rr;j++)for(let i=-rr;i<=rr;i++){const a=(i*cs+j*sn)/r,b=(-i*sn+j*cs)/(r*elong),q=Math.hypot(a,b);if(q>2.1)continue;const k=(((Math.round(y)+j+n)%n)*n+(Math.round(x)+i+n)%n)*4,depth=-25*Math.exp(-q*q*2.0)+5*Math.exp(-(((q-1.04)/.34)**2));d[k]=clamp(d[k]+depth,0,255);d[k+1]=clamp(d[k+1]+Math.exp(-q*q*2)*17,0,255);d[k+2]=Math.max(d[k+2],Math.round(255*Math.exp(-q*q*2)))}}const t=new THREE.DataTexture(d,n,n,THREE.RGBAFormat);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.magFilter=THREE.LinearFilter;t.minFilter=THREE.LinearMipmapLinearFilter;t.generateMipmaps=true;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());t.needsUpdate=true;return t}
const microTex=makeMicro();
const shaderCommon=`
varying vec3 vAnatomy; varying vec3 vBaseNormal;
uniform sampler2D uMicro;uniform float uPore,uOil,uSSS,uTone,uBlush,uFreckles,uFine,uMode,uHole;uniform vec3 uKey;
float hash21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float nv(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+1.),f.x),f.y);}
float ga(float x,float s){return exp(-pow(x/s,2.));}
vec4 microAt(vec3 p){vec3 w=pow(abs(normalize(vBaseNormal)),vec3(5.));w/=w.x+w.y+w.z;return texture2D(uMicro,p.yz/2.8)*w.x+texture2D(uMicro,p.xz/2.8)*w.y+texture2D(uMicro,p.xy/2.8)*w.z;}
vec2 lipOutline(float x){float q=clamp(abs(x)/2.38,0.,1.),env=pow(max(0.,1.-q*q),.80);float cup=.67+.35*ga(q-.25,.20);return vec2(.43*cup*env,.56*env);}
float lipMask(vec3 p){vec2 h=lipOutline(p.x);float y=p.y+4.03;float s=y>=0.?h.x:h.y;return (1.-smoothstep(.78,1.05,abs(y)/max(.003,s)))*(1.-smoothstep(2.30,2.39,abs(p.x)))*smoothstep(2.8,4.8,p.z);}
float skinH(vec3 p){vec4 d=microAt(p);float eye=ga(abs(p.x)-3.1,2.0)*ga(p.y-2.1,1.4),lip=lipMask(p),nose=ga(p.x,1.4)*ga(p.y,1.9);float por=(d.r-.50)*.020*uPore*(1.-.80*eye)*(1.-lip)*(1.+.45*nose);float small=(nv(p.xy*110.)-.5)*.0009*uFine;float lipH=(sin(p.x*63.+nv(p.xy*3.)*7.)*.5+.5)*.0025*lip*uFine;return por+small+lipH;}
`;
function skinMaterial(holes=0){const m=new THREE.MeshPhysicalMaterial({color:0xffffff,roughness:.48,metalness:0,ior:1.42,specularIntensity:.55,clearcoat:.07,clearcoatRoughness:.34,bumpMap:microTex,bumpScale:1,envMapIntensity:.48});m.customProgramCacheKey=()=>`atelier-skin-${holes}`;
m.onBeforeCompile=s=>{Object.assign(s.uniforms,{uMicro:{value:microTex},uPore:globals.pore,uOil:globals.oil,uSSS:globals.sss,uTone:globals.tone,uBlush:globals.blush,uFreckles:globals.freckles,uFine:globals.micro,uMode:globals.mode,uHole:{value:holes},uKey:globals.key});s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vAnatomy; varying vec3 vBaseNormal;').replace('#include <begin_vertex>','#include <begin_vertex>\nvAnatomy=position;vBaseNormal=normal;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\n'+shaderCommon);
s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
vec3 p=vAnatomy;float front=smoothstep(0.,4.,p.z);float lip=lipMask(p);float cheek=ga(abs(p.x)-3.7,2.2)*ga(p.y+.5,2.1)*front;float nose=ga(p.x,1.3)*ga(p.y+.6,1.3)*front;float eye=ga(abs(p.x)-3.1,1.65)*ga(p.y-2.0,1.2)*front;float mott=(nv(p.xy*2.5)+nv(p.yz*4.7)*.40-0.7);vec3 base=mix(vec3(.635,.390,.286),vec3(.255,.123,.078),uTone);base+=mott*vec3(.030,.020,.017);base=mix(base,base*vec3(1.075,.83,.82),clamp((cheek*.28+nose*.32)*uBlush,0.,.5));base*=1.-eye*.10;vec3 lipColor=vec3(.395,.170,.163);base=mix(base,lipColor,lip*.83);float freck=pow(smoothstep(.68,.89,nv(p.xy*16.)),3.)*cheek*uFreckles*.37;base*=1.-freck;float liner=ga(abs(p.x)-3.1,1.50)*ga(p.y-3.07,.40)*front;base=mix(base,base*vec3(.63,.59,.64),liner*.27);
if(uHole>.5&&p.z>0.){float q=min(length(vec2((p.x-3.1)/1.98,(p.y-2.1)/1.37)),length(vec2((p.x+3.1)/1.98,(p.y-2.1)/1.37)));if(q<.985)discard;float nt=min(length(vec2((p.x-.81)/.30,(p.y+1.50)/.145)),length(vec2((p.x+.81)/.30,(p.y+1.50)/.145)));if(nt<.88&&p.z>5.)discard;}
diffuseColor.rgb=base;if(uMode>0.5&&uMode<1.5)diffuseColor.rgb=vec3(.43);`);
s.fragmentShader=s.fragmentShader.replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>
float tzone=ga(p.x,1.5)*ga(p.y-.2,4.0)*front;roughnessFactor=clamp(.54-.17*uOil-.09*tzone*uOil+(microAt(p).g-.5)*.16,.20,.72);roughnessFactor=mix(roughnessFactor,.33-.08*uOil,lip);`);
s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_maps>',`float hh=skinH(vAnatomy);normal=perturbNormalArb(-vViewPosition,normal,vec2(dFdx(hh),dFdy(hh)),faceDirection);`);
s.fragmentShader=s.fragmentShader.replace('#include <opaque_fragment>',`vec3 L=normalize((viewMatrix*vec4(uKey,0.)).xyz);float wrap=max(0.,dot(normal,L)*.55+.45);float back=pow(max(0.,dot(-L,normalize(vViewPosition))),3.);vec3 subsurface=diffuseColor.rgb*vec3(.20,.078,.043)*(wrap*.46+back*.42)*uSSS;outgoingLight+=subsurface;
if(uMode>1.5&&uMode<2.5)outgoingLight=vec3(roughnessFactor);
if(uMode>2.5)outgoingLight=normal*.5+.5;
#include <opaque_fragment>`);};skinMats.push(m);return m}
const skin=skinMaterial(1),skinDetail=skinMaterial(0);
function profile(rows,y){let i=0;if(y<=rows[0][0])return rows[0].slice(1);if(y>=rows.at(-1)[0])return rows.at(-1).slice(1);while(i<rows.length-2&&rows[i+1][0]<y)i++;let a=rows[Math.max(0,i-1)],b=rows[i],c=rows[i+1],d=rows[Math.min(rows.length-1,i+2)],t=(y-b[0])/(c[0]-b[0]),span=c[0]-b[0];return b.slice(1).map((v,k)=>{k++;let m0=(c[k]-a[k])/(c[0]-a[0]),m1=(d[k]-b[k])/(d[0]-b[0]);return(2*t*t*t-3*t*t+1)*b[k]+(t*t*t-2*t*t+t)*m0*span+(-2*t*t*t+3*t*t)*c[k]+(t*t*t-t*t)*m1*span})}
const headRows=[[-11,2.7,3.5,3.8],[-9.5,3.05,4.6,4.1],[-8,3.8,5.25,4.8],[-6.5,4.85,5.40,5.5],[-4.5,5.95,5.42,6.1],[-2.5,6.55,5.67,6.5],[0,6.9,5.92,6.9],[2.1,6.82,5.92,7.2],[4.3,6.75,6.2,7.35],[6.6,6.82,6.45,7.4],[8.5,6.56,6.05,7.0],[10.2,5.65,4.9,5.9],[11.7,3.95,3.05,4.0],[12.65,1.50,.5,1.5],[12.85,.02,.015,.02]];
const neckRows=[[-27,18.4,8.0,7.0],[-24,18.7,8.2,7.0],[-21,15.7,7.5,6.5],[-19,10.1,5.6,5.2],[-17,5.35,3.9,4.3],[-15,3.72,3.25,4.0],[-12,3.52,3.0,4.2],[-9,3.55,3.0,4.5],[-5,4.1,3.4,5.1],[0,4.8,3.8,5.8]];
function lipOutline(x){let q=clamp(Math.abs(x)/2.38),env=Math.max(0,1-q*q)**.8,cup=.67+.35*G(q-.25,.2);return[.43*cup*env,.56*env]}
function facialRelief(x,y){let z=0;z+=.50*G(Math.abs(x)-4.2,1.9)*G(y+.10,1.60);z+=.17*G(Math.abs(x)-3.2,2.1)*G(y-4.4,.66);z-=.30*G(Math.abs(x)-3.1,1.52)*G(y-2.25,1.02);z-=.24*G(Math.abs(x)-4.5,1.55)*G(y+4.1,1.65);
z+=.88*G(x,.68)*G(y-1.5,2.25)+1.75*G(x,.79)*G(y+.57,.82)+.60*G(Math.abs(x)-.86,.36)*G(y+1.13,.46)-.31*G(x,.48)*G(y+1.77,.22);z-=.10*G(Math.abs(x)-1.18,.22)*G(y+1.30,.46);z+=.10*G(Math.abs(x)-.28,.17)*G(y+2.8,.85)-.080*G(x,.22)*G(y+2.9,.76);
let h=lipOutline(x),yy=y+4.03,r=Math.abs(yy)/(yy>0?Math.max(.01,h[0]):Math.max(.01,h[1]));if(Math.abs(x)<2.4){let env=Math.max(0,1-(x/2.4)**2)**.7;z+=env*(.30*Math.exp(-(((r-.50)/.59)**2))+.08*G(r,.28));z-=.08*env*G(yy,.045)}z-=.15*G(x,1.55)*G(y+5.3,.45);z+=.23*G(x,1.72)*G(y+6.65,.9);return z}
function headZ(x,y){let [w,f]=profile(headRows,y),q=clamp(x/Math.max(.01,w),-1,1),cs=Math.sqrt(Math.max(0,1-q*q));return f*cs*(1+.24*q*q)+facialRelief(x,y)}
function bodyPoint(y,a){let cs=Math.cos(a),sn=Math.sin(a),h=profile(headRows,y),n=profile(neckRows,y),front=Math.max(0,cs),back=(1-cs)*.5,b=smooth(-11+back*6,-8+back*8,y);if(y>=8)b=1;let w=mix(n[0],h[0],b),f=mix(n[1],h[1],b),r=mix(n[2],h[2],b),x=w*sn,z=cs*(cs>=0?f:r);if(cs>0)z+=f*.24*sn*sn*cs+facialRelief(x,y)*smooth(-10,-7,y)*smooth(0,.2,front);
if(y<-7){let u=clamp((y+18)/13),track=.35+u*1.1,scm=.16*G(Math.abs(a)-track,.20)*Math.sin(PI*u);x+=sn*scm;z+=cs*scm;z-=.15*G(x,1.4)*G(y+18,1.1)*front**4;z+=.11*G(y+20.4-.05*x*x,.35)*Math.sin(clamp(Math.abs(x)/12)*PI)*front}return[x,y,z]}
function geometry(pos,idx,uv=null){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);if(uv)g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();g.computeBoundingSphere();allGeometry.push(g);return g}
function addMesh(g,m,group=portrait){let mesh=new THREE.Mesh(g,m);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);return mesh}
const p=[],ind=[],uv=[],NY=420,NA=384;for(let j=0;j<=NY;j++){let y=mix(-27,12.85,j/NY);for(let i=0;i<=NA;i++){let a=mix(-PI,PI,i/NA);p.push(...bodyPoint(y,a));uv.push(i/NA,j/NY)}}for(let j=0;j<NY;j++)for(let i=0;i<NA;i++){let a=j*(NA+1)+i,b=a+NA+1;ind.push(a,a+1,b,a+1,b+1,b)}const headMesh=addMesh(geometry(p,ind,uv),skin);headMesh.name='continuous_head_neck_skin';
function paramSurface(fn,nu=96,nv=24,material=skinDetail,group=portrait){let p=[],ix=[],uv=[];for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){p.push(...fn(i/nu,j/nv));uv.push(i/nu,j/nv)}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){let a=j*(nu+1)+i,b=a+nu+1;ix.push(a,a+1,b,a+1,b+1,b)}return addMesh(geometry(p,ix,uv),material,group)}
function fixFront(mesh){let g=mesh.geometry,n=g.attributes.normal,sum=0;for(let i=0;i<n.count;i++)sum+=n.getZ(i);if(sum<0){const a=g.index.array;for(let i=0;i<a.length;i+=3)[a[i+1],a[i+2]]=[a[i+2],a[i+1]];g.computeVertexNormals()}return mesh}
function eyeEdge(a,s){let c=Math.cos(a),sn=Math.sin(a),lateral=c*s,h=sn>0?.53*(1+.07*lateral):.405*(1-.05*lateral);return[3.1*s+1.42*c,2.1+(sn>0?1:-1)*h*Math.abs(sn)*(.80+.20*Math.abs(sn))+.095*lateral*(1-sn*sn)]}
function globeZ(x,y,s){let dx=(x-3.1*s)/1.16,dy=y-2.1;return 4.87+Math.sqrt(Math.max(.010,1.24**2-dx*dx-dy*dy))}
function eyeLidPoint(a,t,s){let [ex,ey]=eyeEdge(a,s),ox=3.1*s+1.98*Math.cos(a),oy=2.1+1.37*Math.sin(a),x=mix(ex,ox,t),y=mix(ey,oy,t),z0=globeZ(ex,ey,s)+.025,z1=headZ(x,y),en=Math.sin(PI*t);let z=mix(z0,z1,smooth(0,1,t))+.095*en;const contact=globeZ(x,y,s)+.016;z=mix(Math.max(z,contact),z,smooth(.58,.97,t));z-=.05*G(t-.62,.11)*Math.max(0,Math.sin(a));return[x,y,z]}
// Tapered strand batches. Runtime geometry is generated from curve recipes.
class Fibres{constructor(){this.p=[];this.n=[];this.u=[];this.ix=[];this.count=0}add(points,width,sides=3){let base=this.p.length/3;const P=points.map(q=>Array.isArray(q)?V(...q):q);for(let j=0;j<P.length;j++){let tangent=P[Math.min(j+1,P.length-1)].clone().sub(P[Math.max(0,j-1)]).normalize(),n=V(0,0,1).cross(tangent);if(n.lengthSq()<.01)n=V(0,1,0).cross(tangent);n.normalize();let b=tangent.clone().cross(n).normalize(),f=j/(P.length-1),r=width*(.10+.9*Math.pow(1-f,.55));for(let k=0;k<sides;k++){let a=k/sides*PI*2,nn=n.clone().multiplyScalar(Math.cos(a)).addScaledVector(b,Math.sin(a));this.p.push(P[j].x+nn.x*r,P[j].y+nn.y*r,P[j].z+nn.z*r);this.n.push(nn.x,nn.y,nn.z);this.u.push(f,k/sides);if(j<P.length-1){let i=base+j*sides+k,i1=base+j*sides+(k+1)%sides;this.ix.push(i,i1,i+sides,i1,i1+sides,i+sides)}}}this.count++}build(mat,group){let g=geometry(this.p,this.ix,this.u);g.setAttribute('normal',new THREE.Float32BufferAttribute(this.n,3));let mesh=addMesh(g,mat,group);mesh.userData.strands=this.count;return mesh}}
const darkHairMat=new THREE.MeshPhysicalMaterial({color:0x252326,roughness:.34,metalness:.05,clearcoat:.15,clearcoatRoughness:.30,envMapIntensity:.75}),lashMat=new THREE.MeshStandardMaterial({color:0x211b1a,roughness:.48,envMapIntensity:.32});
status('生成眼睑、虹膜与角膜');
const scleraMat=new THREE.MeshPhysicalMaterial({color:0xe1d7ca,roughness:.30,clearcoat:.35,clearcoatRoughness:.13,envMapIntensity:.70});scleraMat.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vEye;').replace('#include <begin_vertex>','#include <begin_vertex>\nvEye=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vEye;');s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
vec2 q=vec2(vEye.x*1.16,vEye.y);float r=length(q),a=atan(q.y,q.x);if(r<.598&&vEye.z>.55)discard;float branch=abs(sin(a*23.+r*5.+sin(a*9.)*1.6));float vein=(1.-smoothstep(.025,.085,branch))*smoothstep(.66,1.10,r)*.20;float pink=smoothstep(.80,1.38,r)*.20;diffuseColor.rgb*=mix(vec3(1),vec3(.85,.40,.36),vein+pink);float lidShade=1.-.14*smoothstep(.05,.8,q.y);diffuseColor.rgb*=lidShade;`)};
const irisMat=new THREE.MeshPhysicalMaterial({color:0xffffff,roughness:.42,metalness:0,clearcoat:.02,envMapIntensity:.55});irisMat.onBeforeCompile=s=>{s.uniforms.uPupil=globals.pupil;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vIris;').replace('#include <begin_vertex>','#include <begin_vertex>\nvIris=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vIris;uniform float uPupil;');s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float r=length(vIris.xy),a=atan(vIris.y,vIris.x);float f=sin(a*174.+sin(a*61.)*1.9+r*24.)*.5+.5;float f2=sin(a*321.+r*31.+sin(a*43.)*3.)*.5+.5;float crypt=sin(a*45.+r*50.)*sin(a*89.-r*19.);float mid=smoothstep(uPupil,.38,r),rim=1.-smoothstep(.50,.592,r);vec3 col=mix(vec3(.19,.12,.04),vec3(.105,.145,.078),mid);col*=.52+f*.50+f2*.25;col+=max(0.,crypt)*.024;col*=.24+.76*rim;if(r<uPupil)col=vec3(.0008,.001,.0013);diffuseColor.rgb=col;`)};
const corneaMat=new THREE.MeshPhysicalMaterial({color:0xffffff,roughness:.045,metalness:0,transmission:.95,thickness:.05,ior:1.376,clearcoat:1,clearcoatRoughness:.035,envMapIntensity:1.0}),wetMat=new THREE.MeshPhysicalMaterial({color:0xb68079,roughness:.16,clearcoat:1,clearcoatRoughness:.06,envMapIntensity:1.1});
for(let s of [-1,1]){let lids=fixFront(paramSurface((u,t)=>eyeLidPoint(u*2*PI,t,s),160,36));lids.name='eyelid_'+s;
let eye=new THREE.Group();eye.position.set(3.1*s,2.1,4.87);portrait.add(eye);eyeParts.push(eye);let white=addMesh(new THREE.SphereGeometry(1.24,96,64),scleraMat,eye);white.scale.x=1.16;white.name='sclera';white.castShadow=false;allGeometry.push(white.geometry);
let iris=fixFront(paramSurface((u,t)=>{let a=u*PI*2,r=.598*t;return[r*Math.cos(a),r*Math.sin(a),1.065-.036*(1-t*t)]},144,28,irisMat,eye));iris.name='iris_pupil';iris.castShadow=false;
let cornea=fixFront(paramSurface((u,t)=>{let a=u*PI*2,r=.635*t;return[r*Math.cos(a),r*Math.sin(a),1.105+.165*(1-t*t)]},128,24,corneaMat,eye));cornea.name='cornea';cornea.castShadow=false;
const wet=new Fibres();for(let upper of [0,1]){let pts=[];for(let i=0;i<=100;i++){let a=(upper?0:PI)+i/100*PI,pt=eyeLidPoint(a,0,s);pt[2]+=.010;pts.push(pt)}wet.add(pts,.016,5)}let wm=wet.build(wetMat,portrait);wm.name='tearline';wm.castShadow=false;
let lacr=addMesh(new THREE.SphereGeometry(.125,24,16),wetMat);lacr.position.set(s*1.69,2.02,5.18);lacr.scale.set(1.0,.60,.58);allGeometry.push(lacr.geometry);
const lash=new Fibres();for(let upper of [true,false]){let n=upper?152:74;for(let i=0;i<n;i++){let a=(upper?0:PI)+(.035+.93*i/(n-1))*PI,[x,y,z]=eyeLidPoint(a,0,s),lateral=Math.cos(a)*s,len=(upper?.32:.13)*(1+.40*lateral)*(.7+rng()*.65),pts=[];for(let j=0;j<=5;j++){let t=j/5;pts.push([x+Math.cos(a)*len*.55*t,y+(upper?1:-1)*len*(.3*t+.7*t*t),z+.10*t+len*.8*Math.sin(t*PI*.63)])}lash.add(pts,upper?.007:.004,3)}}lash.build(lashMat,lashGroup);
const brows=new Fibres();for(let i=0;i<680;i++){let u=rng(),x=s*(1.45+3.65*u),y=4.35+.53*Math.sin(PI*u*.94)+(.5-rng())*(.28*(1-u)+.03),l=.20+rng()*.31,pts=[];for(let j=0;j<=3;j++){let t=j/3,xx=x+s*l*t*(.2+u),yy=y+l*t*(.76-u*.6);pts.push([xx,yy,headZ(xx,yy)+.026+.045*Math.sin(PI*t)])}brows.add(pts,.006*(1-u*.35),3)}brows.build(lashMat,lashGroup)}
// Recessed nasal cavities are geometry, not dark albedo dots.
const cavity=new THREE.MeshStandardMaterial({color:0x23100d,roughness:.78});for(let s of [-1,1]){let hole=addMesh(new THREE.SphereGeometry(1,40,24),cavity);hole.position.set(s*.81,-1.5,headZ(s*.81,-1.5)-.11);hole.scale.set(.294,.145,.20);allGeometry.push(hole.geometry)}
const seam=new Fibres(),pts=[];for(let i=0;i<=100;i++){let x=mix(-2.35,2.35,i/100),y=-4.03-.027*G(x,.25)+.032*G(Math.abs(x)-.7,.5);pts.push([x,y,headZ(x,y)+.006])}seam.add(pts,.017,5);seam.build(new THREE.MeshStandardMaterial({color:0x562d2a,roughness:.70}),portrait);
// Authored auricles. This study does not claim a full internal-organ system.
for(let s of [-1,1]){let ear=fixFront(paramSurface((u,r)=>{let a=u*2*PI,xx=Math.sin(a),yy=Math.cos(a),w=1.05*(1+.17*yy),h=2.2*(1+.18*Math.max(0,yy)),x=s*(6.6+r*w),y=.2+r*h*yy,z=.35+r*.80*xx+.45*Math.exp(-(((r-.84)/.12)**2))-.38*Math.exp(-(((r-.38)/.24)**2));return[x,y,z]},96,32));ear.material.side=THREE.DoubleSide;const helix=new Fibres();let pp=[];for(let i=0;i<=90;i++){let a=i/90*PI*1.65-.40;pp.push([s*(6.65+.77*(.8+.15*Math.cos(a))),.2+1.82*Math.cos(a),.5+.64*Math.sin(a)])}helix.add(pp,.09,6);helix.build(skinDetail,portrait)}
status('按导向曲线生成头发与细绒毛');
function scalp(a,y,lift=.15){const h=profile(headRows,Math.min(12.80,y)),cs=Math.cos(a),sn=Math.sin(a);let x=(h[0]+lift)*sn,z=cs*((cs>0?h[1]:h[2])+lift);if(cs>0)z+=h[1]*.24*sn*sn*cs;return[x,y,z]}
function hairline(a){let c=Math.cos(a);return mix(-2.8,6.2,smooth(-.4,.65,c))+.6*Math.sin(a)**2}
let cap=paramSurface((u,v)=>{let a=(u*2-1)*PI,y=mix(hairline(a),12.83,v);return scalp(a,y,.18)},192,100,darkHairMat,hairGroup);cap.material.side=THREE.DoubleSide;
const strands=new Fibres();for(let i=0;i<6400;i++){let a=mix(-PI,PI,rng()),rootY=mix(hairline(a)+.2,12.45,rng()**.72),endY=hairline(a)-(.25+rng()*.40),phase=Math.floor(a*15)*.71,pts=[];for(let j=0;j<=18;j++){let t=j/18,y=mix(rootY,endY,t),aa=a+.08*Math.sin(t*PI)*Math.sin(phase),point=scalp(aa,y,.20+.04*rng()+.10*Math.sin(t*PI));point[0]+=.017*Math.sin(t*13+phase);point[2]+=.017*Math.cos(t*14+phase);pts.push(point)}strands.add(pts,.010*(.65+rng()*.55),3)}
for(let i=0;i<4300;i++){let x=mix(-5.75,5.75,rng()),u=(x+5.75)/11.5,bundle=Math.floor(u*27),phase=bundle*1.7,root=8.9+rng()*2.4,end=4.95+.38*Math.cos(x*.75)+.2*Math.sin(phase)+rng()*.20,pts=[];for(let j=0;j<=16;j++){let t=j/16,y=mix(root,end,t),xx=x*(.76+.24*t)+.075*Math.sin(t*4+phase),h=profile(headRows,y);xx=clamp(xx,-h[0]*.965,h[0]*.965);pts.push([xx,y,headZ(xx,y)+.21+.10*Math.sin(PI*t)+.05*Math.sin(phase)])}strands.add(pts,.009*(.65+rng()*.60),3)}let hm=strands.build(darkHairMat,hairGroup);hm.name='guide_generated_hair';
const braid=new Fibres();for(let bundle=0;bundle<3;bundle++)for(let i=0;i<350;i++){let rad=Math.sqrt(rng())*.43,ang=rng()*PI*2,phase=2*PI*bundle/3,pts=[];for(let j=0;j<=70;j++){let t=j/70,y=mix(4,-24,t),cx=6.8+1.1*Math.sin(t*PI*.7),cz=-3+4*t,turn=t*PI*13+phase,ax=.73*Math.cos(turn),az=.35*Math.sin(turn*2);pts.push([cx+ax+rad*Math.cos(ang+t*8),y,cz+az+rad*Math.sin(ang+t*8)])}braid.add(pts,.011,3)}braid.build(darkHairMat,hairGroup);
const baby=new Fibres();for(let i=0;i<420;i++){let side=rng()>.5?1:-1,x=side*(5.2+rng()*1.20),y=3.4+rng()*4.0,pts=[],len=.8+rng()*1.8;for(let j=0;j<=8;j++){let t=j/8,xx=x+side*.28*Math.sin(t*3.2),yy=y-len*t;pts.push([xx,yy,headZ(clamp(xx,-6.5,6.5),yy)+.10+.45*Math.sin(PI*t)])}baby.add(pts,.0035,3)}baby.build(darkHairMat,hairGroup);
const fuzz=new Fibres();for(let i=0;i<4200;i++){let x=mix(-6.3,6.3,rng()),y=mix(-8.0,5.6,rng());if(Math.hypot((Math.abs(x)-3.1)/1.94,(y-2.1)/1.36)<1.05||Math.abs(x)<2.5&&Math.abs(y+4)<.9)continue;let z=headZ(x,y);if(!Number.isFinite(z)||z<2)continue;let d=.015,n=V(-(headZ(x+d,y)-headZ(x-d,y))/(2*d),-(headZ(x,y+d)-headZ(x,y-d))/(2*d),1).normalize(),len=.024+rng()*.052,pts=[];for(let j=0;j<=2;j++){let t=j/2;pts.push([x+n.x*len*t+.015*t,y+n.y*len*t-.018*t,z+n.z*len*t+.003])}fuzz.add(pts,.0018,3)}fuzz.build(new THREE.MeshPhysicalMaterial({color:0xbaa58d,roughness:.45,metalness:0,sheen:.7,sheenColor:0xe8cab0,sheenRoughness:.30,envMapIntensity:.65}),fuzzGroup);
let garmentMat=new THREE.MeshPhysicalMaterial({color:0x121418,roughness:.72,sheen:.50,sheenColor:0x4a505d,sheenRoughness:.6}),garment=paramSurface((u,v)=>{let a=(u*2-1)*PI,top=-18.8+1.8*(1-Math.abs(Math.cos(a))),y=mix(-27.05,top,v),b=bodyPoint(y,a);return[b[0]*1.018,y,b[2]*1.035]},160,70,garmentMat);garment.name='plain_garment';
const eyeInspect=new THREE.Group();scene.add(eyeInspect);eyeInspect.visible=false;let white=addMesh(new THREE.SphereGeometry(1.24,96,64),scleraMat,eyeInspect);white.scale.x=1.16;white.castShadow=false;allGeometry.push(white.geometry);fixFront(paramSurface((u,t)=>{let a=u*PI*2,r=.598*t;return[r*Math.cos(a),r*Math.sin(a),1.065-.036*(1-t*t)]},144,28,irisMat,eyeInspect));let inspectedCornea=fixFront(paramSurface((u,t)=>{let a=u*PI*2,r=.635*t;return[r*Math.cos(a),r*Math.sin(a),1.105+.165*(1-t*t)]},128,24,corneaMat,eyeInspect));inspectedCornea.name='cornea';inspectedCornea.castShadow=false;
let frame=0,rotatingLight=false,turning=false,last=performance.now(),fps=0,quality=1.5,target=V(0,.6,1.9),distance=51,yaw=.13,pitch=.035;
const defaults={portrait:{t:[0,.6,1.9],d:51,y:.13,p:.035,title:'PORTRAIT / 连续曲面 · 分区微结构'},eyes:{t:[0,2.05,5.9],d:22,y:.02,p:0,title:'EYES / 眼睑 · 虹膜 · 角膜 · 泪线'},skin:{t:[3.55,-.5,5.7],d:8.6,y:.12,p:.015,title:'MICRO / 毛孔 · 油脂 · 细绒毛'},profile:{t:[0,.7,1],d:51,y:1.15,p:.025,title:'PROFILE / 侧面结构检查'},eye:{t:[0,0,.3],d:7.4,y:.1,p:.08,title:'ANATOMY / 独立眼球 · 实时近似光学'}};let currentView='portrait';
function view(name){let d=defaults[name];if(!d)return;currentView=name;target.set(...d.t);distance=d.d;yaw=d.y;pitch=d.p;portrait.visible=name!=='eye';eyeInspect.visible=name==='eye';$('#viewTitle').textContent=d.title;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));updateCamera()}
function updateCamera(){camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(target)}
function resize(){let w=viewport.clientWidth,h=viewport.clientHeight;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,quality));renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();updateCamera()}window.addEventListener('resize',resize);resize();
let pointer=null;renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,button:e.button};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointerup',()=>pointer=null);renderer.domElement.addEventListener('pointercancel',()=>pointer=null);renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;let dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer.x=e.clientX;pointer.y=e.clientY;if(pointer.button===2||e.shiftKey){target.x-=dx*.0006*distance;target.y+=dy*.0006*distance}else{yaw-=dx*.006;pitch=clamp(pitch+dy*.004,-1.3,1.3)}updateCamera()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance*Math.exp(e.deltaY*.001),currentView==='eye'?2.4:3,125);updateCamera()},{passive:false});renderer.domElement.addEventListener('dblclick',()=>view(currentView));
function bindRange(id,label,min,max,step,uniform,parent){const d=document.createElement('div');d.className='control';d.innerHTML=`<label for="${id}">${label}<output>${uniform.value.toFixed(2)}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${uniform.value}">`;d.querySelector('input').addEventListener('input',e=>{uniform.value=Number(e.target.value);d.querySelector('output').value=uniform.value.toFixed(2)});$(parent).appendChild(d)}
bindRange('pore','毛孔微起伏',0,1.8,.01,globals.pore,'#skinControls');bindRange('oil','表面油脂',0,1,.01,globals.oil,'#skinControls');bindRange('sss','浅层散射近似',0,1,.01,globals.sss,'#skinControls');bindRange('tone','基础色素',0,1,.01,globals.tone,'#skinControls');bindRange('blush','区域血色',0,1.5,.01,globals.blush,'#skinControls');bindRange('freckles','色素斑点',0,1,.01,globals.freckles,'#skinControls');bindRange('micro','微纹理',0,1.8,.01,globals.micro,'#skinControls');bindRange('pupil','瞳孔半径 / cm',.13,.34,.001,globals.pupil,'#eyeControls');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{globals.mode.value=+b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))});
function lighting(name){key.intensity=name==='studio'?2.6:name==='rake'?3.9:1.35;fill.intensity=name==='studio'?.75:name==='rake'?.28:.4;rim.intensity=name==='back'?5:2.7;key.position.set(...(name==='studio'?[-18,24,30]:name==='rake'?[-30,8,10]:[-16,17,-14]));globals.key.value.copy(key.position);document.querySelectorAll('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===name))}document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>lighting(b.dataset.light));
$('#hairToggle').onchange=e=>hairGroup.visible=e.target.checked;$('#lashToggle').onchange=e=>lashGroup.visible=e.target.checked;$('#fuzzToggle').onchange=e=>fuzzGroup.visible=e.target.checked;$('#corneaToggle').onchange=e=>{for(const eye of eyeParts)eye.getObjectByName('cornea').visible=e.target.checked;inspectedCornea.visible=e.target.checked};
function hairColor(silver){darkHairMat.color.set(silver?0x9f9b93:0x252326);darkHairMat.roughness=silver?.37:.34;$('#silverHair').classList.toggle('active',silver);$('#darkHair').classList.toggle('active',!silver)}$('#darkHair').onclick=()=>hairColor(false);$('#silverHair').onclick=()=>hairColor(true);
$('#rotate').onclick=e=>{rotatingLight=!rotatingLight;e.currentTarget.classList.toggle('active',rotatingLight)};$('#turn').onclick=e=>{turning=!turning;e.currentTarget.classList.toggle('active',turning)};$('#home').onclick=()=>view('portrait');$('#quality').onclick=()=>{quality=quality===1.5?2:quality===2?1:1.5;$('#quality').textContent='画质 ×'+quality;resize()};$('#mobileControls').onclick=()=>$('#panel').classList.toggle('open');
$('#export').onclick=()=>{let recipe={schema:'kaopu/skin_atelier@1',version:'r1-candidate',teacher:'BLU1304 Shadowheart, visual reference only',units:'centimetre',seed:746331,parameters:Object.fromEntries(Object.entries(globals).filter(([k])=>k!=='key').map(([k,v])=>[k,v.value])),view:{target:target.toArray(),distance,yaw,pitch},quality,visualAcceptance:false};let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(recipe,null,2)],{type:'application/json'}));a.href=url;a.download='skin-atelier-r1-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
let triangles=0,vertices=0,invalid=0;for(const g of allGeometry){let a=g.attributes.position.array;vertices+=a.length/3;triangles+=(g.index?.count||g.attributes.position.count)/3;for(let v of a)if(!Number.isFinite(v))invalid++}let strandCount=0;portrait.traverse(o=>strandCount+=o.userData.strands||0);if(invalid)throw Error('几何存在无效坐标：'+invalid);
$('#stats').innerHTML=`Three.js r169 · WebGL 2<br>${Math.round(triangles).toLocaleString()} 三角面 / ${strandCount.toLocaleString()} 条生成曲线<br>人物模型下载：0 · 人物图片纹理：0<br>微表面纹理：运行时生成 1024²<br>美术质量：候选，尚未达到原片`;window.__atelier={version:'r1-candidate',renderer,scene,camera,portrait,globals,view,lighting,hairColor,stats:{triangles,vertices,strandCount,invalid,geometry:allGeometry.length},getState:()=>({view:currentView,distance,yaw,pitch,hair:hairGroup.visible,fuzz:fuzzGroup.visible,mode:globals.mode.value}),ready:false};
view('portrait');status('编译材质与检查首帧');renderer.compile(scene,camera);renderer.render(scene,camera);window.__atelier.ready=true;$('#loading').classList.add('hidden');$('#status').textContent='READY';document.body.dataset.version='r1-candidate';
function animate(now){requestAnimationFrame(animate);if(document.hidden)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(turning){yaw+=dt*.16;updateCamera()}if(rotatingLight){const a=now*.00025;key.position.set(Math.sin(a)*30,18,Math.cos(a)*30);globals.key.value.copy(key.position)}renderer.render(scene,camera);fps=mix(fps,dt>0?1/dt:0,.035);if(++frame%30===0)$('#meter').textContent=`WebGL2 · ${Math.round(fps)} FPS · ${renderer.info.render.triangles.toLocaleString()} tris · R1`;window.__atelier.frames=frame}requestAnimationFrame(animate);
} catch(e){fail(e)}
