(async()=>{
const status=document.getElementById('status'),canvas=document.getElementById('c');
try{
if(!('DecompressionStream'in window))throw Error('浏览器过旧：请使用最新版 Chrome / Edge / Safari');
function b64(s){const a=new Uint8Array(atob(s).length),t=atob(s);for(let i=0;i<t.length;i++)a[i]=t.charCodeAt(i);return a}
const ds=new DecompressionStream('gzip'),ab=await new Response(new Blob([b64(window.__BIRD_FORM)]).stream().pipeThrough(ds)).arrayBuffer(),dv=new DataView(ab);let o=0;
const vc=dv.getUint32(o,true);o+=4;const ic=dv.getUint32(o,true);o+=4;const lo=[],hi=[];for(let i=0;i<3;i++){lo.push(dv.getFloat32(o,true));o+=4}for(let i=0;i<3;i++){hi.push(dv.getFloat32(o,true));o+=4}const pl=dv.getUint32(o,true);o+=4,il=dv.getUint32(o,true);o+=4;
function readVar(n){const out=new Uint32Array(n);for(let i=0;i<n;i++){let v=0,s=0,b;do{b=dv.getUint8(o++);v|=(b&127)<<s;s+=7}while(b&128);out[i]=v}return out}
const pv=readVar(vc*3);if(o!==40+pl)throw Error('形态位置载荷长度不匹配');const iv=readVar(ic);if(o!==40+pl+il)throw Error('三角索引载荷长度不匹配');
const pos=new Float32Array(vc*3),prev=[0,0,0];for(let i=0;i<pv.length;i++){const d=(pv[i]>>>1)^-(pv[i]&1),j=i%3;prev[j]+=d;pos[i]=lo[j]+prev[j]/65535*(hi[j]-lo[j])}
const ind=new Uint16Array(ic);let pi=0;for(let i=0;i<ic;i++){pi+=(iv[i]>>>1)^-(iv[i]&1);ind[i]=pi}
const nor=new Float32Array(pos.length);for(let i=0;i<ic;i+=3){const a=ind[i]*3,b=ind[i+1]*3,c=ind[i+2]*3,abx=pos[b]-pos[a],aby=pos[b+1]-pos[a+1],abz=pos[b+2]-pos[a+2],acx=pos[c]-pos[a],acy=pos[c+1]-pos[a+1],acz=pos[c+2]-pos[a+2],x=aby*acz-abz*acy,y=abz*acx-abx*acz,z=abx*acy-aby*acx;for(const k of[a,b,c]){nor[k]+=x;nor[k+1]+=y;nor[k+2]+=z}}for(let i=0;i<nor.length;i+=3){const l=Math.hypot(nor[i],nor[i+1],nor[i+2])||1;nor[i]/=l;nor[i+1]/=l;nor[i+2]/=l}
const lines=new Uint16Array(ic*2);for(let i=0,j=0;i<ic;i+=3){const a=ind[i],b=ind[i+1],c=ind[i+2];lines[j++]=a;lines[j++]=b;lines[j++]=b;lines[j++]=c;lines[j++]=c;lines[j++]=a}
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('浏览器没有可用 WebGL');
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}function program(v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
const prog=program('attribute vec3 p,n;uniform mat4 mvp,m;varying vec3 N;void main(){N=normalize(mat3(m)*n);gl_Position=mvp*vec4(p,1.);}','precision mediump float;varying vec3 N;void main(){vec3 n=normalize(N),l=normalize(vec3(.55,.85,.65));float d=max(dot(n,l),0.);vec3 c=mix(vec3(.43,.48,.50),vec3(.90,.92,.90),.45+d*.55);gl_FragColor=vec4(c,1.);}');
const lineProg=program('attribute vec3 p;uniform mat4 mvp;void main(){gl_Position=mvp*vec4(p,1.);}','precision mediump float;void main(){gl_FragColor=vec4(.10,.50,.67,.42);}');
function buf(data,target=gl.ARRAY_BUFFER){const b=gl.createBuffer();gl.bindBuffer(target,b);gl.bufferData(target,data,gl.STATIC_DRAW);return b}const pb=buf(pos),nb=buf(nor),ib=buf(ind,gl.ELEMENT_ARRAY_BUFFER),lb=buf(lines,gl.ELEMENT_ARRAY_BUFFER);
function I(){const a=new Float32Array(16);a[0]=a[5]=a[10]=a[15]=1;return a}function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function persp(f,a,n,fa){const t=1/Math.tan(f/2),m=new Float32Array(16);m[0]=t/a;m[5]=t;m[10]=(fa+n)/(n-fa);m[11]=-1;m[14]=2*fa*n/(n-fa);return m}function norm(v){const l=Math.hypot(...v)||1;return v.map(x=>x/l)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function look(e,t,u){const z=norm(e.map((x,i)=>x-t[i])),x=norm(cross(u,z)),y=cross(z,x),m=I();m[0]=x[0];m[1]=y[0];m[2]=z[0];m[4]=x[1];m[5]=y[1];m[6]=z[1];m[8]=x[2];m[9]=y[2];m[10]=z[2];m[12]=-x.reduce((s,v,i)=>s+v*e[i],0);m[13]=-y.reduce((s,v,i)=>s+v*e[i],0);m[14]=-z.reduce((s,v,i)=>s+v*e[i],0);return m}
let yaw=.73,pitch=.38,dist=3.2,view='persp',wire=false,down=false,lx=0,ly=0;const target=[0,-.06,.06],views={top:[[0,3.2,0],[0,0,-1]],bottom:[[0,-3.2,0],[0,0,1]],front:[[0,0,3.2],[0,1,0]],back:[[0,0,-3.2],[0,1,0]],side:[[3.2,0,0],[0,1,0]]};
function resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,canvas.clientWidth*d|0),h=Math.max(1,canvas.clientHeight*d|0);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h)}function cam(){const a=canvas.width/canvas.height;if(view==='persp'){const cp=Math.cos(pitch),d=dist*Math.max(1,.92/a),e=[target[0]+d*cp*Math.sin(yaw),target[1]+d*Math.sin(pitch),target[2]+d*cp*Math.cos(yaw)];return[e,look(e,target,[0,1,0]),persp(.56,a,.02,30)]}const[e,u]=views[view];return[e,look(e,target,u),persp(.55,a,.02,30)]}
function attr(p,name,b,size){const l=gl.getAttribLocation(p,name);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,size,gl.FLOAT,false,0,0)}function draw(){resize();gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clearColor(.035,.06,.075,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const[e,v,p]=cam(),m=I(),mvp=mul(p,mul(v,m));gl.useProgram(prog);attr(prog,'p',pb,3);attr(prog,'n',nb,3);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'mvp'),false,mvp);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'m'),false,m);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.drawElements(gl.TRIANGLES,ic,gl.UNSIGNED_SHORT,0);if(wire){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(lineProg);attr(lineProg,'p',pb,3);gl.uniformMatrix4fv(gl.getUniformLocation(lineProg,'mvp'),false,mvp);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,lb);gl.drawElements(gl.LINES,lines.length,gl.UNSIGNED_SHORT,0);gl.disable(gl.BLEND)}requestAnimationFrame(draw)}
canvas.onpointerdown=e=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=()=>down=false;canvas.onpointermove=e=>{if(!down)return;view='persp';yaw+=(e.clientX-lx)*.008;pitch=Math.max(-1.35,Math.min(1.35,pitch+(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY};canvas.onwheel=e=>{e.preventDefault();view='persp';dist=Math.max(1.7,Math.min(6,dist*Math.exp(e.deltaY*.001)))};
document.getElementById('views').onclick=e=>{const b=e.target.closest('button');if(!b)return;view=b.dataset.v;document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x===b))};document.getElementById('wire').onclick=e=>{wire=!wire;e.target.textContent='线框：'+(wire?'开':'关')};document.getElementById('reset').onclick=()=>{yaw=.73;pitch=.38;dist=3.2;view='persp';document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x.dataset.v==='persp'))};document.getElementById('menu').onclick=()=>document.getElementById('panel').classList.toggle('open');
status.textContent=`形态载入完成｜${vc.toLocaleString()} 顶点｜${(ic/3).toLocaleString()} 三角面`;requestAnimationFrame(draw);
}catch(err){status.textContent='打开失败：'+err.message;status.style.color='#ff9e99';console.error(err)}
})();
