const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../../..'),out='/tmp/et03-evidence';fs.mkdirSync(out,{recursive:true});
const report={version:'ET03',sourceCommit:process.env.GITHUB_SHA,publicCommit:process.env.ET03_PUBLIC_SHA||null,errors:[],consoleErrors:[],failedRequests:[],checks:{}};
let browser,server,page;
(async()=>{
 let url=process.env.ET03_PUBLIC_SHA?'https://htmlpreview.github.io/?https://raw.githubusercontent.com/haihao0307/Humanoid-Rig-Lab-Next/'+process.env.ET03_PUBLIC_SHA+'/skin-quality-lab/emily-transfer/preview.html':null;
 if(!url){server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}const ext=path.extname(f);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary'})[ext]||'application/octet-stream');fs.createReadStream(f).on('error',()=>res.writeHead(404).end()).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/skin-quality-lab/emily-transfer/index.html';}
 report.url=url;browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.setDefaultTimeout(90000);
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__SKIN_LAB__?.state.ready&&window.__EYES__,{},{timeout:240000});
 await page.evaluate(()=>{window.__EYE_QA_FREEZE__=true;__EYES__.set({autoBlink:false,autoPupil:false,pupilMM:3.4,manualBlink:-1});__EYES__.step(0,true);});
 assert.equal(await page.evaluate(()=>__SKIN_LAB__.state.version),'emily-transfer/3.0.0');
 async function shot(name){await page.evaluate(()=>__SKIN_LAB__.render());await page.screenshot({path:out+'/'+name+'.png'});}
 await shot('01-portrait');await page.click('[data-camera="eyes"]');await page.evaluate(()=>__EYES__.step(0,true));await shot('02-eyes');
 report.checks.initial=await page.evaluate(()=>__EYES__.info());
 await page.evaluate(()=>__EYES__.set({manualBlink:.5}));await shot('03-halfblink');await page.evaluate(()=>__EYES__.set({manualBlink:1}));await shot('04-closed');
 await page.evaluate(()=>{__EYES__.set({manualBlink:-1});__EYES__.setTarget([.15,.1,.8]);__EYES__.step(0,true)});await shot('05-look-right');
 await page.click('[data-camera="iris"]');await page.evaluate(()=>{__EYES__.setMode('camera');__EYES__.step(0,true)});await shot('06-iris');
 const sweep=await page.evaluate(()=>{let data=[];for(const b of [0,.25,.5,.75,1])for(const x of [-.16,0,.16])for(const y of [-.04,.069,.17]){__EYES__.set({manualBlink:b});__EYES__.setTarget([x,y,.8]);__EYES__.step(0,true);let i=__EYES__.info();data.push({b,x,y,lock:i.lockErrorDegrees,contact:i.contact});}return data;});report.checks.contactSweep=sweep;assert(sweep.every(q=>q.contact.every(c=>c.penetratingTestVertices===0)),'Sampled lid penetration');
 await page.evaluate(()=>{__EYES__.set({manualBlink:-1,squint:0});__EYES__.setMode('camera');__EYES__.step(0,true)});
 await page.click('[data-camera="portrait"]');await page.selectOption('#eyeMode','pointer');await page.mouse.move(400,460);await page.evaluate(()=>__EYES__.step(0,true));const before=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(700,460);await page.evaluate(()=>__EYES__.step(0,true));assert.notDeepEqual(await page.evaluate(()=>__EYES__.info().target),before);await page.click('#lockEye');await page.evaluate(()=>__EYES__.step(0,true));const locked=await page.evaluate(()=>__EYES__.info().target);await page.mouse.move(260,340);await page.evaluate(()=>__EYES__.step(0,true));assert.deepEqual(await page.evaluate(()=>__EYES__.info().target),locked);report.checks.pointerAndLock=true;
 await page.click('#reset');await page.evaluate(()=>{__EYES__.set({autoBlink:false,autoPupil:false,manualBlink:-1});__EYES__.step(0,true)});await page.setViewportSize({width:390,height:844});await page.click('[data-camera="portrait"]');await page.evaluate(()=>__EYES__.step(0,true));await shot('07-mobile');await page.click('#mobileToggle');assert(await page.locator('.side').isVisible());await page.click('#mobileToggle');report.checks.mobileViewportOnly=true;
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.failedRequests,[]);report.passed=true;
 fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log('ET03_QA_PASS',JSON.stringify({url,public:!!report.publicCommit,checks:Object.keys(report.checks)}));
})().catch(async e=>{report.passed=false;report.failure=String(e.stack);console.error(e);fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(page)await page.screenshot({path:out+'/failure.png',timeout:60000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
